### PR TITLE
#4953: iOS absolute paths are dynamic, do not load them from config

### PR DESCRIPTION
**Pull request by RomainQuidet**

### CODE REVIEW

**Comment by twinaphex** [comment]
Are you absolutely sure this has no unintended consequences? Did you test most of the relevant related usecases?

**Comment by RomainQuidet** [comment]
Yes I'm testing the cores load, games working, etc. All assets are correctly used by the menu, you can choose the overlays to play etc.

**Comment by RomainQuidet** [comment]
As far as I understand the configuration settings, it is created by default then overided by the file. User on iOS have no way or usage to change paths for data. It works perfectly on my device now.

**Comment by fr500** [comment]
You are preventing from loading every path though...
Saves, States, System, Content, Screenshot path are user data and they should be user tweakable

**Comment by RomainQuidet** [comment]
tweakable on iOS ? Not seen that.
Anyway if you prefer to keep the files recorded in the config file, you need to update the system to get them relative to the app Document directory. Absolute path must not be recorded.
Thanks for your help !

**Comment by iOS4all** [comment]
Please can anyone of you give me a working version of retroarch to my jailbroken device?
Thanks

**Comment by fr500** [comment]
@RomainQuidet I mean, the user may change them
So now there is no public documents area that all apps can read? everything is internal to the application?

**Comment by RomainQuidet** [comment]
@fr500 There's 2 cases.
1 - if you are jailbroken on iOS, the app can access all system file according to access rights.
2 - if not jailbroken, the app can only access sandbox, where main documents should go to the Documents directory. This directory is accessible via iTunes to add games etc. 
By default, retroarch app creates all its directories architecture in Documents/RetroArch, which is fine.
Users can add games in Documents directory via iTunes. I see no use case of moving saves, states etc directories away from where they are create. We are on a mobile here, not on our computer. 
The jailbroken case is quite annoying as people start again to move everything around, but jailbreak on iOS tends to be not anymore a popular (and a lot of people are not able to jailbreak).

I really think that iOS app should not differentiate jailbroken / non jailbroken. If you provide a clean .ipa to be signed with impactor or developers it would be perfect. For jailbreak, to ease the process you can provide a .deb file that behave exactly as the app.

If you really want the user to be free to choose the directories on iOS, no problem. As I say we must make the settings relative to the sandbox Documents directory as the absolute path is changing at each app start.

**Comment by fr500** [comment]
I fully agree with you. The behavior should be uniform.
So for now we should consider the documents dir the "root" and users should be able to organize their files there in any way they see fit.

This is exactly why I say we **should be able to save settings**.
The idea would be to provide sane defaults but allow flexiblity, so we should be able to save the dirs. At least these:

- savestates
- savefiles
- screenshots
- system

All this data belongs to the user.

Not saving the rest should be ok (core, info, playlist, shader, cfg, etc)

I guess we need a way to separate  "retroarch datta" and "user data"

**Comment by RomainQuidet** [comment]
cores directory is already an issue on iOS as it is hardcoded to be inside the app bundle (cores must be signed as the app), but users can download them and change the directory ... which will break the app. iOS users should not be able to update cores alone. It must be a complete app update process.
Anyway I can close this PR and try to make another proposal for this file system architecture on iOS.

**Comment by fr500** [comment]
yes, I understand your point and it's all valid, just trying to come up with a pleasant solution for everyone.
What I recommend is to set the userdata dirs in platform_darwin.c

The sandbox dir is always the same? you mentioned the fullpath changes with updates?

**Comment by RomainQuidet** [comment]
I also agree with you :). 
iOS app provides a method to get the app's Documents directory path, which might go the the configuration.c file as global to use later during the app life cycle.
From an iOS developer point of view, we never work with absolute file paths, we always work with relative file paths from Documents directory (and other allowed directories as cache, temp etc.).

**Pull request closed without merging**
