### PR TITLE
let it snow

### PR DESCRIPTION
**Pull request by fr500**
## Description

Adds a new snow shader to the pipeline, it's very slow though, with 50 snowflakes it's too slow @ 4k on a GTX970

### CODE REVIEW

**Comment by hyarsan** [comment]
Thinking about it... can we have an fireworks pipeline? It would not only look nice, but would be a great way to celebrate new year!

**Comment by fr500** [comment]
This one looks simple enough to port
https://www.shadertoy.com/view/lscGRl

**Comment by hyarsan** [comment]
How did you get the bottom snow to work in your tweet? I don't see the snow at the bottom? https://twitter.com/radius___/status/937113157029580800/photo/1

looks like a bug

**Comment by hyarsan** [comment]
Wow, those fireworks are beautiful!

**Pull request merged**
