### PR TITLE
Fixes #2026: Make DBus dependency 'auto' to enable it by default

### LINKED ISSUE #2026: Linux screensaver suspend malfunctioning
My experience is that that the Linux screensaver suspension doesn't work properly.

**Observed behavior:** Display is prevented from blanking, but the screen still fades to black and is locked after 10 minutes when running Retroarch. Additionally, after quiting Retroarch, display blanking is still disabled (I have to run `xset dpms 300` to restore).

**Expected behavior:** Display blanking / screen locking is "suspended" (poor choice of term there) while I am running Retroarch, and is restored when I quit Retroarch.

**Setup:** Retroarch (git) under Gnome 3 Shell on Arch Linux with Gnome set to suspend the display and lock the screen after 5 minutes of inactivity.

More investigation is needed. It's possible that this is a bug in some other package such as Gnome Screensaver itself. I'll follow up with more info and hopefully a recommendation.

## Related issues

 * #30, #33
 * #1349

### PR DESCRIPTION
**Pull request by nguillaumin**
Rationale copied from #2026:

This DBus issue solves a real problem for users, and while I understand
some people may not want the DBus dependency (but in that case, why have
the lib on your system at all?) and agree it should be disablable, I
think it should be enabled by default.
One could argue other people doesn't want `xdg-screensaver` for various
reasons, but that doesn't mean it should be disabled by default.

I don't think we can really say one method is better over the other,
there are arguments for and against both, so I believe doing both by
default is a reasonable compromise.

### CODE REVIEW

**Comment by orbea** [comment]
My argument stands, there are far less users that will benefit from dbus support than there are those that don't require an extra dependency. Most users will have dbus by default on their distros and removing it is not exactly easy. This should be only enabled for those that need it, not for everyone when it will just become another thing that could go wrong.

**Comment by nguillaumin** [comment]
One could say the opposite, most users run with a desktop environment and as such will benefit from the DBus method rather than a possibly buggy `xdg-screensaver` (which at least on my system causes other issues such as not resuming the screensaver properly).

I'm just saying that we can't really make any claims without numbers or asking users to vote, hence the compromise which I believe reasonable to have both by default (which I thought [you were ok with](https://github.com/libretro/RetroArch/pull/3588#issuecomment-247081903)?)

**Comment by nguillaumin** [comment]
I shall also add that `xdg-screensaver` uses DBus under the hood on Gnome and KDE > 3 I think, so it's kind of there anyway :wink:

**Comment by orbea** [comment]
I do not like `auto`, however I will live with it if that is what the community decides. When this was discussed in irc earlier at least one other user agreed that `no` was a good default. The problem is that `auto` in the case of dbus is more or less synonymous with `yes` given dbus's wide prevalence.

Additionally that argument is backwards, dbus is an abstract and often unreliable program while xdg-screensaver is  mature, not subject to any changes and will continue to just work. Most desktop environments seem to support it including gnome3 on at least some distros. Your issue reportedly only affects a subset of gnome3 users and the default working behavior for everyone else should not change for just you.

In the future when the above has changed this can be re-investigated, but until this dbus code is proven to be solid over a long period of time for multiple users it should remain off by default because at best it really adds nothing for most people.

**Comment by orbea** [comment]
I should add that xdg-screensaver is a shell script, so that even if it can use dbus in some environments, it does so with the benefits of not directly adding dbus as a dependency to RetroArch.

**Comment by nguillaumin** [comment]
If I could make `xdg-screensaver` work I would, so far I've tried [to investigate](https://bbs.archlinux.org/viewtopic.php?id=216930) what's wrong with it but without success. It also seems to affect other systems, see https://bugzilla.redhat.com/show_bug.cgi?id=665918 . My suspicion so far is that it's using some deprecated DBus interface (`org.gnome.SessionManager`) on Gnome that doesn't work on Arch (and Fedora it seems) for some reason.

I think your argument can also be reversed, DBus is the official, proven method to interact with the major desktop environments and `xdg-screensaver` could be considered a dodgy shell script based on heuristics (I think its `screensaver_freedesktop()` method is even flawed by design because it looses the connection to the bus when the script exists, so the inhibition will be lost). As said it even uses DBus under the hood in some cases, so there must be some truth to using it... However note that I'm not advocating for disabling `xdg-screensaver`, I'm for the compromise here.

> proven to be solid over a long period of time for multiple users

It's kind of a chicken and egg problem, if it's not enabled by default it will not be used and so won't be proven solid. I think the code is relatively minimal, easy to understand, so there's little risk in enabling it by default, and it will fix an actual issue for users.

> adding dbus as a dependency to RetroArch.

I guess I'm still unclear why just the mere fact of having the dependency is a problem in practice (Assuming the library is available on the system, which the configure script detects)?

**Comment by nguillaumin** [comment]
Out of curiosity which distro / desktop environment are you using?

**Comment by nguillaumin** [comment]
Hm, I think I found the issue with `xdg-screensaver`: It relies on `xprop`, which is not installed on my system (not installed on Arch by default, hence probably why it affects Arch users. Not sure about Fedora).

Problem is that it doesn't complain `xprop` is missing, it even seems to have some code to deal with that and fall back, but obviously it doesn't work.

I'll report the bug to xdg-utils, nevertheless I think that the DBus method is more reliable in most cases and should be enabled by default if DBus is available.

**Comment by hadess** [comment]
> Additionally that argument is backwards, dbus is an abstract and often unreliable program while xdg-screensaver is mature, not subject to any changes and will continue to just work.

xdg-screensaver is an unmaintained, unmaintainable and unreliable piece of garbage, which we (or I rather) tried to kill. What's the point of not wanting D-Bus when that horrible shell script will go through hoops to eventually call it.

There's now a standard D-Bus interface, which is implemented by GNOME and KDE, probably Cinnamon and MATE too (or at least implementable by them):
https://people.freedesktop.org/~hadess/idle-inhibition-spec/index.html

I don't understand why you wouldn't want to use D-Bus[1], but if that's a problem, you could dlopen() the dbus-glib library, like SDL does.

[1]: It's basically a Unix socket with type safety on top

**Comment by orbea** [comment]
"Hm, I think I found the issue with xdg-screensaver: It relies on xprop, which is not installed on my system (not installed on Arch by default, hence probably why it affects Arch users."

So this basically fixes nothing at the cost of an additional dependency, that does not seem good. It should certainly be `no` by default now, possible reverted entirely.

"I guess I'm still unclear why just the mere fact of having the dependency is a problem in practice (Assuming the library is available on the system, which the configure script detects)?"

I've always been under the impression that RA tries to link to bring in as few dependencies as possible which is a good thing.

**Comment by nguillaumin** [comment]
> xdg-screensaver is an unmaintained, unmaintainable and unreliable piece of garbage

Having to dig into it for this bug, I couldn't agree more. And we're not the only one thinking this, if you Google for screensaver suspend issues on Linux, often the underlying culprit is `xdg-screensaver` (for example with VLC, Mplayer, even Chrome when watching movies). There's a reason why these projects all chose to go with a DBus implementation instead.

> fixes nothing at the cost of an additional dependency, that does not seem good

See just above, I believe the DBus method is actually cleaner and more reliable than the xdg-screensaver one. Did you know that this shell script contained an inline Perl script, which is then spawn as a separate process in the background to monitor a file every 10s? I personally find that terrible, so I'd like for the cleaner DBus method to be available, but I don't mind if others still want to use `xdg-screensaver` (at their peril!).

**Pull request merged**
