### PR TITLE
Fix DRM/KMS keyboard handling

### PR DESCRIPTION
**Pull request by casdevel**
This is a fix for issue that is reported by @Kivutar [here](https://github.com/libretro/RetroArch/issues/4775#issuecomment-306613691).

It adds back xkb handling with additional gfx context identity check so we don't get duplicate keyboard handling when not using kms context. It can be easily extended if some other gfx context driver also depends on handle_xkb function.

### CODE REVIEW

**Comment by Kivutar** [comment]
Very strange, after merging this, the problem is still there on mainline RA.
On your RA, it is fixed however.

**Comment by casdevel** [comment]
I uploaded my local branch (it's not changed since merge) so you can double check.

**Comment by Kivutar** [comment]
Sorry, I don't find it, is it still online somewhere?

**Comment by casdevel** [comment]
No, it's gone. I did some cleanups with my both online and local repositories.

I'm not familiar with DRM/KMS, but if it's necessary I can try to setup that on my machine and than try to fix that but that's probably gonna take some time.

Just looking at the code, it should behave like before the changes (if udev input is used in combination with KMS gfx context). For any other gfx context, xkb code is not used.

**Comment by casdevel** [comment]
@Kivutar Try [https://github.com/casdevel/RetroArch/tree/udev-drm](https://github.com/casdevel/RetroArch/tree/udev-drm).

With this code I get duplicate characters in search dialog (same as before) so xkb handling is definitely used.

**Comment by Kivutar** [comment]
With your https://github.com/casdevel/RetroArch/tree/udev-drm I get:

 - Still the same bug in DRM/KMS: no keyboard typing possible
 - No duplicate characters at all for me, either in X11 or DRM/KMS
 - It fixes localisation of the keyboard in X11, I can really use my azerty now

It's sad that we lost your old branch, this one was perfectly working.

**Comment by casdevel** [comment]
I guess I'll have to set-up DRM/KMS on my machine.

**Comment by casdevel** [comment]
What has priority, this or touchpad issue?

**Comment by Kivutar** [comment]
I'd say this. Thanks for your time spent on these issues.

**Comment by casdevel** [comment]
@Kivutar Unfortunately DRM video driver don't work on my both desktop and laptop machine. I get init errors, probably hardware/driver don't support this, so we have to do this the hard way (maybe).

First we must make sure that events are reaching udev input driver. I added some debug logging to driver which should tell as that. Code is at [https://github.com/casdevel/RetroArch/tree/udev-dbg](https://github.com/casdevel/RetroArch/tree/udev-dbg).

Near the end of the log will be four lines that starts with RetroArch [INFO] :: [UDEV DBG].

**Comment by twinaphex** [comment]
Hi there @kivutar,

could you try what casdevel is explaining please so we can get to the root of this issue?

**Comment by Kivutar** [comment]
The problem is fixed for me on https://github.com/casdevel/RetroArch/tree/udev-dbg.

And here is the log:

    RetroArch [INFO] :: [UDEV DBG]: received 628 pool events (55 input events).
    RetroArch [INFO] :: [UDEV DBG]: received 165 keyboard events (55 passed to "handle_xkb", 28 handled by "handle_xkb", 27 passed to "input_keyboard_event").
    RetroArch [INFO] :: [UDEV DBG]: received 0 mouse events (0 move/wheel events, 0 button events).
    RetroArch [INFO] :: [UDEV DBG]: received 0 touchpad events (0 move/wheel events, 0 button events).

**Comment by casdevel** [comment]
Then RetroArch master branch should also work.

You can also check touchpad with this code.

**Comment by casdevel** [comment]
If xkbcommon is available then something simple as [https://github.com/casdevel/RetroArch/tree/udev](https://github.com/casdevel/RetroArch/tree/udev) may help (if KMS check is no longer relevant).

**Pull request merged**
