### PR TITLE
Revert Qt5 implementation

### PR DESCRIPTION
**Pull request by viachaslavic**
Revert of the old API for compilation with Qt5. Only explicit transformations remained in common.

Solve https://github.com/libretro/RetroArch/pull/17199#issuecomment-2496227805

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
I still get the input issue with this. This is a serious issue.

**Comment by viachaslavic** [comment]
This is strange This PR completely return the previous implementation of Qt5.

**Comment by LibretroAdmin** [comment]
I'll do a make clean and make completely from scratch to rule out any shenanigans.

**Comment by LibretroAdmin** [comment]
Unfortunately it still happens.

**Comment by LibretroAdmin** [comment]
OK so this issue happened before your PRs as well.

So instead of reverting maybe you can fix the fundamental issue since we were really lacking a Qt developer. Our previous Qt developer left years ago.

How to reproduce it:
1 - Popup the UI companion interface by pressing F5
2 - Inside the left panel ' Playlists', scroll up and down with your mouse scrollwheel. Note how the same scrolling behavior will also happen in the RetroArch main window.

What should happen instead is when the mouse is interacting with the 'UI companion driver' window, that the main window becomes unfocused and no longer responds to input.

**Comment by viachaslavic** [comment]
There is no radical reversion here, qt6 implementation still remains. If this issue you are having occurs on yesterday's and previous commits, please create a new issue with a description of the environment. I can't reproduce it yet (probably through the tile VM)

**Comment by LibretroAdmin** [comment]
Hi there, just wanted to let you know we are following a lead on what could be the regression. So for now I just wanted to inform you so you don't waste a good amount of time trying to dig for a solution. So just hold off for now, I will let you know if we cannot come up with anything.

**Comment by LibretroAdmin** [comment]
Yes I can confirm the issue only happens with raw.

**Comment by LibretroAdmin** [comment]
Anyway we can re-revert this since the issue was not related to this.

**Pull request merged**
