### PR TITLE
Rewrite German translation (part 1)

### PR DESCRIPTION
**Pull request by rootfather**
In the last couple of weeks, I started to rewrite the German translation of the RetroArch GUI. I mainly did this because the translation was quite old and incomplete and lots of labels changed since then.

This is the first part where I completed the msg_hash_de.c file. This basically adds all help texts. Next step is to update msg_hash_de.h as well to make it future-proof too.

@CoalaJoe, sorry if this reverts some of the changes you made in the last weeks. After I reworked msg_hash_de.h, I will re-apply your changes. If I finished this project, I think it will be a great start for future updates - maybe we can work together then?

### CODE REVIEW

**Comment by Alcaro** [comment]
>\+// Is this still needed in current RetroArch versions or is
>\+// this an old left-over?

Probably leftover from before we switched the sources to UTF-8. Should be safe to remove.

**Comment by CoalaJoe** [comment]
@rootfather Nice work!
Well, I primarily worked on the .h file. And I checked for the labels in other translation-files and added them to the german-file, but in alphabetical order.

**Comment by rootfather** [comment]
@CoalaJoe, the thing is that lots of labels changed in the .h file too, therefore I suggest that I rewrite that file too and then re-apply your changes.

**Comment by CoalaJoe** [comment]
@rootfather 
Why not just merge?
Maybe we need some definitions on how to translate. Things like "Höflichkeitsform" and direct and in-direct sentences.

**Comment by rootfather** [comment]
I haven't thought about direct and in-direct senteces yet. About the Höflichkeitsform, I primarily wanted to use "Sie", but then I noticed that you use "Du", so I went with that.

**Comment by CoalaJoe** [comment]
@rootfather In my previous job I wrote alot of usermanuals. We took a more indirect language and used "man" as the way of addressing the person, but I don't think it would quiet suit the purpose a GUI.

**Pull request merged**
