### PR TITLE
Add support for Rumble when increase or decrease by the rumble value

### PR DESCRIPTION
**Pull request by alondero**
## Description

I wanted to be able to create a rumble in Tetris only when there was a Tetris (ie. the line counter increases by 4), therefore I've added options in the cheat manager which will check for whether the memory value has increased or decreased by the value specified in the Rumble Value.
I'm unsure if I've tracked all the places that I would need to change to fully complete this, so please let me know if I've missed somewhere.

## Related Issues

None

## Reviewers

Anyone?

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi, sounds like a good idea. You agree with this @RetroSven ?

I assume you would want me to add menu entries for these new options as well?I could do that.

**Comment by RetroSven** [comment]
Yup, sounds good - glad to see people are already off and running with this stuff.

**Comment by alondero** [comment]
@RetroSven loving the ability to create a new experience for retro games! Is there a wiki page for this stuff if not happy to help get that set up (I know there is a blog post but some things took a while to understand).

**Comment by RetroSven** [comment]
@alondero if you have suggestions on how to update the blog post language please feel free.  I'm probably too close to the subject to know what might be problematic from a descriptive POV.  

@twinaphex you mentioned something about there being no documentation about this - please point to the repo/dir that needs to have this documentation added.  I had thought the blog post would just be copy/pasted into wherever it needs to go.

**Comment by twinaphex** [comment]
Hi @RetroSven,

the repo in question is docs -

https://github.com/libretro/docs

All changes made to this repo you can see in real-time at -

http://docs.libretro.com/

**Comment by RetroSven** [comment]
@twinaphex  I meant more like where in the docs do you want this?

**Comment by twinaphex** [comment]
@RetroSven Up to you as far as I'm concerned.

**Comment by alondero** [comment]
@RetroSven just testing this with the latest build and I can't see the options that I added, I suspect that I missed some code somewhere to plug this in. I've searched the code for references of the other types but can't spot anything else... Any ideas?
Also, memory searching doesn't seem to work correctly on the Gambatte core, do you have a list somewhere of which cores it works with and what it doesn't? For example, start Mario Land and start cheat search for an 8 bit number (coins), collect a coin, find values = 1, collect another coin, find values = 2 and so on until typically this results in 0 matches... I've tried with the Big Endian option too.

**Comment by RetroSven** [comment]
@alondero if you grab the latest nightlies of RA and gambatte you should be able to make codes for these extra 63 bytes now

**Pull request merged**
