### PR TITLE
Update deps/libz to 1.2.11.

### PR DESCRIPTION
**Pull request by orbea**
## Description

From what I can tell `deps/libz/` was last updated in the repo a long time ago and has been hacked many times since. This PR will replace `deps/libz/` with the latest release (`1.2.11`) from Jan 15, 2017. 

To keep the `CXX_BUILD` working I added two commits on top of this to fix many errors and then a few `-Wdeprecated-register` warnings. It does not seem upstream zlib is being maintained and PRs are not being merged so I don't think there is much value in trying to get this merged upstream.

Edit: This part of the diff is revealing for the change in version.
```
-  version 1.2.8, April 28th, 2013
+  version 1.2.11, January 15th, 2017
 
-  Copyright (C) 1995-2013 Jean-loup Gailly and Mark Adler
+  Copyright (C) 1995-2017 Jean-loup Gailly and Mark Adler
```

## Related Issues

Besides updating zlib to a much more recent version this will fix the following warning with clang.
```
deps/libz/inflate.c:1484:16: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
           return -1L << 16;
                  ~~~ ^
1 warning generated.
```

## Reviewers

Wait for travis.

I am not sure what problems this will cause for console builds or not, I'll have to use the buildbot to test those builds.

### CODE REVIEW

**Comment by twinaphex** [comment]
This cannot be just done willy nilly. It would first have to be checked against many console platforms for portability. 

I really recommend against just mindlessly updating this to latest, and first making sure it compiles for ALL of our targets before we proceed with this.

**Comment by orbea** [comment]
@twinaphex I totally realize that, but unless you can help find people to test this the reality is that this will either need the buildbot to test or will never be tested.

**Comment by twinaphex** [comment]
I'd argue this is not important right now and we have bigger fish to fry right now. This can wait for now.

**Comment by orbea** [comment]
I personally think that having reproducible dependencies is pretty important, but its your call.

**Comment by twinaphex** [comment]
I want to revisit this but it has to be after the 1.7.8 release, we have a lot on our plate right now. Please be understanding of this.

**Comment by orbea** [comment]
> I want to revisit this but it has to be after the 1.7.8 release

Sure, I'll leave this open for now and occasionally rebase to make sure it still works.

**Comment by RobLoach** [comment]
For what it's worth, this compiled and ran correctly for me. I was able to run games that were compressed in a .zip file.

Screenshot at 2019-07-25 13-20-46

**Comment by orbea** [comment]
I think the remaining issues are.

* New xcode warnings.
* Testing consoles and other platforms.
* Updating and testing cores that require zlib.

As has already been mentioned this will have to wait until after the `v1.7.8` release.

**Pull request closed without merging**
