### PR TITLE
Menu refactors (pt. 1)

### PR DESCRIPTION
**Pull request by twinaphex**
These are a couple of crucial menu refactors so that we can start cleaning up some of the menu drivers (in terms of size, reused functionality), etc.

It does the following:

- Remove unused Stripes menu driver - will just get in the way of further refactoring at this point, and it was essentially a dead and nonfunctional menu driver
- (MaterialUI) Remove/inline materialui_render_switch_icon and reduce two cases in a switch to one
- (MaterialUI) materialui_draw_thumbnail - this sanity check was entirely useless - scale_factor is always hardcoded at 1.00 in all calls

So why am I doing all this? For a number of reasons (and this is all leading up to some of the bigger changes that would appear in future PRs):

- Right now XMB, MaterialUI and Ozone all have their own 'draw_icon' functions. These are nearly 99% the same except for usually one small deviation. We want to basically make these functionally identical across the board and then just use one instead of all this duplication.
- The gfx display driver right now is grossly inefficient. For every quad it has to render (`gfx_display_draw_quad`), it does one draw call. This translates into multiple blending calls, a glDrawArray call (or some equivalent), etc. For every polygon (`gfx_display_draw_polygon`), it does the same. Sometimes it even has to perform matrix calculations unnecessarily for each call to `gfx_display_draw_texture_slice` or some other function. This is especially a problem given that `gfx_display_draw_texture_slice` can be called three times in a row in Ozone for instance, and then we are basically doing these matrix calculations three times in a row when we could have just done it once outside and then pass the matrix around to the `gfx_display_draw_texture_slice` function. Put all together, it's all grossly inefficient, and we need to carefully start working towards being able to batch all these calls and being able to do it with just a couple of 'draw' calls (so instead of blending begin, glDrawArrays, blending end being done like 50 times in a row for some small rectangles and stuff being drawn, instead you'd end up with no more than 5 or 10 times these calls being done). The only way to get there is to work towards it in baby steps.
- Further onto that point, these higher abstractions like 'draw_icon' need to fall by the wayside later on. We need to start thinking lower-level in terms of `gfx_display_draw_quad`, `gfx_display_draw_vertex`, etc. All of this will allow us to more easily batch all this when we actually have to send this data over to the graphics API (i.e. the gfx_display layer). A high level of abstraction like 'texture', 'icon', 'background' is not going to help lead to more efficient draw calls.

So, these are all my future plans for this. This is just merely a very small stepping stone in terms of making the road to get there possible. Hopefully with this context, it's made apparent why I am doing this.

### CODE REVIEW

**Comment by twinaphex** [comment]
I'd like @jdgleaver to review this on Tuesday if possible.

**Comment by hizzlekizzle** [comment]
Good idea removing Stripes.

**Comment by jdgleaver** [comment]
> I'd like @jdgleaver to review this on Tuesday if possible.

Duly noted. I have already committed to reviewing another PR first, but I think this should be manageable.

**Comment by clort81** [comment]
State of the patch on my building right now:
```
make 
CC input/drivers/linuxraw_input.c
CC input/common/linux_common.c
CC input/drivers_joypad/linuxraw_joypad.c
CC frontend/drivers/platform_unix.c
CC version_git.c
CC frontend/frontend_driver.c
make: *** No rule to make target 'menu/widgets/menu_dialog.h', needed by 'obj-unix/release/retroarch.o'.  Stop.
```
Configured with:
```
 ./configure --enable-caca --enable-sixel --disable-dsound --enable-sdl --disable-sdl2 --enable-opengles3 --disable-xrandr --enable-libusb --disable-systemd --enable-udev --enable-threads --enable-thread_storage --enable-ffmpeg --enable-ssa --enable-dylib --enable-networking --disable-d3d8 --disable-d3d9 --disable-d3d10 --disable-d3d11 --disable-d3d12 --disable-d3dx --enable-opengl --enable-x11 --enable-xrandr --enable-xinerama --enable-kms --enable-builtinzlib --enable-alsa --disable-oss --enable-xvideo --enable-v4l2 --enable-mmap --enable-xshm --enable-videoprocessor --disable-pulse --disable-jack
```
Perhaps the unusual configure exposes this.  Just a heads-up. Cheers.

**Comment by twinaphex** [comment]
@clort81 Does that happen on master too? If so, I might want to move your particular issue over to another issue so as not to detract from this PR, thanks.

**Comment by gouchi** [comment]
I confirm this PR build fine with master.

@clort81 You should open another issue for your issue. I tried to compile with your options and indeed I have an issue but another from the one you mentioned. First try to do a `make clean`.

**Comment by jdgleaver** [comment]
@twinaphex I'm afraid there are a number of issues with this PR.

----------

Let me start with the small (essentially trivial) things:

> Remove unused Stripes menu driver - will just get in the way of further refactoring at this point, and it was essentially a dead and nonfunctional menu driver

I agree with this 100% - Stripes is nothing but a maintenance hazard. But the removal of a menu driver is a significant event, and on an organisational level this should be done in its own PR (not tagged onto a collection of other refactors).

> (MaterialUI) Remove/inline materialui_render_switch_icon and reduce two cases in a switch to one

IMHO, all this does is uglify the code. It is unnecessary.

> (MaterialUI) materialui_draw_thumbnail - this sanity check was entirely useless - scale_factor is always hardcoded at 1.00 in all calls

No, do not do this. The sanity check is not useless - when a coverflow playlist view is implemented, the scale factor will be set dynamically, and may be zero (other potential view types may also set 'invalid' scales)

In addition, this is a fundamental rule of encapsulation. If a function accepts an argument, it should be able to deal with it. If it dies when the argument is invalid, then it is a bad function.

----------

Of slightly greater import is the context of the changes you have made in this PR. I have no objection to the Ozone and XMB refactors - but they are essentially a random collection of edits that have no relation to your stated goals. Either deal with the items you want to address, or make this a separate 'clean-up' PR with narrower goals - otherwise there is a lack of order to the development process.

----------

The most significant issue here is item 3 in your list of goals. The first two are fine:

> Right now XMB, MaterialUI and Ozone all have their own 'draw_icon' functions. These are nearly 99% the same except for usually one small deviation. We want to basically make these functionally identical across the board and then just use one instead of all this duplication.

No objections here! But this could be dealt with almost immediately in its own PR - just create a 'draw_icon' function in `gfx_display.h/.c` and use it in the menu drivers.

> The gfx display driver right now is grossly inefficient... we need to carefully start working towards being able to batch all these calls and being able to do it with just a couple of 'draw' calls

Yes, you are absolutely right.

But point 3:

>  Further onto that point, these higher abstractions like 'draw_icon' need to fall by the wayside later on. We need to start thinking lower-level in terms of gfx_display_draw_quad, gfx_display_draw_vertex, etc. All of this will allow us to more easily batch all this when we actually have to send this data over to the graphics API (i.e. the gfx_display layer). A high level of abstraction like 'texture', 'icon', 'background' is not going to help lead to more efficient draw calls.

One hundred times no. By that same measure, we shouldn't be drawing 'text' in the menu - we should get rid of `gfx_display_draw_text()`, and instead draw individual primitives 'by hand'. Except we don't, because that would be crazy!

We absolutely need to keep high level abstracted functions such as draw_texture, draw_icon, draw_background. The key is that the *backend* should be modified. When draw_texture, draw_icon, etc. are called, that operation should be queued - such that draws can be flushed in a batch, exactly the same as when rendering text.

The point here is that the 'baby steps' approach of fiddling with individual drivers (as in this PR) is rather inappropriate. The better way of handling this is to first implement a batch rendering method - a set of functions equivalent to those in `gfx_display.h/.c`, but with a 'batch' suffix and a 'flush' routine. This is the meat of the work, and where all the difficulty lies. But once this is done, it will be very easy to substitute this into any menu driver (or widget) - just a like-for-like replacement in most cases (and then the old routines can be simply phased out).

The side benefit here is that the batch rendering method can be worked on in parallel to everything else - it can be added to master and refined, but kept 'dormant' until it is fully working - i.e. is does not involve large numbers of refactors to (and potential regressions in) all the menu drivers as the fundamental concepts here get straightened out.

And most importantly: attempting to develop a proper batch rendering technique will soon reveal (a) whether such a thing is even possible and (b) what unforeseen caveats and issues will have to be dealt with in the context of menu construction. Trying to rework menu drivers before the rendering method is finalised is very much a case of putting the cart before the horse.

**Comment by twinaphex** [comment]
I think in light of this feedback (which is welcome), it's perhaps best I shelve the current PR as is and make the Stripes removal separate from this.

**Pull request closed without merging**
