### PR TITLE
Some missing core banners for 3DS

### PR DESCRIPTION
**Pull request by fpscan**
Let there be something to start with, so that users don't confuse between the same icons or banners. I will make the rest in future. 
image

### CODE REVIEW

**Comment by jdgleaver** [comment]
@fpscan Thanks for this!  :)

But why did you change the RACE icon...? I feel the old one was more appropriate...

**Comment by fpscan** [comment]
> @fpscan Thanks for this! :)
> 
> But why did you change the RACE icon...? I feel the old one was more appropriate...

Hey there :) actually I was working on it and I had few more variations but I didn't realized that was in this branch, RACE have it's own logo and banner. Okay I see it now, it was in first commit which I wasn't aimed the `RACE` would you like me to change it back? 

race

**Comment by jdgleaver** [comment]
It's a tough call... On the one hand, I can see the appeal of using official logo images for all the app icons, but on the other hand we already standardised on using controller (or handheld console) images where possible...

I think if we want to use logos, they should all be changed at the same time :)
(and we should maybe ask for feedback on this - a twitter poll or something)

Until then, it might best to use the old RACE icon. Is that okay?

**Comment by fpscan** [comment]
> It's a tough call... On the one hand, I can see the appeal of using official logo images for all the app icons, but on the other hand we already standardised on using controller (or handheld console) images where possible...
> 
> I think if we want to use logos, they should all be changed at the same time :)
> (and we should maybe ask for feedback on this - a twitter poll or something)
> 
> Until then, it might best to use the old RACE icon. Is that okay?

It's all good, I was just aiming to make quick icons/banners so people won't confuse the cores with no banners/icons :)
https://github.com/libretro/RetroArch/pull/10903

**Comment by jdgleaver** [comment]
Thanks!

>  I was just aiming to make quick icons/banners so people won't confuse the cores with no banners/icons :)

Yes, absolutely - cores are pretty much unusable on 3DS without proper banners, so your work is very much appreciated :)

**Pull request merged**
