### PR TITLE
(Windows) Mouse grab fixes

### LINKED ISSUE #11932: [Windows] Grabbed mouse can actually leave the RetroArch window.
## Description

When using windowed mode, if you grab the mouse (F11/Scroll Lock), the cursor can actually leave the window, you don't see it on the OS but it's clearly not inside the RA window anymore.

https://user-images.githubusercontent.com/33353403/105615318-e82feb00-5dcf-11eb-8373-40b866ddaf8b.mp4

I've only recorded in RA main menu but it also happens ingame. I actually noticed it while testing Arkanoid on NES with the mouse, the cursor stopped moving at some point because of this.

Tried on my Linux VM and the cursor properly stops when reaching the borders/corners of the window.

### Expected behavior

The mouse shouldn't be able to leave the RA window when grabbed.

### Actual behavior

The cursor can leave the RA window.

### Steps to reproduce the bug

1. Open RetroArch in windowed mode.
2. Press F11 to grab the mouse.
3. Go to the top-left corner for example, instead of being stopped, the cursor will leave the RA window.

### Bisect Results

Since forever it seems, tried with RA 1.3.2 and it was already happening.

### Version/Commit

- RetroArch: 1.9.0 / 6167f8c

### Environment information

- OS: Windows 10.

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

Fixes for grabbings, though the latter one kinda makes the first one obsolete, but it will make the behavior the same with current `dinput`, regardless of global clipping.

- WINRAW: Added `RIDEV_NOLEGACY` to prevent mouse clicks outside the window
- WINRAW+DINPUT: Added `ClipCursor()` to keep cursor inside the window 
- Renamed `winraw_grab_mouse()` `grab` to `state` for consistency with other drivers
## Related Issues

Closes #11932

### CODE REVIEW

**Comment by bslenul** [comment]
Thanks, this is much better already 👍 

Still some issues however (sorry!), looks like it has something to do with the "Window Decorations" setting?

https://user-images.githubusercontent.com/33353403/106537876-840dd500-64fb-11eb-9d34-31779603558d.mp4

Basically with decorations ON: the cursor can still leave the window by a few pixels:

image

However with decorations OFF it's *almost* perfect: the cursor is properly stopped on left/right sides and on the bottom

image

But at the top, it still goes "under" the menu bar:

image
(you can see just a bit of the cursor here)

**Comment by sonninnos** [comment]
Hmm, not really sure if "fixing" that is worth the effort, considering where the rectangle data is coming from, as in I'm out of ideas..

**Comment by sonninnos** [comment]
Please no merging yet! Alt-tabbing forgets the cursor clipping.

**Comment by sonninnos** [comment]
All right, alt-tabbing is now fine and window decorations + menu bar are taken into account.

**Comment by bslenul** [comment]
Just tried it, mouse is now perfect, decorations ON or OFF, the cursor stops properly, etc. ❤️ 

Buuuuut, now for some reason every time mouse is grabbed RA crashes when I enter or exit a menu. For example if it's not grabbed I can enter/exit Settings > Drivers with no issue, but if mouse is grabbed RA will just close when I enter or when I exit the menu.

**Comment by sonninnos** [comment]
Phew, seems to be sorted now.

**Comment by bslenul** [comment]
Aaaaah awesome, just messed a bit with it and it seems perfect now! Thank you so much for this! ❤️

**Comment by twinaphex** [comment]
@sonninnos Let me know at any point when this is ready in your estimation to be merged.

**Comment by sonninnos** [comment]
> @sonninnos Let me know at any point when this is ready in your estimation to be merged.

Should be good to go.

**Pull request merged**
