### PR TITLE
Mayflash DolphinBar

### PR DESCRIPTION
**Pull request by hiddenasbestos**
## Description

Adds support for the Mayflash DolphinBar.

"The Mayflash DolphinBar is a combination Bluetooth adapter and Sensor Bar. It doesn't reveal any of the Bluetooth information to the operating system, instead sending HID packets directly to Dolphin without a Bluetooth Stack, thus allowing -TR [Wii MotionPlus] support and syncing of Wii Remotes"

Basically I just added the correct VID/PID for the bar and used the existing wiimote code and it just worked. I'm not able to sync my wiimote to my PC via my bluetooth adapter so I'm not able to compare the experience, but I was able to map buttons and navigate in the front-end with it, so it's a start.

## Related Issues

NOTE: I had crashes when attaching and removing extension peripherals (such as the nunchuk and classic controller pro) requiring a power cycling on the remote. When booting with these attached the controller didn't function at all.

I don't know whether this is consistent with using a wiimote via a bluetooth adapter.

## Related Pull Requests

none

## Reviewers

@bparker06

### CODE REVIEW

**Comment by hiddenasbestos** [comment]
I've edited the issues section to include a hint that I don't think Wiimote support is working well in general. I tried to diagnose the problems but I'm no expert and didn't really get anywhere.

**Comment by bparker06** [comment]
To my knowledge, Wiimote support is not hooked up at all in the libretro port, so even if you were able to pair it, the inputs would do nothing.

**Comment by twinaphex** [comment]
Hi there,

inside the HID driver, we have a joypad driver that is basically libwiiuse. The only difference is that we stripped it from everything but Classic controller support.

https://github.com/libretro/RetroArch/blob/master/input/connect/connect_wii.c

If you would like, Imcould turn it into full fat wiiuse so that we have more to work with.

**Comment by hiddenasbestos** [comment]
Yeah I spent a long time in connect_wii yesterday trying to figure out why it crashed when connecting an extension device (libhid requests a nonsense size to fifo_read). Also as I don't have a classic controller, just the subtely different cc pro (no analog) I was trying to get the ident code for that and the nunchuk. Failed at all of those tasks unfortunately.

Extending wiimote support with nunchuk and pointer input is something I'd love to see as it opens up the possibilities of dual lightguns (also with all buttons configurable for when PS2 comes along). Although at the moment only the first wiimote is recognised in RetroArch - the DolphinBar supports up to four.

**Comment by twinaphex** [comment]
Let's merge this already since there is no harm in this PR as-is. We can take care of fleshing out wiiuse afterwards.

**Comment by markwkidd** [comment]
@hiddenasbestos have you ever tried Mode 3 with your DolphinBar? I have used it extensively with dual Wiimotes even prior to this PR with no problem due to work @casdevel has done to add support for that configuration.

I'm intrigued about this libwiiuse conversation, but since everything is already working on my Wiimotes via Mode 3 I'm not sure what that would add.

**Pull request merged**
