### PR TITLE
Fixed and edited the FR translation

### PR DESCRIPTION
**Pull request by natinusala**
I fixed some typos and accent errors. I also translated some english sentences that were not translated.

Be careful before merging, github may have messed up the encoding since it shows that I edited some lines with accents on it but I left them untouched.

### CODE REVIEW

**Comment by Alcaro** [comment]
Yes, that's screwed up. Don't use GitHub's built-in editor, it converts everything to UTF-8. Clone the repo and edit it locally instead.

**Comment by Kivutar** [comment]
Thanks for these fixes

**Comment by natinusala** [comment]
I also saw some mistakes in the XMB menu, I guess they are from the "to uppercase" function that is used ; there is some "VIDéO" texts (not accurate, that's just an example) and I couldn't find them in the translations files. So I guess you should fix the function so it uppercases the accents too.

**Comment by Kivutar** [comment]
Either that, or move the uppercase transformation on the menu driver side, so we can disable it on XMB where labels where never meant to be upper case in the original design.

**Comment by natinusala** [comment]
I think that it's the menu's design choice to have uppercase letters, so I guess that in the language file it should be lowercase and if needed the menu alters it to show an uppercase text. But the shared functions should contain an uppercase letter so that anyone can use it. I didn't find the uppercase function so I don't know how it works now, is that an XMB-specific function ?

**Comment by Kivutar** [comment]
I agree.
No, it's not XMB specific, let me find it..

**Comment by Kivutar** [comment]
string_to_upper in the libretro-common repo

**Comment by natinusala** [comment]
Okay, so I think it should be fixed to support accentued characters. The thing is that it's currently using the C function toupper so we don't have much code to fix anyway =/

**Comment by natinusala** [comment]
I think that it would be better to use `towupper` but It has to be on wide chars and RA doesn't support them yet I guess

**Pull request merged**
