### PR TITLE
Fast-Forward Audio Resampling

### PR DESCRIPTION
**Pull request by felipetavares**
## Description

Previously, we avoided doing any resampling while fastforwarding based on the assumption it was impossible to make the audio not crackle due to both flush-to-flush timing fluctuations and timer accuracy.

However, turns out this is not the case. The audio doesn't "crackle" per se when the timing fluctuates! It's just that the sounds don't make sense since the time compression and decompression caused by the flush time fluctuations mess with the audio consistency.

To work around that, we introduce a running average flush delta time that makes sure the audio is both resampled to approximately the correct rate and consistent.

This was tested in two settings:

- Limited rate fastforwarding (2x-4x)
- Unlimited fastforwarding

In both cases it seems to work well, but with unlimited fastforwarding it's just high pitched and annoying, so this is probably the most useful in the 2x to 4x range.

Fixes libretro#15160.

## Reviewers

Sorry, I don't know anyone in the project. 🤞hopefully the right people see this.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
clever! Thanks for the contribution!

@LibretroAdmin

**Comment by crashGG** [comment]
I merged the Fast-Forward Audio Resampling, tested with several cores, when 2x-4x range, audio are all high pitched

**Comment by hilltop804** [comment]
I found the bug in the original PR and re-tested including the lower bounds patch. I didn't experience any bugs, and everything seems to work well.

**Comment by felipetavares** [comment]
Thanks @hilltop804! @LibretroAdmin do I need to do anything else here before review/merge?

**Comment by felipetavares** [comment]
@crashGG Maybe, but backtracking a bit before I answer: my expectation was that the correct behavior would be the pitch shifting by the same amount as the fast-forwarding speed, since the audio is also being played that much faster. It's also computationally cheap since it's only resampling the audio.

> In both cases it seems to work well, but with unlimited fastforwarding it's just high pitched and annoying, so this is probably the most useful in the 2x to 4x range.

When I mentioned this, I was not saying the 2x-4x pitch would be equal to the original, only that at 2x it isn't that annoying and you could still play a game, but if you go to a much higher speed then it's better to just mute because you can't really use the sound clues anymore or make out what is happening.

Now, for the answer, I can try my hand at implementing some [Time Stretching](https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling).

**Comment by hilltop804** [comment]
@felipetavares I didn't really consider adjusting the FF pitch as in-scope for the original bounty I posted since I figured that would be much more difficult than just fixing the crackling. That said, I'm sure @crashGG isn't the only person that will be bothered by the high-pitched sound at >2X and I don't want this to not be adopted because of that. I can think of 3 ways forward:
- Add a simple toggle in settings to turn this off so behavior would match the current master branch.
- Limit your changes to 2X speed and under. (i.e. 3X+ would revert to current master branch behavior).
- Add an audio pitch fix to this PR as well. If you can find a way to implement that with a reasonably low computational impact, I think that would be great. At that point, it should likely also have a settings toggle or be limited to below a certain speed. If you can do this, I can also fund the bounty an additional $50 for the added scope.

Let me know what you think!

**Comment by felipetavares** [comment]
I'm going for both a toggle and pitch correction (with its own toggle).

Some documentation for (mostly my) reference:

https://bugzilla.mozilla.org/show_bug.cgi?id=1630569
https://bugs.chromium.org/p/chromium/issues/detail?id=289354
https://github.com/chromium/chromium/blob/main/media/filters/audio_renderer_algorithm.cc

**Comment by Ryunam** [comment]
Out of sheer curiosity, I have tested this PR with unlimited FF and I have to say, I feel it is definitely quite grating and annoying, particularly when using headphones. 
It could end up being really unpleasant for those games where repeatedly triggering fast-forward might be desirable.

I understand the benefits that come with this implementation though. So I agree on the need for some new toggles under Settings -> Audio, allowing for some further tweaking on the user's part. 

Personally I would also keep the current (crackling) audio mode as the default behavior, but that depends on how effective the pitch correction will turn out to be.

**Comment by i30817** [comment]
Hope there is a option to turn off sound unconditionally while in fast forward. The 'benefits' are unconvincing and the crackling and pitch annoyance quite convincing.

**Comment by crashGG** [comment]
> I'm going for both a toggle and pitch correction (with its own toggle).
> 
> Some documentation for (mostly my) reference:
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1630569 https://bugs.chromium.org/p/chromium/issues/detail?id=289354 https://github.com/chromium/chromium/blob/main/media/filters/audio_renderer_algorithm.cc "AN OVERLAP-ADD TECHNIQUE BASED ON WAVEFORM SIMILARITY (WSOLA) FOR HIGH QUALITY TIME-SCALE MODIFICATION OF SPEECH"

Corresponding to the high pitch during fast forward, the pitch is also suppressed during slow playback.It is difficult to maintain the original pitch when the speed is changed.A perfect example is duckstation, which sounds smooth and pitch-invariant when fast-forwarded. Maybe could refer to his code.
https://github.com/stenzek/duckstation

**Comment by felipetavares** [comment]
Thanks @crashGG, it uses the same idea I'm implementing, it's pretty much used everywhere that does pitch invariant fast playback.

> the pitch is also suppressed during slow playback

Yep, I won't be changing the slow motion behavior for this PR but it is a good candidate for a follow up.

**Comment by felipetavares** [comment]
I'll keep this PR for only the resampling changes, and will try to get the WSOLA implementation in separately as it's much larger and slower: my current implementation requires a ring buffer but I'm trying to do some clever slicing up of buffers to avoid that.

Added a toggle in the menu so this can be merged without changing the default behavior.

**Comment by lonkelle** [comment]
> @crashGG Now, for the answer, I can try my hand at implementing some [Time Stretching](https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling).

did you get anywhere with this, seems like its the solution all other emulators have been using and am wondering if you'd taken a stab at this yet, i'm thinking about trying if you have any tips for me based on how you've already thought it out

**Comment by felipetavares** [comment]
Hi @lonkelle,

No, I didn't get anywhere with it. I got sidetracked with other work after this got merged.

**Pull request merged**
