### PR TITLE
Fix image mirroring in vertical games on the 3ds port (bug #4817)

### PR DESCRIPTION
**Pull request by danieljg**
The current implementation of screen rotation is broken, as per bug #4817. The image is not rotated, but rather it's mirrored. This pull request contains a small fix for this. The image is still not rotated, as it would reduce the screen real state considerably, but it is not mirrored anymore.

### CODE REVIEW

**Comment by bparker06** [comment]
I noticed this just the other day, thanks for finding a fix!

**Comment by danieljg** [comment]
You're welcome! I had found out about this since I filed the bug report in late April, but I hadn't gone ahead and implemented it until today. It's the first pull request I send, so I intentionally kept it small.

There's a lot more 'low hanging fruit' in the 3ds port which is prime for fixing, such as the broken '400x240 mode' that occurs at a little under the middle point of the 3d level slider. That one only sends the image to the left eye, but I think it's an equally simple fix. We'll see soon enough.

**Comment by twinaphex** [comment]
Thanks a lot for this contribution. Awesome to see more devs with 3DS experience.

**Comment by danieljg** [comment]
You're very welcome, twinaphex. I appreciate your efforts greatly, as well as the rest of the teams'.

It's an awesome feeling to have a bit of your code merged into a project you love. I hope there's more to come in the short term from my end. Cheers!

**Comment by vaguerant** [comment]
@danieljg, changing the "broken 400x240 mode" you refer to here would be a misfix. That mode is functioning as it was originally intended, albeit it does not work on "New 3DS" models. That mode was implemented (by @aliaspider) as a mode where the parallax barrier (the thing which makes the system "3D") is switched off (this is the part that's nonworking on New 3DS), and the system is actually now running in a situation where the 3DS still believes it's running in 3D, unlocking the full 800\*240 resolution of the screen.

Now, with the parallax barrier disabled, the "left eye" (every "even" column) is used to display the image to the user, and the "right eye" (every "odd" column) is rendered in black, resulting in clearly delineated pixels rather than them bleeding together horizontally. It's sort of roughly the same concept as scanlines, if it helps to visualize what's going on, except vertically.

A true fix for that issue would be to find why it's not working correctly on New 3DS, or if that can't be done, perhaps just disabling the feature if RetroArch detects it is running on a New 3DS, where the feature is, as you've discovered, not useful.

**Comment by danieljg** [comment]
@vaguerant, I think changing the 'broken 400x240 mode' would only be a misfix if it was innapropriately fixed. It can also be written so as to work both on the 3ds and n3ds, instead of just disabling it for the n3ds. The problem seems the register used to switch the parallax barrier on and off is different in both models, as commenting out the line which is meant to disable said barrier has null effect.

**Pull request merged**
