### PR TITLE
(Vita) Improve controller features of PSTV

### PR DESCRIPTION
**Pull request by d3m3vilurr**
- Support L2/R2 actions (probably work L3/R3 but not tested)
- Autodetect connection of controllers

This patch require to update latest `vita-header`

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi @d3m3vilurr , it seems RetroArch no longer works on PS TV according to some users? Could this be the cause?

**Comment by d3m3vilurr** [comment]
maybe not. i was tested multiple times this api with both ds3&ds4.
is problem cannot use controller?

**Comment by twinaphex** [comment]
https://gbatemp.net/threads/retroarch-libretro-thread-ps-vita-edition-nightlies-included.437034/page-87#post-6726452

This user here provides some details

**Comment by d3m3vilurr** [comment]
> It was working when l2r2 was added 10/3 on pstv 
>
> After 10/4 it no longer works on pstv

hm.. i dont know when add my patch to build, but i can't understand this report, cuz l2/r2 never work before include my pr.

so i guess, some environ changed after 10/4..

**Comment by d3m3vilurr** [comment]
@twinaphex  i was tested pcsx_rearmed of 2016-10-06 version official nightly on the pstv.
it work well. L2/R2 good and no crash.

**Pull request merged**
