### PR TITLE
Added alternate Turbo-Mode 'Single Button'

### PR DESCRIPTION
**Pull request by AnaLogiC76**
For systems supporting only a single button, the turbo-button will toggle firing that button without the need to hold it.
When holding the button turbo will be suspended and resumed when the button is released. Holding the button may have a different function to just tapping it, e.g. charging the beam in R-Type on C64/Amiga.
The original implementation in RA is named 'Classic' because I have no
idea where it originates from.

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
this seems like a good concept, but would you be interested in extending it to more than one button? That is, a flag you could set on each button to make it turbo or not?

**Comment by AnaLogiC76** [comment]
This is already supported by pressing buttons while holding turbo to toggle them. The default only can specify one button because I was not sure how to do configuration for a list of buttons properly in the UI.

**Comment by AnaLogiC76** [comment]
Rebased on master.
I would appreciate to get some more feedback.

**Comment by twinaphex** [comment]
Is it possible for you to refactor this so that both your new way of doing turbo buttons and the old way of doing turbo buttons is one and the same codepath? That way we don't have two separate ways of doing turbo buttons but just one codepath with additional functionality. Otherwise this could become a maintenance burden over time.

**Comment by twinaphex** [comment]
```
The default only can specify one button because I was not sure how to do configuration for a list of buttons properly in the UI.
```

Sounds like something where you'll want to revisit this after we implement button combos for the inputs (this is something @BarryJRowe is going to look into).

So will you want to further improve this the way @hunterk suggested once the button combo functionality is in? I could live with merging this in for now as long as it's understood that once the button combo code is in, that this will see the necessary reworks to expand on its functionality.

**Comment by AnaLogiC76** [comment]
Sure I would want to improve on it, supporting several buttons as default is a UI matter, the code can already handle turboing several buttons at once.
Do you have a link to describe in more detail what button combos would be?

**Comment by i30817** [comment]
I don't think there is a easy way to get turbo working with multiple button at the same time, without significant GUI work that is both unlikely and probably better used for a more complete combo-over-time scheme.

If you insist, though my idea about this functionality is that it's not very discoverable. The help menu with select explaining how it works with a modifier key instead of assigning a 'turbo' to a single button might help (many help menus are 'missing' on this place so i don't think it'd be consistent sadly).

Also, speaking of things that have no good solution, activating autofire when the autofire you want already requires a modifier button in game is a bit annoying, because you have to remember to press the 'game modifier' before the autofire key and before the actual game key, so it trips the mind a bit.

No good idea to avoid it as i mentioned.

**Comment by twinaphex** [comment]
Finally backported this, and just in time for 1.8.2!

https://github.com/libretro/RetroArch/commit/538f0c534f654f5cfa0f5ae127cde9c74f15cde0

Thanks a lot @AnaLogiC76 - hope you don't mind the rebase.

**Pull request closed without merging**
