### PR TITLE
Add View feature

### PR DESCRIPTION
**Pull request by schellingb**
## Description

Add saving of a filter set in the Explore menu into a so called "View" file which then gets listed alongside playlists. This also adds the ability to filter a category by range in the Explore menu and not just filter on exact matches.

The views are saved into .lvw (libretro view) files that just like playlist .lpl (libretro playlist) files are in JSON format and are stored in the same playlists directory.

Here's some examples of views that are now possible with the new range filtering:

- Games made between 1992 and 1996 by developers Capcom and Capcom Production Studio 1
- Games supporting 5 to 8 players
- Games containing "Mario" in the title released between 1988 and 1994

It's a fairly big change that touches ozone and xmb due to how the horizontal list (aka. sidebar in ozone) now shows two kinds of files (.lvw views and .lpl playlists). A small simplification in xmb and ozone removes the variable `playlist_collection_offset` by storing the view/playlist list offset in `entry_idx` and thus avoiding complex counting done separately both in xmb and ozone.

Because this PR touches a bunch of things it's probably better to test it before merging. A review would also be appreciated.

## Reviewers

Maybe @sonninnos ?

### CODE REVIEW

**Comment by gouchi** [comment]
Tested quickly so far so good.

```
git fetch origin pull/14467/head:pr14467
git checkout pr14467
```

## Save view
save-view

## View (xmb)
view

## View (ozone)
view-ozone

Year 2k.lvw 
```
{
	"filter_equal": {
		"releaseyear": "2000"
	}
}
```

**Comment by i30817** [comment]
Only positive filters like the UI right?

**Comment by schellingb** [comment]
@gouchi Thanks for testing! Looks like nothing broke :-)

@i30817
> Only positive filters like the UI right?

Yeah, I kept it simple mostly because making the UI for it is the most time consuming. If there's a demand to add features that can't be set in the UI but needs manual .lvw file editing I guess that could be done easier than adding more features to the UI.


> Followup i'd suggest would be moving these filters to their own dedicated zone in the tab.

Similar reason, adding features to the UI is quite time consuming due to it often requiring touching each of the menu drivers separately. I would have loved to make them stand out better or have an icon. Maybe even allow customization of the icon.

**Comment by sonninnos** [comment]
Looking good, except a few tiny things:
- "By System Name" menu shows bogus thumbnails, when there should be none
- When browsing via a view into entry "Information", the playlist index + thumbnail goes kaboom, requiring extra browsing to recover
- Left sidebar size does not animate like in playlists, making the available space for items rather narrow with thumbnail sidebar visible

**Comment by Tatsuya79** [comment]
Seems to be working fine.
Just that it shows the .lvw playlist in qt and that it's empty.

**Comment by LibretroAdmin** [comment]
Hmm, one issue i can foresee here - it seems XMB/Ozone/MaterialUI are now dependent on a function in menu_explore.c. However, for Griffin builds, this file only gets compiled in if HAVE_LIBRETRODB is defined. How will we deal with this? Can the necessary function possibly be divorced from menu_explore.c, or how should this be resolved @schellingb ?

**Comment by i30817** [comment]
Denylisting is worse than allowlisting because the next time another specialized format happens you'll have to do it again.

Imo, this should go to another directory even, because you can't be sure that code you don't control isn't actually reading the playlists directory naively (my utilities that do it filter by file extension too, but i doubt i'm the only one messing around with those files outside the project).

**Comment by schellingb** [comment]
I did change it first to have its own directory but reverted that. The way RetroArch manages its directories means forcing an empty directory for every user out there that doesn't use this feature. If the directory gets deleted it gets recreated the next time RetroArch launches. If it were possible to only create the directory when first saving a view I'd have kept it. Views do belong to playlists though, as the views are filtering the playlists. Also the place where RetroArch shows playlists it now also shows views, it can enumerate just one directory of the file system and get all the things to be shown.

Maybe a subdirectory /playlists/views/ like the .lrtl files in /playlists/logs/ that only gets created as necessary and not at program start?

**Comment by i30817** [comment]
Unfortunately, most apis (python included) make no hard distinction on getting a file or subdirectory, so i still think it should be completely separate. You can do whatever you like of course, since this is only in case of buggy external programs, so you're not chained to their (possible) faults.

**Comment by sonninnos** [comment]
Heh, here comes the Ozone whack-a-mole:

1. When entering any Explore submenu the left side goes crazy:
retroarch_2022_10_07_03_50_59_230 mp4_snapshot_00 02 614

2. When returning from the same submenu the left side recovers half way:
retroarch_2022_10_07_03_50_59_230 mp4_snapshot_00 03 525

3. When entering entry from view the same invisible space is there:
retroarch_2022_10_07_03_50_59_230 mp4_snapshot_00 10 593



https://user-images.githubusercontent.com/45124675/194444376-846d1edc-0105-458b-8a39-d7f2f8baadf7.mp4


XMB seems fine except the playlist icons are rather random.

**Comment by schellingb** [comment]
@i30817 I would fully agree with all that if the /playlist/logs file and its .lrtl files weren't already a thing. But they exist so might as well add another subdirectory. As long as it doesn't create any directory or file for users who don't use the feature I'm fine honestly.

@sonninnos Man, that was very broken. Sorry about even committing that. I think I found a way to make Ozone cooperate without the need to add something silly like `ozone->was_explore_list` and I looked at all menus and they look good to me now. If you have some more time, can you give it another shot, please?

**Comment by sonninnos** [comment]
Tried my best to make it break, but was not able anymore. Still one more final thing seems to remain, which is the refreshing of downloaded thumbnails in views.

`cb_task_pl_entry_thumbnail_refresh_menu()` is where the current dodgy bit is which prevents the refresh callback from happening. I'll look into cleaning it up, but need a tiny break first.

**Comment by schellingb** [comment]
@sonninnos Thanks for the patch. I applied it and it makes thumbnails appear while browsing views so it seems to work as promised. I don't really know about the code modified there but I hope the removal of these two conditions doesn't somehow affect something else in a weird way. Was this maybe just some optimization to leave early before having to call `string_is_equal`?

```patch
-      if (((pl_thumb->list_index != menu_navigation_get_selection()) &&
-           (pl_thumb->list_index != menu->rpl_entry_selection_ptr)) ||
```

**Comment by sonninnos** [comment]
I wasn't able to get any noticeable benefit from allowing that early return to happen that way where it is supposed to be working (regular playlists), as in it won't catch any serious spam from late items when scrolling fast, so I guess those extra conditions aren't really important anymore..

And besides at that point some damage is already done, as in the image was downloaded, so not much is gained in aggressively preventing it from also displaying.

**Comment by LibretroAdmin** [comment]
OK, so I asked both @sonninnos and @schellingb and both agreed that this PR seems relatively safe now to merge. If there are any more outstanding issues that need addressing, let's make a new Github issue for it so it don't get lost.

**Pull request merged**
