### PR TITLE
[iOS] New iOS 13 project to support Swift; Custom keyboard and touch mouse support

### PR DESCRIPTION
**Pull request by yoshisuga**
## Description

Numerous iOS specific enhancements:

- Added a new Xcode project file, `RetroArch_iOS13.xcodeproj` to support new features using more modern iOS technologies.
- Added a bridging header file to support code written in Swift.
- Refactored the iOS view controller to properly adhere to the view controller lifecycle using the `loadView()` and `viewDidLoad()` methods.
- **Onscreen Custom Keyboard UI**: Allow keyboard input for cores that support keyboard input (DOSBox Pure, etc). This allows direct touch input similar to the system keyboard (without actually using the system keyboard, which does not support keyup/keydown events and blocks a large portion of the screen). Swiping the screen with three fingers will show/hide the custom keyboard.
- **Touchscreen Mouse Input**: Use the touchscreen for mouse input. Tap with one finger for left click, tap with two fingers for right click, tap and hold for left-click dragging.
- Added preprocessor macros (`HAVE_IOS_CUSTOMKEYBOARD`, `HAVE_IOS_TOUCHMOUSE`) to support the above features, and will be backwards compatible with the older `RetroArch_iOS11_Metal.xcodeproj`.
- Added support for JIT code, using the same code used for UTMApp, DolphiniOS. This is for future support for cores that involve JIT - I haven't tested this though.

Since the Onscreen Custom Keyboard UI and Touchscreen Mouse Input features are written in Swift, they only will be available if the project is built with the new iOS 13 Xcode project. We will have to update the build process to use the new Xcode project to pick up the new features - I will make another PR for this.

I'm also planning to make a PR to add iOS-specific UI to enable and add discoverability to these features.

### CODE REVIEW

**Comment by yoshisuga** [comment]
Screenshot of Onscreen Custom Keyboard:
IMG_4D5C2306FA71-1

Core: DOSBox Pure
Game: System Shock

**Comment by hizzlekizzle** [comment]
whoa, this is some good stuff :O

**Comment by yoshisuga** [comment]
Updated the software keyboard with some visual improvements and improved key-press effect (courtesy of @ToddLa)

IMG_77DE02433D91-1

@twinaphex Can this be merged? It shouldn't affect the current iOS build until we change the build process to build using the new Xcode project.

**Comment by xSimone** [comment]
How do you turn OFF this onscreen virtual keyboard stuff? The three finger swipe one. I don't think anything I play would utilise this and it keeps getting in the way.

**Pull request merged**
