### PR TITLE
MESA UWP Integration

### PR DESCRIPTION
**Pull request by aerisarn**
## Description

These modifications allow UWP build to work with a modified version of mesa Gallium d3d12 driver, available here https://github.com/aerisarn/mesa-uwp. This effectively leverages better dx12 capabilities to replace ANGLE builds and use nightly build version of OpenGL plugins instead of using separate versions build against OpenGL ES ANGLE dlls.
ANGLE profile is still available for devices which can't use MESA.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Exciting stuff!

**Comment by GABO1423** [comment]
> Exciting stuff!

This is why I closed the PR btw, this solution does not need cores to implement ANGLE themselves. So you can just get cores from the online updater, avoiding the problem altogether.

**Comment by LibretroAdmin** [comment]
I think it's a good idea to have alternatives for ANGLE, regardless of whether we still use ANGLE on the cores.

**Comment by aerisarn** [comment]
libretro-citra could work with MESA, however the current buildbot version is build with MSVC and doesn't work on XBOX due to dll dependencies. MINGW build however doesn't have the offending dlls

**Comment by LibretroAdmin** [comment]
@GABO1423 So can we merge this or not? Also for whatever reason we can't seem to be able to DM you anymore on Discord, not sure what that is about.

**Comment by GABO1423** [comment]
> @GABO1423 So can we merge this or not? Also for whatever reason we can't seem to be able to DM you anymore on Discord, not sure what that is about.

I stopped using my Xbox for emulation a while ago, my small commit is the last UWP related thing I plan to do. According to people who have tested it, it's ready to be merged so that's good enough for me.

**Comment by LibretroAdmin** [comment]
Alright.

**Comment by GABO1423** [comment]
Build error is not due to the code but an outdated key file, guess I'll do one last commit

**Pull request merged**
