### PR TITLE
(untested) X11 input driver - for lightgun/mouse binds

### PR DESCRIPTION
**Pull request by hiddenasbestos**
This is an un-tested pull-request to implement the new lightgun API and mouse binding features for X11.

* Not 100% sure if it ~~even compiles or~~ works properly but should provide the broad strokes for someone to complete the work. Hope this helps.

Test lightguns with Beetle Saturn / Beetle PSX built from 27th November or later.
Test mouse binding to inputs with any core/content.

### CODE REVIEW

**Comment by hiddenasbestos** [comment]
Once this compile succeeds, someone else will need to test it works. Sorry I can't complete the work but I'm trying to help as best I can :)

**Comment by hiddenasbestos** [comment]
@fr500 did you happen to be running Linux when you replied to me earlier saying the gun/bindings worked? You may have accidentally tested this for me :)

**Comment by fr500** [comment]
No, I'm a Windows user

**Comment by orbea** [comment]
@hiddenasbestos Can you elaborate on what I can test exactly to see if this works or not? I have a dolphinbar and wiimote I could use as a lightgun?

**Comment by twinaphex** [comment]
OK, in order to test the lightgun part, I need to own actual lightguns?

If so, I cannot test that part, but I could test mouse inputs.

**Comment by hiddenasbestos** [comment]
Ah sorry it wasn't clearly described. Testing this new code can be done with a mouse and Saturn core. 

Set the quick menu > controls > user 1 to "Virtua Gun / Stunner".
Without the patch the cursor will stay in the middle of rhe screen, with it should move around.
Playing something like Virtua Cop will help test the buttons and ability to bind mice buttons to inputs.
A good setup for Saturn is to bind trigger to LMB and reload to RMB and start to MMB (or enter).

Play the game if you can now blast the bad guys and reload with the RMB and also by shooting off screen (run fullscreen in 16:9 and shoot into the pillar box area)  it's working as intended.

If you have more questions I'm happy to help!

**Comment by hiddenasbestos** [comment]
Resubmitted as #5803 with unified commit, included test description and changes to coding style.

**Pull request closed without merging**
