### PR TITLE
(XMB) Dynamic wallpaper fix

### LINKED ISSUE #10269: [Bounty] Dynamic Wallpaper gets forgotten when launching a game from a playlist
## Description

1. When you launch a game from a playlist that has a dynamic wallpaper, if you go back to the list to load another game, it will show the default wallpaper instead of the dynamic one.

2. If you go out of the list and back in, the dynamic wallpaper gets displayed again, but if you choose to close the game from its playlist, the dynamic wallpaper will get replaced with the default one again after it closes, even though you're still inside the list.

Usually I like to stay in one playlist and try different games, but this bug takes away the joy of having a customized wallpaper during this process, I'd like to make my own themes too, but this is a bit demotivating as it kinda wastes the effort of creating a custom wallpaper :(

### Expected behavior

Dynamic wallpaper should persist after launching or closing a game

### Actual behavior

The default wallpaper replaces the dynamic one after launching or closing a game.

https://user-images.githubusercontent.com/26237704/119041534-bd703080-b984-11eb-8fb1-9110ebacd763.mp4

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

- Separated dynamic wallpaper update to a function
- Run that update function when lists are populated, and after texture reset, to make sure the wallpaper is still there after closing content and immediately after toggling Quick Menu

## Related Issues

Closes #10269

### CODE REVIEW

**Comment by DisasterMo** [comment]
Tried it out, seems to be working fine. I don't like the delay before the background pops in after closing content, but I don't see any easy way to fix that.
Since you made a new function, could you please add a short descriptive comment to it? RA badly needs more comments, so we should add them at any opportunity.

**Comment by sonninnos** [comment]
Thanks for testing. If with delay you mean RA itself not showing for a while after closing, then yep, nothing to be done about that, at least in this instant.

I don't feel quite right writing a description for a function I simply relocated and not created. And also it feels kinda self explanatory enough to be as-is..

**Comment by DisasterMo** [comment]
> If with delay you mean RA itself not showing for a while after closing, then yep, nothing to be done about that, at least in this instant.

What? Why on earth would I mean that? No, there is a tiny delay between RA showing the text and the dyn. background popping in _after_ the restart following the closing of content (or a least there is on my machine running Ubuntu). I would much prefer to have the background be rendered first, followed by the text. Or better yet, have no pop in at all, or maybe have the background fade in. But yeah, I don't know how one would accomplish any of that.



> I don't feel quite right writing a description for a function I simply relocated and not created.

What do you mean by that? Who cares who wrote what function? I am merely asking you to contribute a description, since you already worked on the corresponding code. I did the same with e.g.
https://github.com/libretro/RetroArch/blob/a129764f0d5199091b24b08fc294c1177a5c7bd8/menu/drivers/xmb.c#L2421-L2422
 Or do you mean, you actually don't know how you would describe it? But that would contradict your very next sentence...


> And also it feels kinda self explanatory enough to be as-is..

... your point? Some would argue Pythons `print` function is self explanatory, and yet there exists a comment describing what it does. I won't say that there cannot be too many comments. But one line for each function? That would hardly be 'too much'.

**Comment by sonninnos** [comment]
I asked because I wasn't getting delays with my setup and test pictures.

**Comment by DisasterMo** [comment]
> 
> 
> I asked because I wasn't getting delays with my setup and test pictures.

Well, I did my test with the (rather large, appearantly) stock "blurred-consoles" wallpapers. And indeed, using smaller images did reduce the lag significantly. So that must be it, then.

**Comment by sonninnos** [comment]
Please no merging yet, I have some optimizations lined up which should help with the delay. It currently resets to the default and then to the dynamic, and the goal is to upload the background only once instead.

**Comment by sonninnos** [comment]
Ready for trying & frying.

**Pull request merged**
