### PR TITLE
(cheevos) group achievements by category in quick menu

### PR DESCRIPTION
**Pull request by Jamiras**
## Description

Modifies the quick menu such that locked achievements are shown before unlocked achievements. Additionally, achievements that track progress and are nearly completed, or recently unlocked achievements are highlighted at the top of the list. This mimics behavior introduced in the most recent RetroAchievements toolkit release.

ozone:
image

xmb:
image

rgui:
image

glui:
image

And an example of highlighting nearly completed progress-tracking achievements:
image

As part of this PR, I've moved the achievement menu code into a separate file and standardized all the related function names to have an `rcheevos_menu_` prefix.

## Related Issues

n/a

## Related Pull Requests

n/a

## Reviewers

@Sanaki @meleu

### CODE REVIEW

**Review by Sanaki — COMMENTED** [review]
Works well on my default build setup, no flaws that I can see. That said, I'm only testing on a single platform. I did give a few compilers a test, including gcc-11 and clang-11, but didn't go back too far. CI indicates there are still some platforms with issues, but once those are resolved, this should be good to go.

**Comment by meleu** [comment]
I suggest to remove `Recently` from `Recently Unlocked`.

**Comment by Jamiras** [comment]
There's already an Unlocked category after the locked achievements:
image

"Recently Unlocked" is also consistent with the standalones:
image

**Comment by meleu** [comment]
oh, I missed that.

So the `Recently Unlocked` are the ones "unlocked during the current gaming session", right?

I was trying to reduce verbosity but now I realized that it looks good. :+1:

**Comment by Jamiras** [comment]
> So the Recently Unlocked are the ones "unlocked during the current gaming session", right?

Just the last ten minutes. It's a way to quickly see the last few things you unlocked in case you missed the popup, or didn't understand why an achievement popped and wanted to see the description.

**Review by Sanaki — APPROVED** [review]

**Pull request merged**
