### PR TITLE
(Netplay) Some cleaning

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**
## Description

Also fixed a bug in socket_connect_with_timeout.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi there @Cthulhu-throwaway ,

unfortunately one of your commits has broken something for Wii. Can you fix this real quickly?

https://git.libretro.com/libretro/SquirrelJME/-/jobs/2020473

> /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld: ./libretro-common/net/net_socket.o: in function `socket_connect_with_timeout':
net_socket.c:(.text.socket_connect_with_timeout+0x90): undefined reference to `getsockopt'
collect2: error: ld returned 1 exit status

Be careful not to break things for the console platforms. The console platforms have limited support for sockets and whatnot.

**Comment by Cthulhu-throwaway** [comment]
> Hi there @Cthulhu-throwaway ,
> 
> unfortunately one of your commits has broken something for Wii. Can you fix this real quickly?
> 
> https://git.libretro.com/libretro/SquirrelJME/-/jobs/2020473
> 
> > /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld: ./libretro-common/net/net_socket.o: in function `socket_connect_with_timeout': net_socket.c:(.text.socket_connect_with_timeout+0x90): undefined reference to `getsockopt'
> > collect2: error: ld returned 1 exit status
> 
> Be careful not to break things for the console platforms. The console platforms have limited support for sockets and whatnot.

Contributors for those platforms not implementing them.

setsockopt is implemented as a macro for them, but whoever did it, did a very lazy job and didn't bother setting a macro for getsockopt.

I'll fix those within this PR, just don't merge yet.

**Comment by LibretroAdmin** [comment]
Yeah ,regardless, let's please fix this so that the WIi port is not broken as a result. Builds are failing right now as a result and we can't have that. I'd appreciate a fix.

**Comment by LibretroAdmin** [comment]
Actually, it was your commit, sorry -

https://github.com/libretro/RetroArch/commit/de30f212bc45f5ef68087e672d43815afb1ea788

These functions simply are not implemented on the Wii toolchain, and there is probably an equivalent for it. Look through the rest of the codebase, and see if you can wrap these calls so that we have an implementation for the platforms we support.

**Comment by LibretroAdmin** [comment]
Look at this -

https://github.com/devkitPro/libogc/issues/56

it's simply not implemented. So you might have to refrain from doing this altogether if it's going to cause compatibility issues on other platforms, and find a different way. Maybe go back to the drawing board with it or provide an alternative for platforms that don't support this?

**Comment by Cthulhu-throwaway** [comment]
Yes, it's my commit because nothing else on net_socket.c uses getsockopt, but as soon as I used it to get the socket's error for its connect timeout, the problem appears because whoever did Wii just implemented setsockopt for it.

I am just doing it right now.

**Comment by LibretroAdmin** [comment]
Thank you. Up to you how we proceed from here.

**Comment by Cthulhu-throwaway** [comment]
I just implemented a prototype nop function for Wii.
getsockopt always gives a value of 0 and always returns 0 (success). This is enough for the socket connect timeout function, but whoever contributes to those platforms should actually implement getsockopt (setsockopt is already implemented, dunno why getsockopt wasn't implemented with it).

I also set a macro for getsockopt for the Vita (the function already exists in the SDK but there was only a macro for setsockopt).

**Comment by Cthulhu-throwaway** [comment]
They should compile just fine now, but let me know if the build still fails after this PR.

**Comment by LibretroAdmin** [comment]
Not good, now even more broke down. 

https://git.libretro.com/libretro/RetroArch/-/pipelines/112090

**Comment by Cthulhu-throwaway** [comment]
> Not good, now even more broke down.
> 
> https://git.libretro.com/libretro/RetroArch/-/pipelines/112090
> 
> See windows 32bit and 64bit now failing to build.

Weird, the original PR compiled just fine for me and I am on Windows. I'll check this out and submit another PR asap.

**Comment by LibretroAdmin** [comment]
I think I fixed it like this for now - 

https://github.com/libretro/RetroArch/commit/17d31e6dfff93b30c697b6a67b1715707105b6e4

I still get this warning though -

> libretro-common/net/net_socket.c: In function 'socket_connect_with_timeout':
libretro-common/net/net_socket.c:475:44: warning: passing argument 4 of 'getsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
  475 |       getsockopt(fd, SOL_SOCKET, SO_ERROR, &error, &errsz);
      |                                            ^~~~~~
      |                                            |
      |                                            int *
In file included from ./libretro-common/include/net/net_compat.h:41,
                 from libretro-common/net/net_socket.c:36:
/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/include/winsock2.h:1010:82: note: expected 'char *' but argument is of type 'int *'
 1010 |   WINSOCK_API_LINKAGE int WSAAPI getsockopt(SOCKET s,int level,int optname,char *optval,int *optlen);
      |

**Comment by Cthulhu-throwaway** [comment]
Yeah, winsock expects a char* while POSIX takes a void*. I'll fix that too by casting it to char*.

**Comment by Cthulhu-throwaway** [comment]
Fixed both issues, the net_compat.h header needed to be moved to the header file of net_socket.

Will submit a new PR.

**Pull request merged**
