### PR TITLE
Reboot Menu Item

### PR DESCRIPTION
**Pull request by duduke**
I've added a Reboot Menu Item.
This is useful for Lakka as well as a dual booting.

I was assisted by Kivutar, and relied on his original Shutdown Menu Item PR (https://github.com/libretro/RetroArch/commit/2b376ce3d551fb2b649743d38ba818be5109b3ba)

Thanks.

### CODE REVIEW

**Comment by duduke** [comment]
I've used the same "if"s as the Shutdown option.
Look at commit: https://github.com/duduke/RetroArch/commit/eecd14086b897fd435a1dd81770545c437ce5db6
Thanks.

**Comment by Kivutar** [comment]
Ah, @twinaphex wants that we ifdef everything about MENU_LABEL_SHUTDOWN, MENU_LABEL_VALUE_SHUTDOWN, MENU_LABEL_REBOOT, MENU_LABEL_VALUE_REBOOT with HAVE_LAKKA

**Comment by duduke** [comment]
Should we ifdef it for Lakka, or for Linux?
"shutdown -P now" and "shutdonw -r now" are perfectly OK for plain linux as well as Lakka.

What do you think?

**Comment by duduke** [comment]
@twinaphex should I use:
if defined(HAVE_LAKKA)
or: 
#if defined(__linux__) && !defined(ANDROID)
And should I add it to menu_hash.h or intl/menu_hash_us.c?
(sorry for the seemingly silly questions - I still am not 100% on how the menuing system works)

**Comment by Kivutar** [comment]
We need to put

    if defined(HAVE_LAKKA)

Around lakka specific stuff like shutdown and reboot in menu_hash.h and menu_hash_us.c and all the places where we made changes.

**Comment by duduke** [comment]
Ok, Will do.

**Comment by duduke** [comment]
@twinaphex, @Kivutar I've performed the requested changes.
Can you please review?

**Comment by Kivutar** [comment]
Looks good to me

**Comment by twinaphex** [comment]
Some stuff is a bit overboard but I'll correct that later.

**Comment by duduke** [comment]
Great, Thanks.

**Pull request merged**
