### PR TITLE
(GX) Fix input issue causing controllers to do not work at all.

### PR DESCRIPTION
**Pull request by netux79**
This issue was for about a month. The RA GX version was unusable.

### CODE REVIEW

**Comment by netux79** [comment]
Is the HID support already working for Wii? Is this the reason you removed libsicksaxis?

**Comment by twinaphex** [comment]
Very cool.

Thanks a lot for this commit,.

**Comment by twinaphex** [comment]
Yes, the HID driver should work. I tested it with a PS3 pad last time.

What the HID driver still needs though, is hotpluggable support.

ToadKing has a branch dedicated to it but he couldn't get the hotplugging part to work properly. Maybe this is somethign you could look into?

**Comment by netux79** [comment]
Yeah I could give it a try. Last time i tried (some months ago) I was unable to make a PS3 controller to work with the HID driver. Does it nned any special config/files or it just requires to change the joypad driver to hid?

**Comment by twinaphex** [comment]
The input device autoconfig dir needs to point to a dir that has all the autoconfig files.

https://github.com/libretro/retroarch-joypad-autoconfig

It looks for the autoconfig profiles inside the 'hid' directory.

**Comment by netux79** [comment]
Unfortunately I was unable to make it work... I tried what you suggested. With a clean build I copied the autoconfig folder under the Retroarch folder (the one in the apps folder which contains the dol files) and within it there is a folder called "hid", I can see there a file related to a PS3 controller with its configuration).

Now, I get into RA and be sure it is working with the 'gx' joypad driver... then I change the autoconfig folder to point to the described folder above. And then I change the driver from 'gx' to 'hid' and restart RA (get out and then get in of it, the menu option doesn't work).

Once inside again I try to move the PS3 controller buttons and I just see the PS3 controller (attached to the first USB port of the Wii) lights flashing but nothing happens... it doesn't work. I also tried to press the PS button before and after entering RA (as I know this controller sometimes needs that).

So I think I'm stuck. I think I can help you with the hotplugging stuff as I already implemented this for the libsicksaxis support but I will appreciate if you can try yourself to check if it still works for you and let me know the steps you did to make it functional (if possible starting with a clean installation so we are sure nothing is left out of the steps).

**Comment by twinaphex** [comment]
@netux79 - Different issue - 

We can no longer properly shutdown in RA on Wii.

**Comment by netux79** [comment]
OK I will give it a look, I think the easiest way will be to see when it got broken. By the way, I see you did some changes in order to fix this new issue, was it successful?. Also, did you have time to check if the HID driver still work for you, as I mentioned in the previous comment I was not able to make it work... maybe if you try with a "clean setup"  and let me know the "exact" steps so I can re take what ToadKing was doing.

**Comment by twinaphex** [comment]
I implemented the shutdown callback and put exit(0); there to force it to return back to HBC. Not clean but it gets the job done for now.

Have you been able to get a DualShock3/4 to work with USB on the regular RA Wii version (i.e. not this branch)? Last time I checked it with the joypad HID driver set to 'hid', I could use the DualShock 3 as the primary input if I disconnected the GC and Wiimote pads and used it as the primary input device plugged into USB.

**Comment by netux79** [comment]
I have not tried the branch you provided from ToadKing yet. I was trying to first make it work with the regular version and it didn't work. Yes, I did change the driver to 'hid' and also put the files you suggested on their place. Now, I think the other controls don't matter with this driver as it is not trying to read from the regular controllers but from the usb port (if fact, I ensured nothing else was connected, the wiimote wasn't even paired as the 'hid' driver doesn't perform any setup for it). 

If you was able to use the DualShock 3 controller and you had to remove the other controllers then I'm afraid you was still using the 'gx' driver and it worked because of the Libsicksaxis support, maybe. For this reason I was asking you to test it again so you can provide the exact steps you took... believe me I tried it hard and all sort of things to make it work (like pressing the PS button before starting RA, different usb ports, different paths, etc).

Now, as a side note regarding usb hid support on libogc: Because I already worked on these for the libsicksaxis I can tell that the hid support for game controllers is not complete in this library. You can connect and read the raw data from the controller but is up to you to interpret it (a good example is nintendont). I checked the config files for the hid controllers used in RA and these are appropriate for a full hid support (like in windows or linux where the driver tells you the button number and the type: regular button, axis, hat) etc. Here in libogc there is no way to get that info from the controller, you have to provide a low level configuration in advance, i.e. the byte # and the bit in it that holds the state of a button. Then you can map this so the application ca react accordingly. I was amazed you guys was able to use the same configuration files from the other RA versions.

Now, what you name hotplugging is to automatically map the controller to specific buttons and axis when you connect it or just to be able to plug it and unplug it and that it still works? maybe both :)

One last unrelated question I noticed with the lastest build of RA I tried... I was no longer able to save the resolution I set for the different cores? was it removed or this just got broken?

**Comment by twinaphex** [comment]
Saving resolutions is unreliable for Wii so until I get somebody who really knows what he is doing to look at that, I am not going to save it to config file. It introduces more problems than it solves.

The HID driver interface works fine on both OSX and Linux.

Regarding it may have defaulted to libsicksaxis, could be. Try to look at the old libsicksaxis code, see why it worked and not the USB HID driver and maybe go from there.

**Comment by fr500** [comment]
Hmm I already had implemented saving about half a year ago.
Was it removed?

**Comment by netux79** [comment]
@fr500: I guess the resolution saving got removed as it's not working as it used to. Yes it had an issue that was making the screen orange tinted but not sure if that was the reason of the change.

@twinaphex: Regarding the HID driver, yes it works perfect on linux and osx, I was referring to the support on Wii. Ok, I will assume the current hid driver is not working and see what I can do starting from that. Let you know what I find later.

**Pull request merged**
