### PR TITLE
Added five retries with 3 secs interval for network connections durin…

### PR DESCRIPTION
**Pull request by leiradel**
…g cheevos initialization.

Many users are reporting that RetroArch doesn't load achievements for games that have them. The most common reason, if not the only one, is related to HTTP issues.

This PR adds retries to HTTP connections while cheevos is trying to identify the game, load the cheevos, and deactivate the ones that have already been awarded to the player.

### CODE REVIEW

**Comment by retro-wertz** [comment]
Thanks for the update. Just a quick test here, not trying to be nit-picking here, but could we only show retry log if it actually is retrying connection? log seems confusing.

```
[INFO] [CHEEVOS]: Making HTTP request, try 2 of 5
[INFO] [CHEEVOS]: got game id 1447.
[INFO] [CHEEVOS]: Making HTTP request, try 1 of 5
[INFO] [CHEEVOS]: got achievements for game id 1447.
[INFO] [CHEEVOS]: Making HTTP request, try 1 of 5
[INFO] [CHEEVOS]: deactivated unlocked cheevo 4266 (Jungle Fever).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 4267 (Bomb The Base).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 4268 (A Salmon With A Spread Shot).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 4269 (In Your Base, Killing Your Dudes).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 4270 (Siberian Warfare).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 4271 (End of The Zoners).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 6769 (The Base 1 Challenge).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 6771 (The Jungle Challenge).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 6804 (The Waterfall Challenge).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 6850 (Who Ordered Fries?).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 6851 (Hi-Score Freak!).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 6852 (Hi-Score Win).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 6854 (Hydrophobia).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 50802 (Anti-Turretism Part 1).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 50804 (Oculus Drift).
[INFO] [CHEEVOS]: deactivated unlocked cheevo 50805 (Anti-Turretism Part 2).
[INFO] [CHEEVOS]: deactivated unlocked achievements in softcore mode.
[INFO] [CHEEVOS]: Making HTTP request, try 1 of 5
[INFO] [CHEEVOS]: deactivated unlocked achievements in hardcore mode.
[INFO] [CHEEVOS]: Making HTTP request, try 1 of 5
[INFO] [CHEEVOS]: posted playing activity.
```
Thanks.

**Comment by leiradel** [comment]
@retro-wertz wow, I was going to comment on https://github.com/libretro/RetroArch/issues/3855 and ask you to test but you were faster.

I'll make this change.

**Comment by leiradel** [comment]
@fr500 I don't know who has knowledge about configuration and UI these days, but it would be great to have the number of retries and the delay between retries configurable in the Achievements sub menu.

**Comment by retro-wertz** [comment]
hi. tested new commit. the new trying log **RARCH_LOG("[CHEEVOS]: Retrying HTTP request: %u of 5\n", K + 2);** does not seem to appear during an actual retry.

**Comment by leiradel** [comment]
It should, but I've committed a less braindead way of doing it.

**Pull request merged**
