### PR TITLE
correctly handle content paths containing a hash (#), fixes issue #3273

### PR DESCRIPTION
**Pull request by bparker06**

### CODE REVIEW

**Comment by Alcaro** [comment]
That's a lot of messy code for something that should be simple. To clean up:

- Rename filename_split to filename_split_archive. Remove the delim parameter, it's not used anymore.
- Create a function in file_path.c that returns a pointer to the delimiting # if the file refers to an archive entry, or NULL if not. Use this from both path_contains_compressed_file, path_basename and filename_split_archive. The fewer places to change to add a new archive format, the better.
- Create string_list_append_n() (possibly under some other name) in string_list.c, which takes an extra length parameter and only cares about that many bytes from 'elem'; use this in filename_split_archive. (You may know this already, but going from delim-pointer and start-pointer to length is just subtracting them. append_n is easiest implemented by copying string_list_append and replacing strdup with malloc(len+1) strlcpy(data_dup, elem, len+1).)

Plus the mandatory nitpicks; most will disappear by doing the above, but no reason not to.
- No need to malloc ext_with_hash, just put it on the stack at a constant size of 8 or 16 or something
- ext_len should be strlen(ext)
- No need to parenthesize the dereference operator, you're not doing anything confusing
- No need to cache a stack allocation, they're cheap
- Better terminate tmp manually after the strncpy than clear the entire buffer
- Actually, don't use strncpy at all, let strlcpy terminate it
- We usually use postfix increment/decrement; prefix was faster on 90s compilers, and still is for complex C++ objects, but neither is the case for us
- 'if (path+first)' should be && or || or something

**Comment by bparker06** [comment]
Thanks, I knew it was bad so I was expecting some ideas for improvement :) I'll work on this and update the PR.

**Comment by Alcaro** [comment]
...that ended up bigger than I expected.

> const char *last = find_last_slash(path);

Any reason this is outside the ifdef?

> retro_assert(strlcpy(out, ptr, size) < size);

Side effects in assertions, sigh. assert() can be defined to empty, we'll need to clean up that at some point. But it's not relevant to this PR.

>   if (delim)
>      return last + 1;

That doesn't look right.

> \-   last_hash = (char*)strchr(path_short,'#');
> \+   last_hash = find_last_slash(path_short);

Neither does that.

> union string_list_elem_attr attr, unsigned length);

Putting elem/length beside each other would be cleaner.

> strlcpy(data_dup, elem, length + 1);
> if (!data_dup)

Let's put the null check before the things it's supposed to protect.

> *delim = '\0';

Writing to things passed as a const argument is very likely to cause bugs. Just remove that write, it's not needed with the _n version; in fact, removing that specific write is exactly why it exists. Better also make path_get_archive_delim return const, to make sure nobody does anything silly elsewhere.

> }else{

In this repository, else goes on its own line.

And I've seen some places (fill_short_pathname_representation in that file, for example) put the else clause outside the ifdef, rather than a #else clone; less repetition is always good.

**Comment by Alcaro** [comment]
> char *delim = NULL;

Let's const this too.

> last = path + (path_get_archive_delim(path) - path);

?

> \- last_hash = (char*)strchr(path_short,'#');
> \+ last_slash  = find_last_slash(path_short);

I'm still not sure you want to look for slashes here, but if it works both with and without slashes in the archive path, then I'll trust that.

The rest seems fine.

**Pull request merged**
