### PR TITLE
C89/CXX support for rcheevos

### PR DESCRIPTION
**Pull request by Jamiras**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

Addendum to #8501 - fixes C89_BUILD and CXX_BUILD

## Related Issues

#8501

## Related Pull Requests

#8501

## Reviewers

@meleu @orbea @twinaphex @leiradel

### CODE REVIEW

**Comment by Jamiras** [comment]
Linux C89_BUILD > success

Linux CXX_BUILD:
```
LD retroarch
obj-unix/release/gfx/drivers_context/wayland_ctx.o: In function `registry_handle_global(void*, wl_registry*, unsigned int, char const*, unsigned int)':
wayland_ctx.c:(.text+0x1f52): undefined reference to `zxdg_decoration_manager_v1_interface'
wayland_ctx.c:(.text+0x20a3): undefined reference to `xdg_wm_base_interface'
wayland_ctx.c:(.text+0x2153): undefined reference to `zwp_idle_inhibit_manager_v1_interface'
collect2: error: ld returned 1 exit status
Makefile:195: recipe for target 'retroarch' failed
make: *** [retroarch] Error 1
```

Linux normal build:
```
gfx/drivers_context/wayland_ctx.c:629:29: error: unknown type name ‘wl_surface’; did you mean ‘EGLSurface’?
 static void wl_nop(void *a, wl_surface *b, wl_output *c)
                             ^~~~~~~~~~
                             EGLSurface
gfx/drivers_context/wayland_ctx.c:629:44: error: unknown type name ‘wl_output’
 static void wl_nop(void *a, wl_surface *b, wl_output *c)
                                            ^~~~~~~~~
CC gfx/common/wayland/xdg-shell.c
gfx/drivers_context/wayland_ctx.c:638:5: error: ‘wl_nop’ undeclared here (not in a function); did you mean ‘wl_api’?
     wl_nop,
     ^~~~~~
     wl_api
CC gfx/common/wayland/xdg-shell-unstable-v6.c
Makefile:199: recipe for target 'obj-unix/release/gfx/drivers_context/wayland_ctx.o' failed
make: *** [obj-unix/release/gfx/drivers_context/wayland_ctx.o] Error 1
```

**Comment by twinaphex** [comment]
Thanks @Jamiras

**Comment by twinaphex** [comment]
Hi @Jamiras, I still get these errors with CXX_BUILD -

CC deps/rcheevos/src/rcheevos/condset.c
In file included from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.0/include/stddef.h:1,
                 from deps/rcheevos/src/rcheevos/internal.h:6,
                 from deps/rcheevos/src/rcheevos/trigger.c:1:
deps/rcheevos/src/rcheevos/trigger.c: In function 'int rc_trigger_size(const char*)':
deps/rcheevos/src/rcheevos/internal.h:10:66: error: types may not be defined within __builtin_offsetof
 #define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                                                  ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: in expansion of macro 'RC_ALIGNOF'
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c:45:10: note: in expansion of macro 'RC_ALLOC'
   self = RC_ALLOC(rc_trigger_t, &parse);
          ^~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c: In function 'rc_trigger_t* rc_parse_trigger(void*, const char*, lua_State*, int)':
deps/rcheevos/src/rcheevos/internal.h:10:66: error: types may not be defined within __builtin_offsetof
 #define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                                                  ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: in expansion of macro 'RC_ALIGNOF'
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c:57:10: note: in expansion of macro 'RC_ALLOC'
   self = RC_ALLOC(rc_trigger_t, &parse);
          ^~~~~~~~
CC deps/rcheevos/src/rcheevos/condition.c
make: *** [Makefile:199: obj-unix/release/deps/rcheevos/src/rcheevos/trigger.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.0/include/stddef.h:1,
                 from deps/rcheevos/src/rcheevos/internal.h:6,
                 from deps/rcheevos/src/rcheevos/condset.c:1:
deps/rcheevos/src/rcheevos/condset.c: In function 'rc_condset_t* rc_parse_condset(const char**, rc_parse_state_t*)':
deps/rcheevos/src/rcheevos/internal.h:10:66: error: types may not be defined within __builtin_offsetof
 #define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                                                  ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: in expansion of macro 'RC_ALIGNOF'
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/condset.c:31:10: note: in expansion of macro 'RC_ALLOC'
   self = RC_ALLOC(rc_condset_t, parse);
          ^~~~~~~~
CC deps/rcheevos/src/rcheevos/operand.c
make: *** [Makefile:201: obj-unix/release/deps/rcheevos/src/rcheevos/condset.o] Error 1
In file included from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.0/include/stddef.h:1,
                 from deps/rcheevos/src/rcheevos/internal.h:6,
                 from deps/rcheevos/src/rcheevos/condition.c:1:
deps/rcheevos/src/rcheevos/condition.c: In function 'rc_condition_t* rc_parse_condition(const char**, rc_parse_state_t*)':
deps/rcheevos/src/rcheevos/internal.h:10:66: error: types may not be defined within __builtin_offsetof
 #define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                                                  ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: in expansion of macro 'RC_ALIGNOF'
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/condition.c:11:10: note: in expansion of macro 'RC_ALLOC'
   self = RC_ALLOC(rc_condition_t, parse);
          ^~~~~~~~
make: *** [Makefile:201: obj-unix/release/deps/rcheevos/src/rcheevos/condition.o] Error 1

**Comment by Jamiras** [comment]
What command do I need to duplicate that? If I just do a `./configure` and `make CXX_BUILD=1` in my  64bit mingw console on RetroArch master, it runs to completion. 
```
...
CC deps/rcheevos/src/rcheevos/condset.c
CC deps/rcheevos/src/rcheevos/condition.c
...
CC menu/drivers_display/menu_display_gdi.c
CC tasks/task_decompress.c
LD retroarch
```
The only obvious difference I can see is that my `/mingw64/lib/gcc/...` folder is 7.3.0 instead of 8.2.0.

**Comment by orbea** [comment]
Fwiw `CXX_BUILD` seems to be working with mingw in my travis test build.

**Comment by orbea** [comment]
`C89_BUILD` still needs to be fixed in rcheevos.

gcc
```
CC deps/rcheevos/src/rcheevos/trigger.c
In file included from deps/rcheevos/src/rcheevos/internal.h:6,
                 from deps/rcheevos/src/rcheevos/trigger.c:1:
deps/rcheevos/src/rcheevos/trigger.c: In function ‘int rc_trigger_size(const char*)’:
deps/rcheevos/src/rcheevos/internal.h:10:66: error: types may not be defined within __builtin_offsetof
 #define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                                                  ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: in expansion of macro ‘RC_ALIGNOF’
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c:45:10: note: in expansion of macro ‘RC_ALLOC’
   self = RC_ALLOC(rc_trigger_t, &parse);
          ^~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c: In function ‘rc_trigger_t* rc_parse_trigger(void*, const char*, lua_State*, int)’:
deps/rcheevos/src/rcheevos/internal.h:10:66: error: types may not be defined within __builtin_offsetof
 #define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                                                  ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: in expansion of macro ‘RC_ALIGNOF’
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c:57:10: note: in expansion of macro ‘RC_ALLOC’
   self = RC_ALLOC(rc_trigger_t, &parse);
          ^~~~~~~~
make: *** [obj-unix/release/deps/rcheevos/src/rcheevos/trigger.o] Error 1
make: *** Waiting for unfinished jobs....
```
clang
```
CC deps/rcheevos/src/rcheevos/format.c
deps/rcheevos/src/rcheevos/alloc.c:53:2: error: no newline at end of file [-Werror,-Wnewline-eof]
}
 ^
1 error generated.
```

**Comment by Jamiras** [comment]
It seems like you're both seeing the same error, but at different times. I don't see it either time. It looks like it wants the struct to be removed from within the `offsetof` macro, which I switched to, replacing the `RC_OFFSETOF` macro @leiradel added [here](https://github.com/RetroAchievements/rcheevos/commit/7a25d015730fb7703c42b06643981829b05da1e6#diff-6c611697043371fc9f330a9ece88dbc2).

Both approaches are listed [here](https://stackoverflow.com/questions/28460987/c-get-type-alignment-portably)

With the RC_OFFSETOF macro, I get this error:
```
deps/rcheevos/src/rcheevos/internal.h:14:43: error: types may not be defined in casts
  #define RC_ALIGNOF(t) RC_OFFSETOF(struct {char c; t d;}, d)
                                           ^
deps/rcheevos/src/rcheevos/internal.h:13:49: note: in definition of macro 'RC_OFFSETOF'
  #define RC_OFFSETOF(s, f) ((int)(long long)(&((s*)0)->f))
                                                 ^
```
If either of you have any ideas how to address this, I would appreciate the help.

**Comment by meleu** [comment]
Guys, sorry for the trouble inserted by my PR. At least I got a lesson learned: **test every commit against `CXX_BUILD` and `C89_BUILD`**.

Integrating rcheevos into RetroArch as a very important step for us, cheevos enthusiasts.

Many thanks for all the effort put here! :heart:

**Comment by twinaphex** [comment]
No problem @meleu, it's all a worthy learning experience.

**Comment by orbea** [comment]
The clang issue is easy to fix, how does contributing to rcheevos work? Should I just make PRs here?

**Comment by Jamiras** [comment]
rcheevos has its own repository: https://github.com/RetroAchievements/rcheevos
but as RetroArch is using a copy of the code the change has to be made in both places, so a PR for either would suffice.

**Comment by orbea** [comment]
@Jamiras Can you tell us a bit about your build environment? What OS and compilers are you using?

I'm not sure about the CXX_BUILD issue either, but I can reproduce it locally too where the previous error was with travis. For reference here is the error clang makes.
```
CC deps/rcheevos/src/rcheevos/trigger.c
deps/rcheevos/src/rcheevos/trigger.c:45:10: error: '_unnamed45' cannot be defined in a type specifier
  self = RC_ALLOC(rc_trigger_t, &parse);
         ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: expanded from macro 'RC_ALLOC'
#define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                           ^
deps/rcheevos/src/rcheevos/internal.h:10:39: note: expanded from macro 'RC_ALIGNOF'
#define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                      ^
deps/rcheevos/src/rcheevos/internal.h:9:21: note: expanded from macro 'RC_TAG'
#define RC_TAG(x,y) RC_TAG2(x,y)
                    ^
deps/rcheevos/src/rcheevos/internal.h:8:22: note: expanded from macro 'RC_TAG2'
#define RC_TAG2(x,y) x ## y
                     ^
<scratch space>:9:1: note: expanded from here
_unnamed45
^
deps/rcheevos/src/rcheevos/trigger.c:57:10: error: '_unnamed57' cannot be defined in a type specifier
  self = RC_ALLOC(rc_trigger_t, &parse);
         ^
deps/rcheevos/src/rcheevos/internal.h:12:76: note: expanded from macro 'RC_ALLOC'
#define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                           ^
deps/rcheevos/src/rcheevos/internal.h:10:39: note: expanded from macro 'RC_ALIGNOF'
#define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
                                      ^
deps/rcheevos/src/rcheevos/internal.h:9:21: note: expanded from macro 'RC_TAG'
#define RC_TAG(x,y) RC_TAG2(x,y)
                    ^
deps/rcheevos/src/rcheevos/internal.h:8:22: note: expanded from macro 'RC_TAG2'
#define RC_TAG2(x,y) x ## y
                     ^
<scratch space>:11:1: note: expanded from here
_unnamed57
^
2 errors generated.
make: *** [Makefile:201: obj-unix/release/deps/rcheevos/src/rcheevos/trigger.o] Error 1
```

**Comment by Jamiras** [comment]
I'd recommend making the fix here and it's an immediate issue here. Then meleu or I can make sure it happens upstream.

**Comment by twinaphex** [comment]
Yeah, I agree.

**Comment by Jamiras** [comment]
My primary development environment is Windows. I usually use VS2017 (RetroArch-msvc2017.sln) for build/debug. I have an Ubunutu18 VM specifically for doing Linux builds and followed the steps [here](https://docs.libretro.com/development/retroarch/compilation/ubuntu/) to build RetroArch. I also have mingw installed for those times when it is needed.

**Comment by orbea** [comment]
From what I can tell from travis and my local builds its only with linux and maybe only some compiler versions? Have you tried both gcc and clang? What versions?

You can find out with:
```
g++ -dumpversion
```
and
```
clang++ --version
```

**Comment by Jamiras** [comment]
No. How do I make RetroArch target `g++` or `clang++`?

`g++` reports "7". `clang++` does not appear to be installed.

**Comment by orbea** [comment]
You can pass `CC` and `CXX` to configure as environment variable to target specific compiler binaries.

For example I build with clang like this.
```
CC=clang CXX=clang++ ./configure
make
```

**Comment by Jamiras** [comment]
I'll give that a try, but I could still use some insight on how to address the underlying issue: how to implement `alignof` ([C++11 feature](https://en.cppreference.com/w/cpp/language/alignof)) in a way that works for all of the various builds.

**Comment by orbea** [comment]
@hhromic This might be the kind of thing you can help with if you would be so kind. :)

**Comment by twinaphex** [comment]
Best not to use these newer constructs please, same with offsetof/alignof. It's not portable enough.

**Comment by Jamiras** [comment]
`offsetof` already occurs 170+ times in the repository, so I thought it was safe to use. I understand that c++11 features are not, so I didn't go all the way to `alignof`. 

Maybe [this](https://github.com/libretro/RetroArch/blob/master/gfx/include/userland/interface/khronos/common/khrn_int_util.h#L432-L438) will work.

**Comment by twinaphex** [comment]
You might have a point about offsetof, although I do feel we should not add to the problem at the expense of portability. The files for which they are used generally assume a compiler with a higher supported C / C++ version, but generally we tend to prefer to err on the side of caution and go for the lowest requirements possible per source file. Cheevos should definitely be a feature that should be available from the low end to the high end.

**Comment by twinaphex** [comment]
That being said, we can try what you suggested.

**Comment by orbea** [comment]
I tried this.
```
diff --git a/deps/rcheevos/src/rcheevos/internal.h b/deps/rcheevos/src/rcheevos/internal.h
index 18b123e871..a0b0cd8265 100644
--- a/deps/rcheevos/src/rcheevos/internal.h
+++ b/deps/rcheevos/src/rcheevos/internal.h
@@ -7,7 +7,14 @@
 
 #define RC_TAG2(x,y) x ## y
 #define RC_TAG(x,y) RC_TAG2(x,y)
-#define RC_ALIGNOF(t) offsetof(struct RC_TAG(_unnamed, __LINE__) {char c; t d;}, d)
+
+#ifdef _MSC_VER
+   #define RC_ALIGNOF(T) __alignof(T)
+#elif defined(__CC_ARM)
+   #define RC_ALIGNOF(T) __alignof__(T)
+#else
+   #define RC_ALIGNOF(T) (sizeof(struct { T t; char ch; }) - sizeof(T))
+#endif
 
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
```
and got this error with `CXX_BUILD=1`.
```
CC deps/rcheevos/src/rcheevos/trigger.c
In file included from deps/rcheevos/src/rcheevos/trigger.c:1:
deps/rcheevos/src/rcheevos/trigger.c: In function ‘int rc_trigger_size(const char*)’:
deps/rcheevos/src/rcheevos/internal.h:16:41: error: types may not be defined in ‘sizeof’ expressions
    #define RC_ALIGNOF(T) (sizeof(struct { T t; char ch; }) - sizeof(T))
                                         ^
deps/rcheevos/src/rcheevos/internal.h:19:76: note: in expansion of macro ‘RC_ALIGNOF’
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c:45:10: note: in expansion of macro ‘RC_ALLOC’
   self = RC_ALLOC(rc_trigger_t, &parse);
          ^~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c: In function ‘rc_trigger_t* rc_parse_trigger(void*, const char*, lua_State*, int)’:
deps/rcheevos/src/rcheevos/internal.h:16:41: error: types may not be defined in ‘sizeof’ expressions
    #define RC_ALIGNOF(T) (sizeof(struct { T t; char ch; }) - sizeof(T))
                                         ^
deps/rcheevos/src/rcheevos/internal.h:19:76: note: in expansion of macro ‘RC_ALIGNOF’
 #define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
                                                                            ^~~~~~~~~~
deps/rcheevos/src/rcheevos/trigger.c:57:10: note: in expansion of macro ‘RC_ALLOC’
   self = RC_ALLOC(rc_trigger_t, &parse);
          ^~~~~~~~
make: *** [Makefile:201: obj-unix/release/deps/rcheevos/src/rcheevos/trigger.o] Error 1
```

**Comment by Jamiras** [comment]
Sigh, it worked for the C89 build on both Linux and MinGW, but failed the CXX build on both.

**Comment by Jamiras** [comment]
I dislike having to specify every type exposed to the macro, but this seems to work for all of my builds. @orbea - can you verify?
```
#ifndef INTERNAL_H
#define INTERNAL_H

#include "rcheevos.h"

#define RC_ALLOW_ALIGN(T) struct __align_ ## T { char ch; T t; };
RC_ALLOW_ALIGN(rc_condition_t)
RC_ALLOW_ALIGN(rc_condset_t)
RC_ALLOW_ALIGN(rc_expression_t)
RC_ALLOW_ALIGN(rc_lboard_t)
RC_ALLOW_ALIGN(rc_memref_value_t)
RC_ALLOW_ALIGN(rc_operand_t)
RC_ALLOW_ALIGN(rc_richpresence_t)
RC_ALLOW_ALIGN(rc_richpresence_display_t)
RC_ALLOW_ALIGN(rc_richpresence_display_part_t)
RC_ALLOW_ALIGN(rc_richpresence_lookup_t)
RC_ALLOW_ALIGN(rc_richpresence_lookup_item_t)
RC_ALLOW_ALIGN(rc_term_t)
RC_ALLOW_ALIGN(rc_trigger_t)
RC_ALLOW_ALIGN(rc_value_t)
RC_ALLOW_ALIGN(char)

#define RC_ALIGNOF(T) (sizeof(struct __align_ ## T) - sizeof(T))

#define RC_ALLOC(t, p) ((t*)rc_alloc((p)->buffer, &(p)->offset, sizeof(t), RC_ALIGNOF(t), &(p)->scratch))
...
```

**Comment by orbea** [comment]
That seems to build fine here too.

**Comment by twinaphex** [comment]
OK, we'll go with that then for now.

**Comment by twinaphex** [comment]
Pushed -

https://github.com/libretro/RetroArch/commit/b5ba2ddc7b4c467a2551c65fc079021d89c9ef81

**Comment by hhromic** [comment]
Just read this message, sorry!  But I see you got it sorted out for the moment! :)

**Pull request merged**
