### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by CyberLabSystems**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

Change "their" to "his" in the credits because it's the appropriate pronoun.
Remove "PSX" from the filenames because they don't seem to work with any currently available PSX core.

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

@hunterk

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I think some PSX games have 256 px width. Maybe it works with those?

**Comment by GABO1423** [comment]
You should remove the `e -i HEAD~5` file from this PR. It's just a garbage file.

**Comment by CyberLabSystems** [comment]
> I think some PSX games have 256 px width. Maybe it works with those?

It might be worth some further testing then. For what it's worth, the SNES filters behind these presets also don't seem to work in the Nestopia core (nothing seems to change) and those games are also 256 px wide.

**Comment by CyberLabSystems** [comment]
> You should remove the `e -i HEAD~5` file from this PR. It's just a garbage file.

Thanks, I'll remove it. It was my first time using rebase to try to edit something rather than to simply delete my branch and start over, which would have been much easier but I would have learned a lot less. My apologies.

**Comment by Tatsuya79** [comment]
They work in 16bits but not 32bits color with FBNeo.
It's up to the color format, like they are working for pcsx-rearmed.

**Comment by CyberLabSystems** [comment]
> They work in 16bits but not 32bits color with FBNeo.
> It's up to the color format, like they are working for pcsx-rearmed.

Okay thanks. Seeing that you can confirm that they are working for PCSX-Rearmed, I will revert to the previous filenames but I will keep the small change in the credits.

**Pull request closed without merging**
