### PR TITLE
Implement support for xdg-decoration

### PR DESCRIPTION
**Pull request by Sunderland93**
## Description

This PR add's support for [xdg-decoration-unstable-v1](https://cgit.freedesktop.org/wayland/wayland-protocols/tree/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml) Wayland protocol, which the request compositor to create server-side window decoration. Because RetroArch doesn't have their own (client) window decoration, request for SSD is forced. xdg-decoration protocol currently implemented only in Sway and Rootston (and probably other [wlroots](https://github.com/swaywm/wlroots)-based compositors). I wanted to add KDE's Server-Decoration protocol as fallback (mostly for KDE), but depend on DE-specific stuff is not good idea, and Plasma devs maybe implement xdg-decoration in 5.15. I also increase minimal Wayland and wayland-protocols versions to 1.15.  The main problem is GNOME: it doesn't have support for SSD, and promotes CSD everywhere. There is 2 solutions:

1. add support for CSD in RetroArch (very simple window decoration);
2. hope that the GNOME devs will implement xdg-decoration eventually.

Screenshots from Rootston:

retroarch_rootston

## Related Issues

https://github.com/libretro/RetroArch/issues/6278 https://github.com/libretro/RetroArch/issues/4778 https://github.com/libretro/RetroArch/issues/6606

### CODE REVIEW

**Comment by twinaphex** [comment]
I am still able to use Weston right?

**Comment by Sunderland93** [comment]
@twinaphex of course

wayland-screenshot-2018-12-09_23-48-24

**Comment by twinaphex** [comment]
OK, let's merge this then. 

What was this about files being generated BTW? If at all possible, I'd prefer files are not generated at runtime and are at least committed to the repository instead. Can you shed some light on that?

**Comment by davidedmundson** [comment]
>and Plasma devs maybe implement xdg-decoration in 5.15.

It will be. Don't bother with the KDE version.

**Comment by Sunderland93** [comment]
Thanks, now it works perfectly in Plasma git

screenshot_20190103_210129

**Pull request merged**
