### PR TITLE
Add support for core option sublabels

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

At present, sublabels are supported for all menu entries apart from core options. This is a slightly unfortunate shortcoming, since some cores have options that are rather inscrutable without consulting the documentation.

As requested by @hhromic, this PR adds support for core option sublabels. It is implemented as follows:

We have a new `retro_core_option_definition` struct:

```c
struct retro_core_option_definition
{
   /* Variable to query in RETRO_ENVIRONMENT_GET_VARIABLE. */
   const char *key;

   /* Human-readable core option description (used as menu label) */
   const char *desc;

   /* '|' delimited list of expected values. */
   const char *values;

   /* Human-readable core option information (used as menu sublabel) */
   const char *info;
};
```

...and two new environment callbacks:

`RETRO_ENVIRONMENT_GET_ENHANCED_CORE_OPTIONS`
`RETRO_ENVIRONMENT_SET_CORE_OPTIONS`

At present, core options are set via an array of retro_variable structs:

`environ_cb(RETRO_ENVIRONMENT_SET_VARIABLES, struct retro_variable[]);`

This can still be used in any case, but if `RETRO_ENVIRONMENT_GET_ENHANCED_CORE_OPTIONS` returns `true` then we may alternatively set core options via an array of `retro_core_option_definition` structs:

`environ_cb(RETRO_ENVIRONMENT_SET_CORE_OPTIONS, struct retro_core_option_definition[]);`

It's basically as simple as that. The code changes are minimally invasive, and there should be no frontend<->core compatibility issues in either direction.

This [PokeMini PR](https://github.com/libretro/PokeMini/pull/23) serves as an example of how to implement sublabels on the core side (it's very easy). And here are some screenshots of the results:

**No sublabels**

Screenshot_2019-07-09_15-38-19

**Sublabels**

Screenshot_2019-07-09_15-28-01

## Reviewers

Since this makes an addition to the API, I would be grateful if @twinaphex and @bparker06 could review the changes before they are merged.

### CODE REVIEW

**Comment by twinaphex** [comment]
OK, this needs two things:

* A new GET_VARIABLES callback. Right now, to query the 'values' state of each and every core option, we have to do a GET_VARIABLE call per core option. This can add up if you have more than 10 core options or so. I'd like a new callback 'GET_VARIABLES', exclusively for this new core option interface, that would allow us to just make one call and grab the state of all core options that way. That way, if we have 10 core options, instead of 10 calls we'd only have to do 1.

* This needs localization support, a very important consideration since we now support multiple languages.

Other than that, great!

**Comment by twinaphex** [comment]
Another good design consideration:

* Maybe also consider adding a 'type' of some sort, so that each core option could be presented differently in the frontend. I'm thinking of core options where it might be desirable for the user to input text on the frontend side instead of just being able to select from a predefined separator list of values.

**Comment by fr500** [comment]
If you're improving core options why not do it right once? If you do it
like this just one limitation is lifted and the whole system remains
limited.
What I mean with this is support numeric values, boolean values, and
arbitrary text entry.

Just a suggestion.

**Comment by twinaphex** [comment]
Yes, that's more or less what I already suggested. But yes, that's what I meant by the types and the text input.

@jdgleaver's current work is a good base to build upon though, so I think the current core options could be the 'default' type, and then we could have other types next to that.

**Comment by hizzlekizzle** [comment]
Rather than calling them "enhanced", would it make sense to version them? That way, if we eventually have a libretro 4.0, we don't have to say "includes enhanced-ultra-turbo-champion-edition core options"?

**Comment by twinaphex** [comment]
I'll discuss this more with @jdgleaver and we'll probably come back with a newer version of this.

**Comment by fr500** [comment]
Core options structure should not be text based (other than for text
options)
So many things are void*, why not options

So it should be feasible to have an enum with the actual types

RETRO_VARIABLE_INTEGER
RETRO_VARIABLE_FLOAT

and parameters for each option
void* min, max, step for numeric values.


Something like that.
No point enhancing something piecemeal just to have people adopt it and
then enhance again forcing everyone to move to a third variant.

**Comment by twinaphex** [comment]
OK, hopefully it's feasible and practical enough for @jdgleaver to whip something up there.

The current default (separator-based string lists) should also be a type.

**Comment by hhromic** [comment]
Great stuff @jdgleaver !  And thanks for making this, appreciated!
I also would advocate for revamping the options system with these ideas if we are to implement new API env calls.  The option type stuff etc.
What I wouldn't do is to create a "default" entry, that would imply adapting the cores (even if little) anyway and in this case better would be to migrate the options fully to the new systme.
What I would suggest is to keep the current system as legacy and implement a completely new system alongisde. Cores then have plenty of time to migrate to the new system (and if not they still continue to work) and at some point the legacy options API simply is deprecated and eliminated.
I will keep an eye on the converation.  Cheers again!

**Comment by twinaphex** [comment]
Let me put some clear boundaries on this: 
the current core options interface will NOT be eliminated for this current API.

The core maker will need to implement at least the old core options API, and from there on preferably the newer one as well in case the extra features are needed (which in most instances will be the case). 

If the new one is not implemented, the frontend should just present the old core options implementation instead.

Removing the old interface would constitute an ABI break. Anyway, I think it's clear now what @jdgleaver should do, so let the suggestions be a feature freeze for now while he takes these ideas into consideration.

**Comment by hhromic** [comment]
Yes, all of that is exactly what I meant. Sorry if I wasn't clear too.
We are on the same page, definitively.

**Comment by twinaphex** [comment]
@hhromic OK, no problem.

**Comment by orbea** [comment]
Just pointing out that this PR seems to address my issue here. https://github.com/libretro/libretro-common/issues/35

**Comment by jdgleaver** [comment]
Hi everyone!

Thanks for the input. Due to unresolvable merge conflicts I'm going to have to re-do this one.

I'll be making a new and improved PR hopefully tomorrow or Friday  :)

**Comment by jdgleaver** [comment]
Closing this in favour of the new PR I'm just about to make...

**Pull request closed without merging**
