### PR TITLE
 Fix getDefaultConfigPath not correctly looking up external and internal data directories

### PR DESCRIPTION
**Pull request by PetePriority**
getDefaultConfigPath was not correctly looking up internal and external storage dirs. Instead, it returned a wrong path (/data/data/com.retroarch/ instead of /data/data/com.retroarch/files) and also defaulted to private internal storage.

With this patch, it first checks whether external storage is available. If not, it uses the private storage in /data/data/com.retroarch/files and configuration changes should now be persistent.
If external storage is present, it will save the configuration files in /sdcard/emulated/legacy/Android/data/com.retroarch/files, where the configuration is user accesible, even if the device is not rooted.

### CODE REVIEW

**Comment by twinaphex** [comment]
That sounds a lot better than the current default, yeah.

**Comment by fr500** [comment]
does this work only with removable cards? for me it still defaulted to /data/data/com.retroarch (in my nexus5)

**Comment by fr500** [comment]
actually, no! it works, the config is saved now in the /sdcard/Android/data/com.retroarch/files
Now we need to make sure saves, states and other user data is saved there too!

**Comment by blockfeed** [comment]
Data point: On a Nexus 6 (5.0.2 rooted, no external SD), /data/data/com.retroarch/files appears to be empty, and Retroarch is saving files to /sdcard/Android/data/com.retroarch.

**Comment by fr500** [comment]
The location for retroarch.cfg is correct.
My DS3 works fine at least

**Comment by vonguard** [comment]
Tried on a Lenovo A1000 Android 4.1.2

Saving configs internally by default to /Android/data/com/retroarch/files/retroarch.cfg 
Nothing is saving on quitting retroarch. I can save config as new and load it again by hand, but nothing seems to displace this default config file, and nothing is being saved to it.

This was all to get some button configs changed on a wired controller, and save as new works fine, but even renaming that save as new file and moving it to the /files/ dir and renaming it retroarch.cfg results in nothing having been saved. It's as if it's writing a new, fresh config file everytime it loads.

I reinstalled, flushed, everything. This is as of nightly build for April 8, 2015

**Pull request merged**
