### PR TITLE
Sideload

### PR DESCRIPTION
**Pull request by fr500**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by fr500** [comment]
@twinaphex I don't think it's fair to ask contributors to reimplement their feature using some internal not-documented, not used wrappers.

Re-implementation using such wrappers should happen at the project lead side of things.

**Comment by fr500** [comment]
Anyway moved file copy to a function, maybe someone else wants to finish it up I'm done with this feature.

**Comment by fr500** [comment]
image

**Comment by hizzlekizzle** [comment]
Whether this gets moved to the VFS or not, I think it's an important feature to have, since the online updater is the only way to get cores into the Android version, and that can be a problem for people who have internet troubles (like a particularly abrasive fellow on the forum right now).

**Comment by fr500** [comment]
Closing for now

**Pull request closed without merging**
