### PR TITLE
android: enable sustained performance mode if supported

### LINKED ISSUE #5316: Implement android sustained performance mode
This would prevent throttling on android 7 and above:
[Sustained Performance API](https://developer.android.com/about/versions/nougat/android-7.0.html#sustained_performance_api)

You can use PPSSPP as an example:
[PPSSPP SPF Implementation](https://github.com/hrydgard/ppsspp/pull/9901)

### PR DESCRIPTION
**Pull request by bparker06**
Fixes #5316.

I'm assuming this is something we do want to have enabled all the time? I know PPSSPP makes it an option, but do we really need that? If so I can add it (and let me know the default setting).

Also do note that this bumps the target API from 23 to 24. Would appreciate testing from @fr500 and/or @meepingsnesroms if needed. Unfortunately I'm not sure how to actually test this feature.

### CODE REVIEW

**Comment by bparker06** [comment]
If anyone needs an apk to test, I put one up here: http://buildbot.libretro.com/.bp/retroarch-release.apk

It does not include any assets or additional files, just the binary itself.

**Comment by xTMODx** [comment]
I would make it an option and off by default, so people with overheating issues can turn it on.

**Comment by bparker06** [comment]
@xTMODx I'm still a bit confused as to the actual intent of this feature. In the original issue report, it said that it "would prevent throttling", which I assume would be the opposite effect of what happens in an overheating situation (e.g. throttling clocks down, not up). I assumed that "sustained performance" meant "always good performance", but I may be mistaken there... and the API docs only say that it provides a "predictable, consistent level of device performance".

Do you know of any better documentation on this?

**Comment by fr500** [comment]
From what I read sustainable performance mode is overall slower. For a
device like the Shield ATV with active cooling it could do more harm than
not, but for people for handsets it maybe good.
I think it should be optional, on by default? I guess

**Comment by xTMODx** [comment]
No sorry i dont know anything about it.
I just played 30min BSNES Mercury Balanced core and the framerates dropped after 20min playing, maybe the cpu was throttled i dont know

**Comment by twinaphex** [comment]
OK, I discussed with @bparker06 what we should do. We agreed on the following:

1 - I will merge this right now in its current state.
2 - I will add a 'Power Management' submenu to Settings.
3 - After this is done, @bparker06 will make a new PR adding a setting for enabling/disabling Sustained performance mode.

If everybody can live with this, I'd like to act on this and merge this so we can get this done.

**Comment by bparker06** [comment]
added the option in #6898

**Pull request merged**
