### PR TITLE
(RGUI) Allow selection of thumbnail downscaling method

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new 'Thumbnail Downscaling Method' setting to the RGUI 'User Interface > Appearance' menu. Three options are provided, in order of increasing performance requirements:

1. 'Nearest Neighbour (Fast)': Uses the existing (custom) method established in PR #8065. Should be light enough to use on any hardware

2. 'Bilinear': Somewhat blurry (I think it looks worse than Nearest Neighbour!), but it smooths out the jaggies. Fairly lightweight. Uses the standard libretro-common scaler (which is a nice piece of code, by the way).

3. 'Sinc/Lanczos3 (Slow)': Very high quality (although sometimes generates artefacts when source image contains dithering). Probably too heavy for junk-tier devices, but has no discernable performance impact on desktop-class hardware. Uses the standard libretro-common scaler.

Here are some examples:

### Nearest Neighbour (Fast)

screenshot_2019-01-23_16-25-42

screenshot_2019-01-23_16-29-05

screenshot_2019-01-23_16-31-10

screenshot_2019-01-23_16-31-41

### Bilinear

screenshot_2019-01-23_16-32-31

screenshot_2019-01-23_16-33-18

screenshot_2019-01-23_16-33-51

screenshot_2019-01-23_16-34-07

### Sinc/Lanczos3 (Slow)

screenshot_2019-01-23_16-34-50

screenshot_2019-01-23_16-35-10

screenshot_2019-01-23_16-35-45

screenshot_2019-01-23_16-36-02

Essentially, with this PR desktop users of RGUI no longer have any need to resize large thumbnails by hand, since maximum quality downscaling can be achieved in real time.

## Related Pull Requests

#8065

### CODE REVIEW

**Comment by hhromic** [comment]
Also another curiousity question, is this only "downscaling" images? I.e. if there are really small thumbnails, are they upscaled instead?  If so, perhaps the option should be named just "thumbnail_scaler".

**Comment by hhromic** [comment]
Yes I agree it's currently very good. I was just wondering how it worked more in detail.
Looking forward for this feature to land in a stable version of RA!  Thanks for all your work.

**Comment by jdgleaver** [comment]
Thanks for the kind words! :slightly_smiling_face: 

I'm also planning to add wallpaper (background image) support to RGUI, but I probably won't have time to look at this until next week. RGUI is the only menu driver that runs on everything - might as well make it as pretty as possible!

**Comment by hhromic** [comment]
Agreed!  Looking forward, whenever you can, I understand very well what is not to have time for these nice things :( :(

**Pull request merged**
