### PR TITLE
Restore resolution fix

### PR DESCRIPTION
**Pull request by alphanu1**
Add new code to fix resolution restore on exit. Also re moved the old obsolete code.

@twinaphex @bparker06 

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by alphanu1** [comment]
Add new code to fix resolution restore on exit. Also removed the old obsolete code.

@twinaphex @bparker06

**Comment by alphanu1** [comment]
There have been many responses about being stuck in 240p on exit. Both on the forum and YouTube.

**Comment by twinaphex** [comment]
Please make sure that resolution restore function doesn't mess up yet again like it did before normal systems that have no need for this CRT SwitchRes stuff. The reason why I don't want it invoked by default is because my system is setup so that it switches to a custom fullscreen resolution (3840x2160) that is Nvidia DSR. With the 'restore original resolution' hack that you implemented, it would then switch my screen resolution upon exit of RA to something undesirable. 

Please make sure that under no circumstance does that 'restore original resolution' thing do anything unless CRT SwitchRes is explicitly enabled.

**Comment by twinaphex** [comment]
I will have to check if this PR right now reintroduces the issue I had before - I will do that later tomorrow.

**Comment by alphanu1** [comment]
Ok, I did think this through the switch resolution fuction does not run unless CRT switch is enabled. So it will leave orig_width and orig_height at 0. So on exit it will ask windows if 0x0@60 exits, which it will not so no switching will happen.

@twinaphex

**Comment by twinaphex** [comment]
OK, sounds like it will probably address the issue I had before. 

I will test this first thing in the morning, and if all is well, merge it. Thanks

**Comment by alphanu1** [comment]
Let me know what issues you have if any. I'll try to sort it ASAP considering it's now the stable version.

**Comment by alphanu1** [comment]
Just made a small change to prevent any unwanted switching.

**Pull request merged**
