### PR TITLE
Fix #14870

### LINKED ISSUE #14870: BSV recording command code seems wrong
https://github.com/libretro/RetroArch/blob/d689a84581c02e7ec76a05eace0723f5ddd5b791/retroarch.c#L2152-L2162

I'm looking into adapting RetroArch for an application that includes input recording and replay, and I'm a bit confused as to why BSV recording seems to trigger command events for toggling video recording.  I don't think those command events should be sent at all, since it seems like `bsv_movie_check` already toggles the recording state for BSV.  If the intent is that BSV recording always comes with video recording, then instead of toggling the video record state it should be forced to match the BSV record state based on the result of `bsv_movie_check`.  But I think those two recording states should be kept separate, since I may want to record BSV but not video.

### PR DESCRIPTION
**Pull request by JoeOsborn**
## Description

This seems to fix two key issues for #14870 , namely that input recording seems to double-record inputs (or records an input and then an empty input) and that video recording should not always be toggled to the same state as BSV recording. 

## Issues

There are two main problems I want feedback on before this PR is ready to merge.

1. Save-state autoloading should not happen if BSV replay is happening.  I have code that I think should do this, but it doesn't seem to work and I need to explore it more deeply.
2. I'm not sure that my solution to avoid double-recording inputs is correct. I don't really understand the `input_state_device` or analog input paths, so I think this might only function properly for inputs coming through `input_driver_state_wrapper`.  So I'd love to have the perspective of that code's owner.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
The BSV feature has gone neglected for a long time and has only really been worked on in like the beginning parts of this project's inception (circa 2010-2012), so we're actually glad someone with interest is looking into this. IMHO, we can probably assume you're going about this the right way, and if any issues arise, you could always send followup PRs later. It's better than BSV going further neglected and a good starting point.

Let me know if you'd want to merge this.

**Comment by LibretroAdmin** [comment]
If you're talking about the input sources, there is a bunch of input sources that can send input to the input driver -

1) remote commands
2) overlay input (like, input overlay screens, where you click on a virtual gamepad's buttons)
3) regular gamepad/keyboard input

**Comment by JoeOsborn** [comment]
Your last comment there kind of frightens me (:

Trying out recording in Gambatte and Snes9x both seem to work fine.  For DOSBox-Pure, it only sort-of works---arrow keys seem to work, other keyboard inputs are just wrong, and the loading of the initial state in the BSV file doesn't work (although loading manual savestates is fine).  I can't seem to run any emulators with analog inputs (dolphin and flycast are both segfaulting on me), so I haven't been able to test those; interestingly, it does seem to work on the powder toy core so at least some non-controller devices ought to work.  I do think this patch improves things more than it breaks things, so I'll remove the WIP label and address other problems in other PRs.

**Comment by LibretroAdmin** [comment]
@JoeOsborn It might be the case that analog control recording was never implemented at the time, only digital D-pad. Might be a nice improvement if that is the case. I'm sorry but I'm not very familiar with the BSV code part.

**Comment by hizzlekizzle** [comment]
Analogs were definitely not part of the original spec. I'd be surprised if they were added at some point, too.

**Pull request merged**
