### PR TITLE
Travis + qb fixes.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This has 3 semi-related commits.

1. Fixes the Qt build for travis, doing this led to several other changes as well. These changes only affect the Linux builds.
* It now uses `gcc-8` and `clang-6.0` instead of `gcc-4` and `clang-3.8`.
* It now actually installs the SDL2 dependency now.
* Several unneeded dependencies which weren't actually being installed before have been removed. These either are pulled in by other packages or are now included by default with travis.
* It also exposes many qt warnings with `clang-6.0`.
2. It fixes an issue where systems that use `qtchooser` would default to the qt4 moc instead of the qt5 moc. This also dehardcodes the qt version from the qb scripts.
3. Fixes an issue where if the c++ compiler was not found or didn't work configure would print a warning that c++ features are disabled and then still fail trying to build them. Now it will actually disable them in such a case.

## Related Issues

Fixes https://github.com/libretro/RetroArch/issues/8028

## Related Pull Requests

https://github.com/libretro/RetroArch/pull/8036

## Reviewers

Please wait for travis to finish for the output to be reviewed!

### CODE REVIEW

**Comment by orbea** [comment]
The builds excluding xcode9.3 which is not affected by this PR all built so this should be good now.

**Comment by orbea** [comment]
The clang warnings appear all to be all inside the upstream qt headers and are probably fixed with a newer version of qt.

Updating the Qt version travis uses could be left for another PR or we could just wait it out as its using the minimally supported qt version in RetroArch now.

**Comment by bparker06** [comment]
Ideally we'd like to keep travis using the minimum Qt version so we'll know if someone makes an incompatible change.

**Comment by orbea** [comment]
Then this should be fine then with the minor inconvenience of very noisy logs for the travis clang build.

**Pull request merged**
