### PR TITLE
FFMPEG core frame based color conversion

### PR DESCRIPTION
**Pull request by hasenbanck**
## Description

Using an ordered ring buffer and a thread pool, the color space
conversion is now multi-threaded based on frames. I tried
to implement slice based threading, but libswscale did produced
corrupted pictures without obvious reason.

This approach introduces some more "lag" when decoding,
but shouldn't be affect the user negatively, since movie
watching is not lag sensitive, as long as the A/V is synchronized.

This PR will also change the default encoder to the software decoder
for now, since it's the most robust decoder and should produce
the best results for most users right now (Embedded systems
aren't particuarly well supported yet by the ffmpeg hw decodign backend).

### CODE REVIEW

**Comment by twinaphex** [comment]
Big speedup for me with dxva2 hw decoding - from 76fps to 166fps with the same video.

Can there be an 'auto' value  back too for "Use hardware decoding" too? This for the user that doesn't know what all these settings are. Of course the default can remain off, but just so that we have an option called 'auto' for the user that doesn't know what all these APIs are.

**Comment by hasenbanck** [comment]
The "auto" value should still be there. I just changed the order to:

```c
      { "ffmpeg_hw_decoder", "Use Hardware decoder (restart); off||auto"
         "cuda|d3d11va|drm|dxva2|mediacodec|opencl|qsv|vaapi|vdpau|videotoolbox" },
         "cuda|d3d11va|drm|dxva2|mediacodec|opencl|qsv|vaapi|vdpau|videotoolbox" },
```

Ahh f*ck.... I will correct the error I inserted here.

**Comment by hasenbanck** [comment]
The only issue left is the error that ASAN is throwing:

```gdb
Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x4e29b2 in calloc (/home/nils/Develop/RetroArch/retroarch+0x4e29b2)
    #1 0xf0485c in sthread_create_with_priority /home/nils/Develop/RetroArch/libretro-common/rthreads/rthreads.c:194:43
    #2 0x18abffa in tpool_create /home/nils/Develop/RetroArch/cores/libretro-ffmpeg/tpool.c:175:16
    #3 0x18a1957 in decode_thread /home/nils/Develop/RetroArch/cores/libretro-ffmpeg/ffmpeg_core.c:1580:15
    #4 0xf04b48 in thread_wrap /home/nils/Develop/RetroArch/libretro-common/rthreads/rthreads.c:146:4
    #5 0x7f532d16e668 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x9668)
```

Allocation in rthreads.c:194 that ASAN thinks that is never de-allocated.
```c
sthread_t *thread        = (sthread_t*)calloc(1, sizeof(*thread));
```

Would be great if somebody could also look into this error, since I don't really know if this is a proper error anyhow. The code detaches the threads right away, since they are a thread pool threads. This should be proper usage of the rthreads library, since the threads should de-allocate themselves judging from the documentation.

**Comment by hasenbanck** [comment]
Fixed the memory leak that ASAN found. Ready for merge.

**Pull request merged**
