### PR TITLE
 vietnamese translation as of Nov-16-2016

### PR DESCRIPTION
**Pull request by cudencuden**
2nd attempt

### CODE REVIEW

**Comment by lasers** [comment]
Too much paste? 
```
      case MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_VOLCANIC_RED:
         return "Đỏ (Núi Lửa)";
--
      case MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_VOLCANIC_RED:
         return "Volcanic Red";
--
      case MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_VOLCANIC_RED:
         return "Volcanic Red";
```

**Comment by cudencuden** [comment]
yeah...can i upload a file instead?

**Comment by lasers** [comment]
Try. Go for it.

**Comment by cudencuden** [comment]
"Uploads are disabled. File uploads require push access to this repository."

I will attach the file here as zip since .c is not allowed




[msg_hash_vn.zip](https://github.com/libretro/RetroArch/files/597341/msg_hash_vn.zip)

**Pull request closed without merging**
