### PR TITLE
qb: Improve the menu checks.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This greater ensures the `HAVE_MENU_WIDGETS`, `HAVE_RGUI`, `HAVE_MATERIALUI`, `HAVE_OZONE` and `HAVE_XMB` will never be defined when `HAVE_MENU` is not.

## Related Issues

This allows only checking if the specific feature is enabled and not that `HAVE_MENU` is also defined with processor code and some clean up in `Makefile.common`.

## Related Pull Requests

I noticed this was not correctly fixed as I previously thought in commit https://github.com/libretro/RetroArch/commit/2be5ffe4e999757ba89a87b0012d1441ec78af77.

### CODE REVIEW

**Comment by twinaphex** [comment]
The changes to qb itself is fine, but the ifdefs themselves I don't really agree with.

Because while that might cover the qb make system, we also use Griffin where every Makefile can have their own flags. Therefore I'd rather be safe than sorry and explicitly state which defines are needed.

**Comment by orbea** [comment]
Are there any griffin build systems that set `HAVE_MENU=0` and any of the menus to `1`? I would consider that a bug in that case where it should be fixed instead of being silently hidden as it would be now. So I respectively do not agree with that assessment.

**Comment by orbea** [comment]
Classic, you reject it for nonsensical reasons and then ignore any debate. Why do I even try?

**Comment by twinaphex** [comment]
My reason for not immediately merging this is for another reason - I want to make menu widgets independent of the menu code altogether. This includes also the menu animation code. That is why I don't want to immediately merge this PR overnight.

All of this could have been explained to you if you didn't immediately throw a childish temper tantrum like this. This continuing behavior whenever something isn't 100% implemented your way is making it harder and harder to continue to collaborate in a constructive manner with you TBH.

**Comment by orbea** [comment]
@twinaphex  Please stop censoring users, its very unprofessional.

**Comment by orbea** [comment]
> My reason for not immediately merging this is for another reason - I want to make menu widgets independent of the menu code altogether. This includes also the menu animation code. That is why I don't want to immediately merge this PR overnight.

Also since you obviously do not understand what I even was submitting let me point out this PR would of only made that task easier in the future where you would of needed to remove one line instead of dozens as is the current state in the code, but good job throwing out the baby with the bathwater. :)

**Pull request closed without merging**
