### PR TITLE
Netplay input upgrades 1

### PR DESCRIPTION
**Pull request by GregorR**
(Don't merge this just yet. Making a pull request so we can discuss UI issues and others can do some tests to make sure it's not totally broken. If a couple people do some tests over larger networks, it'll be OK for merge.)

I've abstracted the away a lot of the details of input in Netplay, so that, in particular, one Netplay client can use two controllers (e.g. Secret of Mana with one peer playing one player and the other peer playing two), or two or more Netplay clients can share the same controller (for e.g. handhelds or classic keyboard games where two players are supposed to grapple over the same input device). Additionally I've loosened up Netplay a bit so it'll connect so long as the protocol version is correct, even if the exact RA version or core version aren't the same.

The major remaining issues:
- This has placed a limit on the number of connections, since every client gets a client number. That limit is currently 32. A better design would be to apply client numbers only when you switch to play mode, so spectators don't waste slots.
- The UI for choosing which controllers you want to use is gaaaaaaaaarbage. The default is as it was before (you use the first available controller), but to hold two controllers or explicitly select a controller, you have to go through hellish new menu options with a toggle for every input device.
- ~~A lot of the messages no longer make any sense. You get the message "Joined as player whatever", where "whatever" is now just your connection number, which is basically meaningless. This should probably still be "Joined as player whatever" when you only have one controller, but it should at least be the controller number, and a new message is necessary for holding multiple controllers. Similarly, the same message is used for different versions of RetroArch as different versions of the core or different cores, but only one of those is still an error. Also, there's no useful error message if you request a particular controller and it's already taken.~~
- ~~The first reason for abstracting input like this was to add support for other kinds of input devices, such as mice and keyboards. That's now doable, but I haven't gotten around to doing it yet. That'll be a separate PR eventually.~~
- The mitm server will need to be upgraded to cope with the protocol changes. I've changed the header in such a way that it's possible to support both the old and new protocol.
- ~~Server spectating is broken again (as per usual)~~

### CODE REVIEW

**Comment by GregorR** [comment]
All of the critical changes are in. If we want to merge this now, we can. The major issue is that the protocol changes aren't backwards compatible, so the mitm server will need to be upgraded before another release is made. If that might be problematic, hold off on merging. Future changes to support new devices won't require protocol changes (that was the point :) )

**Comment by GregorR** [comment]
Adding new input devices turned out to be pretty simple, so I've added them. Unfortunately, none of them work well due to core issues, but in stateless mode they all work as expected. Not sure what to do about the various core issues that limit their usefulness.

**Comment by twinaphex** [comment]
@bparker06 What's the status on the MITM server? I hear that is still a roadblock preventing this from being merged.

**Comment by fr500** [comment]
So I started testing this but it kinda doesn't make sense to me, I need to undestand it to be able to improve the menu.

First thing, it seems the requests only happen upon connect? that means changing the values at runtime does nothing?

Second thing, I don't understand the share options.

Example:
Hosting SMW, hoster sets share to none
Client has request P1 and P2

I end up with hoster being able to user P1, client being able to use P1, P2

Third thing, client only request user 2 it seems his P1 manages netplay P2?

**Comment by fr500** [comment]
Comment, ok I take back the Second Thing, I guess those apply at startup too, if I set it to none in the hoster it allows the hoster to retain exclusive control of the requested controls

**Comment by fr500** [comment]
Not criticizing or asking for changes, just thought it was worth mentioning with I had envisioned:

At runtime under quick menu there would be a lobby management menu like this:

Lobby Management
- Client 1 User 1: netplay 1
- Client 1 User 2: none
- Client 2 User 1: netplay 2
- Client 3 User 1: netplay 3

Basically left column would list the available devices on each client and the right column would have the virtual port that's being controller by such device. By default it would follow the current method (1 client 1 port)

The amount of devices on each client would depend on them pressing "Start" at such moment we would print a "new user found on Client #x" on all clients and the hoster could change the inputs.

Just my idea though, if we can make it work cool, otherwise let's polish this up :)

**Comment by fr500** [comment]
Never the less, can you explain the share options to me?

**Comment by GregorR** [comment]
All of the checks for permission and sharing are done when devices are requested. By default that's at connect, but it also happens when you press 'i' (go to spectator mode) and then come back again.

Current limitations worth noting:

(1) You can't switch from one set of devices to another without first going to spectator mode.

(2) Which device you get is a bit of a dance between client and server. Both the implementation and the UI will need to change for this to change, but that was anticipated; I just need to know what hooks are needed.

(3) The only way to force a user OFF of a device is to disconnect them. I need to implement a softer force-to-spectator.

Sharing:

How it works now is that when you request a device, you request it with a share mode, and the server does the following:

(1) If a device of the requested type is completely free (i.e., no one is connected to it), you get that device, and its share mode is set to the share mode you requested.

(2) If no device is free and you requested unshared access, you don't get a device.

(3) Otherwise, the first shareable device of the correct type is shared to you.

Share modes:

The most important aspect of share modes is that there's unshared or shared. If a device is used unshared, then no one will be given that same device. If a device is set to any share mode, then more than one client can control it. The share modes themselves determine what it means for more than one client to control the same device.

The vast majority of users will never need to share an input device, and so ALL share modes are essentially advanced options. They're useful for either computer games in which two players are expected to grapple for the same keyboard, or for any single player game that the players are simply sharing.

The default share mode is the most sensible: It takes the bitwise OR of all buttons, and the most extreme of any analog positions. This is essentially "anyone who is trying to do something gets to".

All other share modes are even more advanced advanced options :)

The other digital share modes (i.e., share modes for binary inputs) are XOR and voting. XOR mode just uses bitwise XOR instead of OR, so that in principle you can cancel out your friend's actions. To me this makes reasonable sense for sharing a single-player game, since it makes it immediately obvious when you're (accidentally) fighting each other for input. Voting is exactly what it sounds like: If a majority of the users are pressing a button, it is considered pressed.

The other analog share mode is the average of each input.

**Comment by fr500** [comment]
> All of the checks for permission and sharing are done when devices are requested. By default that's at connect, but it also happens when you press 'i' (go to spectator mode) and then come back again.

> (1) You can't switch from one set of devices to another without first going to spectator mode.

Gotcha, maybe we can automate this on "option change"?
Does this need to be done on both sides?

> (2) Which device you get is a bit of a dance between client and server. Both the implementation and the UI will need to change for this to change, but that was anticipated; I just need to know what hooks are needed.

You mean because it depends on the share mode? 

This is my experience:
- If on a client I request one player it gets bound to that client P1
- If on a client I request more than one player the players gets bound to that client corresponding port

Just to be clear, SHARE MODE is a server thing right?
The requested device is for both ends.

What do you think about the menu proposal I had?

**Comment by GregorR** [comment]
Yeah, I can set up some kind of automation of the switch-to-spectator-and-back-again dance. Automating that would be a HELL of a lot easier than directly switching from one set of devices to another.

Your experience with devices is exactly right, and touches on something I forgot about: If you only request one device, it chooses that device in the way I described, but if you ask for more than one, it asks for EXACTLY the devices you asked for. I'd consider that a bug, basically, but a tough one to fix because I'm not sure what the correct user experience is.

I have two notes on the menu proposal:

(1) Presumably you're assuming there's logical default behavior going on when a player first connects, so the menu essentially updates itself until you explicitly change it.

(2) I don't know if we can actually KNOW how many "users" any "client" has, but your suggestion may indeed be enlightening. I could have it send the devices that it knows are connected because somebody's touched an input on them, so we'd essentially have a "press start to join" system. That could even be the default system for player 1, so if you connect and don't press any buttons, you're in spectator mode, and you join the game only when you press a button.

**Comment by fr500** [comment]
> I don't know if we can actually KNOW how many "users" any "client" has

Yeah that's why I suggested we have an extra option that read "Active Players" or whatever that the user can change beforehand.

My reasoning for this kind of menu is that the while current logic to pick one pad (P1) or several (P1, P2, P3) seems sane, it starts falling appart if the user wants P1, P3, P4.

So giving the hoster full control of what's assigned to each gamepad depending on how many users are sitting on any end makes sense to me. After all if it's a big game, or several players are connecting, it's most likely an orchestrated game. 

We could even use the client's max players value as a hint.

Maybe we're worrying too much though :p

**Comment by GregorR** [comment]
Well, I definitely agree that it should be a hoster decision regardless (this sort of comes down to the "host should have a hosting menu" issue), it's just a question of making sure that the host HAS the option, but is not REQUIRED to use it :)

**Comment by fr500** [comment]
Well most things work, the GUI is in fact rather incomplete but the "default behavior" still works as it always has so in my opinion it should be safe.

I would like for other people to test and review this though.

**Pull request merged**
