### PR TITLE
Menu label finetunes

### LINKED ISSUE #16099: Settings -> Directory -> File Browser: Replace "start directory" with "the Start Directory", and "file browser" with "File Browser"
Settings -> Directory -> File Browser: "Set start directory for the file browser"

I suggest that we change it to "Set the Start Directory for the File Browser" as references for:
* Settings -> Directory -> File Browser
* Main Menu -> Load Content -> Start Directory

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 Appimage

### Environment information

- OS: GNU/Linux

### LINKED ISSUE #16104: Settings -> User Interface -> Menu: Add "requires restart" to the description text
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

* Settings -> User Interface -> Menu. The entry description text "Menu driver to use" could be improved by adding "Menu driver to use, requires restart"
* Even better: Switch to the new driver right away

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

image

The new driver is not used when the value is changed:

image

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 Appimage

### Environment information

- OS: GNU/Linux
- Compiler: [In case you are running local builds]

### LINKED ISSUE #16119: Main Menu -> Restart/Quit RetroArch: Remove the "RetroArch" from the menu label
> [think we could remove the "RetroArch" from the menu label, as it's implied and explained in the sublabel.](https://github.com/libretro/RetroArch/issues/16000#issuecomment-1891021956)

image

### PR DESCRIPTION
**Pull request by zoltanvb**
## Description

Change quit sublabel depending on config save on exit status, it may be a bit more informative (or confusing?)
Update restart, file browser, menu driver sublabels.
Update config dir label and sublabel to be more exact and match other entries in the Directories list.
Restore quit help text display (noticed by accident).

## Related Issues

Closes #16099 
Closes #16104 
Closes #16119 

## Reviewers
@davidhedlund

### CODE REVIEW

**Comment by davidhedlund** [comment]
> ## Description
> 
> Change quit sublabel depending on config save on exit status, it may be a bit more informative (or confusing?) Update restart, file browser, menu driver sublabels. Update config dir label and sublabel to be more exact and match other entries in the Directories list. Restore quit help text display (noticed by accident).
> ## Related Issues
> 
> Closes #16099 Closes #16104 Closes #16119
> ## Reviewers
> 
> @davidhedlund

Thank you very much for your contributions, I deeply appreciate it!

Best

**Comment by davidhedlund** [comment]
> Change quit sublabel depending on config save on exit status, it may be a bit more informative (or confusing?)

We could add something like " (Save Configuration on Quit [enabled/disabled])":
* "Quit RetroArch application and save settings." to "Quit RetroArch application and save settings (Save Configuration on Quit enabled)."
* "Quit RetroArch application without saving settings." to "Quit RetroArch application without saving settings (Save Configuration on Quit disabled)."

**Comment by davidhedlund** [comment]
@zoltanvb

**Comment by davidhedlund** [comment]
> Change quit sublabel depending on config save on exit status, it may be a bit more informative (or confusing?)

@zoltanvb, as I suggested [here](https://github.com/libretro/RetroArch/issues/16000#issuecomment-1852267869), I think this is simpler:

If: Settings -> Configuration -> Save Configuration on Quit: Enabled [default]:
* Label: Quit. Sub label: "Save Configuration on Quit enabled."

If: Settings -> Configuration -> Save Configuration on Quit: Disabled:
* Label: "Quit. Sub label: Save Configuration on Quit disabled."

**Comment by hizzlekizzle** [comment]
oh nice, that was pretty painless to have it respond to the setting. I could see that being useful for a number of settings in the future.

**Comment by zoltanvb** [comment]
Updated quit sublabels. It is a convention that sublabel gives a slightly more verbose explanation of the option, so I kept that part as well.

**Comment by davidhedlund** [comment]
> Updated quit sublabels. It is a convention that sublabel gives a slightly more verbose explanation of the option, so I kept that part as well.

Looks great!

**Comment by davidhedlund** [comment]
> Updated quit sublabels. It is a convention that sublabel gives a slightly more verbose explanation of the option, so I kept that part as well.

There are two types of configurations `Save Configuration on Quit`, and `Save Remap Files on Quit`:

image

The text that you added, "`Configuration save on exit is enabled/disabled.`", only covers `Save Configuration on Quit`. It should be updated to
* `Save Configuration on Quit is [enabled]/[disabled]` or
* `Save Configuration on Quit is  [enabled]/[disabled], Save Remap Files on Quit is  [enabled]/[disabled]`

**Comment by davidhedlund** [comment]
Also, replace "Menu driver to use. Requires restart" to "Menu driver to use (Restart required)." to make it consistent with entries that says "Restart required" in `Settings -> User Interface -> Menu Item Visibility`

**Pull request merged**
