### PR TITLE
[discord] set partyId properly

### PR DESCRIPTION
**Pull request by fr500**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by orbea** [comment]
@fr500 New warnings with gcc-8 and travis.
```
discord/discord.c: In function ‘discord_update’:
discord/discord.c:401:60: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size between 116 and 126 [-Wformat-truncation=]
             snprintf(join_secret, sizeof(join_secret), "%d|%s", room->id, party_name);
                                                            ^~             ~~~~~~~~~~
In file included from /usr/include/stdio.h:937,
                 from ./libretro-common/include/file/file_path.h:26,
                 from discord/discord.c:16:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 3 and 140 bytes into a destination of size 128
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
discord/discord.c: In function ‘handle_discord_join_cb’:
discord/discord.c:197:53: warning: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 32 [-Wformat-truncation=]
       snprintf(tmp_hostname, sizeof(tmp_hostname), "%s|%d",
                                                     ^~
In file included from /usr/include/stdio.h:937,
                 from ./libretro-common/include/file/file_path.h:26,
                 from discord/discord.c:16:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 3 and 4108 bytes into a destination of size 32
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fr500** [comment]
I'll verify later

**Comment by orbea** [comment]
I can reproduce it locally too, its just hiding in this giant warning mess...
```
CXX deps/discord-rpc/src/discord_rpc.cpp
In file included from deps/discord-rpc/src/rpc_connection.h:4,
                 from deps/discord-rpc/src/discord_rpc.cpp:6:
deps/discord-rpc/src/serialization.h:6: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)
 
deps/discord-rpc/src/serialization.h:8: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4061) // enum is not explicitly handled by a case label
 
deps/discord-rpc/src/serialization.h:9: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4365) // signed/unsigned mismatch
 
deps/discord-rpc/src/serialization.h:10: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4464) // relative include path contains
 
deps/discord-rpc/src/serialization.h:11: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4668) // is not defined as a preprocessor macro
 
deps/discord-rpc/src/serialization.h:12: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 6313) // Incorrect operator
 
In file included from deps/discord-rpc/src/rpc_connection.h:4,
                 from deps/discord-rpc/src/discord_rpc.cpp:6:
deps/discord-rpc/src/serialization.h:20: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(pop)
 
CXX deps/discord-rpc/src/rpc_connection.cpp
In file included from deps/discord-rpc/src/rpc_connection.h:4,
                 from deps/discord-rpc/src/rpc_connection.cpp:1:
deps/discord-rpc/src/serialization.h:6: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)
 
deps/discord-rpc/src/serialization.h:8: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4061) // enum is not explicitly handled by a case label
 
deps/discord-rpc/src/serialization.h:9: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4365) // signed/unsigned mismatch
 
deps/discord-rpc/src/serialization.h:10: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4464) // relative include path contains
 
deps/discord-rpc/src/serialization.h:11: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4668) // is not defined as a preprocessor macro
 
deps/discord-rpc/src/serialization.h:12: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 6313) // Incorrect operator
 
In file included from deps/discord-rpc/src/rpc_connection.h:4,
                 from deps/discord-rpc/src/rpc_connection.cpp:1:
deps/discord-rpc/src/serialization.h:20: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(pop)
 
In file included from deps/discord-rpc/src/serialization.h:15,
                 from deps/discord-rpc/src/rpc_connection.h:4,
                 from deps/discord-rpc/src/rpc_connection.cpp:1:
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetObjectRaw(rapidjson::GenericValue<Encoding, Allocator>::Member*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Member = rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >; rapidjson::SizeType = unsigned int]’:
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2363:9:   required from ‘bool rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::EndObject(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::SizeType = unsigned int]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1736:18:   required from ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1832:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:487:46:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2159:22:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; SourceEncoding = rapidjson::UTF8<>; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2175:62:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2200:58:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2208:47:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
deps/discord-rpc/src/rpc_connection.cpp:115:50:   required from here
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:1952:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {aka ‘struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >’} with no trivial copy-assignment; use copy-assignment instead [-Wclass-memaccess]
             std::memcpy(m, members, count * sizeof(Member));
             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from deps/discord-rpc/src/serialization.h:15,
                 from deps/discord-rpc/src/rpc_connection.h:4,
                 from deps/discord-rpc/src/rpc_connection.cpp:1:
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:71:8: note: ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {aka ‘struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >’} declared here
 struct GenericMember {
        ^~~~~~~~~~~~~
In file included from deps/discord-rpc/src/serialization.h:15,
                 from deps/discord-rpc/src/rpc_connection.h:4,
                 from deps/discord-rpc/src/rpc_connection.cpp:1:
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetArrayRaw(rapidjson::GenericValue<Encoding, Allocator>*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]’:
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2371:9:   required from ‘bool rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::EndArray(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::SizeType = unsigned int]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1766:18:   required from ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1832:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:487:46:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2159:22:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; SourceEncoding = rapidjson::UTF8<>; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2175:62:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2200:58:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2208:47:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
deps/discord-rpc/src/rpc_connection.cpp:115:50:   required from here
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:1939:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
             std::memcpy(e, values, count * sizeof(GenericValue));
             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
deps/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:540:7: note: ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ declared here
 class GenericValue {
       ^~~~~~~~~~~~
CXX deps/discord-rpc/src/serialization.cpp
In file included from deps/discord-rpc/src/serialization.cpp:1:
deps/discord-rpc/src/serialization.h:6: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)
 
deps/discord-rpc/src/serialization.h:8: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4061) // enum is not explicitly handled by a case label
 
deps/discord-rpc/src/serialization.h:9: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4365) // signed/unsigned mismatch
 
deps/discord-rpc/src/serialization.h:10: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4464) // relative include path contains
 
deps/discord-rpc/src/serialization.h:11: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4668) // is not defined as a preprocessor macro
 
deps/discord-rpc/src/serialization.h:12: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 6313) // Incorrect operator
 
In file included from deps/discord-rpc/src/serialization.cpp:1:
deps/discord-rpc/src/serialization.h:20: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(pop)
 
CC discord/discord.c
discord/discord.c: In function ‘discord_update’:
discord/discord.c:401:60: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size between 116 and 126 [-Wformat-truncation=]
             snprintf(join_secret, sizeof(join_secret), "%d|%s", room->id, party_name);
                                                            ^~             ~~~~~~~~~~
discord/discord.c:401:13: note: ‘snprintf’ output between 3 and 140 bytes into a destination of size 128
             snprintf(join_secret, sizeof(join_secret), "%d|%s", room->id, party_name);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
discord/discord.c: In function ‘handle_discord_join_cb’:
discord/discord.c:197:53: warning: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 32 [-Wformat-truncation=]
       snprintf(tmp_hostname, sizeof(tmp_hostname), "%s|%d",
                                                     ^~
discord/discord.c:197:7: note: ‘snprintf’ output between 3 and 4108 bytes into a destination of size 32
       snprintf(tmp_hostname, sizeof(tmp_hostname), "%s|%d",
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          room->host_method == NETPLAY_HOST_METHOD_MITM ? room->mitm_address : room->address,
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          room->host_method == NETPLAY_HOST_METHOD_MITM ? room->mitm_port : room->port);
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fr500** [comment]
The ones from the deps I can do nothing about. I'll fix the discord.c warnings though.

**Pull request merged**
