### PR TITLE
Changed default level 6 turbo back to 1

### PR DESCRIPTION
**Pull request by xmat123x**

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi, can you provide an underlying reason for this?

**Comment by xmat123x** [comment]
The Wii port has turbo set to 6 every time you load a core or change a game. This fixes it but I guess the issue is much deeper where RA refuses to read the config file for certain settings and loads the default ones instead.

**Comment by twinaphex** [comment]
Yes I see. Oddly enough these were never saved to the config file. I can rectify that now. If I save those to the config file, would that take care of the problem and could we then close this PR?

**Comment by xmat123x** [comment]
Yeah, that's great.

**Comment by twinaphex** [comment]
OK, these should be getting saved now.

https://github.com/libretro/RetroArch/commit/a840a081fb1ef0a5f9160f950196596a3c75a1ff

**Comment by twinaphex** [comment]
Since you mentioned the WIi BTW, I fixed the problems with boot.dol today. So hopefully the nightlies should start working again for you guys. I tested it on my Wii and it worked there.

**Comment by xmat123x** [comment]
Cool stuff, will definitely check it out and report back to IRC after testing.

**Pull request closed without merging**
