### PR TITLE
Add scaling to pointer input

### PR DESCRIPTION
**Pull request by JonnyMe**
## Description

So far, if display is scaled, overlays gets correctly drawn but touch
input is not correctly scaled, resulting in an unusable overlay.

This happens for touches in menu too.

This commit aims to introduce this scaling factor adding it to the
config file, eg:

`input_touch_scale = "2"`

## Related Issues

https://github.com/libretro/RetroArch/issues/12205

### CODE REVIEW

**Comment by jdgleaver** [comment]
Hi! Thank you for this. We need to resolve a couple of things before merging, however:

- The new option needs a menu entry. This is fiddly, but not too difficult - you can find instructions here: https://docs.libretro.com/development/retroarch/new-menu-options/ (you can ignore `msg_hash_us.c` in this case)
- Could you please not do floating point arithmetic in `menu_input_get_touchscreen_hw_state()`? We have to support platforms where the speed difference between float/integer arithmetic is non-trivial. It's probably best to refactor the setting to make it a uint, and then only convert to float inside `input_overlay_poll()` (where we necessarily have to do a bunch of floating point operations, so the additional overhead will be insignificant)

**Comment by JonnyMe** [comment]
Hi @jdgleaver, thank you for your feedback!

Sure, I'll work on the changes you suggested.

**Comment by jdgleaver** [comment]
Thanks, that's much appreciated! :)

**Comment by JonnyMe** [comment]
@jdgleaver regarding the menu entry I set a range between 1 and 4 for the scale, let me know if this would be ok or not :-)

**Comment by jdgleaver** [comment]
@JonnyMe Excellent, thank you for updating this so quickly!

There are just a couple of items left:

1) I've attached a tiny diff that makes a few small changes: [touch_scale.zip](https://github.com/libretro/RetroArch/files/6250472/touch_scale.zip)

    - It clarifies the menu entry sublabel a little
    - It caches `settings->uints.input_touch_scale` to a local variable in `menu_input_get_touchscreen_hw_state()` (saves having to index that huge struct twice)
    - It adds an 'x' in front of the scale factor value (e.g. `x2`)

   Could you please apply this to your PR and check that you're okay with these modifications?

2) Unfortunately, the translation files cannot be edited via regular PRs (apologies - the docs are a little out of date here, and I should have warned you...). All translations have to go via Crowdin: https://docs.libretro.com/development/retroarch/new-translations-crowdin/. That being the case, could you please undo your changes to `intl/msg_hash_it.h`?

Once those things are done, and you've rebased, we should be ready to merge :)

> regarding the menu entry I set a range between 1 and 4 for the scale, let me know if this would be ok or not :-)

Since you raised the initial issue, I think you are best suited to understand the problem here! If you think 1-4 is okay, then I'm quite happy with that :)

**Comment by JonnyMe** [comment]
Thank you @jdgleaver, I applied your patch without changing it, seemed good to me! Thank you for the resources too, I'll look into them to fix the typo.

Regarding the range I think it could be good for now, I don't really know how many OSes/device have this kind of issue, I guess adding scales would be easier however :-)

**Comment by jdgleaver** [comment]
Great, this is all fine now.

@twinaphex I think this is ready for merging :)

> Regarding the range I think it could be good for now, I don't really know how many OSes/device have this kind of issue, I guess adding scales will be easier however :-)

I agree. Now that the code is in place it should be fairly trivial to decrease the granularity if users indicate that more levels are required.

**Pull request merged**
