### PR TITLE
Add option to load overlay based on system name

### PR DESCRIPTION
**Pull request by warmenhoven**

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I'll make some changes to https://github.com/hunterk/playlist-overlays and then PR them back to common-overlays and will link back to this issue. Once they're merged there, we can hammer out the location here and get it finalized.

**Comment by hizzlekizzle** [comment]
Alright, common-overlays PR is up: https://github.com/libretro/common-overlays/pull/135

I named the directory with the overlay cfgs "Named_Overlays," since that seemed to be in-line with our various Named_Boxart/Logos/etc. If that's inappropriate for whatever reason, or if you have a better idea, just let me know and I'll change it over there.

**Comment by LibretroAdmin** [comment]
I merged the common-overlays PR. What is the next step?

**Comment by warmenhoven** [comment]
This PR needs a small adjustment to find the overlay in the correct location. Once the assets pipeline is done running I'll make that change and confirm it's working and then this should be ready.

**Comment by warmenhoven** [comment]
Ok, this should be good to go now. Thanks!

**Pull request merged**
