### PR TITLE
Path substitution

### PR DESCRIPTION
**Pull request by francescotintori**
### Description

This commit adds a path substitution feature to RetroArch.
The idea behind this is to be able to reuse playlists across different installations of retroarch (on different OSes too), without having to rescan everything all the time.

### Simple use case. 

I have a some SNES roms on a Windows machine, in D:\Retroarch\roms\snes.  
The same roms are on an android machine (or any *nix machine), for example in /home/francesco/roms/snes.
I would like to use my already existing playlist in my Windows install on the *nix installation.

To do this I need some kind of path substition:
- first I need to replace "D:\Retroarch" with "/home/francesco"
- then I also need to replace the remaining "\" characters with "/"

So, for example, "D:\Retroarch\roms\snes\zelda3.zip" would be translated to "/home/francesco/roms/snes/zelda3.zip", before actually opening the file.

In retroArch.cfg i would add this parameter:
path_substition = "D:\Retroarch->/home/francesco;\->/"

The syntax separates every source->dest substition with a ";". Source and dest are separated by a "->" (ugly, but I wanted something that would not generate any conflict with any windows/*nix path syntax).

Notes
This is still (very) work in progress. 
The main problem here is finding all possible places where a path substition may be necessary: for now I added replacement in retroarch virtual FS calls, and in task_content.c (used to load files from playlists).

### CODE REVIEW

**Comment by i30817** [comment]
Cool, maybe this will encourage some cores to make their own path/ path separator replacement on their configs (scummvm, dosbox, and cue files in general being the worst offenders i know of).

BTW, if you want, or can, restrict yourself to relative dirs it would seem that you can this without the first part (just having the path separator replacement).

Since linux can have paths with '\' on them you might have problems here, but that should be unusual because rom dumpers avoid that.

**Comment by twinaphex** [comment]
@jdgleaver will be reviewing this early next week. Some implementation changes might be required.

**Comment by francescotintori** [comment]
Hi,
relative paths were the first experiment I did, until I remembered about my Nvidia Shield.
I keep all my roms on a linux server, shared via samba: the shields allows for samba mounting, but it forces all mounts in /storage/<servername>/<sharename>. 
So basically all my roms are mounted in "/storage/jarvis/roms/".
The ideas was then to replace "D:\Retroarch" with "/storage/jarvis", followed by "\" with "/".

I had a similar approach is done on my Windows pc, with symlinks: the linux samba share is mounted in D:\Retroarch\Roms, so it's trasparent to retroarch. 
On Windows of course I dont need path substitution, the windows playlists will be the "base".

About path substition in cores: I guess it would be useful, but it's still necessary in retroarch too.
For example for building correct paths to saverams, savestates, ips patches, etc.
Also, retroarch does not pass the zip/7z file directly to the core, but uncompresses it and then pass the uncopressed rom file, so it's another thing where path substituion is necessary.

Anyway, it's still very work in progress, my initial commit was just to show the basic idea. 
I'm open to any change.

**Comment by i30817** [comment]
Here is some prior art from a new python std library: https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f


As you can see from the article it doesn't solve the 'mount point' problem which your idea does, but it does have some ideas of how to solve the 'separator conversion'. Namely 'windows' paths are always either read with commented backslashes as separators or with the unix form of forward slashes (that iirc are also a reserved character in windows). Maybe you should read the PEP that originated the library to see the rationales.

**Comment by francescotintori** [comment]
Just remembered that playlist also contains core file name and description.
Even using the same core results in a completely different file name, depending on the os (snes9x_libretro_android.so on unix/android, snes9x_libretro.dll on windows).
This may break my playlist sharing idea.

**Comment by i30817** [comment]
Just nuke the setting to default if the 'origin' of the file is different from the current OS. It's a case of the particular 'illegal path for config files' thing i mentioned in the post before: just use the default, which in this case is nothing.

**Comment by i30817** [comment]
I have another idea that i'm not sure of: instead of overwriting the RA config/playlist files when you detect a different OS origin, do the conversion to another file with a suffix for example and make RA fallback to those if they exist in the future.

This avoids the 'information loss' going on from nuked settings. But it's a bit gnarly.

**Comment by i30817** [comment]
OMG. I really should think twice before writing. I hope you didn't merge that because of my dumb idea above.

**Comment by francescotintori** [comment]
I think the current idea of path substitution may results in tons of problems.

I was thinking another approach: let's suppose my playlist only contains relative paths (for example '\roms\snes\zelda3.zip'), and there was an automatic detection logic for posix or windows path syntax (like in the linked python library).
If I was able to understand that the playlist path is in windows format, and I'm running on a unix os, I could easily translate paths switching backslashes with slashes. The same if I had a unix playlist on windows. 
Of course, the resulting filepath is still relative ('\roms\snes\zelda3.zip' or '/roms/snes/zelda3.zip').
Now I add a new optional 'content_basepath' parameter to retroarch.
If Retroarch loads a relative path from the playlist AND the 'content_basepath' parameter is set, Retroarch will just append the relative path to the 'content_basepath' parameter to build the final name.

Example:
- Linux OS
- 'content_basepath' = '/home/francesco'
- playlist path (copied from a windows install) = '\roms\snes\zelda3.zip'
- under linux, retroarch recognizes a windows format and translates it to '/roms/snes/zelda3.zip'
- retroarch also recognizes a relative path (or maybe checks if the file exists, and it probably doesn't)
- then it appends the translated path to 'content_basepath' = '/home/francesco/roms/snes/zelda3.zip'

This approach is much simpler I think, no complicated path substitution calls around the code, and should work even from linux->windows.

I just need to write code to detect windows/unix path syntax (if it doesn't already exist), and to recognize absolute/relative paths.

I still need to understand how to handle the different core filenames.

I'll think about it.

**Comment by i30817** [comment]
> I was thinking another approach: let's suppose my playlist only contains relative paths (for example '\roms\snes\zelda3.zip'),

This is not actually a relative path in linux but a single filename. This is part of why 'detection logic' can't be embedded into the filename (imo).

**Comment by i30817** [comment]
Edit: actually there is a way to embed a 'origin' to a path but it's quite unintuitive and would ruin user ability to edit config files.

Use \0 aka null aka 0x00 as a separator between the OS id and the path. It's illegal in both windows and linux (and everywhere with sense) iirc.

The problem is it's that it's literally invisible when you edit files so it would appear as:

filename="bla/blah/FFVI.romDONT_EDIT_THIS_LUSER_WINDOWS", which is quite awful.

**Comment by i30817** [comment]
Ok this is my last wall of text (but short here) post, tell me if you agree or not:

1. handling normal paths to be portable in RA is a pain. 
2. but you can use the pathlib approach+one or more basenames translations to be portable as the cost of making RA cfg files incompatible. Users would need to be educated to use forward slashes on their copy pasted filenames when editing .cfg manually; and paths that require some kind of OS specific filename (like dll/so) would need to be shortened to remove the extension and adding it at runtime.
3. this doesn't solve the user files problem, where non-redump (for example) cue files have OS path separators and their parsers expect the current OS path separator. So if you do this, some cores would need followup PRs that make their parsers use forward slashes always. Problem: this requires users to change their data manually, a recipe for disaster, and would make them file bug reports about 'this is a legal windows name'. Not sure what to do here, make it optional to turn on the 'relative path assumption' on the cores with RA setting?

**Comment by francescotintori** [comment]
Totally forgot about cue files, which I also use for ps1 games.

So i tried changing the content of one game (chrono crosso) from
.\multicd\Chrono Cross (USA) (Disc 1).chd
.\multicd\Chrono Cross (USA) (Disc 2).chd
to
./multicd/Chrono Cross (USA) (Disc 1).chd
./multicd/Chrono Cross (USA) (Disc 2).chd
For some reason it still worked, I guess it depends on the core to be smart enough (PCSX Rearmed on windows).

**Comment by i30817** [comment]
That needs to be tested exhaustively.

**Comment by jdgleaver** [comment]
@francescotintori  Apologies for taking so long to review this (I've been so busy recently...)

I very much appreciate what you're attempting to do here, but there are so many issues that I cannot see a workable solution using the current approach. I see that you've had alternative ideas since making the PR, but let me first comment on your original code, just so we can get a baseline:

- Your path substitution concept basically amounts to a virtual file system, where the host defines a mount point and then everything beneath that is handled in a platform/system-independent fashion. This kind of thing is only practical when you have a *single* mount point. RetroArch does not. Every single thing can be configured to a separate directory on a separate drive. Playlists themselves can contain content spanning different source folders and physical filesystems to an almost unlimited degree. This means you have to support unlimited 'virtual' mount points, which leads me to this:

- You added the ability to set multiple mount points via the delimited `path_substitution` string. But this doesn't work. You can't store unlimited paths in a 4096 character array. Moreover, how would the user configure this? Even given unlimited storage, it is impractical to create an interface whereby the average user could create virtual mount points for an arbitrary selection of scattered content.

- And here's the worst part: the path substitution code was inserted at the lowest level in the VFS, making it affect all file access. Adding invasive features to this kind of fundamental `libretro-common` code is not something we can ever do lightly, and the VFS cannot ever have any internal dependence upon the global settings struct. But apart from that, it is not unusual to call `retro_vfs_stat_impl()` 10k times in a singe frame - all that heavy string manipulation in `get_substitute_path()` is thus simply unacceptable from a performance standpoint. We just can't slow down file access like this.

So the original implementation is sadly a bust.

Your updated idea of limiting this purely to playlists themselves and having the option of recording relative paths is better, but again this soon becomes impractical. If you're going to do this, then it needs to work in all cases - which means supporting a separate `content_basepath` for each item of content (since a playlist may contain content from unlimited sources). How would this work? In addition, this still requires a large amount of additional runtime string and path manipulation that would affect performance for all users, all the time, while only benefiting a very tiny handful that might want to share playlists between different platforms. I find this difficult to swallow.

So let's try and think of a solution that deals with your edge case of shared playlists without making invasive code changes, and without causing undue performance overheads...

Instead of having runtime detection, would you be amenable to making this a one-shot playlist management task? So under `Settings > Playlists > Playlist Management > [playlist_name]`, you could have something like a `Refresh Content` option (this could even go one level higher, and perform a batch process across all playlists). When selected, it would open a file browser where you select a content directory. Retroarch would then fetch a recursive file list, and:

- For each playlist entry, search the directory listing for matching content and record the updated path. This could probably just be based on matching the filename after the last (platform dependent) slash, or you could also search backwards for matching sub directories.

- For each playlist entry, check the current core association and update the core path based upon the local installation (you can probably match against the leading `core_name_libretro` segment without extension).

- For the playlist as a whole, also update the default core association.

This is simple, entirely self-contained and absolutely harmless for any user that doesn't want to make use of the feature. It can also be as performance-intensive as you like - a user-triggered task is subject to none of the constraints of mandatory runtime code. It doesn't handle the case of multiple source paths for a single playlist, but since this is a feature that requires manual intervention we can expect the user to have at least some idea of what they are doing, and to apply it to playlists where the source directories are well defined.

This seems like a win for everyone. What do you think?

**Comment by francescotintori** [comment]
Hello @jdgleaver, thanks for all your comments.
First, I agree the initial idea is really bad: doing path substition at the file system level means doing it for basically everything (roms, but also config files, saverames, savestates, etc), most of which is already handled by retroarch (with its directory parameters in the base retroarch.cfg, and the core/content overrides cfgs).
I already abandoned this approach (I will also close this pull request).

The second idea (a base path to be merged to a relative path read from playlist) seemed a much better approach:
- First, it's optional. If you dont' configure a base path, retroarch works exactly the same as before
- It's also fast anyway: during my test, once you select a game in a playlist the function is called twice (I still need to understand why two times). Anyway, we are just copying and comparing strings in memory, it's a very fast operation.

I proposed a single 'base path' parameter because I keep all my roms in a single place, but I guess someone may split in different sources (for example old systems games in a small drive, isos and the whole mame set in a bigger one).
What if we defined both? A base path in the retroarch config file, and another in the playlist (basically an override): if the playlist base path is defined, retroarch will use it, else will use the retroarch one.
If both parameters are not defined, we just use the playlist path with no modifications.

I would REALLY like to share playlists without having to modify them, because right now I'm setting up multiple retroarch instances (Windows PC, Shield, two smartphones) where most data is synchronized (saverams, achievements, runtime logs, etc.). Imagine playing FF7 on your living room tv, and then resuming another time on your phone :)
In my current setup i don't synch playlists but I manually copy them when modified on my Windows PC. 
Then I edit them on the Shield, replacing the windows absolute path with the android absolute path, and I would really like to avoid this additional step.

I basically want a Plex for roms, maybe one day someone will do it..

I'll prepare another pull request for this second approach.

**Comment by jdgleaver** [comment]
@francescotintori Okay, I understand your goals here  :)

I've thought about your relative playlist path idea, and I think it could work - but can I make some more suggestions that would help to minimise the impact for users who don't want this feature, and maybe simplify the configuration?

- Have a global setting: `Save Relative Paths in Playlists` (can name this as you please). When disabled, everything works exactly as it does now.

- Add a new member to the `playlist_entry` struct: `relative_path`

- We already have a kind of global `base path` set in `settings->paths.directory_menu_content` - I think it would be easiest to reuse the path set here for your purposes. A per-playlist override could also be set, but that kinda defeats the point of what you're aiming for - i.e. anyone using per-playlist base paths would still have to edit every playlist when transferring files, meaning you loose the behaviour you want...

So we have a `playlist_save_relative_paths` flag, a `relative_path` field and a `settings->paths.directory_menu_content` base directory. The program flow would then go as follows:

*Push path to playlist:*

- If `playlist_save_relative_paths == false`, set `entry->path` as we do now - no manipulation

- If `playlist_save_relative_paths == true`:

    - Determine content path relative to `settings->paths.directory_menu_content`

    - Convert all platform-dependent slashes to Unix style

    - Record the result in `entry->relative_path` and leave `entry->path` blank

    - If the relative path involves a transition to a different physical drive, *then this cannot work* - because trying to convert platform-specific drive letters is a fool's errand. If this situation occurs, then throw an error and just record the 'raw' path in `entry->path` - users should understand that relative playlists are only functional when using 'sane' content paths (you can make this clear in the `Save Relative Paths in Playlists` sublabel)

*Fetch path from playlist:*

- We can make this seamless by continuing to use `playlist_get_index()` (and associated functions) directly.

- When fetching the entry, if `entry->path != NULL` then we do nothing - actual content path is already populated, so no action is required

- If `entry->path == NULL`, and `entry->relative_path != NULL` then:

    - Copy `entry->relative_path`

    - Convert slashes to local platform format

    - Use `fill_pathname_resolve_relative()` to combine `settings->paths.directory_menu_content` and 'converted' relative content path

    - Assign the result to `entry->path`

When saving a playlist, if `entry->relative_path != NULL` then we record this value and *omit* `entry->path` - otherwise, we record `entry->path` (and omit `entry->relative_path` as normal)

How does this sound? I think it gives you what you want, without harming performance for users who don't want this (i.e. the only extra work in this case will be an `if (!entry->path)` when fetching, and an `if (playlist_save_relative_paths)` when setting, and of course a bunch of `if (entry->relative_path)` when saving  - all of which should be fine)

**Comment by francescotintori** [comment]
Hello @jdgleaver,
my current implementation postpones path resolution until I load the game, but I think your solution it's actually easier: if I resolve paths at playlist load runtime I don't have to hunt down all locations in code where the paths are used.
Nice idea, I'll work on it.

**Comment by francescotintori** [comment]
I'll close this pull request, I made a new one (https://github.com/libretro/RetroArch/pull/10642).

**Pull request closed without merging**
