### PR TITLE
imgui based debugger

### PR DESCRIPTION
**Pull request by fr500**
THIS IS NOT A MENU DRIVER

this is still very much WIP, opening a PR so it can be scrutinized.

@leiradel is gonna hook up the cheevos hunter and make an API so several plugins can be integrated into this view, could have a sprite viewer, or a waveform viewer or anything really. It's meant to be a complimentary window and it will not mess with the normal runloop.

### CODE REVIEW

**Comment by fr500** [comment]
image

This is a single RetroArch instance with the new debug window showing up

**Comment by twinaphex** [comment]
@leiradel Can you take the lead on this issue and determine when we might be getting to something that is considered merge-eable? I'd be fine with something that requires a specific configure switch in order to bake in this functionality.

**Comment by leiradel** [comment]
Although the code is only compiled with HAVE_DEBUGGER=1, the code is still changing a bit. Also, we don't have much to show yet, and I'm a bit uncomfortable with the way the debugger window and RetroArch share data, which just pretend there aren't two separate threads and data races don't exist.

I'm thinking in using semaphores (only for debugger builds) to lock the two threads, so i.e. RetroArch runs one frame, then fires the debugger to run one frame, repeat. If we can have both windows running in that fashion on the same thread, it would be even better IMHO.

**Comment by twinaphex** [comment]
Why are you closing this?

**Comment by fr500** [comment]
because leiradel force pushed the commits twice so I'll have to rebase to clean this up again

**Comment by twinaphex** [comment]
OK, I understand then. No problem.

**Comment by leiradel** [comment]
I wish I knew how git add/commit/push can lead to a forced push. It sounds like I used some `--force` flag, which I didn't.

**Pull request closed without merging**
