### PR TITLE
Only call glUniformMatrix4fv if needed

### PR DESCRIPTION
**Pull request by loganmc10**
This has been tested with mupen64plus-libretro and glupen64, I also tested toggling shaders with both cores and everything seems to be working well.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hmm, it causes a very bad regression in XMB though, the icons are way too big.

Can you confirm this on your end and if so, try finding a regression fix for this?

**Comment by twinaphex** [comment]
Here are before/after screenshots illustrating the regression -

http://imgur.com/a/5MJRM

**Comment by loganmc10** [comment]
Sorry I believe basically a merger of the 2 pull request will solve this issue, I'll submit another pull request

**Comment by loganmc10** [comment]
Fix is in #3674

**Comment by twinaphex** [comment]
Seems to be fixed now, thanks.

**Pull request merged**
