### PR TITLE
Reworked xmb driver to allow tab hiding

### PR DESCRIPTION
**Pull request by gitghostcoder**
I wanted to hide the history tab, and I saw several requests around the web for a similar feature so I thought I would dive into the code.

You can hide most tabs, but the main tab is required.

### CODE REVIEW

**Comment by RobLoach** [comment]
Did I test this right? Seems like it didn't take affect for me...

1. Deleted `~/.config/retroarch/playlists` and `~/.config/retroarch/content_*`
2. Ran newly compiled RetroArch with your changes
3. Went into Settings and disabled Show Images Menu and Show History Menu
4. Main menu, Save Current Config
5. Quit
6. Re-ran RetroArch
7. Saw the Images and History menu at the top

**Comment by gitghostcoder** [comment]
@RobLoach

I can't be sure, but I have a strong feeling you are seeing the result of a compromise. I really only need to ask: do you build without ffmpeg support? If so, you only have two history tabs which explains what you've seen. You can (should be able to) hide individual history tabs, but the compromise I chose forces the history tabs to be reset as shown in the event that histories are enabled and /all/ history tabs are set to be hidden.

Basically, the code considers hiding /all/ the history tabs with histories still enabled a user error.

I tried to get more people interested in which direction to go, but I couldn't get any feedback beyond one other person so I picked a compromised between what he wanted and what I wanted. If you feel the compromise I chose is the wrong behaviour, I'd like you to start an issue up so maybe I can get a little more feedback this time.

As I said, I can't be sure your problem is just hiding both of the history tabs available to you while you have histories enabled. If you still have issues after relevant change, can you pass along any quirks you might have in your configure/make/retroarch.cfg bits so I can look into things a bit more?

Just in case, I followed these steps to try and confirm on my end:

git clone https://github.com/libretro/RetroArch.git
*removed ~/.config/retroarch*
./configure --prefix='/usr' --enable-ffmpeg
make
*changed retroarch menu driver to xmb*
*hid images and history leaving video and music shown*
(The images and history menu are gone.)
*removed ~/.config/retroarch*
make clean
./configure --prefix='/usr' --disable-ffmpeg
make
*changed retroarch menu driver to xmb*
*hid images and history leaving no history tabs shown*
(The images and history menu remain.)
*disabled history and again hid images and history*
(The images and history menu are gone.)

**Comment by Kivutar** [comment]
I noticed something strange: if I try to enable only the main menu and the add tab, all tabs will be displayed. Am I doing it wrong?

**Comment by Kivutar** [comment]
We get bugs like this now when scanning a directory

capture du 2016-08-18 14-00-02

**Comment by gitghostcoder** [comment]
@Kivutar 

For the first issue, read my other post.

For the second issue, I'll have to try and recreate the issue so I can find the bug.

**Comment by gitghostcoder** [comment]
@RobLoach 
@Kivutar 

I've now seen enough people with "Have I done something wrong?" comments that I've changed the behavior to better match what users are expecting. The updated code (see pull requests) should resolve both your issues with the history tabs still being shown.

@Kivutar 

I was able to recreate your problem with the display. When I was moving code around to simplify the implementation for future maintainers, I lost the line responsible for resetting tab positions. The updated code restores the relevant line so you should be able to scan files/directories again.

I can't test the scan feature (I have no matching files.) so please let me know if you still have problems.

**Comment by Kivutar** [comment]
@gitghostcoder sorry but the implementation was too complex and buggy. I asked you to test the scan feature in my first response to your first PR and I see it have not been tested.

Also, I really don't think that we need things like HAVE_KIOSK or the other define you added. Reordering is also too much.

I reverted your commit because of this bug, and re-implemented the feature in a more simple way. I'm currently testing it.

**Comment by gitghostcoder** [comment]
You gave me less than two hours to fix a bug I introduced because of you?

Fuck you. I'm done. I'm not going to put up with this shit again.

**Comment by RobLoach** [comment]
@gitghostcoder He's not criticising you, or your work. He wants this feature as much as you, and you did a great job getting this pushed forwards. Thank you so much! :+1:

Just need to clean up a few things before it's finally merged. We're all working towards the same thing here :smile: .

**Comment by Kivutar** [comment]
@gitghostcoder If I took it that bad each time my commits where reverted, I would have left the project one year ago.

I know what it feels to see your code rejected and it often makes me mad too.

However, it's more important to have something easy to understand and easy to maintain. Take a look at my PR here, this is how I would have done it. https://github.com/libretro/RetroArch/pull/3404

There is no need of insulting me. I can assure you that there is nothing personal against you at all. Let discuss it on IRC.

**Comment by gitghostcoder** [comment]
@RobLoach

I don't think that's true at all.

There is a huge difference between "We are pulling this until you get the kinks worked out." and "We are pulling this and I'm going to do it right.".

The one says "We are all on the same team." while the other says "You are not on the team.".

We all know bugs happen, but I've just been told I don't the option to fix the bugs. You see where  Kivutar is just going to write the code himself instead? I'm perfectly happy to work the code, but I don't have time to spend on another project where my bugs are forever.

I was more than happy to fix any bugs. I'm not being given that option. You are free to think as you will, but I /can't/ write bug free code. I doubt I will ever submit a pull request for a new feature that is completely free of bugs, and I'm not going to waste my time working on a project that rather throw out my work than allow me time to fix it.

@Kivutar

I took a look at your implementation, and we both know that your code implements exactly one features request. Your code does not allow reordering tabs. Your code does not have bits aimed towards supporting the "kids mode" mechanism. Your code hides tabs and nothing more. I expected exactly as much when before I ever looked.

I'm not even slightly upset that my commit was reverted. I'm not upset that my code was rejected in the current state. I'm upset that I'm not being given a /real/ opportunity to fix the code so it wouldn't be rejected. I'm upset because I'm not now allowed to polish the code until reverting it would be a mistake.

If I upload buggy code, I /want/ to fix it. You would have never needed to ask me to fix something in my code I had the capacity to fix. You only had to file a bug report. In exchange, I do absolutely demand a /real/ opportunity to fix it. I'm not being given that opportunity which makes this a waste of my time.

You work you project however you like, but I specifically asked you if this was an all or nothing thing with you. If you were so against supporting the other features that I was working on implementing, you should have told me to stop wasting my time implementing those other features instead of telling me you would accept such an implementation. You should have had enough respect for me to be honest, and we wouldn't be having this discussion.

**Comment by gitghostcoder** [comment]
I've created a patch to restore some of the functionality tossed for anyone who had been wanting to try the *other* features.

https://gist.github.com/anonymous/28d81c6b209771fd8b3cc4400c6a5bd1

If you were interested in a "kids mode", you can hide the main menu which rather than actually hiding the main menu removes most of the entries. You could also hide the main menu and advanced settings to suppress most of the entries in the quick menu. I had been working on loading cheats automatically when a game was started from a playlist so the cheats entry doesn't really work... 

If you were interested in moving the tabs around instead of just hiding them, you can reorder the menus. You just can't reorder the menus in the gui because Kivutar thought it would make the menus too complex, and I was trying to get my code to the point where he would be happy.

You can edit the retroarch.cfg directly if you want to try things out.

0 = Hidden
1-10 = Playlist Left
11-20 = Playlist Right

xmb_menu_position_history = "11"

Would push the history menu for games to the right of any of your normal playlists.

xmb_menu_position_images = "4"
xmb_menu_position_music = "3"
xmb_menu_position_video = "2"

Would leave the images, music, and video to the left of your normal playlists. They would instead display in the video, music, and images order.

**Pull request merged**
