### PR TITLE
Streamlining brightness control in Retroarch (for Lakka)

### PR DESCRIPTION
**Pull request by davidgfnet**
This is an attempt to improve the already existing support for Nintendo Switch to control screen brightness when using Lakka.
Adds a generic hook to do so that, at least for now, is picked at build time. Future improvements could use get_lakka_version to figure out a way to change brightness in the platform.

For now this supports Nintendo Switch and Odroid Go Advance (and clones). There are plans to add more platforms with embedded screen (Dingux-like platforms IIIRC). New translations will be needed!

### CODE REVIEW

**Comment by jdgleaver** [comment]
We'll need to sort out automatic restoration of the configured brightness value on startup/driver reinit, but I understand that there are some hardware-related difficulties in doing this, so we can postpone it for another PR.

As it stands, this looks good to me - ready for merging :)

**Comment by WeedyWeedSmoker** [comment]
This somehow breaks netplay on iOS (crashes when loading content after enabling netplay…) @twinaphex @davidgfnet

**Comment by twinaphex** [comment]
Hi @WeedyWeedSmoker , do you have a potential fix for us?

**Comment by davidgfnet** [comment]
Lol it's weird right? I cannot imagine how this breaks iOS netplay. Did you bisect it to get to this commit?

**Comment by WeedyWeedSmoker** [comment]
@davidgfnet I bisected it, and even tried to revert individual file changes, but I had to revert almost this whole commit for netplay to work again on the latest commit

**Comment by davidgfnet** [comment]
Ah nice, thanks for doing this!
Is there a way you can get a backtrace or a coredump? Does netplay work on other platforms?
Thanks!

**Comment by WeedyWeedSmoker** [comment]
@davidgfnet I just tried commit https://github.com/libretro/RetroArch/commit/4c51e31b9db95ef1ccf28f2c63b2d11742485911 by @twinaphex and it actually fixes netplay on iOS!

That was a strange issue indeed… Thanks!

**Comment by davidgfnet** [comment]
I just realized that I forgot to update platform_darwin in my commit. So the pointer table is wrong and that can cause the crash. Does that make sense?
The commit you mention seems to refactor that and fix it.
Heh if only we had better gcc warnings we could have caught this!

**Pull request merged**
