### PR TITLE
(dispserv_x11.c) add missing defines and clean-up code

### PR DESCRIPTION
**Pull request by hhromic**
## Description

When building with x11 headers but without xrandr headers, i.e. in a very minimal system, the build fails because of missing define checks for `HAVE_XRANDR`. This PR adds these to the relevant parts of the source code. Without xrandr, mode switching is simply no-op. Most users highly likely have x11 + xrandr headers, explaining why this has been unnoticed all this time.

* Removed redundant and unused variables
* Use multiples of eight for array sizes
* Styled code for consistency with the rest
* Quoted string arguments in shell commands
* Added missing `HAVE_XRANDR` define checks

This PR has been tested by building with and without xrandr headers installed in the system. Both cases are building fine. For the normal case of x11 + xrandr this PR should not alter any current functionality, however I don't have means to verify it.  If anybody using this functionality can confirm, would be great.

## Related Issues

https://github.com/libretro/RetroArch/issues/8191#issuecomment-466444571

## Reviewers

@orbea

### CODE REVIEW

**Comment by orbea** [comment]
That build worked without xrandr for me, but there are new warnings now with gcc8.
```
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_set_resolution’:
gfx/display_servers/dispserv_x11.c:315:43: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 235 [-Wformat-truncation=]
                "xrandr --addmode \"%s\" \"%s\"",
                                           ^~
                outputs->name, new_mode);
                               ~~~~~~~~     
gfx/display_servers/dispserv_x11.c:314:10: note: ‘snprintf’ output 23 or more bytes (assuming 278) into a destination of size 256
          snprintf(xrandr, sizeof(xrandr),
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                "xrandr --addmode \"%s\" \"%s\"",
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                outputs->name, new_mode);
                ~~~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:319:49: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 229 [-Wformat-truncation=]
                "xrandr --output \"%s\" --mode \"%s\"",
                                                 ^~
                outputs->name, new_mode);
                               ~~~~~~~~           
gfx/display_servers/dispserv_x11.c:318:10: note: ‘snprintf’ output 29 or more bytes (assuming 284) into a destination of size 256
          snprintf(xrandr, sizeof(xrandr),
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                "xrandr --output \"%s\" --mode \"%s\"",
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                outputs->name, new_mode);
                ~~~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:323:43: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 235 [-Wformat-truncation=]
                "xrandr --delmode \"%s\" \"%s\"",
                                           ^~
                outputs->name, old_mode);
                               ~~~~~~~~     
gfx/display_servers/dispserv_x11.c:322:10: note: ‘snprintf’ output 23 or more bytes (assuming 278) into a destination of size 256
          snprintf(xrandr, sizeof(xrandr),
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                "xrandr --delmode \"%s\" \"%s\"",
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                outputs->name, old_mode);
                ~~~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:327:35: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 239 [-Wformat-truncation=]
                "xrandr --rmmode \"%s\"",
                                   ^~
                old_mode);
                ~~~~~~~~            
gfx/display_servers/dispserv_x11.c:326:10: note: ‘snprintf’ output between 19 and 274 bytes into a destination of size 256
          snprintf(xrandr, sizeof(xrandr),
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                "xrandr --rmmode \"%s\"",
                ~~~~~~~~~~~~~~~~~~~~~~~~~
                old_mode);
                ~~~~~~~~~
gfx/display_servers/dispserv_x11.c:289:46: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 235 [-Wformat-truncation=]
                   "xrandr --addmode \"%s\" \"%s\"",
                                              ^~
                   outputs->name, new_mode);
                                  ~~~~~~~~     
gfx/display_servers/dispserv_x11.c:288:13: note: ‘snprintf’ output 23 or more bytes (assuming 278) into a destination of size 256
             snprintf(xrandr, sizeof(xrandr),
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   "xrandr --addmode \"%s\" \"%s\"",
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   outputs->name, new_mode);
                   ~~~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:293:52: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 229 [-Wformat-truncation=]
                   "xrandr --output \"%s\" --mode \"%s\"",
                                                    ^~
                   outputs->name, new_mode);
                                  ~~~~~~~~           
gfx/display_servers/dispserv_x11.c:292:13: note: ‘snprintf’ output 29 or more bytes (assuming 284) into a destination of size 256
             snprintf(xrandr, sizeof(xrandr),
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   "xrandr --output \"%s\" --mode \"%s\"",
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   outputs->name, new_mode);
                   ~~~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:297:46: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 235 [-Wformat-truncation=]
                   "xrandr --delmode \"%s\" \"%s\"",
                                              ^~
                   outputs->name, old_mode);
                                  ~~~~~~~~     
gfx/display_servers/dispserv_x11.c:296:13: note: ‘snprintf’ output 23 or more bytes (assuming 278) into a destination of size 256
             snprintf(xrandr, sizeof(xrandr),
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   "xrandr --delmode \"%s\" \"%s\"",
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   outputs->name, old_mode);
                   ~~~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:301:38: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 239 [-Wformat-truncation=]
                   "xrandr --rmmode \"%s\"",
                                      ^~
                   old_mode);
                   ~~~~~~~~            
gfx/display_servers/dispserv_x11.c:300:13: note: ‘snprintf’ output between 19 and 274 bytes into a destination of size 256
             snprintf(xrandr, sizeof(xrandr),
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   "xrandr --rmmode \"%s\"",
                   ~~~~~~~~~~~~~~~~~~~~~~~~~
                   old_mode);
                   ~~~~~~~~~
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_destroy’:
gfx/display_servers/dispserv_x11.c:77:33: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 238 [-Wformat-truncation=]
             "xrandr --addmode \"%s\" 700x480_59.94",
                                 ^~
             orig_output);
             ~~~~~~~~~~~          
gfx/display_servers/dispserv_x11.c:76:7: note: ‘snprintf’ output between 34 and 289 bytes into a destination of size 256
       snprintf(xrandr, sizeof(xrandr),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "xrandr --addmode \"%s\" 700x480_59.94",
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             orig_output);
             ~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:81:32: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 239 [-Wformat-truncation=]
             "xrandr --output \"%s\" --mode 700x480_59.94",
                                ^~
             orig_output);
             ~~~~~~~~~~~         
gfx/display_servers/dispserv_x11.c:80:7: note: ‘snprintf’ output between 40 and 295 bytes into a destination of size 256
       snprintf(xrandr, sizeof(xrandr),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "xrandr --output \"%s\" --mode 700x480_59.94",
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             orig_output);
             ~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:85:33: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 238 [-Wformat-truncation=]
             "xrandr --delmode \"%s\" \"%s\"",
                                 ^~
             orig_output, old_mode);
             ~~~~~~~~~~~          
gfx/display_servers/dispserv_x11.c:84:7: note: ‘snprintf’ output between 23 and 533 bytes into a destination of size 256
       snprintf(xrandr, sizeof(xrandr),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "xrandr --delmode \"%s\" \"%s\"",
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             orig_output, old_mode);
             ~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:89:32: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 239 [-Wformat-truncation=]
             "xrandr --rmmode \"%s\"",
                                ^~
             old_mode);
             ~~~~~~~~            
gfx/display_servers/dispserv_x11.c:88:7: note: ‘snprintf’ output between 19 and 274 bytes into a destination of size 256
       snprintf(xrandr, sizeof(xrandr),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "xrandr --rmmode \"%s\"",
             ~~~~~~~~~~~~~~~~~~~~~~~~~
             old_mode);
             ~~~~~~~~~
```
Without this patch the only warnings with this code are.
```
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_set_resolution’:
gfx/display_servers/dispserv_x11.c:156:45: warning: ‘%d’ directive output may be truncated writing between 1 and 11 bytes into a region of size 7 [-Wformat-truncation=]
    snprintf(crt_name, sizeof(crt_name), "CRT%d", crt_name_id);
                                             ^~
gfx/display_servers/dispserv_x11.c:156:41: note: directive argument in the range [-2147483647, 2147483647]
    snprintf(crt_name, sizeof(crt_name), "CRT%d", crt_name_id);
                                         ^~~~~~~
gfx/display_servers/dispserv_x11.c:156:4: note: ‘snprintf’ output between 5 and 15 bytes into a destination of size 10
    snprintf(crt_name, sizeof(crt_name), "CRT%d", crt_name_id);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by orbea** [comment]
@alphanu1 You might be able to help review this PR since I believe you have been working on this code?

**Comment by hhromic** [comment]
@orbea thanks for the warnings, I'm using Debian Stretch which comes with GCC 6.3 so didn't see them in my tests. Fortunately they are simple to address, will force-push with improvements soon.

**Comment by alphanu1** [comment]
@orbea It look good reading through it. 

I not able to test ATM. But if anything gets broken I'll fix it.

**Comment by hhromic** [comment]
@orbea I enlarged the size of `xrandr` now to accomodate the strings as the warnings indicate (good guy GCC8!). Can you please re-test it? Should be fine now. If not, please post the remaining warnings :)

**Comment by orbea** [comment]
I'm getting no warnings now. :) I can't test this during run time however.

**Comment by bparker06** [comment]
@hhromic I noticed you're using (and existing code is using) XOpenDisplay here (and coincidentally there's no calls to XCloseDisplay either which is wrong)... but is there any reason we can't just use the global `g_x11_dpy` that is always open?

**Comment by ofry** [comment]
@hhromic @orbea Please fix merge conflicts.

**Comment by hhromic** [comment]
@bparker06 to clarify I didn't write this code, with this PR I'm simply cleaning it up and adding the missing `HAVE_XRANDR` checks for it to compile when there is no xrandr headers in the system.

I agree with you that Open functions should be paired with Close functions. Regarding `g_x11_dpy`, as I didn't design this code, I'm not the right person to ask :) However it makes sense as you suggest. Unfortunately I don't have X11 programming experience so I would prefer someone with that experience to address these issues instead.

I also noticed you now applied some of the changes in this PR in recent commits, so I will rebase this with any missing changes (as @ofry just pointed)

**Comment by hhromic** [comment]
@ofry @orbea rebased now, should be good to go (testing welcome)

@bparker06 now that I rebased the code I can see 100% what you meant about using `g_x11_dpy` directly. I fully agree with you that using this like you did for setting the screen orientation is the better approach. I can update the code using your code for screen orientation as model however I can't test it. Let me know what you prefer to do.

**Comment by alphanu1** [comment]
CRTSwitRes code does now use g_x11_dpy . Haven't merged for a while as some of the new additions aren't ready for mainstream.

**Comment by hhromic** [comment]
@alphanu1  for now the code is exactly as it was before, just cleaned-up and prepared for when you don't have xrandr in the system.

When you merge your new changes, can you please make sure you don't undo the changes in this PR? I can help by reviewing later when you submit these changes too. Thanks!

**Comment by alphanu1** [comment]
@hhromic no worries I'll pull from RA first!

**Comment by bparker06** [comment]
Thanks guys, and @hhromic there should be no issues with switching it to use `g_x11_dpy` if you don't mind.

**Comment by ofry** [comment]
@hhronic Merge conflicts exists again.

**Comment by bparker06** [comment]
Sorry about that. I was asked to make additional changes.

**Comment by hhromic** [comment]
@ofry  rebased again ;)

@bparker06 no worries, was an easy rebase. However I noticed that you switched from using `g_x11_dpy` to using `XOpenDisplay()`.  Is this the recommended approach then? @alphanu1 probably should take that in consideration as he was moving to `g_x11_dpy` for the resolution set functions: https://github.com/libretro/RetroArch/pull/8349#issuecomment-466641092

**Comment by alphanu1** [comment]
@hhromic @bparker06  It's not an issue either  way, just let me know what we are going with.

I don't have time to check the PR ATM but I'll make sure CRTSwitchRes remains working after.

**Comment by bparker06** [comment]
@hhromic The reason I changed it in this case was because we're now calling set_screen_orientation when RA is shutting down, to restore the initial orientation that was set when the program was started, but the global `g_x11_dpy` is already freed at that point.

But for normal switchres use, unless you have to deal with the same thing when exiting, it should be safe to use the global.

**Comment by hhromic** [comment]
@bparker06 @alphanu1 I would assume that when exiting RA, you also want to restore the resolution as well to the originalsettings before starting RA, so maybe `XOpenDisplay()` is also better for this?

@alphanu1 I was curious on why it is necessary to call the `xrandr` binary through `system()` to manipulate the output resolution? That can't be done programmatically using xrandr functions directly?

**Comment by alphanu1** [comment]
@hhromic it is possible to do it programmatically. However, I do not have it working yet. You can see in the code I am using XRRModeInfo to build up the the resolution information. One issue is the mode flags, just need to figure that part out. Then it's just a case of utilizing XRRCreateMode , XRRSetMode and XRRDeleteMode.

Do you have knowledge in this area and be able to help out?

**Comment by hhromic** [comment]
> Do you have knowledge in this area and be able to help out?

I do not have ready-to-use knowledge nor experience on X11 programming unfortunately. Also I don't have a proper testing env (running x11 and CRT), so can't test :(

**Pull request merged**
