### PR TITLE
First Integration RetroArch For PS2

### PR DESCRIPTION
**Pull request by fjtrujy**
## Overview
This PR contains the first phase of the development of the RetroArch for the PS2 Platform.

## Description
The `PS2` architecture is similar to the `PSP` (first version) one, so I have taken as a reference the PSP1 implementation.

As you can guess all the functionality that RetroArch offers are not implemented yet, but so far we have implemented the first version of some driver:

- Platform
- GFX
- JoyPad
- Input

We don't have audio driver for now.

## Additional Information

`PS2 SDK` is not fully using `newlib`, so they are using another another `libc` library. The problem is that library is kind of buggy, so in order to make it work, I have needed to implement here a lot of string functions.

### CODE REVIEW

**Comment by Sunderland93** [comment]
Amazing! Is it possible to save game state's to PS2 Memory Card?

**Comment by TnA-Plastic** [comment]
Hm... It fails to compile here...

I've got the newest toolchain and PS2SDK installed, but Griffin does not like me, lol.

**Comment by fjtrujy** [comment]
You need to have a libretro_ps2.a core in the root of the repo

**Comment by TnA-Plastic** [comment]
Where do I find that file, or how to create it?

Is your tutorial on libretro missing some expressions?

**Comment by fjtrujy** [comment]
So,
In order to make compile RetroArch, when it uses static linking (as the PS2 does), you need to compile first the one core.
So, when you compile one core and you put on the folder with the name that I said, you could continue with the compilation of RetroArch.

On the tutorial we are not mentioning anything regarding the cores, but we should. Not sure if we have different place were we are mentioning how to compile with static linking.

Anyway you didn't post the error that you are receiving, you just said `is not compiling`, just with this information as you can guess we can not know what is happening.

Finally I think that comment in the PR that was already merged I think that is not a good approach either, you should open a github issue.

Is good that more people like you are trying to compile the RetroArch for PS2, it will help to identify issues (we have for sure issues), but let's go to do it in a good way.

So please, give a try once more, and if still you are not able to compile, create a github issue.

Thanks!

**Comment by TnA-Plastic** [comment]
Yes, that (missing) file probably is the cause. ;) 

Well, it gave me an 'Error 1' on 'griffin.o' (or similar name... I will look it up, when I am at home.) and 'No rule for target' or similar.
I can post a screen-shot or the last line/-s later.

I've got no clue, where to start about compiling a core for the PS2, honestly.

Is there any 'general Retroarch core compiling tutorial' (not specifically limited to the PS2) available somewhere, or anything I should read (up on)?


I posted it here in the PR, because it is the first implementation and seems related (due to all the additions and changes), but I will/might create an issue, once I determined where I might have other issues, if it also doesn't work with a pre-compiled core for the PS2 (if I get one to compile), to compile Retroarch.


Oh and I've seen the link to the source and to the... erm... 'tutorial' and thought, I would give it a try and maybe I can help out in a way. ;)
The first idea which comes to mind is 'letting more people know, how to compile it (properly)' via a tutorial and thus getting more people interested in it, or even 'into the project'.

This (project) will probably even lead to quite some new people entering the scene, or old-schoolers returning OR new developers emerging in the scene (just as FMCB and OPL did).

So that's why I took a glimpse of trying (to compile) it, so we could get more people working on it. :)


A little intro/tutorial would be neat (at the usual places/boards as well), but you don't need to write one up, once I know what to look for.
I worked a bit with libretro (quite a while ago), but never Retroarch.

Some 'pointers' (what to read or where to start) would be nice! :)


Best regards,
TnA

**Pull request merged**
