### PR TITLE
Added HDR support to Vulkan driver

### PR DESCRIPTION
**Pull request by MajorPainTheCactus**
## Description
This adds HDR support to Vulkan - it may not mean its added to everything that supports Vulkan though as say I think Linux x manager for example will need to support HDR.  All I can say is that it works in Windows.

## Related Issues

N/A

## Related Pull Requests

N/A

## Reviewers

@DisasterMo  Thanks for helping sorting out my git troubles

### CODE REVIEW

**Comment by Sanaki** [comment]
-- comment copied from commit for increased visibility --

As of this commit, all menu shader pipelines are broken with vulkan on x86_64 Linux. My device does not support HDR, which may be a factor, but I also see no way to disable it if that's the issue. I've attached a screenshot of RetroArch with the "Snow" menu shader pipeline selected, which is my default.
Screenshot from 2022-01-08 17-52-51

Behavior verified as far as 176c2d1, using vulkan 1.2.198 on the 495.46 Nvidia driver.

**Comment by twinaphex** [comment]
I can reproduce this issue on Windows yes. Reporting this back to @MajorPainTheCactus .

**Comment by stuken** [comment]
This is also causing crashes on startup on intel xe.

**Comment by MajorPainTheCactus** [comment]
Hi all although @ColinKinloch (btw thanks for investigating) may well have fixed another bug I've not yet seen then I'd take my fixes first and see if the crash issue is fixed - it did for me.  I was using rgui and ozone and they dont use the menu shaders and I'd missed a place where a 4 needed to be changed to a 6 (someone really should #define these).  Anyway my bad and hopefully fixed - it could have been causing all sorts of problems that one.

**Pull request merged**
