### PR TITLE
fix SELECT as hotkey sometimes messy with arcade

### PR DESCRIPTION
**Pull request by paradadf**
This fixes the hotkey being sometimes messy with arcade when on SELECT.

### CODE REVIEW

**Comment by twinaphex** [comment]
Can you explain better what this is intended to solve? I recall @joolswills doing this too in RetroPie's version of RetroArch, I'd just like to know what it's intended to fix and where it manifests itself. The description is pretty vague as-is.

**Comment by hizzlekizzle** [comment]
I believe it delays the "hotkey enable" functionality for a default of 5 frames, which is long enough for the input functionality of the button to take effect.

With the current behavior, if you have the enabler on, say, select, and you press it to insert a coin into a arcade game, it will either not insert a coin at all or it will sometimes (I don't recall which, but neither is good). Adding this imperceptible delay gives the core time to insert the coin before the hotkey-enabler functionality takes over and cancels the original input.

@paradadf , feel free to correct me if I've gotten anything wrong.

**Comment by twinaphex** [comment]
You have a typo in the code right now though that causes this file not to compile. You forgot an '}'.

**Comment by paradadf** [comment]
Sorry about the vage description and the typo... it should be fixed now.
It is exactly what hizzlekizzle said. The problem also happened frequently on netplay; users not being able to insert coins when the hotkey was set on the select button. This fixes the issue.

**Comment by retro-wertz** [comment]
NES VS-System insert coin also has this delay, about 5-6 frames for next coins to be registered.. but that was done through the emulator...

just saying...

**Comment by fr500** [comment]
this seems really nasty and forced upon everyone
it also means every action taken with hotkey enable + button is delayed 5 frames

so if you take a screenshot it will be a screenshot 5 frames later than intended

**Comment by hizzlekizzle** [comment]
That's a good point. I was thinking there wouldn't be any hotkey actions that required frame-perfect precision, but screenshots are a good example.

**Comment by fr500** [comment]
actually it seems that what this does is jut delay the blocking state, then it would be fine except that other core inputs may happen while taking a screenshot or a savestate within that window.

For example say hotkey + B is savestate, it would mean in many games it may trigger a jump before saving a state (leading to death or whatever)

**Comment by paradadf** [comment]
We have been using the code in recalbox long enough to say that no collateral is caused by this delay.

**Comment by rsn8887** [comment]
If you set the hotkey enable to select, how do you prevent inserting a coin every time you try to press a hotkey combination?

**Comment by hizzlekizzle** [comment]
@fr500 that would only be if they hit the button within 5 frames of the hotkey-enabler, though, right? So, if they hold it for at least 5 frames *before* hitting the action button, it will still be blocked...?

**Comment by paradadf** [comment]
@rsn8887 that‘s true, you don‘t. But select is a standard button chosen as hotkey when the gamepad doesn‘t have something else to chose from and this isn‘t different from the standard behavior... I‘d rather have one coin more than not being able to input coins at all.

**Comment by fr500** [comment]
@hizzlekizzle sure, still seems nasty and forced unto everyone

**Comment by twinaphex** [comment]
I agree this is a bit tacky and it might even potentially lead to more unintended consequences that people could perceive as bugs.

**Comment by paradadf** [comment]
Can anyone actually test this and comment if any noticeable difference is found?
Aparently not only recalbox but retropie also uses this kind of patch, so there should be something to correct.
Otherwise and considering I can’t come up with a better way of doing this, would setting `HOTKEY_DELAY 0` something you‘d merge? That would default to the current behavior and spare the need of patching the whole file.
If none of the above yields good results, please feel free to close this PR.

**Comment by twinaphex** [comment]
Would you be interested in exploring how this could be fundamentally improved upon in the core input logic of RetroArch without resorting to a 'delay' hack? I know it's a lot of code to wade through but I think that ideally would be the best approach.

**Comment by paradadf** [comment]
I do have the interest, but I’m certaintly lacking the skills to achieve it, sadly.

**Comment by fr500** [comment]
it's not something that could be feasibly fixed in the core unless the core
implements some kind of buffer for particular keys on particular games.
ie: when you press select the core DOES receive select.

But the  signal for the GAME requires some kind of hold.
It's not even core dependent but game dependent. I remember SSFII needed 5
frames, but VS. games didn't.

**Comment by hizzlekizzle** [comment]
As I recall, this is the exact same discussion we had when this was previous PRed from Retropie folks (@dankcushions , perhaps?). That is, it's hacky/tacky and inelegant and we should come up with a better way of doing it, but clearly that never happened :P

**Comment by twinaphex** [comment]
By 'core', I meant RetroArch's internal input code, not the libretro core side.

**Comment by fr500** [comment]
Even worse, that means forwarding a one frame select as a 5 frame input to
the core.

Just add an option or at least a check that verifies that hotkey mod is
mapped to another button to enable this behavior. That way it's at least
not forced on people who have enough buttons.

**Comment by twinaphex** [comment]
Nah, I think you misunderstand what I was saying. I was saying that instead of him resorting to hacks where it waits for 5 frames before registering input like 'hotkey block', we should instead just make things latch properly in RetroArch so that it isn't necessary to do this. Like you I don't believe adding all sorts of frame counter-based delays to actions is desirable.

**Comment by paradadf** [comment]
I can’t really think of a better way of adding this. When you press SELECT, you’ll add a coin, that’s expected. The hotkey is an “invention” or “trick”, so it is not hacky to expect this minimal delay. It is not noticeable. And it fixes the issue of not being able to add coins.

**Comment by dankcushions** [comment]
> As I recall, this is the exact same discussion we had when this was previously PRed from Retropie folks (@dankcushions , perhaps?). That is, it's hacky/tacky and inelegant and we should come up with a better way of doing it, but clearly that never happened :P

i would read all of:
https://github.com/libretro/RetroArch/issues/2230

this PR has been used at retropie for several years with no consequences, but i'm sure there is a better way.

**Comment by fr500** [comment]
I have no problem with it happening, but worst case scenario:
- Should check if the hotkey button is mapped to a retropad button at the
same time
- Should have a setting

**Comment by ofry** [comment]
@paradadf This PR has merge conflicts.

**Comment by snackycakes** [comment]
Hello, I'm new, but have been following this issue for some time and wanted to see if I could help.  Took code from original PR and created PR #1080 to implement a request for configuration to see if it would be a more suitable candidate for merge.

**Comment by dankcushions** [comment]
@snackycakes you linked to the wrong PR. i guess you mean https://github.com/libretro/RetroArch/pull/10801

**Comment by snackycakes** [comment]
Yes, sorry, meant #10801

**Pull request closed without merging**
