### PR TITLE
Fetch translations from Crowdin

### PR DESCRIPTION
**Pull request by guoyunhe**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by DisasterMo** [comment]
Heeey! Welcome back, @guoyunhe! Say, if you have the time, could you please take a look at #12120 (kinda important) & #12439 (not as important)?
Thank you!

**Comment by IlDucci** [comment]
Hey there! I think a bigger question needs to be asked.

Since your Internet connectivity is so limited, we've been having issues to update the translations whenever a big revision was done. This happens because you are marked on Crowdin as the sole owner of the translation project, thus, you are the only one who can use Crowdin to reimport the strings back onto GitHub.

So far @DisasterMo and I have done standalone updates by building the project on Crowdin and then doing a PR via our repos, but I'd like to ask you if you could try to fix this bottleneck and see if Autechre or someone else could also be assigned as an owner or have a rank alongside you in order to update the translations with a shorter notice.

What do you think?

**Comment by guoyunhe** [comment]
One thing to be cleared: everyone in the list have full control of the Crowdin project:

image

You can download and upload translation if you setup a local environment with credentials from the project settings.

I don't have any special permissions...

**Comment by IlDucci** [comment]
Are you saying that the importing method was always manual?!?!?

Then I'm sorry for taking the wrong assumption. This explains quite a few things.

**Comment by twinaphex** [comment]
What we can possibly do is add more in a direct succession list so that if anything were to happen to anyone on that list, somebody can still pick up the baton.

**Comment by IlDucci** [comment]
I'd really wish we had a system that goes as automatic as the current export procedure. Other projects (usually based on other, non-Crowdin system, so I don't know how does the Crowdin integration works) typically have scripts in place to automatically reimport the translations from the server (typically either with a timer, like per day or week, or as soon as someone hits the build button). That way we wouldn't have this sort of bottlenecks.

In any case, knowing now that the translations import process is manual, well, anyone from that list can do that.

**Pull request merged**
