### PR TITLE
CRTSwitchRes Updates: Including Raspberry PI

### PR DESCRIPTION
**Pull request by alphanu1**
New Linux switching method partially implemented. Not all system calls have been replaced yet

Linux restore desktop resolution fixed.

Monitor index switching and auto enumerate for output detection in Linux (still working on the windows method)

Added Raspberry PI Switching method. This Uses Raspiberry PI userland. Currently this is if defed, this is a temporary measure and will need to be placed in a new display server eventually. Not all of userland is currently used. However, it may in the future.

### CODE REVIEW

**Comment by twinaphex** [comment]
Just a general note - don't use sprintf anymore, I will clean this up for you in this case. Use snprintf instead of sprintf always.

**Comment by orbea** [comment]
@alphanu1 and @twinaphex New warnings.
```
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_set_resolution’:
gfx/display_servers/dispserv_x11.c:138:12: warning: variable ‘scrn’ set but not used [-Wunused-but-set-variable]
    Screen *scrn             = NULL;
            ^~~~
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_destroy’:
gfx/display_servers/dispserv_x11.c:86:34: warning: ‘%s’ directive output may be truncated writing up to 249 bytes into a region of size between 233 and 482 [-Wformat-truncation=]
             "xrandr --delmode %s %s",orig_output, old_mode);
                                  ^~               ~~~~~~~~
gfx/display_servers/dispserv_x11.c:85:7: note: ‘snprintf’ output between 19 and 517 bytes into a destination of size 500
       snprintf(output, sizeof(output),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "xrandr --delmode %s %s",orig_output, old_mode);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by alphanu1** [comment]
I will have a look into this. I have not noticed them while I was compiling.

@orbea what is your compile environment?

**Comment by orbea** [comment]
@alphanu1 Slackware Linux with gcc-8.2.0.  These warnings were new with gcc8 and they used to be really spammy with RetroArch, but most have been entirely silenced/fixed until recently again.

**Comment by orbea** [comment]
@alphanu1 Would this work? I'm not sure how to test this change, but it at least silences the warning here.
```
diff --git a/gfx/display_servers/dispserv_x11.c b/gfx/display_servers/dispserv_x11.c
index 2c6d168cb4..07c5250be0 100644
--- a/gfx/display_servers/dispserv_x11.c
+++ b/gfx/display_servers/dispserv_x11.c
@@ -44,7 +44,7 @@ static char new_mode[250]       = {0};
 static char xrandr[250]         = {0};
 static char fbset[150]          = {0};
 static char output[500]         = {0};
-static char output4[500]         = {0};
+static char output4[500]        = {0};
 static bool crt_en              = false;
 static unsigned crtid           = 20;
 static XRRModeInfo crt_rrmode;
@@ -83,11 +83,9 @@ static void x11_display_server_destroy(void *data)
       system(output);
 
       snprintf(output, sizeof(output),
-            "xrandr --delmode %s %s",orig_output, old_mode);
+            "xrandr --delmode %s %.s",orig_output, old_mode);
       system(output);
 
-
-
       snprintf(output, sizeof(output), "xrandr --rmmode %s", old_mode);
       system(output);
    }
```
That would leave this warning.
```
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_set_resolution’:
gfx/display_servers/dispserv_x11.c:136:12: warning: variable ‘scrn’ set but not used [-Wunused-but-set-variable]
    Screen *scrn             = NULL;
            ^~~~
```
Do you plan to do something with this variable or should it just be removed?

**Comment by alphanu1** [comment]
The Screen variable will be used soon. It can remove for now though if you wish.

I'm going to create a pull request in a min as there is a resolution restore issue with auto detect.

**Comment by dankcushions** [comment]
why was the entire RPI userland brought in? surely if you're using an RPI this is already available?

**Pull request merged**
