### PR TITLE
(Menu) Fix crash when changing core's options on Android

### LINKED ISSUE #7130: (Android) Crash when changing core's options
When using the core theodore, RetroArch 1.7.3 (Android version) crashes each time I try to change one of the core's option.
There is no problem when using the Linux version of RetroArch. Also, the crash occurs on two phones I tested (one under Android 8 and another under Android 7), but not on a Tablet running Android 7.
It may be a bug on the core, however I cannot find any problem on it, even when using Valgrind on Linux to detect potential memory read/write problems.
I have a detailed report on the bug (cf. below). It is a null pointer dereference that occurs in the menu_input_post_iterate function.

Thanks for your help.

```Build fingerprint: 'HUAWEI/PRA-LX1/HWPRA-H:8.0.0/HUAWEIPRA-LX1/370(C432):user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 7090, tid: 7111, name: Thread-5  >>> com.retroarch <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
Cause: null pointer dereference
    r0 00000000  r1 00000000  r2 00005000  r3 00000001
    r4 c5967000  r5 de0eda40  r6 00000168  r7 c705c6c8
    r8 00000001  r9 00000092  sl 00000005  fp c6deb5f8
    ip d87b08c0  sp c6deb5f0  lr c7089b50  pc c705c6f8  cpsr a00d0010
    d0  72635f7343b40000  d1  706f5f6343120000
    d2  40d046aa43dbdc48  d3  000000004312dc48
    d4  0000000000000000  d5  0000000000000000
    d6  0000000000000000  d7  0000000000000000
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 000000020000003c  d17 0000000100000001
    d18 0000000003980a30  d19 0000000004108fb0
    d20 bf67a000bf67a000  d21 bf67a000bf67a000
    d22 bf67a000bf67a000  d23 bf67a000bf67a000
    d24 3d36d927bc35df80  d25 3f648e19be0917c4
    d26 bdc376d93e8cd794  d27 bb8cbe6a3d0ccc82
    d28 0000000000000000  d29 0000000000000000
    d30 00000000735a11e4  d31 000008d0000008c4
    scr 8b000011

backtrace:
    #00 pc 002706f8  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so
    #01 pc 0029db4c  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so
    #02 pc 002493f8  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so (menu_input_post_iterate+3868)
    #03 pc 0028aae8  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so (generic_menu_iterate+2208)
    #04 pc 00245c88  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so (menu_driver_iterate+272)
    #05 pc 001db0a8  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so (runloop_iterate+1564)
    #06 pc 001da918  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so (rarch_main+296)
    #07 pc 002fc844  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so
    #08 pc 002201e4  /data/app/com.retroarch-oW8E8dz2ksH6nxG1X7-4rw==/lib/arm/libretroarch-activity.so
    #09 pc 000486cf  /system/lib/libc.so (_ZL15__pthread_startPv+22)
    #10 pc 0001b02f  /system/lib/libc.so (__start_thread+32)

- RetroArch: 1.7.3

### Environment information

- OS: Android

### PR DESCRIPTION
**Pull request by Zlika**
Fixes crashes on Android when changing a core's option on cores having less then 10 option items (cf. #7130).
I do not master the code base so there is maybe/certainly a cleaner way to fix this bug, but this small commit seems to do the job.

### CODE REVIEW

**Comment by twinaphex** [comment]
Can you make this C89 compliant? As in - all variables should be declared at the top of a function/code block.

**Comment by Zlika** [comment]
I've fixed the C89 error.

**Comment by twinaphex** [comment]
Apparently according to @alfrix, this caused a crash in XMB instead -

https://github.com/libretro/RetroArch/pull/7277

Pleas revisit this and make sure it will no longer crash with XMB.

**Comment by alfrix** [comment]
caused #7276

**Pull request merged**
