### PR TITLE
(RGUI) Add 'full width' layout option

### LINKED ISSUE #8354: (RGUI) Load Content settings are misaligned.
## Description

When using the `rgui` menu driver the the root directory under `Load Content` is misaligned.

### Expected behavior

The settings should be aligned.

### Steps to reproduce the bug

1. Start RetroArch with the `rgui` menu driver.
2. Select `Load Content`.
3. Observer the `/` root directory setting.

### Bisect Results

This started between `v1.5.0` and `v1.6.0`.
```
ecadf864c56be9c497a7cdaff8ad178796b1eeb1 is the first bad commit
commit ecadf864c56be9c497a7cdaff8ad178796b1eeb1
Author: twinaphex <libretro@gmail.com>
Date:   Fri May 26 15:57:18 2017 +0200

    Fixed font selection

:040000 040000 aa738927cc809fb62f872065cf215d389fcce174 7877209c02b05545169a5f9a68427a106644d673 M	frontend
:040000 040000 10004f83ceb874ae526f096749be51b292e6938f 5a81ee3d9693e1a443c89fd4b291efea4e662ef2 M	menu
```
ecadf864c56be9c497a7cdaff8ad178796b1eeb1

### Version/Commit
You can find this information under Information/System Information

- RetroArch: d2f73e3f33f93f8606bcf7e60d09cfc74a73d304

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.2.0`

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

As pointed out by @orbea in issue #8354, RGUI currently has a couple of entry value alignment issues, and the layout in general wastes a great deal of space on the right hand side of the screen.

It's not really practical to address this with the current layout technique, so this PR adds a new 'full width' layout method. This very simply:

- Right aligns menu entry values

- Expands entry labels to fill all available space

I can't see any reason not to use this method (it's better in every way), so it's enabled by default. To switch back to the old one, set `User Interface > Appearance > Use Full-Width Layout` `OFF`.

Here are some random screenshots. In each case, it's the original layout followed by the new 'full width' layout:

screenshot_2019-02-25_11-53-39

screenshot_2019-02-25_11-57-39

screenshot_2019-02-25_11-54-28

screenshot_2019-02-25_11-58-00

screenshot_2019-02-25_11-55-05

screenshot_2019-02-25_11-58-20

screenshot_2019-02-25_11-56-42

screenshot_2019-02-25_11-58-43

## Related Issues

I believe this should close #8354

### CODE REVIEW

**Comment by orbea** [comment]
Looks good! Thanks a lot. :)

**Comment by hizzlekizzle** [comment]
This indeed looks superior in every way.

**Comment by orbea** [comment]
Maybe there is one minor way this could improve?

Take this image for example.

example

Maybe it would be better if the right column was aligned on the first character? It looks kind of off when `ON` and `OFF` are slightly misaligned. Regardless this is still better than before!

**Comment by jdgleaver** [comment]
@orbea That would be nice, but ensuring semi-left alignment in a properly generic fashion has a significant performance impact - we would have to loop through the whole list first in order to determine max/min widths, so we'd have to cache everything and end up with double the amount of string duplications etc. Since RGUI targets low end hardware, I don't like the idea of this...

OFF/ON could be made special cases, I suppose, but then you'd have the same alignment offset in list of ints/enums/whatever mixed with a bool.

As a side note, Ozone also has this issue:

screenshot_2019-02-25_14-26-47

**Comment by orbea** [comment]
Good point, it would not be worth fixing if that caused a significant performance impact. Also with the spacing between settings in ozone it doesn't look as bad, but that wouldn't really work with rgui.

I think its good enough as is and it can always be improved in the future if a good method is found.

**Pull request merged**
