### PR TITLE
Fix GLES3 compling

### PR DESCRIPTION
**Pull request by loganmc10**
Note: This pull request also includes changes to libretro-common that will need to get merged into that repo as well.

This fixes ```./configure --enable-gles --enable-gles3```.

GLES3 actually does share the same extensions as GLES2, so using "GLES2/gl2ext.h" with GLES3 is correct. Many GLES3 implementations (like MESA) actually still use libGLESv2.so for GLES3 (and linking with -lGLESv2 for GLES3)

There were also some #ifdef's that assumed that "HAVE_OPENGLES2" meant any version of GLES, but "HAVE_OPENGLES2" is not defined when using GLES3, HAVE_OPENGLES is though.

### CODE REVIEW

**Comment by twinaphex** [comment]
Thanks, have you confirmed if the ribbons still work with GLES3 in the XMB menu?

**Comment by loganmc10** [comment]
No I just tested with RGUI, I'll test with XMB

**Comment by twinaphex** [comment]
OK, thanks.

**Comment by loganmc10** [comment]
XMB still looks good, I navigated around the menu's and loaded a game and such.

screenshot from 2016-08-07 22-50-10

**Comment by twinaphex** [comment]
OK, looks fine then. 

Maybe on GLES3 we can use the fancy ribbon for XMB since I imagine partial derivatives might be a default feature for ES3. But we can look at that later.

Thanks for this at any rate.

**Comment by loganmc10** [comment]
When I try to compile without those changes to shaders_glsl.c I got:

```no matching function for call to dFdx```

This is with an Intel Graphics card, I don't know if that issue exists for other GPUs

**Comment by loganmc10** [comment]
It is probably related to this:

https://bugs.chromium.org/p/chromium/issues/detail?id=243038

**Pull request merged**
