### PR TITLE
support subsystem type netplay lobbies

### PR DESCRIPTION
**Pull request by fr500**
It still doesn't allow connecting!!! **do-not-merge**
This will allow loading subsystem type content for netplay

Usecases:
- Pokemon battles with sameboy and tgb dual
- Netplay all the fba subsystems

Hopefully we'll get more subsystem support in the future now that the gui is functional

Previews:

Single game subsystem lobby:
image

Dual game subsystem lobby:
image

Progress:
- [x] lobby server changes
- [x] announcing lobbies
- [x] querying lobbies
- [x] scan for the content files in playlists
- [x] load and connect

### CODE REVIEW

**Comment by fr500** [comment]
Done, review plz @twinaphex @bparker06

**Comment by fr500** [comment]
that... wasn't me, but according to our conversation replaced free(playlist) with playlist_free(playlist) and simplified the loop a bit

**Comment by twinaphex** [comment]
OK, just let me know when this is fit to be merged and we can sneak it in before the 1.7.6 release.

**Comment by fr500** [comment]
it's as ready as it will ever be heh

**Pull request merged**
