### PR TITLE
unify input bind hold behavior across platforms

### PR DESCRIPTION
**Pull request by markwkidd**
This would resolve https://github.com/libretro/RetroArch/issues/7871 by enabling the "Bind Hold" function for all platforms, not just Android.

The other alternative that has been discussed would be to hide this setting from the menu in all versions of RetroArch other than for Android if that is the only platform where it is intended to be used.

### CODE REVIEW

**Comment by markwkidd** [comment]
That makes sense.

I've pushed a commit to bring back that logic, but I've also screwed up my RA build environment so I will need to fix my mess here before I can test to make sure things work as expected when refactored this way

**Comment by markwkidd** [comment]
I've tested this PR and all is working as expected

**Comment by fr500** [comment]
I think this is a good change, it makes input binding slower but more precise (sometimes binding analogs is tricky otherwise)

**Comment by hizzlekizzle** [comment]
Does anyone dislike this change? @twinaphex @bparker06

**Comment by markwkidd** [comment]
There is some discussion of changing the default bind hold period to be `1` second rather than two. For my own reference in case I need to make that change in this PR, here's the line: https://github.com/libretro/RetroArch/blob/4368f6cb66814096d8762678d4f5e36912411159/config.def.h#L760

**Pull request merged**
