### PR TITLE
Analog button and keyboard tester

### PR DESCRIPTION
**Pull request by zoltanvb**
## Description
Added analog button indication for those buttons that may have use for it - primarily L2/R2, but support was added for all buttons where at least one controller is known to support it (L,R,L2,R2,A,B,X,Y). The indication is a smaller rectangular area inside the button, which changes color according to the analog value, from black to red, see R2 on the screenshot. Analog axes have now also dynamic coloring.

RetroPad Remote-240330-182629

Added also core option to show mismatching inputs where analog value is not sent (like keyboard hotkeys assigned to retropad buttons). If not hidden, the rectangular area remains white/green, see L1 on the screenshot.

Analog button values are not set up for remote transmission, only for local test.

Added a keyboard tester screen which includes a standard 102-key PC keyboard + extra blocks for all RETROK_ values present in the code. Screen adapted from DOSBox-Pure onscreen keyboard with permission. Keyboard button A+B switches between the two screens. Keyboard inputs are not set up for remote transmission, only for local test. Core option added to select start screen.
RetroPad Remote-240330-182858

The test input part can now request pressing keyboard keys, by setting expected_button to 1000+RETROK_ value. Display will switch to keyboard if test sequence requires.
```
{
  "expected_button": 1032,
  "message": "Press spacebar"
},
```

Other small improvements: retropad core reset will use new option values, input driver applies received values more carefully.

## Related Pull Requests

#16342 
#16357

### CODE REVIEW

**Comment by zoltanvb** [comment]
Hi, is there something I should change in this? There are a few other improvements/fixes I plan to do, where having this would come handy.

**Comment by hizzlekizzle** [comment]
@LibretroAdmin care to take a look?

**Comment by zoltanvb** [comment]
One more ping.

**Comment by sonninnos** [comment]
I'm getting this warning now:
```
cores/libretro-net-retropad/net_retropad_core.c: In function 'open_UDP_socket':
cores/libretro-net-retropad/net_retropad_core.c:589:7: warning: implicit declaration of function 'close'; did you mean 'fclose'? [-Wimplicit-function-declaration]
  589 |       close(s);
      |       ^~~~~
      |       fclose
```

**Comment by zoltanvb** [comment]
Thx, buildbot also shows this. Looking...

**Pull request merged**
