### PR TITLE
Cleanse colons in Core Information

### PR DESCRIPTION
**Pull request by lasers**
Remove spaces before colons to display information in perfect harmony with other information... and to omit letter s on all "informations"

### CODE REVIEW

**Comment by twinaphex** [comment]
@Kivutar Can you review if these French string changes are OK?

**Comment by lasers** [comment]
https://en.wikipedia.org/wiki/Mass_noun

**Comment by Kivutar** [comment]
There are no mass nouns in French. Informations need to stay informations in this context.

**Comment by lasers** [comment]
Commit removed.

**Comment by lasers** [comment]
@twinaphex? I removed the "Informations" commit yesterday.

**Comment by lasers** [comment]
@twinaphex Please merge this too.

This remove the spaces before the colons.

**Network Information**
```
Interface (lo) : 127.0.0.1
Interface (eno1) : 192.168.1.XXX
```

**System Information**
```
Everything else looks fine.
...
Frontend OS : Linux 4.8
RetroRating : -1
Memory in bytes : 132131
Memory in megabytes : 2312/123123 B
Memory in gigabytes: 3/7 GB <-- This is already fixed.
Network Command interface support : Yes
...
Everything else looks fine.
```

**Pull request closed without merging**
