### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by hyarsan**

### CODE REVIEW

**Comment by bparker06** [comment]
@hyarsan Did you test this before creating the PR? It's failing:

```
In file included from intl/msg_hash_nl.c:48:0:
intl/msg_hash_nl.h: In function ‘msg_hash_to_str_nl’:
intl/msg_hash_nl.h:2964:52: warning: missing terminating " character [enabled by default]
 "Toon/verberg de 'Neem Schermafdruk' optie.")")
 ^
intl/msg_hash_nl.h:2963:1: error: missing terminating " character
 MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_TAKE_SCREENSHOT,
 ^
make: *** [obj-unix/intl/msg_hash_nl.o] Error 1
```

**Comment by hyarsan** [comment]
Oh my bad, I think I know how to fix it.

**Comment by hyarsan** [comment]
Okay... I have no idea why it is failing :/
another time.

**Comment by bparker06** [comment]
@hyarsan It's telling you exactly which line the problem is on:

`2964: +      "Toon/verberg de 'Neem Schermafdruk' optie.")")`

You have an extra set of `")` at the end that needs to be removed. Please test your changes locally and try to keep from adding more commits until you're sure it works.

**Comment by hyarsan** [comment]
I thought that I just removed the ' ")' ? Anyways, now it is working :)

**Comment by bparker06** [comment]
No worries, thanks for fixing it up.

**Comment by hyarsan** [comment]
Wait... I just updated RetroArch to the latest nightly and my changes aren't there? 0_0 wut?

**Pull request merged**
