### PR TITLE
Create Korean, Japanese, and Chinese fonts for rgui

### PR DESCRIPTION
**Pull request by trngaje**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

created Korean, Japanese, and Chinese fonts for rgui drivers.The font size is 10 pixels * 10 pixels.
tested in rpi3,4 and oga.Corrected static analysis errors as well.

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Thanks again for working on this! Our RGUI expert is planning to take a deeper look at it soon, but I wanted to let you know that we're not ignoring it :)

**Comment by trngaje** [comment]
@hizzlekizzle Thank you for your interest in my work. If Travis Ci didn't have an error, I would have applied more. I'll just wait until it's resolved now.

**Comment by jdgleaver** [comment]
@trngaje Thank you very much for the contribution. CKJ fonts are certainly a desirable addition.

Unfortunately, there are two issues that prevent us from merging the PR in its current form:

- The new CKJ bitmaps are included in source code, and are thus baked into the generated binary. This increases the size of the RetroArch executable by over *half a megabyte*. We simply cannot accept this.

- Your changes have a substantial performance impact for all users, regardless of whether they need CKJ fonts. This is harmful on low-end hardware, and potentially catastrophic on cache-limited platforms.

In order to move forward with this, we basically need the following modifications:

- The CKJ bitmaps must be loaded from one or more external files, which can be included in https://github.com/libretro/retroarch-assets. The format can be anything you like - the important thing is just to move them outside of the RetroArch binary.

- All of your changes must be behind a new `ifdef` (I'd suggest `HAVE_CKJ_BITMAP_FONTS`). This allows us to easily disable the functionality on platforms that are incapable of supporting it (e.g. PSP, PS2, 3DS, OpenDingux, etc.)

- On platforms where `HAVE_CKJ_BITMAP_FONTS` is set:

   - The CKJ fonts should only be loaded/made available if `*msg_hash_get_uint(MSG_HASH_USER_LANGUAGE)` is equal to `RETRO_LANGUAGE_JAPANESE`, `RETRO_LANGUAGE_KOREAN`, `RETRO_LANGUAGE_CHINESE_TRADITIONAL` or `RETRO_LANGUAGE_CHINESE_SIMPLIFIED`

   - The CKJ fonts should only be used in RGUI if `settings->bools.menu_rgui_extended_ascii` is `true`

If you can do this, then we can review the code in more detail and work towards getting it integrated.

I do apologise if this seems critical, and I realise that the above requests represent a great deal of labour. But please be assured that we really appreciate your efforts. We are keen to get this implemented in a manner that is compatible with all the hardware platforms that we support :)

**Comment by trngaje** [comment]
@jdgleaver 
I was already expecting that it would not be easy to apply my code to retroarch.
I created some font data for retroarch-assets.
rgui_font_kor10x10.bin
rgui_font_jpn10x10.bin
rgui_font_chn10x10.bin
Is it easy to post my generated files on retroarch-assets without any interference?
It's already been implemented when settings->bools.menu_rgui_extended_ascii is true.
"HAVE_CKJ_BITMAP_FONTS" has never been defined. Can I use this name for my code?
How do I add a new commit from an already registered PR? I just know how to close the old PR and create a new one.
The work itself is not difficult. However, I don't want my code to interfere with the existing stable retroarch.
This is the last question. If the font data for rgui does not exist on retroarch-assets, can I insert a code that forces the language to be changed to English early in the retroarch?

**Comment by jdgleaver** [comment]
> I created some font data for retroarch-assets.
> rgui_font_kor10x10.bin
> rgui_font_jpn10x10.bin
> rgui_font_chn10x10.bin
> PR:libretro/retroarch-assets#389
> Is it easy to post my generated files on retroarch-assets without any interference?

Yes, this is absolutely fine - we can add binary files to `retroarch-assets` without any problems.

> It's already been implemented when settings->bools.menu_rgui_extended_ascii is true.

The issue with `rgui.c` is that your changes also apply when `settings->bools.menu_rgui_extended_ascii` is false. You added this new implementation to the `blit_line_regular()` functions - it should have gone in the `blit_line_extended()` functions instead.

> "HAVE_CKJ_BITMAP_FONTS" has never been defined. Can I use this name for my code?

Yes, absolutely. Use `#if defined(HAVE_CKJ_BITMAP_FONTS)` in the code, then you will also need to reference the new flag in these two files:

 - `qb/config.params.sh`:

```
HAVE_CKJ_BITMAP_FONTS=yes           # CKJ bitmap font support
```
-  `Makefile.common`

```
ifeq ($(HAVE_CKJ_BITMAP_FONTS), 1)
   DEFINES      += -DHAVE_CKJ_BITMAP_FONTS
endif
```

> How do I add a new commit from an already registered PR? I just know how to close the old PR and create a new one.

Yes, the way you are using git has created quite a mess...

In general, it is always best to make your changes in a feature branch. I always recommend that people follow this guide when making contributions: https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/

The benefits of this are:

1) It is trivial to rebase against current master - i.e.:

```
git checkout master
git pull upstream master
git checkout my_branch
git rebase master
```

...this is much cleaner than having to make `Merge remote-tracking branch 'upstream/master'` commits...

2) It is trivial to squash your commits into one (which is what we require before merging) - i.e. if you made 5 commits in your feature branch, you'd just do:

```
git rebase -i HEAD~5
```

...then follow the instructions here: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

If you work in `master`, then squashing commits can be bothersome (since you can end up with upstream commits in-between yours)

What I think you would be best off doing here is the following:

- Close this PR

- Back up your local repo (in case something goes wrong!)

- Undo all the commits you have made, while keeping the actual file edits - I believe this should do the trick:

```
git reset HEAD~12
```

- Create a new feature branch:

```
git checkout -b ckj-bitmap-fonts
```

- Add and commit your changes:

```
git add .
git commit
```

- Create a new PR, and mark it as `[WIP]` in the title

```
git push origin ckj-bitmap-fonts
```

- Thereafter, you can continue making commits in your feature branch, and the PR can be updated simply by repeating the `git push origin ckj-bitmap-fonts` command

- When everything is complete, you can rebase and squash the commits in your feature branch, and do a final `git push --force origin ckj-bitmap-fonts` to clean up the PR

> This is the last question. If the font data for rgui does not exist on retroarch-assets, can I insert a code that forces the language to be changed to English early in the retroarch?

Hmm... This is somewhat tricky...

There are probably two things you can do here:

- At this point in `configuration.c`: https://github.com/libretro/RetroArch/blob/865303c5019240756a8520660b692551600cda9b/configuration.c#L3394-L3395, you can check if the current language + menu driver combo requires CKJ fonts, and if the files are missing you can override the language setting

- Here at the end of the `general_write_handler()` in `menu_settings.c`: https://github.com/libretro/RetroArch/blob/865303c5019240756a8520660b692551600cda9b/menu/menu_setting.c#L7480, you can add a new case statement for `MENU_ENUM_LABEL_USER_LANGUAGE` where you perform the same language/menu driver/file exists check as in `configuration.c`

**Pull request closed without merging**
