### PR TITLE
Autoconfig extension with alternative name/vid/pid

### LINKED ISSUE #16907: [IMPORTANT feature request]: Support multiple input_device, input_device_display_name, input_vendor_id, and input_product_id variables
PR accepted. Kindly refrain from closing this issue until I have completed merging the autoconfigs as outlined below.

# input_device (linuxraw)
To avoid the need for uploading and maintaining multiple copies of files for `linuxraw`, which uses `input_device` to identify the controller, I propose the following:

- Implement `input_device_2` and `input_device_display_name_2`
- Implement `input_device_3` and `input_device_display_name_3`

After implementation, this can be incorporated into the `android` and `udev` autoconfiguration files as well, to significantly enhance their ability to utilize input_device as fallback when the vendor or product ID is unavailable. This feature is unnecessary for `sdl2` autoconfig files because they use the same input_device value for both USB and Bluetooth across all Linux kernel versions.

Placed USB lines before Bluetooth lines in the examples below, as the input_device USB name more clearly identifies the hardware device.

## Nintendo Switch Pro Controller
* Device Index for Linux 5.19, and 6.2.0:
  - USB: Nintendo Switch Pro Controller
  - Bluetooth: Nintendo Switch Pro Controller
* Device Index for Linux 6.8.0:
  - USB: Nintendo Co., Ltd. Pro Controller
  - Bluetooth: Pro Controller

### Current
Nintendo Switch Pro Controller.cfg
```
input_driver = "linuxraw"
input_device = "Nintendo Switch Pro Controller"
input_device_display_name = "Nintendo Switch Pro Controller (Bluetooth/USB)"
```

Nintendo Co., Ltd. Pro Controller.cfg
```
input_driver = "linuxraw"
input_device = "Nintendo Co., Ltd. Pro Controller"
input_device_display_name = "Nintendo Switch Pro Controller (USB)"
```

Pro Controller.cfg
```
input_driver = "linuxraw"
input_device = "Pro Controller"
input_device_display_name = "Nintendo Switch Pro Controller (Bluetooth)"
```

### Proposed merge
Nintendo Switch Pro Controller.cfg
```
input_driver = "linuxraw"
input_device = "Nintendo Switch Pro Controller"
input_device_display_name = "Nintendo Switch Pro Controller (Bluetooth/USB)"
input_device_2 = "Nintendo Co., Ltd. Pro Controller"
input_device_display_name_2 = "Nintendo Switch Pro Controller (USB)"
input_device_3 = "Pro Controller"
input_device_display_name_3 = "Nintendo Switch Pro Controller (Bluetooth)"
```

## Nintendo Switch Pro Controller (non-HID)
* Device Index for Linux 5.15:
  - USB[1]: Nintendo Switch Pro Controller
  - Bluetooth: Pro Controller

Notes:
* 1: Only Bluetooth is avalible for the non-HID version. So there is no need to merge anything.

## Sony DualSense
* Device Index for all Linux versions:
  - USB: Sony Interactive Entertainment DualSense Wireless Controller
  - Bluetooth: DualSense Wireless Controller

### Current
Sony Interactive Entertainment DualSense Wireless Controller.cfg
```
input_driver = "linuxraw"
input_device = "Sony Interactive Entertainment DualSense Wireless Controller"
input_device_display_name = "Sony DualSense (USB)"
```

DualSense Wireless Controller.cfg
```
input_driver = "linuxraw"
input_device = "DualSense Wireless Controller"
input_device_display_name = "Sony DualSense (BlueTooth)"
```

### Proposed merge
Sony Interactive Entertainment DualSense Wireless Controller.cfg
```
input_driver = "linuxraw"
input_device = "Sony Interactive Entertainment DualSense Wireless Controller"
input_device_display_name = "Sony DualSense (USB)"
input_device_2 = "DualSense Wireless Controller"
input_device_display_name_2 = "Sony DualSense (BlueTooth)"
```

## Sony DualShock 4 v2
* Device Index for all Linux versions:
  - USB: Sony Interactive Entertainment Wireless Controller
  - Bluetooth: Wireless Controller

### Current
Sony Interactive Entertainment Wireless Controller.cfg
```
input_driver = "linuxraw"
input_device = "Sony Interactive Entertainment Wireless Controller"
input_device_display_name = "Sony DualShock 4 v2 Controller (USB)"
```

Wireless Controller.cfg
```
input_driver = "linuxraw"
input_device = "Wireless Controller"
input_device_display_name = "Sony DualShock 4 v2 Controller (BlueTooth)"
```

### Proposed merge
Sony Interactive Entertainment Wireless Controller.cfg
```
input_driver = "linuxraw"
input_device = "Sony Interactive Entertainment Wireless Controller"
input_device_display_name = "Sony DualShock 4 v2 Controller (USB)"
input_device_2 = "Wireless Controller"
input_device_display_name_2 = "Sony DualShock 4 v2 Controller (BlueTooth)"
```

# input_vendor_id, and input_product_id (android, udev, sdl2)
- Implement `input_vendor_id_2` and `input_vendor_product_2` so we can:
  - Merge DualShock 4 versions 1 and 2 — this task has been on my agenda.
  - Merge Microsoft X-Box pad versions 1 (US) and 2 (US) — thank you for highlighting this.

### android
Merge `Sony Computer Entertainment Wireless Controller.cfg` (v1) and `Wireless Controller.cfg` (v2)

#### Current
DualShock 4 v1: `Sony Computer Entertainment Wireless Controller.cfg`
```
input_driver = "android"
input_device = "Sony Computer Entertainment Wireless Controller"
input_device_display_name = "Sony DualShock 4 Controller v1"
input_vendor_id = "1356"
input_product_id = "1476"
```

DualShock 4 v2: `Wireless Controller.cfg`
```
input_driver = "android"
input_device = "Wireless Controller"
input_device_display_name = "Sony DualShock 4 v2 Controller"
input_vendor_id = "1356"
input_product_id = "2508"
```

#### Proposed merge
DualShock 4.cfg
```
input_driver = "android"
input_device = "Wireless Controller"
input_device_display_name = "Sony DualShock 4 v2 Controller"
input_vendor_id = "1356"
input_product_id = "2508"
input_device_2 = "Sony Computer Entertainment Wireless Controller"
input_device_display_name_2 = "Sony DualShock 4 Controller v1"
input_vendor_id_2 = "1356"
input_product_id_2 = "1476"
```

### sdl2
Merge `PS4 Controller (v1).cfg` (v1) and `PS4 Controller.cfg` (v2)

#### Current
DualShock 4 v1: `PS4 Controller (v1).cfg`
```
input_driver = "sdl2"
input_device = "PS4 Controller"
input_device_display_name = "PlayStation 4 (PS4) Sony DualShock 4 v1 Controller"
input_vendor_id = "1356"
input_product_id = "1476"
```

DualShock 4 v2: `PS4 Controller.cfg`
```
input_driver = "sdl2"
input_device = "PS4 Controller"
input_device_display_name = "PlayStation 4 (PS4) Sony DualShock 4 v2 Controller"
input_vendor_id = "1356"
input_product_id = "2508"
```

#### Proposed merge
PS4 Controller.cfg
```
input_driver = "sdl2"
input_device = "PS4 Controller"
input_device_display_name = "PlayStation 4 (PS4) Sony DualShock 4 v2 Controller"
input_vendor_id = "1356"
input_product_id = "2508"
input_device_2 = "PS4 Controller"
input_device_display_name_2 = "PlayStation 4 (PS4) Sony DualShock 4 v1 Controller"
input_vendor_id_2 = "1356"
input_product_id_2 = "1476"
```

### udev
Merge `Sony Computer Entertainment Wireless Controller.cfg` (v1) and `Sony Interactive Entertainment Wireless Controller.cfg` (v2)

#### Current
DualShock 4 v1: `Sony Computer Entertainment Wireless Controller.cfg`
```
input_driver = "udev"
input_device = "Sony Computer Entertainment Wireless Controller"
input_vendor_id = "1356"
input_product_id = "1476"
```

DualShock 4 v2: `Sony Interactive Entertainment Wireless Controller.cfg`
```
input_device = "Sony Interactive Entertainment Wireless Controller"
input_device_display_name = "Sony DualShock 4 v2 Controller"
input_driver = "udev"
input_vendor_id = "1356"
input_product_id = "2508"
```

#### Proposed merge
Sony Computer and Interactive Entertainment Wireless Controller.cfg
```
input_device = "Sony Interactive Entertainment Wireless Controller"
input_device_display_name = "Sony DualShock 4 v2 Controller"
input_driver = "udev"
input_vendor_id = "1356"
input_product_id = "2508"
input_device_2 = "Sony Computer Entertainment Wireless Controller"
input_device_display_name_2 = "Sony DualShock 4 v1 Controller"
input_vendor_id_2 = "1356"
input_product_id_2 = "1476"
```

### PR DESCRIPTION
**Pull request by zoltanvb**
## Description
There may be several variants of a controller, where name and/or vid:pid is different, but their button layout is exactly the same (for one example, `Microsoft X-Box pad v1 (US)` and `Microsoft X-Box pad v2 (US)` in udev). 

Allow up to 9 alternative values in the autoconfig file for the 3 config entries used for identification, e.g.: 
```
input_device_alt1
input_vendor_id_alt1
input_product_id_alt1
```
The matching against the alternative identifiers is done exactly the same way as for primary identifiers (affinity calculation).

Note: contrary to the linked request, there is only one display name supported. The reason is that this way, code changes are quite limited and do not spread to any other function. Since this PR just enables reducing number of autoconfig files, I wanted to keep changes and future code maintenance increase to a minimum.

Omitting the display name will keep the name contained in input_device (whichever alternative matched). Change is not driver specific and is valid for any controller driver. Existing driver limitations still apply (i.e. linuxraw driver can not extract vid:pid).

Autoconfig file generation does not change. Any merge of matching autoconfigs must be done manually. Existing autoconfigs are good as-is.

Test supplied using test input driver:
`retroarch --appendconfig tests-other/testinput_alternative_autoconfig.cfg\|tests-other/all_binds_empty.cfg`

## Related Issues

Closes #16907 

## Reviewers

@davidhedlund 
@RobLoach (in case verify_duplicate_profiles CI script would be incompatible with this)

### CODE REVIEW

**Comment by davidhedlund** [comment]
Thank you very much, as always, Zoltanvb. You have been instrumental in helping me achieve my goals!

There's just one last detail to address. Please ensure that you can accommodate up to eight input_device_display_name variables (the issue title is "Support multiple input_device and input_device_display_name variables). This will allow for specifying whether the controller is connected via USB or Bluetooth, as outlined in the issue. Besides ensuring technically correct output, this also makes all players aware of the connectivity used for each controller, enabling them to communicate effectively if issues arise when the controllers do not function properly.

**Comment by davidhedlund** [comment]
* I documented how to use the new variables in: https://github.com/libretro/docs/pull/985
* I've merged all files in the PRs by utilizing the new variables.

**Comment by landfillbaby** [comment]
just to clarify, if for example a .cfg provides
```
input_device
input_vendor_id
input_product_id

input_vendor_id_alt1
input_product_id_alt1
```
but not `input_device_alt1` and a device matching `input_vendor_id_alt1` and `input_product_id_alt1`, does it use `input_device` for matching or no?

in other words, do i ned to provide `input_device_alt1` when it would be the same as `input_device`"

**Comment by zoltanvb** [comment]
Yes, input_device_alt1 is needed. Each set of (input_device, input_vendor_id, input_product_id) is treated as a separate entity.

**Pull request merged**
