### PR TITLE
add input option to allow any user to control the menu

### PR DESCRIPTION
**Pull request by bparker06**
fixes issue #3337, default setting is off to preserve current behavior

### CODE REVIEW

**Comment by meleu** [comment]
@bparker06 
Is there a chance to make `all_users_control_menu` defaults to `true` on Android devices? It would solve the #3014 issue as well.

**Comment by bparker06** [comment]
I'm not sure most people would agree to make it default, but currently it is indeed available in Settings -> Input to enable if you need it.

**Comment by meleu** [comment]
@bparker06 OK. Then there's no need to make it default. I think that when this feature reach the Google Play's version of RetroArch (1.3.7, I think) the #3014 issue can be closed.
Thanks for your work! :+1:

**Comment by meleu** [comment]
I've just realized that this PR doesn't fix #3337 .

The `all_users_control_menu` (from #3499 PR) doesn't make "**all plugged controllers** control the menu", as the title of the issue says. Actually it just makes "**all controllers bound to a player** control the menu".

If I have a plugged controller not bound to any player, this controller can't control the menu.

Maybe the current behavior of what is implemented in this PR could bring less confusion and be better named as `all_players_control_menu`.

**Comment by dankcushions** [comment]
this doesn't appear to be working on latest master.

**Pull request merged**
