### PR TITLE
[record] streaming & recording refinements

### PR DESCRIPTION
**Pull request by fr500**
You can now pick youtube or twitch from the menu (assuming you have entered the streaming key) for either

There are a couple todos, and entering those keys by hand is painful but @bparker06 said oauth is a no-go without a browser.

There seems to be an oauth2 for devices authorization path both on youtube and twitch but that falls outside my skillset.

Given oauth, getting the key from twitch at least is easy:
https://www.twitch.tv/radius__/dashboard/settings/streamkey
https://www.slickremix.com/docs/get-api-key-for-youtube/

Anyway this is not an OBS replacement of course (although given a cam driver and GPU accelerated encoding and the overlay system it could be).

It's meant to enable usage of this feature from the RA interface.

Please try to fill the to-do's, I don't really know how, particularly the stream key to-do's, and I won't be available for a few days

The whole feature needs a few things:
- OSD messages on recording failed to start / recording saved / streaming started
- GPU encoding (needs custom ffmpeg builds)
- Built-in preset refinement

### CODE REVIEW

**Comment by fr500** [comment]
@twinaphex the custom streaming quality entry still starts at the wrong place

**Comment by fr500** [comment]
@twinaphex I guess we also need a setting for this:
https://github.com/libretro/RetroArch/blob/e170c3db297e6e1c58eac97dec4a7359f9388c18/record/drivers/record_ffmpeg.c#L806

It's the metadata embeded in the recording/stream

**Comment by fr500** [comment]
Also it doesn't seem the hotkeys are hooked up?

**Comment by fr500** [comment]
@twinaphex 
not sure how to hook these up:

https://github.com/libretro/RetroArch/pull/7302/files#diff-af5795e6898c0dc19d991bd2a8fe4021R2989
https://github.com/libretro/RetroArch/pull/7302/files#diff-af5795e6898c0dc19d991bd2a8fe4021R2975

**Comment by fr500** [comment]
Also, please do some testing, on linux particularly, with ASAN if at all possible.
I have no crashes on windows (so far) but who knows...

**Comment by RobLoach** [comment]
Was having troubles getting streaming to work, and discovered it needed `ffmpeg` >= 4 ... After updating to ffmpeg version 4.0.2-1, things worked smoothly.

**Comment by twinaphex** [comment]
OK, let me merge this first, then I will start correcting what needs correcting.

**Comment by twinaphex** [comment]
OK, I implemented a Stream of Title setting.

**Comment by twinaphex** [comment]
> Also it doesn't seem the hotkeys are hooked up?

Yes, I left these open-ended for you to implement.

See this -

https://github.com/libretro/RetroArch/blob/master/retroarch.c#L2926

**Comment by twinaphex** [comment]
> @twinaphex
> not sure how to hook these up:

> https://github.com/libretro/RetroArch/pull/7302/files#diff-af5795e6898c0dc19d991bd2a8fe4021R2989
> https://github.com/libretro/RetroArch/pull/7302/files#diff-af5795e6898c0dc19d991bd2a8fe4021R2975

What do you mean here? I cannot make out what it is you want me to do based on those links.

**Comment by twinaphex** [comment]
> @twinaphex the custom streaming quality entry still starts at the wrong place

How should it be instead then? Tell me exactly what the enum values should be and what it should start at, and I can get it done.

**Pull request merged**
