### PR TITLE
msg_hash_us.h: Clean up and organize US translation

### PR DESCRIPTION
**Pull request by im-4-potato**
## Description

The entire `msg_hash_us.h` file has been organized to make it much easier to read and understand what each entry does. None of these changes are visible to the user, no strings have been changed (I'll be working on that next), this cleanup is to make future work easier.

### Cleanup:
- Grouped related items together
- Created sections corresponding to the relevant parts of the UI
- Organized menu items so they appear in the same order as the UI
- Cleaned up and grouped defines
- Changed indents to follow the RetroArch coding standard (3 spaces)
- Fixed minor formatting issues

### Remaining Issues:
- I was unable to figure out what settings a few strings were related to, but they appear to be used in some way. Those are now in the `/* Unsorted */` section, which I would like to get sorted before this is merged.
- I discovered quite a few strings that only exist within the translation files, they are never referenced by the UI, instead of removing them I put them in the `/* Unused (Only Exist in Translation Files) */` section. Assuming these are unused, they should be removed before this gets merged.
- Similar to the previous point, there are some strings that appear to only exist within the translation files and `msg_hash.h`, but nowhere else. I've put these in the `/* Unused (Needs Confirmation) */` section.
- There are a number of entries that use the wrong naming designation or they refer to a specific menu driver even though they are used globally, I have marked these issues with `FIXME`.
- Is the `ifdef` and `defined` usage necessary? There are many other entries that fit in those areas but they are not.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I like this. Having comments tell you where to find the strings in the menu is very helpful.

My only concern is with the preprocessor stuff at the beginning. Some compilers we deal with can't handle any tabs/spaces in front of the #. However, if it would be a hassle to fix that right now, a follow-up PR that fixes that would also be acceptable.

**Comment by im-4-potato** [comment]
@hizzlekizzle I just pushed a commit that removes those indents.
Any input on the remaining issues I mentioned above? It might be nice to take care of removing the stuff in `/* Unused (Only Exist in Translation Files) */` now, the other issues are going to require a little more work that I can take care of in a future PR.

**Comment by hizzlekizzle** [comment]
Hmm, I think a lot of those were kept in after their antecedent option was removed in case the option were to return. I would say we can probably lose them, but I don't know enough about how the translation thing works to give the go-ahead on removing them.

I think we can safely merge this as-is without removing the questionable items and then cull them later, since they're helpfully sorted now.

**Comment by im-4-potato** [comment]
Sounds good to me.

**Comment by tpfaff** [comment]
Nice

**Pull request merged**
