### PR TITLE
xfree86_keycodes: Add non-evdev keycodes to fix keyboard input on non-Linux systems with X11.

### LINKED ISSUE #8807: input/include/xfree86_keycodes.h assumes evdev is used
As discussed in #8591, this has broken keyboard input on OSes that don't use evdev (most non-Linux unixes with X11...)

The offending commit is 347519a4d8f3befb719f11eeb0121c736ce64dee

### PR DESCRIPTION
**Pull request by niacat**
I don't know if this makes the most sense as a workaround, considering I had difficulty figuring out the assumptions the driver makes, but it seems to work...

Closes #8807

### CODE REVIEW

**Comment by jdgleaver** [comment]
With this change, keyboard input is broken by default on Linux. You have to explicitly run:

```
./configure --enable-udev
```

before building. Is this intended behaviour?

**Comment by niacat** [comment]
@jdgleaver There doesn't seem to be defined auto-detection bits for udev in RetroArch. I assumed there was because HAVE_UDEV is set to "auto" in qb.

It might make sense to add auto-detection for udev. I don't think there are any Linux distributions that don't use it in some form?

**Comment by jdgleaver** [comment]
@niacat Actually, I just realised that a normal `./configure` is sufficient provided you have `libudev-devel` installed (i.e. it gets auto detected properly). I didn't have this installed initially when I first discovered that keyboard input was 'broken'.

So I guess maybe this is okay after all...? (although it does add an extra dependency that wasn't required before)

**Comment by twinaphex** [comment]
Well, that extra dependency shouldn't be there. We should not make working on Linux even more inconvenient.

**Comment by twinaphex** [comment]
I'll revert it for now then.

@niacat You can send me another version of this PR that won't negatively adversely affect Linux in any way.

**Pull request merged**
