### PR TITLE
(Menu) Add Menu Scroll Acceleration option

### PR DESCRIPTION
**Pull request by parport0**
Fixes: #9980

### CODE REVIEW

**Comment by natinusala** [comment]
Thanks for the PR!

I would actually like to have this enabled by default, I don't know what others think

Also should the menu entry not be reworded? `PSP-style fast scroll` is not very self explanatory, (not looking at the sublabel).

Or... wouldn't it make sense to reverse it all? Have the default be what you made, and have an option to go back to the old "too fast" setting? Just throwing ideas

**Comment by jdgleaver** [comment]
Yes, very nice - this should indeed probably be the default setting  :)

I agree, though, that `PSP-style fast scroll` is unclear. Perhaps this could be changed to `Menu Scroll Acceleration`? With options `Fast` and `Slow` - or maybe `Normal` and `Fast`, corresponding to the new and old methods respectively.

**Comment by twinaphex** [comment]
I'm fine with merging this.

I will say this though - if you have a list of over a thousand items, the 'Fast' scroll acceleration is really useful. Not sure if in the future this can be improved to provide faster scroll acceleration based on the overall length of a menu list.

**Comment by natinusala** [comment]
The current speed is too fast IMO

I always use left/right to go through large lists personnally

**Comment by twinaphex** [comment]
Alright, we'll merge this. If people want it faster they can go for the fast acceleration.

**Comment by natinusala** [comment]
Did we not want this by default?

**Comment by jayare5** [comment]
Just wanted to say to everyone, I am really happy with this change!!!! Thank you very much
This even fixed other obscure issues I was going to post about, but it won't be needed anymore.
I will be posting other issues I had planned :)

**Pull request merged**
