### PR TITLE
Add option to save core options per-core

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

At present, RetroArch saves all core options to one monolithic file (`retroarch-core-options.cfg`). This has two disadvantages:

1) Every time content is loaded, we have to read. parse and store in memory the options for every core that has ever been run. This is wasteful of RAM and CPU cycles. Moreover, it causes unnecessary wear on solid state storage, since *all* options are written back to disk when content is closed. Arcade cores greatly exacerbate the issue, since they typically create unique options for each game - the result being that `retroarch-core-options.cfg` can balloon to many 100's of kb in size, all of which data has to be loaded and rewritten (uselessly) when running any other core.

2) If a user tries a core and then decides to delete it/use another instead. the settings for that core hang around forever in `retroarch-core-options.cfg`, serving no purpose. The only way to remove them is to edit `retroarch-core-options.cfg` by hand (which is quite awkward/error prone!)

This PR adds a new `Use Global Core Options File` option under `Settings > Configuration`. When this is enabled (the default), RetroArch behaves as normal (writing everything to `retroarch-core-options.cfg`). When it is disabled, core options are instead saved to a core-specific file in the config directory - i.e. `/config_path/core_name/core_name.opt`. This means (a) we only have to load/save options for the current core and (b) removing unwanted options is as simple as just deleting a file.

On first run of a core after disabling `Use Global Core Options File`, existing settings will be read from `retroarch-core-options.cfg`. Thereafter, the core-specific file is used. (This is annoying on the code side, but it's pretty much required from a usability perspective!)

### CODE REVIEW

**Comment by hhromic** [comment]
@jdgleaver this is such a nice improvement!  Thanks for the great work!

I'm wondering about something. You mention that options can be now stored in `/config_path/core_name/core_name.opt` if the new option is enabled.

Is `.opt` the actual file extension being used? Wouldn't have been better to keep `.cfg` for consistency with all other config/option-type files in RetroArch, including the "old" global core options file?

**Comment by Tatsuya79** [comment]
Options overrides are .opt file already, so that makes sense and differentiates them from core config overrides.

**Comment by hhromic** [comment]
Ah I see, yes that makes sense. So in a fully customised core it would look like this?

    config/
        snes9x/
            game1.opt
            game2.opt
            snes9x.opt
        mupen64/
            game1.opt
            game2.opt
            mupen64.opt

Sorry for the "dumb" question but I don't use core overrides :)

**Comment by jdgleaver** [comment]
@hhromic Yes, your example is correct  :)

As @Tatsuya79 said, we already use `.opt` for option overrides - we couldn't use `.cfg` here because it would have conflicted with configuration overrides. I guess the global options file should have been `retroarch-core-options.opt` - but it's a bit late to change it now... (i.e. users would have to manually rename their existing file - there would be so many complaints!)

**Comment by hhromic** [comment]
@jdgleaver yes that makes perfect sense.
Renaming the global options file def is not desirable at this point :)

So, this new approach works as long as there is no content/core name clashes right?  What happens if a user loads a content named `snes9x.sfc` using the `snes9x` core and creates a core-override config?  All content for that core will use the override for the `snes9x.sfc` content in that case?

I guess this is a very unlikely/rare case anyway, just wondering if this situation was considered.

**Comment by jdgleaver** [comment]
Heh - yes that is a peculiar edge case!

What will actually happen is that there won't be an options override for `snes9x.sfc` at all - It'll use the 'master' core options file instead (so any changes will be saved to the 'master' file). So it's kinda as you say (only the other way around).

There's not really any way to handle engineered conflicts like this - but nothing will outright 'break' if the user tries these kinds of shenanigans.

**Comment by hhromic** [comment]
Thanks for the clarification.
I agree that the odds of any content having the same name as its core are pretty low, so should be safe enough I guess :)

**Pull request merged**
