### PR TITLE
Refactoring conditional directives for alternative if statements and incomplete if conditions.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by twinaphex** [comment]
Variables have to be declared at the top of a function otherwise we break C89 backwards compatibility.

**Comment by wmarquesr** [comment]
All fixed. What do you think about refactoring?

**Comment by twinaphex** [comment]
Looks better but there are still some code foibles. Uninitialized variables should come first, then initialized ones. 

Anyway, I'll likely do a selective backport of these commits if that's OK with you so that I'll save you some of the further suggestions.

**Comment by wmarquesr** [comment]
Right. I'll be waiting.

**Comment by twinaphex** [comment]
OK, I backported all of your changes except for the zlib changes (since that is external code and not really ours anyway). I gave you credit too in the commit. 

Let me know if we can close this.

**Comment by wmarquesr** [comment]
I'm sorry, i did note realize in zlib. But i don't understand the pull request will be accepted or not.
If yes, of course, you can close this.

**Comment by twinaphex** [comment]
I manually made commits for all of the patches you made here.

So yes I think we can close it. Thanks for the refactorings, I did some modifications here and there too and I gave you credit as well.

**Pull request closed without merging**
