### PR TITLE
(Manual content scanner/playlist cleaner) Prevent redundant playlist entries when handling M3U content

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

At present, when the manual content scanner is used to scan content that includes M3U files, redundant playlist entries are created. For example, content like this:

```
Panzer Dragoon Saga CD1 (Saturn) (U).cue
Panzer Dragoon Saga CD2 (Saturn) (U).cue
Panzer Dragoon Saga CD3 (Saturn) (U).cue
Panzer Dragoon Saga CD4 (Saturn) (U).cue
Panzer Dragoon Saga (Saturn) (U).m3u
```

(where the `.m3u` references all the `.cue` files) will generate playlist entries for both the `.m3u` file *and* each of the `.cue` files. This is annoying, since the latter are pointless, and must be removed manually by the user.

This PR adds M3U 'awareness' to the manual content scanner. Now whenever M3U files are encountered, they are parsed, and anything they reference internally is removed/omitted from the output playlist.

This functionality has also been added to the `Playlist Management` `Clean Playlist` task, so these redundant entries can be removed easily from existing playlists.

(Side note: this PR adds a simple but feature complete M3U handling library - this may have additional use if someone wants to add the ability to *generate* M3U files for existing content...)

### CODE REVIEW

**Comment by jdgleaver** [comment]
Crud - just noticed some tab indents in `m3u_file.c`. Pushed a second commit to fix this...

**Comment by hizzlekizzle** [comment]
oh wow, this is a great feature, jdgleaver.

Auto-generating m3us would indeed be great, too.

**Comment by jdgleaver** [comment]
Thanks!

I probably will look at m3u creation at some point, when I've shifted some more stuff off the TODO list. It's a bit tricky implementing something that will work reliably in all cases - but I have some ideas...

**Comment by i30817** [comment]
> Thanks!
> 
> I probably will look at m3u creation at some point, when I've shifted some more stuff off the TODO list. It's a bit tricky implementing something that will work reliably in all cases - but I have some ideas...

https://gist.github.com/i30817/7dccadc56bfa63f344032c957d8d6cf9

**Comment by i30817** [comment]
And in fact this is the reason i maintain that m3u aren't even necessary except as a runtime abstraction, though i understand why that would be weird to Retroarch.

**Pull request merged**
