### PR TITLE
(Android) Target the newest android 

### PR DESCRIPTION
**Pull request by Aaahh**

### CODE REVIEW

**Comment by twinaphex** [comment]
Do we need this bump necessarily?

**Comment by Aaahh** [comment]
Nah, but the numbers should match, and atleast be 23

**Comment by fr500** [comment]
I reckon this would need a toolchain update on the buildbot

**Comment by Aaahh** [comment]
It would

**Comment by twinaphex** [comment]
That's rather bad. Is this still really necessary @Aaahh ?

**Comment by Aaahh** [comment]
Ill test tonights nightly and we'll find out

**Pull request closed without merging**
