### PR TITLE
Attempt to fix some localisation issues

### PR DESCRIPTION
**Pull request by IlDucci**
## Description

 - Merging the virtual disk tray pieces into full strings.
 - Adding new strings for the Mixer Stream.
 - Removing some apparently unused strings from the cheat system? Please verify.

I'm not too well versed into coding, so these changes should be checked thorougly.

## Related Issues

Related to https://github.com/libretro/RetroArch/issues/10990. This PR doesn't cover all the points mentioned there.

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by twinaphex** [comment]
OK, the Travis jobs fail. Can you fix this?

https://travis-ci.org/github/libretro/RetroArch/builds/712719710

**Comment by twinaphex** [comment]
What you're doing in that last commit isn't going to work. That's not how snprintf or strlcpy work.

Anyway, I'll just make my own commit based on the ideas here that you wanted to convey.

**Comment by IlDucci** [comment]
I'm sorry I can't do too much else. I'm not a programmer and just wanted to speed up the localisation, specially the last strings I'm trying to find out within the emulator in order to wrap the Spanish translation as fully verified.

**Comment by IlDucci** [comment]
Closing PR as the concatenation part, the one that was giving me trouble, has been done in #12120 . The other two problems are still an issue, but the audio is still mentioned in the currently open issue https://github.com/libretro/RetroArch/issues/10990 and the cheat codes can be solved another day.

**Pull request closed without merging**
