### PR TITLE
Added a hotkey delay option to fix issue #9080

### PR DESCRIPTION
**Pull request by snackycakes**
Fixes #9080.

Added a hotkey delay option to allow hotkey input to work properly when it is assigned to another action.  Original pull request from issue #9080 by paradadf was taken and modified to be configuration based.

Delay can be controlled by setting input_hotkey_block_delay = <frame delay> in configuration options.  Setting value to 0 (default) will effectively disable the functionality.

### CODE REVIEW

**Comment by dankcushions** [comment]
i like it! i would prefer the default to be a value that solves the logged problem, as i would think it would be low enough to be invisible to usual function

**Comment by snackycakes** [comment]
Sure, I can change the default to 5 which is what it was in the original fix and is used in other distros.

**Comment by twinaphex** [comment]
@snackycakes OK, so explain to me exactly step by step how this is supposed to work.

This includes:
- setting a value in retroarch.cfg
- Binding a button in the user interface
- Then trying it out ingame, and what to try.

I'm just trying to make sure that the behavior I see here is as intended.

**Comment by hizzlekizzle** [comment]
Set a value of 0, bind hotkey enabler to retropad-select, go into arcade games and try to insert coins. It will work okay on some games, other games it won't. If you find one where it won't, change the value to 5 and try again.

**Comment by snackycakes** [comment]
Yes, that's right.  I tested it using FBA Neo and the game Contra and select button as both hotkey and coin insert.  With value set to 0, coin button is blocked and no coins inserted.  After setting value to 5, coin key is processed correctly and hotkeys still work.

**Pull request merged**
