### PR TITLE
(RGUI) Add inline playlist thumbnail support

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds 'proper' inline thumbnail support for playlists in RGUI. Previously, thumbnails could only be shown by highlighting a playlist entry and pressing RetroPad Y. Now we have the following:

Screenshot_2019-03-27_16-18-22

Screenshot_2019-03-27_16-18-39

Screenshot_2019-03-27_16-19-40

Fullscreen thumbnails can still be toggled by pressing RetroPad Y, which provides a pleasant user experience:

window_record__2019_03_27__16_22_02

This of course works best with the new RGUI widescreen layouts, but it's still pretty good with the traditional 4:3:

Screenshot_2019-03-27_16-24-02

The feature is controlled via the following menu options under `User Interface > Appearance`:

- `Show Playlist Thumbnails`: Toggles the feature on/off (even when it is off, fullscreen thumbnails may still be shown with RetroPad Y)

- `Top Thumbnail`: This is renamed from the usual 'Thumbnails' entry, and this is the one that's shown fullscreen when pressing RetroPad Y

- `Bottom Thumbnail`: This is renamed from the usual `Left Thumbnails`

- `Swap Thumbnails`: Just swaps the draw position of the top/bottom thumbnails (in case the user wants the fullscreen-able thumbnail at the bottom)

The mini thumbnails look best (I think) with `Thumbnail Downscaling Method` set to `Sinc/Lanczos3`, but all methods look okay (particularly on small screens)

### CODE REVIEW

**Comment by hhromic** [comment]
Please give this man (or woman) a medal. What an incredible work he (or she) has been putting together for the RGUI menu recently. Million thumbs up.

**Comment by jdgleaver** [comment]
I'm a 'he', and your kind words are so very much appreciated. :slightly_smiling_face: 

Long live RGUI!

**Comment by fr500** [comment]
This is amazing

**Comment by twinaphex** [comment]
Amazing yeah.

**Comment by fr500** [comment]
Just wondering... but maybe you can do a high resolution mode? so the screenshots would look fine for RA users on PC that like RGUI?

Or is rendering RGUI and the thumbs and all that in software that demanding?

**Comment by jdgleaver** [comment]
@fr500 I've been thinking about that for a while...

I would like a high resolution mode, but it's kind of impractical with the way that RGUI is written - i.e. it's all geared around a fixed framebuffer size, with fixed positions/offsets and a bitmap font that doesn't scale. I could leverage the current internal upscaling option (draw background/text/border, perform upscale and then 'paste in' high resolution thumbs) but this is *very* expensive (like >50% of one CPU core on a decent desktop system, whereas the current low resolution mode - with inline thumbnails - doesn't even stress an o3DS). It's also a bit of an ugly solution...

I'm sort of toying with the idea of a new rgui-hd menu driver, which would keep the exact same aesthetic but allow for a high resolution font + thumbnails (using the conventional menu drawing methods, a la XMB/Ozone). This could be a nice lo-fi option for desktop users. It would be quite a bit of work, however! Probably something I'll pick at in-between other projects...

**Pull request merged**
