### PR TITLE
Step#1 to add per-folder core options

### PR DESCRIPTION
**Pull request by crystalct**
Why per-folder options file (.opt file) should be helpfull?
Have you ever tried to play different subplatforms with atari800 or blueMSX cores? You have to change core option every time you change subplatform or save per-game options every game. With per-folder options you can save one options file for the folder where games are  grouped about one subplatform (like atari 800XL or atari 5200, for example).
Step#1 is demostrative but working. Just rename a per-game option file as folder name (where games are placed) and you can try it .... it works.
Diff file make confuse the things, but they are simpler than how it seems, i added one step on previous IF:
```
/* Check whether game-specific options exist */
   if (game_specific_options &&
         rarch_game_specific_options(&game_options_path))
   {
      /* Notify system that we have a valid core options
       * override */
      path_set(RARCH_PATH_CORE_OPTIONS, game_options_path);
      p_rarch->runloop_game_options_active = true;

      /* Copy options path */
      strlcpy(path, game_options_path, len);

      free(game_options_path);
   }
   else
   {
      char global_options_path[PATH_MAX_LENGTH];
      char per_core_options_path[PATH_MAX_LENGTH];
.......
```
after `Check whether game-specific options exist` and if is false, it make a `Check whether folder-specific options exist` and if no follow previous else as usual.

```
   /* Check whether game-specific options exist */
   if (game_specific_options &&
         rarch_game_specific_options(&game_options_path))
   {
      /* Notify system that we have a valid core options
       * override */
      path_set(RARCH_PATH_CORE_OPTIONS, game_options_path);
      p_rarch->runloop_game_options_active = true;

      /* Copy options path */
      strlcpy(path, game_options_path, len);

      free(game_options_path);
   }
   else
   {
      /* Check whether folder-specific options exist */
      if (game_specific_options &&
            rarch_folder_specific_options(&folder_options_path, p_rarch))
      {
         /* Notify system that we have a valid core options
          * override */
         path_set(RARCH_PATH_CORE_OPTIONS, folder_options_path);
         p_rarch->runloop_game_options_active = true;

         /* Copy options path */
         strlcpy(path, folder_options_path, len);

         free(folder_options_path);
      }
      else
      {
         char global_options_path[PATH_MAX_LENGTH];
         char per_core_options_path[PATH_MAX_LENGTH];
         bool per_core_options_exist   = false;
         bool per_core_options         = !settings->bools.global_core_options;
.........................
```
Next step should be write per-folder options file.
The natural thing is add a specifil menu item inside Option core menu or let `Content Directory Overrides` to write both .cfg and .opt option folder files.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
Can we get this merged? it's already something if it can read the per folder opt files.

But I see this change isn't doing the same declarations for folder_options_path that are done for core/game_options_path:
there's no
char per_folder_options_path[PATH_MAX_LENGTH];
nor
per_folder_options_path[0]      = '\0';

Not that I know why it's needed. Please check.

**Comment by Tatsuya79** [comment]
Ok it's working, you're missing:
char *folder_options_path      = NULL;
at the beginning of:
static void rarch_init_core_options_path

**Comment by twinaphex** [comment]
@jdgleaver Can you review this?

**Comment by jdgleaver** [comment]
I will try to find some time to review this next week

**Comment by jdgleaver** [comment]
@crystalct Apologies for taking so long to review this. You have made a valuable addition here!

I see a couple of small issues:

- The way you've written `rarch_folder_specific_options()` means there is some unnecessary code duplication. I would prefer all of these 'options' routines to use the same `retroarch_validate_per_core_options()` function as a base
- We need to distinguish between having active per-game and active per-folder options

I have addressed these with the following diff: [folder_options.zip](https://github.com/libretro/RetroArch/files/6022118/folder_options.zip)

(I also fixed up a couple of other things unrelated to your PR, It seems someone else has refactored some of the existing functions, and made bad design choices... I undid this...)

Please could you apply the patch on top of your PR, and then rebase against current master? I think we should be good to merge after that.

I think for step 2, the existing `Create Game Options File`/`Save Game Options File` entry in the `Options` menu should be replaced with a new submenu that has similar functionality to the current `Controls` quick menu (i.e. with entries to save and delete each type of override). But of course, this is a larger project, and can be done at another time.

@Tatsuya79 I would appreciate it if you could double-check the patch file as well :)

**Comment by crystalct** [comment]
Patch applied.
There aren't any conflicts... good!

**Comment by Tatsuya79** [comment]
Working fine, it loaded the opt I made for some folders.

Slightly unrelated as it concerns cfg overrides, but this line is wrong in the log:
```
[INFO] [Overrides]: Content dir-specific overrides found at "E:\Emulateurs\RetroArch64\config\Genesis Plus GX\Woody Pop - Shinjinrui no Block Kuzushi (Japan).cfg".
```

It should be:
```
[INFO] [Overrides]: Content dir-specific overrides found at "E:\Emulateurs\RetroArch64\config\Genesis Plus GX\Sega - Master System - Mark III.cfg".
```

while this line following up is right:
```
[INFO] [Config]: Appending config "E:\Emulateurs\RetroArch64\config\Genesis Plus GX\Sega - Master System - Mark III.cfg".
```

**Comment by jdgleaver** [comment]
@crystalct Great, thanks! The code is all good now, but would you be able to squash your commits before we merge this? (e.g. https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec)

@Tatsuya79 Thanks for testing. I see the bug in the config log:

```c
   /* per-content-dir overrides */
   /* Create a new config file from content_path */
   if (config_file_exists(content_path))
   {
      char temp_path[PATH_MAX_LENGTH];

      temp_path[0]    = '\0';

      RARCH_LOG("[Overrides]: Content dir-specific overrides found at \"%s\".\n",
            game_path);
```
Someone pasted `game_path` there instead of `content_path` - I'll fix that later...

**Comment by crystalct** [comment]
OK.... i dont know exactly what i done... but surely now this pull request is not usable ......

**Comment by jdgleaver** [comment]
Oh dear... :(

Let me check out your repo again at my end, and I'll try to work out the exact commands to fix this....

**Comment by Tatsuya79** [comment]
I did rebase it there if you need it:
https://github.com/Tatsuya79/RetroArch/tree/foldopt

**Comment by jdgleaver** [comment]
Okay:

```
git reset --hard 397ef6c29ed41ee0029c8fe18768430f535c7c3f
git rebase -i 1c6c03fa786c98b1b86ce7bead37631c95ba55ed~1
```
Change the first part of the text so it looks like this (note the `fixup`s):

```
pick 1c6c03fa78 Step#1 to add per-folder core options
fixup cb55513cc0 Define `folder_options_path` in retroarch.c so it compiles
fixup 10411561b5 jdgleaver patch

# Rebase f40644c901..10411561b5 onto f40644c901 (3 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
```

When you save that, your original 3 commits will be squashed into one. Then force push your changes (`git push --force`)

You should also really rebase against master, but I think that will complicate things further, so might be best to omit that step...

**Comment by crystalct** [comment]
Done ^_^

**Comment by jdgleaver** [comment]
Excellent!

@twinaphex Please merge :)

**Pull request merged**
