### PR TITLE
Input remapping improvements

### PR DESCRIPTION
**Pull request by fr500**
Done:
- allows saving/loading analog dpad mode
- allows saving/loading libretro device
- restores the original values when the remap is unloaded
- allow removing remap files when present
- error checking

Might add:
- reset to defaults menu entry
- move the actions to the top of the menu

Won't do: 
- localization, it's too much of a hassle to go over all those files pasting the same un-localized strings

Only active remaps show up (active means loaded, it only loads core or game automatically, never both):

image

Can remove properly:

image

If I try removing again I get an error:

image

If I save both at runtime both are marked as active so it allows me to remove both:

image

### CODE REVIEW

**Comment by fr500** [comment]
please test before merging, haven't found any issues so far.

**Comment by hizzlekizzle** [comment]
this seems to be working for me in brief testing. Being able to delete them from the menu is pretty awesome. Are there any troublesome scenarios I should test specifically?

**Comment by fr500** [comment]
Just if analog dpad  and libretro device leaks to the main config I guess

**Comment by twinaphex** [comment]
Seems some conflicts need to be resolved before this could be merged. Luckily it's only in CHANGES.md

**Comment by fr500** [comment]
fixed the conflicts

**Pull request merged**
