### PR TITLE
Initial UTF-8 support for rgui/xmb/glui. Enables first 256 codepoints.

### PR DESCRIPTION
**Pull request by bparker06**
Due to the current freetype atlas limitation that needs further discussion before any work is done, this patch will only appear to support the first 256 Unicode codepoints, which includes the Latin-1 Supplement. rgui and xmb drivers can now support those languages like French, German Spanish etc. and their translations have been re-saved as UTF-8. I have also switched UTF-8 to be the default compile option, with make NO_UTF8=1 able to switch it off... however this will also break the translations which are now encoded as UTF-8.

### CODE REVIEW

**Comment by twinaphex** [comment]
Have you been able to see any regressions with non-GL drivers then or is this mentioning just erring on the side of caution?

**Comment by bparker06** [comment]
I am not able to test any other video drivers on my system. The available ones mentioned on startup are: gl, sdl, vg.

When I try to use SDL (with my patch or not), it picks 'null' instead and I get a black screen. When I choose vg, it segfaults in an unrelated place:

udev_input_poll (data=0x0) at input/drivers/udev_input.c:376
376	   udev->mouse_x   = udev->mouse_y   = 0;

**Comment by twinaphex** [comment]
OK, so these drivers already had issues before? No biggie then it seems.

**Comment by bparker06** [comment]
Correct.

**Comment by Alcaro** [comment]
I wouldn't recommend turning UTF-8 on by default until it also works in Material/GLUI (and possibly other menus as well, not sure if any other than RGUI/Material/XML are considered stable?). If you prefer moving fast and breaking things, go ahead, but expect a huge pile of dissatisfied users.

> static uint32_t string_walk(const char **string)

Don't create functions with the same name in two files, not even static. We sometimes #include every single source file in a huge blob, as a poor man's LTO (or if we don't want to keep updating 20 MSVC project files).

> static uint32_t gl_strlen_utf8(const char **string)

Why is that a pointer-pointer? It makes sense for string_walk since it updates the pointer, but this one doesn't need that.

> /* Prefetch 256 bytes ahead. */

Our strings aren't that long. Just iterate byte-by-byte, there's no reason to overcomplicate it. Oh, and __builtin_prefetch is GCC only, let's not break MSVC compat.

> static uint32_t xmb_strlen(const char **string)

That's the read-a-UTF8-codepoint function, except with 'read byte' replaced with strlen. It won't return anything useful, except by coincidence.

**Comment by bparker06** [comment]
Thanks for the comments, I will update the pull request to fix all of that.

**Comment by bparker06** [comment]
Hopefully this update addresses all of your concerns, I tested materialui and it seems to work for me as well.

**Comment by Alcaro** [comment]
> uint8_t utf8_walkbyte(const char **string)

That function made sense when it was replaced with utf8_walk depending on compiler flags. But since it doesn't seem used anymore (other than utf8_walk itself), let's inline it, or at least make it static.

> uint32_t utf8_walk(const char **string)

Missing ifdef?

> -#define RETRO_LBL_TURBO_ENABLE "Turbo Activé"
> +#define RETRO_LBL_TURBO_ENABLE "Turbo Activé"

The language files follow the default state of the UTF-8 flag. If we're not changing the default, then they stay in their old encodings.

But if Material is that easy to fix, I vote enable. That's always been the long-term goal, anyways.

**Comment by Alcaro** [comment]
> ifneq ($(NO_UTF8), 1)

...could swear I mentioned this last time? ifneq ($(UTF8), 0) would be cleaner, negative flags tend to confuse me.

But with the language files translated, the only good name for that switch is $(I_LIKE_BROKEN_STRINGS), so let's just keep it as is. We'll remove it soon enough, anyways.

Everything here looks fine to me; thanks for finishing this project. (I could swear we had a Russian PR that's also waiting for UTF-8, but it seems to have disappeared.)

Unless you have any final comments, @twinaphex, I'll let you do the honors.

**Pull request merged**
