### PR TITLE
Vulkan backend for RetroArch

### PR DESCRIPTION
**Pull request by Themaister**
*Massive PR dump incoming*

This is a result of a boring (which got interesting) christmas vacation and finally I can make it public. Here's a fairly complete Vulkan implementation for RetroArch. Currently, the backend supports most of the bells and whistles which are expected from a backend.

- 16-bit/32-bit blits to screen (duh)
- XMB/GLUI/RGUI
- Overlays
- Font rendering
- Basic multipass shader support based around Vulkan GLSL/SPIR-V. We're not at the point where we can move to this wholesale, so it will live along side with CG/GLSL for now.
- libretro vulkan interface with simple test core
- Async GPU recording

As for context backends, there's only Wayland in this PR.
I have only had access to ARM and Intel/MESA setups during development. Getting things up and running on more platforms, backends and GPUs will be priority once I find time.

There are a few points which can be contentious here:
 - https://github.com/KhronosGroup/glslang is included as a submodule, this is to be able to build GLSL -> SPIR-V in runtime.
- The glslang bison generated file is part of the repo. This is to avoid requiring bison during build which is super painful for Windows.
- Stock Vulkan shaders are built to SPIR-V as includable headers offline. These files are part of repo, since my hacked up script uses glslangValidator + xxd, again not palatable for Windows.
- The core shader backend of Vulkan is C++. There are a few reasons for this:
    - It needs to interface with glslang, which is also C++.
    - I wanted to make the shader backend more palatable for being reusable outside RA to increase adoption in other projects. Therefore the core backend is completely agnostic to RA itself. However, the entire backend is hidden behind a C API, so should be well enough contained and it doesn't spill into the actual RA vulkan backend (which is fully C).
    - In order to support GL/GLES properly with Vulkan GLSL/SPIR-V later, I have a concrete plan for that, and will require to interface with C++.

### CODE REVIEW

**Comment by ToadKing** [comment]
It sucks that we have to include a git submodule after the horror of dealing with PPSSPP submodules, but there's not much way around it other than yet another baked-in dependency.

I'm okay with the C++ dependency as well for this since we thankfully won't have to worry about legacy platforms.

What would be nice in the future is combining the separate wayland_ctx_vulkan driver into a generic wayland driver that would support GL(ES) and Vulkan in one, but I am unsure how easily that can be done. We already support it for GLES and OpenVG on Videocore.

**Comment by Themaister** [comment]
Once glslang becomes a mainstream library in distros, we can probably rely on that instead.

Yes, we need some refactoring to avoid near-duplicating X/Windows/Wayland backends.

**Comment by neobrain** [comment]
Hey, that's some impressive work over there ;)

Just curious, how does this new backend compare against your old code? Did you try out AZDO optimizations before, or is this mostly a "I wanted to try out new stuff" kind of thing?

**Comment by twinaphex** [comment]
@Themaister I still cannot test with Vulkan (the Ivy Bridge support in Intel Mesa driver seems broken right now, and according to early reports Haswell won't show the menu drivers' output so far, only Broadwell and up seems to output fine as reported by @almostalive) -

I took an initial stab at trying to unify the regular Wayland EGL context driver and the Wayland Vulkan context driver - 

https://github.com/libretro/RetroArch/commit/eeada0c458b5e53cc4b2656556350dcfb213726d

@Themaister - try seeing if this context driver works for you on Vulkan. The only things you have to change is:

1) gp to gfx/drivers_context/wayland_ctx.c
2) change line 19 to '#if 1'.
3) go to gfx/video_context_driver.c
4) remove gfx_ctx_wayland_vulkan from the list
5) go to Makefile.common
6) Remove wayland_ctx_vulkan.c so that it will no longer be compiled in.

**Comment by Themaister** [comment]
I have a pull request up now which should hopefully fix Ivy Bridge.
@neobrain AZDO is useless for us, it only makes sense for larger 3D engines where you're okay with only targeting nVidia/AMD. I did try persistent PBO uploads before, but it was actually 10x *slower* for some bizzarre reason, so didn't bother trying to figure out why that happened.

**Comment by twinaphex** [comment]
@Themaister 

OK, so with the recent pull request, I can get ingame with Vulkan now.

Here are my current findings with Ivy Bridge Mesa (latest source I believe from mesa vulkan branch) -

1 - GLUI is the only menu driver that works reliably. The background is black instead of white (does this happen for you too? on GL we'd do a glClearColor to white there and then do glClear), the glyphs are messed up but it at least works. It seems it also might still have some problems with 'labels' that get updated per-frame (like the estimated monitor refresh rate setting)

2 - XMB doesn't start up, gives this -

Assertion failed at gfx/common/vulkan_common.c: 116.

3 - RGUI gets ingame but shows a black screen instead of a menu texture.

4 - The Vulkan test core seems to run and output graphics just fine. I see a colored triangle and an orange-ish background.

5 - XRGB8888/RGB565 software rendered cores seem to work just fine.

6 - The regular Test Core (the one that uses the new 'get_current framebuffer' environ callback), it does crash when I try to shut it down. No idea if this is a regular core issue or if it's something related to Vulkan, I'll have to look into that.

**Comment by almostalive** [comment]
Ok I guess I will finally write down my experience a bit. I have a broadwell laptop and a haswell desktop. 

On the broadwell laptop everything works as expected I believe. I can run all the menu_drivers, the cores I have tried worked and the vulkan test core works.

On the haswell desktop. All the menu drivers "technically" work. rgui and xmb are blank/black screens but navigation works and you can load cores. glui is fully functional though which is awesome! The cores and vulkan test core all work as expected.

Amazing work @Themaister day one support and I was running this the same day as well!

Now on to the problems I have seen. These happen on both pc's
Smaller one first.
The vulkan test core does not respond to any input. f1 does not bring up the menu and Esc does not quit retroarch. 

The second bigger problem.
video_driver="gl" does not work with vulkan support compiled in. Building retroarch with ./configure --disable-vulkan the gl driver works again.

this is what gdb has to say for a debug version of retroarch running wayland on my broadwell laptop
https://gist.github.com/almostalive/129b1fddb3eeeeff0800 if you need me to build a debug version of mesa as well let me know.

also I made two crappy videos with weston's screen-recorder
https://www.dropbox.com/s/qz3wttdl4romzsv/ravulkanbroadwell.mkv?dl=0
https://www.dropbox.com/s/lspv01jxxyfi6m6/ravulkanhaswell.mkv?dl=0 

again awesome work. and now with your recent changes allowing @twinaphex to run it, vulkan support will hopefully improve even more.

**Comment by twinaphex** [comment]
@almostalive I took care of the Vulkan test core not being able to respond to the menu toggle press or any other input at least by at least doing one input_state call. Not sure if this is intended behavior and if it only requires you to do at least one input_state call per frame when input poll behavior is set to 'late'.

**Comment by twinaphex** [comment]
@Themaister I added a large amount of the WSI platform-specific code to wayland_ctx.c - the following functions could be easily moved outside to a vulkan_wsi_common.c file  -

vulkan_destroy_context 
vulkan_acquire_next_image
vulkan_surface_create
vulkan_present

Along with this struct which could be moved outside to a header file -

gfx_ctx_vulkan_data

from there we can have the context drivers calling these functions along with a requested type.

Let me know if you can use these as building blocks to take a look at the xcb/xlib context drivers (if I don't get around to those before you do that is). @ToadKing maybe you could look into the Windows side of things based on this? I lack a Windows device with a Vulkan-compatible GPU at any rate.

**Comment by ToadKing** [comment]
I looked briefly into Windows support the other day. Compiling in glslang statically might be difficult since it doesn't seem to support mingw that well, and has some DLL-specific code. It might be better on Windows to just build it as a DLL and link to it from RetroArch. It would avoid a bunch of upstream changes as well.

**Pull request merged**
