### PR TITLE
(RGUI) Add colour themes

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new 'Menu Color Theme' option to the RGUI 'User Interface > Appearance' menu. 32 presets are included.

- These are identical to the existing default, but with different primary colours:

screenshot_2019-01-09_10-36-09

screenshot_2019-01-09_10-36-19

screenshot_2019-01-09_10-36-31

screenshot_2019-01-09_10-36-39

screenshot_2019-01-09_10-36-48

screenshot_2019-01-09_10-36-56

screenshot_2019-01-09_10-37-14

- There are more 'conventional' themes, based for the most part on those included with XMB:

screenshot_2019-01-09_10-37-26

screenshot_2019-01-09_10-37-36

screenshot_2019-01-09_10-37-44

screenshot_2019-01-09_10-37-51

screenshot_2019-01-09_10-37-59

screenshot_2019-01-09_10-38-09

screenshot_2019-01-09_10-38-19

screenshot_2019-01-09_10-38-28

- These are all based upon popular (and not so popular?) text editor colour schemes (I think these 'flat' colours work particularly well):

screenshot_2019-01-09_10-38-37

screenshot_2019-01-09_10-38-45

screenshot_2019-01-09_10-38-54

screenshot_2019-01-09_10-39-05

screenshot_2019-01-09_10-39-14

screenshot_2019-01-09_10-39-23

screenshot_2019-01-09_10-39-30

screenshot_2019-01-09_10-39-38

screenshot_2019-01-09_10-39-50

screenshot_2019-01-09_10-39-58

screenshot_2019-01-09_10-40-06

screenshot_2019-01-09_10-40-14

screenshot_2019-01-09_10-40-21

screenshot_2019-01-09_10-40-29

screenshot_2019-01-09_10-40-37

screenshot_2019-01-09_10-40-45

screenshot_2019-01-09_10-40-55

By default, 'Menu Color Theme' is set to 'Custom', which uses the existing normal/hover/title/etc. colour values currently set via the RetroArch config file (shown in the menu as 'Custom menu ... color').

Hopefully with this addition, RGUI need no longer be considered the 'ugly duckling' of the family!

### CODE REVIEW

**Comment by twinaphex** [comment]
Hey that's pretty great! Thanks so much for this!

**Comment by RobLoach** [comment]
This is so cool!

**Comment by jdgleaver** [comment]
Thanks for the appreciation!

I'm really glad that people like this. Preparing these colour schemes was *extremely* tedious, but nice comments make it all worthwhile!  :slightly_smiling_face:

**Comment by RobLoach** [comment]
Have any tips on how to generate the C value? I'd like to add Monokai.

**Comment by jdgleaver** [comment]
@RobLoach Sure, it's reasonably straightforward:

- First you need an editor colour scheme file that gives the colours in hex RGB format. Perhaps something like this would do for Monokai: https://github.com/gerardroche/sublime-monokai-free/blob/master/MonokaiFree.tmTheme. You'll also want a screenshot of the theme in action.

- The rgui colour values are in argb8888 format, i.e.: AARRGGBB

    - For any text colours, the alpha component (AA) should be FF

    - For any dark theme, the alpha component should be C0 (not set in stone, but this gives consistent results)

    - For any light theme, the alpha component should be E0 (this needs to be high, otherwise we don't get a light enough background, but we still need a little transparency)

- For 'bg_dark_color' and 'bg_light_color', make a note of what the editor scheme text file defines as the background colour. Now here's the fun part:

    - Convert the RGB value it to HSV

    - Increase V (Value) by ~4-6

    - Convert back to RGB

    - Set the 'bg_dark_color' and 'bg_light_color' RRGGBB values to the result

    - Compile and run RetroArch, then compare the background colour that's displayed with the screenshot of what the theme *should* look like. It'll be fairly close, but you may need to go back and tweak the 'V' value (sometimes a tiny adjustment to the Hue is also required...)

- For 'border_dark_color' and 'border_light_color' it's basically the same, only the theme colour value you want for these is most likely whatever is specified for 'line highlight' (sometimes this doesn't look so good, in which case the 'comment' colour is a reasonable alternative).

- The text colours are easy - pluck whatever values you want from the scheme text file (no tweaking is required)

I hope that helps!

**Pull request merged**
