### PR TITLE
Add "absolute" mouse support

### PR DESCRIPTION
**Pull request by casdevel**
In order for this to work, mouse input data handling had to be changed. This is way so many changes.

Most of the new code is for absolute/relative data conversions and mapping of coordinates to the viewport, and is organized into functions to minimize/simplify changes to the rest of the code.

There is also addition of single OS pointer coordinates (for menu) since this must be separated from multiple mice code. This coordinates are (currently) available only if we have X11.

Since mouse code now handles both "absolute" and "relative" devices, touchpads can be handled the same way as mice. This makes separate touchpad code no longer necessary, and is removed.

Rest of the changes are mainly adaptations to this new way of handling input data, apart from few lines with trailing spaces that are changed automatically by text editor.

### CODE REVIEW

**Comment by retro-wertz** [comment]
how does change affects cores which already used RETRO_DEVICE_MOUSE/LIGHTGUN and RETRO_DEVICE_POINTER, both have different computations as to track where exactly the coordinates suppose to be with respect the games resolution.

from what i know RETRO_DEVICE_POINTER gives you divides the viewport to -7fff to 7fff while RETRO_DEVICE_MOUSE/LIGHTGUN gives +/- px.

thanks.

**Comment by casdevel** [comment]
Neither cores nor RetroArch should "notice" any difference, everything should be the same. 

However, with this changes, core can use RETRO_DEVICE_MOUSE, RETRO_DEVICE_POINTER or RETRO_DEVICE_LIGHTGUN with any device that is recognized as a mouse. This means it's possible that core that had no-input issues with udev to start getting input after this.

Basically core should always get valid input, regardless of RETRO_DEVICE_* type and actual hardware device that is used.

**Comment by twinaphex** [comment]
Hi there @casdevel,

great commit. One little thing though. Can you replace the usage of __s32 with int32_t instead?

**Comment by casdevel** [comment]
@retro-wertz you can test this with [input debugger core](https://github.com/casdevel/input-debugger-libretro).

Core is still not finished but main functionality is there. No user docs yet, so if you decide to try, go to core options and select input device type and number of user you want to monitor ('Page' and 'User Count' option). Both "absolute" and "relative" device(s) should work with 'Lightgun Input', 'Mouse Input' and 'Pointer Input' page. Note that small difference in speed is expected when switching between 'Mouse/Lighgun Input' and 'Pointer Input' pages.

**Comment by casdevel** [comment]
@twinaphex 

> Can you replace the usage of __s32 with int32_t instead?

Yes.

**Comment by retro-wertz** [comment]
i though that everything would be the same, especially for RETRO_DEVICE_POINTER but its not. this used to return coordinates -7fff to 7fff inside the game's viewport. but this commit is returning coordinates based on the entire screen, which in a crosshair-type game, you now are moving the crosshair like device_mouse/lightgun does instead of the crosshair following the mouse pointer. it was easier to play zapper games for example this way.

also the edges are not always the min x/y or max x/y (which i believe is min -32767 to max 32767 x/y)
(i used this to return the coordinate of pointer-forgive the newbish method as i am not a seasoned programmer, i just trace stuff and test)

      mzx = input_cb(port, RETRO_DEVICE_POINTER, 0, RETRO_DEVICE_ID_POINTER_X);
      mzy = input_cb(port, RETRO_DEVICE_POINTER, 0, RETRO_DEVICE_ID_POINTER_Y);
      printf("%04d %04d\n", mzx, mzy);
(see where the pointer is on the screen)

x_min:
screenshot_2017-10-05_19-52-05

x_max:
screenshot_2017-10-05_19-53-16

y_min: (pointer is not showing in screenshot, but it should be on the top now):
screenshot_2017-10-05_20-04-36


y_max:
screenshot_2017-10-05_19-55-09

**Comment by casdevel** [comment]
@retro-wert matching OS pointer position is possible only in RetroArch menu with udev input driver. 
It's either that or no multiple mice support. Further more, OS usually applies some effect(s) to mouse input, while udev driver works with original (raw) mouse input, so movement will also be different (not just the position).

**Comment by retro-wertz** [comment]
so, the change in behavior of device_pointer between the old version(and other drivers at the moment) compared to how this is now is now an issue? its now acting like device_mouse/light(and i am not talking about the actual mouse hardware, but the interface that is used to communicate between the cores and retroarch, which is RETRO_DEVICE_MOUSE/LIGHTGUN/POINTER)

**Comment by casdevel** [comment]
Core still receives RETRO_DEVICE_POINTER data in the same range as before, difference is that udev driver no more uses OS pointer position for that. Now every mouse has it's own absolute position. This was necessary in order to support multiple "absolute" mice

**Comment by casdevel** [comment]
If this turns out to be a problem for the users, new menu option(s) can be introduced to allow user to disable multiple mice and/or "absolute" mice support and keep the old pointer behavior (if he don't need new functionality).

**Pull request merged**
