### PR TITLE
Ifdef the broken dbus code better.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This PR does two things.

1. It hides the dbus code better better behind `#ifdef`, this should of been done from the start, but it seems in the rush to replace the working `xdg-screensaver` this was overlooked.
2. It disables dbus again by default as this feature does not work and the people who added this pointless feature besides strong and valid objections have not bothered to fix it or even noticed it was broken after an extended period of time. Personally I have 0 interest in dbus and would prefer to just remove it outright. However those who do have an interest in it should be at least given a chance to fix it first, but they should use `--enable-dbus` given how upstream dbus will break compatibility again in the future and its not fair for the majority of users who do not need this functionality to build useless code.

Also consider this does compile and work.
```
./configure --disable-x11 --enable-dbus && make
```

## Related Issues

New dbus versions will and have broken compatibility. This should be expected to happen again and again which results in.
```
[ERROR] [DBus]: Failed to suspend screensaver via DBus.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
```
Personally I think its stupid to play catch up when we already have a fully working feature that does not have these drawbacks.

## Related Pull Requests

N/A

## Reviewers

@nguillaumin, @t-paul and maybe @hadess
(I have no idea which of these users are still around?)

### CODE REVIEW

**Comment by twinaphex** [comment]
I don't think any of them are really actively around right now.

Anyway, I'll merge your PR, there is logic in it.

**Comment by hadess** [comment]
My attempt at cleaning this up backfired, as I didn't understand the API used. I made assumptions on what I thought it did, which wasn't the way it did actually work.

> New dbus versions will and have broken compatibility.

There was nothing cross-desktop available before, and it hasn't changed in the 5 years since the Idle Inhibition spec was written. I'm pretty sure the old GNOME and KDE-specific APIs still work if that's a concern.

The problems I encountered were:
- the API didn't have any way to stop the inhibition. It expected the inhibition to automatically stop once the window that was used to actually launch the emulator/core disappeared.
- what I thought was a toggle to turn the screensaving on/off is actually the configuration for whether or not to do inhibition at all.

And as I didn't test my patch, and was expecting somebody to point out my mistakes, but the patch just got merged, I got yelled at instead. That seriously hampered my willingness to contribute.

**Comment by orbea** [comment]
> And as I didn't test my patch, and was expecting somebody to point out my mistakes, but the patch just got merged, I got yelled at instead. That seriously hampered my willingness to contribute.

If I contributed to that I would like to apologize. Scaring away contributors is certainly not my goal.

That said dbus support did work initially and only broke for me when it was upgraded in Slackware-current. I did not notice till long after the fact so I'm not sure what dbus version caused the regression. The only potential controversial change in this PR was that dbus support now explicitly requires `--enable-dbus`,  I think there is little value in setting it to `auto` if the feature has no one willing to maintain it and that it will be enabled by default on most linux systems regardless of whether that is required, desirable or even works.

Additionally I have no plans of objecting to someone improving the dbus support here as long as it does not break the existing xdg-screensaver support, but they should consider that this will be a long term maintenance given that dbus clearly has broken this feature with some upstream change and I suspect this won't be the last time... I hate to say "I told you so", but I foresaw this outcome from the start and I personally have very little interest in trying to make this feature work with all the potentially incompatible dbus versions users may have installed.

**Comment by hadess** [comment]
> That said dbus support did work initially and only broke for me when it was upgraded in Slackware-current. I did not notice till long after the fact so I'm not sure what dbus version caused the regression. 

I think you confuse dbus, the protocol and its implementation, and the services which could be implemented with D-Bus as a transport. Think of D-Bus as HTTP, and the implementation of that idle inhibit spec as the web server.

It's much more likely that the implementation of that idle inhibit spec broke on your system. I implemented the one for GNOME, so I could help with that. If you used another desktop, their implementation might be the problem. If you use a bare window manager under X11, there's probably nothing setup that implements the spec.

In which case you'd have an error coming from D-Bus telling you the error (such as the fact that there's no known services with that name, or it didn't understand the arguments, or the code in RetroArch failed to parse the return values).

This is very terse:
> [ERROR] [DBus]: Failed to suspend screensaver via DBus.

```dbus-monitor --session``` will show you the messages going back and forth in the D-Bus session, if you can't add better error messages in the RetroArch code.

**Comment by orbea** [comment]
I start dbus in `.xinitrc` with.
```
eval `dbus-launch --sh-syntax --exit-with-session`
```
This has not changed in a long time and any regressions are not from my configuration, but from a newer version of dbus.

Like I said, I have very little interest in making dbus work when xdg-screensaver works just fine, if others want to accomplish that they can. However please don't expect me to debug it. :)

**Comment by nguillaumin** [comment]
Cheers for CC'ing me.

> And as I didn't test my patch, and was expecting somebody to point out my mistakes, but the patch just got merged, I got yelled at instead. That seriously hampered my willingness to contribute.

Unfortunately I got the same experience. I proposed a patch stating clearly that I hadn't done C in a long time and it needed review, it got merged without comments, then I get yelled at by anti-DBus people, and then someone rewrote my patch completely because of "bad coding" without giving me feedback nor the possibility to fix my mistakes and improve. Same as you, I'm not especially interested in contributing anymore.

Regarding DBus support in itself, I'll repeat what I said last time: I'm sure it will be useful to some people, and some people won't like it. Calling it "useless" or "pointless" is not very respectful to the people it would be useful for, and neither for the people having worked on the patch in the first place.

The only way to know would be to survey user or collect data, without that it will just be personal opinion. That's what I though "auto" would be a good compromise as it would only be enabled where it makes sense. But at this point, I'm not too interested in debating that anymore so I won't object to any change.

**Comment by twinaphex** [comment]
Just to make it clear - neither of you two were getting yelled at by me, instead, I welcomed your contributions and merged them. 

I think people need to realize that we are a quickly moving project here and we need to move fast at times and that in doing so it's impossible to live up to everybody's expectations. That being said, I do not think every comment that gets made amounts to yelling, I don't think that is orbea's intention or tone here.

If you guys have all sorts of reasons for not wanting to contribute anymore that has nothing to do with us as a project or as a team, I cannot help that. The only thing I can do is try to be as inclusive to everybody that tries to submit a PR. But at the same time, it is our project, we have a lot of users, and when users creep along that cause major issues for them, we have to be able to move quickly and we cannot worry then about stepping on oversensitive toes of some coder who contributed to this or that. The project comes first then. I think this is only natural, the same would apply towards me were I to contribute something and it causes more problems than it solves, then for the sake of the project I'd swallow my pride and go along with what the majority wants or what causes the least problems. We cannot make ourselves dependent on coders whom will leave on a whim without informing us whatsoever of what the issue was, I think that much is certain.

**Comment by nguillaumin** [comment]
> neither of you two were getting yelled at by me, instead, I welcomed your contributions and merged them

Agreed, and it's appreciated.

> we are a quickly moving project here and we need to move fast at times and that in doing so it's impossible to live up to everybody's expectations.

That's fine, and probably what contributes in making RetroArch such a great project. I'm just saying there may be ways to be a bit more diplomatic with new / once-off contributors, which presumably have something valuable to add to the project too.

> If you guys have all sorts of reasons for not wanting to contribute anymore that has nothing to do with us as a project or as a team, I cannot help that

> stepping on oversensitive toes of some coder

You have 2 contributors both reporting a similar bad(-ish) contribution experience, and yet no, it has to be our own fault :wink:. Either we are "oversensitive" (I'm not known for being oversensitive), or we had external reasons for not wanting to contribute anymore (that's not true, I had other stuff to contribute but was put off by this experience).

I get that you're trying to be inclusive, and it works well in some aspects (quick PR merging), but I'm just saying there may be other possible improvements in this area, assuming contributors feedback can be acknowledged.

**Comment by twinaphex** [comment]
@nguillaumin Well, it's impossible for me to police other contributors' speech. It might be that I don't think whatever @orbea said was really all that overtly off-putting, it was just differences of opinion on technology. It shouldn't really cause anybody to stop contributing. So yes, unless specific instances can be cited where somebody was being particularly abusive, I would err on there being an element of oversensitivity going on. 

@orbea pretty much votes with his time and wallet as far as the project is concerned, I think both him and me are united in our sincerity and drive to see the project improve. We might even share a certain impulsiveness, but none of it should really be all that serious. Users and contributors alike should understand it is about the project, when we point out a mistake or an issue in a PR or commit, the contributor should not feel down or should feel depressed, we appreciate ANY and all contribution. The only reason to point it out is to make it better, but that doesn't mean your efforts are worthless or that we don't appreciate the commit in and of itself.

I hope you guys understand what I mean by this.

**Comment by orbea** [comment]
For the record my way of speaking can be overly blunt and that tends to rub some people the wrong way even when its not intended. I did not mean to offend anyone, but I also do not want to walk on eggshells just in case someone might be offended. Personally I want people to be honest with me and give it to me straight so I try to do that in return. It doesn't always work out, but I can't please everyone...

To further clarify, its "useless" in that compiling redundant code that fills the purpose of an already existing and long working solution is not useful. Not to say the code is useless in itself, but using it in this context when its just going to fall back to `xdg-screensaver` is. Calling it "pointless" in retrospect may of been a little harsh, but my objections that keeping up with dbus upstream and supporting the various different dbus implementations is a heavy burden still stands.

> That's what I though "auto" would be a good compromise as it would only be enabled where it makes sense. 

This is not how the qb configure scripts work. If its set to `auto` the script will use a pkg-config implementation to check for `dbus-1.pc` and if it exists it will be set to `yes`. Given that nearly all distros include dbus by default and that removing dbus from a system without breaking anything is not at all trivial for most users setting it to `auto` is almost the same as setting it to `yes` in this particular case. So no, unfortunately its not only enabled when it makes sense. This is not the fault of anyone here.

Additionally I still am still doubtful this should be set to `auto` when xdg-screensaver works for almost everyone without any controversy. And yes, I strongly suspect there would be a lot of issues claiming it does not work if this was not true. Instead the only one I have personally seen was the original issue that prompted dbus support since xdg-screensaver failed due to a missing xprop dependency.

By all means if you guys want this to work, please make it work! If not then I'm not sure it will go anywhere as everyone else does not have the interest and/or time. All I ask are.

1. xdg-screensaver continues to work.
2. People with the interest in this function stick around to improve and support it.

Also how about wayland? I have not used it and do not know a lot about it. Does `xdg-screensaver` ever work there or is dbus a hard requirement in that case? Does xwayland help here? If its required maybe it should be set to `auto` if wayland is set to `yes`? I can do that much if someone can help me understand why this would or not be needed.

**Comment by twinaphex** [comment]
> For the record my way of speaking can be overly blunt and that tends to rub some people the wrong way even when its not intended. I did not mean to offend anyone, but I also do not want to walk on eggshells just in case someone might be offended. Personally I want people to be honest with me and give it to me straight so I try to do that in return. It doesn't always work out, but I can't please everyone...

Me as a Dutch personally we also have the same mindset, it's better to be direct, no-nonsense and be honest vs. walking on eggshells all the time. Now I know some of my American colleagues usually have issues with this and it can lead to some friction but honestly I feel a lot of time is wasted on basically jumping through hoops and going through some disingenuous song and dance. So yes, I appreciate that more at least are of my persuasion.

**Comment by twinaphex** [comment]
And I also believe that in the end, all that matters is making it work and making sure users are happy. People are welcome to join the project, we are grateful for the contributions, but at the end of the day, code indulgences take a backseat vs. the end product acting and operating as it should be, and I think contributors should be cognizant of that basic reality as well. I am very, very open to whatever can get merged in, but at the same time, I have to walk a fine line between putting it all together and having it all work in a reasonable timeframe so users can still get their releases and be generally satisfied.

**Comment by nguillaumin** [comment]
To get back on topipc: Regarding DBus support, we already had this discussion and I thought we reached a compromise everybody was happy with, so if we could keep it on auto that would be great. I don't like `xdg-screensaver`, but I'm not trying to remove or disable support for it by default.

Regarding it being "broken", it still works fine on my system:

```bash
$ retroarch -v 2>&1 |grep -i dbus
[INFO] [DBus]: Suspended screensaver via DBus.
```

```bash
$ retroarch --version
RetroArch: Frontend for libretro -- v1.6.9Compiler: GCC (7.2.0) 64-bitBuilt: Dec  5 2017
```

As @hadess said it's probably related to your desktop environment that is using a different protocol to inhibit the screensaver. If you could help us in diagnosing the problem by telling us which desktop environment you're using, and running `dbus-monitor --session` that would be awesome. But if you have no interest in this as you claimed, then I think there's still value in keeping it as it still works on Gnome, and quite probably KDE too.

**Comment by orbea** [comment]
Sorry if I was not clear, I do not run a desktop environment. I use a window manager spectrwm, but that should have nothing to do with dbus which is started in `.xinitrc` as shown above.
```
$ dbus-monitor --session
signal time=1513885369.410441 sender=org.freedesktop.DBus -> destination=:1.15 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.15"
signal time=1513885369.410502 sender=org.freedesktop.DBus -> destination=:1.15 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.15"
```

**Comment by nguillaumin** [comment]
Looks like a cool WM. I used Awesome in the past but was put off by the Lua config :wink: 

I think in your case it's just that spectrwm is not interacting with DBus at all, nor it is managing the screensaver, so it just won't work.

With KDE and Gnome (and possibly others like XFCE, LXDE), they directly manage the screensaver (i.e. it's not a separate process) and are connected to DBus. So they listen to DBus, they get a message "screensaver inhibit", and inhibit their internal screensaver.

In your case spectrwm doesn't seem to be listening to DBus as far as I can tell (and I suspect it's considered a "feature" :wink: ), and it's not dealing with screensaver at all either (I suspect you have to run something separately, like xscreensaver perhaps?). `xdg-screensaver` works for you because it know how to talk to xscreensaver directly.

I don't see that as a bug or an issue, it's just that your environment is different so the DBus method won't apply to it. I don't think there's any harm in attempting it though, and my feeling is that Linux desktop users would be mainly using Gnome / KDE / XFCE / LXDE so that would be beneficial to them.

**Comment by nguillaumin** [comment]
As far as I know that should have never worked as `xscreensaver` has no DBus support, so it won't be listening to the bus for inhibition messages. There were a few attempts to add DBus support but they were never merged (and I'm not surprised since the author jwz is notorious for disliking DBus / Gnome :wink:)

It may have worked if you were running something like `gnome-session` or similar on top of your window manager, bit otherwise I can't see how...

**Pull request merged**
