### PR TITLE
Fix some achievements for NES.

### PR DESCRIPTION
**Pull request by leiradel**

### CODE REVIEW

**Comment by meleu** [comment]
Hey guys! I'd love to see these latest @leiradel fixes for retroachievements and the @bparker06 `all_user_control_menu` in the Android version (Google Play).
Is there some other place to make this kind of request?

**Comment by fr500** [comment]
Hopefully a stable will be released within this month.
Honestly you should just use the f-droid packages
(Install f-droid, add https://buildbot.libretro.com/repo/fdroid/repo as a repository)

**Comment by meleu** [comment]
Thanks. I didn't know this tool. So is the RetroArch_GIT.apk a kind of nightly build for android?

**Comment by fr500** [comment]
Yes.. more than the latest commit, it updates several times a day

**Pull request merged**
