### PR TITLE
US Translation: Style changes and more cleanup

### PR DESCRIPTION
**Pull request by im-4-potato**
Still no major wording changes, this PR is mostly about making what is already there more consistent.
- Made all menu items use Title Case (except system libraries)
- Hyphenated a few words (on-screen, built-in, fast-forward, slow-motion)
- Consistent usage of "disc" vs "disk"
- Changed uses of "dir" to "directory"
- Changed "pos." to "position"
- Changed "max" to "maximum"
- Changed "config" to "configuration" where applicable
- Consistent usage of "save state" vs "savestate"
- Consistent usage of "Run-Ahead"
- A few other minor cleanups

### CODE REVIEW

**Comment by WeedyWeedSmoker** [comment]
Actually, I think disk was used for a purpose here, for cores supporting writable disk media, not CD-ROM/DVD…

**Comment by im-4-potato** [comment]
@WeedyWeedSmoker Fixed the triple space, thanks.
As for disc/disk usage, I left in the cases where "disk" was used to refer to writing to internal storage and not a CD. The vast majority of cases that disk had been used previously were not correct, although if you can point out any errors I've introduced here I'd be happy to fix them.

**Comment by WeedyWeedSmoker** [comment]
For udev and zlib, I would have left them as-is, as this is their "branding" to be lowercase…

**Comment by im-4-potato** [comment]
@WeedyWeedSmoker I'm not sure what you mean. They were uppercase previously, my changes make them lowercase, which is the way the official websites refer to them.

**Comment by WeedyWeedSmoker** [comment]
Oh yeah, sorry… I thought it was the other way around!

**Comment by im-4-potato** [comment]
@twinaphex @hizzlekizzle 
This should be ready to merge, I've synced it up with the latest changes from the last 24 hours and just completed another pass of checking for issues. Let me know if there's anything you need me to fix.

**Pull request merged**
