### PR TITLE
(Direct3D) Menu display driver implementation.

### PR DESCRIPTION
**Pull request by aliaspider**
see #5266.

### CODE REVIEW

**Comment by twinaphex** [comment]
Awesome work! This will really start making D3D a viable option in the future.

**Comment by hyarsan** [comment]
"
[INFO] [D3D]: Renderchain driver: null
[INFO] [D3D]: Renderchain driver: null
Segmentation fault
"
D3D doesn't work at all anymore?

Windows 10 64-bit

**Comment by twinaphex** [comment]
Umm, are you compiling with Cg support? D3D to this day still depends on Cg support being baked in.

It works for me.

**Comment by hyarsan** [comment]
I just did whatever
https://bot.libretro.com/.docs/compilation/windows/
said.

**Comment by fr500** [comment]
https://docs.libretro.com/compilation/windows/

```
The NVIDIA CG toolkit package hasn't been updated for a while so you need to download that package manually and install with pacman. You can download the packages from sourceforge at the following locations: 32-bit / 64-bit. Alternatively you can use the following commands directly:
```

**Comment by hyarsan** [comment]
d3d_glui
d3d_xmb

I mean it's not perfect... but it's great!

**Comment by twinaphex** [comment]
It's a very good beginning yeah, and definitely loads bette than what it was before.

I will be excited to see the Direct3D driver finally start becoming a viable video driver for RetroArch that can hold its own against GL, especially if we can figure out a GL interop so we can run libretro GL cores and have them output with D3D. I thnk there are native ways to do that with D3D11 but I am not sure if we could accomplish the same through some extensions (maybe Nvidia-only or maybe they are more generic and vendor-agnostic than that).

**Comment by hyarsan** [comment]
> especially if we can figure out a GL interop so we can run libretro GL cores and have them output with D3D

That's possible? 😲 Pretty cool :P

**Comment by fr500** [comment]
Yes it's called WGL_NV_DX_interop

**Pull request merged**
