### PR TITLE
Updated xcode project and deleted legacy build steps

### PR DESCRIPTION
**Pull request by miguelpinheiro**
Updated the xcode project to the recomended settings by the software
and deleted steps in the build which no longer applied and caused the
build to fail.

### CODE REVIEW

**Comment by twinaphex** [comment]
There are some hardcoded bits related to your name in 'RetroArch.xccheckout'.

Also, we generally want to go with as low Xcode requirements as possible. Is the bump to Xcode 3.2 really necessary? The assets can go though, agreed.

**Comment by miguelpinheiro** [comment]
Sorry, that was xcode bullshit, didn't even notice. Legacy Issues, but I can change it to xcode 3.1, if you prefer

**Comment by twinaphex** [comment]
Yeah, I'd prefer if we sticked as low as possible. 

Also, since you're doing this stuff anyway, maybe you'd like to look into fixing the 'nib' file too? There's an entry called 'Load Core' which is currently greyed out because of some Interface Builder shenanigans - it probably lacks a responder right now.

**Comment by miguelpinheiro** [comment]
I would, but I'm a noob. I only noticed the assets folder error because it's easy to fix. Deleted "RetroArch.xccheckout" with the name issues (it's not needed to build) and reverted to xcode 3.1.

**Pull request merged**
