### PR TITLE
Translate "Applying cheat changes." to all languages

### PR DESCRIPTION
**Pull request by lasers**
I removed my earlier hardcoded English message in "applying cheat changes" section to support all languages... to be translated properly.

### CODE REVIEW

**Comment by Alcaro** [comment]
Maybe add //TODO to the untranslated ones? Otherwise, looks good to me.

**Comment by twinaphex** [comment]
Turn those into C style comments, not C++. This is going to break C89_BUILD.

**Comment by twinaphex** [comment]
I'll manually fix up the comments now, but @lasers, please keep it in mind in the future.

**Comment by twinaphex** [comment]
Whoops, didn't notice you already sent a commit before replying, sorry about that. Thanks for the last commit.

**Pull request merged**
