### PR TITLE
Flag existing cores in the updater

### PR DESCRIPTION
**Pull request by huwpascoe**
## Description
Cores that the user already has are flagged.

## Reviewers
Not familiar enough with project. Will need code review.

### CODE REVIEW

**Comment by fr500** [comment]
What does this achieve in functional terms (screenshot would be preferable)

**Comment by bparker06** [comment]
Why are you opening core info files manually with config_file? There's already a global variable that holds all of them, I think that should be used instead.

**Comment by huwpascoe** [comment]
@fr500 
As shown in this screenshot the cores that are already installed have an asterisk at the front of their name and are sorted to the top of the list.
https://user-images.githubusercontent.com/1812087/53281340-76038700-371e-11e9-9838-a76234bc9518.jpg

@bparker06 
I don't know why, that's the code already present in /master. What's the global variable called?

**Comment by markwkidd** [comment]
Nice!

**Comment by i30817** [comment]
Could be later used to 'update all' in the core downloader.

**Comment by bparker06** [comment]
@huwpascoe The same code you used in menu_networking.c can be used to get the (already populated) core info list.

**Comment by huwpascoe** [comment]
@bparker06 Thanks

I've reduced the changes to just _menu_networking.c_ and extracted the switch statement body into a function. Now it uses core_info_find() to check and retrieve the display name of existing cores.

**Comment by huwpascoe** [comment]
rebased, fixed conflict

**Comment by soredake** [comment]
Any progress on this?

**Comment by huwpascoe** [comment]
(Fixed merge conflict)

@soredake it's ready to merge, someone just gotta hit that button!

**Comment by markwkidd** [comment]
@hunterk I'm not able to be around much but I get notifications about this PR. Is anyone in RetroArch HQ tracking it?

**Comment by soredake** [comment]
@twinaphex why revert?

**Comment by soredake** [comment]
Any progress on this?

**Comment by RobLoach** [comment]
"Update Installed Cores" is in there. This PR was probably reverted because of compat issues, but I'm unsure.

Screenshot at 2020-01-21 08-35-32

**Pull request merged**
