### PR TITLE
remove task_push_http_transfer_raw, encode before sending data to the…

### PR DESCRIPTION
**Pull request by fr500**
… task

This reverts the code to the state it was before the changes and makes the following changes:

- Rename: `net_http_urlencode_full` to `net_http_urlencode` since this function is used to encode individual string members
- Add `net_http_urlencode_full`, this function still needs more work but it's working ok so far, it takes a full URL, splits it up in parts and encodes the non-domain part

The idea is that the task caller would be responsible for encoding, the task assumes the URL is encoded / valid

### CODE REVIEW

**Comment by fr500** [comment]
@leiradel @meleu let me know if everything is still in working order.

I think this is better than having an extra function that serves no purpose other than working around the problem I caused last night.

**Comment by meleu** [comment]
> I think this is better than having an extra function that serves no purpose other than working around the problem I caused last night.

Agreed. I'll be able to test it tonight.

**Comment by meleu** [comment]
I confirm that regarding cheevos this PR is working as expected. :+1:

**Comment by fr500** [comment]
regarding the downloader it seems alright too

**Pull request closed without merging**
