### PR TITLE
Bring back Driver-suffix for driver-strings

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

Currently `MENU_ENUM_LABEL_VALUE_AUDIO_ENABLE` and `MENU_ENUM_LABEL_VALUE_AUDIO_DRIVER` are both "Audio" (just like Video), leading into confusion due to driver selections existing outside driver menu, therefore let's restore the driver strings back to how they were some time ago for proper distinguishing:

retroarch_2021_09_16_21_10_54_019

Or we could of course also keep all drivers in driver menu to avoid this.

### CODE REVIEW

**Comment by twinaphex** [comment]
As part of an accessibility /usability suggestion by some user, we actually made it like this.

As usual, it seems we cannot get everyone to agree on how things should be laid out. Is this really a big issue? What do you think @hizzlekizzle ?

**Comment by sonninnos** [comment]
Not a huge deal, but identical strings for different options do feel a bit clumsy..

#programming-frontend has some discussion.

**Comment by hizzlekizzle** [comment]
Having the driver option show up in the appropriate submenu seems to be pretty popular for usability, so I don't think that would go over well. In this case, I think having `driver > audio driver` is by far preferable to `audio > audio`. That is, overly verbose is better than confusingly vague.

**Comment by RobLoach** [comment]
> I think having driver > audio driver is by far preferable to audio > audio

If we adopt `Drivers > Audio Driver`, that would also imply we would have to adopt...

- `Drivers > Video Driver`
- `Drivers > Input Driver`
- `Drivers > Controller Driver`
- ...etc

This will seem a bit overwhelming and verbose and may bring us to where we were before, but may be the best approach. Alternatively, we could think of another label to use for the first `Audio > Audio`. Perhaps...

- `Audio > Output Audio`
- `Audio > Process Audio`
- `Audio > Audio Processing`
- `Audio > Monitoring`

Screenshot at 2022-01-10 02-16-12

**Comment by sonninnos** [comment]
Sure, I'm down for plan C too, as in adding separate suffix strings for those which are also outside drivers-menu (Video, Audio, Menu), but it will get somewhat messier..

**Pull request closed without merging**
