### PR TITLE
add mouse relative check and set appropiatley to fix issue

### PR DESCRIPTION
**Pull request by grant2258**
The old code was traced and it returned zero values. The relative check was added to make the code clear and its a mouse as well. This should put the issue to sleep. Will test on the pi at the weekend cant see there being any issues.

@jdgleaver  @twinaphex  @bozothegeek

### CODE REVIEW

**Comment by grant2258** [comment]
This has been tested in x and kms with ./configure --disable-discord --disable-qt --disable-cdrom --disable-x11 --disable-caca --disable-sdl --disable-sdl2 --disable-opengl1 --disable-ffmpeg --disable-flac --disable-wayland --enable-kms --enable-opengl --enable-vulkan

**Comment by i30817** [comment]
What will this do? Fix restricted mouse areas in cores like puae and scummvm?

**Comment by grant2258** [comment]
It would be nice to clarify something though.

https://github.com/libretro/RetroArch/blob/12f787547c7728a0efb5d68a07c07dbcdf52802c/input/drivers/udev_input.c#L367-L435

the pointer and lightgun use this.

Now correct me if im wrong the pointer and lightgun should be absolute devices yet its falling back to relative if its not abs should we really be doing this that my only confusion on this matter.

@ i30817 
unfortunately my touchpad is toast but I can still test. If you try this and you still have them issues please open another issue with details of how to reproduce the issue and ill certainly try take a look if I can do anything or at least trace the issue to give you some clarification.

**Comment by i30817** [comment]
It happens in all cores that need a computer mouse and you're using a touchpad. PUAE, or scummvm for instance.

The area where the touchpad can operate doesn't fill in the whole game screen or is offset from the center. The weird part is that that area can change so if you frenetically push back and forwards along a axis you sometimes can 'drag' that area to other parts of the screen.

It's unusable. But i don't see anyone else complaining so i assume it only doesn't work in linux and every user is on windows or something.

**Comment by grant2258** [comment]
@i30817 the udev input driver is what this applies too. Change that to udev. I'm going  to get a laptop hopefully today I need to test some things there are two issues. I need to check properly.

**Comment by grant2258** [comment]
There are still some issues in this driver that will need more time. The hotplug  add remove isint setting /setting removing mouse names and touchpad devices are starting at zero as they are called separately from mice obviously static wasnt the way to fix it since its called more than once and it was only originally added for logging now it setting the name for ra it will need fixed.

[INFO] [udev]: Keyboard #0: "Power Button" (/dev/input/event3).
[INFO] [udev]: Keyboard #1: "Video Bus" (/dev/input/event6).
[INFO] [udev]: Keyboard #2: "Acer Wireless Radio Control" (/dev/input/event5).
[INFO] [udev]: Keyboard #3: "Power Button" (/dev/input/event0).
[INFO] [udev]: Keyboard #4: "Sleep Button" (/dev/input/event1).
[INFO] [udev]: Keyboard #5: "HD User Facing: HD User Facing" (/dev/input/event13).
[INFO] [udev]: Keyboard #6: "AT Translated Set 2 keyboard" (/dev/input/event4).
[INFO] [udev]: Keyboard #7: "Acer WMI hotkeys" (/dev/input/event12).
[INFO] [udev] REL MOUSE
[INFO] [udev]: Mouse #0: "ELAN050A:00 04F3:3158 Mouse" (/dev/input/event7).
[INFO] [udev] ABS MOUSE
[INFO] [udev]: Mouse #0: "ELAN050A:00 04F3:3158 Touchpad" (/dev/input/event8).

**Comment by grant2258** [comment]
@jdgleaver  @twinaphex  the code is complete now. The hotplug will add names now and a relative check. Sorry it took so long have been really busy with work.

**Comment by twinaphex** [comment]
OK, we'll merge as is. I will be doing some style nits later on but nothing that will affect anything on a fundamental level. Thanks for all your efforts.

**Pull request merged**
