### PR TITLE
Add EmojiActive Theme.

### PR DESCRIPTION
**Pull request by Tatsuya79**
[Assets have been added there already.](https://github.com/libretro/retroarch-assets/pull/213)

### CODE REVIEW

**Comment by RobLoach** [comment]
@777sha It's a beautiful theme, and I'm sure there could be a way to package it. Could we be considered a Open Source App?

Considering how many different projects we package, just want to be careful and respectful of everyone's wishes.

**Comment by RobLoach** [comment]
Keep your own project in place though... Would be cool to make RetroArch "discover" the themes that you have installed. Then you could just download from your project, and select it in the menu.

**Comment by Tatsuya79** [comment]
Yes, instead of "Custom", having the themes list be whatever folders are inside assets\xmb.
We won't have to them in the menu code each time too.
The limitation is about stuff you add sometimes like gradients.

**Comment by Tatsuya79** [comment]
closing it then

**Pull request closed without merging**
