### PR TITLE
Support libctru 1.6

### PR DESCRIPTION
**Pull request by justinweiss**
## Description

This is probably missing some things, but it gets RetroArch to build and run under the current version of devkitARM.

Not all of the cores build yet. I was able to get pcsx_rearmed to build with the current devkitARM with only a few changes, though.

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
is this going to require updating the buildchain on the buildbot server? If so, there are probably a few other people that need to give their go-ahead.

**Comment by justinweiss** [comment]
Yes, this was backed out of a different PR (#9488). In that patch, @jdgleaver mentioned:

> Now the only issue is the libctru 1.6 support. Updating the devkitARM toolchain is not a task we can undertake lightly - it needs every core to be built and checked on o3DS/n3DS, including performance profiling, regression testing, etc. We don't have the time or manpower for this.

So this PR has the changes in the event someone wanted to push it through.

I think I still have a patch for pcsx_rearmed lying around as well, although I didn't try many cores besides that.

**Comment by ofry** [comment]
@justinweiss This PR has conflicts. Please resolve them.

**Comment by justinweiss** [comment]
@ofry Is this something that's being considered for a merge? I've been holding off putting more work into it until it's planned to move forward.

**Comment by twinaphex** [comment]
Well, we'd have to coordinate with @jdgleaver to see if it has regressions in cores and then it would also have to be deployed on the buildbot, so it's not a trivial thing. I'm willing to consider it but you'll have to do your part too in order for us to be able to do our stuff in terms of the buildbot and testing of the cores.

**Comment by justinweiss** [comment]
@twinaphex OK, that's where I thought we were at (and is 100% reasonable). I don't think getting this in is urgent. I was just curious why it was bumped.

**Comment by justinweiss** [comment]
Closing in favor of #11248

**Pull request closed without merging**
