### PR TITLE
(Buildfix) iOS 6 & 8 + iOS projects fixes

### PR DESCRIPTION
**Pull request by WeedyWeedSmoker**
## Description

Various fixes for iOS compilation and jailbroken installation

## Reviewers

@twinaphex

### CODE REVIEW

**Comment by WeedyWeedSmoker** [comment]
@twinaphex There is something strange on the buildbot, iOS and iOS 9 versions of xrick (Rick Dangerous) are compiled for OS X x64, not iOS...

**Comment by WeedyWeedSmoker** [comment]
@twinaphex I may be wrong for the iOS static projects with the `"-DHAVE_DYNAMIC"` option, if you could clarify that...

**Comment by twinaphex** [comment]
HAVE_DYNAMIC should not be used for the statically linked xcodeprojs. The entire point there is to link a statically linked libretro core against it that you supply yourself. It is not supposed to link cores dynamically.

**Comment by WeedyWeedSmoker** [comment]
Ok, thanks for the clarification ! Fixed...

**Pull request merged**
