### PR TITLE
Re-enable RXML and purge libxml

### PR DESCRIPTION
**Pull request by huwpascoe**
Fixed rxml to work with griffin.c

## Related Issues
https://github.com/libretro/RetroArch/issues/7419

### CODE REVIEW

**Comment by orbea** [comment]
Would you mind elaborating more on the point of this PR? What is libxml2 even used for in RetroArch?

**Comment by huwpascoe** [comment]
libxml2 isn't used for anything, it's been commented out.
rxml is needed for the linked issue.

**Comment by orbea** [comment]
Rather, why was libxml added in the first place?

**Comment by huwpascoe** [comment]
I think maybe it was for opengl xml shaders or something like that?

**Comment by orbea** [comment]
Sounds plausible, thanks for satisfying my curiosity.

**Comment by markwkidd** [comment]
GLSL XML shaders I guess? https://docs.libretro.com/development/shader/xml-shaders/

**Comment by orbea** [comment]
Just for reference that page says.

> XML shaders as a whole are deprecated in RetroArch, and will not be selectable in RGUI. You can still use them via video_shader config option. To use GLSL in RetroArch, the new GLSL shaders format is used, which mirrors the Cg shaders implementation quite well. The new GLSL shaders only support modern style, no fixed function. To convert XML shaders into straight GLSL, see GLSL shaders. 

@hizzlekizzle Is it worth supporting XML shaders anymore? I imagine most shaders have been converted for glsl and slang by now?

**Comment by hizzlekizzle** [comment]
@orbea No, zero point AFAIK. I'm not sure if the "game-aware" shader functionality was ever added to the modern shader backends, but they were only ever proofs of concept anyway.

**Comment by grant2258** [comment]
expat https://libexpat.github.io/ is an easy to use lib and only a few files too add

**Comment by huwpascoe** [comment]
I'm not going to be dealing with expat, sorry. This is just for https://github.com/libretro/RetroArch/issues/7419 if someone else wants to improve xml support later they can.

**Pull request merged**
