### PR TITLE
Unify timedate ENUMs and formatting

### PR DESCRIPTION
**Pull request by im4potato**
## Description
Previously, there were two sets of ENUMs for date and time, one used for `Settings > User Interface > Views > Style of Date and Time` and the other for `Settings > Playlists > Playlist Sub-Label Runtime 'Last Played' Format` that contained identical entries (although a there were a few more for `Style of Date and Time` that only made sense there). This PR removes all of the ENUMs that were only used for the `Last Played` strings so that they all get their values from the same place, and renames the rest of them to make them more generic.

I also unified the style of the date and time, for example, changing `YYYY-MM-DD HH:MM:SS` to `YYYY/MM/DD HH:MM:SS` in the few places where they didn't match. This is the only change in this PR that's visible to the user.

Overall, this PR removes redundant entries and makes all of the date and time output consistent.

## Reviewers
@hizzlekizzle

### CODE REVIEW

**Comment by Ryunam** [comment]
There is one simple drawback to this, which may not even be an issue but I’m going to mention it anyway: simply put, the previous configuration made it so that users could set two different timedate styles - if they wanted - for the two respective timedate options. So you could have the current date and time displayed in a certain format in the Menu, while only having month/day hour:minutes (for instance) for the runtime log.

This makes it impossible to differentiate the two styles. Again, it might not be an essential thing and in fact the point here is indeed to unify, but this is potentially removing an element of customization that may be desirable to some.

**Comment by im-4-potato** [comment]
@Ryunam I'm not entirely sure what you mean, those two settings still exist independently. If you go to each setting you can set them to different values and that works the same way it always has. The change I've made here just makes them pull from the same set of values to generate the menu options.

**Comment by Ryunam** [comment]
Oh, if that’s the case it’s all good as far as that aspect is concerned. I had mistakenly interpreted the changes.

**Comment by Sanaki** [comment]
I'd warn against specifically removing YYYY-MM-DD, since changing that to YYYY/MM/DD breaks ISO8601 compliance. Just a minor detail, but it still seems like a mistake.

**Comment by im4potato** [comment]
Is it `YYYY/MM/DD` specifically, or any date format that uses `/` instead of `-`? I'm not familiar with the limitations of ISO8601. There were other date formats before that already used `/`.

**Comment by Sanaki** [comment]
It's not a question of it working correctly. ISO8601 is a standard for universal international date and time formats. The basic format is `YYYY-MM-DD`, with no deviation. In display, it's merely a nitpick. In writing files, it's more of an issue due to the potential for conflicts with outside tools. The full format would be `2020-05-07T02:47:20+00:00`.

Honestly, just adding an extra option for YYYY-MM-DD next to YYYY/MM/DD would satisfy me personally, but I'm not sure others would see the merit in that.

**Comment by im4potato** [comment]
I'd rather not clutter up the date and time options even more than they already are. My preference from a visual standpoint would be to keep `/` over `-`, but that's subjective. If there is a technical reason that we shouldn't do that, then so be it, I can change them all to `-`. I will point out that even before this PR, many of the date and time settings were already using `/`, so that didn't appear to be an issue.

To me, the most important thing is to have consistent options, so getting some feedback from the more knowledgeable contributors would be helpful here. If that part needs to be reverted I can take care of that.
@twinaphex @hizzlekizzle

**Comment by sonninnos** [comment]
As a side note: I'm personally comfortable with ISO, but it would be nice to have "DD.MM.YYYY" as an option too. Or instead of piling on the available options maybe a way to pick the format straight from the OS or something.

**Comment by Sanaki** [comment]
Barring adding a secondary option to pick the divider, I'm not really sure how to accomplish versatility and simplicity at the same time.

**Comment by Ryunam** [comment]
Personally I would rather not change DD/MM/YYYY by replacing / with -. I had added that format specifically because, at least where I live (Italy), it is the most commonly used method of writing the current date, even in official forms and all sorts of documents.

**Comment by im4potato** [comment]
`/` is much more common than `-` in the US as well.

**Comment by hizzlekizzle** [comment]
The / vs - was a concern for me, as well, for compatibility reasons. Perhaps twinaphex has some insight on how it would affect things.

**Comment by im4potato** [comment]
I see that some other recent changes require me to fix up this PR. Can we reach a consensus on what the proper format should be so that I can make the necessary changes and get this merged?
@twinaphex @hizzlekizzle

**Comment by Sanaki** [comment]
Honestly, Retroarch natively supporting ISO8601 formatting made me ridiculously happy when I first set it up. If that's removed, I'll probably open an issue asking for it to be added back. The standard is designed the way it is for a reason. Slashes are preferred in writing because they're an easier stroke to make, but visually dashes are easier to distinguish. That aside, the only compatibility issue I could see happening on a display-only value would be for screen readers, since they should be the only things using that as input.

**Comment by im4potato** [comment]
I'd be happy to keep it ISO8601 compliant if that's what people want, as I said previously, I just want consistency.

**Comment by Ryunam** [comment]
If I may, I would suggest this course of action to possibly achieve a good result that preserves consistency and user personalization:

1) Create a new option named "Date Separator" (or any other appropriate name of course) in Settings -> User Interface -> Views, that only appears if Settings -> User Interface -> "Show Advanced Settings" is set to ON. This could have the following values, based on what was suggested here:

- `- (ISO8601-compliant)` (this could be the default value)
- `/`
- `.`

2) Duplicate the timedate view modes and make new `strftime` calls for each separator that the user may want to set.

Of course this would mean extending the code further, which seems to be against the point that @im4potato was making about de-cluttering it all, but I for one would greatly prefer the `/` separator from a purely visual standpoint, so maybe it's appropriate to offer more options for customization and leave the ISO8601-compliant as the default setting. What do you think?

**Comment by im4potato** [comment]
@Ryunam I've got no issues with that proposal, I don't mind additional code or settings as long as they actually serve a purpose. Though I must admit, I'm not too familiar with adding new settings to RetroArch, so that's something I would have to study up on before I was capable of adding this. I will work on implementing this, but I might need help.

**Comment by im4potato** [comment]
My lack of git knowledge is really showing here, I'm not sure how to sync up my changes with the latest RetroArch code, I've tried merging, I've tried rebasing, but I just can't figure it out. I will close this PR and open a new one that should be synced up with the latest code.

**Comment by twinaphex** [comment]
Sounds good, looking forward to it.

**Pull request closed without merging**
