### PR TITLE
Fix ram states to file when core deinit

### PR DESCRIPTION
**Pull request by bulzipke**
## Description
 Removed `state_data_on_ram` from ctr_common.h
 -> Set flag for write file on `ram_save_state_buf`'s `to_write_file`

 Call `CMD_EVENT_RAM_STATE_TO_FILE` when `CMD_EVENT_CORE_DEINIT`
 -> This should also be called when using ram_state on other platforms.

## Related Issues
https://github.com/libretro/RetroArch/issues/12950

## Reviewers
@MrHuu 
@jdgleaver

### CODE REVIEW

**Comment by twinaphex** [comment]
Yeah, a couple of things here for future reference - 

we eventually need to move out anything unrelated to actual rendering of graphics outside of the video driver. Mixing it up with save state logic and whatnot is a dangerous road to be crossing as we have not done that before with any other driver and pretty soon other coders could decide to base decisions on this. So we definitely need to have some intermediary layer at some point outside of the video driver for this kind of stuff. For now we can see how it goes, as long as it's clearly understood by everyone that we do not want this going on for other video drivers as a future reference.

**Comment by twinaphex** [comment]
I see the current PR is a step in the right direction there so I'll merge it. I will be cleaning up some other stuff in ctr_gfx.c that is currently bugging me - using C comments instead of C++ comments, making sure variables are declared at the top of a function or code block, some indentation issues ,etc. But I can do that myself. Hopefully people can follow in those footsteps from now on.

**Comment by bulzipke** [comment]
@twinaphex 
This is what @MrHuu  has already mentioned. (https://github.com/libretro/RetroArch/pull/12470#issuecomment-874986666)
I'm sorry about the technology debt I made. I will pay attention to future PR.

I thought about what ram-states-save could be used on all platforms and revised this time.
I implemented it in lid closing or home buttons with 3DS, but other platforms may need additional implementation.
Also, need to test on a old platform with insufficient RAM.

**Comment by jdgleaver** [comment]
@bulzipke Thanks for this. In addition to twinaphex's comments, I see just a few small issues:

- You added `CMD_EVENT_RAM_STATE_TO_FILE` to `CMD_EVENT_CORE_DEINIT`. This also needs to be added to `CMD_EVENT_UNLOAD_CORE` (since either code path may be used depending on how the core exits)
- Remember that `char state_path[PATH_MAX_LENGTH];` must always be NUL terminated before using it in `retroarch_get_current_savestate_path()` (this is only strictly required when you don't check the return value of `retroarch_get_current_savestate_path()`, as in `/ctr_gfx.c:save_state_to_file()`, but it's good practice to do it everywhere)
- Rather than calling the (somewhat expensive) `retroarch_get_current_savestate_path()` function by default in `CMD_EVENT_CORE_DEINIT`/`CMD_EVENT_UNLOAD_CORE`, I think it would be nice/more efficient to add a `content_ram_state_pending()` function to `content.h`/`task_save.c` which just returns the value of `ram_buf.to_write_file`. Then you only have to do additional work if this is true, i.e.:

```c
if (content_ram_state_pending())
{
    char state_path[PATH_MAX_LENGTH];
    state_path[0] = '\0';

   /* The platform that uses ram_state_save calls it when the content
    * ends and writes it to a file */
   if (retroarch_get_current_savestate_path(state_path, sizeof(state_path)))
      command_event(CMD_EVENT_RAM_STATE_TO_FILE, state_path);
}
```

**Comment by bulzipke** [comment]
@jdgleaver 
I fixed it as you suggested.
Thank you for the review !

**Comment by jdgleaver** [comment]
@bulzipke Thanks! This all looks fine now :)

**Comment by MrHuu** [comment]
Great job, not only fixing the issue mentioned but also moving the function out of the graphics driver.

I'm very much aware of the issue @twinaphex mentioned about the non gfx logic ran each frame.

The code for saving, input handling and probably even rendering the bottom screen should be separated from the main gfx (topscreen) driver.

While during runtime the impact is minimal, is does affect performance.
For example: When initially starting a core with a rom, loading the savestate information from sd may cause the rendering to hold until the information is loaded. Resulting in delayed rendering for the topscreen, sometimes even after the initial gfx_widgets have starting to 'fade out'.

The bottom screen does not have to run in sync with the topscreen, so it can have it's own function for rendering, invoked when necessary. This allows us to have every benefit from the threaded main gfx driver, with the bottom screen rendering handled by either the main thread or even maybe it's own thread.

This is a good step in the right direction. 

Also, @twinaphex please do make the changes to have the code styled and implemented in a way you want to keep forward. I personally have to very much rely on existing implementations of functions for either 3ds or any other platform, usually adapting or re-implementing existing functions. For me this would really help with contributing properly formatted and maintainable code.

All the efforts made here are greatly appreciated, thanks everyone!

**Pull request merged**
