### PR TITLE
Added Turkish Lanugage

### PR DESCRIPTION
**Pull request by fpscan**
Based on Libretro Adding Language docs, I translated most of text based on msg_us.h file and check, I had a couple issue but Orbea helped me a lot, I will keep translate, for now I assume it's okay. I also followed Pull request docs before I request. Looking forward to see this live!

image

### CODE REVIEW

**Comment by fpscan** [comment]
> Hi @fpscan,
> 
> We cannot accept this PR as there are several problems with it. First, all of your line endings are in Windows format, and there are several unrelated pieces of code seemingly removed at random. I'll just take your .c/.h files and add it myself in a separate commit since I know you're ready to get this over with.

That would be great and I would be happy to work on something really work, so I can focus on translating stuff, so when I would be able to make new translates? Thank you for your help!

**Comment by bparker06** [comment]
I have added your translation to the current master branch in d8968d8d0ba366c2d121c8fe4047cc1f7b2e73cb now.

**Comment by orbea** [comment]
@bparker06 Can you fix the documentation issue in issue https://github.com/libretro/RetroArch/issues/8584?

**Comment by bparker06** [comment]
@orbea done

**Comment by orbea** [comment]
Thanks, I appreciate it!

**Comment by fpscan** [comment]
I would like to thank you both of you guys, I just updated my RA nightly and I saw Turkish language option in settings, this is important... So thank you both of you for your patience and support!

**Pull request closed without merging**
