### PR TITLE
Add Miyoo target

### PR DESCRIPTION
**Pull request by salvacam**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description
This is to add the Miyoo firmware supported devices to retroarch. Works on New BittBoy, Pocket Go and PowKiddy Q90-V90-Q20 consoles.
I have only been able to test on the powkiddy V90, maybe for others the buttons B and A and X and Y are reversed

Miyoo is a custom firmware running on the allwinner f1c100s CPU which is around 50% the speed compared to the devices running Opendingux
[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by salvacam** [comment]
configure toolchain
extract toolchain.7z into /opt/miyoo
https://github.com/steward-fu/miyoo/releases/download/v1.0/toolchain.7z

export command
export PATH=$PATH:/opt/miyoo/bin

**Comment by jdgleaver** [comment]
@salvacam Here is the patch, as promised: [miyoo.patch.zip](https://github.com/libretro/RetroArch/files/7083267/miyoo.patch.zip)

This does the following:

- `sdl_dingux_gfx.c`: Consolidate platform-specific surface flags
- `sdl_dingux_joypad.c`: Consolidate platform-specific key maps and re-enable menu key on miyoo devices (I assume the latter is wanted, since you specify a key for it?)
- `Makefile.miyoo`: A few clean-ups, re-enable command line override of toolchain-related variables, enable stripping of output binary
- All: Remove miyoo-specific `#include "SDL/SDL.h"` references (you already pass the correct include directory - you only need `#include "SDL.h"`, same as all other platforms)

Please apply this onto of your PR, and check that everything is okay. Then squash your commits, and we should be able to merge this :)

One other thing - I see that you're not using OPK files on miyoo (I guess they are unsupported?). This is absolutely fine, but before we can add the miyoo build to our buildbot, you will need to explain exactly how the files should be packaged (directory structure, launcher scripts, etc. - we can't just ship a binary!)

**Comment by salvacam** [comment]
Miyoo does not support OPK files. You only need to run the binary a text file that creates the link on the frontend you use, GMENU2X.
I include a compressed file, with the binary, and the link of gmenu2x. You have to unzip in the Q90 partition, if you are using stock firmware, or in the main partition, if you use cfw, you have to unzip the contents of the file.
[retroarch_Miyoo_2021-09-01.zip](https://github.com/libretro/RetroArch/files/7093028/retroarch_Miyoo_2021-09-01.zip)

I have tested that when executing for the first time, all the necessary file structure for retroarch is created, in a hidden folder, .retroarch, in the root of the Q90 partition, if you are using the stock firmware, or in the main partition, if you use the custom firmware.

I include all the cores that I have been wearing.
[cores.zip](https://github.com/libretro/RetroArch/files/7093064/cores.zip)

I have used the Poligraf changes, but I see that the emulators are scaled. I have tried to use the sdl driver and scale but it is very slow, and the controls do not recognize them well. We will have to modify the graphics driver, sdl_dingux_gfx.c, or create a new one for these consoles

**Comment by jdgleaver** [comment]
@salvacam 

(I should probably first mention that I do not own any devices that run Miyoo, so I cannot actually test anything myself...)

> I include a compressed file, with the binary, and the link of gmenu2x. You have to unzip in the Q90 partition, if you are using stock firmware, or in the main partition, if you use cfw, you have to unzip the contents of the file.
retroarch_Miyoo_2021-09-01.zip

Thanks - that layout is fine, and we can recreate that on the buildbot without issue

> I have tested that when executing for the first time, all the necessary file structure for retroarch is created, in a hidden folder, .retroarch, in the root of the Q90 partition, if you are using the stock firmware, or in the main partition, if you use the custom firmware.

We will still need to distribute a `.retroarch` folder, since the file structure generated by the binary is empty - i.e. the user needs cores, core info files, assets, etc.

> I have used the Poligraf changes, but I see that the emulators are scaled. I have tried to use the sdl driver and scale but it is very slow, and the controls do not recognize them well. We will have to modify the graphics driver, sdl_dingux_gfx.c, or create a new one for these consoles

Yes, the regular sdl driver cannot be used on these handhelds.

As for the rest, I'm afraid I don't quite understand what you are saying:

`see that the emulators are scaled` - what does this mean? How are they scaled? Do you mean that they are integer scaled? Do these devices not have a hardware IPU? If this is what you mean, then yes - you will need a new gfx driver just like `sdl_rs90_gfx.c` which performs some software scaling to the device's native resolution.

`the controls do not recognize them well` - what does this mean? Are you saying that controls do not work properly in general...? Or are you talking about using the regular sdl input/joypad driver? You shouldn't be using anything other than `sdl_dingux_joypad.c` on these devices.

If there are scaling/control issues, then it sounds like this PR is in fact WIP. These issues should be resolved before we publicly release any binaries.

**Comment by salvacam** [comment]
@jdgleaver 
Sorry for taking time to answer.

Do not explain me well, using the same driver that RetroFW uses, sdl_dingux_gfx.c, the controls work correctly, but some cores look very small. You can see in this video how the core of Game Gear is shown, [https://youtu.be/XflXU0VNVdc?t=440](url)

I have tried to implement the same scaling that I have used in other emulators, [https://github.com/salvacam/sz81-miyoo/commit/988c581ed7b3b576c01b5e46d88e9113547ab299](url)
in that commit in the sdl_video.c file I use the SDL_SoftStretch function so that they occupy the whole screen, but using it in the sdl_dingux_gfx file I only get it to be seen in the upper left corner, at the same size.

I know of no other way to get on these consoles. 
Maybe using the SDL_SoftStretch function as in the commit that I have shown you is the correct way but I am not using it in the right place.

**Comment by jdgleaver** [comment]
@salvacam Okay, I understand the issue :)

The Miyoo hardware has no IPU support, so the `sdl_dingux_gfx.c` gfx driver is not the best choice here (it is explicitly designed to leverage hardware IPU scaling for the best possible image quality).

The `SDL_SoftStretch()` function will not work here - it needs a software surface, it is slow, and not very good quality.

You are dealing with the same hardware restrictions that affect the RS-90 - and so I think you would be better off using the `sdl_rs90_gfx.c` gfx driver (we may end up renaming this for use on any 'dingux-type' device that has no IPU). I believe the only thing you need to change are the two values here: https://github.com/libretro/RetroArch/blob/f587d28a0d0c27afcdba6cfdae84ce2219d7d0b7/gfx/drivers/sdl_rs90_gfx.c#L54-L55 (i.e. hardcode the correct resolution of 320x240). This driver will give you several software scaling options: integer, nearest neighbour, bresenham.

Could you please test this driver, and see if it produces acceptable results?

**Comment by salvacam** [comment]
I have tried the RS90 driver, the scaling is fine but the menu is not visible
IMG_20210921_171615
IMG_20210921_171655

I have to see why it does not display well, but I think it is better to use the sdl_rs90_gfx.c driver than the sdl_dingux_gfx.c
After the menu is displayed correctly, I will upload the changes and check that all the controls work.

I'll keep you informed

**Comment by jdgleaver** [comment]
Oh, this is great! Good job :)

**Comment by ofry** [comment]
@salvacam There are merge conflicts.

**Comment by salvacam** [comment]
With the RS90 driver scaling works well, some systems work well with some cores. I show you a video of Master System, Nintendo Nes, Game Boy and Scummvm.
https://www.youtube.com/watch?v=TwGANgjeLMU&ab_channel=Salvacam
I have compiled many more cores over about 30 but not all of them work well.

With the last commit is giving conflict when merging, the last two commits are not necessary. This is the last commit
https://github.com/salvacam/RetroArch/commit/9b39c0b8f210cafae13861d6fa2348a1660883f6
what do you need to merge.

I don't know how to resolve conflicts without permissions in the libretro repository

**Comment by jdgleaver** [comment]
@salvacam You will need to fix the conflicts before we can merge. You don't need any libretro repo access to do this.

Firstly, you need to squash your commits:

```
git checkout miyoo
git rebase -i HEAD~10
```
In the editor that opens, 'pick' the first commit and set all the rest to 'fixup' - like this:

```
pick 221b39cb88 add miyoo target
fixup be217eb626 add miyoo target
fixup 51cd9b2532 add miyoo target
fixup 97ca80842f add miyoo target
fixup d86a0e8054 fix path sdl
fixup 4c0c3e65bd fix comment
fixup ceb938a269 use RS90 driver
fixup 9b39c0b8f2 use RS90 driver
fixup c3920baa99 fix menu scaling
fixup 7fba7e8a8e revert fix menu scaling

# Rebase 9000e81498..7fba7e8a8e onto 9b39c0b8f2 (10 commands)
```

When you exit the editor and save, you will end up with a single commit. Now you can rebase:

```
git checkout master
git pull upstream master
git push origin master
git checkout miyoo
git rebase master
```

This will produce conflicts in `config.def.h` and `retroarch_data.h`. Open these file in a text editor and search for `>>>>>>>`. You will see that `config.def.h` is trivial to fix, whereas in the case of `retroarch_data.h` the line you need to edit has moved to `gfx/video_driver.c`. Once you have updated `config.def.h`, `retroarch_data.h` and `gfx/video_driver.c`, do the following:

```
git add config.def.h retroarch_data.h gfx/video_driver.c
git rebase --continue
```

Your local branch will then be rebased. You can push this to github by doing:

```
git push --force origin miyoo
```

Finally, there are a couple of other things that need to be resolved:

- You should implement the 'surface_flags' in `gfx/drivers/sdl_rs90_gfx.c` in the same way as `gfx/drivers/sdl_dingux_gfx.c`, so the additional `#if defined(MIYOO)` is only needed in one place
- The Miyoo target does not use `gfx/drivers/sdl_dingux_gfx.c`, so the changes to this file should be reverted

Once you have made these last changes, squash your commits again and force push - then we should be ready for a final (quick) review and merge.

**Comment by ofry** [comment]
@jdgleaver

**Comment by jdgleaver** [comment]
@salvacam Thank you, this is great. We are ready to merge now. I will let you know once I have things set up on the buildbot :)

**Comment by jdgleaver** [comment]
@salvacam Miyoo builds are now available on the buildbot: https://buildbot.libretro.com/nightly/dingux/miyoo-arm32/

Could you please test and confirm that the installation package is okay?

You can now PR any other cores that you like. Note that when updating a core, you'll also need to edit the `.gitlab-ci.yml` file as I have done here: https://github.com/libretro/QuickNES_Core/pull/88/files (this creates the build job on the build server)

Also, cores that need cmake are not supported yet (this needs some more setup on the server, so if you want any of these we can sort them out later). All cores that just use the regular makefiles will be fine, though.

**Comment by salvacam** [comment]
@jdgleaver Hi, the installation package for Miyoo does not work, the retroarch folder must be hidden. If the folder is renamed to .retroarch it works fine.

Tomorrow I will try more core that I have ported and I will do PR of those that go well

**Comment by salvacam** [comment]
@jdgleaver 
Close the last pull request and open this https://github.com/libretro/RetroArch/pull/13092/files

**Pull request merged**
