### PR TITLE
Reorganize Quick Menu items

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

The diff is somewhat messy, but bear with me. Goal is to shuffle the items around to reduce scrolling needs by moving most often used to top, and related items more next to each other.

Same order is reflected in "Menu Item Visibility" list and `msg_hash_us.h`.

Changes:
- Optional submenu for Save States (disabled by default)
- Renamed "Options" to "Core Options" (option manager already calls it that)
- Moved "Options", "Controls" and "Disc Control" to top after Save States
- Moved "Take Screenshot" over "Start Recording"
- Removed "Download Thumbnails" when content is running
- Edited sublabels of visibility items that exist only when content is not running to reflect that
- "Information" is kept as the last item in both menus
- Rationale with the bottom items are so that items below "Overrides" are saved separately and thus are not part of overrides, and items before that and after "Add to Favorites" are part of overrides, since they are shortcuts to global settings

Suggestions/complaints welcome!

retroarch_2022_04_07_14_12_19_092

retroarch_2022_04_09_22_01_17_927

retroarch_2022_04_09_22_01_24_267

### CODE REVIEW

**Comment by realnc** [comment]
I believe the restart and close content entries should be at the very bottom. This would be in line with pretty much every application out there (File->Quit is usually the last entry in the menu of every application.)

As of putting the most used options at the top and bottom, that doesn't work out. This increases the distance of the commonly used options a lot. They should be packed together closely. So most commonly used should come first.

**Comment by sonninnos** [comment]
Updated and adjusted.

**Comment by Psithief** [comment]
> I believe the restart and close content entries should be at the very bottom. This would be in line with pretty much every application out there (File->Quit is usually the last entry in the menu of every application.)

I can't agree with equating "Close Content" with "Quit RetroArch", and "Restart" is equivalent to "Quit to Menu" for many titles. These are the most important and frequently-used commands. A typical console has a restart/power button and an eject button, and I'd expect them to be on the *front* of the console for easy access, not the back. The menu has them in the correct place as it is.

**Comment by realnc** [comment]
> > I believe the restart and close content entries should be at the very bottom. This would be in line with pretty much every application out there (File->Quit is usually the last entry in the menu of every application.)
> 
> I can't agree with equating "Close Content" with "Quit RetroArch", and "Restart" is equivalent to "Quit to Menu" for many titles. These are the most important and frequently-used commands. A typical console has a restart/power button and an eject button, and I'd expect them to be on the _front_ of the console for easy access, not the back.

You still expect them to be on the console though, not on the gamepad. Anyway, these are just personal opinions. There is no objective answer here.

**Comment by sonninnos** [comment]
Final issue with XMB finally sorted, thus removing draft state.

**Comment by i30817** [comment]
If you're still messing around with the menus @sonninnos, the manage playlists always bothered me to not have a way to download thumbnails enmasse for a single playlist.
, s
In fact that option doesn't exist anywhere, so i had to make it (and add a fuzzy match feature, among others) [in this application.](https://github.com/i30817/libretrofuzz)

**Comment by sonninnos** [comment]
Please no unrelated noise to the thread. Rather create issues about other things.

**Comment by sonninnos** [comment]
No opinions on the current order?

**Comment by hizzlekizzle** [comment]
> Rationale with the bottom items are so that items below "Overrides" are saved separately and thus are not part of overrides, and items before that and after "Add to Favorites" are part of overrides, since they are shortcuts to global settings

This just sunk in for me. Very smart idea.

**Comment by realnc** [comment]
> No opinions on the current order?

Well, you didn't reply to the opinions that were posted.

**Comment by sonninnos** [comment]
Moving Restart and Close Content to bottom would be outright rejected, and the rest don't apply anymore.

**Comment by sonninnos** [comment]
Conflict resolved.

**Comment by jdgleaver** [comment]
@twinaphex This should be ready to merge now...

 (it's been left ignored here for too long, I think....)

**Pull request merged**
