### PR TITLE
(cheevos) show message when trying to load state in hardcore

### LINKED ISSUE #13469: (Cheevos) When Hardcore Mode is enabled, display a Load State message
As a response to @Keltron3030's comment in https://github.com/libretro/RetroArch/pull/13465 , when Hardcore Mode is enabled in Cheevos, we should still show the Load State option to users in the menu, but display a message telling them that they can't load states when the user attempts to load a saved state, due to Hardcore Mode.

### Suggested Changes

- [ ] Have Hardcore Mode be enabled by default
- [ ] Have "Load State" be present in the Quick Menu
- [ ] When Hardcore Mode is enabled and the user attempts to Load State, display an error message saying they can't load states when Hardcore Mode is enabled

### PR DESCRIPTION
**Pull request by Jamiras**
## Description

Closes #13469

Resets Hardcode default back to enabled
Allows Load State item to appear in menu when hardcore is enabled
Shows a message when trying to load a state while hardcore is enabled

image

## Related Issues

#13469, #13465

## Related Pull Requests

n/a

## Reviewers

@Sanaki @RobLoach

### CODE REVIEW

**Comment by twinaphex** [comment]
What is the justification for turning on Hardcore Mode by default for Cheevos?

**Comment by Jamiras** [comment]
From #13238 (where the change was first made):
>  We want to encourage players to play in Hardcore. It's easy enough to disable (or pause) if they don't find it to their liking.

From #13465 (where the change was reverted without anyone consulting us):
> With hardcore default off, users have complained they feel cheated when they find out they didn't earn hardcore credit for the games they played, not knowing it made a difference. We've had users asking us to make hardcore default for years because of this.

**Review by Sanaki — APPROVED** [review]

**Comment by twinaphex** [comment]
Fine then, I guess I'll merge it.

**Comment by RobLoach** [comment]
Thanks for taking this one on, @Jamiras :+1:

**Pull request merged**
