### PR TITLE
Extra mouse buttons

### PR DESCRIPTION
**Pull request by hiddenasbestos**
Given the common occurrence of additional buttons on modern mice, I propose adding controls RETRO_DEVICE_ID_MOUSE_BUTTON_4 and RETRO_DEVICE_ID_MOUSE_BUTTON_5 to the set of constants. 

Sega Saturn cores can map these to the required start button input on its official mouse, to more accurately represent the real hardware. Other cores, such as for ports of Doom and Quake would also benefit.

### CODE REVIEW

**Comment by twinaphex** [comment]
Thanks for the contribution. I still see some platforms for which we need to add mouse 4/5 support (like Android/OSX/Linux), but I imagine you don't have access to those development environments so we could take care of this ourselves.

@Alcaro Seems like a fairly useful and trivial thing to add to libretro.h, got any last-minute objections or design considerations that would prevent this from being merged?

**Comment by Alcaro** [comment]
Mouse 4/5 are mouse wheel up/down on Linux, and possibly on other problems.

But there are wheel constants around there already, and anyone with a brain can figure out that linux-mouse4 does not trigger both of those, so I'm fine with this.

I would prefer if RETRO_DEVICE_ID_MOUSE_HORIZ_WHEELUP had a less weird name, like RETRO_DEVICE_ID_MOUSE_HORIZ_WHEELLEFT, but that's out of scope here.

**Comment by twinaphex** [comment]
OK, I am merging this then and also the PRs made to libretro-common, libretro-arb, and the saturn core.

**Comment by hyarsan** [comment]
Yes! I was thinking about this an few days ago! :)

**Pull request merged**
