### PR TITLE
 push save state into background for cores that need the emulator to be running during serialization

### PR DESCRIPTION
**Pull request by RetroSven**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

 push save state into background for cores that need the emulator to be running during serialization

## Related Issues

https://github.com/libretro/reicast-emulator/issues/204

## Reviewers

@twinaphex

### CODE REVIEW

**Comment by twinaphex** [comment]
@RetroSven I hear from @Tatsuya79 that this is resulting in savestate corruption in cores like snes9x. We might have to revert this, and you should probably fix the savestate issues inside the core. The frontend probably shouldn't be touched, it should be possible to fix the issues core-side without touching the frontend.

**Comment by twinaphex** [comment]
Alternatively ,if the changes absolutely have to be made to frontend code, we should make absolutely zero there is no savestate corruption with other cores.

**Comment by Tatsuya79** [comment]
I got corrupted save states in several cores I tested (snes9x, fceumm, beetle-sgx).
1 or 2 states are fine and then you got a corrupted one that crash the core.

Reverting to the previous version of task_save.c fixed it.

Win7 x64, MSYS2 gcc 7.3.

**Comment by RetroSven** [comment]
well that's unfortunate -  I have an idea of what may be the problem.  I'll take a look at it tomorrow and see why snes9x is failing.   Might be something simple, but worst-case scenario is that it could be a config option in RA that defaults to true for reicast.

**Comment by twinaphex** [comment]
Also @RetroSven , tested Power Stone using the exact same scenario and the sky background now properly appears. So that issue seems to be resolved now.

**Comment by RetroSven** [comment]
@twinaphex Here is the problem:

Everything works except for saving the state when reicast threading is enabled and the emulator is paused  (because you're in the menu).  Serialization when emu is paused results in a freeze because it must wait for the core to be in such a state that it is ready for serialization (i.e. sh4 core is stopped and in a static state).  When the emulator is "paused" in reicast threaded mode, emu_thread continues to run, but it "looks" paused because there are mutexes on the video thread and the audio thread such that if those threads are not processed (by RA) it cannot proceed.  When the user pauses the emu,  emu_thread will continue to run up to one of two states : waiting for video mutex  or waiting for audio mutex.  I can work around the video mutex on the core side (i.e. can manually trigger/set the video mutex and get the sh4 core unstuck) but I have not found a way to do the same thing for the audio mutex.   For example, if you're using pulse (like me) it hangs on pulse.c line 259 "pa_threaded_mainloop_wait" which is ultimately called from reicast's audiostream.cpp WriteSample line 28 "audio_batch_cb".  I can trigger/unstick this in RA via a call to audio_driver_start before the serialization call (and then saving appears to work 100% from in-menu), but I suspect this will result in the same kind of problems that manifested when the entire save state process was pushed into a background task.

I do not see any way around this because there's no way to anticipate or control when a user enters the menu and I don't know of a way for the core to be told when the user goes into the menu (pauses).

Therefore, we either need a way for the core to be able to manually start/stop the audio or we need a way for the core to instruct RA to push save states into the background so it can be done on a core-by-core basis.  

The only way I see to do either of these things without changing anything in libretro is to make use of RETRO_ENVIRONMENT_GET_VARIABLE/RETRO_ENVIRONMENT_SET_VARIABLES in a hack-ish way (where the core and RA agree upon a specific hardcoded string value and set/check that value to determine if saves should be pushed to the background.  That's not ideal, so we're left with changing libretro in some manner.

The cleanest, least invasive way seems to be to add a new ENVIRONMENT variable  like:

RETRO_ENVIRONMENT_SAVE_STATE_IN_BACKGROUND

which would essentially have the same kind of logic as RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME and simply default to the way things currently work.  If (and only if) the core sends this env variable with true as a parameter then RA will push save states to the background.

That would be one extra line to libretro.h and wouldn't necessarily be needed to be pushed to all the cores because they will all compile fine without it (although I don't know what your internal process is for libretro changes)

Alternatively, we could do nothing and just tell reicast users that saving via the menu when reicast threading is enabled is not currently supported.

Thoughts?

**Comment by twinaphex** [comment]
@Themaister Can we have your input on this?

**Comment by RetroSven** [comment]
Another thought is to create another RA-specific config (which would be visible to all cores) that defaults to false and we'd have to tell reicast users that you must set the variable to enabled if you want to save states via menu with reicast-threading enabled.

**Comment by Themaister** [comment]
On serialize, if a core is doing weird stuff like being in "limbo", it will need to unblock the emulator, run until it's safe, then serialize, then block again.

For reference, this is what bsnes does because video refresh IRQs can triggen in-between opcodes, at times where you cannot synchronize. Adding this much weirdness to a frontend just for saving savestates is not a good idea.

**Comment by twinaphex** [comment]
I asked @Themaister, one of the initial authors of the libretro API, and he doesn't believe we need to add an environment calback like this to the libretro API, and that it should be perfectly possible to fix this core-side without altering anything to either the libretro API or RetroArch.

He might comment later on, but this is in short what he said:

'In serialize, unblock the thread, run till serialization then block again'.

**Comment by RetroSven** [comment]
And I think the RA-specific option (which doesn't require any changes to libretro) would be the best option right now since it's the least invasive.

**Comment by twinaphex** [comment]
@Themaister - it might be important to note this threaded rendering option also does audio on a thread, with audio_batch_cb being called on a thread different from the main thread as far as I know.

**Comment by RetroSven** [comment]
@twinaphex yes that's correct

**Comment by Themaister** [comment]
Well, you say that you block in RA's audio backend? How is that possible when you're in the menu? I assume you're only calling audio_batch_cb from within the AUDIO_CALLBACK? You cannot call audio_batch_cb unless RA asks you for audio in that callback.

That callback should not be active when the audio backend is paused/stopped. Of course, there could be a bug where the audio backend is stopped, but there's a pending audio push command being blocked. That would be wrong behavior on RA's part though. Do you have a backtrace of the deadlocked audio command?

**Comment by RetroSven** [comment]
reicast (when running in threaded mode) starts its own cpu-processing thread outside of the main RA thread.  This reicast cpu thread has call backs to flush audio.  When that happens it must lock the sound driver (e.g. pulse) with a mutex.  Calls to retro_run do nothing except to adjust video framebuffers.  The main meat of the emulation CPU happens in the other thread.

When the user opens the menu, calls to retro_run stop, but the main CPU processing thread continues.  The main CPU processing only appears to stop because the RA audio thread was paused which eventually causes the main CPU thread to block while waiting for the audio resume (which won't happen until the menu is closed)

Backtrace of blocked audio

reicast emu thread:
pthread_cond_wait@@GLIBC_2.3.2() at 0x7ffff4c913e7	
pa_threaded_mainloop_wait() at 0x7ffff5176640	
pulse_write() at pulse.c:259 0x62626c	
audio_driver_flush() at audio_driver.c:719 0x46604c	
audio_driver_sample_batch() at audio_driver.c:782 0x4661cd	
WriteSample() at audiostream.cpp:28 0x7fffe451d4d1	
AICA_Sample() at sgc_if.cpp:1,399 0x7fffe348327c	
libAICA_TimeStep() at aica.cpp:99 0x7fffe3480afc	
arm_Run() at arm7.cpp:441 0x7fffe347f752	
AicaUpdate() at sh4_interpreter.cpp:237 0x7fffe34b283f	
handle_cb() at sh4_sched.cpp:127 0x7fffe34af7fd	
sh4_sched_tick() at sh4_sched.cpp:151 0x7fffe34af8d5	
UpdateSystem() at sh4_interpreter.cpp:40 0x7fffe34b238f	
ngen_mainloop() at rec_x64.cpp:53 0x7fffe34f0eb6	
recSh4_Run() at driver.cpp:89 0x7fffe450aaae	
dc_run() at nullDC.cpp:392 0x7fffe34c291f	
emu_thread_func() at libretro.cpp:143 0x7fffe4518d19	
thread_wrap() at rthreads.c:145 0x7fffe454dacd	
start_thread() at 0x7ffff4c8d184	
clone() at 0x7fffefe7103d	

RA thread:
clock_gettime() at 0x7ffff7ffabd9	
clock_gettime() at 0x7fffefe7f51d	
cpu_features_get_time_usec() at features_cpu.c:226 0x4d790c	
acquire_mainloop_lock() at libretro.cpp:1,223 0x7fffe451c3d9	
retro_serialize() at libretro.cpp:1,251 0x7fffe451c4b9	
core_serialize() at core_impl.c:337 0x430ad3	
content_save_state() at task_save.c:1,177 0x452aad	
command_event_main_state() at command.c:1,667 0x43b7eb	
command_event() at command.c:1,934 0x43bd7e	
generic_action_ok_command() at menu_cbs_ok.c:1,274 0x666ed0	
action_ok_save_state() at menu_cbs_ok.c:3,000 0x66b12c	
menu_entry_action() at menu_entry.c:454 0x663cc0	
generic_menu_iterate() at menu_generic.c:233 0x6ad0de	
menu_driver_iterate() at menu_driver.c:1,926 0x64422e	
runloop_check_state() at retroarch.c:2,775 0x435758	
runloop_iterate() at retroarch.c:3,386 0x43679f	
ui_application_qt_run() at ui_qt_application.cpp:184 0x558758	
rarch_main() at frontend.c:157 0x42f2fa	
main() at ui_qt_application.cpp:208 0x5587c2

**Comment by RetroSven** [comment]
@twinaphex what are your thoughts about just making this an option like settings.bools.savestate_in_background and make it visible in the same menu as settings.bools.savestate_auto_save ?

**Comment by twinaphex** [comment]
@RetroSven I really want to explore first the possibility of avoiding adding anything to either RetroArch or the API. If @Themaister concludes that the only way to fix this is to add / change code to RetroArch or to the API, then sure, we can explore your suggestions. But let's first see what @Themaister responds with. He knows the API and RetroArch itself better than I do.

**Comment by Themaister** [comment]
From that backtrace, I can conclude that reicast is misusing the libretro API. Audio callbacks are being called outside the frontend callback, but rather just being pumped through without any consideration from some random thread it seems. In threaded audio, you must only push out audio when the frontend asks you to, or you end up with problems like these.

**Comment by RetroSven** [comment]
https://github.com/libretro/reicast-emulator/pull/240

**Pull request merged**
