### PR TITLE
Fix Mac build on CircleCI

### PR DESCRIPTION
**Pull request by GeoffreyPlitt**
With these changes, this will actually build on CircleCI.
- submodules are fetched
- Nvidia "Cg" is installed
- Build output saved to artifacts (good place to save nightly builds, but we can also add a buildbot-upload step later too)
- The "true" command has a different path on Mac, and anyway it should be in the `$PATH` on either platform so it doesn't need an explicit path.

### CODE REVIEW

**Comment by GeoffreyPlitt** [comment]
Thanks!

**Comment by GeoffreyPlitt** [comment]
Hey @twinaphex can you or someone with perms go to https://circleci.com/add-projects and enable our project for building on CircleCI? They have a nice free plan for open source projects.

**Comment by twinaphex** [comment]
I'll discuss it with some others in the group and look into it.

**Comment by fr500** [comment]
how is this different from our current CI server?, we have TeamCity which supports xcode, msvc among other things

**Comment by GeoffreyPlitt** [comment]
This was motivated by the fact that buildbot is missing many months of Mac
builds. I figured we didn't have automated Mac builds working, is that not
the case?

On Fri, Mar 6, 2015 at 2:45 PM, Andrés <notifications@github.com> wrote:

> how is this different from our current CI server?, we have TeamCity which
> supports xcode, msvc among other things
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libretro/RetroArch/pull/1472#issuecomment-77650403>.
>



-- 
http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915

**Comment by fr500** [comment]
Well we have CI server that has those features, the problem is noone has provided an OSX box to install the agent and produce the builds. 

How does this solution work?

**Comment by GeoffreyPlitt** [comment]
This solution would work well then. CircleCI has free plans for Open Source
(http://blog.circleci.com/a-step-into-open-source/) and they build in the
cloud, with a fresh box for each git-push. Example:
https://circleci.com/gh/GeoffreyPlitt/RetroArch/40 . We can use this just
for Mac, and then push the builds elsewhere if you can tell me where they
should end up.

On Fri, Mar 6, 2015 at 3:17 PM, Andrés <notifications@github.com> wrote:

> Well we have CI server that has those features, the problem is noone has
> provided an OSX box to install the agent and produce the builds.
>
> How does this solution work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libretro/RetroArch/pull/1472#issuecomment-77654097>.
>



-- 
http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915

**Comment by fr500** [comment]
Sounds good, someone is still working on the OSX buildbot though so I guess
it's his call

**Comment by GeoffreyPlitt** [comment]
Who?

On Fri, Mar 6, 2015 at 3:46 PM, Andrés <notifications@github.com> wrote:

> Sounds good, someone is still working on the OSX buildbot though so I guess
> it's his call
>
> On Fri, Mar 6, 2015 at 6:40 PM, Geoffrey Plitt <notifications@github.com>
> wrote:
>
> > This solution would work well then. CircleCI has free plans for Open
> Source
> > (http://blog.circleci.com/a-step-into-open-source/) and they build in
> the
> > cloud, with a fresh box for each git-push. Example:
> > https://circleci.com/gh/GeoffreyPlitt/RetroArch/40 . We can use this
> just
> > for Mac, and then push the builds elsewhere if you can tell me where they
> > should end up.
> >
> > On Fri, Mar 6, 2015 at 3:17 PM, Andrés <notifications@github.com> wrote:
> >
> > > Well we have CI server that has those features, the problem is noone
> has
> > > provided an OSX box to install the agent and produce the builds.
> > >
> > > How does this solution work?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/libretro/RetroArch/pull/1472#issuecomment-77654097
> >.
> > >
> >
> >
> >
> > --
> > http://www.geoffplitt.com
> > http://facebook.com/geoffrey.plitt
> > https://twitter.com/GeoffreyPlitt
> > 773.339.0915
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/libretro/RetroArch/pull/1472#issuecomment-77656590>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libretro/RetroArch/pull/1472#issuecomment-77657178>.
>



-- 
http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915

**Comment by fr500** [comment]
Ikarith, he is doing the iOS builds now and he mentioned it should be  easy
to adapt the same build rule for OSX

**Pull request merged**
