### PR TITLE
add comments in order to document input_driver.h

### PR DESCRIPTION
**Pull request by markwkidd**
I am working to learn the input driver code, and as part of the process I would like to add some comments that, from my experience, I think would help other people to work in this part of RetroArch.

This should be fine to merge as is, but I would prefer to use this PR thread to ask questions to fill in a couple more blank spots.

### CODE REVIEW

**Comment by markwkidd** [comment]
@jdgleaver I really appreciate all your help while I've been learning this code, thank you for letting me tag you periodically. Is there any way you could help me come up with a clear description for two of these parameters to the `input_state` function?

I'm having trouble putting my finger on the exact role of `sec_joypad_data` and `joypad_info` that get passed to the input driver in the `input_state` function?

This is the function prototype I'm referring to:
https://github.com/libretro/RetroArch/blob/a34ea2ffac413443b3bbe605e5c5ddb3064b621e/input/input_driver.h#L162-L191

**Comment by jdgleaver** [comment]
Yes, the input code is dreadful...

Thank you for adding these comments - any documentation here is more than welcome!

- `sec_joypad_data`: This one is a dirty hack. It exists purely to support "Made For iOS (MFi)" controllers, which cannot be handled in the regular fashion (because Apple...). On iOS platforms, these MFi controllers have to be initialised as a 'secondary' input device (with hardcoded driver id), which is then polled/read in conjunction with the regular RA input device. So I guess the comment should be something like:

```
     * @sec_joypad_data: the input state struct of any secondary input device (e.g. MFi controllers), defined by the secondary input driver. May be NULL. Queried state will be the logical OR of 'joypad_data' and 'sec_joypad_data'.
```

- `joypad_info`: This one is also a bit dubious... The `rarch_joypad_info_t` struct contains the device index + autoconfig binds for the controller to be queried, and also (for unknown reasons) the analog axis threshold when mapping analog stick to dpad input. I suppose you could write it something like:

```
     * @joypad_info:      Info struct for the controller to be queried, containing physical (hardware) device index and autoconfig input mapping.
```

For reference, this snippet shows the info struct assignment:

```c
   for (i = 0; i < max_users; i++)
   {
      joypad_info[i].axis_threshold              = p_rarch->input_driver_axis_threshold;
      joypad_info[i].joy_idx                     = settings->uints.input_joypad_index[i];
      joypad_info[i].auto_binds                  = input_autoconf_binds[joypad_info[i].joy_idx];
```

**Comment by markwkidd** [comment]
Perfect, thanks! I have now marked this PR as ready to review/merge.

@jdgleaver I have also started a specification doc for input drivers which complements the source comments, viewable here https://docs.libretro.com/development/retroarch/input/input-drivers/ . 

I plan to continue documenting input code and improving the specification doc over the next couple of weeks, so you might hear from me again if I have trouble figuring something out.

In terms of my professional career, I'm much more experienced as a technical writer and project manager than a coder. 🔢

**Comment by jdgleaver** [comment]
Nice, this is ready for merging now :)

And many thanks for starting the input driver specification document! Good technical writers are something that RetroArch needs quite desperately!

**Pull request merged**
