### PR TITLE
Merge Newest Commits

### PR DESCRIPTION
**Pull request by meepingsnesroms**

### CODE REVIEW

**Comment by twinaphex** [comment]
Ugh, this is a very nasty way of merging back stuff from the master branch.

A far better way to do this is git pull --rebase

Did you make any changes to this yet? If you didn't, I'd advise we remove this branch you made and I create a clean one for you from scratch. This is going to be unmergable later on otherwise.

**Comment by meepingsnesroms** [comment]
No I haven't made any changes yet,I am not good with git since this is the first open source project I am a part of and still learning this.

**Comment by fr500** [comment]
you should start over @meepingsnesroms 
the correct workflow should be:

- fork
- clone your fork to your PC
- push any changes you want to your repo, nothing happens
- send a pull request when you are done

If you want to sync from upstream do:
git remote add upstream https://github.com/libretro/RetroArch.git
git fetch upstream
git rebase upstream/master

DO NOT PUSH such a rebase while you have an open pull request.

That's it.

**Comment by fr500** [comment]
@meepingsnesroms additionally, please don't merge your PRs yourself unless you're absolutely sure of what you're doing.

This is really ugly.

**Comment by twinaphex** [comment]
@meepingsnesroms I re-made the msr_temp branch.

It's clean now.

Don't feel discouraged from contributing, however, keep in mind what @fr500 told you about how to rebase from now on. Thanks and good luck.

**Comment by meepingsnesroms** [comment]
I hadn't made any changes and when working on it I would want to use the latest version so I tried to update the repository.(I wouldn't have done that if I made changes since once they where merged into the main branch it would have the changes and be up to date)

**Comment by twinaphex** [comment]
Anyway, from now on,

if you want to resync with master, you can do this -

git rebase master

In most cases that should work. If it doesn't ,you can let me know and I could help you out there and then.

**Comment by fr500** [comment]
Looking at it again, it's really not a problem since he's just merging master into his branch.

**Pull request merged**
