### PR TITLE
Allow for both -e and -R to start a BSV file recording at a state

### PR DESCRIPTION
**Pull request by JoeOsborn**
This is a followup to https://github.com/libretro/RetroArch/pull/14877#issuecomment-1398896753 .  It shows a warning if -e and -P are used in combination, and allows for using -e and -R together to start a recording from a given entry state.  I thought it would be interesting to allow -e to take a file path or state slot as argument, but in the PR that introduced -e this option was considered but discarded and I wanted to keep the scope of this change as small as I could.

The reason this patch is surprisingly large is that loading a state takes some time, and the BSV recording shouldn't start until that's done.

The minimal patch for this would just be a change to runloop.c which moves movie initialization after entry state loading, throwing in a task_queue_wait().  This makes for some awkward repeated autoload OSD messages and doesn't solve the underlying issue, which is a mixing of async task queue stuff and synchronous function calls.

Most of this change therefore puts BSV recording start/stop into tasks, like saving and loading are tasks; this was important to centralize BSV operations a bit more and is the first part of a refactoring towards more robust input recording.  The necessary wait for state loading to complete is introduced in the begin-recording task handler.

Movie types are also moved out of command.h, since they weren't used in command.c.

### CODE REVIEW

**Comment by JoeOsborn** [comment]
I saw the style problems, I’ll fix them soon. Is there an easy way to build locally for c89?

**Comment by LibretroAdmin** [comment]
hi can you fix the C89 build error? See the CI pipeline checks

**Comment by LibretroAdmin** [comment]
> I saw the style problems, I’ll fix them soon. Is there an easy way to build locally for c89?

Yes. Build with make C89_BUILD=1

**Comment by JoeOsborn** [comment]
CI is good now, thanks for the makefile tip.

**Pull request merged**
