### PR TITLE
Add sublabel for Content Saving

### PR DESCRIPTION
**Pull request by lasers**

### CODE REVIEW

**Comment by Kivutar** [comment]
Why renaming saving to content saving? looks like we're going to save the content itself

**Comment by lasers** [comment]
Savestates? Looking to expand the word 'Saving' a bit because the sublabel is ratherl ong.

**Comment by Kivutar** [comment]
It's not just about savestates, it's also about saving the ram, saving in general

**Comment by lasers** [comment]
What do you want to do?  `Saving` // `Change settings for the savings.` ?

**Comment by lasers** [comment]
Fixed. I'll do the next one. 👍

**Pull request merged**
