### PR TITLE
Allow RETRO_ENVIRONMENT_SET_MEMORY_MAPS also after core startup

### PR DESCRIPTION
**Pull request by schellingb**
## Description
As of now RetroArch parses the passed data from `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` after starting up the core (after `retro_init` and `retro_load_game`) and then if the core were to call that same environment call again during `retro_run` it would ignore the passed data.

This fits libretro.h which includes this comment:
```
Can be called from retro_init and retro_load_game.
```

This PR removes that comment and changes RetroArch so it can receive changes in the memory maps at any time when the core is running. 

While this PR modifies libretro.h, this is NOT an API/ABI change. All that is being changed is a comment.

If this PR is merged, my DOS emulator core can be improved to provide more stable memory addresses to RetroArch's cheat manager by placing the memory of a running DOS game at a fixed memory address. It also avoids a possible crash when using the cheat system with dosbox-pure because rebooting the emulated DOS computer causes the emulated RAM to be reallocated. With this fix RetroArch will use the new pointers instead of keeping the old ones that have been freed.

Another libretro frontend "RALibretro" already supports calling `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` at any time so this will make RetroArch match that.

Change the comment in libretro.h about the removed limit and handle the environment call during core runtime in RetroArch.

## Related Pull Requests
- #2986
- #734

## Reviewers
It seems like in the past @Jamiras and @leiradel have been involved with handling the core's memory maps in RetroArch so I'd greatly appreciate their review or them voicing any feedback or concerns. Thanks.

### CODE REVIEW

**Comment by leiradel** [comment]
I wasn't really involved in the design of `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`, but I added the environment call to many cores at the time so they would support achievements.

I think the interface is too restrictive, it should be expanded to allow passing functions to read and write from blocks of memory instead of using pointers. Alternatively, another environment call could be created to expose memory as functions to read from and write to them.

That being said, I think lifting the restriction that `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` can only be called from `retro_init` and `retro_load_game` is great.

**Comment by Jamiras** [comment]
> It also avoids a possible crash when using the cheat system with dosbox-pure because rebooting the emulated DOS computer causes the emulated RAM to be reallocated. With this fix RetroArch will use the new pointers instead of keeping the old ones that have been freed.

We already had to address this for RetroAchievements:
https://github.com/libretro/RetroArch/blob/e2e193290ca1d5cb462818ccc3bf7bc8b2074411/cheevos/cheevos.c#L741-L744

I'm not sure if those cores are calling `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` on reset, so it's probably best to leave that in place for now. It may be duplicate work.

**Review by Jamiras — APPROVED** [review]

**Comment by schellingb** [comment]
@leiradel Thanks for your feedback and approval!
If a core could pass a read and write function that would be pretty good I think. There's also a lot of "TODO" in `struct retro_memory_descriptor` in libretro.h which would be nice if they could get addressed. Maybe some day...

@Jamiras Thanks for looking through this! I checked both functions which I added calls to in the place where `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` is handled in RetroArch, `cheat_manager_initialize_memory` and `rcheevos_refresh_memory`, and both clean up everything they did on a previous call so at worst calling them too much is a bit of a waste of freeing/allocating/copying memory but that certainly is better than keeping potentially invalid pointers around.

**Comment by schellingb** [comment]
@Jamiras Looking at the function `rcheevos_reset_game` you mentioned:

```c
void rcheevos_reset_game(bool widgets_ready)
{
   ...
   /* Some cores reallocate memory on reset, 
    * make sure we update our pointers */
   if (rcheevos_locals.memory.total_size > 0)
      rcheevos_init_memory(&rcheevos_locals);
}
```

This call to `rcheevos_init_memory` is probably superfluous now with this PR is merged.
`rcheevos_init_memory` reads from `runloop_state_get_ptr()->system->mmaps`, which the only place that ever changes in RetroArch is in the handling of `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` in `runloop_environment_cb`. This is where this PR now adds the call to `rcheevos_refresh_memory` (which also calls `rcheevos_init_memory`).

Thus I think the call to `rcheevos_init_memory` in `rcheevos_reset_game` can be safely removed as part of this PR, what do you think?

**Comment by Jamiras** [comment]
> Thus I think the call to rcheevos_init_memory in rcheevos_reset_game can be safely removed as part of this PR, what do you think?

As long as the cores are calling `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` when they change the pointer, which is why I said:
> I'm not sure if those cores are calling RETRO_ENVIRONMENT_SET_MEMORY_MAPS on reset, so it's probably best to leave that in place for now. It may be duplicate work.

The concern is, as you mentioned, using a stale pointer.

**Comment by schellingb** [comment]
> As long as the cores are calling RETRO_ENVIRONMENT_SET_MEMORY_MAPS when they change the pointer, which is why I said:
> The concern is, as you mentioned, using a stale pointer.

When RetroArch handles `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`, it deep-copies anything passed into it. So if a core were to modify anything related to the memory maps (like freeing or moving pointed at memory) and not call `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`, then the frontend would have no way of knowing about it.

`rcheevos_init_memory` works on what has been copied at the point of `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`. Just calling `rcheevos_init_memory` again in `rcheevos_reset_game` won't be able to do anything different if nothing new has been copied by the core calling `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` again.

With that in mind, I'm confident the call to `rcheevos_init_memory` in `rcheevos_reset_game` can be removed.

**Comment by Jamiras** [comment]
> if a core were to modify anything related to the memory maps (like freeing or moving pointed at memory) and not call RETRO_ENVIRONMENT_SET_MEMORY_MAPS, then the frontend would have no way of knowing about it.

That's what I'm worried about.

I tried the one core I know this behavior was added for (Sameboy), and it does call `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` on reset, so it's probably safe to remove the explicit call in `rcheevos_reset_game`. It definitely should be the core's responsibility to inform us if the pointer changes.

**Comment by schellingb** [comment]
Yeah if the core doesn't inform the frontend then the frontend can't do anything. RetroArch will just keep the old memory map information it had copied from before as is in `runloop_state_get_ptr()->system->mmaps` and reading that copied old data again in `rcheevos_init_memory` won't help.

The only thing a frontend really could do is keep a list of cores with bad behaviors and on reset clear the known mmap information.... but it should be much easier to fix the core then :-)

In the end if the core invalidates the pointers passed by `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` without informing about the change it is bugged. Just like if it were to return an invalid pointer in `retro_get_memory_data` or send an invalid pointer to an environment call.

Though up until this PR the core wasn't really "allowed" to call `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` again (because the comment in libretro.h said "Can be called from retro_init and retro_load_game."). Though my core did anyway and it seems Sameboy ignored the comment as well. Also it doesn't look like things are crashing everywhere for achievement users so we can assume most cores (at least those that support achievements) are clean.

**Comment by schellingb** [comment]
I realized that for cores that don't use `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` but instead use `retro_get_memory_data`, calling `rcheevos_init_memory` in `rcheevos_reset_game` might still be required.

So I will leave `rcheevos_reset_game` as is after all. For cores that use the memory map environment call it will end up doing some superfluous work but it's a tiny amount of memory allocation and copying once on core reset so it's probably fine.

Instead I made a change to only actually call `rcheevos_init_memory` via `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` if RetroAchievements have actually been enabled and started up. That should be more correct, can you quickly check that change [54a3f1b](https://github.com/libretro/RetroArch/pull/15310/commits/54a3f1b47914328c35d08e35e2d41214ac3d1300) @Jamiras ? Thanks!

**Review by Jamiras — APPROVED** [review]
Only refreshing when there's something to refresh makes sense. Verified working with Sameboy core.

**Pull request merged**
