### PR TITLE
Update Simplified Chinese Language

### PR DESCRIPTION
**Pull request by ayssia**
Fixed some non-native words which causes misunderstanding.

### CODE REVIEW

**Comment by ayssia** [comment]
"状态" means "status" in Chinese, so "保存状态" is misleading to "save status", instead of "savestate".

Changed all _"保存状态"(save status)_ and _"状态存储"(status saved)_ to **"即时存档"(savestate)**.

"卡槽" is "card slot", which is not suitable for "savestate slot".

Changed _"卡槽"_ to **"栏位"(slot)**.

**Comment by twinaphex** [comment]
Hi there @ayssia ,

thanks for your efforts.

I'd like to ask you though if you could follow a different procedure from now on for submitting localization updates.

There is now a very easily accessible way to provide localization updates in a team-based manner. You can follow our guide here -

https://docs.libretro.com/development/retroarch/new-translations-crowdin/

all it takes is to register an account on a site called Crowdin.com and from there you can join our project.

If you have questions beyond what is addressed in the article, you could talk to @guoyunhe himself who started this initiative.

Again, thanks very much for your efforts and I hope you can submit these to Crowdin.

**Comment by twinaphex** [comment]
Hi @guoyunhe,

could you perhaps take these changes and incorporate them on Crowdin so they don't get lost? I could then close this PR. Thanks.

**Comment by guoyunhe** [comment]
They are in Crowdin now. You can close it.

**Pull request closed without merging**
