### PR TITLE
Updating Spanish translation

### PR DESCRIPTION
**Pull request by IlDucci**
Now with a 100% more ANSI characters.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hmm, seems to have a merge conflict?

**Comment by IlDucci** [comment]
Well, I didn't expected the last update to fuse with the one three days ago. Guess I messed again.

**Comment by Alcaro** [comment]
I think I managed to clean up the conflicts here, but please double check it; I may have picked wrong side on some places.

**Comment by IlDucci** [comment]
So far seems good.

**Pull request merged**
