### PR TITLE
Folding message in CJK environment

### PR DESCRIPTION
**Pull request by toshixm**
## Description

This PR tries to fix issues #7439 and #9731.
The position of the fold is incorrect when using East Asian language (Chinese, Japanese and Korean) , because current implementation of word_wrap() has two problems below.

1. The method of calculating the character width is wrong.
2. The folding uses only space as delimiter, but it is not usualy used as delimiter in East Asian language.

I try to fix 2 in this PR, and try to fix 1 in #12399.

I add an additional folding condition below:

- search nearest first byte of character whose length in UTF-8 representation is equal to or greater than 3
- put '\n' into destination buffer and move the index of source string to above location

This is not the best way, but it can be achived at additional small cost and is better than the current implementation .

before:
Honeyview_after

after:
Honeyview_after2

## Related Issues

#7439, #9731

## Related Pull Requests

#12399

### CODE REVIEW

**Comment by sinusinu** [comment]
Hello, I opened the issue #9731. Thank you for looking into this problem!
I tested with both PRs applied, and somehow the issue gets fixed only when the RetroArch is launched with language set to Japanese.

- If RetroArch is launched with language set to Japanese, Chinese and Korean language also gets wrapped properly.
- If RetroArch is launched with language set to either Chinese or Korean, changing language back to Japanese doesn't fix the problem.

I noticed that Korean font looks quite different between two situation, so could it be using a different font renderer and that renderer is reporting wrong character size?

| Japanese | Chinese | Korean |
| -------- | ------- | ------ |
|jp|cn|ko|

| Chinese → Japanese | Japanese → Chinese | Japanese → Korean |
| ----------------- | ------------------ | ----------------- |
|cn-jp|jp-cn|jp-ko|

**Comment by toshixm** [comment]
Hi @sinusinu , thank you for your very useful feedback!

As you said, the behavior you have pointed out is caused by different font used.

When selecting Japanese, assets/glui/font.ttf ('M+ 1p') is used. It is designed that the width of full-width characters is about 2.0 times wider than the width of typical half-width ones.
While when selecting Korean, assets/pkg/korean-fallback-font.ttf ('SpoqaHanSans-Regular') is used. It seems that the width of full-width character is about 2.5 - 2.6 times wider than the width of typical half-width ones.

I think that there are three approach below to fix the behavior:
1. use font that the width of full-width character is about 2.0 times wider then half-width ones
2. change calculation algorithm to full_width = half_width * 2.6
3. pass the widths of full/half width character as parameters of word_wrap(), and calculate using them

I think the best approach is 3, but it requires a lot of changes.
Approach 2 is very simple and seems to be good in most cases, so I will try an additional fix at #12399.

@sinusinu , could you try approach 1 if you can? I can't try it soon because I don't have enough knowledge about Korean fonts.

**Comment by sinusinu** [comment]
For approach 1, I changed assets/pkg/korean-fallback-font.ttf to D2Coding (Korean fixed-width font which have full-width characters exactly 2 times wider than half-width characters) and texts got wrapped fine just like Japanese ones.
This font is mainly designed to be used in IDE/Coding stuff, so it wouldn't fit as the UI font.

d2coding

For approach 2, I applied commit 35a635c and tried with Spoqa Han Sans again. Wrapping has changed, but not enough.
Japanese texts are already getting wrapped too early with value of 2.6, so setting value even more higher might not be an option.



Here's approach 2 with D2Coding.

d2coding+26

**Comment by toshixm** [comment]
@sinusinu Thank you for quick response.

> Wrapping has changed, but not enough.

Sure. I think that my proposed fix is a temporary one until implementing a more accurate calculation method. It is a small fix and not exact, but better then before in many cases.

As I described first, this PR is try to fix the problem below.

> The folding uses only space as delimiter, but it is not usualy used as delimiter in East Asian language.

Is it achived when selecting Korean? (Are there any bad side effects?)
If it is achived, I suggest that this discussion should be continued at not this PR but #12399.

**Comment by sinusinu** [comment]
> Sure. I think that my proposed fix is a temporary one until implementing a more accurate calculation method. It is a small fix and not exact, but better then before in many cases.
>
> As I described first, this PR is try to fix the problem below.

Yes, now I see that particular menu text was a bad case. In most cases wrapping with 2.6 seems quite reasonable.

> Is it achived when selecting Korean? (Are there any bad side effects?)

Yes, there is no problem. Spliting inbetween korean words usually won't make reading any harder.
I will follow on #12399 after this.

**Comment by jdgleaver** [comment]
@toshixm It is great that you are trying to solve this long standing issue :)

The most significant problem with your implementation, however, is that `word_wrap()` is no longer 'safe', and cannot really be used in its current form.

The existing function only *replaces* spaces with newline characters. Your version *inserts* newline characters. This means you can and will overflow the input string buffer.

For example, try navigating XMB with a CJK language selected. With your changes, it will segfault almost immediately.

**Comment by toshixm** [comment]
@jdgleaver  Thank you for reporting problem with my implementation.

I checked all callers to see what they were passing as the first argument (char *buffer) of word_wrap().
There are two patterns below.

1. allocate buffers statically or dynamically, and pass its pointer
2. pass pointer to source string,  and the same value is also passed as the second argument (const char *string)

I couldn't find the specification of word_wrap() function, and implicitly assumed the pattern 1 above.
If caller uses pattern 1, I think that I can fix the problem to allocate additional some spaces for inserting '\n'.
But, if it allows that caller uses pattern 2, my implementation  cannot be used, as you said.

I think it is wrong for the caller to use pattern 2, and it should be modified to use pattern 1.
How do you think about my suggestion?

**Comment by jdgleaver** [comment]
I agree with you completely that pattern 2 is wrong - input and output buffers shouldn't be the same (I didn't realise there were so many instances of this bad behaviour!). So yes, pattern 1 should be used in all cases.

The remaining difficulty is in determining the correct size of the output buffer. With the current implementation, the string length cannot change - so you just have to allocate (statically or dynamically) an output buffer the same length as the input one. With your implementation, the output size is variable.

I suppose the *maximum* output size is double the length of the input string. We just have to be a bit careful regarding performance issues here: doubling the size of any static arrays may cause issues on platforms with limited stack space, and dynamically allocating the output buffers can be slow. I guess experimentation is required.

**Comment by toshixm** [comment]
I have added an argument (size_t bufsize) to word_wrap(), that is a length of output buffer and used to prevent buffer overrun.
If the length of the output string is greater than this argument, the output string is forcibly truncated.

Most of callers allocate the output buffer statically, and their length (e.g. MENU_SUBLABEL_MAX_LENGTH) are long enough to insert several '\n'. So I think I don't need to increase their length.
Some callers allocate the output buffer dynamically using malloc() or strdup(). I have modified to use malloc() in all cases and allocate additional 10 bytes for inserting '\n'. 10 is a temporary value, but I think it is enough in most cases.

**Comment by jdgleaver** [comment]
Ah, this is good! I like what you've done here :)

I still need to review the code properly and run some comparison benchmarks, but I think we're in pretty good shape now. I'm afraid I'm almost out of time for the week, but I will test everything and get any final comments to you on Monday. I anticipate that we'll have this ready for merging before the next stable release (weekend after next) :)

**Comment by jdgleaver** [comment]
@toshixm Okay, I've had a closer look at the code, and there remains some work to be done here.

Trivial issues:

- I'm afraid I will need you to undo all of your whitespace changes. I know this is annoying, but changing whitespace as you have done effectively breaks the git history, and makes it impossible to track code changes properly
- You need to combine #12399 into this PR. It is impossible to test the full effects of one change without the other, and at present there are merge conflicts between the two. Having two PRs like this only creates difficulties
- When the two PRs are combined, the `bool unicode` argument of `word_wrap()` is no longer used, and should be removed (although there are other reasons to keep it - see my comments at the end)

Bugs:

- Where you have replaced `strdup()` with `malloc()`, you are not NUL terminating the resultant string (`strdup()` automatically ensures NUL termination in the correct place - `malloc()` does not). This means you can and will end up overflowing the resultant buffer during read operations - e.g. RetroArch will segfault on Linux when pushing a multiline widget notification message

Fundamental issues:

- Your implementation, while improving matters for CJK languages, breaks many other languages by wrapping far too aggressively. For example:

*Current master:*

Screenshot_2021-05-24_12-06-23

*Your implementation:*

Screenshot_2021-05-24_12-06-45

This really is not acceptable!

- Your implementation increases the performance overheads of the `word_wrap()` function by ~16% for all languages, which is quite a high figure, and something we would prefer to avoid...

-----

Given that your implementation only works for certain languages, and harms performance for all, I think we need a slightly different approach here:

- Keep the old `word_wrap()` implementation
- Add a new word wrap function (with the same prototype) that uses your implementation (i.e. `word_wrap_cjk()`) - we could have several of these, for multiple 'special case' languages
- Everywhere that `word_wrap()` is currently employed, have a `word_wrap` function pointer instead, that gets assigned on 'object' initialisation (menu init, widgets init, etc.) according the currently set user language

This way, we can fine tune the wrapping behaviour, and only 'fix' the languages that are currently broken. What do you think...?

**Comment by toshixm** [comment]
@jdgleaver  Thank you for reviewing my implementation and giving useful suggestions!

> I'm afraid I will need you to undo all of your whitespace changes. I know this is annoying, but changing whitespace as you have done effectively breaks the git history, and makes it impossible to track code changes properly

I was concerned about that too. I am using Visual Studio Code with Editorconfig extention, then the current .editorconfig will unintentionally make changes like this.

> Your implementation, while improving matters for CJK languages, breaks many other languages by wrapping far too aggressively.

This behavior is not intended and may be fixable, so I will investigate it.

> Your implementation increases the performance overheads of the word_wrap() function by ~16% for all languages, which is quite a high figure, and something we would prefer to avoid...

I also think it is a big problem. I think that I can reduce the overhead a bit by refactoring the implementation, but if that is not enough, I will split function as you said.

I think I'll close this PR and #12399, and re-implement them based on your suggestion. That will also solve the whitespace problem.
I will send another pull request when finish that.

**Comment by toshixm** [comment]
@jdgleaver Could you tell me how to measure the performance overhead of word_wrap()? I would like to use it when reimplementing.

**Comment by jdgleaver** [comment]
> I think I'll close this PR and #12399, and re-implement them based on your suggestion. That will also solve the whitespace problem.
> I will send another pull request when finish that.

@toshixm Thank you - I look forward to your updates :)

> Could you tell me how to measure the performance overhead of word_wrap()? I would like to use it when reimplementing.

I use Callgrind - but this may be a problem for you, because it doesn't run on Windows... I don't use Windows at all, and I am not aware of anything that is exactly equivalent on that platform...

If you are able to get hold of a Linux machine (or can set up a local VM), then profiling with Callgrind is pretty easy. The best place to do this in the code is at the point where GLUI determines the size of each menu entry (which involves wrapping sublabel text):

```diff
diff --git a/menu/drivers/materialui.c b/menu/drivers/materialui.c
index 4bde4f1726..016f52d5ff 100644
--- a/menu/drivers/materialui.c
+++ b/menu/drivers/materialui.c
@@ -3490,6 +3490,8 @@ static void materialui_layout(
       settings_t *settings,
       bool video_is_threaded);
 
+#include <valgrind/callgrind.h>
+
 /* Called on each frame. We use this callback to:
  * - Determine current scroll position
  * - Determine index of first/last on-screen entries
@@ -3564,8 +3566,10 @@ static void materialui_render(void *data,
 
    if (mui->need_compute)
    {
+CALLGRIND_START_INSTRUMENTATION;
       if (mui->font_data.list.font && mui->font_data.hint.font)
          materialui_compute_entries_box(mui, width, height, header_height);
+CALLGRIND_STOP_INSTRUMENTATION;
 
       /* After calling populate_entries(), we need to call
        * materialui_get_scroll() so the last selected item
```

You then run RetroArch like this:

```
valgrind --tool=callgrind --instr-atstart=no ./retroarch
```

...and do some simple navigation. The first thing is to navigate to a fully populated 'content history' list (with 100-200 entries, all with full core + runtime sublabels), then go through the settings entries (you don't have to do all of them - video settings and user interface > appearance are fairly good samples). Then just close RetroArch normally - this will generate a `callgrind.out.xxxxxx` file, which you can view with the following command:

```
callgrind_annotate --inclusive=yes --tree=both --auto=yes --show-percs=yes callgrind.out.xxxxxx | less
```

You can then search for the `word_wrap()` function, and it will tell you the number of times it was invoked, and the number of instructions used. Make a note of these, then edit your code and repeat - it's easy to track percentage changes in this fashion :)

**Comment by toshixm** [comment]
@jdgleaver Thank you. I am developing using not only Windows but also Linux, so I can try it you teach.

**Pull request closed without merging**
