### PR TITLE
Add ALSA MIDI driver

### PR DESCRIPTION
**Pull request by casdevel**

### CODE REVIEW

**Comment by twinaphex** [comment]
Awesome work @casdevel !

Could you also please submit the MIDI test core to https://github.com/libretro/libretro-samples? That way, people have an example core to easily access.

**Comment by casdevel** [comment]
@twinaphex 

> Could you also please submit the MIDI test core to https://github.com/libretro/libretro-samples?

Which directory?

**Comment by casdevel** [comment]
My suggestion is not to mix Audio and MIDI. This also applies to the RetroArch-s menu (I see that MIDI settings are moved to the Audio settings).

**Comment by twinaphex** [comment]
@casdevel You can come up with the directory yourself.

**Comment by 5schatten** [comment]
Just wondering if you could add [munt](https://github.com/munt/munt) support as midi output too like DOSBox uses it for example?

**Comment by casdevel** [comment]
@5schatten I don't know how DOSBox uses munt, but you can use it with mt32emu-qt (from munt repo) just like any other soft-synth that can create virtual MIDI output port(s). I just tested this with ALSA MIDI driver and it worked  as expected.

**Comment by casdevel** [comment]
I forgot to mention that I used mt32emu-qt_WITH_ALSA_MIDI_SEQUENCER option with cmake. Without it probably wont work (I didn't check).

**Comment by 5schatten** [comment]
This is the munt mt32 DOSBox patch maybe you understand how it works ^^
https://github.com/munt/munt/blob/master/DOSBox-mt32-patch/dosbox-SVN-r4025-mt32-patch.diff

I'm using DOSBox standalone which uses the libmt32emu.so.2.3 and I've checked mt32emu but this means I would need QT for this too. AFAIK either this mt32emu or fluidsynth will be an option for emulation builds like lakka?

**Comment by casdevel** [comment]
@5schatten I'm not sure what's your point, and I don't see any connections to this commit either.
If you think that RetroArch-s ALSA MIDI driver is not working as expected feel free to open a issue, mention me there and I'll try to help.

**Pull request merged**
