### PR TITLE
Non-X11 lightgun support

### PR DESCRIPTION
**Pull request by benklop**
## Description
Non-X11 retroarch was missing lightgun support, this fixes that.

The current method for getting the lightgun aiming coordinates "udev_lightgun_aiming_state" only work in X11 which is shown if you follow the code through, the required coordinates are not set otherwise. I've added an X11 if statement and left that block of code as it is. For the non-X11 code block I've used the methods from the touchscreen/pointer function which successfully gets absolute coordinates back from the mouse device in non-X11. This update is tested and working on the Raspberry Pi for an absolute mouse based device and it was not working before.

I tried to decrease the amount of changes to a minimum set.

## Related Pull Requests

This is based on https://github.com/libretro/RetroArch/pull/9684 and simply fixes the merge conflict and removes unnecessary ordering or whitespace changes.

### CODE REVIEW

**Comment by twinaphex** [comment]
Looks good.

**Comment by benklop** [comment]
something went wrong with this PR - it shows 0 line changes. the code is definitely not in there. i'll re-submit something soon.

**Comment by twinaphex** [comment]
OK, understood.

**Comment by benklop** [comment]
https://github.com/libretro/RetroArch/pull/10924 is the fixed version, it's a small change, i have no idea how it got messed up the way it did.

**Pull request merged**
