### PR TITLE
International: Add all the language updates from Crowdin…

### PR DESCRIPTION
**Pull request by WeedyWeedSmoker**
## Description

International translations update:

- Add all the language updates from Crowdin…

This unifies formatting for all languages, and this will facilitate the transition to an automatic way like https://github.com/libretro/RetroArch/pull/10358

## Related Pull Requests

https://github.com/libretro/RetroArch/pull/10511

## Reviewers

@twinaphex

### CODE REVIEW

**Comment by WeedyWeedSmoker** [comment]
@twinaphex I redid the PR — to have only 1 commit (and less confusion)…

**Comment by WeedyWeedSmoker** [comment]
@twinaphex I think it would help a great deal to merge this first, to actually see if there are any strings that get automatically removed in @guoyunhe's [commit](https://github.com/libretro/RetroArch/pull/10358), and to visualize newly added/modified strings to his commit too!

Thanks

**Comment by WeedyWeedSmoker** [comment]
@twinaphex Now would be the perfect time to merge this pull request, as a stable release has just been out, this commit is indeed thoroughly tested but it may make more sense making such a big commit at a time like this just so you can be sure…

**Comment by WeedyWeedSmoker** [comment]
@twinaphex I fixed the conflicts introduced by https://github.com/libretro/RetroArch/commit/1c4cb37e613ef31341ca0f7a01eb523d970cad31 but github went down just after commiting, that's why LGTM analysis failed miserably, somehow…

**Comment by WeedyWeedSmoker** [comment]
@twinaphex OK! This is finally ready to merge… Again!

As I mentioned in my feature request here: https://github.com/libretro/RetroArch/issues/10513, we really should consider getting a font that properly supports all Chinese characters, as well as Arabic ones (or incorporate these characters from an other font into the existing one) — especially now that the Arabic translation is coming up nicely on crowdin…

**Comment by IlDucci** [comment]
Are there any plans to update the repository's translations automatically? It seems like all the updates were not implemented in time for the latest release.

Also, are the .c files still unreachable for script conversion?

**Comment by guoyunhe** [comment]
Here is only one step left to make the process fully automatically: some one with GitHub write permission run a cron job:

```
0 * * * * cd path/to/RetroArch/intl && git pull && python3 crowdin-sync.py && git add . && git commit -m "Crowdin sync" && git push
```

For `*.c` files, here is nothing we can do right now because it is not key-value pair structure. If possible, transform its content to `*.h` files.

**Pull request merged**
