### PR TITLE
Implement "Latency" list under Settings and group all latency-related options together

### PR DESCRIPTION
**Pull request by Ryunam**
This commit proposes the implementation of a new list / category named "Latency" under the Settings tab, where all the options affecting video, audio and input latency are now grouped together and can be easily located and tweaked at once. 

Following the creation of the Runahead system by @Dwedit, latency settings have become quite numerous and diverse in RA, so this is an attempt to streamline this category and let users micromanage all the relevant values in one place.

A few pictures of the end-result:

ra-latency1
ra-latency2

### CODE REVIEW

**Comment by fr500** [comment]
I would be lost looking for audio latency...
Maybe duplicate the settings, but just moving them may make things worse.

**Comment by Ryunam** [comment]
@fr500, I understand your concerns regarding the initial confusion that might come up for some users. Still, I'd like to further expand on the reasoning behind my idea to permanently move Audio Latency as well as the other options listed here to this new submenu, instead of duplicating the settings (which would be a first for RA, I think).

Based on my personal experience, Audio Latency as an example is something you either leave at the default value or that you tweak along with the other latency-related setting, often on a per-core basis. All these values have an impact on the capabilities of your CPU and striking a proper balance between the different options on a per-core basis is a difficult task sometimes. This was made harder when you had to previously navigate through the different submenus (Video, Audio, Frame Throttle, etc.) in order to find that specific latency setting you wanted to tweak, while remembering at the same time all the other values that you had modified already. 

On the other hand, having everything in one page makes it simpler to perform these tweaks and visualize them all at once. Those who want to simply leave everything at their default values will not even have to touch the Latency menu, while "micromanagers" will be able to do so more neatly, as well as set overrides and/or compare the results with much less back-and-forth (this is especially true for Hard GPU Sync, Frame Delay and Run-Ahead).

That being said, if the consensus is on duplicating some of these settings and keeping their original position in addition to this new Latency submenu, I can work on restoring them.

**Comment by hizzlekizzle** [comment]
I think most of them are fine, since, for example, hard gpu sync and frame delay are only related to video in a technical sense and not necessarily in a way that end-users would expect. However, I'm not 100% on including audio latency in with the others, since it's usually tweaked to adjust audio quality rather than responsiveness.

**Comment by Ryunam** [comment]
When the intent is to adjust audio quality in the strictest sense, I believe that the relevant options a user would like to tweak are:
- the Audio Driver, first and foremost;
- the Resampler Quality option that was recently implemented (which by the way does have an impact on latency, but I deliberately chose to leave it out because it's more related to the quality of the output);
- following these two, all of the timing options (Dynamic Rate Control, Timing Skew, etc.)

I think the default Audio Latency value (64ms) is very safe for giving average users the expected results in terms of quality, while I have often found myself in a situation of trying to figure out the right balance between, say, Frame Delay and a value of 32ms, all without introducing pops, cracks or stuttering or making my CPU go insane. 

In that sense, I see it as a latency-related and responsiveness-related option primarily (for example, with Rhythm/Music games or with Mother 3 on GBA, where you ideally want no more than 1-2 frames of *audio* delay to match your inputs with the audio cues).

**Comment by rsn8887** [comment]
I am in favor of duplicating options. Many other apps have duplicated options, such as a quick settings menu with the most common options in addition to more detailed settings. I see no problem with it.

**Comment by twinaphex** [comment]
I added the duplicate options as well.

**Pull request merged**
