### PR TITLE
reset on hardcore enable

### PR DESCRIPTION
**Pull request by fr500**
This changes the achievements behavior again so if the hardcore mode toggle is... toggled at runtime it will reset the current content.

Before it was only warning the user to reset, but that only tracked SAVESTATES which is not "complete", a cheat could have been applied.

So the new behavior would be to reset content.

Please do not merge before @meleu and @leiradel agree with this

#7800

### CODE REVIEW

**Comment by meleu** [comment]
@fr500 on my first tests it's not resetting (fceumm with "Tiny Toons Adventures", if it matters).

What is weird is that "resetting when enabling hardcore" was the behavior before.

**Comment by fr500** [comment]
yeah but someone told me to change it,
What did you test? this PR or master?

**Comment by orbea** [comment]
I also tested this PR and found that it doesn't reset with fceumm and Castlevania.

**Comment by meleu** [comment]
I tested this branch: https://github.com/fr500/RetroArch/tree/fixes
specifically this commit: 6eae0df01080ae37d93b5d8eef437dfcbb4f6f7a

systeminformation

I alternated between softcore/hardcore and never got a reset.

**Comment by fr500** [comment]
ah, well that's part of what I'm asking, see it currently only resets **if a state has been loaded**
should I just reset every time it's toggled instead?

**Comment by orbea** [comment]
Still not resetting here.

**Comment by fr500** [comment]
are achievements actually enabled?

**Comment by orbea** [comment]
No...they are now and its resetting as expected. Sorry for the noise!

**Comment by twinaphex** [comment]
Are there still outstanding issues here or can this be merged?

**Comment by fr500** [comment]
I think it's good to go

**Comment by meleu** [comment]
Agreed.
After the last commit this PR has the intended behavior :+1:

**Pull request merged**
