### PR TITLE
intl: Add intl_bom.sh

### PR DESCRIPTION
**Pull request by orbea**
## Description

This script supports testing for missing BOM in c and header files as well as automatically fixing them.

Travis will now test if these files contain a BOM and fail when missing. They can be trivially fixed by running this script.

To print errors when the BOM is missing.
```
intl/intl_bom.sh
```
To automatically fix the files.
```
intl/intl_bom.sh -f
```

## Related Issues

The BOM is often silently and unintentionally removed from the intl c and header files breaking msvc builds, this should help both catch these instances and optionally fix them with one command.

## Related Pull Requests

Alternate PR to https://github.com/libretro/RetroArch/pull/8784, this should be an more automatic way of addressing these issues.

## Reviewers

Please wait for travis. The first travis builds should fail and I will add a second commit after I confirm it fails correctly to finish this PR.

@bparker06 Maybe you would be willing to look at this to make sure the result is correct? Do we want the BOM set correctly for all `*.c` and `*.h` files in the `intl/` directory or only some of them?

@Dwedit Since you gave me this idea maybe you can see if this will work for you too? :)

### CODE REVIEW

**Comment by orbea** [comment]
Travis correctly fails when these are missing now.
```
$ intl/intl_bom.sh
ERROR: msg_hash_de.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_eo.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_es.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_fr.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_it.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_nl.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_pt_br.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_pt_pt.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_tr.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_us.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_vn.c is missing an UTF-8 BOM at the header.
ERROR: msg_hash_de.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_eo.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_es.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_fr.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_it.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_lbl.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_nl.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_pt_br.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_pt_pt.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_tr.h is missing an UTF-8 BOM at the header.
ERROR: msg_hash_us.h is missing an UTF-8 BOM at the header.
Run 'intl/intl_bom.sh -f' and commit the results to fix these files.
The command "intl/intl_bom.sh" failed and exited with 1 during .
```

**Comment by orbea** [comment]
I added a second commit with the results of `intl_bom.sh -f`, now travis should pass. Can someone please test this with msvc builds?

**Comment by Dwedit** [comment]
I've done like 5 or 6 PRs to fix BOMs before, so anything to automate it is welcome.

**Comment by orbea** [comment]
@Dwedit Does windows have `hexdump`? Does this script work for you on a windows install? I'd prefer to make it portable, but I can't test that. Travis is using linux so it won't be able to tell me. If `hexdump` doesn't work I'll have to find a more portable way.

**Comment by Dwedit** [comment]
Someone would need additional software besides Windows itself just to run shell scripts in the first place.  If they install bash from msys or cygwin, they probably have hexdump too.

**Comment by Dwedit** [comment]
Just tested the script, and it changed the newlines from CRLF to LF when it fixed a file.

**Comment by orbea** [comment]
I didn't realize `sed` had this caveat. I added a new commit to try avoiding this, would you mind trying again?

**Comment by Dwedit** [comment]
Tested it again, appears to work fine.

**Comment by bparker06** [comment]
>Windows by itself can't run shell scripts at all.

Maybe, but we build everything for windows from within msys2 so we have tools like hexdump/bash/etc.

I wouldn't add the BOM to the `us` files, this can break *really* old compilers that have no concept of Unicode, where we would only enable English anyway. And MSVC only really needs the BOM for non-Latin based scripts.

**Comment by orbea** [comment]
> I wouldn't add the BOM to the us files, this can break really old compilers that have no concept of Unicode, where we would only enable English anyway. And MSVC only really needs the BOM for non-Latin based scripts.

Thanks for pointing this out, I think there are a few ways to deal with this.

* Keep a list of languages to run this script on or otherwise languages to exclude. This may require updating to work correctly.

* Add a specific comment to files so that we can use `grep` to match and then ignore them. This would require making sure the files are correctly commented, but if only `us` needs this then that may not be much of a burden.

I'm leaning towards the latter choice, but I'm open to suggestions.

**Comment by orbea** [comment]
@bparker06 I added a new commit to add a hint to the `us` files to disable the test for them and redid the  commit editing the files. Are there any more this should be done to or is this fine as is?

**Comment by Dwedit** [comment]
There's only one reason to have BOM markers in the first place, and that is that MSVC on Windows tries to use your local code page to build source files.

If your local code page is one of these:  Japanese Shift-JIS (932), Simplified Chinese GBK (936), Korean (949), Traditional Chinese GBK (950), you get problems.

Example that fails:
```
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_QUIT,
    "Çıkış"
    )
```
In Shift-JIS:
```
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_QUIT,
    "ﾃ・ｱkﾄｱﾅ・
    )
```
Bytes are `22 C3 87 C4 B1 6B C4 B1 C5 9F 22`.

In Shift-JIS, it divides the characters like this: `22 C3 87C4 B1 6B C4 B1 C5 9F22`, thus loses the end quote.  This is despite the Shift-JIS standard saying that bytes 00-3F cannot be used as the second byte of a multibyte character.

My understanding is the proper way to deal with the issue is to build with the `/utf-8` switch.  But there are a few caveats to using this switch:
* You are unable to use `#pragma execution_character_set("utf-8")`, even though it's reassigning it to the same character set.  I think that's a hack for a very specific older version of MSVC, and maybe should be removed.
* Older versions of MSVC do not support the `/utf-8` switch.

**Comment by orbea** [comment]
Thanks for the detailed explanation, I think the main question is if there are more files we should ignore or not.

**Comment by orbea** [comment]
@twinaphex Since I am clearly not going to get any further review I think we should consider this ready...

**Comment by Dwedit** [comment]
So this was closed, but not merged in?

**Comment by orbea** [comment]
I closed my PRs because no one else seemed to care...

**Comment by twinaphex** [comment]
@orbea Don't be so quick to assume malice, I was just busy. 

Reopen your PRs and I'll get it merged assuming there is no issue.

**Comment by Dwedit** [comment]
I think this one may be a no-go.  I just figured out that both the BOM and the Pragma must be in the code at the same time.  If there only the BOM, you get corrupted text.

We'll need to make a decision regarding supporting JP locale building in MSVC 2010+, or support MSVC 2008 and earlier...
https://github.com/libretro/RetroArch/pull/8784#issuecomment-493724057

**Pull request closed without merging**
