### PR TITLE
Add CoreAudio V3

### PR DESCRIPTION
**Pull request by stuartcarnie**
This branch is a work-in-progress and **not ready to merge**

### CODE REVIEW

**Comment by CatGreen90** [comment]
Looks like Travis is still silently failing to build this, with these errors:
```In file included from /Users/travis/libretro-super/retroarch/griffin/griffin_objc.m:76:
In file included from /Users/travis/libretro-super/retroarch/griffin/../gfx/common/metal/Context.m:9:
/Users/travis/libretro-super/retroarch/griffin/../gfx/common/metal/Context.h:52:33: error: expected a type
                         layer:(CAMetalLayer *)layer
                                ^
In file included from /Users/travis/libretro-super/retroarch/griffin/griffin_objc.m:82:
In file included from /Users/travis/libretro-super/retroarch/griffin/../gfx/common/metal_common.m:10:
/Users/travis/libretro-super/retroarch/griffin/../gfx/common/metal/../../../ui/drivers/cocoa/cocoa_common_metal.h:47:9: fatal error: 'os/signpost.h' file not found
#import <os/signpost.h>
        ^~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by stuartcarnie** [comment]
@CatGreen90 thanks for the heads up; I'm not intending for this to be merged anytime soon. It remains an experiment for now.

**Comment by twinaphex** [comment]
Can you rebase this PR @stuartcarnie ?

**Comment by ofry** [comment]
@stuartcarnie @RobLoach This PR has merge conflicts. Could you resolve them?

**Pull request closed without merging**
