### PR TITLE
Small porch fix and switching patch

### PR DESCRIPTION
**Pull request by alphanu1**
For some reason snprintf has broken switching. I have kept the increased array size but moved back to sprintf.

### CODE REVIEW

**Comment by twinaphex** [comment]
Have you tried initializing those static char arrays first?

Like for instance -

static char chararr[250] = {0};

Maybe then you could still use snprintf instead. I'd really prefer we don't have any direct usage of sprintf in the codebase going on.

**Comment by bparker06** [comment]
How is snprintf not working?

**Comment by alphanu1** [comment]
@twinaphex I will give that a try.

@bparker06 I think it's adding or loosing data ?? I'm not too sure really. However, ubuntu was not switching resolutions correctly. I will try to initialize the variable as twinaphex suggested.

**Comment by bparker06** [comment]
We definitely should not overlook or try to work around a fundamental problem like that, it needs to be fixed head-on. I would also *highly* suggest running with ASAN enabled to make sure you're not trashing any memory by mistake.

**Comment by twinaphex** [comment]
@alphanu1 

BTW, @fr500 told me that he is getting spammed on Linux with xrandr messages even though he doesn't use CRT SwitchRes. Can you look into this issue?

image

'btw
there is a constant stream of xrandr errors
in RA linux
even though I don't use switchres at all
'

**Comment by bparker06** [comment]
FYI there is an issue for the spam: https://github.com/libretro/RetroArch/issues/7200

**Comment by alphanu1** [comment]
I will look into this now!

**Pull request closed without merging**
