### PR TITLE
Updates Porches and Super width

### PR DESCRIPTION
**Pull request by alphanu1**
Updates Porches, updated super width calculation, and cleanup.

### CODE REVIEW

**Comment by alphanu1** [comment]
@twinaphex @bparker06  

Do we have a #define for the RPI4 yet? There will be new CRT switching for it but currently RPI3 uses VIDEOCORE which RPI4 does not (its build in to the GL driver)! Plus The RPI4 handles resolutions differently to the RPI3.

**Comment by alphanu1** [comment]
@hizzlekizzle @twinaphex compiling on RPI4 with the latest version the CRTSwitchRes Options are missing! any Idea? Are they now tied in with videocore? this now has to be disabled to use GL!

**Comment by hizzlekizzle** [comment]
hmm, i thought we had gotten rid of the rpi ifdefs around that, but maybe not...? I'll look into it and let you know what I/we find.

**Comment by twinaphex** [comment]
Maybe it's due to this?

https://github.com/libretro/RetroArch/blob/master/gfx/display_servers/dispserv_x11.c

If this is not how it's intended to be (that this flag should only be enabled when Xrandr is available), then please change it so that it makes sense.

**Comment by alphanu1** [comment]
The RPI does not use x11 for CRT Switching. The menu items are there in 1.7.6 but no longer since 1.7.7 

The Raspberry Pi uses userland to communicate with the graphics interface.

**Comment by twinaphex** [comment]
> The menu items are there in 1.7.6 but no longer since 1.7.7

That's because it looks at that flag now and if that bit is not set, it will not display them.

So, what I'm trying to tell you is - change the code/improve the code so that it works on RPi. I already showed you what to change. Since I don't use this code myself, I was not sure how to implement it and assumed the option should not be shown unless HAVE_XRANDR is defined (since it depends on so much xrandr code).

**Comment by hizzlekizzle** [comment]
ok, so we either need to come up with a new ifdef/ifndef to hide it when appropriate, or just deal with it being there sometimes when it shouldn't be.

**Comment by alphanu1** [comment]
Yes that would be ideal. Linux PC does use x11 and xrandr. However, the RPI does not use either, x11 nor xrandr both of which are not installed. 

 if we configure with --enable-xrandr or --enable-x11 they would need to be installed.

**Comment by orbea** [comment]
Can you just check for `videocore` or `xrandr` support?

**Comment by alphanu1** [comment]
@orbea no. You need to disable videocore core the RPI4 to use gl. The reason for this is because the RPI foundation worked with Mesa to include videocore functionality so now they dont work together. 

As RPI switching does not use x11 or xrandr. It does not need to be installed for a non destop enviroment. So, without having x11 installed which bloats out a tty environment this is not feasible. I assume Lakka is the same, having to disable videocore that is, to render gl video!

**Comment by alphanu1** [comment]
I have moved the RPI issue away from this PR! This PR is to fix CRTSwitchRes Porches and can be merged

**Pull request merged**
