### PR TITLE
(XMB) Fix Battery/Clock Icon Sizes

### PR DESCRIPTION
**Pull request by RobLoach**
This makes it so that the XMB battery/clock sizes are normal sizes, rather then the super small versions that currently exist. Fixes https://github.com/libretro/RetroArch/issues/4587 .

Requires the retroarch-assets PR over at: https://github.com/libretro/retroarch-assets/pull/122

iconsize

### CODE REVIEW

**Comment by twinaphex** [comment]
@kivutar What do you think about this PR? And about the amount of space now inbetween time and battery level?

**Comment by Kivutar** [comment]
I'm testing it.

**Comment by Kivutar** [comment]
The positions are wrong, and scaling down the textures make them look ugly with GLES where we don't have mipmaping. But even with mipmaping, scaling down makes them ugly.
We can't get it as is.

**Comment by RobLoach** [comment]
> The positions are wrong, and scaling down the textures make them look ugly with GLES where we don't have mipmaping. But even with mipmaping, scaling down makes them ugly.
We can't get it as is.

Would you mind posting a screenshot with GLES without mipmapping?

**Comment by RobLoach** [comment]
Going to close this, seems there's some mipmapping issues. That's beyond my knowledge.

**Pull request closed without merging**
