### PR TITLE
(Playlist Management) Add optional per-playlist alphabetical sorting

### LINKED ISSUE #10359: [Feature Request] Option / task under Playlist Manager to sort alphabetically each playlist
Currently RA allows users to decide whether they want to view all Playlists sorted by alphabetical order. This is controlled through the boolean option "Sort playlists alphabetically", located under Settings -> Playlists.

It could be very useful to also have another option for sorting entries of each individual playlist under the Playlist Manager and have it as a task that saves the re-sorted playlist to disk. 

This would make it possible to:
- choose whether you want one specific playlist to be sorted alphabetically, while maybe leaving other playlists set to a personalized order;
- reorganize an LPL file that was modified manually and saving the re-sorted version permanently.

I have tried to work on this and basically did most of the framework, but I am still clueless about how to properly write / edit a RA task. So I would be more than happy to see this feature implemented by someone definitely more experienced than I could be at this point.

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

At present, RetroArch offers a global `Sort playlists alphabetically` option - but several users have requested more fine grained control. i.e. Users with highly customised setups might want a number of 'hand-crafted' playlists with specific ordering (release date, games in a particular series, etc.) *without* losing the ability to automatically sort their other conventional platform-based playlists.

This PR adds a new `Sorting Method` option to the `Playlist Management` interface. This allows the sorting method to be overridden on a per-playlist basis. Available values are `System Default` (reflects `Sort playlists alphabetically` setting), `Alphabetical` and `None`.

Notes:

- Content history playlists are excluded - they are never sorted (this has always been the case!)

- This option is only available when using the 'new' format playlists (i.e. `Save playlists using old format` = `OFF`). There's just not enough room in the old-style playlists for additional metadata. Since pretty much everyone uses the new format (by default), I don't think this is an issue.

- The PR also tweaks the way that the displayed menu entries are handled - previously, it would go as follows:

    - Sort playlist
    - Loop through playlist and generate menu entries
    - Sort menu entries

...not only did this duplicate effort, but it meant there was a chance of the playlist and menu going out of sync - especially when using the `Label Display Mode` feature, which could lead to a different alphabetical ordering when processing the generated menu entries. With this PR, only the playlist is ever sorted, and menu entries are listed in exactly the same order.

## Related Issues

This closes #10359

### CODE REVIEW

**Comment by Ryunam** [comment]
Just tested it, works great. :) Thanks a lot for implementing this so quickly!

**Comment by RobLoach** [comment]
Checked out the branch, compiled and ran. Was able to create a playlist with a non-alphanumeric order.

Screenshot at 2020-04-10 15-36-23

**Comment by jdgleaver** [comment]
@Ryunam @RobLoach Thanks for testing - I really appreciate it!

> Thanks a lot for implementing this so quickly!

Well, it was a week later than I planned...  ;)

Anyway, you're very welcome - always glad to help out!

**Comment by twinaphex** [comment]
Looks good to me.

**Pull request merged**
