### PR TITLE
Enable cheevos for Wii builds

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

This PR enables cheevos for Wii builds by:

1. Extending the Makefile.wii to add the cheevos flags
2. Extend the `rc_compat.c` mutex functions to use libogc.
3. Fix an issue in `net_compat.h` where the network codes where interpreted incorrectly.

Some extra notes:

- I build it using Fedora with the latest libogc and `make -f Makefile.wii -j4 EXTERNAL_LIBOGC=1 GX_PTHREAD_LEGACY=0`. I failed to understand how the build bot environment works (any help is welcome). 
- ~~Getting the achievement list is quite slow on the Wii and its instant on Dolphin.~~ Enabling threaded tasks solves the issue.

## Related Issues

- #14982

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
That's cool.

@Jamiras Can we merge this? I ask because it makes some changes to rcheevos that I hope you are OK with.

**Comment by Jamiras** [comment]
They're `#ifdef`'d, so it shouldn't affect anything outside of the targeted platform. I'll have to incorporate them upstream so they don't get lost in the future.

**Comment by LibretroAdmin** [comment]
OK, how should we proceed? Should I merge first and then you incorporate them upstream afterwards or do you want to incorporate it upstream first and afterward I merge? Up to you.

**Comment by Jamiras** [comment]
You can merge here. Even if I incorporated it upstream right now, I wouldn't want to merge all the other changes at this time.

**Pull request merged**
