### PR TITLE
Fix certain builds for Microsoft platforms

### LINKED ISSUE #15357: (UWP) Broken Builds 4: The Comeback
## Description

Commit https://github.com/libretro/RetroArch/commit/938d60d0f4589a3c6982838176475f077df640a4 broke UWP builds.

@JesseTG Your input would be appreciated here.

### Expected behavior

RetroArch to build.

### Actual behavior

You can guess. Here's the Visual Studio Error List:

image

### Bisect Results

Commit https://github.com/libretro/RetroArch/commit/938d60d0f4589a3c6982838176475f077df640a4 broke things.

### Environment information

- OS: Windows 11
- Compiler: MSVC

### PR DESCRIPTION
**Pull request by JesseTG**
## Description

This pull request does the following:

- Fixes UWP builds
- Fixes most build configurations for MSVC 2019. Configurations that use Cg or Qt on ARM are not yet working; I haven't tested Cg builds (because I'm told that Cg is no longer shipped in mainline builds), and I haven't gotten ARM+Qt builds working yet because I haven't figured out how Qt supports ARM.
- Consolidates repeated parts of the MSVC 2019 project file.
- Introduces a basic workflow that builds all UWP profiles and most MSVC 2019 profiles. This will reduce the chances of a new change breaking these builds.

Once all workflows (including the new ones) pass and the correct artifacts are uploaded, then this PR will be ready to merge.

## Related Issues

Fixes #15357

## Reviewers

@GABO1423
@LibretroAdmin

### CODE REVIEW

**Comment by GABO1423** [comment]
Removing 7zip support from the UWP breaks support for CHD files with RetroAchievements, which is why I added it back in https://github.com/libretro/RetroArch/pull/13669. This flag should be kept as a result.

**Comment by JesseTG** [comment]
Okay, I'll re-add them. What do you want to do about the linker errors?

**Comment by GABO1423** [comment]
> Okay, I'll re-add them. What do you want to do about the linker errors?

I have not encountered any linker errors back when I added the 7Zip build flags, which is why I went ahead and added them.

**Comment by JesseTG** [comment]
Give me a moment and I'll show the errors I encountered. Or they'll mysteriously go away and I'll look like a jackass. Only one way to find out!

**Comment by JesseTG** [comment]
Okay, here they are:

```
"D:\Code\Contributions\RetroArch\pkg\msvc-uwp\RetroArch-msvcUWP.sln" (default target) (1) ->
"D:\Code\Contributions\RetroArch\pkg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj" (default target) (2) ->
(Link target) ->
  griffin.obj : error LNK2019: unresolved external symbol _CreateFileA referenced in function _File_Open [D:\Code\Contributions\RetroArch\pk
g\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
  griffin.obj : error LNK2019: unresolved external symbol _CreateFileW referenced in function _File_OpenW [D:\Code\Contributions\RetroArch\p
kg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
  griffin.obj : error LNK2019: unresolved external symbol _GetFileSize referenced in function _File_GetLength [D:\Code\Contributions\RetroAr
ch\pkg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
  D:\Code\Contributions\RetroArch\pkg\msvc-uwp\Debug\RetroArch-msvcUWP\RetroArch-msvcUWP.exe : fatal error LNK1120: 3 unresolved externals [
D:\Code\Contributions\RetroArch\pkg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
```

**Comment by GABO1423** [comment]
> Okay, here they are:
> 
> ```
> "D:\Code\Contributions\RetroArch\pkg\msvc-uwp\RetroArch-msvcUWP.sln" (default target) (1) ->
> "D:\Code\Contributions\RetroArch\pkg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj" (default target) (2) ->
> (Link target) ->
>   griffin.obj : error LNK2019: unresolved external symbol _CreateFileA referenced in function _File_Open [D:\Code\Contributions\RetroArch\pk
> g\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
>   griffin.obj : error LNK2019: unresolved external symbol _CreateFileW referenced in function _File_OpenW [D:\Code\Contributions\RetroArch\p
> kg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
>   griffin.obj : error LNK2019: unresolved external symbol _GetFileSize referenced in function _File_GetLength [D:\Code\Contributions\RetroAr
> ch\pkg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
>   D:\Code\Contributions\RetroArch\pkg\msvc-uwp\Debug\RetroArch-msvcUWP\RetroArch-msvcUWP.exe : fatal error LNK1120: 3 unresolved externals [
> D:\Code\Contributions\RetroArch\pkg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]
> ```

Meanwhile....
image

**Comment by JesseTG** [comment]
Well, damn. We can't exactly ignore these errors, otherwise some other poor soul will run into them.

The offenders are `_CreateFileA`, `_CreateFileW`, and `_GetFileSize`. If I remember correctly, UWP doesn't provide those functions. So why aren't you seeing this problem? Any ideas?

**Comment by GABO1423** [comment]
> Well, damn. We can't exactly ignore these errors, otherwise some other poor soul will run into them.
> 
> The offenders are `_CreateFileA`, `_CreateFileW`, and `_GetFileSize`. If I remember correctly, UWP doesn't provide those functions. So why aren't you seeing this problem? Any ideas?

My first guess might be some differences with our build environments, maybe you are missing a component I have or my settings are different enough to get past the errors. Can you describe the build process? Maybe we can find some variables that way.

**Comment by JesseTG** [comment]
Sure.

1. `git clean -xdf`
2. `cd $RETROARCH_SOURCE_DIR/pkg/msvc-uwp`
3. `msbuild -p:Configuration=Debug -p:Platform=x64 -fileLogger .\RetroArch-msvcUWP.sln`
4. [This log file.](https://github.com/libretro/RetroArch/files/11780430/msbuild.log)

**Comment by GABO1423** [comment]
Btw to answer your question from Discord, the most useful artifact to use is the ReleaseANGLE x64 build, since it includes ANGLE support to circumvent the lack of OpenGL support, allowing three cores to work (Mupen64Plus-Next, ParaLLEl-N64, and YabaSanshiro). But there's an added wrinkle with this, the builds need to be signed with the pfx file in the `msvc-uwp` folder in order for an user to be able to install it. Without that step, the user would need to sign the appx file themselves.

**Comment by GABO1423** [comment]
> Sure.
> 
> 1. `git clean -xdf`
> 2. `cd $RETROARCH_SOURCE_DIR/pkg/msvc-uwp`
> 3. `msbuild -p:Configuration=Debug -p:Platform=x64 -fileLogger .\RetroArch-msvcUWP.sln`
> 4. [This log file.](https://github.com/libretro/RetroArch/files/11780430/msbuild.log)

I was able to replicate the errors this way, I'll try the command with the Release configuration now, the error could be related to using the Debug configuration.

**Comment by JesseTG** [comment]
The pipeline I included is only intended to prevent compiler errors and upload the basic artifacts to GitHub, as is the case for the other GitHub workflows; it is not designed to produce a build that's ready for end users. I don't know enough about UWP to do that off the top of my head.

**Comment by GABO1423** [comment]
> The pipeline I included is only intended to prevent compiler errors and upload the basic artifacts to GitHub, as is the case for the other GitHub workflows; it is not designed to produce a build that's ready for end users. I don't know enough about UWP to do that off the top of my head.

In that case you can stick to the Release and ReleaseANGLE x64 builds, the ARM builds are only useful for ARM Windows PCs, and Win32/x86 is not that useful nowadays.

**Comment by JesseTG** [comment]
Gotcha. Okay, fingers crossed. If all checks pass, then this PR will be ready to be merged (unless @LibretroAdmin says otherwise).

**Comment by GABO1423** [comment]
@JesseTG I found the issue:

```  D:\Code\Contributions\RetroArch\pkg\msvc-uwp\x64\Debug\RetroArch-msvcUWP\**x86**\RetroArch-msvcUWP\RetroArch-msvcUWP.exe : fatal error LNK1120: 3 unresolved externals [D:\Code\Contributions\RetroArch\pkg\msvc-uwp\RetroArch-msvcUWP\RetroArch-msvcUWP.vcxproj]```

It's building not only for x64, but also for Win32 for some reason. I checked the files and it did produce a x64 appx build just fine.

**Comment by JesseTG** [comment]
> It's building not only for x64, but also for Win32 for some reason.

Ah, I'd meant to ask you about that. Any ideas here? I'm gonna venture a guess that something is screwy with intra-solution dependencies, but I don't know what that would look like here.

**Comment by GABO1423** [comment]
> > It's building not only for x64, but also for Win32 for some reason.
> 
> Ah, I'd meant to ask you about that. Any ideas here? I'm gonna venture a guess that something is screwy with intra-solution dependencies, but I don't know what that would look like here.
> 
> This will have to be fixed too. Not only will it slow down future PRs, but it'll cause unnecessary errors.

I found a lead, it's regarding a line the UWP vcxproj file, I'm looking further into possible fixes.

**Comment by JesseTG** [comment]
Thank you, I appreciate it.

**Comment by GABO1423** [comment]
> Thank you, I appreciate it.

Try removing this line from the UWP vcxproj file: `<AppxBundlePlatforms>x86|x64|arm|arm64</AppxBundlePlatforms>`, it's on line 106.

You should also use this command as it has the proper MSBuild syntax: `msbuild /p:Configuration=Release /p:Platform=x64 RetroArch-msvcUWP.sln`

**Comment by JesseTG** [comment]
> > Thank you, I appreciate it.
> 
> Try removing this line from the UWP vcxproj file: `<AppxBundlePlatforms>x86|x64|arm|arm64</AppxBundlePlatforms>`, it's on line 106.

Trying this out now, let's see what happens.

> You should also use this command as it has the proper MSBuild syntax: `msbuild /p:Configuration=Release /p:Platform=x64 RetroArch-msvcUWP.sln`

Actually, the `--help` output says that `-p` is okay, too.

```msbuild --help

...

Switches:            Note that you can specify switches using
                     "-switch", "/switch" and "--switch".
```

**Comment by GABO1423** [comment]
Seems it worked! To give some explanation into the issue, RetroArch is set to generate a bundle file (a file that has multiple appx files at once), so that line basically told MSBuild to build all of the configurations and then bundle them together, even if the user only specified one configuration. With the line gone, the bundle will only include files from the current build platform and nothing else. 

This might mean x86 builds are broken? I would have test separately to make sure, but as I stated, x86 builds for UWP are not that useful since the majority of UWP users play on Xbox consoles, which are x64 only.

**Pull request merged**
