### PR TITLE
Fixed some Monitor index bugs ad updated to the latest SR2

### PR DESCRIPTION
**Pull request by alphanu1**
Added new SR_CONFIG_PATHS for non Windows and Linux systems.
Not that SR works on them but to fix RA compile issues. Fixed by TA in the passed 
but now given them more meaningful names.

Updated SR2 code base to latest. Added support for windows monitor indexing.
Fixed monitor index bug where index 1 was not being used correctly
and "auto" was not being sent.

@twinaphex

### CODE REVIEW

**Comment by alphanu1** [comment]
@twinaphex hold off on this merge. We are investigating another Windows bug

**Comment by twinaphex** [comment]
Hi there, let me know when you think this is ready.

**Comment by alphanu1** [comment]
@twinaphex will do. Just ironing out a few more issues in SR2

**Comment by alphanu1** [comment]
@twinaphex All ready to go :smiley:

**Pull request merged**
