### PR TITLE
3ds icons and banners

### PR DESCRIPTION
**Pull request by 44100hertz**
enjoy 💯

### CODE REVIEW

**Comment by twinaphex** [comment]
I have some problems with putting this inside the RetroArch repo, we don't want even more image files in what should be a source-only repo. I might have to find another repo where we could add this to instead - maybe retroarch-assets. Let me think of this some more.

**Comment by 44100hertz** [comment]
Makes enough sense.
https://github.com/44100hertz/libretro-3ds-svg
By the way, here's the vectors.

**Comment by twinaphex** [comment]
Thanks.

Yeah, seems like it's best if we start moving this to retroarch-assets instead, that is where our other svg/vector images currently are as well.

**Comment by 44100hertz** [comment]
Well, I can PR them there as well if it's easier, just not sure how it should be organized.

**Comment by twinaphex** [comment]
I guess for now we can merge it as-is since the files already exist anyway. Longer-term I might look at moving this to retroarch-assets or something similar like that.

**Comment by aliaspider** [comment]
thanks for this.
just a small comment for the future, it would be better to keep the old assets in there so they aren't lost forever, and to have more selection.
I'll just re-add them later so this isn't a big deal right now.

**Comment by 44100hertz** [comment]
They're not lost...that's why we're using git.

**Pull request merged**
