### PR TITLE
Add a configurable workaround for Android reconnecting devices

### PR DESCRIPTION
**Pull request by phcoder**
Closes https://github.com/libretro/RetroArch/issues/3414

### CODE REVIEW

**Comment by ofry** [comment]
@phcoder This PR has merge conflicts. Please resolve them.

**Comment by phcoder** [comment]
Rebased
@twinaphex can we merge this?

**Comment by MastaG** [comment]
So is this PR already merged into the RetroArch Plus version in the Google Play Store?
If yes, where can I find this option?

**Comment by Nickneo3** [comment]
Same doubt... please give us some answer. Thanks

**Comment by javito1081** [comment]
> So is this PR already merged into the RetroArch Plus version in the Google Play Store? If yes, where can I find this option?

Any response to this?

**Comment by kold666number** [comment]
Solved here: https://github.com/libretro/RetroArch/issues/3414#issuecomment-1474342394

**Pull request merged**
