### PR TITLE
Analog buttons

### PR DESCRIPTION
**Pull request by hiddenasbestos**
Added support for analog buttons. Cores can use the new libretro.h constant to request analog input from any RetroPad button. I've submitted a pull request for the Sega Saturn core to implement this.

Note this feature simply detects analog inputs bound to retropad controls and allows the core to query the true analog value. It's optional in the case of an older version of RetroArch and an analog enabled core if you follow the reference implementation:

```
static uint16_t get_analog_button( retro_input_state_t input_state_cb,
                                   int player_index,
                                   int id )
{
    uint16_t button;

    // NOTE: Not all front-ends support analog buttons (or pre-date it) 
    // so we need to handle this in a graceful way.

    // First, try and get an analog value using the new libretro API constant
    button = input_state_cb( player_index,
                             RETRO_DEVICE_ANALOG,
                             RETRO_DEVICE_INDEX_ANALOG_BUTTON,
                             id );

    if ( button == 0 )
    {
        // If we got exactly zero, we're either not pressing the button, or the front-end
        // is not reporting analog values. We need to do a second check using the classic
        // digital API method, to at least get some response - better than nothing.

        // NOTE: If we're honestly just not holding the button, we're still going to get zero.

        button = input_state_cb( player_index,
                                 RETRO_DEVICE_JOYPAD,
                                 0,
                                 id ) ? 0x7FFF : 0;
    }

    return button;
}
```

### CODE REVIEW

**Comment by retro-wertz** [comment]
oh, a PR is already here.. anyways why just analog button? isnt L2 and R2 analog triggers?

anyways, a separate and more descriptive name for each left/right analog triggers would be better i believe in the long run. what if one of the analog button is busted and does not center(or returns 0) properly(mostly happens to 360 controllers) wouldnt that offset the returned value for the other button? I think thats how i understand this implementation is.

**Comment by hiddenasbestos** [comment]
(I'm not really understanding you I think, sorry about that.)

This change makes all inputs (face buttons, d-pad, shoulder buttons, etc.) on the base RetroPad virtual controller available as analog if the front-end can provide the data. This includes the L2/R2 inputs which the user will have likely mapped to the triggers of their IRL gamepad given that the naming in the RetroArch UI calls them triggers.

In terms of changing the control naming to something else, that's an issue to take up with the RetroArch developers. However I think it's pretty clear that the user should map L2/R2 to the analog triggers on their controller if they've got them -- this change simply lets the core have access to controls mapped to axes as true analog inputs instead of boolean values.

**Comment by fr500** [comment]
I guess this also means we could use something like... 
Fireshock https://github.com/nefarius/FireShock to have pressure sensitive buttons in a PS2 emulator sometime in in the future.

@nefarius

**Comment by twinaphex** [comment]
I agree with the implementation of this. It doesnt break ABI, it also doesnt break normal behavior of existing fronts, its an optional thing for frontends to add, its the best we could hope for given these design considerations.

**Comment by nefarius** [comment]
Cool!

**Pull request merged**
