### PR TITLE
(UPnP) Support for IPv4 tunneling

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**
## Reviewers

@fr500

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
It seems @fr500 is better able to test this when it's merged, so I'll take the plunge and merge it.

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway We have a build failure on 3DS now -

griffin/../network/natt.c: In function 'addr_6to4':
griffin/../network/natt.c:85:28: error: invalid use of undefined type 'struct sockaddr_in6'
   85 |          if (!memcmp(&addr6->sin6_addr, preffix, sizeof(preffix)))
      |                            ^~
griffin/../network/natt.c:92:38: error: invalid use of undefined type 'struct sockaddr_in6'
   92 |    memcpy(&address, ((uint8_t*)&addr6->sin6_addr) + sizeof(preffix),
      |                                      ^~
griffin/../network/natt.c:94:16: error: invalid use of undefined type 'struct sockaddr_in6'
   94 |    port = addr6->sin6_port;
      |                ^~

https://git.libretro.com/libretro/SquirrelJME/-/jobs/2112763

**Comment by LibretroAdmin** [comment]
Going to try seeing if defining HAVE_SOCKET_LEGACY will fix the build failure.

**Comment by LibretroAdmin** [comment]
It seems to build now at least. Disappointing that apparently socket support is this premature on 3DS too.

I noticed this in the code too which we might have missed before -

https://github.com/libretro/RetroArch/blob/master/network/netplay/netplay_frontend.c#L81

So now that 3DS defines HAVE_SOCKET_LEGACY too, I will just take that _3DS part out.

**Comment by LibretroAdmin** [comment]
Here are some other things I discovered BTW when reading the compilation logs for RetroArch on other console platforms -

here is what Wii reports -

> libretro-common/net/net_compat.c: In function 'inet_ntop_compat':
libretro-common/net/net_compat.c:651:11: warning: implicit declaration of function 'inet_ntop'; did you mean 'inet_ntoa'? [-Wimplicit-function-declaration]
  651 |    return inet_ntop(af, src, dst, cnt);
      |           ^~~~~~~~~
      |           inet_ntoa
libretro-common/net/net_compat.c:651:11: warning: returning 'int' from a function with return type 'const char *' makes pointer from integer without a cast [-Wint-conversion]
  651 |    return inet_ntop(af, src, dst, cnt);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

So we need to look at what we could use instead for inet_ntop for when GEKKO is defined

**Comment by Cthulhu-throwaway** [comment]
> Going to try seeing if defining HAVE_SOCKET_LEGACY will fix the build failure.

Setting HAVE_SOCKET_LEGACY for the 3DS will hide some features that are available for it, such as net_ifinfo.

I recommended reverting those last two PRs and just adding "!defined(_3DS)" to addr_6to4.

**Comment by Cthulhu-throwaway** [comment]
> Here are some other things I discovered BTW when reading the compilation logs for RetroArch on other console platforms -
> 
> here is what Wii reports -
> 
> > libretro-common/net/net_compat.c: In function 'inet_ntop_compat':
> > libretro-common/net/net_compat.c:651:11: warning: implicit declaration of function 'inet_ntop'; did you mean 'inet_ntoa'? [-Wimplicit-function-declaration]
> > 651 |    return inet_ntop(af, src, dst, cnt);
> > |           ^~~~~~~~~
> > |           inet_ntoa
> > libretro-common/net/net_compat.c:651:11: warning: returning 'int' from a function with return type 'const char *' makes pointer from integer without a cast [-Wint-conversion]
> > 651 |    return inet_ntop(af, src, dst, cnt);
> > |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> So we need to look at what we could use instead for inet_ntop for when GEKKO is defined

Yeah, I've been aware of that for a while, but that isn't my code and I don't develop for the Wii.

It's currently not used, which is why it's just a warning rather than error, but if you want to silence that warning, you should make the function nop for the Wii and add a TODO/FIXME comment.

**Comment by LibretroAdmin** [comment]
> > Going to try seeing if defining HAVE_SOCKET_LEGACY will fix the build failure.
> 
> Setting HAVE_SOCKET_LEGACY for the 3DS will hide some features that are available for it, such as net_ifinfo.
> 
> I recommend reverting those last two PRs and just adding "!defined(_3DS)" to addr_6to4.

Alright, can we find out though why IPv6 support is not available or if there are ways to do this on 3DS? @MrHuu got any ideas?

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway OK, done -

https://github.com/libretro/RetroArch/commit/01eab0fba591e145621c595127a970a9024348f5

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway @fr500 confirmed that it solved the issues for him on Android, so that's good to hear.

**Pull request merged**
