### PR TITLE
(Cheevos) By default, have Hardcore Mode be disabled

### PR DESCRIPTION
**Pull request by RobLoach**
There have been some users who report inability to load save states. This is because they enable Achievements, but don't realize Hardcore Mode is enabled. This change makes Hardcore Mode be disabled by default, so that the user has to opt-in to Hardcore Mode, making them understand that it will also disable load states.

### CODE REVIEW

**Comment by Jamiras** [comment]
The default for hardcore was specifically changed to ON in #13238.

> The default value of Hardcore Mode has been changed to ON. We want to encourage players to play in Hardcore. It's easy enough to disable (or pause) if they don't find it to their liking.

If they are enabling Achievements, they should have some idea of what they're getting themselves into.

**Comment by RobLoach** [comment]
@Jamiras Thanks for the context! I believe the other options make perfect sense. Saw like 3 reports of users saying they couldn't Load State, and noticed it was because of Hard Mode. It appears they didn't know what they were getting themselves into.

**Comment by Sanaki** [comment]
Unfortunately this is a problem with no distinct correct answer. With hardcore default off, users have complained they feel cheated when they find out they didn't earn hardcore credit for the games they played, not knowing it made a difference. We've had users asking us to make hardcore default for years because of this. I recognize there's an issue with people enabling achievements and not understanding the implications, but I'm not sure just turning it back off is the correct solution to that.

**Comment by Keltron3030** [comment]
Ideally it should be hardcore by default with a pop-up when a load state is attempted indicating "Retroachievement hardcore mode on (load state disabled)".

**Comment by RobLoach** [comment]
Made a follow up issue for this over at https://github.com/libretro/RetroArch/issues/13469 ... THANKS ALL!

**Pull request merged**
