### PR TITLE
Found a combination that doesn't work

### PR DESCRIPTION
**Pull request by loganmc10**

### CODE REVIEW

**Comment by twinaphex** [comment]
@loganmc10 - Can you retest on Android?

Maybe the buildbot nightly will update itself again today, right now on the current nightly build though, in MaterialUI, the blue bars are black, and the highlighted background is of a blackish color too.

**Comment by loganmc10** [comment]
Ya that's why I sent these commits, hopefully the buildbot will update and i can test that, compiling RetroArch for Android is a bit of a task

**Comment by loganmc10** [comment]
OK just tested the  build bot version and it looks good again, sorry about all that

**Comment by twinaphex** [comment]
Yeah I tested the latest f-droid version now and it looks OK again, thanks.

**Pull request merged**
