### PR TITLE
remove task_push_http_transfer_raw, encode before sending data to the…

### PR DESCRIPTION
**Pull request by fr500**
I messed up the old PR so here it goes again.

Old PR: https://github.com/libretro/RetroArch/pull/6401

Everything seems to be working properly with this

### CODE REVIEW

**Comment by meleu** [comment]
what happens when submitting a PR from the master branch of a fork :sweat_smile:

**Comment by fr500** [comment]
yeah I didn't want to have unrelated stuff to the PR in the PR :P

**Comment by twinaphex** [comment]
OK, does this PR still need to be reviewed by somebody or are we good here?

**Comment by fr500** [comment]
We're good

**Pull request merged**
