### PR TITLE
Small fix for low res cores for CRT switching < 200

### PR DESCRIPTION
**Pull request by alphanu1**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by alphanu1** [comment]
Hey @twinaphex 

I am going to add the code for the new options this weekend. Could you let me know how to tie into them please?

Cheers,

**Comment by twinaphex** [comment]
@alphanu1 You will need to add 'action OK' callbacks for the new settings if they weren't added already. I assume you know how to do this already?

If not, as stated before, you will really need to come to Discord so we can communicate in realtime so I can walk you through this.

**Comment by alphanu1** [comment]
Yeah, should be fine.

**Comment by twinaphex** [comment]
Anyway, I'm not really sure how you want to implement thing and whatnot, I just added the settings to the configuration struct and I also added menu entries. What happens from there is up to you, I hope at least to leave the implementation up to you as I have not really used this feature in practice at all.

One thing though - we need CRT SwitchRes to at least work as well as it did in the previous version (1.7.4), otherwise I won't be able to release a version 1.7.5. So I'm not sure if things right now are broken, but if it is, it is imperative this gets fixed as soon as possible so  that the release of 1.7.5 does not have to be postponed.

**Comment by alphanu1** [comment]
OK, No worries. What is your planned release date? I''ll make sure its defiantly sorted before then.

**Comment by twinaphex** [comment]
Not sure to be honest. The sooner these features are in the better from my point of view.

Also, I very much appreciate your commits and your features, so hopefully none of it is seen as pushy or even as criticism.

**Pull request merged**
