### PR TITLE
Add Optimize for GamePad option on Wii U

### PR DESCRIPTION
**Pull request by vaguerant**
**EDIT:** This initial description has become a bit outdated. What this PR now does is add an option Video -> Output -> Optimize for Wii U GamePad, which switches to a 960p viewport if the user is running at either 720p or 1080p.

## Description

This switches to a 960p viewport when running at 1080p on the Wii U, sacrificing some sharpness on the TV for greatly improved sharpness on the GamePad.

I say don't merge because this should probably be optional, but I don't know how to do that. There is probably *some* use case for having native 1080p on Wii U, I just don't know what it is.

## Explanation

The Wii U is a weird case with RetroArch because of the two screens (TV and Wii U GamePad). The Wii U can be configured to output video at 480p, 720p or 1080p (or interlaced equivalents), whereas the GamePad has a native 480-line display. While it is possible to send different images to the TV and GamePad, RetroArch currently sends the same image to both. This creates a bit of a conundrum as 480 does not divide evenly into any of the other available resolutions.

When running 240p content, setting the Wii U to 720p *just works*, because a 3x integer scale (240\*3 = 720) on the TV also happens to be a 2x integer scale (240\*2 = 480) on the GamePad. However, when running 480p content, having the Wii U set to 720p will result in a poor image all around, with non-integer scaling from 480->720 on the TV, and then even worse, 480->720->480 on the GamePad.

Running the Wii U at 1080p, you get the worst of all worlds. Absolutely nothing divides evenly into 1080, so no matter what content you're playing, you'll need either large borders or a filter/shader to stretch to that non-integer resolution, and putting that 1080p image back on the 480p GamePad makes it even worse again. Many users only use 720p because of the poor results you get from 1080p currently.

By running 1080p with a 960p viewport, you can do things like a 4x integer scale of 240p content which becomes a 2x integer scale on the GamePad, or a 2x scale of 480p content which becomes a 1x native display on the GamePad. Even more exotic resolutions like the Game Boy Advance (160p) are enhanced, with 160 dividing 6x into 960 or 3x into 480. This one change makes 1080p a lot less useless on Wii U.

## Related Issues

#11383 is a feature request about making the viewport on Wii U customizable. This does not do that, but addresses how poorly suited 1080p is to the Wii U, which is part (or even most) of what that issue is about.

## Reviewers

@gblues, ideally I think you or somebody else who's capable and interested could make this optional on Wii U before merging. If this does happen, I have no opinion about whether it should default to on or off.

### CODE REVIEW

**Comment by gblues** [comment]
What do you think about adding an "Optimize for Gamepad" option for the Wii U build?
- when "Optimize for Gamepad" is OFF: use the system output resolution (current behavior)
- when "Optimize for Gamepad" is ON, pick the closest resolution from #11383 based on the system resolution (similar to this PR, but a little cleaner)

**Comment by vaguerant** [comment]
@gblues, that sounds like a very attractive approach, I like it, with one minor exception.

After thinking on it further, I believe 1708 \* 960 is the best "Optimize for GamePad" resolution for *both* 720p and 1080p. 1138 \* 640 is **only** useful for 160p content and bad for everything else, Native 1280 \* 720 is **only** useful for 240p content and bad for everything else. 960p, on the other hand works for all kinds of content.

# Explanation
720p is a weird case where "Optimize for GamePad" would otherwise have to mean different things for different content,.

Quoting and adding to the table in the earlier issue:
||854 \* 480|1138 \* 640|1280 \* 720|1708 \* 960|
|:-:|:-:|:-:|:-:|:-:|
|**160p**|3x / 3x|4x / 3x|NA: 4.5x / 3x|6x / 3x|
|**240p**|2x / 2x|N/A: 2.66...x / 2x|3x / 2x|4x / 2x|
|**480p**|1x / 1x |N/A: 1.33...x / 1x|N/A: 1.5x / 1x|2x / 1x|

Specifically looking at 1138 \* 640 and 1280 \* 720 there, the former is a good viewport for 160p (GBA) content, while the latter is perfect for 240p (basically every retro console) content, in terms of getting a clean image on both the TV and GamePad. For 480p content, 720p is kind of just boned, you'd have to drop all the way down to an 854 \* 480 viewport to get a 1x/1x image.

Instead, I think the most usable and simple option here is for "Optimize for GamePad" to have the following behavior:
|Wii U resolution|Behavior|Viewport size|
|:-:|:-:|:-:|
|480p|do nothing|854 \* 480|
|720p|enlarge viewport|1708 \* 960|
|1080p|shrink viewport|1708 \* 960|

As far as I'm aware, there's nothing preventing RetroArch from using a viewport that's larger than the output resolution, and in this case doing so actually preserves what makes 720p good ("native" support for 240p) while "adding" support for the other major resolutions. Table time again.

|Content resolution|Size in 960p viewport|Size in actual 720p output|Size on GamePad|
|:-:|:-:|:-:|:-:|
|240 \* 160|6x: 1440 \* 960|4.5x: 1080 \* 720|3x: 720 \* 480|
|320 \* 240|4x: 1280 \* 960|3x: 960 \* 720|2x: 640 \* 480|
|640 \* 480|2x: 1280 \* 960|1.5x: 960 \* 720|1x: 640 \* 480|

By the nature of linear filtering, 720p's current strong point (240p content) should look identical when rendered to a 960p viewport then linear filtered down to 720p as it does currently being rendered to 720p directly. Then, while 160p and 480p content is non-integer linear scaled, the GamePad is once again getting native 1:1 or 3:1 pixels respectively.

Ultimately, "Optimize for GamePad" really needs to be an integer multiple of 480 to have good results everywhere, so the only real options are 1x: 480p or 2x: 960p. The end result of either should be identical on the GamePad, but 720p and 1080p TVs will benefit from the extra sharpness of running with an internal viewport of 960p.

The one downside of this approach is that it might be confusing to users when their Wii U configured to run at 720p "supports" 960p within RetroArch. However, I don't think that's much more confusing than the opposite scenario where 1080p users find that RetroArch "only" runs at 960p with this option enabled. I think this is acceptable and can be explained pretty simply in the tooltip for the option in the GUI by saying it forces RetroArch to run at an integer multiple of the Wii U GamePad's resolution.

Sorry this comment got so long.

**Comment by twinaphex** [comment]
Hi @vaguerant , what if you added a 'resolution' setting for this? You could look at the way it's implemented for 'Win32' and then maybe follow suit. I do think this would require making a 'display server' driver for WiiU though (for reference, you can look at gfx/display_servers.

@gblues What's your thoughts on that idea? It'd allow us to select between multiple resolutions that way.

**Comment by gblues** [comment]
I don't think a resolution selection is a good UX for Wii U.

This isn't a PC where the video hardware can drive arbitrary displays of arbitrary resolutions. The Wii U only supports standard TV resolutions, and users typically choose the one they want in the Wii U setup--making a resolution selection within RA redundant.

What *would* be cool is having independent resolutions for the gamepad vs the TV screen, but I don't know how much work it would take to implement that.

**Comment by vaguerant** [comment]
I agree, gblues. The thing here is that adjusting viewports to suit two screens simultaneously is a bit of a stopgap solution, so leaning into something more structured and "permanent" like a whole resolution configuration on Wii U seems like moving in the wrong direction. In a perfect world, RetroArch would be driving the two screens completely independently, right down to things like different shader choices for each screen--sometimes the things that look good at 1080p don't look so good at 480p.

But that seems like an enormous undertaking and there's not exactly a surplus of Wii U devs around looking to fundamentally overhaul how RetroArch functions on the platform. Short of supporting the screens separately, I do think there's merit in having a simple and relatively user-friendly option to select whether to prioritize fidelity on the TV or the GamePad.

The GamePad is particularly underserved at the moment because 480p is a fairly low resolution for the size of the display, so it really does look pretty poor when displaying non-native resolutions. The 720p/1080p output on the TV is a lot more resilient--960p scaled to 1080p looks totally fine at couch distance, while 1080p scaled to 480p looks miserable at lap distance.

**Comment by vaguerant** [comment]
@gblues, I just force-pushed a version that does what we talked about earlier: adds an option Video -> Output -> Optimize for GamePad, which uses a 960p viewport if the user is on either 720p or 1080p (if they're on 480p, they're already optimized for GamePad). It defaults to off, so the native TV resolution is still preferred out of the box.

It seems to work fine to me--toggles on and off, saves to/loads from the config file correctly, but as basic as this is, it's still the most complex thing I've ever done with the RetroArch code, so it definitely should be reviewed before merging is considered. If any of it looks wrong, it probably is. In particular, somebody should make sure this is all right in `menu/menu_setting.c`, as it's mostly copy-paste work and not something where I actually understand what I'm reading:
```
#ifdef WIIU
            CONFIG_BOOL(
                  list, list_info,
                  &settings->bools.video_wiiu_prefer_drc,
                  MENU_ENUM_LABEL_VIDEO_WIIU_PREFER_DRC,
                  MENU_ENUM_LABEL_VALUE_VIDEO_WIIU_PREFER_DRC,
                  DEFAULT_WIIU_PREFER_DRC,
                  MENU_ENUM_LABEL_VALUE_OFF,
                  MENU_ENUM_LABEL_VALUE_ON,
                  &group_info,
                  &subgroup_info,
                  parent_group,
                  general_write_handler,
                  general_read_handler,
                  SD_FLAG_NONE);
#endif
```
Review highlight for @jdgleaver.

**Comment by jdgleaver** [comment]
@vaguerant Good job - the code here looks fine :)

There is only a very trivial style nit regarding braces:

https://github.com/libretro/RetroArch/pull/13257/files#diff-63886d17a2328563e24f1361d68019c29f2c024268da14a65e225958eba3e6acR255-R261
https://github.com/libretro/RetroArch/pull/13257/files#diff-63886d17a2328563e24f1361d68019c29f2c024268da14a65e225958eba3e6acR453-R463

In the RA codebase we standardise on Allman style - i.e. this:

```c
if ()
{
}
else
{
}
```

instead of this:

```c
if () {
} else {
}
```

**Comment by vaguerant** [comment]
Thanks @jdgleaver, glad to hear I didn't horribly break anything. 👍

Just pushed another commit to match the RA standard. I can force push if you prefer it in a single commit, but I see squash merges are used here, so I figured it wasn't particularly problematic.

**Comment by jdgleaver** [comment]
Thanks, that's great!

>  I can force push if you prefer it in a single commit, but I see squash merges are used here, so I figured it wasn't particularly problematic.

Yes, a squash merge here should be fine

**Comment by twinaphex** [comment]
Alright @vaguerant , it took some time but I'm merging this now. Thanks for your patience.

**Pull request merged**
