### PR TITLE
qb: Don't set IFS.

### PR DESCRIPTION
**Pull request by orbea**
Its not really good practice to set `$IFS` and then neglect to reset it to its original value which is `<space><tab><newline>`. That said working with IFS is not fun and its not needed here so this commit should work around its use here.

### CODE REVIEW

**Comment by bparker06** [comment]
Does this somehow interfere with IFS used elsewhere in the script? Personally I think this makes the code a lot harder to read as most people may not know what the special characters inside a variable block does.

**Comment by orbea** [comment]
It does not interfere. The special characters are well defined in any POSIX shell and avoid problems associated with IFS. However if you do not like this it does have to be merged, but if its not the script should take care to set the `$IFS` to its original value. This PR could help with that. https://github.com/libretro/RetroArch/pull/5713

**Comment by orbea** [comment]
From the `yash` man page (It has a nice man page).
```
           #word
               The shell performs pattern matching against the value that
               is being expanded, using word as a pattern. If word
               matches the beginning of the value, the matching part is
               removed from the value and the other part remains as
               expansion results. The shortest matching is used if more
               than one matching is possible.

           ##word
               This is similar to #word above. The only difference is
               that the longest matching is used if more than one
               matching is possible.

           %word
               This is similar to #word above. The only difference is
               that matching is tried at the end of the value rather than
               at the beginning: if word matches the end of the value,
               the matching part is removed from the value and the other
               part remains as expansion results.

           %%word
               This is similar to %word above. The only difference is
               that the longest matching is used if more than one
               matching is possible.
```
This has been used since before I touched the script. I just added more of it here.

**Comment by orbea** [comment]
In case its not clear the other symbols are literal. If you want to understand how this works better try this test script.
```
#!/bin/sh

while read -r VAR COMMENT; do
  echo "VAR = $VAR"
  echo "COMMENT = $COMMENT"
  TMPVAR="${VAR%=*}"
  COMMENT="${COMMENT#*#}"
  VAL="${VAR#*=}"
  VAR="$(echo "${TMPVAR#HAVE_}" | tr '[:upper:]' '[:lower:]')"
  echo "TMPVAR = $TMPVAR"
  echo "COMMENT = $COMMENT"
  echo "VAL = $VAL"
  echo "VAR = $VAR"
done < 'qb/config.params.sh'
```
And example output.
```
VAR = HAVE_VIDEOPROCESSOR=auto
COMMENT = # Enable video processor core
TMPVAR = HAVE_VIDEOPROCESSOR
COMMENT =  Enable video processor core
VAL = auto
VAR = videoprocessor
VAR = HAVE_VIDEOCORE=auto
COMMENT = # Broadcom Videocore 4 support
TMPVAR = HAVE_VIDEOCORE
COMMENT =  Broadcom Videocore 4 support
VAL = auto
VAR = videocore
```

**Comment by orbea** [comment]
Additionally this commit can be easily tested with `./configure --help`.

**Pull request merged**
