### PR TITLE
Add core options v1 to v2 conversion script

### PR DESCRIPTION
**Pull request by DisasterMo**
## Description

Adds a python 3 script to aid in converting core options from v1 to v2.
Just copy 'libretro_core_options.h' into the same folder as this script and run it. You'll have a nice 'libretro_core_options_v2.h' to start working on!

## Related Pull Requests

#12749

## Reviewers

@twinaphex

### CODE REVIEW

**Comment by jdgleaver** [comment]
This is grade A stuff. Incredibly useful!

@twinaphex I'd recommend merging this ASAP

**Comment by DisasterMo** [comment]
Rebased & cleaned up a little. Just to make the script a bit more useful, it now converts both `libretro_core_options.h` and `libretro_core_options_intl.h`, if present.

**Comment by DisasterMo** [comment]
A couple examples; left: original v1, right: converted v2
converter_comp1
converter_comp2

**Comment by jdgleaver** [comment]
Excellent - thank you!

**Pull request merged**
