### PR TITLE
Update video_defines.h

### PR DESCRIPTION
**Pull request by Gagert**
Using the beetle PSX core in RetroArch, it has occurred to me that different ps1 games runs at different aspect ratios. If I take an ingame screenshot of a 2D sprite-based ps1 game while in RetroArch, the image itself reveals the games true native resolution.

As of now I have stumbled upon several different resolutions for 2D sprite-based games for the ps1:

256x240 = 16:15 Aspect Ratio (Already available in RetroArch)
320x240 = 4:3 Aspect Ratio (Already available in RetroArch)
320x252 = 80:63 (Not available in RetroArch)
364x240 = 91:60 (Not available in RetroArch)

I've added the 80:63 Aspect Ratio for games ps1 games running at the odd native resolution of 320x252 (PAL games such as Hugo, Hugo 2 and Mickey's Wild Adventure), and also the 91:60 Aspect Ratio for ps1 games running at the also odd resolution of 364x240 (both the Oddworld games).

### CODE REVIEW

**Comment by hhromic** [comment]
**Careful with this PR.** It once again changes the aspects ratios enum, causing the indexes to shift. This type of change is *very* annoying for users of the "custom" aspect ratio because they have to reconfigure all their overrides for the new shifted index. See for example Issue #7536 and the issues referencing it.

There are a number of possible solutions, for example in the Issue, it is suggested to use human-readable labels instead of raw indexes for the config files. Another solution could be to move the custom aspect ratio to the top of the enum so it doesn't get shifted every time a new AR is added. As a good practice, enums should grow from the bottom always, never in the middle, to avoid this problem.

A solution should be discussed before continuing to add new AR entries, otherwise users will get pissed.

**Comment by Gagert** [comment]
I understand; the last time I updated RetroArch it messed up my custom configs because of this; the "custom" aspect ratio was moved and I had to update all my config files.

Moving "custom" aspect ratio to the top would be a good move I suppose. I was thinking about moving the lines I wrote below the ASPECT_RATIO_CUSTOM line, but then those odd aspect ratio would maybe be shown before the more ordinary ones such as 4:3 and so on and create confusion.

Being able to create custom aspect ratios could be more ideal I suppose.

**Comment by dankcushions** [comment]
yes absolutely please let this be the straw that breaks the camel's back and the aspect ratios are finally put into a sensible maintainable format. i suggested some in issue https://github.com/libretro/RetroArch/issues/7536

also to the issue at hand - @Gagert are you sure you're not confusing resolution with aspect ratio? PSX games were played on 4:3 TVs so they are almost always intended to be 4:3 (some few games had a 16:9 mode). tvs don't have to have 'square' pixels.

if you used integer scaling in retroarch you would get a 1:1 pixel mode which would give you want you want.

**Comment by Gagert** [comment]
@dankcushions it might be true that the old CRT TVs stretched the picture of many consoles into a 4:3 aspect ratio, making Mario even fatter than he was supposed to be on the NES and SNES because of the pixel aspect ratio of 8:7 or something like that.

What I did with the PS1 games emulated in libretro especially, was studying many of the pixels to see if they are all perfect squares, and that there's not any rectangular pixels hiding in the image because of the wrong aspect ratio values. I suppose that on a good old TV setup some of the pixels are actually stretched while playing 2D sprite-based games like Final Fantasy Tactics (taking an ingame screenshot revealed it's native pixel resolution being 256x240).

If my goal is to have the perfect scaled square pixels route when emulating ps1 games on my 1080p monitors with integer scaling, I can either calculate how many times I can multiply the 256x240 resolution to fill my entire 1080p image while keeping all the pixels square (in this case multiplied 4 times making the custom resolution 1024x960), or I can just type in the aspect ratio of this resolution and RetroArch does the math for me to keep the pixels square and large (256x240 = 16:15 Aspect Ratio).

On my setup I suppose I don't go the "authentic" route with a forced aspect ratio on 2D sprite-based games like it may have been in the old games playing the game on the console itself, but because of my perfectionism I need all the pixels be be perfectly scaled squares, and not having some of the pixels appear rectangular.

**Comment by Gagert** [comment]
I compiled this on my PC, but I had also to edit the gfx/video_driver.c file as well to get the two new aspect ratios to be viewed in the RetroArch menu. To my surprise, even though the aspect ratio now seemed worked in the game Hugo using the beetle PSX libretro core (using the 80:63 aspect ratio I compiled on my PC), it seems like the beetle PSX core has some issues when calculating the proper native resolution for some games. Some of the pixels became rectangular.

Thereby I went back to my previous setup using custom aspect ratio with a resolution of 1280x1008 for this game (4x the native resolution of 320x252), and all the pixels became perfect squares again.

Anyway I'll think it's for the best that I just close this Pull Request and wait for a better solution regarding adding more Aspect Ratios in RetroArch that doesn't mess up all the configs yet again.

**Comment by dankcushions** [comment]
> @dankcushions it might be true that the old CRT TVs stretched the picture of many consoles into a 4:3 aspect ratio, making Mario even fatter than he was supposed to be on the NES and SNES because of the pixel aspect ratio of 8:7 or something like that.

i think it's a contentious issue as to what it was 'supposed' to be. game developers knew that TVs always had the same aspect ratio, but obviously it's easier drawing pixel art shapes at 1:1 pixel ratio. eg, CPS2 (street fighter 2, etc) games have an internal resolution of 384×224 but that is a widescreen image, but the games were displayed on 4:3 arcade cabs. if you use the native resolution with square pixels, you get fat Ryu :)

tekken 3 is 384x480. that would be a very tall image if you used square pixels.

but anyway, that's why retroarch has the ability to use integer scaling or indeed whatever custom resolution you want. the aspect ratio setting is really intended to reflect different standard TV and computer screen aspect ratios, rather than the 1000s of weird and wonderful internal resolutions of consoles.

> If my goal is to have the perfect scaled square pixels route when emulating ps1 games on my 1080p monitors with integer scaling, I can either calculate how many times I can multiply the 256x240 resolution to fill my entire 1080p image while keeping all the pixels square (in this case multiplied 4 times making the custom resolution 1024x960)

this is exactly what the 'integer scaling' option in retroarch does, though? just turn it on and you will get the same result.

> it seems like the beetle PSX core has some issues when calculating the proper native resolution for some games. Some of the pixels became rectangular.

it's quite common for psx games to have different resolutions. in fact, many games change resolution mid-game. this might be affecting your results.

**Comment by Gagert** [comment]
Regarding polygon based games on the ps1, I'm using the Beetle PSX hw libretro core and forcing a 4:3 aspect ratio because of the weird native resolutions some of the games have (I have experienced the tall Tekken 3 fighters using the games native res). In some games like Frogger I even use the widescreen hack and force a 16:9 aspect ratio. In polygon based games on the ps1 I don't mind if the 2D sprite based menu elements and such are stretched with rectangular pixels.

2D sprite based games on the ps1 have in my experience usually less extreme native resolutions; Castlevania Symphony of the Night have an ingame resolution of 256x240, but the title screen runs at an entirely different resolution.

Regarding integer scaling using the Beetle PSX core; in some games it works flawlessly using integer scaling combined with the games pixel aspect ratio (after doing some quick testing), but other games such as those running in the 320x252 resolution (using the 80:63 aspect ratio on my compiled version of RetroArch) must calculate the wrong native pixel resolution, because some of the pixels on the image are rectangular if I use the 80:60 aspect ratio and integer scaling to make the image bigger.

**Pull request closed without merging**
