### PR TITLE
(Emscripten) Show/Hide the console with no animation

### PR DESCRIPTION
**Pull request by RobLoach**
Reverts libretro/RetroArch#3587 and uses http://api.jquery.com/toggle/ rather then the slide animation. Will speed it up.

### CODE REVIEW

**Comment by fr500** [comment]
Can you have it open by default regardless?

**Comment by twinaphex** [comment]
RobLoach - when you're back on IRC, I'd like to run some local tests first together with you to ensure this doesn't result in a performance regression again. Got really concerned earlier today about it.

**Comment by RobLoach** [comment]
The performance cause was likely two things....

1. The page started with the console being shown, and then we hide it, which required another render of the browser
2. Using the slide animation to show/hide the browser.

**Comment by fr500** [comment]
He didn't touch it, it was always hidden and slow

**Comment by twinaphex** [comment]
Yeah, what radius said.

And the browser I used is Chrome. If I start up and toggle the Log button so that the console shows, and then I start up a game, performance is fine and the audio doesn't constantly crackle. If I start the console later on after the game has already been loaded, I can get crackle again.

Bottom line, the only way I get reliable performance is if the console log window is open as soon as possible before starting anything.

**Comment by fr500** [comment]
@RobLoach maybe we can move logging to the browser log somehow?

**Comment by RobLoach** [comment]
> maybe we can move logging to the browser log somehow?

Moving it to `console.log` would be the fastest, as it wouldn't be manipulating the DOM.

**Comment by RobLoach** [comment]
https://github.com/libretro/RetroArch/pull/3590

**Pull request closed without merging**
