### PR TITLE
Revert "Update french translation"

### PR DESCRIPTION
**Pull request by bubuleur**
Reverts libretro/RetroArch#8504

### CODE REVIEW

**Comment by bubuleur** [comment]
Why did not you consider my request?
thank you

**Comment by orbea** [comment]
This is an empty commit, I am not sure you meant to do that?

**Comment by Tatsuya79** [comment]
This was reverted because it was an automated translation of really poor quality.

Les traductions automatiques de mauvaise qualité ne sont pas acceptables.

**Comment by bubuleur** [comment]
Thank you for your answer both but why not work on my translation to improve translation

**Comment by orbea** [comment]
@hug0b I see you were the last person to actually work on French translations, would you be willing to help out here?

**Comment by hug0b** [comment]
@orbea Sorry I don't really have spare time to contribute anymore

**Comment by orbea** [comment]
No worries and thanks for the response.

**Comment by bubuleur** [comment]
No news ?

**Comment by orbea** [comment]
Seems we don't have any French speakers that have time or the motivation to help.

**Comment by twinaphex** [comment]
@Tatsuya79 and @kivutar both should know French.

**Comment by Tatsuya79** [comment]
I'm not interested to work on that, and almost everything seems automated in that "translation".
So all the work has to be done.

**Comment by orbea** [comment]
Given that this is an empty PR, the lack of current interest and @Tatsuya79's comment I am going to close this. If anyone is interested in improving the French translation a new PR can be made. :)

**Pull request closed without merging**
