### PR TITLE
Move frontend code to frontend_driver.c

### PR DESCRIPTION
**Pull request by inactive123**
Move frontend code out of retroarch.c and into frontend_driver.c. retroarch.c is now 694kb after this change.

@jdgleaver I'd appreciate a review before merging this.

### CODE REVIEW

**Comment by vaguerant** [comment]
This change is breaking on Wii U. I was getting crash dumps building abce5e1 (photo below), and since the dump specifically references `frontend_driver`, I rolled three commits back to c568872 (before this PR was merged) and had a working build up immediately.

Wii U crash

**Comment by jdgleaver** [comment]
Awesome. And that's why we shouldn't merge PRs without review....

It would seem (as one might expect) that all of those removed `frontend` NULL checks are in fact required.

**Comment by twinaphex** [comment]
My bad, I think this commit should address the issues - 

https://github.com/libretro/RetroArch/commit/c88577850d2dab799aaa2b76500929cb34b0e118

**Comment by twinaphex** [comment]
Honestly though @jdgleaver , this is pretty bad code all-around.

I have been informed that when it calls `frontend_driver_attach_console`, it can be the case that `frontend_driver_init_first` has not yet been called, so the entire frontend driver has not yet been setup then. That is just bad design, and duct-tape fixing that is just leaving us open to even more unintentional issues and bugs later down the line vs. fixing this properly, i.e. making sure the frontend driver state has been properly set up first BEFORE we attempt calling any other frontend driver related function.

**Comment by twinaphex** [comment]
Had a talk with @gblues, now it makes sense why he made the change he made to frontend_driver.c in his 'all users can control the menu' PR.

So I have replicated his implementation and also left a TODO/FIXME note so that people are aware of the nasty shenanigans that are happening here. Guess the code shuffling and the moving of state did help us identify a severe design issue in RetroArch that ought to be resolved as soon as possible -

https://github.com/libretro/RetroArch/commit/4b16b4fe9a08ddaa63d03b0054cff74a7ecddaf1

**Pull request merged**
