### PR TITLE
Add multiple mice support to udev input driver

### PR DESCRIPTION
**Pull request by casdevel**

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there,

do you feel comfortable with merging this?

**Comment by casdevel** [comment]
On my machine everything looks OK, although I tested this with OpenGL driver only since other video drivers don't work (on my machine) regardless of input driver used.

**Comment by casdevel** [comment]
Pointer device coordinates reporting is probably incorrect but that code was already like that. Udev is not "aware" of absolute coordinates. I thought to remove that code but decided not to, since that can be done anytime (this shouldn't interfere with mouse functionality).

**Comment by twinaphex** [comment]
The only regression I see is that the mouse cursor no longer shows up in the menu when you are in fullscreen mode with udev. You might have to look into that.

**Comment by spinktvis** [comment]
For some reason this broke my keyboard input on Arch Linux running latest RetroArch GIT compiled just now.

No matter what I press on my keyboard there is no response from within RetroArch. Can't even access the menu with F1. Worked fine yesterday. My keyboard works fine outside RetroArch. Thankfully my gamepad is still working.

**Comment by casdevel** [comment]
@twinaphex On my machine mouse cursor was not visible in fullscreen mode even before changes. I'll check that again and see what can be done.

@spinktvis I'll go trough code and check all changes again, in the meantime you can check log to see if udev driver reports some error(s).

**Comment by casdevel** [comment]
@twinaphex I was wrong about mouse cursor in fullscreen mode, it's visible with old code. I'll see why is not working now.

**Comment by twinaphex** [comment]
Ah, good to hear.

**Comment by casdevel** [comment]
@twinaphex Correction, this is not udev driver, its X11, old udev doesn't work with OpenGL.

**Comment by twinaphex** [comment]
The mouse cursor doesn't show up with the udev driver either though on DRM/KMS OpenGL, which runs without X11.

**Comment by casdevel** [comment]
@spinktvis It's possible that even udev input driver was selected from the menu before, the actual used input driver was not been udev. If you see error in log regarding permissions [this](https://github.com/libretro/RetroArch/wiki/Input-drivers-in-Linux-without-Xorg) page may help you setting things up.

**Comment by casdevel** [comment]
@twinaphex I found why mouse cursor is not visible in fullscreen mode, but if I'm correct old code have this issue also regardless of video driver used. RARCH_DEVICE_MOUSE_SCREEN device is not handled in code, and this is needed for mouse cursor to work in menu when app is in fullscreen mode.

Now, if I can't find reliable way of obtaining this coordinates this will need some workaround. I was thinking of this when I was working on changes, but since it's not been implemented already I skipped that to minimize code changes.

If turns out that there is no reliable way of obtaining this coordinates are you OK to start cursor from, let's say, center of the window, and than update those coordinates with relative movement of the mouse. I remember that I tried this with winraw driver under Windows and it's working, but with multiple monitor setups OS cursor stays visible and may be seen on other monitor(s).

**Comment by twinaphex** [comment]
RARCH_DEVICE_MOUSE_SCREEN is used while we are inside the RetroArch ingame menu. It will never be used by cores themselves.

**Comment by casdevel** [comment]
RARCH_DEVICE_MOUSE_SCREEN will be addition, code for relative coordinates remains the same.

I already implemented this and it's working but has one drawback: mouse should always be "grabbed" to avoid accidental activation of command(s) from other window(s) but that is another feature that udev driver currently don't supports and I don't know whether is possible at all to add this feature to udev driver (I'll check that).

**Comment by spinktvis** [comment]
@casdevel, thanks, you're right, it was exactly that, working like a charm now with udev. Thanks again.

**Pull request merged**
