### PR TITLE
Make playlist sorting optional and consistent

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

RetroArch is currently in a muddle when it comes to (alphabetically) sorting playlists...

- Load any normal (non-history, non-favourites) playlist via the playlist 'tabs' in XMB or Ozone, and the playlist contents will always be sorted alphabetically.

- Load any normal playlist via the 'Collections' menu in *any* menu driver, and the contents will never be (automatically) sorted alphabetically.

- Load the 'favourites' playlist in *any* menu driver, and the contents will never be (automatically) sorted alphabetically.

This is highly inconsistent, and it's also a nuisance for RGUI/GLUI users, who can never get sorted playlists. (For example: I regularly add new fan translations to my collection, and I do this by manually adding entries to the end of my playlist files. Since switching to RGUI, this causes everything to degenerate into a disordered mess...)

It's also a nuisance for any XMB/Ozone user who might want to order their playlists 'by hand' (e.g. to ensure that certain sequals/prequals show up in the correct 'play' order).

This PR solves the issue by adding a new `Sort playlists alphabetically` option to the `Settings > Playlists` menu.

- When this is turned `ON` (the default), every playlist (apart from histories) is sorted alphabetically.

- When this is turned `OFF`, playlists are never sorted.

Nice and tidy!

## Related Issues

This PR should close the following issues:

- #5511 (since playlists can now always be sorted, the generation order is basically irrelevant)

- #7140 (again, GLUI can now sort playlists, so generation order is irrelevant)

- #6422 (manual sorting is now enabled)

## Related Pull Requests

While adding the new option to the `Playlists` menu, I also discovered and fixed a little bug introduced by PR #8307. It turns out that having an option under `case DISPLAYLIST_PLAYLIST_SETTINGS_LIST:` that only exists for RGUI causes a display glitch when accessing the `Playlists` menu under XMB. Odd that this doesn't happen anywhere else (i.e. there are many other RGUI-specific options entered in exactly the same way in other categories, and they cause no issues). Never mind, I guess. It's fine now.

### CODE REVIEW

**Comment by orbea** [comment]
Maybe it would be handy for a future PR to be able to sort playlists from the menu? Like grab one item and drop it where desired?

**Comment by jdgleaver** [comment]
Ooh, I think that would be quite difficult! I believe the menu display code would need some deep changes to allow real-time editing by the user.

It's a good idea, though. I wonder if might be more practical to make it an option via the QT WIMP GUI?

**Comment by orbea** [comment]
Yea, that is understandable that it would be difficult and it would be nice to add it to the qt companion ui as well, but qt5 is a really heavy dependency so its good to assume the user may not have it.

**Comment by jdgleaver** [comment]
> but qt5 is a really heavy dependency so its good to assume the user may not have it.

Oh, absolutely. I was just thinking that a mouse interface would already be geared up for drag and drop (and it could probably be implemented as a simple layer on top of the existing menu code, without having to hack away too much at the internals).

I can kinda see how it might work with the existing menu drivers, though: select playlist item -> select 'move' option -> copy item using `playlist_get_index()` -> return to playlist view -> move up/down -> swap old/new values using `playlist_update()` -> trigger screen refresh -> repeat (ad nauseam) -> press A to confirm.

I guess it's something to add to the TODO list (albeit with a very low priority... :wink:)

**Comment by i30817** [comment]
If you're interested in the playlists, you may want to look at my RFE: https://github.com/libretro/RetroArch/issues/6410

**Comment by jdgleaver** [comment]
@i30817 That's a cool idea, but probably not my area (at least for the time being). In the 4-5 years that I've been playing with RetroArch, I've never even attempted to use the content scanner. It's too easy for me to write scripts to manage my collections, or to add individual rom hacks by hand. As for dealing with multiple disks, you're right - but the kind of uninformed user who can't make an m3u file and cope with normal disk swaps isn't someone I'm going to expend much effort on... :slightly_smiling_face:

**Pull request merged**
