### PR TITLE
Added 21:9 as an option to RGUI

### PR DESCRIPTION
**Pull request by Cpod12**
## Description

Added 21:9 as an option to RGUI. There is a bug when selecting it that it lists both the standard 21:9 option and the centered ones as 16:10. I'm unsure what causes this and would appreciate any help I could get with that.

## Related Issues

None

## Related Pull Requests

None

## Reviewers

Unsure

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
ha, nice. I was going to track down the commit where jdgleaver added 16:9 to RGUI and pass it along in the thread you made, but no need now :)

It looks like the annotated skeleton retroarch.cfg has been replaced with your actual retroarch.cfg, so definitely need to fix that!

**Comment by Cpod12** [comment]
Ok I'll fix that! Any advice for fixing that issue I have or where to get some help?

**Comment by zoltanvb** [comment]
As for msg_hash_*.h files, please add it to msg_hash_us.h, and only to that. All other such files are maintained in Crowdin and will be updated afterwards when translation is submitted there.

**Comment by zoltanvb** [comment]
And take a look at setting_get_string_representation_uint_rgui_aspect_ratio(), change is probably needed there.

**Comment by Cpod12** [comment]
> As for msg_hash_*.h files, please add it to msg_hash_us.h, and only to that. All other such files are maintained in Crowdin and will be updated afterwards when translation is submitted there.

Ok I'll do that. Thanks of letting me know!

**Comment by Cpod12** [comment]
> And take a look at setting_get_string_representation_uint_rgui_aspect_ratio(), change is probably needed there.

Where is this? I'm not able to find that function call

**Comment by Cpod12** [comment]
Nvm got it all fixed! Thank you both for all the help! Should be ready to merge hopefully :)

**Comment by hizzlekizzle** [comment]
This looks much better, thanks!

@LibretroAdmin would you care to review?

**Comment by metchebe** [comment]
Hello. This PR affects text and thumbnail scaling for the 16:9 mode, as shown in these screenshots:

v1.15.0 (OK):
Screenshot_20230925_084924

v1.16.0 (skinny text):
Screenshot_20230925_084821

**Comment by Cpod12** [comment]
Ok sorry about that. I can give that a look when I have some time.

**Pull request merged**
