### PR TITLE
Draft: Display server for KMS

### PR DESCRIPTION
**Pull request by zoltanvb**
## Description

Add a display server construct for DRM/KMS mode. The main use is to provide resolution changes (including automatic refresh rate switch) for this configuration, i.e. DRM context and OpenGL drivers.
Resolution changes are now also presented in the menu. Modes were already detected by the context driver.

This update does not bring any change for Vulkan in KMS mode (khr_display_ctx).

Tested on RPi 4.

## Related Issues
https://github.com/libretro/RetroArch/issues/8663

## Reviewers

There are some things that would be nice to get feedback on:

First, refresh rate restoration was not working in this setup, unless av_info->timing_fps was also adjusted on core close / RA exit. If this one was not changed, other parts of the code initiated a switch again, in effect cancelling the restoration.

Second, the driver reinit at display mode change. I tried to avoid it but was not successful, without this refresh rate was updated, but screen remained blank.

And CRT Switchres. Should it be left enabled in the KMS display server (X11 display server has it)? I have no means to test it.

### CODE REVIEW

**Comment by zoltanvb** [comment]
About Switchres, I'll check this, but it seems that it should already work without display server support: 
https://github.com/libretro/RetroArch/pull/15131

**Comment by zoltanvb** [comment]
Yes, that is the idea, but it will require more investigation, since the DRM context driver does not deal with planes directly. The stub is left there as a reminder, but this PR makes sense even without it, rotation can come later.

Meanwhile I checked the relation to CRT Switchres, and it should work the same way with KMS as before.

**Comment by substring** [comment]
Hey!

I started a KMS display context, but I gave up since I didn't see any use for it. If I'm not mistaken, this PR is just adding resolution selection, right ?

A few words regarding some topics that were mentionned:

- CRT Switchres simply creates a CRTC at the right mode when required. I'd need to investigate further to see how the default mode is restored (if it's the "connector current mode" so to say, or the connector preferred mode). I'd love this PR doesn't break CRT modeswitching 🥲 
- whole video reinit on resolution change: that's the best way of doing it I guess, oterwise OpenGL gets totally messed or segfaults
- Menu rotation: KMS/DRM simply doesn't really care about rotation. There is a kenrel flag to set the orientation of the monitor and DRM can indeed store this property, but nothing more happens with it, except you can query that property (I can give a few links from the kernel code and an example of a use case to manage rotation). It would probably be better if RA had an option in the menus to force the rotation of the screen ...

**Comment by zoltanvb** [comment]
It enables resolution selection, and the automatic refresh rate switch function that also relies on video_display_server_has_resolution_list():
https://github.com/libretro/RetroArch/blob/13fc4cbda3a51bc6573d05d6941bdab7dae8863d/retroarch.c#L808

The refresh rate change/restore function is independent of CRT Switchres, they should be able to coexist in the code without problems, the conditions are not overlapping:
https://github.com/libretro/RetroArch/pull/12795
https://github.com/libretro/RetroArch/pull/13316

I will take another look anyway, as the more I think about it, the worse idea it seems to set av_info.

Thanks for the comments on reinit and rotation. No low hanging fruit here, then.

**Comment by substring** [comment]
For the rotation thing:
https://github.com/torvalds/linux/blob/f1fcbaa18b28dec10281551dfe6ed3a3ed80e3d6/drivers/gpu/drm/drm_connector.c#L2499-L2532
And how plymouth uses that to rotate its splash screen:
https://gitlab.freedesktop.org/plymouth/plymouth/-/blob/main/src/plugins/renderers/drm/plugin.c#L490-564

It's quite niche and lacks on-the-fly setting, not implemented into EDID, but at least it's one step to get rotation working in RA menu (which is definitely missing on KMS).

Auto refresh rate would be overridden by CRT stuff I guess. Probably not much conflict here, depends when the refresh rate is set. I'll procrastinate for now and not dig

**Comment by zoltanvb** [comment]
I have not found any better way to avoid setting av_info. So I'll just wait for https://github.com/libretro/RetroArch/pull/15297 to be merged, rebase, some final tests and then mark it as ready.

**Comment by LibretroAdmin** [comment]
Merged the PR you referenced above

**Comment by zoltanvb** [comment]
Ohf... Messed up the rebase. I will open a new PR with the needed changes only.

**Pull request closed without merging**
