### PR TITLE
changes, enhancements and fixes to the cheevos

### PR DESCRIPTION
**Pull request by leiradel**

### CODE REVIEW

**Comment by twinaphex** [comment]
You'll need to rebase this, I had to do some style nits to the file before.

Would maybe prevent future collisions if some of these stylistic preferences were taken into consideration.

**Comment by leiradel** [comment]
Code style is something we should strive for, but hard to achieve. I cannot make myself think about code style while writing code. We could perhaps have an AStyle configuration ready to be used.

What should I do now regarding these changes? Is there a git command that will let me resolve the conflicts in my local repo?

**Comment by twinaphex** [comment]
I'll just manually merge them this time by hand.

**Comment by twinaphex** [comment]
OK, I backported all the patches now. See if things build with HAVE_CHEEVOS defined, if not, we have to push some more patches.

**Pull request closed without merging**
