### PR TITLE
Make sure HAVE_CHD is defined regardless of which FLAC we use

### PR DESCRIPTION
**Pull request by bkoropoff**
Second attempt

### CODE REVIEW

**Comment by fr500** [comment]
what purpose does CHD serve in RetroArch?

I understand for cores, not sure what it does in the frontend tho

**Comment by orbea** [comment]
@bkoropoff What are you trying to fix? It already builds CHD files with either flac...

**Comment by orbea** [comment]
Wit builtin flac.
```
CC deps/7zip/7zIn.c
CC deps/7zip/7zFile.c
CC deps/7zip/Bra86.c
CC deps/7zip/7zStream.c
CC deps/7zip/LzFind.c
CC deps/7zip/LzmaDec.c
CC deps/7zip/LzmaEnc.c
CC deps/7zip/7zCrcOpt.c
CC deps/7zip/Bra.c
CC deps/7zip/7zDec.c
CC deps/7zip/Bcj2.c
CC deps/7zip/7zCrc.c
CC deps/7zip/Lzma2Dec.c
CC deps/7zip/7zBuf.c
CC deps/ibxm/ibxm.c
CC deps/libFLAC/bitmath.c
CC deps/libFLAC/bitreader.c
CC deps/libFLAC/cpu.c
CC deps/libFLAC/crc.c
CC deps/libFLAC/fixed.c
CC deps/libFLAC/float.c
CC deps/libFLAC/format.c
CC deps/libFLAC/lpc.c
CC deps/libFLAC/lpc_intrin_avx2.c
CC deps/libFLAC/lpc_intrin_sse2.c
CC deps/libFLAC/lpc_intrin_sse41.c
CC deps/libFLAC/lpc_intrin_sse.c
CC deps/libFLAC/md5.c
CC deps/libFLAC/memory.c
CC deps/libFLAC/stream_decoder.c
CC libretro-common/file/archive_file_zlib.c
CC libretro-common/streams/trans_stream_zlib.c
CC libretro-common/formats/libchdr/bitstream.c
CC libretro-common/formats/libchdr/cdrom.c
CC libretro-common/formats/libchdr/chd.c
CC libretro-common/formats/libchdr/flac.c
CC libretro-common/formats/libchdr/huffman.c
```

**Comment by orbea** [comment]
With builtin flac.
```
CC deps/libFLAC/bitmath.c
CC deps/libFLAC/bitreader.c
CC deps/libFLAC/cpu.c
CC deps/libFLAC/crc.c
CC deps/libFLAC/fixed.c
CC deps/libFLAC/float.c
CC deps/libFLAC/format.c
CC deps/libFLAC/lpc.c
CC deps/libFLAC/lpc_intrin_avx2.c
CC deps/libFLAC/lpc_intrin_sse2.c
CC deps/libFLAC/lpc_intrin_sse41.c
CC deps/libFLAC/lpc_intrin_sse.c
CC deps/libFLAC/md5.c
CC deps/libFLAC/memory.c
CC deps/libFLAC/stream_decoder.c
CC libretro-common/file/archive_file_zlib.c
CC libretro-common/streams/trans_stream_zlib.c
CC libretro-common/formats/libchdr/bitstream.c
CC libretro-common/formats/libchdr/cdrom.c
CC libretro-common/formats/libchdr/chd.c
CC libretro-common/formats/libchdr/flac.c
CC libretro-common/formats/libchdr/huffman.c
```

**Comment by orbea** [comment]
Alright, I see the problem... It won't build CHD if flac is not installed and uses the builtinflac.

I suggest you just add `HAVE_FLAC = 1` under ` ifeq ($(HAVE_BUILTINFLAC),1)` and leave the rest as is.

**Comment by bkoropoff** [comment]
@orbea I'm hesitant to touch HAVE_FLAC since it seemed to break C89 builds.  Could you test that your proposed solution doesn't cause any problems?

**Comment by bkoropoff** [comment]
@fr500 CHD support in retroarch allows scanning CHD files and adding them to playlists

**Comment by orbea** [comment]
The problem with `C89_BUILD=1` is that by default it will use the builtin flac, but `HAVE_BUILTINFLAC=1` will be ignored in `config.mk` if building with `C89_BUILD=1` so it might fall back to the system flac. However that will not work if it never checks for and uses `-lFLAC`. This means we have to always check if flac exists and we can't set `HAVE_FLAC=1` if `HAVE_BUILTINFLAC=1`  because that will force the flac check from `auto` to `yes` which will result in an configure error if flac is not installed.

However `Makefile.common` does not have this issue, it will either use the builtin or system flac and then should build the libchdr files if either is true. The intent was that `HAVE_FLAC=1` should be true for both, but it seems I overlooked that detail when adding support for building with a system flac...

I tested my suggestion and with `C89_BUILD=1` it will either use the system flac or not build libchdr if flac is missing.

**Comment by orbea** [comment]
Btw thanks for explaining what CHD support in RetroArch does, I can confirm I can scan a CHD file with my system flac now. :)

**Comment by bkoropoff** [comment]
@orbea Alright, changed my commit to what you suggested

@twinaphex I think this is good now

**Comment by orbea** [comment]
@twinaphex I agree.

**Pull request merged**
