### PR TITLE
despite disabling oss on configure, the driver is still linked to.

### PR DESCRIPTION
**Pull request by devnexen**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by orbea** [comment]
Could you explain the the issue here? I think that ifdef should be redundant. `HAVE_NO_OSS` should always be true if `HAVE_OSS` is false. I confirmed this with `./configure --disable-oss` in freebsd and looking at the resulting `config.mk`.

**Comment by devnexen** [comment]
Problem is more HAVE_OSS_BSD ... I spotted it in linkage time (on OpenBSD you re probably right for FreeBSD) ... e.g ./configure --disable-oss ...

**Comment by orbea** [comment]
I think this should be solved in the configure scripts, would this work for you?
```
diff --git a/qb/config.libs.sh b/qb/config.libs.sh
index 52e6e47d8d..95f796c42d 100644
--- a/qb/config.libs.sh
+++ b/qb/config.libs.sh
@@ -228,9 +228,12 @@ fi
 
 check_pkgconf ALSA alsa
 check_lib '' CACA -lcaca
-check_header OSS sys/soundcard.h
-check_header OSS_BSD soundcard.h
-check_lib '' OSS_LIB -lossaudio
+
+if [ "$HAVE_OSS" != 'no' ]; then
+   check_header OSS sys/soundcard.h
+   check_header OSS_BSD soundcard.h
+   check_lib '' OSS_LIB -lossaudio
+fi
 
 if [ "$OS" = 'Linux' ]; then
    HAVE_TINYALSA=yes
```

**Comment by devnexen** [comment]
Sounds reasonable indeed

**Comment by orbea** [comment]
Alright, thanks for explaining. I made a PR with that change. :)

**Comment by twinaphex** [comment]
Alright, can @orbea or anybody else give me a heads up here on what to merge and what not? This goes for the other qb-related PRs too.

**Comment by orbea** [comment]
@twinaphex I think my change in PR https://github.com/libretro/RetroArch/pull/6008 made this PR not needed @devnexen could confirm since I could not reproduce the issue.

**Comment by devnexen** [comment]
Works fine now thanks.

**Pull request closed without merging**
