### PR TITLE
Migrate to Qt6

### PR DESCRIPTION
**Pull request by viachaslavic**
## Description

* Basic support Qt6 with minimal changes required for compiling
* ~~Avoid using NULL for Qt UI~~ (keep for further refactoring)
* Look `moc` in QT_HOST_LIBEXECS
* Soft switching to C++17 (required by Qt6).  If the compiler does not support it, the build will be performed as before with c++11, but without qt6 support (but will still try to find and compile with qt5).
* cflags for Qt moved to CXXFLAGS to avoid affecting the C code. At least this fixes compiling xaudio driver on Windows.

Tested on ArchLinux/Qt6.8, Debian12/Qt6.4, Win10(MSYS2)/Qt6.8

## Related Issues

#16913 

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by viachaslavic** [comment]
Done. Added compatibility with Qt5 for unhurried updating of build environments.

**Comment by LibretroAdmin** [comment]
HI, I have a request. 

Can you make it so that we can have a separate Qt5 and Qt6 implementation? That way we are not boxed-in to either ONLY Qt 5 or Qt 6 at the compilation stage. I'd like to eventually reduce our dependence on Qt and to go through more abstractions in the UI companion layer so that we can also have like a native Win32 UI implementation. Furthering our dependence on Qt 6 alone in that regard I think would be a mistake, so best to make sure that we take this opportunity now to make the current Qt implementation for Qt5 and then your new implementation a new compilation option for Qt 6. That way we can keep our options open.

**Comment by viachaslavic** [comment]
I have some thoughts for the code, which I can try to implement using inheritance, maybe with templates …
But I'm not completely clear on what to do with the build scripts. That means the scripts should allow to build with both Qt5 and Qt6 at the same time? Why is this useful to the user? Or can we leave the scripts as is in this PR for now?

**Comment by LibretroAdmin** [comment]
Hmm, I had a look at the code, and I guess it looks fine for now. So from what i understand of the current code, if HAVE_QT6 is defined, it will build with Qt 6 support, and if not, Qt 5 support is assumed ? I guess that could work.

Sorry I hadn't studied the code closer beforehand.

**Comment by viachaslavic** [comment]
>  if HAVE_QT6 is defined, it will build with Qt 6 support, and if not, Qt 5 support is assumed ?

Exactly, but this internal variable is used only inside the build logic, it is not accessible outside. In other words, Qt6 support is currently implicitly available, **only via Makefile and if all dependencies are satisfied**. Otherwise, everything remains as before, it will try to build with qt5 (unless explicitly `disable-qt` configured).

I decided to offer a smooth migration to Qt6 with a minimum of required changes, which behaved the same as Qt5.
Moreover, after a full migration (after some time) I don't see any cases of leaving the Qt5 implementation, since both have almost the same hardware requirements. But that's a topic for a separate discussion in the future

> Is there a technical reason Qt 6 requires C++17 or was that just a liberty you took?

This is a [Qt6 requirement](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qcompilerdetection.h#n1297); with c++11 it refuses to compile.

**Comment by LibretroAdmin** [comment]
Alright, sounds reasonable then.

**Pull request merged**
