### PR TITLE
Add option to reset all core options for current core/content

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR simply adds a new `Reset Options` entry under `Quick Menu > Options > Manage Core Options`:

Screenshot_2021-02-25_16-58-45

This provides an easy way to reset all options for the current core (or core options override), without having to manually press RetroPad `start` on each individual options entry.

### CODE REVIEW

**Comment by bslenul** [comment]
Hey!

Found a crash while messing with this awesome addition (could be the previous commit I'm not sure, I could test tomorrow, it's way too late right now :p), if you're in this new "Manage Core Options" menu, resume game with F1 then close content with a "Close Content" hotkey, RetroArch crashes.

With Ozone: https://pastebin.com/tX0nBD2T
With XMB: https://pastebin.com/pFU4fYQf

No crash with GLUI and RGUI. This in on Windows 10 64bit, again it's super late here but I could try on other systems tomorrow if needed!

**Comment by jdgleaver** [comment]
@bslenul Thank you! That's a really funky edge case, and I never would have found it on my own :)

I'm pretty sure I know what's going on there - should have a fix later today

**Comment by jdgleaver** [comment]
@bslenul There we go - that should fix it: #12079

**Comment by bslenul** [comment]
Oh nice, I was about to give you an update, I tested on my Linux VM and it crashes there too. Now with this new PR it doesn't anymore! 👍 

I got this however on close content: `menu/drivers/ozone/ozone_entries.c:748:18: runtime error: load of value 190, which is not a valid value for type '_Bool'`, no idea if this is harmless or not, I was able to navigate menus and launch other games without any issue after the error.

I'll test the PR on Windows and edit my post!

**Comment by jdgleaver** [comment]
Ah, yes - look at that:

```c
ozone_node_t *ozone_alloc_node(void)
{
   ozone_node_t *node   = (ozone_node_t*)malloc(sizeof(*node));

   node->height         = 0;
   node->position_y     = 0;
   node->console_name   = NULL;
   node->icon           = 0;
   node->content_icon   = 0;
   node->fullpath       = NULL;
   node->sublabel_lines = 0;

   return node;
}
```

It's not setting `node->wrap = 0` on node creation, so `if (node->wrap && !string_is_empty(sublabel_str))` is operating on an uninitialised variable during the transition animation. In this case, it's perfectly harmless (the `string_is_empty()` will always be `true` if `wrap` is undefined), but yeah, that should be fixed on principle. Just started working on something else, so I'll do it later :)

**Comment by bslenul** [comment]
Yeah no rush, especially if it's harmless, plus it's such a specific case anyway... :p

Works like a charm on Windows too btw! So thank you for the quick fix! And a big thank you to you and @crystalct for these awesome improvements on the core options menu ❤️

**Pull request merged**
