### PR TITLE
[WiiU] Add proper DRC touch scaling for non-720p resolutions

### PR DESCRIPTION
**Pull request by QuarkTheAwesome**
Heyo!
As it turns out, not everyone uses 720p on their Wii U; so this is a quick patch to allow the touch driver to deal with the different resolutions the console might run at. I think we're finally at the point where this driver will be usable for the majority of users.

Thanks again,
Ash

(edit: tagging #5294 for tracking)

### CODE REVIEW

**Comment by fr500** [comment]
Is it stable enough? we're trying to push a release today

**Comment by QuarkTheAwesome** [comment]
It worked fine in my testing, but I don't mind if you want to wait until after the release to merge. Most Wii U users are on the nightlies anyway.

**Comment by fr500** [comment]
up to @twinaphex

**Comment by twinaphex** [comment]
OK, let's merge it in.

**Pull request merged**
