### PR TITLE
remove MIT-incompatible rsemaphore

### PR DESCRIPTION
**Pull request by bparker06**
Not being used anyway.

### CODE REVIEW

**Comment by orbea** [comment]
Just out of curiosity, what was it used for?

**Comment by orbea** [comment]
@twinaphex What is the status on this? Violating a violence in our own code base is not good.

**Comment by twinaphex** [comment]
I'll ignore the typo -

this file is/was only used by one specific core, I believe it might be np2kai.

We might be able to move it over to RetroArch, that way it's out of libretro-common.

**Comment by bparker06** [comment]
Any progress on this?

**Comment by bparker06** [comment]
No progress has been made in 3 months so I'm merging this. Just looks worse the longer we don't do it.

**Pull request merged**
