### PR TITLE
Allow Toggling the XMB Horizontal Animation

### PR DESCRIPTION
**Pull request by RobLoach**
**Don't Merge Yet**

This takes @Tatsuya79's work from https://github.com/libretro/RetroArch/issues/4517 and allows the user to enable/disable the Horizontal Animation in the configuration. Would be nice to have a sublabel.

As @bparker06 mentioned, there may be some drawbacks. Need more investigation.

### CODE REVIEW

**Comment by twinaphex** [comment]
@kivutar Please investigate this if it's safe.

**Comment by Ploggy** [comment]
This has been compiled into a test core for the WiiU and the speed difference is.. noticeable lol 
Before: https://youtu.be/lys1u77j_0w 
and After: https://youtu.be/AEM6Pq_VaGg

**Comment by Tatsuya79** [comment]
Is that a 2mn long lag between Mame and FBA playlists? lol
I'm using this fix too since I found that cpu expensive part to skip and it's dramatically faster on my PC as well.

**Comment by twinaphex** [comment]
Alright, I'll merge this then.

And yeah, kivutar is aware that the deep copying we are doing for the animation is slow. It's unfortunately one of the warts in our menu system.

We are hoping to completely overhaul the menu system code since there is a lot of room for improvementt there and we need more people working with it.

**Comment by Tatsuya79** [comment]
@Ploggy 
please try again with horizontal animation ON with today build.
The optimization made yesterday by Heuripedes is really good on my PC.
I wonder if it's noticeable on Wii U as well.

**Comment by Ploggy** [comment]
I just tried..  but its still really slow with horizontal scrolling left on on WiiU :(

**Pull request merged**
