### PR TITLE
Vulkan: X11 backend

### PR DESCRIPTION
**Pull request by Themaister**
This adds various minor fixes and a X11 backend in same style as Wayland.
I didn't try to refactor out too much.

Seems to work on nVidia GTX 760, but there are some weird glitches here and there.

### CODE REVIEW

**Comment by Themaister** [comment]
We might want to rename GLX to X or something more generic since it's not just GL now.

**Comment by Themaister** [comment]
Another thing that this changes is that in Wayland, the GLX driver will be picked up before it comes before Wayland in the context driver list. GLX works on wayland usually, but perf is kinda crap ... Maybe we need to put Wayland first? Doubt wayland will work when running on X ...

**Comment by almostalive** [comment]
this is what is happing on both my haswell and broadwell.
https://gist.github.com/almostalive/f4801b28b59f9c1d443d

@Themaister  you only mention nvidia, did you try this with intel? and @twinaphex you are not on irc right now, is this working on your ivybridge?

**Comment by twinaphex** [comment]
Yeah it doesn't work for me with X11, same issue.

I think it's probably best if we move Wayland up the chain so it tries starting that context driver first.

**Comment by Themaister** [comment]
Ye, X11 (current) master is working fine for me on Broadwell inside Gnome Wayland, it's just slower as expected.

**Comment by twinaphex** [comment]
Well, I'm running Openbox and X11, it didn't work on there.

Looking at vkcube it seems they do a whole lot more to set up the xcb context, unfortunately I can't get it to compile, seems to require glslc or something.

**Comment by almostalive** [comment]
@Themaister ok stupid easy fix getting vulkan to work on x11 with Intel. Arch (I think most distro's) default to dri2. While at least Intel vulkan on x11 requires dri3. Switching over to that me and @twinaphex both can run vulkan on x11.

Mostly it is the same menu driver issues with vulkan(haswell and ivybridge) on x11, but the menu drivers do not respect vsync and run as fast as they can. Games are alright. Still awesome! now for drm/kms!

**Pull request merged**
