### PR TITLE
(Netplay/3DS) Launch compatibility patch

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**
## Description

I'll be doing these patches individually in case we need to revert some of them.

## Related Pull Requests

https://github.com/libretro/RetroArch/pull/14202

## Reviewers

@MrHuu

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi @MrHuu and/or @bulzipke ,

would any of you fine people be able to give this a shot and let us know your results?

**Comment by Cthulhu-throwaway** [comment]
This likely requires more work to function as intended. I am switching it to a draft until I am confident it's implemented correctly.

**Comment by Cthulhu-throwaway** [comment]
I don't think it needs anything else, so I am making the PR ready again.

**Comment by LibretroAdmin** [comment]
Any response yet? Or should we take the plunge and merge this?

**Comment by Cthulhu-throwaway** [comment]
I don't think anyone netplays on the 3DS and I am pretty sure there are other (library related) networking issues there that prevent netplay from working anyway.

I am more interested in knowing whether my changes to frontend_ctr_exec broke non-netplay related forks (I am fairly confident it didn't).

**Comment by LibretroAdmin** [comment]
Alright, I'll take that as a yes in terms of merging this one.

**Pull request merged**
