### PR TITLE
Review: allow blocking screensaver

### PR DESCRIPTION
**Pull request by fr500**
- It won't clear the request unless you restart because the object is no longer accessible. I don't know how to declare the Request globally object only if getProcAddress is true
- It won't set the request unless you restart the gl context (load content will set the request just fine)
- It fixes https://github.com/libretro/RetroArch/issues/2138

### CODE REVIEW

**Comment by fr500** [comment]
It probably bumps compilation requirements to windows 7 sdk

**Comment by twinaphex** [comment]
This can never be merged then. At no point ever can compilation requirements be bumped to later versions.

**Comment by fr500** [comment]
Ok, I'll keep this for my personal builds anyhow.
The functions are new and the old ones don't work on win 7+

**Comment by fr500** [comment]
Wait what? only compilation bumps to windows 7, it should still work in vista/XP

**Comment by twinaphex** [comment]
Not acceptable either. I still have a Windows XP box too and at no point in time can we cut offo compilation to a specific Windows OS version.

Im sorry but search for a way so this cutoff point isnt required.

**Comment by fr500** [comment]
ok, so your personal builds that you don't use take precedence.

**Comment by twinaphex** [comment]
No, portability takes precedence, not artificial obsolescence.

Anyway I will check if this can be done in a backwards compatible way, but this implementation is not going to work obviously.

**Comment by fr500** [comment]
It would be as simple as having an extra define like my latest commit, then
the configure script would add that to config.h but I don't know much about
pkgconfig

**Comment by fr500** [comment]
Anyway, even if this is good this PR shouldn't be merged, I didn't notice my repo was not clean (have a few stray commits in there so it shouldn't be merged), let me knoow if this approach is acceptable so I can send another PR

**Pull request closed without merging**
