### PR TITLE
Enable svchax in 3dsx builds when running under Luma3DS 8.0+

### PR DESCRIPTION
**Pull request by justinweiss**
## Description

When running under modern versions of Luma3DS / boot9strap, it appears that we can get as much system access with 3dsx files as we can with cia files. This allows for dynarec in cores launched from the Homebrew Menu. With this change, I see roughly equal framerates between pcsx_rearmed cia and 3dsx builds.

One caveat: I wasn't able to get the correct version of devkitARM running on my Mac, so I had to do a little bit of work to get RetroArch to build under the current version: #9487. I don't see any problem with cherry-picking https://github.com/libretro/RetroArch/pull/9488/commits/81426c8a8af0e550175db1a342462c9855240be7 and building with the old devkitARM, but I wasn't able to test that combination.

## Related Issues

This should address part of https://github.com/libretro/RetroArch/issues/8750.

## Related Pull Requests

~~As is, this depends on #9487 and is based off that branch.~~

## Reviewers

I think @jdgleaver may have been looking into this.

### CODE REVIEW

**Comment by twinaphex** [comment]
This sounds highly promising! It's definitely something I would like to see @jdgleaver review.

**Comment by jdgleaver** [comment]
@justinweiss Hey, this is great!

I did indeed say that I would look into this, and I had a go at it several months ago - but I was trying to use this from Luma Updater:

```c
int NAKED svcGetLumaVersion(SvcLumaVersion UNUSED *info) {
	asm volatile(
		"svc 0x2E\n"
		"bx lr"
	);
}
```

...which unfortunately just raises an exception (when using our toolchain, at least). So it didn't work, and I got sidetracked with other things...

But your implementation seems perfect  :)

Now the only issue is the libctru 1.6 support. Updating the devkitARM toolchain is not a task we can undertake lightly - it needs every core to be built and checked on o3DS/n3DS, including performance profiling, regression testing, etc. We don't have the time or manpower for this.

But as you say - we can certainly cherry pick commit https://github.com/libretro/RetroArch/commit/81426c8a8af0e550175db1a342462c9855240be7. I have tested this with the current 'official' (old) toolchain and can find no issues (builds/runs just fine).

So how do you want to handle this? Would you like to make a new PR containing just commit https://github.com/libretro/RetroArch/commit/81426c8a8af0e550175db1a342462c9855240be7? I think that could be merged straight away without any problems.

**Comment by justinweiss** [comment]
Makes sense! I just rebased this PR onto master, thanks for trying it out.

**Comment by jdgleaver** [comment]
Good stuff!

@twinaphex I think we can go ahead with this  :)

**Comment by twinaphex** [comment]
So this PR is safe to merge now for our buildbot and won't require us to update the toolchain?

**Comment by justinweiss** [comment]
This PR now only has the Luma version detection changes -- the toolchain upgrade changes are isolated to https://github.com/libretro/RetroArch/pull/9487. I don't have a working old toolchain, so I wasn't able to test these changes in isolation, but @jdgleaver said it worked fine.

**Comment by jdgleaver** [comment]
@twinaphex Yes, this PR is good to go

(BTW @justinweiss - awesome job with PCSX-ReARMed, too. Really nice to have someone else taking an interest in the 3DS port!)

**Pull request merged**
