### PR TITLE
[bugged] Reworked xmb driver to allow tab hiding

### PR DESCRIPTION
**Pull request by gitghostcoder**
I wanted to hide the history tab, and I saw several requests around the web for a similar feature so I thought I would dive into the code.

The linked page discusses a potential key combination to show settings which have been hidden. I'd be happy to look into such a feature, but I wanted to touch as few files as possible until the approach I've used to remove the enum dependency could be reviewed.

References: (I'm new to github so do not know how to link a feature/issue to my fork.)
https://github.com/libretro/RetroArch/issues/3106

### CODE REVIEW

**Comment by RobLoach** [comment]
1. Nicely done submitting the PR.
2. Would an alternative way around this be to hide them only when the playlist is empty?

**Comment by Kivutar** [comment]
I really like this feature!
Did you test it well? I mean, with no playlists, with playlists, with an old retroarch.cfg, etc?
I'm not for a key combo.

**Comment by gitghostcoder** [comment]
@RobLoach
1:
The approach I used was not my first instinct. I would have liked to kill a few more birds with a weighted sort. My gut says playlists from files are (1, 1) with core tabs (x, y) where y is the [main, settings, images, music, video, history, import] enumeration. You could then have xmb_main_index and related to set the x value for left, right, or hidden with relative sorting within the two groups.

The simple fact is I touched way too much code for an unknown feature set.

If there is interest in the approach, I can revisit next weekend.

2:
I have no idea. I didn't look into that.

@Kivutar 
I did do testing, but I didn't think of testing without any playlists. Without even running the code, I now expect an off-by-one error thanks to the way I accumulated the end-of-sequence marker. Certainly not a difficult fix, and I should have caught it myself, but no reason to pull an expected bug.

Thanks for the logic check.

I'll update the tag accordingly until I can change the way the end-of-sequence marker is accumulated.

**Comment by Kivutar** [comment]
I get this segfault with my setup. I checked out your branch, kept my current retroarch.cfg. RetroArch launched fine the first time. Then I went in the menu settings, hidded the music and video tabs. Noticed that they were still displaying. Quit RetroArch and launch again, then get this segfault:

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
menu_animation_push (anim=0x555555b8b960 <anim>, data=0x7ffffffeb9e0) at menu/menu_animation.c:385
385	   t.initial_value = *entry->subject;
(gdb) bt
#0  menu_animation_push (anim=0x555555b8b960 <anim>, data=0x7ffffffeb9e0) at menu/menu_animation.c:385
#1  menu_animation_ctl (state=state@entry=MENU_ANIMATION_CTL_PUSH, data=data@entry=0x7ffffffeb9e0) at menu/menu_animation.c:701
#2  0x000055555560e3f6 in xmb_list_open_horizontal_list (xmb=0x5555566111b0) at menu/drivers/xmb.c:1259
#3  xmb_list_open (xmb=0x5555566111b0) at menu/drivers/xmb.c:1479
#4  xmb_populate_entries (data=0x5555566111b0, path=<optimized out>, label=<optimized out>, k=<optimized out>) at menu/drivers/xmb.c:1541
#5  0x0000555555610b37 in menu_driver_ctl (state=state@entry=RARCH_MENU_CTL_POPULATE_ENTRIES, data=data@entry=0x7fffffff4cb0) at menu/menu_driver.c:663
#6  0x0000555555645d8f in menu_displaylist_push_list_process (info=info@entry=0x7fffffff4cb0) at menu/menu_displaylist.c:3792
#7  0x0000555555646828 in menu_displaylist_ctl (type=type@entry=DISPLAYLIST_PROCESS, data=data@entry=0x7fffffff4cb0) at menu/menu_displaylist.c:5435
#8  0x00005555556098c5 in xmb_init_horizontal_list (xmb=<optimized out>) at menu/drivers/xmb.c:1312
#9  0x0000555555609e33 in xmb_init (userdata=0x555555b53f60 <menu_userdata>) at menu/drivers/xmb.c:2613
#10 0x00005555556104b7 in menu_driver_ctl (state=state@entry=RARCH_MENU_CTL_INIT, data=data@entry=0x0) at menu/menu_driver.c:562
#11 0x00005555555bbcbc in init_drivers (flags=<optimized out>) at driver.c:357
#12 driver_ctl (state=<optimized out>, data=<optimized out>) at driver.c:457
#13 0x00005555555bbbe7 in driver_ctl (state=state@entry=RARCH_DRIVER_CTL_INIT_ALL, data=data@entry=0x0) at driver.c:463
#14 0x000055555559937d in retroarch_main_init (argc=1, argv=argv@entry=0x7fffffffe838) at retroarch.c:1385
#15 0x00005555555a8deb in content_load (info=0x7fffffffe700) at tasks/task_content.c:936
#16 task_load_content (content_info=content_info@entry=0x7fffffffe700, launched_from_menu=launched_from_menu@entry=false, mode=CONTENT_MODE_LOAD_FROM_CLI)
    at tasks/task_content.c:1623
#17 0x00005555555aace9 in task_push_content_load_default (core_path=<optimized out>, fullpath=0x0, content_info=0x7fffffffe700, type=CORE_TYPE_PLAIN, 
    mode=CONTENT_MODE_LOAD_FROM_CLI, cb=<optimized out>, user_data=0x0) at tasks/task_content.c:1966
#18 0x0000555555595201 in rarch_main (argc=1, argv=0x7fffffffe838, data=0x0) at frontend/frontend.c:104
#19 0x00007fffefa17741 in __libc_start_main () from /usr/lib/libc.so.6
#20 0x0000555555592199 in _start ()
```

**Comment by gitghostcoder** [comment]
@Kivutar 
I don't know what to tell you other than say I had a forest/trees issue. I worked from 1.3.6 and was too focused on the process of updating the code. I made a stupid assumption causing an off-by-one issue resulting in out-of-bounds access.

I started to fix the code, but I decided that a patch I intended as an intermediate feature depending on interest wasn't worth spending more time. I instead followed my instinct and updated the original ordering code which can also hide tabs. Plus, a comment from another person make me wary of eventually introducing two competing options for hiding tabs.

I wasn't going to work on the feature until next weekend, but I thought I might catch you before you went back to work or whatever starts your week. Would you try the ordering version when you have the time? I now have issues public on a public fork so you can start a report if you find something.

https://github.com/gitghostcoder/RetroArch

I already know about two issues:
1 - The driver loads the main menu by default, and I haven't found the best place to address the issue. The result is that you can hide and reorder the main menu, but the main menu will load at position zero at first. You can move back and forth from a different tab to properly load the expected menu at position zero.
2 - The animation system seems to make an assumption that at least two menus will exist, but I think I can fix the issue by suppressing tab swapping when only one tab exists. The current result is that hiding all system tabs with one playlist or having only one system tab with no playlists will cause graphics artifacts when attempting to navigate between tabs.

The options are currently named Offset Main Tab and so on for other tabs. I don't particularly like the label for general users, and I'd appreciate any feedback.

An offset of zero hides the relevant tab while the playlist tabs are basically given a weight of (4, INT_MAX) so an offset five or greater positions the relevant tab to the right of the playlist tabs.

**Comment by gitghostcoder** [comment]
The main driver sending a menu reset followed eventually by a list request for the main menu instead of first requesting which menu to display is the cause of the main menu being forced into position zero before any navigation input.

As far as I can tell, the behavior can't be changed within the xmb driver without duplicating some work or making changes to the display list controller.

I don't want to change the display list controller because the changes might break other menus.

I don't want to duplicate work with input from a maintainer because the duplication could potentially become out-of-sync at some point.

I think for now keeping the main menu at position zero and simply hiding most elements of the would be for the best.

**Comment by gitghostcoder** [comment]
@Kivutar 
I've been trying to recreate the crash on the current code. I'm pretty sure I got the bugs related to the history tabs fixed, and I wanted to offer a reason for needing a reset in the event you get back to me on the current code.

The fact is I kept hiding the settings tab when I was testing my code just tapping left once more than intended, and I figured needing a reset after a change is a small price to pay to help prevent users accidentally hiding the settings tab for environments like Lakka where manually editing the configuration isn't as simple as on a computer.

**Comment by Kivutar** [comment]
How can I try your new code?

**Comment by gitghostcoder** [comment]
I've just been trying to recreate your crash as a break from working on the two issues I know about. I haven't submitted a pull request against the alternate implementation because I'm still working on the graphic artifacts with one tab and the main tab at position zero before navigation issues.

You should be able to clone the https://github.com/gitghostcoder/RetroArch, the alternative implementation, which I believe has the history tab bugs fixed.

To explain myself in case it is an issue, I didn't want to cancel this pull request because I found competing claims as to whether or not the conversation would be lost.

**Comment by gitghostcoder** [comment]
I've again added and updated the fix for showing the correct movie, film, and history icons which was missing from my repository. I would have caught that sooner, but I didn't have the image files for them in the assets folder for my test installation.

I've also added some code to use the labeling hooks to show more usable, hopefully, values instead of just integers. You get a nice "Left or Playlist" or "Right of Playlist" instead of an arbitrary integer.

**Comment by twinaphex** [comment]
@kivutar Can we review this again and if it's OK, merge it?

**Comment by gitghostcoder** [comment]
@twinaphex 

I made the mistake of asking for a pull too soon for the featured code. I had made a silly assumption about the environment causing a serious bug. The current code changes is now, I believe, free of such serious bugs. However, the current code does need a little more work.

I believe the code is /stable/, but I do not believe the code is /good/, and I'd appreciate a little more time. If you just want to cross the pull request off the list, I'd prefer you to close and allow me to reopen after a little more time.

1) I'd like to fix the main menu being displayed before navigation instead of the expected menu if the user has moved or hidden the main menu. I've decided to reuse code already in the list display controllers by issuing a controller command of the appropriate type. I think the approach is consistent with the rest of the architecture, and I'll only need to make a couple of small changes to reuse those commands.

2) I'd like to revisit one of the ideas suggested by RobLoach and people on the forum. If the history system is disabled, I'd like to hide the relevant history menus by default. I'd also like to hide the history menus if the associated history is empty. I believe the change makes the displayed menus more dynamic and just in general a quality of life improvement.

3) Distributions like Lakka need a simple hook to disable hiding either the main menu or the system menu. I've been playing with RetroArch on a few different environments, and I think suppressing the option to completely hide either main or settings within the gui is crucial for some environments. You don't want users to accidentally hide the only normal way to safely reboot or shutdown their hardware. I don't want to disable the option completely. I just want to prevent the option to completely hide crucial menus within the gui as a form of accident insurance when required by distributors.

4) I have a few more code quality and consistency improvements to make.

**Comment by Kivutar** [comment]
Ok I tested his branch here https://github.com/gitghostcoder/RetroArch (which doesn't reflect this current PR)

I haven't noticed major bugs. I have just a few requests:

1) Please prevent users to hide the main menu. The main menu is too important for now to be hidden. And anyway, hiding it on your current code doesn't work and would require huge refactoring of RA. And we don't want to be in a case where there is no tabs at all and the menu is completely empty.

2) I would prefer if you don't allow reordering of those tabs. Just a simple ON/OFF is enough.

3) With your new feature, we don't need the "Enable History" in the Playlist Settings anymore. We can remove it.

**Comment by gitghostcoder** [comment]
@Kivutar 

Let me ask you honestly, "a few requests" or "a few things to change if you actually want the feature merged into mains"?

1-A) As you can see from my earlier post, I've decided that on my own after trying RetroArch for some other environments. I don't want to disable the option completely in the code, but I was planning on throwing a build configuration option over a bit of code to reset either the main menu position or settings position if they otherwise would have been hidden. I know you've said main menu, but I believe both are necessary depending on the distribution.

1-B) You are not entirely correct. I'd like you to move or hide the main menu and after starting my feature fork of RetroArch move back and forth between what was the main menu and the next tab when you find the time to mess with the feature. The issue of the main menu being displayed at first comes from the deferred push in the main loop rather than asking what menu should be displayed before the deferred push. I may certainly be wrong, but I believe every other access to both the real main menu and whatever menu happens to be first behaves as expected.

1-C) I was beginning to think that moving or even hiding the main menu would be impossible without significant duplication or an architectural change, but I've been reviewing traces for three days, and I think I have a strong plan. The controller for the display lists already allows you to request a menu to be pushed so if the controller code is properly reentrant the xmb driver can just forward the request for the expected menu back to the controller. I've already tried implementing the approach and I've seen a lot of success which gives me hope.

1-D) I'm pretty sure I've already caught that possibility, but the currently uploaded code resets the history tab instead of the main tab in the event no menus would be shown. I certainly have no issues changing the reset to show the main menu instead even if everything works out as I'd like. Actually, I'd reason that if no menus would be shown something else is wrong anyway so showing both main and settings in the event is probably preferable.

2-A) I'd love you to explain why or at least give me more information and a chance to change your mind. I do want to allow hiding the menus because the feature is more commonly requested, but the very first code I wrote for RetroArch 1.3.6 focused on moving the menus, and I have seen plenty of requests for moving the import tab after the playlists and similar.

2-B) If you don't want to explain or just refuse to have your mind changed, would you be okay with keeping the reordering feature while still simplifying the menus? I have no issues at all with changing the settings code so that configuration in Settings->Menu is changed to read "Hide" instead of "Position" with values being "on/off/moved". I can also change the limits within the settings code so that only "on/off" are accessible within the gui settings.

3) I strongly disagree. I think the feature works better with the option available. Hiding the menu just isn't the same as disabling the feature. Just hiding the menu leaves RetroArch tracking and recording the information. On the flip side, disabling the feature can definitely be used as information in hiding the history tabs.

For now, I'll work on making the changes relevant to your requests that don't directly contradict my desires for the feature fork, but I would appreciate you getting back to me if you don't want to budge on your requests.

And I'm sorry about the pull request and current code being out-of-sync issues.

**Comment by Kivutar** [comment]
@gitghostcoder RetroArch is perceived as a complex software and many users are scared to mess with so much settings. For this reason, we should avoid to make it even more complex.

Having a distinction between hiding history and disabling history is exactly the kind of things we should avoid if we want to reach the masses.

We're going to have bug reports like "I enabled history but I don't see it".

Also adding things like ordering makes the code more complex. I can understand that some users want to have a "kiosk mode" to prevent their children to mess with the settings. But I don't think it's worth it maintaining the ordering code just because some people prefer to display the Music before the Movies.

However, I see that you have a deep understanding of how the menu works. And we clearly need a contributor on this side. So I prefer to vote to merge this as you want rather than loosing you. We need more capable hands.

I'll let @twinaphex try the PR on his side and give the final word, as it is his role to shape RA.

**Comment by gitghostcoder** [comment]
@Kivutar 

No. I don't want my contributions to be an all or nothing thing. I don't want to leave, and I don't want to alienate other contributors by trying to shove my approach on the project. I've literally just left that situation, and I don't want a repeat of that hostility and those issues. I know we all have other things which consumes our time, but I'd much rather delay a feature or a bug fix a few days so that stuff can be discussed a little.

I also know that maintainers leave. I like the project, but things happen. I don't want to leave the code in the state that it is for exactly that reason. Please, I'd just like a little more time to work the code before the project developers make anything like a decision. I didn't know going in how much code I'd have to touch so I just wrote the code where I needed not where the code needed to live. I do know now where the code needs to live, and I can all but vanish the extra complexity of ordering versus simply hiding by moving all of the ordering related stuff where it needs to live. You'll have, for example, switch(xmb_get_node(xmb, i)) instead of switch(i) as in the original code or a lot of else if as in my current code.

Anyways, I see what your saying with the likely "I enabled history but I don't see it." issue. I was concerned about a similar but different complaint. Now that I also know your concerns with having both, I think I can solve things to our satisfaction just using the existing settings related hooks. I'm fairly certain I can tie the settings together in such a way as to effectively eliminate the distinction. I think I can cover 99% of users while still protecting them from the issues both of us imagined. 

Arguably just as or even more important, keeping the disable/enable history feature unrelated to the currently xmb specific tab hiding keeps the other menu drivers working without needing to change their code or the various task code for managing the history playlists. To be honest, I don't really think the other menu drivers benefit from the feature as much as xmb so I'm wary of touching that unrelated code. I'd rather solve the issue within the settings, localization, and xmb code I've already touched if at all possible.

If you have any other concerns or suggestions, please let me know. Really.

@twinaphex

Once again for you in case you missed the fact: I was new to github when I started make the feature public so the code in the pull request doesn't match the current code which lives at the https://github.com/gitghostcoder/RetroArch repository.

**Comment by gitghostcoder** [comment]
@Kivutar 
@twinaphex 

I'm pretty satisfied with the state of the current https://github.com/gitghostcoder/RetroArch code.

If whoever else needs to be satisfied is satisfied, I think we can get the feature merged.

I don't want to drown the two of you, but I do want to give a little explanation for what is changed.

1-A) The HAVE_KIOSK and HAVE_XMB_REQUIRESETTINGS build options, which are disabled by default, now exist.

1-B) The HAVE_KIOSK option primarily governs how the menus relevant to my feature behaves. When disabled, the option for hiding the main menu does not exist and the gui shows a simple on/off arrangement for setting tab visibility.

1-C) The HAVE_XMB_REQUIRESETTINGS option enables a similar bit of code to govern the settings menu. I'm pretty sure hiding settings in some environments would be a significant issue so wanted to provide distributions an easy path to preventing the setting menu from being hidden.

2-A) The main menu can not be moved of hidden at all. I intended to suppress the possibility with a build option, but the possibility doesn't now exist. I discovered that some controllers use global state in a way that prevents the reuse I had been exploring.

2-B) You might notice that the support code related to hiding the main menu still exists. With a HAVE_KIOSK build, people who want a "kids mode" have the option of suppressing those entries in the main and quick menus which represent the heart of the issue.

3) I have partially combined how the history setting and tab hiding works. If any history tab is shown, the history is reset as enabled. If the history is enabled and all the history tabs are hidden, the tabs are reset to be shown. The code with all the history tab test macros and conditions isn't particularly nice to look at, but I think I've done a fair job limiting user confusion.

4) I've moved most of the complex bits into a pair of functions so all the position setup and access is isolated.

**Comment by gitghostcoder** [comment]
I know I said I happy, but I wanted to make one more change for consistency and simplicity after spending more time using my build.

With respect to the concerns @Kivutar has for intimidating menus, I've made the menu hiding options in the gui an advanced setting so that they can be hidden away if desired.

**Comment by gitghostcoder** [comment]
@twinaphex

You merged the wrong code!

Oh man, I wish I hadn't screwed up.

The code at https://github.com/gitghostcoder/RetroArch has the code that /actually/ works.

Whether you merge the working code or not, you need to revert. Like, now!

I wish I'd made a different pull request or something...

**Comment by Alcaro** [comment]
Sure, can do.

Next time, please use an issue instead of PR unless it's intended for merging, @twinaphex hates no-merge PRs.

**Comment by gitghostcoder** [comment]
@Alcaro 

The correct code at https://github.com/gitghostcoder/RetroArch is intended to be merged. I had some flaws, and some issues came up so I've worked on the code since making the pull request. I'm new to github and somehow made things so I couldn't cancel this pull request so I could replace it one that had the issues resolved.

Again, I'm really sorry.

**Comment by Alcaro** [comment]
If your PR is buggy, you can push more commits to the same branch to fix it, it'll update the PR. It looks like you instead deleted and recreated some branches and forks; it _works_, but as you saw, it tends to cause a bit of a mess.

The cancel button is called 'close', should be beside the Comment button. Doesn't really work if the PR is already merged, though.

**Comment by gitghostcoder** [comment]
Yeah. I've certainly seen that now.

I had looked on a certain Q/A site, but the advice I received was either misinformed or simply outdated.

Don't worry though, I have learned that lesson.

**Comment by oblitum** [comment]
Hi. I was just looking the discussion here and simply couldn't understand whether any good code got merged in the end. The referred branch supposed to be hosting what was good is now dead.

**Comment by oblitum** [comment]
Ah. Nevermind. I see now it was reverted. Sad I'm still missing this.

**Comment by twinaphex** [comment]
Actually tab hiding has been implemented, just in a different way.

**Comment by oblitum** [comment]
Ah OK. Any links with docs about it?

**Comment by Kivutar** [comment]
Go in Settings->Menu and choose the tabs you want to show or hide.

**Comment by oblitum** [comment]
@Kivutar Thanks. I guess this shouldn't be available in the latest cubox-i build. I'm not seeing any tab hiding option.

**Comment by Kivutar** [comment]
It's because I'm late to release a new upgrade of Lakka. But don't worry,this feature is already in our development builds. So it should be released as soon as I can come back home and do all the required manual testing.

**Comment by oblitum** [comment]
Nice!

**Pull request merged**
