### PR TITLE
Rotation fixing

### PR DESCRIPTION
**Pull request by Aethyrion**
## Description

Fixes for rotation not working properly with shaders (only for openGL), 1:1 PAR and Integer Scaled Custom Viewport.

## Related Issues

https://github.com/libretro/RetroArch/issues/8876

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

@Autechre64 
@hunterk

### CODE REVIEW

**Comment by Tatsuya79** [comment]
I'm really confused testing this I must say. :sweat_smile: 

I'm noticing for Dimaho with FBNeo, changing the rotation while the ratio is already on PAR gives a wrong result, but then if you change the ratio again while you're rotated from PAR to something else and back to PAR will then be the right aspect.
And that's the case prior to that PR already.

**Comment by Aethyrion** [comment]
> I'm really confused testing this I must say. 😅
> 
> I'm noticing for Dimaho with FBNeo, changing the rotation while the ratio is already on PAR gives a wrong result, but then if you change the ratio again while you're rotated from PAR to something else and back to PAR will then be the right aspect.
> And that's the case prior to that PR already.



> I'm really confused testing this I must say. 😅
> 
> I'm noticing for Dimaho with FBNeo, changing the rotation while the ratio is already on PAR gives a wrong result, but then if you change the ratio again while you're rotated from PAR to something else and back to PAR will then be the right aspect.
> And that's the case prior to that PR already.

You're right, the viewport is not updated when you change the rotation from the menu. I'll try to fix that (already existing) issue as well.

All the issues that I have fixed, if you want to test them:
- Shaders are now working properly (only in OpenGL) when rotating both from Core API rotation and from menu video rotation. The fix is clearly visible with crt-royale for example.
- 1:1 PAR is now correct when rotating (both from Core API rotation and from menu video rotation, as you said, in the latter case you currently have to change Aspect Ratio after menu video rotation for it to work).
- When using Custom Aspect Ratio and rotation (both from Core API rotation and from menu video rotation), Integer Scaling is now working properly (correct multiples of internal resolution). Even when Integer Scaling is not activated, the Custom AR width / height are now correctly labeled using (1x), (2x), ... suffixes. You also have to activate Integer Scaling after menu video rotation for it to work.
- (my last commit) For all other Aspect Ratio options, Integer Scaling and rotation (both from Core API rotation and from menu video rotation) are now working properly together (correct multiples of internal resolution). You also have to activate Integer Scaling after menu video rotation for it to work.

All the tests I have done are positive so far.

**Comment by Tatsuya79** [comment]
Ok, I had some issues with megaman x on snes9x but it's fine with the latest commit.

It's still wrong in beetle_pce though, rotation with PAR. Could be something with the core.

**Comment by Aethyrion** [comment]
Custom Aspect Ratio values and 1:1 PAR are now updated correctly when you change the rotation from the menu.

**Pull request merged**
