### PR TITLE
menu_widgets: fix crash with tasks

### PR DESCRIPTION
**Pull request by natinusala**

### CODE REVIEW

**Comment by orbea** [comment]
Do you know if there are any open issues for this?

**Comment by natinusala** [comment]
I don't think so, as it will only _crash_ when using ASAN so regular users won't see this

**Comment by orbea** [comment]
This breaks the `C89_BUILD=1` build with clang.
```
menu/widgets/menu_widgets.c:1997:27: error: ISO C90 forbids mixing declarations
      and code [-Werror,-Wdeclaration-after-statement]
   menu_animation_ctx_tag tag = (uintptr_t) &libretro_message_timer;
                          ^
1 error generated.
Makefile:202: recipe for target 'obj-unix/release/menu/widgets/menu_widgets.o' failed
make: *** [obj-unix/release/menu/widgets/menu_widgets.o] Error 1
```

**Comment by natinusala** [comment]
Fixed :+1:

**Pull request merged**
