### PR TITLE
Show actual refresh rate and allow setting from video menu

### PR DESCRIPTION
**Pull request by bearoso**
So it's kind of irksome how the estimated refresh rate works, and since we live in an age where most APIs now know that 60Hz isn't usually 60Hz, I thought I'd use those APIs and expose the actual video-timing refresh rate to the user. This way, you can know for sure it's correct, or even see if you're getting the refresh rate you're supposed to in fullscreen mode.

I've used the APIs for X11, Wayland, and Windows (WDDM) to get the actual refresh rate, and added an option to the video settings below the estimated refresh rate. It only shows up if there's API support. The neat thing is that the X11 and Wayland interfaces in RetroArch already know about the correct timing, but don't ever use it anywhere. Windows only allows this through WDDM, which is Windows 7 and above only. I've also got standalone tests working for DRM and the fbdev interfaces if this is a good idea.

Anyway, if this interests anyone, let me know. It may not be something you want to add. The menu item thing was kind of complex, so I might not have done that part right or used text that fits very well with your usual conventions.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there, I really like this. I'd definitely like to see more of it.

Is there a possibility we can use the results of these new query functions to then set the refresh rate in RetroArch automatically? This could be a separate setting/menu entry and could be a convenience feature so that we don't need to do the manual 'refresh rate' estimation that we currently have to do, where we need to wait for at least 2048 frames to have ran before we hit the OK button and we then set the refresh rate. It'd be nice to have an option that would set the exact refresh rate if this callback function is implemented with that specific context driver/display server. I assume this is what you are ultimately aiming for? If so, that is certainly something I'd love to see.

**Comment by twinaphex** [comment]
Ah, silly me, you already added that menu setting specifically! Very cool, shows you are always two steps ahead of me.

Yeah, I'm definitely in favor of this feature.

**Comment by bearoso** [comment]
There’s an #Ifdef at gfx/common/win32_common.c:287. You might need to make the check differently. I forced both defines in the build to get past the redefinition of _WIN32_WINNT earlier in the file.

**Comment by bearoso** [comment]
I've got it the Windows problems sorted, I think. It's in the same refresh_rate branch ATM. I'm going to look at the other drivers now to see which ones can be updated, then I'll do another pull request.

**Comment by mudlord** [comment]
I'm sure you can use the DWM API to also do this, in much less lines.

**Comment by hizzlekizzle** [comment]
following onto @mudlord's comment, he posted this in Discord:
```
DWM_TIMING_INFO timing_info = { 0 };
        timing_info.cbSize = sizeof(timing_info);
DwmGetCompositionTimingInfo(NULL, &timing_info);
```

**Comment by bearoso** [comment]
That’s a good solution. The question is does it work when the DWM is disabled, and for full screen exclusive mode? I can’t test because I only have Windows 10 here. If so, that will get us Vista support.

**Comment by bearoso** [comment]
It seems to work in exclusive mode, but I doubt it would with the compositor turned off in Windows 7 or Vista. 
I looked into it, and it would require linking the dwm library. I have no experience with the retroarch build system, or any clue how to do Windows version checking to conditionally load the library there, being the complete Windows novice I am. I think it'd be easiest to just start defining the _WIN32* version flags in the build system for mingw, like MSVC does automatically, and have that as a configure option.

I don't know if that's too much work for Vista support that likely no one will use. :-)

**Pull request merged**
