### PR TITLE
Add compatibility with FFMPEG 7.0

### PR DESCRIPTION
**Pull request by eclipseo**
channel_layout has been replaced with ch_layout

Fix: #16437

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
I have asked @hizzlekizzle to test this. Thanks for doing this.

**Comment by hizzlekizzle** [comment]
@LibretroAdmin just got done testing and all seems well. It does what it says on the tin.

**Comment by eclipseo** [comment]
> @LibretroAdmin just got done testing and all seems well. It does what it says on the tin.

Simplify the code following feedback from another patch from another project.

**Comment by LibretroAdmin** [comment]
Confirmed with @hizzlekizzle that the latest patch worked for him.

Thanks so much for this. This will make ffmpeg viable again on Linux.

**Comment by nunotexbsd** [comment]
@LibretroAdmin 

Hello

1.21.0 fails to build with FFmpeg 8, should I open a new PR?

```
<snip>
record/drivers/record_ffmpeg.c:377:25: error: use of undeclared identifier 'AV_INPUT_BUFFER_MIN_SIZE'
  377 |    audio->outbuf_size = AV_INPUT_BUFFER_MIN_SIZE;
      |                         ^
record/drivers/record_ffmpeg.c:954:7: warning: call to undeclared function 'avcodec_close'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  954 |       avcodec_close(handle->audio.codec);
      |       ^
record/drivers/record_ffmpeg.c:962:7: warning: call to undeclared function 'avcodec_close'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  962 |       avcodec_close(handle->video.codec);
      |       ^
2 warnings and 1 error generated.
```

Thanks

**Pull request merged**
