### PR TITLE
Add Preemptive Frames to Latency Settings

### PR DESCRIPTION
**Pull request by neil4**
RunAhead alternative that reruns core logic to "rewrite history" before the current frame. Frames are only rerun when the controller state changes, so it's faster overall.

Preemptive Frames has to peek at the input state before retro_run(), and that's kept somewhat simple. Only devices in `input_libretro_device` are checked (with a few exceptions, e.g. pointers can act as lightguns). Keyboards are ignored. Analog IDs are checked if requested in the previous frame. For other devices, the full state is checked.

For convenience, the 'Number of Preemptive Frames' setting uses the `run_ahead_frames` value. So there is no need to change two settings when swapping between the two features.

This also adds a toggle hotkey, similar to RunAhead's.

## Reviewers

@LibretroAdmin

### CODE REVIEW

**Comment by neil4** [comment]
Hold on... build failures

**Comment by hizzlekizzle** [comment]
So how does this differ from runahead, exactly?

@Dwedit would you care to take a look?

**Comment by Dwedit** [comment]
I was thinking about implementing this feature before, but the code got moved around so many times that I can't even find the runahead code anymore.  So I can't do comparisons with my own code, because it's now scattered into other places.  I think it could be helpful to undo all that scattering and put it back into runahead.c.

Anyway, having a worst-case mode would still be useful for performance testing, just hide it behind advanced mode.

**Comment by LibretroAdmin** [comment]
After Neil submits his next PRs, I can spend some time moving the runahead/pre emptive frames code to its own file

**Comment by neil4** [comment]
@hizzlekizzle It's the same basic idea, but Preemptive Frames acts a little more like Netplay, replaying past frames up to the current.

Comparing to RunAhead w/ 'second instance', both use in-memory savestates and run extra frames when input is "dirty". RunAhead does it by running its primary instance first and then comparing the requested input states to what it logged previously, which is the bulletproof way of knowing if its secondary instance needs to run more than one frame. Preemptive Frames requests input states itself before running the frame, and that gives it a reasonably good idea if a replay is needed.

To avoid running 2+ frames per frame period, it also needs to keep a savestate buffer and save states on every frame (even on replays), so that cuts into its speed advantage, and more so when the input state changes are frequent (e.g. moving a mouse or analog stick). In my own testing, it still has a speed advantage, but that can depend on the core.

In general, RunAhead is the better option when its second instance fixes audio issues, and Preemptive Frames is better for battery life (or doing a lot of fast-forwarding). And there are more minor (to me) pros and cons- Preemptive Frames as written doesn't help with keyboard latency; RunAhead's second instance adds audio latency.

**Comment by LibretroAdmin** [comment]
OK @Dwedit , did the following -

https://github.com/libretro/RetroArch/commit/f0c8008bdaef110272a10a170333659a59f3c6ab

Hope that is sufficient. Very much looking forward to your future improvements. It would be extremely nice BTW if there was some way for runahead to be improved so it can work with hardware rendering contexts as well.

**Pull request merged**
