### PR TITLE
(Network) net_ifinfo refactor

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**
## Description

Refactoring for net_ifinfo_new and net_ifinfo_free.

As usual with the network codebase, this PR fixes a significant number of issues and changes the following:
1. IPv6 support for Linux-based platforms.
2. Ignore interfaces reported as not up in order to avoid bloating the returned entries.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi, can you fix the C89 build errors?

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway You broke WiiU now -

https://git.libretro.com/libretro/fmsx/-/jobs/2139090

libretro-common/net/net_ifinfo.c:41:20: fatal error: net/if.h: No such file or directory
 #include <net/if.h>
                    ^
 Why can't you just define IFF_UP if it's not already defined instead of trying to include a header that is not guaranteed to be across all these various platforms? Seems to be just begging for issues (like what happened here).

**Comment by Cthulhu-throwaway** [comment]
Because the header file guarantees the correct flag value and that the system actually recognizes that. No point in guessing and defining it to a value if the system doesn't use it all and then we've no interfaces at all.

Needs to wrap this around to skip this check for WiiU.

**Comment by Cthulhu-throwaway** [comment]
Moreover, these Nintendo platforms are a pain in the ass. Every single improvement I make to networking it ends up breaking them, no matter how basic my changes are.

**Comment by Cthulhu-throwaway** [comment]
@LibretroAdmin turns out my approach was correct. Take a look at these:

https://github.com/libretro/RetroArch/blob/master/wiiu/system/missing_libc_functions.c#L238-L247
https://github.com/libretro/RetroArch/blob/master/wiiu/system/missing_libc_functions.c#L170-L190

ifa_flags is never set and remains at 0; forcing IFF_UP to 0x1 would've caused net_ifinfo_new to always fail on the WiiU.

**Pull request merged**
