### PR TITLE
Update the 3ds build system to match new core format

### PR DESCRIPTION
**Pull request by meepingsnesroms**
These files also need to be replaced in the buildbot repos:
[BuildBotFiles.zip](https://github.com/libretro/RetroArch/files/2019742/BuildBotFiles.zip)

RetroArch and salamander compile fine but I cant test the buildbot portions since I dont have a buildbot.

### CODE REVIEW

**Comment by fr500** [comment]
for recipe.sh you should send a PR to libretro super.
for the other you should request access to the buildbot repo and send a PR too, otherwise it's not likely gonna be sorted out

**Comment by meepingsnesroms** [comment]
I can do that, I just didnt know if a pull request was wanted on that repo.

**Comment by fr500** [comment]
yeah that's the way we roll for everything

**Comment by meepingsnesroms** [comment]
Ok I made the 2 pull requests.

**Pull request merged**
