### PR TITLE
Show useful messages to RetroAchievements user

### PR DESCRIPTION
**Pull request by meleu**
When launching a game with RetroAchievements enabled, show messages like the following:

`RetroAchievements: logged in as "RAUser"`

`You have 3 of 20 achievements unlocked`

Obs.: the number of achievements unlocked is counted according to hardcore mode being enabled or not.

**UPDATE:**
In the last commit I tried to satisfy these requirements/suggestions:

@twinaphex 
>  I can accept this as an 'achievement debug' setting, but it should not be enabled by default at least.

@leiradel 
> RetroArch has too many options already. I'd go with a unique global setting to control the verboseness of everything though.

I added the `video_message_verbosity` option (default is false). I chose this name because it's similar to other OSD-related configs (`video_message_pos_*`, `video_message_color_*`, etc). It was added in configuration.c, `settings_t.video` and named `msg_verbosity` (again, to match the `msg_pos_*`, etc.).

The RetroAchievements messages I'm introducing in this PR will only be shown if `settings->video.msg_verbosity` is true (`video_message_verbosity = true` on retroarch.cfg).

### CODE REVIEW

**Comment by fr500** [comment]
People are most likely gonna enable achievements and forget it.
This message will become annoying after the 10th time it shows up...

**Comment by meleu** [comment]
Well, I don't have statiscs, but I think exactly the oposite. Not rarely I have "timeouts" and the achievements list don't load, or load with every cheevo as locked (when I'm sure I have some unlocked)... Then I must check quick menu > achievements list to make sure they load correctly... This is annoying.
Those messages help with error diagnosis, and also are shown on official RetroAchievements emulators.

**Comment by twinaphex** [comment]
I agree with @fr500 that this might be information overload. At the very least this option should not be enabled by default and hidden behind a setting that you have to explicitly enable.

**Comment by twinaphex** [comment]
Also achievements on PSN/XBLA don't do this, list all obtained achievements out of total achievements when you start up. This would just look bad. I can accept this as an 'achievement debug' setting, but it should not be enabled by default at least.

**Comment by fr500** [comment]
@leiradel mentioned once that achievements could be cached and then posted whenever it's back online, that would be a good solution

**Comment by leiradel** [comment]
@fr500 I remember reading in the chat that caches were a no-go. I'd like to use them to cache cheevos lists, awards, and badges, so the entire thing works even without network connectivity.

**Comment by meleu** [comment]
> @leiradel mentioned once that achievements could be cached and then posted whenever it's back online, that would be a good solution

It happens when RetroArch loads the cheevos list correctly and then loose internet conection during the game. When the connection is retrieved the achievements are registered on RA site.

I agree that `logged in as "user"` is a little verbose. But I think that the number of awarded cheevos and total of cheevos is an useful info to see after loading a game.

**Comment by fr500** [comment]
@leiradel not sure why it would be a no go. I think it's the better solution.
We have at least 4 possible messages that can pop up at game startup. I would actually remove them all

**Comment by CoalaJoe** [comment]
I think this is very valuable. 
Why not make it optional?

**Comment by leiradel** [comment]
> @leiradel not sure why it would be a no go. I think it's the better solution.

I'll take a look at it after the current priorities.

**Comment by meleu** [comment]
@fr500 @twinaphex would you agree if I implement a boolean option, let's say, `cheevos_verbose` defaulting to false? When it's true those messages will be shown.
I'm not familiar with the `configuration.c` code but I can try. I'm on my days off... :-)

**Comment by leiradel** [comment]
@meleu I'd rather not have that option, RetroArch has too many options already. I'd go with a unique global setting to control the verboseness of everything though.

Having said that, I like the OSD message for a successful Retro Achievements login. Consoles have similar messages when the user logs into their networks. If the OSD is too polluted with messages, it's because we lack a better user feedback system IMHO.

**Comment by fr500** [comment]
Most of the consoles retry on the background too when they can't connect right away.
I agree, the login notifications are rather nice on other services but we don't have anything but the OSD.

Something like this:
https://files.andressm.org/f/5bc5f35a79/

A notification system with pop-ups and stuff would be nice.

**Comment by meleu** [comment]
> RetroArch has too many options already.

Yeah. I agree.

> I'd go with a unique global setting to control the verboseness of everything though.

Then I'll let it with you guys. I'm not too confident to implement this.

I think that most of the RetroAchievements users would like to see those messages. It's very similar to the official RetroArch emulators (and less verbose).

**Comment by meleu** [comment]
I forgot to mention: those messages will only be displayed if the game have achievements.

**Comment by retro-wertz** [comment]
that should be a good feature, if it can appear the same or better than
ones from retroachievements emulatoetors.

**Comment by meleu** [comment]
@twinaphex 
> At the very least this option should not be enabled by default and hidden behind a setting that you have to explicitly enable.

Would you agree if I use the `log_verbosity` for this purpose?

**Comment by meleu** [comment]
> I'd rather not have that option, RetroArch has too many options already. I'd go with a unique global setting to control the verboseness of everything though.

In this last commit I did as @leiradel suggested. I've realized that a "global setting to control the verboseness of everything" already exists. It's the `log_verbosity`, when it is true RetroArch launch as if received the `--verbose` argument on command line.

Summing up: those messages will only appear when running with `--verbose` (or `log_verbosity = true` on retroarch.cfg).

I think this also satisfies the @twinaphex requirement: 

> At the very least this option should not be enabled by default and hidden behind a setting that you have to explicitly enable.

What do you guys think?

**Comment by fr500** [comment]
Libretro log are the logs from the core. Not for the frontend.
The verbosity setting is for the stdout log though....
IDK I sustain my POV. This isn't really necessary and fencing the message with verbosity which is for stdout seems outright wrong.

Maybe we should add a messages struct to settings_t and add all the possible OSD messages so far with a setting for each instead of doing stuff at random for one particular message.

**Comment by meleu** [comment]
> Libretro log are the logs from the core. Not for the frontend.

Actually I did that based on the description of `log_verbosity` on config skeleton:
```
# Enable or disable verbosity level of frontend.
# log_verbosity = false
```
And later I realized that it's the same as using `--verbose` on command line.

Well, I think I'm starting to be annoying with this insistence, but as the PR wasn't closed I think there's a hope. So let me just list some points and stop:
- The messages are shown only when cheevos are enabled **and** there is an entry about the game on RetroAchievements.org database (they won't be shown with every single game loaded).
- I talked about the messages with other RetroAchievements players (people who really like to earn those points) and they liked.
- It's an useful feature when you just launch a "random" game from your set and can immediately know if there are achievements for that game (no need to go to the retroachievements.org, log in, check the last game on your wall, and then check if there are achievements for it).

**Comment by RobLoach** [comment]
> This message will become annoying after the 10th time it shows up...

Haven't read the full backlog here, but I must agree with @fr500 here...

1. The messages would get annoying. I removed the message "Achievements found/notfound and enabled" message that popped up before, just because it was so annoying.
2. Verbosity is for stdout logs, not overlay messages

Perhaps a solution around it would be to move the message to the top of the Achievements menu....
screenshot at 2016-12-12 11-02-06

**Comment by meleu** [comment]
@RobLoach I remember those messages you removed and I agree, they were really annoying. Specially when running a core for a system that doesn't support cheevos.

The messages I want to introduce in this PR would be shown only if the game has an entry in retroachievements.org database.

And that verbose thing was an attempt to satisfy a requirement from @twinaphex (hide the messages behind a setting that you have to explicitly enable). To avoid the creation of one more option for `settings_t` I tried this solution, but maybe there is a better approach to implement the messages as an option.

Based on the last @fr500 comment, I'm thinking on a boolean option `video_message_verbosity` (or something). What do you guys think?

**Comment by meleu** [comment]
Next attempt to satisfy the libretro members requirments/suggestions.

In the last commit I added the `video_message_verbosity` option (default is false). I chose this name because it's similar to `video_message_pos_*`, `video_message_color_*`, etc. It was in added configuration.c, `settings_t.video` and named `msg_verbosity` (again, to match the `msg_pos_*`, etc.).

The RetroAchievements messages will only be shown if `settings->video.msg_verbosity` is true (I removed the `--verbose` condition).

I think this satisfies those requirements/suggestions:

@twinaphex 
>  I can accept this as an 'achievement debug' setting, but it should not be enabled by default at least.

@leiradel 
> RetroArch has too many options already. I'd go with a unique global setting to control the verboseness of everything though.

@fr500 (maybe partially satisfies)
> Maybe we should add a messages struct to settings_t and add all the possible OSD messages so far with a setting for each instead of doing stuff at random for one particular message.

I agree with @leiradel opinion that RetroArch has too many options and then I added the option as a way to define the global OSD verbosity. But if you guys think that it sould be very specific to cheevos, I can easily add such option in `settings_t.cheevos` (maybe `cheevos_verbose_enable` or something).

**Comment by meleu** [comment]
Just clarifying why I think those RetroAchievements messages useful (maybe it would be an edge case, but it's worth to mention):

- It is a similar behavior as the official RetroAchievements emulators.
- **Network timeout is a very common issue**. I'm not sure if it happens because the RetroAchievements.org servers aren't that powerful or because my internet connection is poor, but it's a common issue. The following items are consequence of this problem.
- Happened a few times that I started playing a game to earn some cheevo and after a hard part the cheevo didn't trigger. And then I realized that the achievements list didn't load. It's really frustrating. In practice, every time I want to earn cheevos I have to load the game, launch RGUI -> Quick Menu -> Achievements List. I think it's much more annoying than having those OSD messages ("OK. I'm logged in and the cheevos were loaded. Let's play!").
- I was helping @leiradel with testing and collecting users reports (the edge case I mentioned):
  - you know that testing is a bit tedious. I went to achievements list hundreds of times to check if the user logged in, the game was recognized, the achievements list loaded. The OSD messages would be much less painful than invoking RGUI -> Quick Menu -> Achievements List.
  - many many many users report that a game isn't working and later, with no fixes on the RetroArch code, they come back saying "oh! Now it's working fine". I think those OSD messages would avoid these false positive reports.

**Comment by retro-wertz** [comment]
#4231 - any update on this? would like to do more retroachievement-related test(especially if Chi no Rondo  will be supported) if ra was not crashing

**Comment by fr500** [comment]
@retro-wertz don't do that. This is not a forum. This is an issue about OSD messages and nothing else.

**Comment by grenade44** [comment]
Just wondering if this will be merged? I would love to get these handy messages.

**Comment by meleu** [comment]
Hey guys. Since 1.4 was released (nice work, by the way) can we reopen the discussion here?
I think the only thing we have to decide is: how RetroArch should control the OSD verbosity?
What approach?
What you guys (libretro team) decide I'll do in this PR. :)

**Comment by meleu** [comment]
As the cheevos.c has been moved, I am closing this PR and will try to submit another using the new location soon.

**Comment by meleu** [comment]
Just to let the participants of this conversation know: I'm trying to add the feature I tried here in another PR: #5138

**Comment by meleu** [comment]
OK guys, #5128 was merged. Now I've added that option to Achievements menu and submitted the PR #5140 . The result is something like this:

ra_menu

**Pull request closed without merging**
