### PR TITLE
(cheevos) challenge indicators

### PR DESCRIPTION
**Pull request by Jamiras**
## Description

Adds support for a new achievement feature.

Achievements can be written to show an indicator when a they are eligible to trigger. This provides useful feedback to the player so they can immediately tell when they fail a challenge. There are some previous attempts to do something similar using dummy leaderboards.

The feature is on by default, but can be disabled by the user:
image

When an eligible achievement activates the functionality, the achievement's icon will appear in the bottom right corner of the screen:
image

Up to eight indicators can be shown at one time (though rarely more than one or two should be). If indicators and leaderboard trackers are both visible, the tracker will appear above the indicators.
image

## Related Issues

n/a

## Related Pull Requests

n/a

## Reviewers

@Sanaki @meleu

### CODE REVIEW

**Comment by IlDucci** [comment]
"Indicators" might be a divergence from the usual term on RetroArch, "Notification"/"Notificators". Please double check you are following RetroArch's namings on this PR and the previous one.

**Comment by Jamiras** [comment]
I can't find any references to "Notificator" in the RetroArch codebase (or dictionary.com)
```
/e/source/RetroArch
$ grep -rnIi notificator *

/e/source/RetroArch
$
```

I associate notifications with messages. There's no text associated to this indicator. It works like a boolean - it's either on or off. You wouldn't call that little green light on the front of your computer a "power notificator", would you?

Also, it's called an Indicator in other RetroAchievements uses outside of RetroArch. It's a RetroAchievements feature more than a RetroArch feature. To which should it be standardized?

**Comment by IlDucci** [comment]
> Also, it's called an Indicator in other RetroAchievements uses outside of RetroArch. It's a RetroAchievements feature more than a RetroArch feature. To which should it be standardized?

Sorry, I didn't know it was a RetroAchievements term. Well, unless the main team has something against it, you probably want to use RetroAchievements' standard.

**Comment by DisasterMo** [comment]
Notification: an act or instance of notifying, making known, or giving notice
Inficator: a person or thing that indicates, signals, or points out
Just grabbed the first fitting definitions from dictionary.com. First, I agree that 'Notificator' isn't a thing. Now, please explain to me how exactly this 'indicator' works - for me it sounds something like:
You play a game and earn an achievement
The indication pops up, notifying you of said achievement 
The pop-up fades away

If that is the case, then this is undoubtedly a _notification_. An indicator should continuously point something out, like whether the power is on or not, whether the disk is being accessed, the progress of a file move (yeah right <.<) etc. It doesn't just blink up once when you start your PC and then immediatly turns off, does it? Notifications do, because their only purpose is to notify about an event occuring, not to monitor whether it continues or not.

As for which standard to follow: I am not one to decide this, but in my opinion we should stick to the RetroArch standards since this is a setting within and for the RetroArch front-end.

**Comment by Jamiras** [comment]
I've added screenshots. I should clarify that the indicators are the icons in the lower right part of the screen. They are visible when the challenge in active, and hidden when it's not. These screenshots are from a test achievement, so they're not the best example. 

A common use case would be a damageless boss achievement. The indicator would be shown when starting the boss fight, and disappear as soon as the player takes damage indicating they're no longer eligible to unlock the achievement.

**Pull request merged**
