### PR TITLE
add traditional Chinese language files

### PR DESCRIPTION
**Pull request by asakous**
basically convert from simplified Chinese with few term adjustment

### CODE REVIEW

**Comment by bparker06** [comment]
Why are you overwriting the simplified translation with a traditional one?

**Comment by bparker06** [comment]
Sorry, my mistake. I do see that the filename is different. But I don't see any additional hooks added into RetroArch to support this language.

**Comment by bparker06** [comment]
@asakous I went ahead and fixed up a couple errors with your PR and added the necessary GUI hooks in df09b0d so the language is actually selectable from the menu now.

**Comment by asakous** [comment]
thanks

**Comment by asakous** [comment]
I didn't. According to my source code 
Simplified translation is different from traditional one.  Traditional Chinese is mainly use in Taiwan and Hong Kong . You think there are the same files but actually not. Because some characters look same others are don't . Ex simplified 光駆 traditional 光碟。one character different but all point to same thing .

從我的 iPhone 傳送

**Comment by asakous** [comment]
sorry I didn't see the last mail you sent. never mind I said .
and Yes I did hook up traditional Chinese language . I only add translated files.

從我的 iPhone 傳送

**Pull request merged**
