### PR TITLE
I have added a new theme for Ozone (Ocean Blue)

### PR DESCRIPTION
**Pull request by SecularSteve**
## Description

It's just what it sounds like. A theme meant to be very calm and pleasing for your eyes, and your screen.
I even added a small tutorial for beginners in the ozone_theme.c file (for the floats).
Please check if there are any issues, this is literally my first time working with this.

## Related Issues

Sorting the "float" code in ozone_theme.c to the right places (like alphabetising a bookshelf).

## Related Pull Requests

https://github.com/libretro/RetroArch/commit/6f29c1ff94b7b1a839848afbbe447b034885b1d3

## Reviewers

Nobody comes to mind at the moment.

### CODE REVIEW

**Comment by Ryunam** [comment]
Thank you for making this! I was working on some Ozone themes myself, so having some new colors to choose from (especially variants of blue) is very much appreciated.

Could you please include a preview screenshot of what it looks like? Also, I think the commit history appears to be a bit disjointed right now...

**Comment by twinaphex** [comment]
We could squash and merge the PR later.

A bigger concern though is that all the Travis tests have failed.

**Comment by SecularSteve** [comment]
Apparently, the logs say my new theme is "undeclared" for some reason, and it thinks I mean "Dracula" instead.

`[2021-05-20 12:55:57] [build-stderr] menu/drivers/ozone/ozone_theme.c:684:12: error: ‘OZONE_COLOR_THEME_OCEAN_BLUE’ undeclared (first use in this function); did you mean ‘OZONE_COLOR_THEME_DRACULA’?`

Did I miss a step somewhere?

**Comment by Ryunam** [comment]
I believe what’s missing is that you also need to declare the new theme name inside the corresponding enum at line 358 of `menu/menu_defines.h` here: https://github.com/libretro/RetroArch/blob/29475a904fc7927a3de5fe85cf7d1fc312da062b/menu/menu_defines.h#L358

Add `OZONE_COLOR_THEME_OCEAN_BLUE, ` before `OZONE_COLOR_THEME_LAST`and I think it will work.

**Comment by gouchi** [comment]
- I confirm adding the enum like Ryunam said make it compile.

- Here is a screenshot of this new theme 

ozone-ocean-blue

**Comment by SecularSteve** [comment]
> 
> 
>     * I confirm adding the enum like Ryunam said make it compile.
> 
> 
> ```
> diff --git a/menu/menu_defines.h b/menu/menu_defines.h
> index a526c15b19..52e3d2fcdc 100644
> --- a/menu/menu_defines.h
> +++ b/menu/menu_defines.h
> @@ -365,6 +365,7 @@ enum ozone_color_theme
>     OZONE_COLOR_THEME_HACKING_THE_KERNEL,
>     OZONE_COLOR_THEME_TWILIGHT_ZONE,
>     OZONE_COLOR_THEME_DRACULA,
> +   OZONE_COLOR_THEME_OCEAN_BLUE,
>     OZONE_COLOR_THEME_LAST
>  };
> ```
> 
>     * Here is a screenshot of this new theme
> 
> 
> ozone-ocean-blue

Just as good as I expected it.
Though the sidebar is the "reverse" of what I expected.

Don't forget to check the "running" mode when you toggle the menu during a game.

**Comment by hizzlekizzle** [comment]
Yeah, i think the text and background need higher contrast.

**Comment by SecularSteve** [comment]
Check it again, I think I just fixed it.

**Comment by twinaphex** [comment]
Hi there, this theme was not yet submitted to retroarch-assets so everytime now it brings up a warning in RetroArch that assets are missing.

Can you submit a PR to retroarch-assets adding this new theme? Afterwards, I can re-revert this and add it back. For now, I have to revert this since it inconveniences every RetroArch user right now.

Let me know though if you can get this done, I'll be sure to re-revert it again so it's back in RetroArch.

**Pull request merged**
