### PR TITLE
 qb: Add --enable-c89_build and --enable-cxx_build. 

### PR DESCRIPTION
**Pull request by orbea**
## Description

This only affects `qb` builds and `C89_BUILD` and `CXX_BUILD` are only used with `qb`.

This fixes a long standing limitation in the way `C89_BUILD` and `CXX_BUILD` are handled by implementing `--enable-c89_build` and `--enable-cxx_build` for `qb`.

Now the configure process is capable of disabling features with C89 or C++ builds dynamically which solves a long list of issues.

Passing `C89_BUILD=1` or `CXX_BUILD=1` to `make` is still supported in this PR, but using the configure arguments will work much better and is highly preferred.

Additionally in the future we could consider only supporting the configure arguments and not supporting passing  `C89_BUILD=1` or `CXX_BUILD=1` directly to `make` for a few reasons.

* It would allow removing redundant code in qb.
* Future improvements I am planning will not work well unless this limitation is fixed and passing theses variables to `make` would defeat that.

The second commit implements this change for travis.

## Related Issues

Here are a few of the many issues this solves.

* It disables unsupported features much earlier in the process allowing to properly create `config.mk` and `config.h`.
* Because the unsupported features are disabled sooner any relevant configure checks will be skipped when appropriate.
* Allows checking for the correct switch during configure, `-std=gnu99` for default builds, `-std=c89` for C89 builds and `-xc++` for C++ builds.
* Allows for better error checking for configure arguments, for example `./configure --enable-vulkan --enable-c89_build` will not result in a configure error instead of silently disabling vulkan support like before with `./configure --enable-vulkan && make C89_BUILD=1`.
* Correctly sets `HAVE_C99=no` for both `--enable-c89_build` and `--enable-cxx_build`.
* An old minor bug in `check_switch` is fixed which this PR would expose.

## Related Pull Requests

PR https://github.com/libretro/RetroArch/pull/9211 helped implement this one.

## Reviewers

Let travis pass first since it should fully test `C89_BUILD` and `CXX_BUILD` build paths.

Some things to note.

* This adds a `check_disabled` function which more or less does the opposite of the already existing `check_enabled` function. If any of the variables in the first argument (`$1`) is true it will automatically disable the variable in the second argument (`$2`). For example:
```
# If 'HAVE_C89_BUILD' or `HAVE_CXX_BUILD` is 'yes' then `HAVE_C99` will be disabled.
check_disabled 'C89_BUILD CXX_BUILD' C99
```
* This adds an internal `check_build` function to handle the `C89_` and `CXX_` variables set in `qb/config.params.sh`. I don't expect this will be needed outside of two instances in the recent `add_opt` function and in `qb/qb.make.sh`.
* This changes how `qb/config.params.sh` needs to be edited in the future for `C89_` and `CXX_` variables where they will need a comment like other variables. The comment differs a little in that they are not used by `./configure --help`, but used to populate error messages. For example
```
# If someone uses './configure --enable-vulkan --enable-c89_build' 
# it will result in a configure error.
C89_VULKAN=no              # Vulkan is
```
```
Error: Vulkan is not supported with C89 builds.
```
Where the comment must be the name of the feature (`Vulkan`) and a verb (`is`/`are`) where the rest of the message `not supported with C89/C++ builds` is hardcoded. I am not sure there is any better way around this.
* If someone uses both `--enable-c89_build` and `--enable-cxx_build` it will respect the last one passed to configure and then print a warning.

### CODE REVIEW

**Comment by orbea** [comment]
Does anyone have an opinion if `--enable-c89_build` and `--enable-cxx_build` or `--enable-c89` and `--enable-cxx` is better? The former is clearer, but the latter is easier to type.

**Comment by twinaphex** [comment]
I'm not too sure really if the configure system should be doing this. I am especially not a fan of removing C89_BUILD and CXX_BUILD from regular Make. I definitely do not want to force people to use the configure scripts there.

So I'm not so sure what the point here is.

**Comment by orbea** [comment]
> I'm not too sure really if the configure system should be doing this.

Why not? Configure already does half the job, this just allows it to handle it much better.

> I am especially not a fan of removing C89_BUILD and CXX_BUILD from regular Make. 

It has not been removed in this PR, just a much better working alternative has been added.

> So I'm not so sure what the point here is.

I explained a lot of reasons, to put it simply configure will work much better in regards to the C89 and CXX code paths and this will open the door for other improvements and clean ups in the future.

**Comment by orbea** [comment]
@hhromic Sorry, this can be considered a won't fix and that this build system is now unmaintained.

**Comment by bparker06** [comment]
Not every platform uses configure and we still need to be able to test otherwise unreachable codepaths for C89/CXX compatibility.

**Comment by hhromic** [comment]
@orbea thanks for the heads-up. I'm confused about this:
> this build system is now unmaintained.

Are you referring to the current qb/configure build system in RetroArch?
You mean that it is being discontinued?

**Comment by twinaphex** [comment]
Qb/configure build system is not discontinued or unmaintained.

**Comment by hhromic** [comment]
That's great news, the build system is very handy. Cheers!

**Pull request closed without merging**
