### PR TITLE
(PSL1GHT) Add improvements to the RSX driver

### PR DESCRIPTION
**Pull request by OsirizX**
These changes to the rsx driver enables the xmb/ozone menus as well as frame rate improvements.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Oh, thats out of the blue and amazing to hear! I hope with these changes it can finally become a good main build for PS3!

**Comment by crystalct** [comment]
I tired to compile for PSL1GHT....
`
griffin/../deps/libz/adler32.c: At top level:
griffin/../deps/libz/adler32.c:49:10: error: conflicting types for 'adler32'
 uint32_t adler32(uint32_t adler, const uint8_t *buf, size_t len)
          ^~~~~~~

In file included from griffin/../libretro-common/file/archive_file_zlib.c:34:0,
                 from griffin/griffin.c:132:
/usr/local/ps3dev/portlibs/ppu/include/zlib.h:1688:23: note: previous declaration of 'adler32' was here
 ZEXTERN uLong ZEXPORT adler32 OF((uLong adler, const Bytef *buf, uInt len));
                       ^~~~~~~

In file included from griffin/../deps/libz/gzguts.h:171:0,
                 from griffin/../deps/libz/gzclose.c:6,
                 from griffin/griffin.c:1484:
griffin/../deps/libz/gzfile.h:5:8: error: redefinition of 'struct gzFile_s'
 struct gzFile_s
        ^~~~~~~~

In file included from griffin/../libretro-common/file/archive_file_zlib.c:34:0,
                 from griffin/griffin.c:132:
/usr/local/ps3dev/portlibs/ppu/include/zlib.h:1300:16: note: originally defined here
 typedef struct gzFile_s *gzFile;    /* semi-opaque gzip file descriptor */
                ^~~~~~~~

In file included from griffin/griffin.c:1492:0:
griffin/../deps/libz/uncompr.c:24:5: error: conflicting types for 'uncompress'
 int uncompress (
`
I forgot something?

**Comment by crystalct** [comment]
Yes... the right order of Includes....

**Comment by OsirizX** [comment]
> I hope with these changes it can finally become a good main build for PS3!

It should be for the most part although more improvements can be made to reduce flickering in the menus

@crystalct 
Seems you're not loading zlib.h header from libretro-common/include/compat/zlib. Makefile.psl1ght has this path as part of INCLUDE so that the compiler looks at these paths before the system default (/usr/local/ps3dev/portlibs/ppu/include/)

**Comment by crystalct** [comment]
^_^

**Comment by crystalct** [comment]
@OsirizX 
is set_rotation implemented?
rotation is alway orizontal...

**Comment by OsirizX** [comment]
@crystalct 
I've submitted the fix [here](https://github.com/libretro/RetroArch/pull/14990) for video rotation

**Comment by krimnassim** [comment]
hi.OsirizX,idon't know if this is the right place to ask you this,can you please fix retroarch online core updater for jb ps4,if you can make updated cores.pkg sorry i don't know how this stuff works and i really appreciate your work.

**Comment by krimnassim** [comment]
> @OsirizX  hi.OsirizX,idon't know if this is the right place to ask you this,can you please fix retroarch online core updater for jb ps4,if you can make updated cores.pkg sorry i don't know how this stuff works and i really appreciate your work.

**Pull request merged**
