### PR TITLE
(Wayland) Fix resize check

### PR DESCRIPTION
**Pull request by ColinKinloch**
## Description

This solves MR two issues:

* On scaled desktops the wayland backend deciding to resize based on values multiplied by the scale factor twice. Resulting in continuous attempts to rebuild the swapchain when in fullscreen.

* GL is sometimes not rescaling property (Super + Left).

Screenshot from 2023-03-06 18-57-08

Also on 

## Related Issues

#15062

## Reviewers

@nfp0

### CODE REVIEW

**Comment by nfp0** [comment]
Hey @ColinKinloch 
Thanks for looking into this! :)

Does this also fix the shader corruption and swapchain invalidation?
I can only test later.

**Comment by ColinKinloch** [comment]
I didn't get round to trying to reproduce the specifics of your issue, just finding where `VK_CTX_FLAG_INVALID_SWAPCHAIN` was being set and figuring out why it was being run. Hopefully it'll work.

I haven't felt motivated to look at RetroArch since #14485, it really could do with maintaining a connection to the wayland compositor.

**Comment by LibretroAdmin** [comment]
@ColinKinloch Can that PR be safely merged? Are there any downsides to merging it from a backwards compatibility perspective?

**Comment by nfp0** [comment]
@ColinKinloch Alright. I'll give it a test tomorrow and report if it fixes the issues or not.

**Comment by ColinKinloch** [comment]
@LibretroAdmin Yes it can, resizes happen in order.

**Comment by nfp0** [comment]
@ColinKinloch Yes! It's fixed! :smiley: :tada: 

I've tested your branch and the shader corruption is gone! The log spam is gone too, as the swapchain is not being recreated every frame anymore.

The only strange thing remaining are the log messages mentioning double my resolution, such as:
`[Vulkan]: Using resolution 3840x2160.`
and
`[Vulkan filter chain]: Creating framebuffer 3840x2160 (max 1 level(s)).`

This is on a 1080p screen. The log shows the correct 1920x1080 resolution if I set scaling to 100%.
Could the shader passes still being rendered at double the desired resolution?

> GL is sometimes not rescaling property (Super + Left).

I've tried this using GL and GLCore, before your fixes, but it did not reproduce on my end.

**Comment by ColinKinloch** [comment]
I see.
When in fullscreen the vulkan/GL driver calls `set_video_mode` with the size of the display.

**Comment by ColinKinloch** [comment]
I'll fix that in another MR

**Comment by ColinKinloch** [comment]
@nfp0 That should fix the double scaling.

**Comment by nfp0** [comment]
@ColinKinloch Yes! Now the log is outputting the correct 1080p resolution in all places, so I assume everything is working as it should.
Everything I mentioned on https://github.com/libretro/RetroArch/issues/15062 seems to be in working order now! I'll close the issue.

Now I can finally play RetroArch on my 4K TV!
Thank you so much for looking into this and fixing it! :smiley:

**Comment by LibretroAdmin** [comment]
Hi @ColinKinloch , merged this one. Can you go to the other PR and rebase that one so I can merge that one too? Thanks.

**Comment by LibretroAdmin** [comment]
Ah just saw you did it. Thanks.

**Pull request merged**
