### PR TITLE
Add verb for menu command: "Create Game-options file"

### PR DESCRIPTION
**Pull request by markwkidd**
This corrects the text that is displayed on the menu for the command to generate a Game-options file. It is an action so there should be a verb.

As things are in the English menu now it's not clear that it should be clicked on rather than navigated right and left as part of the core options. This comes from doing some support and realizing that things aren't intuitive for a new user even though I know exactly what it does.

screenshot 2018-05-20 13 38 18

I noticed there is another string already present for `MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS_CREATE` with the correct wording but that string doesn't seem to be used.

### CODE REVIEW

**Comment by fr500** [comment]
Uh no, the first time it's Create Game-options file
When it exists t's just Game-options file

**Comment by fr500** [comment]
You could change the second string to... Current Game-options file or active but this change is counter productive

**Comment by markwkidd** [comment]
Well shucks, now I know why I didn't remember it being as intuitive as it seems. Both of us must have already had the file in place.

**Comment by markwkidd** [comment]
@fr500 there is still one aspect of this -- it is a command so IMO it should have a verb

If the command when an override already exists isn't to "Create Game-options file" then it is probably to "Save Game-options file" or "Overwrite Game-options file". Does that make more sense?

**Comment by fr500** [comment]
Actually it's not a command, maybe we can turn it into Delete Core-options file?

**Comment by markwkidd** [comment]
"Purge Core-options file"
"Reset Core-options file"
"Wipe Core-options file"

**Comment by markwkidd** [comment]
"Regenerate Core-options file"

**Pull request closed without merging**
