### PR TITLE
Playlist base content directory paths

### PR DESCRIPTION
**Pull request by francescotintori**
## Description
Alternate PR to https://github.com/libretro/RetroArch/pull/10718.
Based on matheman's suggestion in the same PR.

An alternate approach on portable playlist: a new `base_content_directory` field is added to the playlist header, filled with the current value of parameter `'rgui_browser_directory'`.
On playlist load, the `base_content_directory` is compared with `'rgui_browser_directory'`: if different, all entries' paths are automatically "rebased" to the new base content directory. Paths are also adapted to local FS (switching `\` with `/`, and viceversa).

The feature is enabled only if the new `playlist_autofix_paths` parameter is enabled.
As for #10718, if parameter `'rgui_browser_directory'` is empty the whole functionality is disabled.

Code was mostly copied from #10718, and modified for the new logic. 
The core selection logic via file id was also replicated in this PR.

Notes:
- unlike #10718, this approach requires an initial "preparation" of the existing playlists: the new field `base_content_directory` needs to be added in the playlist header. This can be done manually (with a text editor), or by browsing all playlists with retroarch (on playlist load the field is automatically added and saved).
- the preparation step explained in previous point must be run on the same machine where the "original" playlists were created, so that the `base_content_directory` field matches the playlist entries path
- once the playlists are updated, they can be used on other machines, with same or different file systems. If the feature is not enabled on the machine, the `base_content_directory` field will be ignored (but still kept and saved, so it's not lost)

Example:
- original playlist:
```json   {
  "version": "1.4",
  "default_core_path": "",
  "default_core_name": "",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "sort_mode": 0,
  "items": [
    {
      "path": "c:\\roms\\snes\\zelda3.zip",
      "label": "Zelda 3",
      "core_path": "cores\\snes9x2005_libretro.dll",
      "core_name": "Nintendo - SNES / SFC (Snes9x 2005)",
      "crc32": "EAC3358D|crc",
      "db_name": "Nintendo - Super Nintendo Entertainment System.lpl"
    }
  ]
}
```
- in our system, 'rgui_browser_directory' = 'c:\roms'
- on first playlist load, the 'base_content_directory' field is added to the playlist, rom paths are NOT edited, because we do not have the "original" base to make a comparison, so we can only add the base folder:
```json   {
  "version": "1.4",
  "default_core_path": "",
  "default_core_name": "",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "base_content_directory": "c:\\roms",
  "sort_mode": 0,
  "items": [
    {
      "path": "c:\\roms\\snes\\zelda3.zip",
      "label": "Zelda 3",
      "core_path": "cores\\snes9x2005_libretro.dll",
      "core_name": "Nintendo - SNES / SFC (Snes9x 2005)",
      "crc32": "EAC3358D|crc",
      "db_name": "Nintendo - Super Nintendo Entertainment System.lpl"
    }
  ]
}
```
- we load the playlist on another system, where 'rgui_browser_directory' = '//roms'
- both the 'base_content_directory' field, AND the entries paths will be edited:
```json   {
  "version": "1.4",
  "default_core_path": "",
  "default_core_name": "",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "base_content_directory": "//roms",
  "sort_mode": 0,
  "items": [
    {
      "path": "//roms//snes//zelda3.zip",
      "label": "Zelda 3",
      "core_path": "cores\\snes9x2005_libretro.dll",
      "core_name": "Nintendo - SNES / SFC (Snes9x 2005)",
      "crc32": "EAC3358D|crc",
      "db_name": "Nintendo - Super Nintendo Entertainment System.lpl"
    }
  ]
}
```
- Note: core paths are not edited in any way, because core are usually inside retroarch folder, and not in the rom folder. So in this case the new core selection logic using the core "file id" is used. 
- In this case we extract the file id from "snes9x2005_libretro.dll", resulting in "snes9x2005", then we look for a core with the same file id

## Related Pull Requests
This is an alternate approach to https://github.com/libretro/RetroArch/pull/10718.

### CODE REVIEW

**Comment by jdgleaver** [comment]
@francescotintori Ah, now this is very nice! So clean and self-contained :+1: 

I'll let you play around with it, then I'll review it properly next week - but from a quick read through, I can't see any objections. I think we'll be able to get this merged very soon!

Thank you again for your patience in reworking this. We're almost at the finish line :)

**Comment by i30817** [comment]
I'm a bit confused, how does it decide on a `base_content_directory` playlist field automatically if it's done automatically. Does it decide on the least specific path prefix to every ROM? What if a few of the ROMs don't have the same parent drive/mount?

**Comment by twinaphex** [comment]
Just one suggestion if I may in the future - use git pull --rebase - all these intermediary 'merge' commits are quite ugly.

**Comment by mantheman** [comment]
I played with the previous PR and it worked perfectly on an Apple TV (1Ghz pentium M, Ubuntu 14.04 with Retroarch "standalone", 256MB RAM, but with mSata SSD in an IDE-adapter@~82MB/s). I'll say the runtime overhead was negligable. I couldn't detect any obvious slowdown. Will hiccup a split second on loading a really big playlist like MAME2003 or similar, but it's always done that.

Do I get this right...If you share the playlists among all your machines (maybe on a samba share):
Previous PR - Switch between systems: The playlists will be converted on first run, and always have runtime overhead after that (which I think is negligable?). 
Previous PR - Same systems:  Only runtime overhead.

This PR - Switch between systems:  The playlists will be converted on first run, but have no runtime overhead after that.
This PR - Same systems: Converted on first run only if `base_content_directory` are different, but have no runtime overhead after that.

I will leave it up to you devs but it seems this PR might edge out the previous?

Espescially since I don't think it's/will be particularly common to share your playlists among systems on a samba share., so if that runtime overhead does make a difference to very low power systems then this PR might be the best choice.

**Comment by francescotintori** [comment]
@mantheman, yes it's as you say:
- in the first PR, you have a one-time conversion to relative paths, and a in-memory conversion from relative to absolute paths on each playlist load
- in this PR: the playlist will be modified on first run only to add the new `base_content_directory` field. On each playlist load, if it's the same system, or another system where the base content folder did not change, the playlist will be loaded in ram as usual. Else, it will be converted to the new base content directory, and then saved.

The second PR may result in more playlist rewrites if you switch system often (like I do).
The first PR will modify the playlist only if actually changing content, but requires relative->absolute path conversions on each load (only if relative paths are enabled).

To be honest, I still prefer the first PR, because it seems cleaner to me, even if it requires a playlist structure change. 
But I also like this PR, because we are only adding a new field to the playlist header, so code is not modified too heavily.
Either is fine for me :)

Anyway, I think the changes in this PR (or in the first one) will be useful only to a (very) small percentage of users, who want to be able to share playlists between devices (so via shared folder with samba/nfs, or the cloud). This is why I expect this to run on moderately powerful devices, which should have no problems handling some string conversions in memory.

**Comment by francescotintori** [comment]
@i30817: this PR works in a similar way to previous PR.
The playlist entries are converted only if "inside" the base content directory, if not they are left unchanged.
This means that all roms must be inside a "main" folder (the one assigned to parameter 'rgui_browser_directory').
Of course, once inside this folder, roms can be split in different subfolder, for example split by system.

**Comment by i30817** [comment]
That obvious but i was wondering how the base directory is chosen if it's not set yet. Is always the `rgui_browser_directory`; or is it some kind of heuristic from the absolute paths in a 'normal' playlist? 

I think first because second sound a bit fragile no? And if `rgui_browser_directory` is not set either, nothing happens right? 

It just wasn't explained very well in the first post.

**Comment by francescotintori** [comment]
Yes. the base content directory is always copied from `rgui_browser_directory`.
If the path is not set, the whole functionality is disabled. The same goes for the first PR.

**Comment by i30817** [comment]
Ok, be sure to make it obvious in the feature description that it can only be enable with the 'File Browser' directory set.

**Comment by francescotintori** [comment]
I added a more accurate example in the PR description, I hope it's clearer now :)

**Comment by i30817** [comment]
I actually meant the runtime retroarch description ;). And there is subtle distinction that you kind of have to explain the purpose '(transfer playlists but not config files) to the users too and that the file browser dir replacement needs the destination config file set.

**Comment by i30817** [comment]
Does it convert back to absolute paths if you turn off the option too? Just wondering.

**Comment by francescotintori** [comment]
Ok I will refactor the configuration parameter name, plus all related descriptions.
If the configuration parameter is disabled, it doesn't do anything for now. 
Also, path are always absolute in this PR, what we do is just replace the base path (if possible).

**Comment by i30817** [comment]
I see, so it's not needed. I had the idea it reflected on the file, but if it's a memory only transformation even better.

**Comment by francescotintori** [comment]
Actually yes, in this PR if the absolute paths loaded from the playlist need to be "rebased", we recalculate the real paths and then save the playlist.
The alternate PR (#10718) instead loads relative paths from the playlist, and recalculates the absolute path in memory, without modifying the playlist.

I guess I could avoid saving the playlist and keep the rebased absolute paths only in memory, but I fear this would lead to problems:
- first, we would be rebuilding the new absolute paths on each playlist load, defeating the purpose of this alternate PR
- second, any changes to the playlist (add/remove entries, etc) would still force a playlist save

**Comment by i30817** [comment]
I don't disagree, i even deleted the post when i realized what was going on from rereading the 1rst post.

**Comment by francescotintori** [comment]
Ok it seems to work.
I also refactored variables and interface options to be more clear.
I'll wait for travis to complete, if there are no errors I think I'm finally done :)

**Comment by mantheman** [comment]
> To be honest, I still prefer the first PR, because it seems cleaner to me, even if it requires a playlist structure change.
> But I also like this PR, because we are only adding a new field to the playlist header, so code is not modified too heavily.
> Either is fine for me :)

Yes I agree. But legacy compatibility/performance is a big deal. If I remember correctly, I did run Win98SE on a P166mmx@200 w/ 32MB RAM back in the day, and if I remember correctly it ran CPS2/fba and NEOGEO/Neorage games fine, so I would like to think a slight overhead is negligable within any system regardless of age. Of course a little overhead here and there over many PRs is going add up, so you have to be very selective, but I would think this PR warrants it since it very useful. Then again, if one can get away with no overhead at the cost of slightly "less elegant" code, then that's kinda of a good compromise too. But that's only the layman in me thinking.  

> Anyway, I think the changes in this PR (or in the first one) will be useful only to a (very) small percentage of users, who want to be able to share playlists between devices (so via shared folder with samba/nfs, or the cloud). This is why I expect this to run on moderately powerful devices, which should have no problems handling some string conversions in memory.

I don't think it only caters to that small of a percentage. A few of us might have a "main" desktop RA installation, which you use to maintain roms, try out stuff and such. With this PR (or even the previous) it's easy to drag and drop playlists when you want to set up your Pi that is set up for plug'n'play. It's becomes very tedious to replace paths manually after a while. 
For most of us this is actually the main benefit since I agree with you that very few people will share their playlists over Samba. Most people would want a standalone system that they can bring along to friends, or to the hotel room when they travel. 

Maybe the solution could be both where this PR would be a sub-setting of the first PR. Something tells me that won't fly with the main devs :)

**Comment by jdgleaver** [comment]
@francescotintori I am happy with this new implementation :)

It offers all the benefits of the other PR, but has the following benefits:

- The code is minimally invasive

- The *effective* performance overheads for users who enable the feature are very low, since they only apply once per session

- The performance overheads for users who disable the feature are effectively zero (this was not the case for the other PR, since the JSON parser had to do a substantial amount of extra work)

So this is great - excellent work!

Now, there are some problems with the PR as it stands: you have several build errors, a memory leak, a missing label definition, several formatting issues, etc.. I've tried to fix them all in this diff: [path_autofix.patch.zip](https://github.com/libretro/RetroArch/files/4983025/path_autofix.patch.zip)

Please can you apply the diff, and make sure that everything still works as you intended?  :)

After that, could I also request that you do an interactive rebase and squash your commits? (this is a handy guide: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

After *that*, I think we'll be ready to merge :)

**Comment by francescotintori** [comment]
Yes I noticed the many build errors, but I didnt have time to check it.
I did not notice the memory leak though, very bad :\
Thanks @jdgleaver for the patch, I will apply it as soon as possible 👍

**Comment by francescotintori** [comment]
Applied the patch and rebased.
I'll let it finish compiling 👍

**Comment by i30817** [comment]
You have a extra ' in the button label.

> the playlist entries'

**Comment by francescotintori** [comment]
> 
> 
> You have a extra ' in the button label.
> 
> > the playlist entries' paths
> 
> edit: never mind, this is supposed to be a possessive plural noun?
> 
> If so it's 'right' but i frankly never see that rule applied on common usage, but i'll shut up since i'm not a native writer.

Yes, that's exactly as you say, it's a possessive plural noun.
I'm also not a native english speaker, so I checked in google translate just in case :)

**Comment by jdgleaver** [comment]
@francescotintori Okay, I think we're good to go! Thank you for your patience throughout this process :)

@twinaphex If you'd like to give this a final check over, I think we can go ahead with merging

**Comment by francescotintori** [comment]
Thank you too @jdgleaver for all your help :), and to everyone who contributed to this PR!

**Comment by francescotintori** [comment]
Uh oh, I'm testing 1.9.0 but it doesnt' seem to work. :(
Rechecking the code...

**Pull request merged**
