### PR TITLE
(cheevos) disable hardcore when cheats are enabled

### PR DESCRIPTION
**Pull request by Jamiras**
## Description

Fixes cheevos not being disabled when activating RetroArch-managed cheats. 

image

When #7017 was implemented, the new RetroArch-managed cheat functionality _did not_ notify the achievements code that a cheat was active, allowing cheats to be used while earning achievements.

>There are now two different cheat types - Emulator (handled by the emulator, the original type) and the new type - RetroArch - that is handled by RetroArch itself

When an Emu-managed cheat was activated, achievements were disabled entirely.

I've modified the behavior so both methods pause hardcore. This aligns with the messaging in the Pause Hardcode menu option: https://github.com/libretro/RetroArch/blob/f1158b988c7eb26e2da3be11dd7563ff29e3c07a/intl/msg_hash_us.h#L6025

image

## Related Issues

n/a

## Related Pull Requests

n/a

## Reviewers

@meleu

### CODE REVIEW

**Comment by meleu** [comment]
I suggest a shorter message. For example:
`A cheat was activated. Achievements Hardcore Mode disabled for the current session.`

The final part (`Disable cheats and restart to enable hardcore mode`) is implicit.

**Comment by Jamiras** [comment]
It's based on the existing message for loading a save state:
> A save state was loaded. Achievements Hardcore Mode disabled for the current session. Restart to enable hardcore mode.

**Comment by meleu** [comment]
Wow! Even if loading a state turns off hardcore mode, I think it shouldn't be allowed. Pressing the loadstate buttons accidentally and ruin your progress on the game would be very frustrating. :(

Regarding the message, I suggest a shorter message for loading a state too. For example:
`A save state was loaded. Achievements Hardcore Mode disabled for the current session.`

The final part (`Restart to enable hardcore mode.`) is implicit.

**Comment by Jamiras** [comment]
It might be obvious if they Pause Hardcore themselves, but when the code does it for them, they may have no idea. "for the current session" may be a good hint, but that implies reloading the game, not just restarting.

And I'm not really sure how to trigger the first message. Load State is explicitly hidden from the menu in hardcore mode, and I can't get it to trigger via the HotKey either.

I'll remove the text from both. Note that the first has already been translated to several other languages.

**Pull request merged**
