### PR TITLE
CRTSwitchRes improvements and Core Load Chrash Fix

### PR DESCRIPTION
**Pull request by alphanu1**
@twinaphex @bslenul @DocMAX

Changes made to fix crashes reported in issue #11319 https://github.com/libretro/RetroArch/issues/11319

Original PR https://github.com/libretro/RetroArch/pull/11315

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by alphanu1** [comment]
@twinaphex This has now been checked and rechecked. No more crashing.

**Comment by twinaphex** [comment]
We probably should make sure all the memory leaks are fixed first that are related to this PR before merging.

**Comment by alphanu1** [comment]
@twinaphex All X11 memory leaks have been removed.

**Comment by twinaphex** [comment]
This got a thumbs up from @jdgleaver , so it's good to go as far as I'm concerned.

**Pull request merged**
