### PR TITLE
Every .h files && tr.c&.h files edited

### PR DESCRIPTION
**Pull request by fpscan**
So I deleted my old files and forked with latest RetroArch, just changed text files and didn't touched anything else, it worked great on my device.

each .h file  is edited in their own language, Menu_ENUM_LABEL_VALUE_LANG_GREEK & Menu_ENUM_LABEL_VALUE_LANG_TURKISH added into missed .h files, according to the frequency of use Turkish translations changed. some unnecessary blank spaces deleted

I double checked everything with wikipedia, professional translations tools, tureng etc.

### CODE REVIEW

**Comment by fpscan** [comment]
Hi @orbea , @bparker06 and @twinaphex 

I deleted the old fork and started with latest one and this is good one but It failed again I don't know why, I just changed text files nothing else... So im okay with everything.. I added Turkish files in here as well in case we avoid other changes

[intl.zip](https://github.com/libretro/RetroArch/files/3124428/intl.zip)

**Comment by fpscan** [comment]
@bparker06 @orbea @twinaphex 

As twinaphex mentioned old PR, C89 is over my head, so how can we add these changes?

**Comment by fpscan** [comment]
Hi, when this will be live?

**Comment by ofry** [comment]
```
intl/msg_hash_tr.c: In function ‘menu_hash_get_help_tr_enum’:
intl/msg_hash_tr.c:960:30: error: string length ‘524’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
                              "germe filtresini etkiler.");
                              ^
intl/msg_hash_tr.c:1224:30: error: string length ‘568’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
                              "ve bunu varsayılan olarak bırakın.");
                              ^
```

**Comment by fpscan** [comment]
> ```
> intl/msg_hash_tr.c: In function ‘menu_hash_get_help_tr_enum’:
> intl/msg_hash_tr.c:960:30: error: string length ‘524’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
>                               "germe filtresini etkiler.");
>                               ^
> intl/msg_hash_tr.c:1224:30: error: string length ‘568’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
>                               "ve bunu varsayılan olarak bırakın.");
>                               ^
> ```

fixed, looks great so far.

**Comment by twinaphex** [comment]
Hi, seems to be a merge conflict here still.

**Comment by fpscan** [comment]
> Hi, seems to be a merge conflict here still.

Hi Twinaphex, so I deleted my old fr file and download new fr file which merged before, but still failed

**Comment by twinaphex** [comment]
OK @fpscan, is this the one to merge and not the other PR?

**Comment by fpscan** [comment]
> OK @fpscan, is this the one to merge and not the other PR?

yes sir, this the one with latest translations, its good to go.

**Pull request merged**
