### PR TITLE
(GX) Refactor of the Wii USB HID support. Now it's working!

### PR DESCRIPTION
**Pull request by netux79**
In order to have a controller working you need:
1) Have a matching HID autoconfig file in autoconfig/hid for your controller.
2) Create a "connect" driver for the pad in "input/connect" folder (source code of RA).
3) Once you are in RA, change the joystick driver to HID and restart.
4) You may be now able to use you USB HID compatible pad in RA.

I included some "connect" drivers as an example. It also need to include them for compilation.

### CODE REVIEW

**Comment by twinaphex** [comment]
Very cool. I'm going to try this out either later today or tomorrow.

Does hotplugging work now too with this?

**Comment by fr500** [comment]
is it possible to have a generic connect driver for HID devices like on other platforms?

**Comment by netux79** [comment]
Yes, hotplugging works too.

And related to fr500's question.. no, it is not possible as I already mentioned before to twinaplex that the HID support on Wii is very basic, this means that we cannot get the controller information from the USB system like the # of buttons, their names or types... we can just get its IN / OUT interfaces and read the raw data which we need to interpret. So we need to know in advance the controller configuration (what byte holds what information) and from the controllers I tried, the info is different each time... the most we can do to simplify it is one of two options: what was done in nintendont, have a configuration file that holds each controller setup and a separate utility that help to know the byte distribution. This way each user can create its own controller setup that can be read by the application without recompiling... and even with that there are some controllers like the ps3's one that need special commands to enable it, rumble, set the led indicators, etc which will require some hardcoding... And the second is that there may be a set of controllers that share the distribution/setup and maybe can use the same "connect" driver. Another idea is to write a "connect" driver that exposes all bits of its information as if these were ALL buttons (most of the controllers have 8 bytes of data which gives us a total of 64 bits = "64 buttons"). And then use an autoconfig/hid file to map those that have some meaning (most of them would be just junk that we will need to process for the sake of simplicity).

**Comment by fr500** [comment]
oh... ok then.
I guess autoconf profiles are still good to have so people can have customized layouts for certain pads.
The later option seems feasible and it would adjust nicely to what is supported by RetroArch on the Wii.

**Comment by netux79** [comment]
Yes, I may write one some time later... I will try to focus on 2 issues of the Wii version which is the resolution changing and the issues on the native controllers which have been reported lately and remove the custom code that has a matching functionality in the libogc... this will save some space as it can be considered duplicated.

@twinaphex: You disable the resolution saving, right? Could you please indicate what you did to disabled this so you can save me some research time. Hope you still recall this. Thanks.

**Comment by twinaphex** [comment]
@netux79 - I think it's as simple as basically adding an entry to config_save_file and config_load_file inside configuration.c.

Just to clarify: these NES USB/SNES USB connect drivers you added, these do not require an autoconfig file in order to work on the Wii? Also, were you able to test a DS3 or DS4 pad with this or are you not in possession of those pads?

**Comment by netux79** [comment]
OK I will check those entries, I was planning use an index (which I think is already there as you mention) instead of the direct resolution values.

Yes, all 3 (NES, SNES and Wii GC Adapter) I added require the autoconfig file. I have them and I can add them to the repo if you want. And yes, I tested a PS3 controller I have, I don't own a PS4 so I couldn't try that one.. however it may need some small changes just s the PS3 one needed in the connect driver.

The easier way to test it would be to use the PS3 controller as the other I think are not very common (maybe the Wii GC Adapter is) which I'm pretty sure is working.

**Comment by twinaphex** [comment]
OK, that would be great if you could send us a pull request to our retroarch-joypad-autoconfig repo for the autoconfig files.

**Pull request merged**
