### PR TITLE
[CRT] Add KMS modeswitch

### PR DESCRIPTION
**Pull request by substring**
## Description
This PR adds KMS modeswitching for CRT. Also:

- updated switchres base code
- enable the CRT switchres menu on KMS (but most of options don't work yet)
- As this relies on /etc/switchres.ini and I think about Lakka, also add the ra_config_path to switchres.ini search path
- Show a decimal refresh rate when modeswitching instead of an integer (to show off, mostly)

The 3 first commits are just to update the `deps/switchres` subtree as a subtree can't be updated if there has been any change in it

This has been tested on PC and custom build of lakka on Pi4 (full Lakka support need additional stuff beyond RA to have 15kHz from boot to shutdown, but at least RA behaved well)

## Related Issues

Not tested, but probably:

- https://github.com/libretro/RetroArch/issues/8663
- https://github.com/libretro/RetroArch/issues/13485

## Related Pull Requests

None I know of

## Reviewers

@hunterk @LarsenDX

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
This is an exciting addition! Thanks so much for working on it :)

@alphanu1 do you have any thoughts?

**Comment by alphanu1** [comment]
@hizzlekizzle I’ve been working with calamity and substring on the true switches implementation. I have tested this as well as many other user and it works really well. Kudos to @substring for the great work.

**Comment by miguedevel** [comment]
Since this commit, RetroArch crashes on Windows when enabling CRT Switchres with a segmentation fault.
Here's the log:```

[INFO] RetroArch 1.15.0 (Git f24893bcb1)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: May 27 2023
[INFO] Version: 1.15.0
[INFO] Git: f24893bcb1
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 640x480.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Requesting 1 maximum frame latency, using 1.
[INFO] [D3D11]: Found GPU at index 0: "AMD Radeon R5 200 Series (CRT Emudriver)".
[INFO] [D3D11]: Found GPU at index 1: "Intel(R) HD Graphics 4600".
[INFO] [D3D11]: Found GPU at index 2: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\miguel\src\retroarch\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\miguel\src\retroarch\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\miguel\src\retroarch\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\miguel\src\retroarch\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\msys64\home\miguel\src\retroarch\content_favorites.lpl".
[INFO] [CRT]: Requested Resolution: 320x240@60.000000 orientation: normal
[INFO] [CRT] Video context is: (null)
```

I can't produce a crash log because if I build with DEBUG=1 then  RetroArch crashes on launch with any video_driver but SDL2 and attempting to enable CRT Switchres with SDL2 just hangs, not crash RetroArch.

**Comment by miguedevel** [comment]
Alright this is a simple not checking for NULL bug.
On gfx/video_crt_switch.c line 147 there's a strncmp without first veryfing if the argument is NULL, which it seems to be on Windows.

**Comment by hizzlekizzle** [comment]
eyy, awesome. I'm glad you were able to track it down. Thanks for the PR!

**Pull request merged**
