### PR TITLE
(D3D11/12) Make waitable swapchains optional

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

- New option for waitable swapchains, which disables `Max Frame Latency`, acting like GPU Hard Sync
   - Disabled by default for `__WINRT__`
- Maximum `Max Frame Latency` increased to 4

## Related Issues

#14069

## Related Pull Requests

#14073

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
@TheRhysWyrill Can you give us your findings?

**Comment by TheRhysWyrill** [comment]
> @TheRhysWyrill Can you give us your findings?

Just tested with Waitable Swapchains both Disabled and Enabled and the performance difference between the 2 is negligible at best, even with a Max Frame Latency setting of 1 when Enabled no longer causes the FPS to be severely impacted.

**Comment by LibretroAdmin** [comment]
Sounds good then. So with this merged @TheRhysWyrill everything should be OK on the Xbox end?

**Comment by TheRhysWyrill** [comment]
Yeah, looks to be, thanks @sonninnos for the quick fix and sorry for being such a royal pain about this 😅

**Comment by LibretroAdmin** [comment]
We very much appreciate it @TheRhysWyrill !

**Pull request merged**
