### PR TITLE
change `q` for quit and `esc` for menu

### PR DESCRIPTION
**Pull request by omenking**

### CODE REVIEW

**Comment by twinaphex** [comment]
It would be counterproductive to change that default bind now this late in the game. I'd suggest to people who want to see the two mapped the other way to just change that for themselves instead.

**Comment by RobLoach** [comment]
I do enjoy this change, and do it manually in the settings myself. If people are upgrading existing setups, wouldn't their Escape/F1 setup exist through the upgrade?

Perhaps this would be for a 1.7 or 2.0?

**Comment by hizzlekizzle** [comment]
I'm not a fan of changing default binds this late in the game. In this case, 'q' is already the default bind for retropad L, IIRC.

I think if we were going to do such a thing, it would be more productive to just change everything to MAME's default mappings to work with all of the X-Arcade/I-PAC-type keyboard encoders. I don't like the idea of changing them to suit preferences rather than any concrete rationale.

**Comment by retro-wertz** [comment]
a good mod would be to allow a delay when pressing quit hotkey, something
like holding the key for 3 secs instead of quitting  immediately.

**Pull request closed without merging**
