### PR TITLE
macOS controller duplication bug

### PR DESCRIPTION
**Pull request by ComradeEcho**
## Description

Decided it would be for the best to remake this from master because I mangled it through learning how to use github.
Sorry if you get pinged again. This is a copy/paste of the previous PR I made.

Hey y'all. 

Just to preface, I have ~zero experience with github, and this is literally my first time ever touching C or anything close to this low-level. Please scrutinize the heck out of this, because I don't know what I'm doing. Especially pointer/memory/free()/deinit stuff.

This PR aims to take care of a couple of things having to do with the macOS HID Driver.

1) The `IOHIDDeviceRegisterRemovalCallback` simply was not working as I believe it should. I don't know if it was implimented improperly, or if there's a bug in macOS related to it. It was being set, but it wouldn't trigger reliably. I replaced `IOHIDDeviceRegisterRemovalCallback` with `IOHIDManagerRegisterDeviceMatchingCallback` which seemed to have perfect detection of device removal on my system.

2) Upon fixing the first issue, I discovered that devices matched by the autoconfigurator still were not disconnecting properly. This was caused an `struct iohidmanager_hid_adaptor` being improperly cast as a `struct pad_connection`, and having its data overwritten/corrupted.
I solved this issue by adding a `void* connection` to `joypad_connection` and assigning the offending `struct pad_connection` there instead of it going in `void* data`, thus removing the data collision.

3) I removed all references to `uniqueId` because I *assumed* it accomplished nothing. I later realized what it was accomplishing, but decided to try to implement the same goal with `kIOHIDLocationIDKey` instead, because `kIOHIDUniqueIDKey` is unsupported by powerPC
What it was accomplishing was: controllers are detected both when the application is launched, and by the controller connection callback. uniqueId was being used to make sure the controllers are not duplicated by getting added by both of those. 

## Notes

I have done testing solely on M1 macOS 11.

I have done testing with these controllers: 
* xbox series s (bluetooth)
* ps3 (bluetooth)
* ps4 (wired and bluetooth)

I have access to a few more untested controllers including:
* Mayflash
* 360
* joyconns
* switch pro
* switch-gamecube
* n64 usb adapter?
* maybe many more!

I have *absolutely* no idea if this affects windows/linux/android. It seems like a very Apple-heavy driver, and I don't know if the HID input driver is even functional on other platforms.

## Related Issues

For sure:
https://github.com/libretro/RetroArch/issues/12561
https://github.com/libretro/RetroArch/issues/11294
https://github.com/libretro/RetroArch/issues/10546

Possibly:
https://github.com/libretro/RetroArch/issues/3414
https://github.com/libretro/RetroArch/issues/2808
https://github.com/libretro/RetroArch/issues/4215
https://github.com/libretro/RetroArch/issues/3415
https://github.com/libretro/RetroArch/issues/6731
https://github.com/libretro/RetroArch/issues/4793

## Reviewers

@gblues @jdgleaver @hunterk @markwkidd @twinaphex

### CODE REVIEW

**Comment by twinaphex** [comment]
Tested this on ARM Macbook 2020 (11.4), an Intel Macbook 2013 (10.14), and a PowerPC Powerbook G4 (10.5). 

I tested both a DualShock 4 (which has a HID driver written for it) and a Logitech Rumblepad 2 (no HID driver), and both worked fine.

There are no longer issues like 'attach a pad, it gets attached to both port 1 and 2', and some other issues seem to have been fixed too.

Great job all-around. I think we have tested this pretty extensively but if anyone reports any issues as a result of merging this, we can always revisit this.

**Review by gblues — COMMENTED** [review]
I am worried that the changes to `iohidmanager_hid_manager_set_device_matching` are going to break Mac OSX PPC (because the old code on lines 1081-1102 are gated with an ifdef to exclude it) but I don't exactly have a G5 workstation laying around to test it.

other platforms might still have the pad sorting issue, but we can tackle those separately as needed, and will need the joypad changes here merged first regardless.

**Comment by ComradeEcho** [comment]
Thanks for the input, and thanks for looking it over :)

There shouldn't be any issues with PPC

There were many PPC ifdef statements added to gate off [this](https://github.com/libretro/RetroArch/commit/9008684651f2df0cc428bbb83c160ba03d7c0d49#diff-cbde5c0fa0d7e8da145db4ca5b01bcca5080d6e328464b8aeeb5e66623114bd5) entire commit due to a PPC incompatibility with `kIOHIDUniqueIDKey`.

The [feature](https://github.com/libretro/RetroArch/commit/82e2cc7c73a1f8b0693cdfec59e04665e99375c4#diff-cbde5c0fa0d7e8da145db4ca5b01bcca5080d6e328464b8aeeb5e66623114bd5) appeared to adding all the controllers on start in an attempt to deterministically get them all in the same order every time the app is launched and would then use `kIOHIDUniqueIDKey` to try to prevent the controllers from getting added a *second* time by the `DeviceMatchingCallback`...

I removed all of that,  so now the controllers are *only* added by the `DeviceMatchingCallback`. They might not end up in the *same port* every time the app is launched... but the code is cleaner, and everything *appears* to be working and there should be no PPC-incompatible code left that needs gated off.

I suspect this feature may be able to be re-implimented with `kIOHIDLocationIDKey` rather than `kIOHIDUniqueIDKey `, but I think we can cross that bridge when someone complains about it.

**Comment by briankendall** [comment]
> I removed all of that, so now the controllers are only added by the DeviceMatchingCallback. They might not end up in the same port every time the app is launched... but the code is cleaner, and everything appears to be working and there should be no PPC-incompatible code left that needs gated off.

I'm afraid to say this PR is responsible for introducing #13294. It's important that controllers get deterministically added in the same order, otherwise binding a port to a specific controller doesn't work at all.

I think this points to a larger issue with the way RetroArch assigns a controller to a port, in that it does it in enumeration or connection order rather than by identity.

**Pull request merged**
