### PR TITLE
Only attempt to call dir_check_defaults once per runtime session

### PR DESCRIPTION
**Pull request by twinaphex**
when calling the frontend environment get callback - we want to
look at the 'default' directories, and then if they don't yet exist,
auto-create them so we can store files in them.

@jdgleaver If you could review this, I'd be grateful. Similarly, if you know of any ways to improve upon this, that is very welcome as well.

The aim here is:
* We assume g_defaults.dirs is only changed once for the entire duration of the runtime, so it doesn't make sense for us to continue checking these default dirs and attempting to recreate them for every time we load content. Therefore, we save on a loop iteration, and we save on potential file I/O calls (even if it's only an fstat-esque call). The assumption is that by changing it like this, that we call upon this loop less often than before. Let me know if that is indeed the case. If not, we might have to rethink things a bit.
* Another plus is that we no longer need to have all these ifdefs. Each platform gets its own specific implementation inside the frontend driver.
* They are put behind #ifndef IS_SALAMANDER defines for now just to be safe. Let me know if that has unintentional consequences.

### CODE REVIEW

**Comment by jdgleaver** [comment]
Yes, this makes perfect sense :)

> We assume g_defaults.dirs is only changed once for the entire duration of the runtime, so it doesn't make sense for us to continue checking these default dirs and attempting to recreate them for every time we load content.

This assumption is true. It therefore is indeed a waste of effort to check these directories on every load content, and the directories should instead be checked at the point where the paths are set (i.e. inside `get_environment_settings()`, exactly as you have done)

> They are put behind #ifndef IS_SALAMANDER defines for now just to be safe. Let me know if that has unintentional consequences.

This is a problem. The salamander builds read/write a file in the config directory - if this directory doesn't exist, then there will be trouble...

So either the `#ifndef IS_SALAMANDER` defines should be removed, or `salamander_init()` should be modified to create the base path of `g_defaults.path_config` if it does not already exist

(Note: having checked this, it would seem to be a pre-existing bug, unrelated to the PR...)

On the one hand, fewer `#ifdefs` are always nice - but on the other, I think I'd recommend modifying `salamander_init()` (since this will have the smaller performance impact)

----

One final note: There is an awful lot of duplicated code in the frontend drivers now. I think I'd put the common parts of this into a new `void dir_create_defaults(void);` function defined in `paths.h` - i.e.:

```c
void dir_create_defaults(void)
{
   size_t i;

   for (i = 0; i < DEFAULT_DIR_LAST; i++)
   {
      char       new_path[PATH_MAX_LENGTH];
      const char *dir_path = g_defaults.dirs[i];

      if (string_is_empty(dir_path))
         continue;

      new_path[0] = '\0';
      fill_pathname_expand_special(new_path,
            dir_path, sizeof(new_path));

      if (!path_is_directory(new_path))
         path_mkdir(new_path);
   }
}
```

...then the frontend functions will look like:

```c
static void unix_dir_check_defaults(void)
{
   /* early return for people with a custom folder setup
      so it doesn't create unnecessary directories
    */
#if defined(ANDROID)
   strcpy_literal(path, "host0:app/custom.ini");
#else
   strcpy_literal(path, "custom.ini");
#endif
   if (path_is_valid(path))
      return;

   dir_create_defaults();
}
```

**Comment by twinaphex** [comment]
OK, can you push some of these improvements to the PR ? Both Salamander and the code de-duplication.

**Comment by jdgleaver** [comment]
Okay, I'm working on it now. You'll probably have to give me some access permissions, though, or I won't be able to push to your branch... (otherwise I could just post a diff - maybe that would be simpler...)

**Comment by jdgleaver** [comment]
Yeah, I can't push to your branch - so here's a diff: [dir_check_defaults.zip](https://github.com/libretro/RetroArch/files/5567676/dir_check_defaults.zip)

Make sure you check it over yourself before merging :)

**Comment by twinaphex** [comment]
Seems to work fine for me.

**Pull request merged**
