### PR TITLE
New example_translation core options sample

### PR DESCRIPTION
**Pull request by DisasterMo**
## The Problem

The current state of core options is very translation unfriendly - the only way to add translations is by copying the entire `option_defs_us` array from libretro_core_options.h to libretro_core_options_intl.h and add each translation into place manually.

There exists no easy way to upload the texts to crowdin and updating the translations is just a pain.

## Suggested Solution

In this PR I attempt to rectify this, even though a little naively: by converting the handling of core options into a form similar to how it is done in RetroArch - by utilising hash keys to fetch the actual string via the `msg_hash_to_str()` function from a msg_hash file corresponding to the current user language. Scripts for converting such msg_hash files into jsons for uploading to crowdin already exist and would need to be modified only slightly for compatibility with core options.

For this I created a Python script ('extract_from_options.py') which extracts the original texts from `option_defs_us`, creates hash keys for each and even reconstructs `option_defs_us` to utilise the `msg_hash_to_str()` function. As a bonus, it converts v1 structs to v2! See 'extract_from_options_readme.txt' for a more detailed description - keep in mind, though, that those instructions might yet need some touch-ups.

## Conclusion

As an example, I converted the core options for gambatte-libretreo (libretro/gambatte-libretro#196) and confirmed that it works using some nonsense I wrote into 'intl/msg_hash_mgba_de.h'. I don't know how elegant or robust - or even complete - my implementation is, so I am humbly requesting a review.

## Reviewers
@jdgleaver, since they just finished up the v2 update (thank you for your hard work!).

### CODE REVIEW

**Comment by jdgleaver** [comment]
@DisasterMo Firstly, thank you for shining a spotlight on this issue. It is a highly significant problem, and one that has been neglected since forever. I am also very impressed by the amount of work you have done here.

However, you asked for a review, and you're going to get one :)

I'm going to say some things that you will hate, but this is in no way a criticism of your work (which is excellent - its only failing is that it's derived from less than ideal source material...) and I hope that you will be open to change (because I don't think anyone else - or anyone with your python skills - will be willing to tackle such a tiresome task). So here goes:

The `msg_hash` system is, quite frankly, horrible. It is a constant aggravation, a huge maintenance burden, and it's one of the reasons that there is a high barrier of entry for anyone wanting to work on RetroArch's menu system. It's so deeply entrenched in RetroArch that we can't really do anything about it, but it's acceptable there because:

a) RetroArch is conservative - options rarely change (much), they are usually only added
b) Very few people work on the menu, and they are all accustomed to the shenanigans involved...

Cores represent a very different environment. All kinds of people work on cores all the time - people with all levels of experience and patience - and to keep and attract core developers the workflow must be as simple as possible (or as simple as is practical). The key thing in this context is that core devs must be 100% free to add, remove and modify core options with zero impediment. The current `libretro_core_options.h` setup is designed with this in mind. You have a single array of human-readable text and a single function you can call in `libretro.c`- it literally couldn't be easier. Translations, as you point out, are problematic - but the core dev doesn't have to worry about that: they can change the US English array however they like, and everything just works (and then translators pick up the pieces later...).

Now instead of this trivial setup, look at the implementation you are proposing. Everything you have done here is technically excellent - but as a core dev I wouldn't stand for it. There is simply too much hassle involved. Any of those options can change at any time - and if I had to deal with those message hashes, and the tangle in `libretro.c`, I just wouldn't bother to do anything. If even I feel that way, then I guarantee that enforcing this model would discourage and drive away core devs - which is the exact opposite of what we want to do.

I understand that facilitating core translations will impose an extra burden - but this burden cannot be bourne by core devs - or in fact by translators. All the unpleasantness must be dealt with by the one who enforces the model.

Thus as a basic premise, I would insist that `libretro_core_options.h` remains in its current form - a single human-readable array, with a single function to call in the core code. Devs can play around with the elements of this array however they please, and all is easy and nice. Which means everything else is hard...

The idea I have is that `libretro_core_options.h` is the definitive source, and all other translation-related files are generated dynamically each time `libretro_core_options.h` changes. The actual scripting involved here is quite laborious/complex (although you have a lot of it done already), but I would suggest the following approach:

- Parse the array in `libretro_core_options.h` to create a reference list of US English strings:
```
MYCORE_MYOPTION_LABEL_US "my option label"
MYCORE_MYOPTION_INFO_US "my option info"
MYCORE_MYOPTION_VALUE_0_US "my option value 0"
etc.
```
- While doing this, compare it against a cache - so changes/deletions are noted, and any existing translations for those strings can be removed/invalidated.
- This reference list will not be used anywhere in the code - it will just be sent to crowdin as a list of source strings
- While parsing the source array, generate a `libretro_core_options_intl.h` file laid out exactly like the hand-written ones - but set each string value via a define. A crude example:
```c
   #define MYCORE_MYOPTION_LABEL_FR   "my option label (french)"
   #define MYCORE_MYOPTION_INFO_FR    "my option info (french)"
   #define MYCORE_MYOPTION_VALUE_0_FR "my option value 0 (french)"
   #define MYCORE_MYOPTION_VALUE_1_FR "my option value 1 (french)"
   #define MYCORE_MYOPTION_VALUE_2_FR "my option value 2 (french)"
   #define MYCORE_MYOPTION_VALUE_3_FR "my option value 3 (french)"

   {
      "mycore_myoption",
      MYCORE_MYOPTION_LABEL_FR,
      NULL,
      MYCORE_MYOPTION_INFO_FR ,
      NULL,
      NULL,
      {
         { "auto",   MYCORE_MYOPTION_VALUE_0_FR },
         { "ntsc-j", MYCORE_MYOPTION_VALUE_1_FR },
         { "ntsc-u", MYCORE_MYOPTION_VALUE_2_FR },
         { "pal",    MYCORE_MYOPTION_VALUE_3_FR },
         { NULL, NULL },
      },
      NULL
   },
```
- These 'defines' will be set via crowdin. I guess defines for each language can be stored in a cache file which gets updated directly from crowdin, and the generation script just pulls in the ones it needs (any missing strings should be defined as `NULL`)

The process here would be:

- Core dev changes `libretro_core_options.h`
- After PR is merged, automated script regenerates `libretro_core_options_intl.h`. Where it can, it uses existing 'defined' international strings - any changed or missing ones are defined as `NULL`
- This script also generates the cache of define lists for each language, which can then be uploaded to crowdin
- When translations are updated on crowdin, the define lists for each language get modified, and the automated script is run again to regenerate `libretro_core_options_intl.h`

I think this would achieve your goal of making everything easily translatable, without inhibiting or changing in any way the workflow of core developers. Moreover - using defines like this greatly reduces code complexity and performance overheads vs. a `msg_hash` implementation. The complexity and performance overheads shift entirely to the scripting, which developers and translators don't have to worry about at all :)

So does this all make sense? And would you be interested in looking at adapting your work to follow this kind of model?

**Comment by DisasterMo** [comment]
Thank you very much for your extensive evaluation! Since it _is_ quite a lot, I'll address the relevant points in order:

> Firstly, thank you for shining a spotlight on this issue.

Thank _you_ for acknowledging it.


> I'm going to say some things that you will hate [...]

If you want to do me a favour: In the future, please leave out unnecessary paragraphs like this. I _want_ to make contributions that make sense. So unless you talk complete rot or are otherwise being toxic, all input is definitely welcome and appreciated.


> The idea I have is that `libretro_core_options.h` is the definitive source, and all other translation-related files are generated dynamically each time `libretro_core_options.h` changes.

Sure, I am all for that. This will, however, still require quite a bit of work for some cores, since it makes fill-ins on run time/via macro unviable. I cannot fill those in using a python script, and even if we were to, say, create a debug function in the libretro code to print out the filled array on run time - there are sometimes alternative info/value texts, which would not be included. So, the first part of my instructions, regarding the manual fill-in of those parts, will stay largely the same.


> Parse the array in `libretro_core_options.h` to create a reference list of US English strings:

Easy.


> While doing this, compare it against a cache - so changes/deletions are noted, and any existing translations for those strings can be removed/invalidated.

Deletions I get - but changes? Is that really necessary? Most changes merely fix spelling or formulation mistakes, right? Besides, any such changes & deletions would be eventually handled by crowdin, anyway.


> While parsing the source array, generate a `libretro_core_options_intl.h` file laid out exactly like the hand-written ones - but set each string value via a define. A crude example:
>  [...]
> These 'defines' will be set via crowdin. I guess defines for each language can be stored in a cache file which gets updated directly from crowdin, and the generation script just pulls in the ones it needs (any missing strings should be defined as `NULL`)

Yeah, maybe I could have thought of that one, had I not rushed as much (the `v1_to_v2_converter.py` sure is a nice add-on to your update, isn't it?). Given the crowdin translation jsons, this should be doable. But I'll order the languages alphabetically (by abbreviation), if you don't mind.


>     * Core dev changes `libretro_core_options.h`

As mentioned above, we'd still need rules for that: primarily no macros or run time fill-ins, unless no translation of the inserts is needed/wanted.


Well, thank you once again for your fantastic input. While I wait for a response for some of the raised concerns (especially the "on delete/change" one) I'll just start on reworking the scripts.

PS: Maybe we could still somehow promote the `v1_to_v2_converter.py`? It only requires the `core_option_regex.py` and makes converting core-options a (comparative) breeze (although one still has to create categories and insert them into the options manually, of course). It would just be such a shame, if core devs were to do all the work manually, while we already have a script for that.

**Comment by jdgleaver** [comment]
My allotted RetroArch time for the week is up, but let me quickly address this one before I have to go:

> Deletions I get - but changes? Is that really necessary? Most changes merely fix spelling or formulation mistakes, right? Besides, any such changes & deletions would be handled by crowdin, anyway.

Yes, core options can and will change in unexpected fashion. We are well-behaved on the frontend side of things (taking care not to break crowdin stuff), but cores are the wild west. Core devs can basically do *anything*.

I'll give a proper response to the rest of your points on Monday!

> PS: Maybe we could still somehow promote the v1_to_v2_converter.py?

Yeah, that could be very useful, and could even go into a separate PR for faster merging.

@twinaphex It might well be worth your while to take a look at this script for the cores you want to update before the next stable release.

**Comment by DisasterMo** [comment]
Okay, the scripts are ready for testing. Though, that will be a tad difficult, without any translations from crowdin.

Oh, and one thing I forgot to mention: the scripts sync with the current RetroArch crowdin project.
Another possibility would be creating a project for the cores/each core (though the latter seems excessive).

**Comment by jdgleaver** [comment]
@DisasterMo Firstly, apologies for the delay in replying.

What you have done here is quite breathtaking. I am incredibly impressed, and I think this will certainly become the de-facto standard moving forwards.

As you say, the main thing now is testing. Personally, I'm not sure how crowdin works - so we'll need to get the folk who handle that to set something up for a test core. There are some internal project issues we're dealing with right now, and a new stable just around the corner, so this might take a little while - but hopefully something can be done within a week or so.

But honestly, this looks like a done deal. If this works as expected, then you have solved a very significant longstanding issue. Thank you so much.

**Comment by DisasterMo** [comment]
@IlDucci and I did some testing already and I have a re-designed version on its way. Ultimately the idea is to use it for the cores in a similar way to how it's done for RA right now: integrate the script into a workflow activated on push to master.

Since @guoyunhe 's original approach (the crowdin_sync.py script, which I tried to re-use here) will become unusable by the end of the year due to Crowdin endig API v1 support, I wrote my own functions based on guos work using the Crowdin Python client. The problem with this is, I don't know whether/how an external module like that can/should be handled in a workflow (except for outright donwloading & including it with the scripts). Never created a workflow action before. Not even sure yet how to do it.

Well, we'll see, I guess.

**Comment by jdgleaver** [comment]
@DisasterMo I just spoke to twinaphex and the plan is to try and get a full test setup organised next week, after the next stable release - so hopefully we can move this forwards quite quickly after that.

**Comment by DisasterMo** [comment]
Okay, major update:

- Switched to using Crowdin CLI, since the Python client proved to be unreliable
- Made the script more 'robust'; it can create translations even for some (slightly) non-libretro-conformant cores (e.g. boom3)
- Tested it with personal Crowdin project - synchronization works perfectly
- Bug fixes. Lot's of 'em.

**Comment by twinaphex** [comment]
Hi there @guoyunhe and @IlDucci , can you as Crowdin maintainers help out here? We will require your input here as well too since there's a bunch of Crowdin stuff going on here as well.

**Comment by IlDucci** [comment]
> Hi there @guoyunhe and @IlDucci , can you as Crowdin maintainers help out here? We will require your input here as well too since there's a bunch of Crowdin stuff going on here as well.

@twinaphex I don't know much of Crowdin's API controls, but I'll assist at doing any changes needed inside the Crowdin project's control panel whenever possible (as long as we've tested them with @DisasterMo 's test server just so we don't break anything).

**Comment by DisasterMo** [comment]
I. Finally. Did it!

New approach: 

1. put `.github` folder into root of core repo, all the python scripts into the same folder with `libretro_core_options.h` & `libretro_core_options_intl.h`
2. into the 2 .yml files in `.github/workflows/` insert the base path of `libretro_core_options.h` (i.e. the folder path where the scripts were copied to) and the path to `libretro_core_options.h` specifically where indicated by <>-surrounded placeholders
3. `libretro_core_options.h` will possibly need a make over (scripts are not compatible with macros/on run time fill-ins)
4. run 'core_opt_translation.py' once to 'set up' the repo, commit & push changes
5. once the above is merged into master, set up Crowdin integration (that's another process of it own, I'll write up instructions if/when necessary)
6. thanks to step 4, already present translations will be uploaded to Crowdin on step 5
7. profit!!

What will basically happen from then on:

1. changes to `libretro_core_options.h` will result in `crowdin_prep.yml` creating/updating the repo's source text .json (1st action)
2. Crowdin will periodically fetch that source file & create a PR with any new translations
3. once that PR is merged, it changes files within the `intl` folder, which triggers 'crowdin_intl.yml' (2nd action) to reconstruct `libretro_core_options_intl.h` on the basis of the new translation files
4. new translations acquired! (== profit! again!)

**Comment by DisasterMo** [comment]
I also updated the gambatte-libretreo PR (libretro/gambatte-libretro#196) to reflect the current state of the project.

**Comment by jdgleaver** [comment]
@DisasterMo This is a legitimate work of genius. I am so impressed.

Hopefully we can start setting this up in live repos next week :)

**Comment by DisasterMo** [comment]
@jdgleaver Thank you very much! I am trying my best.
Though I already have a couple tweaks in mind. The way this is all set up right now makes Crowdin integration a hassle. I'll try and make all the scripts work from the root of the repo and place the `intl` folder there as well. This way, only the GitHub actions/workflows (I am still unsure about the terminology) would need to be adjusted for each core, the Crowdin integration would become pretty much the same for all.

**Comment by jdgleaver** [comment]
@DisasterMo What is the current status of this PR + your gambatte one? It looks like everything is ready to merge, but I'm not sure if you've finished making commits yet... :)

I guess the only 'major' thing left on the infrastructure side is setting up the Crowdin integration...? I think this PR can be merged quite safely in advance, but do we need to set up Crowdin before merging the gambatte one?

**Comment by DisasterMo** [comment]
@jdgleaver I was just waiting for the go signal! Squashed commits & rebased for clean merge.

According to my last test (my Crowdin trial expired, so I couldn't do more) everything works pretty darn well! (But is it bug free? Only time will tell...). So, yes, both this and the gambatte PR can be merged - we can deal with the Crowdin integration later; while both processes work together, they are actually independent.

**Comment by jdgleaver** [comment]
@DisasterMo Excellent! I shall ask twinaphex to merge these right away :)

Again - many thanks for this brilliant work!

**Comment by DisasterMo** [comment]
What do you think, @guoyunhe?
All we need now, is to connect a GitHub account (probably twinaphex's) to Crowdin & we can start integrating repos for automatic synchronisation. I wrote up some rudimentary instructions for that (`translation scripts/instructions.txt`) & I believe once the account is linked to the project, the Crowdin managers can do the rest. I can help, too, but I would need manager rights then.

**Pull request merged**
