### PR TITLE
Better scrolling sound implementation, add new 'notice back' sound, stop menu sounds before playing them

### PR DESCRIPTION
**Pull request by Skirlez**
## Description

1. This PR improves on the implementation of #14770 by making it more general, to the point where RGUI needs no additional coding to have accurate scrolling sounds, however the other menu drivers still have some code inside of them to handle their unique features (Ozone sidebar, XMB categories, switching between MaterialUI menus..)
In addition this PR fixes scrolling sounds continuously playing if holding on a direction at the ends of a list of option with wraparound disabled.

2. It adds the NOTICE_BACK sound which was unimplemented despite the regular NOTICE being implemented for some reason. It plays if you have "Enable 'Notice' Sound" turned on.
(I would've also changed the option name to 'Notice' **sounds** instead of sound, since it plays two sounds when toggled now, but it's already been translated to a lot of languages)

3. It makes `audio_driver_mixer_play_menu_sound()` stop the sound given as a parameter before playing it, so that if you exit out of a long chain of options for example, the cancel sound plays accurately every time.

It would have also made the 'OK' sound play after toggling a boolean option but the pull request would be getting too general.
If you think it's a good idea I could just add it to this PR or make a separate one

Video:

https://user-images.githubusercontent.com/17904548/211144961-08f7be6f-ff38-4c5d-8390-bf4120298f92.mp4

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi, nice PR.

however, can you fix these C89 build errors?

https://github.com/libretro/RetroArch/actions/runs/3861662117/jobs/6582769325

**Comment by Skirlez** [comment]
> Hi, nice PR.
> 
> however, can you fix these C89 build errors? That prevents it from being merged right now. Always declare variables either at the start of a code block or at the beginning of a function.
> 
> https://github.com/libretro/RetroArch/actions/runs/3861662117/jobs/6582769325

Oops, fixing right now

**Comment by LibretroAdmin** [comment]
It's not just xmb.c - see accompanied log.

https://github.com/libretro/RetroArch/actions/runs/3861705391/jobs/6582833475

You can check for this during compilation BTW by specifying 'make BUILD_C89=1'

**Comment by LibretroAdmin** [comment]
OK, looks promising now. If all PR checks succeed I will merge it.

**Comment by Skirlez** [comment]
Thanks!
I guess I'll make a separate PR for the toggle option sound later.

**Pull request merged**
