### PR TITLE
Option to open the file browser in the last used directory

### PR DESCRIPTION
**Pull request by ImJezze**
This pull request implements a similar functionality as #11222 for the start directory of the file browser. 

There is a new toggle option under "Load Content" > "File Browser" named "Open last used start directory". When set to "On" the last used directory and index of the selected file is temporary cached and used when the "Start Directory" is opened again. The temporary cache will be reset after a restart.

The currently supported languages are English and German.

### CODE REVIEW

**Comment by ImJezze** [comment]
Please do not accept the pull request yet. There is still an issue to fix.

**Comment by ImJezze** [comment]
The issues should be fixed now.

The only exception is the new FIXME comment, where I added a German Translation for a sublabel, whose identifier was already tagged before.

**Comment by jdgleaver** [comment]
Thank you for this - it's a really nice feature! Much appreciated :)

I'm short on time today, but I'll review the PR properly tomorrow. I can see a couple of trivial issues, and I need to verify whether the start index needs additional error checking, but I don't think there will be any problems here.

**Comment by jdgleaver** [comment]
Okay, we have some small issues and some big ones... :)

### Trivial issues:

- Translation files cannot be edited via regular PRs - all translation stuff has to go via Crowdin

- All comments have to be C-style, or the C89 build will fail

- All variables must be declared at the beginning of the scope, or the C89 build will fail

- The entry label needs to be in title case

- The `path_is_directory()` checks in `generic_action_ok_displaylist_push()` are unnecessary

- Various style nits

None of this is very important - this diff file can be applied to your PR, and it will fix these problems: [cleanups.zip](https://github.com/libretro/RetroArch/files/5546300/cleanups.zip) (I also took the liberty of editing the label/sublabel text - I hope that's okay)

### Serious issues:

- Calling `menu_navigation_set_selection(entry_idx)` at the end of `generic_action_ok_displaylist_push()` breaks playlists (try it yourself: go to any playlist and select the 10th entry for example - see where the selection marker ends up). This is clearly unacceptable...

- Restoring the index is somewhat finicky - since users can delete files (eternally) while RetroArch is running, you need to make sure that you don't set an index that exceeds the length of the current menu list

- The feature is not fully wired up - i.e. the path is only remembered in specific circumstances. Please try all permutations - you'll see that, for example, the last used path is not set if you load content that is only supported by one core (such that the core is auto selected). I think I would suggest that instead of trying to set the last used path in `generic_action_ok_displaylist_push()`, you should investigate the practicality of doing it inside `default_action_ok_load_content_with_core_from_menu()`, where the behaviour will be a little more well defined

I hope this doesn't seem too negative! I'm certain these things can be fixed, and this will end up being a valuable addition :)

**Comment by ImJezze** [comment]
Thank you very much for your detailed review! Constructive criticism is always welcome and not negative. And since I'm absolutely new to the code base of RetroArch, I knew from the beginning that there would be obstacles and things I would overlook.

I will fix all open issues as soon as possible.

**Comment by ImJezze** [comment]
@twinaphex 
So far I have only applied the patch. But the critical problems still need to be fixed. Sorry for the delay. I will inform you when I think I am done.

**Comment by jdgleaver** [comment]
@ImJezze Please don't feel pressurised! Take all the time you need. Despite the impression given by twinaphex's unfortunate comment, no one is trying to rush you :)

**Comment by twinaphex** [comment]
My bad, I didn't mean it like that.

**Comment by ImJezze** [comment]
@jdgleaver 
I finally found some time to address the major issues and rewrote the implementation that now shouldn't have unwanted behaviors.

The start director is now set after a successful task_push_load_content_with_new_core_from_menu() call and the file selection is done after filebrowser_parse().

I think I tested all constellation when loading content w/ and w/o core:
- via Start Directory (directory stored)
  - plain content
  - archive
  - plain content when browsing inside an archive
- via Favorites (directory not stored)
- via History (directory not stored)
- via Playlist (directory not stored)

**Comment by ImJezze** [comment]
... but I need to resolve some conflicts before.

**Comment by ImJezze** [comment]
Conflicts resolved and ready for review.

**Comment by ImJezze** [comment]
@jdgleaver 
I just want to give a quick reminder and would like to know if there are any issues I need to resolve.

**Comment by jdgleaver** [comment]
@ImJezze Apologies. This PR hasn't been forgotten (I looked at it earlier this week, in fact), but it has been a case of bad timing. You updated the PR right when we were deeply involved in setting up the new build infrastructure - and we haven't stopped since... This has taken up all of our time for more than 6 weeks now - it is relentless. We are all stressed and exhausted.

The PR looks good, but I need to properly asses the performance impact of your 'pending selection' code. I just don't have the energy to do that right now. I promise that I will review the PR next week.

**Comment by ImJezze** [comment]
@jdgleaver 
Thank you for your quick feedback. The PR is not urgent, other work and free time come first. I really just wanted to know the current status. =)

**Comment by jdgleaver** [comment]
@ImJezze Okay, finally managed to squeeze in a quick review... :)

There remain a couple of significant issues with the PR:

- It incorrectly applies the 'last directory' setting to *every* directory entry in the load content menu + scan file. e.g. `Load Content > Downloads` will take you to the last used directory, not `Downloads`...
- The `strdup()` in `menu_driver_get_last_start_directory()` is a memory leak

This diff file fixes all the problems I could find, and cleans up a few things: [last_dir_fixes.zip](https://github.com/libretro/RetroArch/files/5932361/last_dir_fixes.zip)

Please apply this on top of your PR, and check that everything still works as you expect.

After that, please rebase and squash your commits. We should then be ready to merge :)

**Comment by ImJezze** [comment]
@jdgleaver 
Thanks again for your detailed review. I applied your patch and everything seems to work fine. I rebased the branch and squashed all commits into one. Hope I didn't screw up anything in the process.

**Comment by jdgleaver** [comment]
@ImJezze Excellent - this is perfect now. Thanks!

It's such a nice addition, and I'm excited about your `menu_driver_set_pending_selection()` implementation. I can't believe I never thought of that before! I will certainly be using it for other file browser menu entries ;)

@twinaphex This is ready to merge :)

**Comment by ImJezze** [comment]
@jdgleaver @twinaphex 
While browsing the issue list I found two that probably were fixed with this PR: #5544, #1438

**Pull request merged**
