### PR TITLE
Wii: Skip CRC. Avoid an unnecessary delay.

### PR DESCRIPTION
**Pull request by Wiimpathy**
## Description

When loading a large rom, Sengoku 3 in fbalpha2012_neogeo for example, there's an added delay of about 4 or 5 seconds. From what I understand, this CRC check is used for network play which isn't available for the Wii and Gamecube platforms.

## Related Pull Requests

This was added by this commit: https://github.com/libretro/RetroArch/commit/edacf67e7545af5e2edce63efc16e6cd8c4b10c2#diff-5b4b98202ea8ff3448e09fd786674bf3

### CODE REVIEW

**Comment by fr500** [comment]
it's a good thing I agree
maybe we need to have a define for LOW MEMORY / LOW POWER devices to be able to apply this globally 

(this would be good on PSP, 3DS, emscripten, probably XBOX OG, PS2)

**Comment by RobLoach** [comment]
It's also used for playlist generation. Does this completely disable scanning on Wii?

**Comment by fr500** [comment]
No that is not used for playlist generation

**Comment by fr500** [comment]
It's not used for either, this is under content_load

**Comment by i30817** [comment]
Why isn't CRC checking memoized if it's used in 2 or more places?

**Comment by Wiimpathy** [comment]
I don't see any real use for this crc check or a better and simpler way to skip it. But feel free to correct me. I've tested once again with Garou or Kof2003 and it's more about 10 seconds. I'm working on updating fba neogeo to reduce loading times for the Wii, and with this check there wouldn't be any improvements.

Right now, in fbalpha2012_neogeo with this crc calculation and the above-mentioned games, it takes about 50 seconds. With some tricks it could be below 30 seconds.

**Comment by i30817** [comment]
No, i agree that in general, there is no point for it on platforms that have no netplay.

I was just wondering if the `file_crc32` function shouldn't be wrapped in another that checks if the value is already cached or on the playlist.

**Comment by fr500** [comment]
this has **nothing to do with scanning** even if the host uses playlists, the client is not guaranteed to use playlists at all.
I think this PR is good.

**Comment by i30817** [comment]
To be 'constructive' and not get into digressions of if a cache needs to be 'guaranteed' ...

Isn't it better to make a specific define for this called something like 'NO_NETPLAY' that currently has that GECKO value?

Because it's not very self-documenting right now if other platforms are to be added.

In fact, i kind of remember seeing `./configure --disable-networking` which is more general, and  `--disable-netplaydiscovery` which is even more specific?

**Pull request merged**
