### PR TITLE
(WiiU) Buildfix

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Why are we doing this instead of just defining it? All these one platform specific ifdefs are going to be making this very unmaintainable moving forward vs. just defining a one line macro.

**Comment by LibretroAdmin** [comment]
Fine, you provided a justification before, guess I'll live with it. I'd still prefer if instead of all these WiiU ifdefs we had something like this instead -

#ifndef WIIU
#define HAVE_IFF_UP
#endif

and if that is defined, you include the header. And you then change the remaining #ifndef WIIU ifdefs to HAVE_IFF_UP. That way, if other platforms pop up that don't support this, we can group them together like this.

**Comment by Cthulhu-throwaway** [comment]
That only applies to Linux (and some BSDs). Windows for instance uses IfOperStatusUp and is defined in a completely different header. Other platforms that aren't Linux (or BSD-based) don't even have this check (Wii, Switch and 3DS).

This is structured the same way as net_compat, full of platform specific branches because they either decided they didn't need BSD sockets or because the SDK used is just a partial CTRL+C of glibc.

All files in libretro-common/net are branched like this, I don't see a point of defining HAVE_IFF_UP for just one platform.
If another platform pops up that tries to compile the Linux portion of the code and fails, it either needs its own branch or it's another partial glibc implementation. Your suggestion would apply for the latter, which feels even less maintainable as it becomes ambiguous (IFF_UP is for Linux-based platforms).

Feel free to change it to the way you like though, either edit my PR or change it after merging it. I think it's a waste of time and adds nothing to maintainability because IFF_UP is by itself platform-specific.

**Comment by LibretroAdmin** [comment]
Will just go along with what you think is best in that case.

**Comment by Cthulhu-throwaway** [comment]
And of course, compilation fails because of IPv6 on the WiiU.

**Pull request merged**
