### PR TITLE
(Has dependencys in libretro-super and libretro-toolchains)Update 3ds devkitPRO/ARM to latest version

### PR DESCRIPTION
**Pull request by meepingsnesroms**
It is compiling but there are still issues with some assets and I need to make a new custom toolchain for the buildbot

### CODE REVIEW

**Comment by meepingsnesroms** [comment]
This should all be ready to merge now and I have tested compiling on windows with msys2 and the newest devkitARM with the 2048 core, it works fine.

The buildbot part has not been tested, but I will be providing support within 24 hours for the next week if anything is wrong.

**Comment by twinaphex** [comment]
OK, I assume you are in talks with either @fr500 or @bparker06 when it comes to whatever needs to be changed on the buildbot side?

@bparker06 and/or @fr500 - can either of you two coordinate this with him? You can merge whatever is necessary then in the process.

**Comment by meepingsnesroms** [comment]
I havent talked with either of them but I already made all the necessary changes with the 3 pull requests, they just need to all be merged at the same time or they will break things.

**Comment by fr500** [comment]
Neither of those will update the toolchain on the buildbot though.
If you can give me a full tarball of the toolchain I can update it today. If it implies manual labor... I don't think I can do it right away.

**Comment by meepingsnesroms** [comment]
There is a tarball in a pull request for libretro-toolchains.

**Comment by meepingsnesroms** [comment]
Is there anything I need to change?

**Comment by twinaphex** [comment]
@fr500 Let's see if we can push this along if you have time.

**Comment by meepingsnesroms** [comment]
Will this be merged after the Christmas 1.7.0 update, its quite distressing to just have a working sdk update just sit for a week with no knowledge of when it might be merged.
I have already checked 252(3 times an hour) times, I need to know what is going to happen with this.

**Comment by fr500** [comment]
I'm not near my computer now, and probably won't be till the 27th

**Comment by twinaphex** [comment]
@fr500 OK, is this safe to merge then on all repos?

**Comment by fr500** [comment]
No I don't think so you have to update the toolchain on the buildbot first from the tarball in libretro-toolchains

**Comment by twinaphex** [comment]
@meepingsnesroms since you are on Discord as cuttlefish, come on there and you can talk to @bparker06 who is in charge of the buildbot. We could discuss things further then.

**Comment by meepingsnesroms** [comment]
This pull request is outdated due to [this](https://github.com/libretro/RetroArch/pull/5951).

I will make a new pull request with the other fixes since this already adds support for the new devkit arm.

**Pull request closed without merging**
