### PR TITLE
[Win32 & UWP] ANGLE OpenGL ES support

### PR DESCRIPTION
**Pull request by driver1998**
## Description

Add ANGLE OpenGL ES support for both Win32 and UWP.
Support the following backing renderers:
- D3D11
- D3D11 Feature Level 9_3
UWP only, for devices without full D3D11 support, like phones
Not needed on Win32 because we can just use D3D9)
- D3D9 (Win32 Only, not available on UWP)

No vcproj updates here, because I can't just assume where ANGLE is located. (I installed it from vcpkg, with https://github.com/microsoft/vcpkg/pull/8970)
But it is as simple as adding includes and libs, and the following defines:
- HAVE_OPENGL
- HAVE_OPENGLES
- HAVE_OPENGLES2 (or 3?)
- HAVE_GLSL
- HAVE_EGL

On Win32 this will replace WGL entirely, getting rid of opengl32.dll dependency.

It currently cannot coexist with OpenGL Core support, it won't compile.
It can coexist with Vulkan support though.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hey, this is an awesome commit!

One small thing I'd request is if there is a way to either have a compile-time option where either ANGLE is used for all things GL or regular GL is used. Preferably it'd be runtime but I'm not sure if you consider that impractical to do considering ANGLE requires GLES2, so I'd be fine with a compile-time option as a compromise.

If this can be done, you could pick a 'define' of your choice (i.e. -DHAVE_ANGLE), and then I could whip up a qb option around it so we could tell configure something like ./configure --enable-angle.

And yes, for the UWP builds, we will enable ANGLE by default. There is no way to do native OpenGL there anyway.

**Comment by driver1998** [comment]
Currently ANGLE is enabled if you have both HAVE_OPENGLES and HAVE_EGL, because we have neither of these in normal Windows.

If I add a HAVE_ANGLE, that would be something like
#ifdef HAVE_ANGLE
#define HAVE_EGL
#define HAVE_OPENGLES
#define HAVE_OPENGLES2
#undef HAVE_OPENGL_CORE
#endif

**Comment by twinaphex** [comment]
Yeah, that would be fine. I just want to have some options here so the builder can always specify not to compile in ANGLE at his/her own discretion.

**Comment by driver1998** [comment]
So now we have HAVE_ANGLE, you still need HAVE_OPENGL and HAVE_GLSL along side with it.

PS: It turns out that ANGLE works fine with HAVE_OPENGLES3, even when it is running on D3D9 hardware (where ANGLE only implements GLES2), so I use that instead.
glcore driver also works now (on D3D11 hardware)

**Comment by twinaphex** [comment]
Hi @driver1998 ,

can you make a branch on your fork where you show the changes you had to make to MSVC 2017 to get it to work? It would help me out here on my end to come up with a new configuration target for it.

**Comment by twinaphex** [comment]
Hi @driver1998,

I'm having issues building UWP from vcpkg even with that yet unmerged PR you linked to.

I get this back -

https://paste.ee/p/bOyV2

Any ideas?

**Comment by driver1998** [comment]
Well I use Win10 SDK v18362 here, so that might be why vcpkg failed to compile on your end?

**Pull request merged**
