### PR TITLE
Add error notification

### PR DESCRIPTION
**Pull request by lasers**
Fixes https://github.com/libretro/RetroArch/issues/3807#issuecomment-262228977

### CODE REVIEW

**Comment by lasers** [comment]
This is to help the users.

I forget I had `joypad_autoconfig_dir = "/usr/share/libretro/autoconfig"` from the first time I set up RetroArch following Archlinux Wiki.

The notification right now: `100%: Downloading $STUFF` then `... failed quietly ...`
New notification: `100%: Downloading $STUFF` then `Download $STUFF: $ERROR_MSG`

**Comment by twinaphex** [comment]
@fr500 Can you review if we can merge this?

**Comment by Alcaro** [comment]
> char err_msg[128];

Assuming $STUFF is a path, 128 feels a bit slim.

> err_msg[0] = '\0';

Not needed, s(n)printf doesn't care what's in the output buffer.

**Comment by lasers** [comment]
Thanks for the feedback @Alcaro. Much appreciated. Finished.

**Comment by lasers** [comment]
@fr500 Can you review if we can merge this?

**Comment by twinaphex** [comment]
@fr500 / @Alcaro can we do a final review on this and determine whether to merge it or not? Thanks.

**Comment by fr500** [comment]
Not sure what he's trying to communicate with the message

**Comment by lasers** [comment]
@twinaphex Can you review if we can merge this?

**Comment by lasers** [comment]
**@lasers** Can you review if we can merge this?

Ok. I reviewed it. It looks good but `Write failed.` is not written for language transitions. Can you please fix that? Many thanks.

**Comment by lasers** [comment]
@twinaphex I skipped msg_hash_ja.h (problematic just now). 

Do you want to merge or close this? Same for `Add error notification`.

**Comment by lasers** [comment]
@fr500 This too?

**Comment by fr500** [comment]
I think it's ok but I'll wait for twinaphex

**Comment by lasers** [comment]
It had been more than two weeks. I better close this too. Thanks for letting me know if the team does not want something included.

**Pull request closed without merging**
