### PR TITLE
Restore BOM markers on msg_hash_tr files

### PR DESCRIPTION
**Pull request by Dwedit**
BOM markers re-added to `msg_hash_tr.c` and `msg_hash_tr.h` to fix building on MSVC.

### CODE REVIEW

**Comment by orbea** [comment]
Mind explaining how to check for BOM markers and how to add them back? It would be nice to know how to avoid breaking this. :)

**Comment by Dwedit** [comment]
I only really notice missing BOM markers when I get compiler errors when I try to build on MSVC, with computer set to Code Page 932 (Japanese locale).  Without the BOM markers, I get "Newline in Constant" errors everywhere.

Anyway, the first 3 bytes of the file should be EF BB BF, and you can use a hex editor to make sure that those bytes are present.  I use HXD.  When I see the BOM maker missing, I copy-paste it from another nearby file which has the BOM marker.

Some text editors also let you pick between "UTF-8" and "UTF-8 with BOM", and will strip off the BOM marker in one mode, and add it in in the other mode.

**Comment by orbea** [comment]
Thanks, what is the complete list of files that need these BOM markers? I'm considering that it might be possible to check these files with travis and a shell script.

**Comment by orbea** [comment]
Seems there are several files missing them?
```
$ for i in *; do  echo $i ; hexdump -n 3 -C $i; done
msg_hash_ar.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_ar.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_chs.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_chs.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_cht.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_cht.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_de.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_de.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_el.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_el.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_eo.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_eo.h
00000000  4d 53 47                                          |MSG|
00000003
msg_hash_es.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_es.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_fr.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_fr.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_it.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_it.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_ja.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_ja.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_ko.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_ko.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_lbl.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_nl.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_nl.h
00000000  4d 53 47                                          |MSG|
00000003
msg_hash_pl.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_pl.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_pt_br.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_pt_br.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_pt_pt.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_pt_pt.h
00000000  4d 53 47                                          |MSG|
00000003
msg_hash_ru.c
00000000  ef bb bf                                          |...|
00000003
msg_hash_ru.h
00000000  ef bb bf                                          |...|
00000003
msg_hash_tr.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_tr.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_us.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_us.h
00000000  23 69 66                                          |#if|
00000003
msg_hash_vn.c
00000000  2f 2a 20                                          |/* |
00000003
msg_hash_vn.h
00000000  ef bb bf                                          |...|
00000003
```

**Comment by Dwedit** [comment]
Went ahead and added in all the other BOMs using a hex editor

**Comment by orbea** [comment]
I think I can support this in travis, I'll make a new PR in a bit which may conflict with yours, but that is the best way to test this...

**Comment by orbea** [comment]
Alternate PR is here.

https://github.com/libretro/RetroArch/pull/8787

@Dwedit I would really appreciate your thoughts on this. :)

**Comment by twinaphex** [comment]
Ok so what is the idea here? Can this be merged or not?

**Comment by orbea** [comment]
@twinaphex PR https://github.com/libretro/RetroArch/pull/8787 has a more complete solution which replaces this PR (They will conflict), please ask @bparker06 if that one is ready or not.

**Comment by Dwedit** [comment]
Looks like PR #8787 was closed and not merged in.  While it does provide a script for fixing the code and such, and checks for issues, my PR is just a one-time fix for the code.

Anyway, the build is still temporarily broken in MSVC on certain Asian locales, so we still need the BOMs to be added to the files.

**Comment by twinaphex** [comment]
Why can't you get it building with MSVC though? I can get it building just fine with the MSVC solution files that use Griffin.

So I'm just trying to understand where the demand is coming from here.

**Comment by Dwedit** [comment]
MSVC builds using your system code page by default.  My system code page is Shift-JIS, therefore I get this issue:
```
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_QUIT,
    "Çıkış"
    )
```
In Shift-JIS:
```
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_QUIT,
    "ﾃ・ｱkﾄｱﾅ・
    )
```
Bytes are `22 C3 87 C4 B1 6B C4 B1 C5 9F 22`, but if interpreted as Shift-JIS, you get `22 C3 87C4 B1 6B C4 B1 C5 9F22`, and lose the end quote.

So either we need a BOM on the file, need to build with the /utf-8 switch (PR #8804), or force the developer to change their system code page to something that isn't Chinese/Korean/Japanese.  I think applying both the BOM and the /utf-8 switch would be most helpful.

**Comment by twinaphex** [comment]
Just make sure that there are exactly ZERO backwards compatibility regressions when introducing this. We target very low Visual Studio versions, it needs to continue being compilable on there. Same with ancient compilers.

**Comment by Dwedit** [comment]
I think I can test MSVC 6.0 and MSVC 2008 right now, but I don't have any other of the older compilers right now.

**Comment by bparker06** [comment]
if we add the resource files into msvc (we should have already done it honestly) then those use local codepages... but I don't know if any /utf8 switch might affect that.

**Comment by Dwedit** [comment]
So I was doing a bunch of testing, and things are more difficult then I thought.  Don't merge this until I've finished the tests.

**Comment by Dwedit** [comment]
There are so many combinations of compilers, BOMs, build locales, and Pragmas that this gets complicated quickly.

I had run a number of experiments in building the program to see how text was affected.

I came to the conclusion that in order to get text intact, and not encounter compiler errors, you must do one of three things:
* Strip off all BOMs, remove all `execution_character_set` pragmas, and exclusively build on a non-Asian system locale.
* Place a BOM at the beginning of all files using international characters, and use the `execution_character_set` pragma.
* Use the `/utf-8` switch, and do not use the `execution_character_set` pragma at the same time.  BOMs can either be present or absent, and it won't matter.

Option 1 is required for MSVC 6 through 2008 (pre-patch).
Option 2 can be used for MSVC 2010 through MSVC 2017.  You will get corrupted text for international characters on MSVC 2008 and earlier on all build locales.
Option 3 can be used for MSVC 2015 and MSVC 2017, and can be combined with either option 1 or 2.

So in the end, it's a choice between supporting MSVC 2010-2013 on Asian system locales, or supporting MSVC 2008 and earlier.

**Comment by bparker06** [comment]
I always build on JP locale and haven't had any problems, can you give some examples?

The reason our current option 2 approach works is because we simply disable HAVE_LANGEXTRA at the age of compiler (and below) that starts to complain about BOMs... so there's no non-Latin chars in the source to worry about then. Most of the older systems targeted by these compilers don't have enough memory to support all the languages (and unicode font drivers) anyway.

**Comment by Dwedit** [comment]
Here's an example.
You are using MSVC 2017 on the current Git Master under JP locale.
You attempt to build, and msg_hash_tr won't build without a BOM on the file, you add it in.
You test the program, and you see this when you pick the Portuguese language: "Portuguﾃｪs (Brasil)", and elsewhere on the screen you see "Usuﾃ｡rio".

What's going on? `msg_hash_pt_br` has no BOM, and the compiler interpreted it as Shift-JIS.  Then later on, the compiler encoded the mojibake into UTF-8, because it encountered an `execution_character_set` pragma somewhere in another file.

Another example.
You are using MSVC 2008.  Your system locale is English.  You are building the current Git Master.
All international characters outside the western codepage become question marks.  Yes, this is real.
If your system locale was Japanese instead, all non-Japanese international characters would have accent marks stripped off, or become question marks.
What happened here?  MSVC 2008 interpreted the code as UTF-8 because it saw a BOM, but then discarded the characters that it could not encode in the local code page.

So once again, the question becomes: "Do we support 2008 versions of MSVC on all locales, or do we support 2010-2013 versions of MSVC on JP locale, and break 2008 and earlier on all locales?"

We're currently doing the latter.

**Comment by bparker06** [comment]
Would it help to add the pragma to *all* language files?

**Comment by bparker06** [comment]
Also as it stands I'm fine with simply not defining HAVE_LANGEXTRA on 2008 and below, limiting them to English. I don't think TA has a problem with this either as it's generally just a waste of memory.

**Comment by Dwedit** [comment]
Adding the BOM and Pragma to all non-english language files would help MSVC 2010-2013 on JP locale.
There are also a few other files which use international characters that are not part of the language files: `menu_cbs.c`, and `menu_osk_utf8_pages.h`

So the Euro character will be corrupted on MSVC 2008 and earlier if built on JP locale.

I'm guessing that MSVC 2010 or 2013 is your main version of MSVC?

**Comment by bparker06** [comment]
Not sure what you mean by main... I don't typically use msvc unless I'm just testing things, but I think 2010 is the most popular msvc build as we still have a good number of XP users, and it works better for some people with older graphics hardware in general.

**Comment by Dwedit** [comment]
I'm leaning towards dropping support for JP locale on MSVC 2010-2013, and having a script available for people who need to build on JP locale on MSVC 2010-2013.

**Comment by bparker06** [comment]
I don't agree with that approach at all.

**Comment by bparker06** [comment]
@twinaphex thoughts?

**Comment by twinaphex** [comment]
Dropping locale seems to me like a regression. I'd prefer we don't do that.

**Comment by Dwedit** [comment]
So we've decided to prioritize Japanese Locale building on MSVC 2010-2013, and not support MSVC 2008 and earlier out of the box.

Therefore source files which contain any international characters in strings must have a BOM, and must have a Pragma specific for MSVC 2008-2013.

These are the files with international characters which actually matter:
* Everything in `intl/` except `msg_hash_en`
* `menu/menu_cbs.c` - Used for the Euro character
* `menu/widgets/menu_osk_utf8_pages.h` - Used for Japanese text entry
* `ui/drivers/qt/shaderparamsdialog.cpp` - Used for arrow-shaped text labels on buttons

So those files above will get a BOM, and a utf-8 fixing pragma for MSVC 2008-2013 only.

The MSVC 2015 and 2017 projects will get the `/utf-8` switch.  The makefiles for MSVC 2015 and 2017 will also need the `/utf-8` switch added, where do I put this?

A developer will be able to build RetroArch without errors on MSVC 2010 through 2017 on any locale.
Will not be able to build on MSVC 2003-2008 on any locale without introducing corrupt text.  Will not be able to build on MSVC 6.0.
If the developer strips off all BOM characters, they will be able to build on MSVC 6.0 on any locale, and MSVC 2003 through 2008 on non-Asian locales.

**Comment by Dwedit** [comment]
Okay, just thought of one more thing I hadn't considered.  You can token paste `u8` and a string literal together, so I'll see what happens if you define MSG_HASH for various MSVC versions and locales.

**Comment by bparker06** [comment]
The `u8` string literal prefix only exists with C++11 though...

**Comment by Dwedit** [comment]
Yep, just confirmed that it indeed does not work on MSVC 2008.

**Comment by Dwedit** [comment]
So the EO locale looks like a placeholder (is it just English?), and the NL locale uses no accented characters?  Should I mark those files as UTF-8 anyway?

**Comment by bparker06** [comment]
It appears to be a placeholder for Esperanto (Latin-3). NL is Latin-1.

**Comment by Dwedit** [comment]
Resubmitted as PR #8829

**Pull request closed without merging**
