### PR TITLE
Fix cheevos.c performance issues due to headerless NES hashing

### PR DESCRIPTION
**Pull request by rzumer**
## Description

The NES hashing strategy happens to be applied to all files regardless of extension or system, so #7201 dramatically increased the number of requests for systems that benefit from the generic MD5 hashing strategy (including SNES), causing delays in retrieving game IDs.

This reduces the average number of iterations for headerless NES hashing by decreasing the chunk count in the hashing loop with every iteration instead of increasing it, and moves the NES subroutine to the bottom of the list in order to avoid blocking other systems.

## Reviewers

@leiradel

### CODE REVIEW

**Comment by leiradel** [comment]
I'm not sure we can shuffle the heuristics around like that, I seem to remember issues with one heuristic wrongly identifying some games and thus having to stay after the other one.

**Comment by rzumer** [comment]
@leiradel So, MD5 hash collisions? If that's an issue, the hashing algorithm should change altogether, but I don't think that changing the order of operations will make it any more or less likely to occur.

**Comment by rzumer** [comment]
@leiradel I don't think that this will help in case of collisions, but I brought `NES_MD5` back before the generic hashing methods and split the headered and headerless methods into different subroutines, which is cleaner anyway.

**Comment by leiradel** [comment]
Shouldn't all occurrences of `0x4000` be changed to `chunk_size`?

**Comment by leiradel** [comment]
@meleu do you know how we can test this?

**Comment by Dwedit** [comment]
Does it at least check for "NES",0x1A before trying NES hashing?

**Comment by leiradel** [comment]
Hm, I believe we'll have to roll this back, it takes too long to login to RetroAchievements and get the list of cheevos in some situations.

The correct fix is to update RetroAchievements to have the full content hash of NES games.

**Comment by rzumer** [comment]
Did you not realize that #7333 fixes your issue?

**Comment by leiradel** [comment]
Looking at the code it seems the code can make up to 250 HTTP requests on some cases.

**Comment by rzumer** [comment]
@leiradel And it used to be that every single thing being loaded that required generic MD5 hashing or was simply not in the database would request up to its file size / 16KB worth of requests. If you prefer, the maximum number of tested chunks can be restricted to 125 (largest size I'm aware of) or extensions tested with this method can be filtered like the other platform-specific ones.

Can you submit a code review and point out specific lines that you have issues with instead of leaving individual comments that are not all related to this PR?

**Comment by leiradel** [comment]
> And it used to be that every single thing being loaded that required generic MD5 hashing or was simply not in the database would send up to its file size / 16KB worth of requests

Yes, it was already bad and I didn't realize at the time.

> Restricting the maximum number of unnecessary requests is important, but it is not that dramatic if the back-end is able to handle it.

The backend can handle it, but can the user wait? One minute to get the achievements after the emulation starts is not acceptable.

> If you prefer, the maximum number of tested chunks can be restricted to 125

I don't think it will bring wait times below anything acceptable. Also, we have to think of mobile users which may be on mobile network.

> extensions tested with this method can be filtered like the other platform-specific ones

It will still make that many HTTP requests for those extensions.

> Can you submit a code review and point out specific lines that you have issues with instead of leaving individual comments that are not all related to this PR?

Sorry, what?

**Comment by rzumer** [comment]
Rebased. What looks like a whole file change in 8f0efd9 is due to line endings changing, but content is not affected.

@leiradel

>
> > Restricting the maximum number of unnecessary requests is important, but it is not that dramatic if the back-end is able to handle it.
> 
> The backend can handle it, but can the user wait? One minute to get the achievements after the emulation starts is not acceptable.

As I tried to explain in the description, the point of this PR is to solve that issue.

> 
> > If you prefer, the maximum number of tested chunks can be restricted to 125
> 
> I don't think it will bring wait times below anything acceptable. Also, we have to think of mobile users which may be on mobile network.

The "one minute wait" scenario applies only to situations where hashes are tested for the wrong files (i.e. non-NES) at the wrong time (i.e. before the generic method). af4ecf1 solves that part with reordering.

> 
> > extensions tested with this method can be filtered like the other platform-specific ones
> 
> It will still make that many HTTP requests for those extensions.

It won't unless testing for an unsupported title (not in the database at all), in which case the client does not care anyway, because no ID will be returned. If something is in the database, larger NES files should load faster than they used to with this PR, because larger chunks are now tested first.

> > Can you submit a code review and point out specific lines that you have issues with instead of leaving individual comments that are not all related to this PR?
> 
> Sorry, what?

The "Files changed" tab allows you to refer to specific lines in your comments.

**Comment by leiradel** [comment]
> Rebased. What looks like a whole file change in 8f0efd9 is due to line endings changing, but content is not affected.

I can't see the diff any longer, can you undo this?

**Comment by rzumer** [comment]
> 
> 
> > Rebased. What looks like a whole file change in [8f0efd9](https://github.com/libretro/RetroArch/commit/8f0efd9a601e7d4d737492157c42a79747761584) is due to line endings changing, but content is not affected.
> 
> I can't see the diff any longer, can you undo this?

Line endings needed to be renormalized due to the big revert, I can't do anything about it. Here is the diff with `--ignore-all-space`.
```
diff --git a/cheevos/cheevos.c b/cheevos/cheevos.c
index 0e21e3687a..a0fc48ca9f 100644
--- a/cheevos/cheevos.c
+++ b/cheevos/cheevos.c
@@ -1,5 +1,5 @@
 /*  RetroArch - A frontend for libretro.
- *  Copyright (C) 2015-2016 - Andre Leiradella
+ *  Copyright (C) 2015-2018 - Andre Leiradella
  *
  *  RetroArch is free software: you can redistribute it and/or modify it under the terms
  *  of the GNU General Public License as published by the Free Software Found-
@@ -288,6 +288,7 @@ static cheevos_locals_t cheevos_locals =
 bool cheevos_loaded = false;
 bool cheevos_hardcore_active = false;
 bool cheevos_hardcore_paused = false;
+bool cheevos_state_loaded_flag = false;
 int cheats_are_enabled = 0;
 int cheats_were_enabled = 0;
 
@@ -2554,18 +2555,19 @@ enum
    GENESIS_MD5          = -2,
    LYNX_MD5             = -3,
    NES_MD5              = -4,
-   GENERIC_MD5  = -5,
-   FILENAME_MD5 = -6,
-   EVAL_MD5     = -7,
-   FILL_MD5     = -8,
-   GET_GAMEID   = -9,
-   GET_CHEEVOS  = -10,
-   GET_BADGES   = -11,
-   LOGIN        = -12,
-   HTTP_GET     = -13,
-   DEACTIVATE   = -14,
-   PLAYING      = -15,
-   DELAY        = -16
+   HEADERLESS_NES_MD5   = -5,
+   GENERIC_MD5          = -6,
+   FILENAME_MD5         = -7,
+   EVAL_MD5             = -8,
+   FILL_MD5             = -9,
+   GET_GAMEID           = -10,
+   GET_CHEEVOS          = -11,
+   GET_BADGES           = -12,
+   LOGIN                = -13,
+   HTTP_GET             = -14,
+   DEACTIVATE           = -15,
+   PLAYING              = -16,
+   DELAY                = -17
 };
 
 static int cheevos_iterate(coro_t *coro)
@@ -2603,6 +2605,12 @@ static int cheevos_iterate(coro_t *coro)
       0
    };
    
+   static const uint32_t nes_exts[] =
+   {
+      0x0b88944bU, /* nes */
+      0
+   };
+
    static const uint32_t lynx_exts[] =
    {
       0x0b888cf7U, /* lnx */
@@ -2616,7 +2624,9 @@ static int cheevos_iterate(coro_t *coro)
       {LYNX_MD5,            "Atari Lynx (only first 512 bytes)", lynx_exts},
       {NES_MD5,             "NES (discards VROM)",               NULL},
       {GENERIC_MD5,         "Generic (plain content)",           NULL},
-      {FILENAME_MD5, "Generic (filename)",               NULL}
+      {FILENAME_MD5,        "Generic (filename)",                NULL},
+      /* Headerless NES comes last due to the volume of requests. */
+      {HEADERLESS_NES_MD5,  "Headerless NES (discards VROM)",    nes_exts}
    };
 
    CORO_ENTER();
@@ -3002,15 +3012,10 @@ found:
       memcpy((void*)&coro->header, coro->data,
             sizeof(coro->header));
 
-      if (     coro->header.id[0] != 'N'
-            || coro->header.id[1] != 'E'
-            || coro->header.id[2] != 'S'
-            || coro->header.id[3] != 0x1a)
-      {
-         coro->gameid = 0;
-         CORO_RET();
-      }
-
+      if (coro->header.id[0] == 'N'
+        && coro->header.id[1] == 'E'
+        && coro->header.id[2] == 'S'
+        && coro->header.id[3] == 0x1a)
       {
          size_t romsize = 256;
          /* from FCEU core - compute size using the cart mapper */
@@ -3026,24 +3031,74 @@ found:
             * we use FCEU_read. */
          coro->round       = mapper != 53 && mapper != 198 && mapper != 228;
          coro->bytes       = coro->round ? romsize : coro->header.rom_size;
-      }
 
-      /* from FCEU core - check if Trainer included in ROM data */
-      MD5_Init(&coro->md5);
       coro->offset = sizeof(coro->header) + (coro->header.rom_type & 4
             ? sizeof(coro->header) : 0);
-      coro->count  = 0x4000 * coro->bytes;
+
+          size_t chunk_size = 0x4000;
+            
+          /* from FCEU core - check if Trainer included in ROM data */
+          MD5_Init(&coro->md5);
+
+          coro->count  = chunk_size * coro->bytes;
           CORO_GOSUB(EVAL_MD5);
 
-      if (coro->count < 0x4000 * coro->bytes)
+          if (coro->count < chunk_size * coro->bytes)
           {
              coro->offset      = 0xff;
-         coro->count       = 0x4000 * coro->bytes - coro->count;
+             coro->count       = chunk_size * coro->bytes - coro->count;
              CORO_GOSUB(FILL_MD5);
           }
 
       MD5_Final(coro->hash, &coro->md5);
       CORO_GOTO(GET_GAMEID);
+      }
+
+    CORO_SUB(HEADERLESS_NES_MD5)
+
+      size_t chunks     = coro->len >> 14;
+
+      /* Assume that valid (including unlicensed) NES titles do not 
+       * exceed 32MiB, in order to avoid excessive requests
+       * with large non-NES files. */
+      if (chunks > 250)
+      {
+          CORO_RET();
+      }
+
+      size_t chunk_size = 0x4000;
+
+      /* PRG ROM size is unknown, so test by 16KB chunks. */
+      coro->round       = 0;
+      coro->offset      = 0;
+
+      unsigned i;
+      for (i = chunks; i > 0; i--)
+      {
+          MD5_Init(&coro->md5);
+          
+          coro->bytes = i;
+          coro->count = coro->bytes * chunk_size;
+          
+          CORO_GOSUB(EVAL_MD5);
+
+          if (coro->count < chunk_size * coro->bytes)
+          {
+             coro->offset      = 0xff;
+             coro->count       = chunk_size * coro->bytes - coro->count;
+             CORO_GOSUB(FILL_MD5);
+          }
+
+          MD5_Final(coro->hash, &coro->md5);
+          CORO_GOSUB(GET_GAMEID);
+          
+          if (coro->gameid > 0)
+          {
+              break;
+          }
+      }
+
+      CORO_RET();
 
       /**************************************************************************
        * Info   Tries to identify a "generic" game
@@ -3389,9 +3444,9 @@ found:
 
                /* Save token to config and clear pass on success */
                *coro->settings->arrays.cheevos_password = '\0';
-               strlcpy(
+               strncpy(
                      coro->settings->arrays.cheevos_token,
-                     cheevos_locals.token, sizeof(coro->settings->arrays.cheevos_token)
+                     cheevos_locals.token, sizeof(cheevos_locals.token)
                );
                CORO_RET();
             }
```

**Comment by leiradel** [comment]
So in the case the content is a headerless NES ROM, we still can make lots of HTTP requests until it's correctly identified, up to 250 if it's not present in the database.

I believe we should revert all this, I think it's not acceptable to make that many HTTP requests, specially on mobile. RetroAchievements should work towards adding headerless ROMs to the database, or the player should be using ROMs with headers.

@fr500 do you have an opinion about this?

**Comment by rzumer** [comment]
@leiradel I don't want to keep repeating myself, but like I said, I can reduce the number of chunks tested further if you still have reservations. The server-side change that you want cannot happen in the immediate future.

**Comment by leiradel** [comment]
How much is the minimum? Any number in the tenths is unacceptable IMO. We already do one HTTP request per heuristic, but those are unavoidable.

**Comment by rzumer** [comment]
@leiradel Less than 10 requests (i.e. trimming 0-168KB of CHR) will likely fail for titles with large CHR banks.

Do you know the average size of a request-response pair? I doubt that it is measured in more than a few bytes when compressed and when the response is negative.

**Comment by rzumer** [comment]
@leiradel Firstly, I just verified the response length, and it is under 50 bytes. The request is a simple GET, so even overestimating at 100 bytes per request, 1000 such request-response pairs only weigh 100 KB. I think with that we can be confident that even mobile users will not feel this much, especially considering that this hashing method will be skipped over for non-NES platforms.

As far as detection time goes, you need to understand that:
* with this PR, this is only relevant to headerless files and no longer blocks other systems
* any file present in the database will be detected in a much lower number of iterations
* any file not present in the database will not be detected either way, so the extra requests does not affect the user experience

With that in mind, what is the "wait time" you are referring to? Typical files will be detected in just a handful of iterations, i.e. a few seconds. Larger ones may indeed take a little bit longer to be detected (this is unlikely to take a minute, however), but again, this *only* affects headerless NES files with these changes.

**Comment by rzumer** [comment]
With 6596cab, even files with the `nes` extension that don't have an ID will not be tested in the headerless fallback method, so most users will never even go through this branch.

**Comment by fr500** [comment]
As far as I can tell on good wifi it was simply not working at all. On AARCH64 it never loaded, on Windows Desktop wired it was taking a minute. Not sure how is that it was working on 32-bit android.  I'll have to test the current master tonight.

Also my testing was not with NES roms, but SNES, (and GBC and GBA) and both presented the same behavior.

**Comment by rzumer** [comment]
@fr500 You need to pull the branch associated with this PR and recompile if you want to test it. Your comment is relevant to https://github.com/libretro/RetroArch/pull/7201, not this PR. The current master is a rolled back version that does not support headerless NES hashing.

**Comment by leiradel** [comment]
I've talked to the Retro Achievements guys and there are only around 2000 games with achievements. This means that, for the majority of games, there will be a huge number of wasted HTTP connections trying to identify games that are not even in the database.

The correct fix is to add the appropriate hashes to the Retro Achievements database, and make it clear somewhere that the player should try a ROM with header if RetroArch fails to load the achievements and the game is supported by Retro Achievements.

I'll remove progressive scanning of headerless NES ROMs from the cheevos implementation in RetroArch.

**Comment by rzumer** [comment]
@leiradel Firstly, detection relies on the presence of a title linked in the database, of which there are over 12 thousand. Secondly, and I think I was pretty clear in my earlier comments, headerless hashing is skipped for headered files with this PR. Finally, I already proved to you that the cumulative requests for even the biggest known headerless file would amount to under 25KB of transmitted data. I already addressed your suggestion for a back-end change; it will require changes in the clients, and is unlikely to happen any time soon. 

From my point of view, you are only compromising compatibility and you have not provided a valid reason to do so. I have already made adjustments based on your feedback, but at this point I think the evidence is pretty clear that your reservations are unfounded. You may not care about this compatibility feature, but please consider other users.

**Comment by i30817** [comment]
The simple solution is to remove the roms with headers from the database, add the roms hashes without the header and skip the header when calculating.

This is actually what no-intro pushes because their dat doesn't have the header iirc. For hacks, i have a collection of hacks and a tool to automate a dat creation that i can modify to skip the nes header on the output... it's not exactly all that hard.

**Comment by rzumer** [comment]
> 
> The simple solution is to remove the roms with headers from the database, add the roms hashes without the header and skip the header when calculating.

That is the ultimate goal, but there are considerable difficulties involved in deploying it at a large scale. A client-side workaround gives the other end the flexibility to develop the tools necessary to get it done properly and deploy compatibility updates for all clients, and besides some nebulous and unfounded concerns brought up earlier, the solution I propose is adequate for that purpose.

It was also suggested to me that instead of replacing the database contents, both "old" and "new" hashes generated using different methods should coexist, which also ignores the problems that this would generate with regards to maintenance and identification. I understand that not everyone is familiar with the data dependencies within the entire system, but if it were that easy of an issue to solve at the root, it would have been done a long time ago.

Either way, when (if) the back-end supports those full content hashes later on, the headerless method introduced in this PR will never trigger on titles that exist in the database, as they will be detected via the generic MD5 routine, and will be trivial to patch out while making the necessary changes to handle full content hashing in headered files.

**Comment by leiradel** [comment]
@i30817 yes, we at Retro Achievements will be adding the plain hashes to the database, we're just discussing some details like leaving the old hashes there or not. The database was made to support multiple hashes per game, so it won't be a problem if we have to.

We have a complete set of NES ROMs with headers, so this is something that we can update very quickly once the details are ironed out.

So we at libretro (I code for both projects) won't add this scheme to RetroArch. Even though it works fine, it can make many HTTP calls and we have many concerns about that.

**Comment by rzumer** [comment]
As mentioned elsewhere, I would have no problem with a planned and thought-out back-end solution as an immediate replacement to this PR, but far from being ready, not much thought has even been put into it: there is no issue up on the related back-end project, no open discussion with database maintainers, and the only estimate given for a fix is "months". There are other immediate priorities on both projects, as indicated by the fact that you suggested I do the back-end work myself.

Meanwhile, there is a regression in the client, and there is a fix for it. I reiterate my offer to eliminate your unlikely concerns by further restricting the maximum chunk amount and still maintain some partial compatibility in the meantime.

**Comment by rzumer** [comment]
Fixed server-side as far as I can tell.

**Pull request closed without merging**
