### PR TITLE
Fix input state combos and empty binds

### LINKED ISSUE #16215: Holding R3 not input from any other button
Hello.
Thanks for reading my topic.

Ubuntu 20.04.6 and PS4 DS4 Controller.
In recent version 1.17 has an issue in inputs.
If input autoconfig is enabled so the R3 is mapped to R3.
The problem is if holding R3 not any input from other buttons and dpad ir R3 is being mapped to the controller R3.
I use R3 for hotkey fast forward.
The temporary solution is edit the retroarch.cfg and use an high value for button removing the auto map.
input_player1_r3_btn = "99"

Have an nice day.

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

Better handling for preventing `RETROK_UNKNOWN` triggering hotkeys and binds, since current ugly band-aid has serious side effects.

## Related Issues

Closes #16215

## Related Pull Requests

#16225

### CODE REVIEW

**Comment by Augusto7743** [comment]
Hello.
That PR was added in Retroarch ? If using current build 2024-02-14 has that PR ?

**Comment by hizzlekizzle** [comment]
it can take a few hours to filter down, and there's still caching to worry about. If it's still giving you problems, maybe wait until the 2/15 build to be sure.

**Comment by Immersion95** [comment]
The combos for invoking the menu doesn't work anymore since this PR. The only ones working are Holding Start or Select.

**Comment by sonninnos** [comment]
I only found issues with L2 and R2..

**Comment by Immersion95** [comment]
> I only found issues with L2 and R2..

L3 + R3 also, maybe it's because I'm using Steam Input.

**Comment by sonninnos** [comment]
The result seems to depend on the existence of the keyboard bind of the specific button. So no keyboard bind means the press is ignored even if autoconf bind exists. In other words: badly broken.

**Comment by Augusto7743** [comment]
Immersion95 are correct. version 1.17 are with errors in inputs.
Please see my comment in
https://github.com/libretro/RetroArch/issues/16215#issuecomment-1962182952

**Comment by sonninnos** [comment]
But it is already fixed.

**Comment by Augusto7743** [comment]
Yes .. the error in L3 and R3 is fixed, but has another errors in inputs in version 1.17

**Pull request merged**
