### PR TITLE
Segregate language (ja)

### PR DESCRIPTION
**Pull request by lasers**

### CODE REVIEW

**Comment by twinaphex** [comment]
Sorry but I don't see what you're doing here.

What I was asking for was to make sure that in every .h language file, every message is in the EXACT SAME ORDER. That means, that if 'MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_DATABASE_INFO is at the bottom of the list, then it should be in EVERY language file, from Japanese to English to German, etc.

Just dropping in random labels somewhere creates a huge maintenance hazard for us.

I'm going to close this. I hope you understand now what I want.

**Comment by lasers** [comment]
I place them in the organized list (CHEEVOS-related). In the future, I'll place them all at the bottom as you're asking me to... Instead of doing couple lines, I thought this would help a Japanese translator because I put all `INCOMING MESSAGES TO BE TRANSLATED` at the bottom.

**Comment by twinaphex** [comment]
No, that is wrong.

Any 'new' enum that you add has to be added to the bottom. Re-read what I said. I said every single enum label needs to be ordered the exact SAME way in EVERY file.

**Comment by lasers** [comment]
_Note:_ In this one, I plucked out 214~ English strings. I later found two more... It's all at bottom. I'm more than happy to put them all back using `sort` after the translation has been completed.

**Pull request closed without merging**
