### PR TITLE
(Menu) Add more XMB Icons

### PR DESCRIPTION
**Pull request by alfrix**
This will need new assets, I've made the monochrome ones and monochrome inverted. 
[Menu Icons #220](https://github.com/libretro/retroarch-assets/pull/220)
Help or input would be appreciated.
screenshot_20180812_185728
screenshot_20180812_185824
screenshot_20180812_185901
screenshot_20180812_185958
screenshot_20180812_190029

### CODE REVIEW

**Comment by twinaphex** [comment]
Yes, I agree this is an improvement.

**Comment by twinaphex** [comment]
My only concern is potential GPU RAM requirements, but since it's just 8 extra icons, I think it's probably not too severe. And we could always add a low-memory mode later on where some of these icons could be disabled if so necessary.

**Comment by twinaphex** [comment]
By all means continue though. I think it could potentially solve a lot of people's gripes with the current XMB UI as it is by making people able to visually identify certain options instead of just having to rely on text instead.

**Comment by alfrix** [comment]
Now at 21 new icons, less than 100kb total, i'm reusing some existing icons where i can

**Comment by Ryunam** [comment]
A few months ago I had thought of actually attempting this same project, but I got really busy in the meantime and I couldn't get around to creating anything tangible. I really love the idea and your execution!

**Comment by alfrix** [comment]
@baxysquare probably want to update your themes, don't worry, it will not show black boxes because i disabled the extra icon support until explicitly enabled

**Comment by baxysquare** [comment]
Thanks for the heads up @alfrix.  I'll add it to my to-do list.

**Comment by Tatsuya79** [comment]
That's nice, seems to work fine here!
You can add "Dot-art" theme to the supported list as I'm going to push that shortly (using the new monochrome icons you made).

**Comment by alfrix** [comment]
> I noticed there's a single new icon in the shader menu for "load preset" for some reason.

Good catch, i'll remove it

**Comment by alfrix** [comment]
It should be ready now
@RobLoach i cannot remove the wip label

**Comment by twinaphex** [comment]
Let me know if this is fit to be merged @Tatsuya79 . If so, I will do it.

**Comment by Tatsuya79** [comment]
Yes, it's rdy alongside those 2:

https://github.com/libretro/retroarch-assets/pull/220

https://github.com/libretro/retroarch-assets/pull/221

**Pull request merged**
