### PR TITLE
Fix frameskipping with duped frames

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

Fix for fast-forward frameskipping when core is sending dupe/NULL frames, sponsored by jdgleaver.

### CODE REVIEW

**Comment by realnc** [comment]
This fixes the broken fast-forward in dosbox-core. :+1:

**Review by loki666 — COMMENTED** [review]
`&& !!data` why not? not?

**Comment by realnc** [comment]
> `&& !!data` why not? not?

`!!data` is a shorthand for `(bool)data`. I don't know why you'd do that in C code though (it's more useful in C++ to avoid compiler warnings about comparing pointers and bools).

**Comment by loki666** [comment]
Ok...
Why not simply write it as `data != 0` then ?
It looks like a typo to me.

**Comment by realnc** [comment]
> Ok... Why not simply write it as `data != 0` then ? It looks like a typo to me.

Because it's a known idiom used by many.

**Pull request merged**
