### PR TITLE
travis: Test android builds. 

### PR DESCRIPTION
**Pull request by orbea**
## Description

I'm trying this out and it seems the only way I can test travis is in PRs...

https://docs.travis-ci.com/user/languages/android/

### CODE REVIEW

**Comment by webgeek1234** [comment]
The android build system has changed. Need to cd to phoenix and run the gradle wrapper.
https://github.com/libretro/libretro-super/blob/master/libretro-buildbot-recipe.sh#L1063

Don't need the play service dependency anymore either. And it's now targeting SDK 28.

**Comment by orbea** [comment]
Thanks for pointing that out, I forgot to fetch recent changes in my copy of libretro-super...

**Comment by webgeek1234** [comment]
Looks like there's issues with Travis and sdkmanager licenses. The recommended fix I found looks like adding the following to the script.

before_install:
  - yes | sdkmanager "platforms;android-28 ndk-build"

**Comment by orbea** [comment]
Thanks for the tip, I guessed that adding `extra-google-m2repository` might work, but I'll give  your idea a try next.

**Comment by orbea** [comment]
That idea didn't work either.
```
$ yes | sdkmanager "platforms;android-28 ndk-build"
Warning: File /home/travis/.android/repositories.cfg could not be loaded.
Error: Failed to find package platforms;android-28 ndk-build
The command "yes | sdkmanager "platforms;android-28 ndk-build"" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by webgeek1234** [comment]
Hmm. I wonder if it has to run each component separately. platform;android-28 is one and ndk-build is a second. Maybe try putting duplicating the command once for each. Keep the quotes, they were in the examples I found.

**Comment by orbea** [comment]
I'm trying stuff from the example in https://github.com/googlesamples/android-ndk/blob/master/.travis.yml. Not sure which exact components we need for android though.

**Comment by orbea** [comment]
@webgeek1234 

It seems to be working now, but the android travis build took 35 minutes. Is there anything that can be done to speed this up? Do you see any other issues with this PR?

Also this warning seems interesting, but not relevant to this PR.
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by webgeek1234** [comment]
By default, the gradle build script builds three different apks. For build testing purposes, only normal should be needed to cover all arch's. So, try:
./gradlew assembleNormalRelease
Should finish in a tad over a third of your listed time.

**Comment by orbea** [comment]
I'm not sure I fully understand, what exactly is the difference in building 3 different apks and just building all the different arches? I can assume that `assembleNormalRelease` should adequately test all of the different android builds?

**Comment by webgeek1234** [comment]
So, the three different apks are:

aarch64 - contains aarch64 and x86_64
normal - contains aarch64, armv7, x86, and x86_64
ra32 - contains armv7 and x86

So, normal builds all archs and covers all the paths that a build test needs.

**Comment by twinaphex** [comment]
Looks like the test succeeded.

Should we merge this?

**Comment by orbea** [comment]
The new build took 18 minutes, I suppose 18 minutes is not so bad for 4 different android architectures.

@twinaphex I think this is ready and that 18 minutes is okay to make sure android builds are not broken before merging.

**Comment by twinaphex** [comment]
Cool. Let's go for it then. And thanks for figuring all this out together with @webgeek1234 .

**Comment by orbea** [comment]
@webgeek1234 I concur that your help was invaluable in getting this PR working so fast, thanks a lot!

**Pull request merged**
