### PR TITLE
Adjust cheevos addresses for SNES when using the MMAP interface; alwa…

### PR DESCRIPTION
**Pull request by leiradel**
…ys show the retro_get_memory values on the log; use strncpy instead of strlcpy

### CODE REVIEW

**Comment by twinaphex** [comment]
Don't use strncpy. Use strlcpy.

**Comment by leiradel** [comment]
I did and it introduced a bug, so I rolled it back.

**Comment by twinaphex** [comment]
I'm not going to merge that.

strncpy is banned from RetroArch, it will have to use strlcpy. No strcpy either.

**Comment by leiradel** [comment]
"Best practices" in the code base now? We should move to C++ and STL.

My use of strlcpy is perfectly safe, but if changing perfectly fine code for something else is what it takes to get it merged I'll do it later.

**Comment by Alcaro** [comment]
Ew, STL is ugly.

strncpy is not only harder to get right (I don't doubt your ability to get it right, but less work is less work), but also a performance issue, as it zeroes the entire buffer even if it only copies a few bytes.

**Comment by twinaphex** [comment]
No C++ and STL ever.

You know perfectly well my stance on this, and that is not subject to change. Let's not become unreasonable now.

**Comment by leiradel** [comment]
I'm not really asking for C++ and STL adoption, I like C++ for the (few) good things and hate STL.

**Comment by leiradel** [comment]
Done. Sorry for overreacting.

**Comment by twinaphex** [comment]
No problem, thanks for the change.

**Comment by Alcaro** [comment]
> \+   strlcpy(memaddr, memaddr_ud->string, sizeof(memaddr));
> \+   
> \+   if (memaddr_ud->length < sizeof(memaddr))
> \+      memaddr[memaddr_ud->length] = 0;

That part isn't necessary, strlcpy always terminates.

> \-      strlcpy(value, ud.value, length);
> \+      strlcpy(value, ud.value, ud.length + 1);

Pretty sure the old one is more correct.

**Comment by leiradel** [comment]
> That part isn't necessary, strlcpy always terminates.

`memaddr_ud->string` is not null-terminated, its length is given by `memaddr_ud->length`.

> Pretty sure the old one is more correct.

`length` is the size of `value`, and the `if` guarantees that `ud.length` is less than `length`. It has to be that way to have a correctly null-terminated string in value, because `ud.value` is not null-terminated.

Actually, I'll rewrite the `memaddr` thing to be more like the second and avoid copying bytes unnecessarily.

**Pull request merged**
