### PR TITLE
Request write access to external storage on Android 6.0+

### PR DESCRIPTION
**Pull request by Qard**
This is a cleanup of #4315 with some various compilation error fixes.

NOTE: I tested this on my 5.x device and it runs fine. I don't have a 6.x device handy at the moment to test the programmatic part works as expected though.

### CODE REVIEW

**Comment by twinaphex** [comment]
@fr500 Can you test this out since the OP has not had a chance yet to test it on a 6.x device?

**Comment by fr500** [comment]
I don't have any non-rooted non-sdfixed device

**Comment by autofire372** [comment]
My Galaxy S5 fits those categories. Can I test this?

**Comment by fr500** [comment]
the next _staging build should have the changes included

**Comment by autofire372** [comment]
I'll keep an eye out, then.

**Comment by autofire372** [comment]
Unfortunately, this doesn't work. RetroArch still cannot write to external storage, despite requesting the necesarry permission during the install process.

**Comment by Qard** [comment]
It should also pop up a dialog of some sort, requesting access when the main menu is opened. I'll take another look at it soon and see what I can figure out.

**Comment by fr500** [comment]
Did you figure it out?

**Comment by Qard** [comment]
Not yet, no. I spent about half a day on it, but it seems the problem is more complicated. As far as I can tell, this method would only grant access to specific standard Android folders (Documents, Downloads, Pictures, etc.) and each has to be specifically requested. It'd also change how file access has to happen, which would require changes to libretro-common too, not just the Android project.

I found another possible option for just requesting access to an SD card root, but I need to take the time to look into it more. Maybe this weekend?

**Comment by twinaphex** [comment]
Hi there,

I hope you will manage to make some breakthroughs soon since this issue is still a major issue for people on Android.

**Comment by Qard** [comment]
Sadly, as far as I can tell, it seems to be impossible without some major rearchitecting of libretro-common. I don't think I'm experienced enough with Android and the RetroArch codebase to be able to get any further with this. 😞 

It seems like *all* write access to the filesystem has to go through the `DocumentProvider` interfaces which uses `DownloadsProvider` if accessing the downloads folder, `MediaProvider` if accessing Audio, Video or Images folders, and `ExternalStorageProvider` if accessing anywhere else on the SD card. (except /Android, which is just plain inaccessible)

None of the C standard library filesystem I/O is usable at all. All the save state stuff and config file management would have to move out of C and delegate to Java as the `DocumentProvider` interfaces don't even appear to exist in JNI...it'd take some serious effort to make this work.

**Comment by fr500** [comment]
Are you sure it's not enough to grant the permission?
I'm pretty sure it should work

**Comment by Qard** [comment]
The XML permission doesn't work at all anymore. With the Android M runtime permissions, you can request access to a limited set of standard paths (Downloads, Pictures, Videos), and must request each separately. With DocumentProvider, you can request display a system UI to select the SD card root, granting write access to anywhere in that path and nested paths, but it only supports access via the Storage Access Framework, which requires using the DocumentProvider interfaces--not even the Java File API works.

**Comment by fr500** [comment]
Of course, but I don't think the external storage permission works like that, it gives you access to the whole SD card.

It has to be asked on runtime though.
I tried this PR and it never asked, that was the problem I had.

**Comment by Qard** [comment]
Maybe I'm misunderstanding something? I read through a bunch of docs on it and tried whatever I could, but I'm not really an Android developer, so I don't have a ton of experience here. 😞

**Comment by fr500** [comment]
I mean, I never got the prompt for permissions

**Comment by xTMODx** [comment]
`It seems like all write access to the filesystem has to go through the DocumentProvider interfaces which uses DownloadsProvider if accessing the downloads folder, MediaProvider if accessing Audio, Video or Images folders, and ExternalStorageProvider if accessing anywhere else on the SD card. (except /Android, which is just plain inaccessible)`

Don't get confused, the internal storage is called "sd card" sometimes and this is about the external sd card which is removable. Or did you mean the removable storage?

**Pull request closed without merging**
