### PR TITLE
Enable tinyalsa for the RG350

### PR DESCRIPTION
**Pull request by john-parton**
Enables the TinyAlsa driver for the RG350.

@jdgleaver Is TinyAlsa or OpenAL better on these devices?

I can add a conditional so that OpenAL is still the default if that's preferred.

### Testing

Tested on my RG350M and it works correctly as far as I can tell.

### CODE REVIEW

**Comment by jdgleaver** [comment]
It's great to have support for more drivers, but again, we don't want to change the default setting without due care and attention. If you implement the default setting as I asked here: https://github.com/libretro/RetroArch/pull/12568#issuecomment-868995203, this won't be a problem.

I do not know how well TinyAlsa performs on OpenDIngux. If you want to propose changing the default setting to TinyAlsa, then you would need to do the legwork:

- Actually profile the performance difference between OpenAL and TinyAlsa
- Verify comprehensively that there are no regressions related to RA's frameskip implementation (which is heavily dependent upon the implementation of the audio driver itself)

As you can imagine, this is a time consuming endeavour! To minimise pain, it is therefore best to just enable TinyAlsa *without* making it the default, and then users can compare the different drivers at their leisure. If we get some stats, *then* we can make a decision about changing defaults :)

**Comment by john-parton** [comment]
Okay, I'll remember the "don't override the default" rule for future pull requests and I'll update this one soon.

**Comment by john-parton** [comment]
Added `&& !defined(DINGUX)` so that it skips tinyalsa as a default (which means OpenAL will continue to be the default.)

I tested several games, and the tinyalsa backend sounds worse. There's definitely more "crackle."

I absolutely do not think we should use tinyalsa as the default, but I think it makes sense to have it as an option for testing purposes.

**Comment by john-parton** [comment]
Rebased and force pushed based on the feedback you gave on the alsa branch.

Works the same.

Fixed whitespace issue

**Comment by jdgleaver** [comment]
> I absolutely do not think we should use tinyalsa as the default, but I think it makes sense to have it as an option for testing purposes.

Yep, I agree with you 100% on both counts.

The change to `Makefile.rg350_odbeta` is fine, but you'll end up with merge conflicts in `configuration.c` - so basically, as soon as #12568 gets merged, you'll need to rebase this PR against master, and then we can merge this one without hesitation :)

**Comment by john-parton** [comment]
@jdgleaver Rebased. Now it's a one line change.

**Comment by jdgleaver** [comment]
Great, thanks!

@twinaphex This is ready for merging now :)

**Comment by john-parton** [comment]
@twinaphex Just a bump on this. I think we're ready to merge.

**Pull request merged**
