### PR TITLE
Runahead system

### PR DESCRIPTION
**Pull request by Dwedit**
## Description

This is the run-ahead system created to reduce input lag, ported from C++ to C.

**Files changed:**
Menu and settings related files:
config.def.h
configuration.c
configuration.h
intl/msg_hash_lbl.h
intl/msg_hash_us.h
menu/cbs/menu_cbs_sublabel.c
menu/menu_displaylist.c
menu/menu_setting.c
msg_hash.h

Changes to allow using a secondary core:
core_impl.c: Makes calls to remember controller_port_device changes, and make a copy of the load_info struct
dynamic.c: Symbol loading code changed to allow passing in the DLL file path and handle to write back into, also stores the core_type it loaded in order to reject cores that are not plain

Changes made to allow running ahead:
retroarch.c: The call to core_run now goes to run_ahead if the feature is enabled.

Brief summary of new code:
copy_load_info.c exists just to make a copy of the load_info struct, so when the secondary core needs to create itself, it can get to the load_info.  This may contain a const cast that may need to be removed.
dirty_input.c is responsible for checking if the input has changed since the last frame, and setting input as dirty.  It also hooks onto Reset, and Load State to have those set input as dirty as well.
mem_util.c is just some functions for memory allocation to make strings easier
secondary_core.c
mylist.c is a list data structure for pointers where you can set the constructor and destructor to functions.  It will automtically call them to create new elements and clean up existing elements when destroying the list.
secondary_core.c is the file responsible for creating a secondary core, including copying the DLL to a temporary file, requesting loading the DLL, then setting some callbacks within the newly created core.  It also exports the run, load state, and destroy functions for the secondary core.
runahead.c is the code responsible for doing the save and load states necessary for the runahead system, and is the main entry point for that feature.  It also hooks the Unload Core and Destroy Core events to clean itself up.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
error on compilation

```
retroarch.c:121:10: fatal error: runahead/run_ahead.h: No such file or directory
 #include "runahead/run_ahead.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:171: obj-unix/release/retroarch.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Tatsuya79** [comment]
Compiling on win7 x64 with Mingw64 gcc 7.3, got that error at the end:
```
obj-unix/release/core_impl.o:core_impl.c:(.text+0x3b5): undefined reference to `remember_controller_port_device'
obj-unix/release/core_impl.o:core_impl.c:(.text+0x419): undefined reference to `set_load_content_info'
obj-unix/release/retroarch.o:retroarch.c:(.text+0x5198): undefined reference to `run_ahead'
obj-unix/release/dynamic.o:dynamic.c:(.text+0x2bb3): undefined reference to `set_last_core_type'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:166: retroarch] Error 1
```

**Comment by Tatsuya79** [comment]
New error:
```
CC intl/msg_hash_eo.c
runahead/run_ahead.c:39:13: error: static declaration of 'runahead_destroy' follows non-static declaration
 static void runahead_destroy(void);
             ^~~~~~~~~~~~~~~~
runahead/run_ahead.c:37:6: note: previous declaration of 'runahead_destroy' was here
 void runahead_destroy(void);
      ^~~~~~~~~~~~~~~~
runahead/run_ahead.c:86:13: warning: 'runahead_save_state_list_rotate' defined but not used [-Wunused-function]
 static void runahead_save_state_list_rotate(void)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:169: obj-unix/release/runahead/run_ahead.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Tatsuya79** [comment]
Thanks, it compiled fine with just that warning left:
```
runahead/run_ahead.c:83:13: warning: 'runahead_save_state_list_rotate' defined but not used [-Wunused-function]
 static void runahead_save_state_list_rotate(void)
```
Read ahead options seem to be working fine from a quick test.

**Comment by Dwedit** [comment]
It probably needs some testing, since it was not heavily tested after being ported from C++ to C.

**Comment by twinaphex** [comment]
Is unlink_utf8 even used?

I am thinking that this might be unimplemented on several console SDKs, so if we don't absolutely need this, could we go without it?

**Comment by twinaphex** [comment]
The rest of the code looks fine to me, so barring any last objections from anybody, I think that part is good to go.

**Comment by Dwedit** [comment]
unlink_utf8 is used to delete the temporary copy of the core after it is unloaded.

**Comment by twinaphex** [comment]
Can you put HAVE_RUNAHEAD ifdefs around this code so that it could still be baked out for specific targets? I imagine that for certain platform targets we won't be needing this, and since these are RAM-strapped platforms, compiling in a lot of source files would matter in terms of binary size. So it is always useful to have options to reduce the size of a RetroArch binary.

Apart from that, I am concerned about the portability of 'unlink' in general. Those are my last two concerns. Apart from that, I consider this fit for merging.

**Comment by twinaphex** [comment]
Alright, I'll take the gamble. I'll manually add in the ifdefs after merging this and assume unlink won't be the portability hazard that I fear it is. Thanks for your contribution.

**Comment by Dwedit** [comment]
The only portability hazard is #including the header file on systems without <unistd.h> which also support dynamic linking,

**Comment by twinaphex** [comment]
Added the HAVE_RUNAHEAD ifdef. Enabled this by default for PC targets.

https://github.com/libretro/RetroArch/commit/c041470bb09278ed4608f24ef0aeb7bcbcb12a00

@Dwedit For which platform would runahead also be usable? Android, iOS?

**Comment by twinaphex** [comment]
@Dwedit This is a portability issue right now on OSX -

https://github.com/libretro/RetroArch/blob/master/runahead/secondary_core.c#L164

Why do we need to roll our own file reading handling code here? Is it not possible to simply peruse the existing filestream/VFS interfaces here? It would save on a lot of boilerplate code and it would also avoid recurring portability issues like this, since those issues have already been taken care of in the existing file stream interfaces in libretro-common.

**Comment by twinaphex** [comment]
Also some Coverity warnings that it would be nice to see fixed -

https://hastebin.com/bozuvijifi.md

**Comment by Dwedit** [comment]
The run ahead feature *without* the secondary core should work on all platforms, it's just that it needs good performance to actually work well, and needs support from the core for glitch-free audio.  Memory fragmentation could be a problem on lower spec platforms though.
I'd love to see this feature running on the Wii.

With the secondary core, it would need dynamic linking.  I wrote the code with Windows and Unix-like platforms in mind, so Android with its ".so" files should be okay too.  I only tested it on Windows though, it could use some more testing on non-windows platforms.

Might need to hide the UI option for using the secondary core on platforms without dynamic linking.


As for the extra file handling code, I just had issues locating code in a big codebase.  Using griffin in MSVC breaks the IDE's ability to find functions in the project, since it doesn't handle #include ".c" files well.  You need to use 'Find in Dependencies', which also ends up searching all the system library header files too.

I could try taking all the added file code out and using the other Retroarch code.

**Comment by twinaphex** [comment]
Yeah, I think the Wii and Wii U platforms don't use dynamic loadable cores though, the cores get linked statically to RetroArch, so each 'core' is its own standalone binary executable.

**Pull request merged**
