### PR TITLE
First version of menu widgets (gl only)

### PR DESCRIPTION
**Pull request by natinusala**
# Menu widgets

* All menu widgets related code is under the `HAVE_MENU_WIDGETS` define 
    * Use `./configure --enable-menu_widgets` on desktop to enable them
* Widgets will be enabled if they are built (obviously) and if the current video driver supports them
    * They are only enabled for GL for now, adding them to other graphics drivers should be trivial (change the `frame` function to render the menu pass even when running content)
* All widgets scale according to the `Notification Size` setting (size of the font, default at ~30px)
* The font used is `Notification Font` setting if any > ozone font > default bitmap font
* Menu widgets specific assets and overall design were made by Krispy (see `menu_widgets/README.md` in retroarch-assets)
    * widgets use xmb monochrome for regular icons

* List of all widgets, with (possibly outdated) previews:
    * **message queue**: yellow messages have been replaced by stacking notifications (with icons and color codes)
        * [preview](https://twitter.com/natinusala/status/1085260327351173120) (replace the stupid Undertale meme by an actual notification)
    * **task progress**: task progress can now be seen via a sticky notification (with progress bar)
        * [preview](https://twitter.com/natinusala/status/1085600188721491968)
    * **screenshot notification**: flashing animation followed by a notification containing a thumbnail of the screenshot and the file name
        * [preview](https://twitter.com/natinusala/status/1068117950232739840)
    * **volume bar**: shows muted or current volume in db or percent (100% being +0db)
        * [preview](https://twitter.com/natinusala/status/1066388122781519874)
    * **run content animation**: with content name and playlist icon
        * [preview](https://cdn.discordapp.com/attachments/432657353775513631/536969376104972288/Project_2.mp4)
    * **fps counter**: top-right counter (separated from the notifications)
        * [preview](https://twitter.com/natinusala/status/1065950221245526016)
    * **status icons** on the top-right corner of the screen, showing:
        * pause
        * fast-forward
        * rewind
        * slow-motion
* Planned menu widgets:
    * **Achievements** notifications with icon (see the bounty)
    * **Netplay** lobby join prompt w/ Discord integration
    
# Changes to libretro-common

**Those changes will break static platforms until libretro-common is synced on all of them.**

* task queue changes:
    * tasks now have two new members: 
        * a unique identifier (given through `task_get_next_ident`)
        * a frontend userdata pointer, which can be anything (I use it for sticky progress notifications)
    * new function: `retro_task_t *task_init()`, which allocates a new task and gives it a new unique identifier
    * `retro_task_callback_t` now has an additional task parameter `retro_task_t *task`
    * `retro_task_queue_msg_t` now has an additional task parameter `retro_task_t *task`
    * `runloop_task_msg_queue_push`, a new function, is now used as the task message queue implementation (instead of `runloop_msg_queue_push`)
* message queue changes:
    * new enums: `message_queue_icon`, `message_queue_category`
    * struct `queue_elem` changed, added title, icon and category members
    * `msg_queue_push` signature changed, title, icon and category parameters were added
        * this changes `runloop_msg_queue_push` aswell
* `file_list_insert` was added to the file list data structure
    * `file_list_prepend` was modified to use `file_list_insert`

# Changes to RetroArch

* `unsigned *width` and `unsigned *height` parameters have been added to `menu_display_reset_textures_list` - if set to anything but `NULL`, the function will fill their value with the image width and height when loading it
* menu widgets are initialized in `drivers_init`, before the menu, and deinitialized in `RARCH_DRIVER_CTL_DEINIT`
* graphics drivers now call `menu_widgets_frame` in their `frame` function (only implemented in gl for now)
* `bool menu_widgets_enabled(void *data)` was added to the graphics drivers, along with `bool video_driver_has_widgets(void)` (enables or disables widgets for that driver)
* runloop now calls `menu_widgets_iterate` and `menu_animation_update` every frame
* the file download task now passes its frontend userdata when spawning a decompress task (to keep the same notification)
* menu animations has been improved
    * the (ideal) delta time has been removed and animations now use milliseconds as a unit (instead of 60th of seconds)
        * this was made to keep consistent speeds in animations regardless of the internal running speed of RetroArch (some cores run faster than others, or faster than the menu)
    * menu animations are now updated even when the menu is not alive (through `menu_animation_update`)
    * tickers have been modified to take those new changes into account, with a new function `menu_animation_get_ticker_time` for `ticker.idx`
* menu driver changes:
    * ozone now uses the monochrome XMB assets
    * `bool get_load_content_animation_data(void *userdata, menu_texture_item *icon, char **playlist_name)` has been added to menu drivers so that they can provide the current playlist icon and name to the menu widgets for the load content animation
    * some display macros have been moved from the ozone files to `menu_driver.h`
    * text is not rendered if the color alpha is 0 (fixes a flickering bug)
* The `Switch Controller Configured on port #X` message has been removed from the libnx platform (it spams and it's useless). Other platforms might want this fix too (Wii U, 3DS, Vita... ?)

# What remains to be done / known issues

See #8198

# Associated PR to retroarch-assets

https://github.com/libretro/retroarch-assets/pull/290

### CODE REVIEW

**Comment by orbea** [comment]
@twinaphex You merged this way too soon...it broke everything other than windows.

**Comment by twinaphex** [comment]
I can fix that in subsequent commits, no big deal.

**Comment by orbea** [comment]
It is a big deal as it makes bisecting this range of commits more difficult and its not fair for contributors to have to go around fixing up other contributors work all the time...

**Comment by twinaphex** [comment]
Calm down, you are getting too aggravated over something that is relatively inconsequential. There is no problem here and we are already onto fixing it. More time is spent here arguing than actually fixing this, so let's rather do the fixing instead of losing our cool here over stupid stuff.

**Comment by twinaphex** [comment]
@orbea I believe the issues are resolved by now. Let me know in case issues remain.

**Comment by twinaphex** [comment]
According to @hizzlekizzle , there are also issues now on Android.

This is way too much instability to be introducing, so I will have to revert this menu widgets PR for now.

What we have to do is start from scratch with this menu widgets PR and this time be way more careful, test on all important platforms during the programming process, and make less intrusive changes.

**Comment by twinaphex** [comment]
@natinusala Please note, PLEASE do not take this the wrong way. I still want your menu widgets, I think it is awesome.

I want to work with you and test with you to do this reimplementation, and with a bit of luck we can do this in less than a week. I just want to get back to a stable state before we do this reimplementation. Please understand this decision, and please also understand that it is not your fault or anybody else. We simply will do it better and right with the reimplementation this time, and this can be an opportunity to arrive at a better solution.

**Comment by orbea** [comment]
I'm also looking forward to menu widgets, it'd just be nice if it can be introduced more carefully. :)

**Comment by twinaphex** [comment]
OK @natinusala , 

so here is what I did:

https://github.com/libretro/RetroArch/commit/7022786f3439e8b003acb20bad7c384f0f017ff9

in this commit I reverted the changes to menu widgets but left intact:
*  the changes to runloop_msg_queue_push
* the additions to msg_hash

menu_animation was reverted and menu_widgets.c/.h were made blank files.

https://github.com/libretro/RetroArch/commit/894f3b7aef0d4ac5f0a893c572b8ee8bc129d86c

In this commit I fixed a few signatures that I forgot.

https://github.com/libretro/RetroArch/commit/386657a36660c245edcfff8921f4eeaf1d6cb45f

In this commit I re-committed the task queue changes, tested it on OSX, and can confirm there are no issues anymore as of this moment.

So we can confirm by this that the major regressive parts are in the menu animation code / delta timing. Both menu_input.c and menu_animation were updated.

It looks to me like the 'animation update' routine for OSX/Android might be out of sync leading to all these visual anomalies.

Where we should go from here, is that we should first make sure that any changes we make to menu_animation don't regress on the platforms we are testing (like Switch/Mac/PC). After we have done that, we can look at re-implementing the HAVE_MENU_WIDGETS parts again. I still left the menu_widgets_frame function calls inside the video driver files.

**Comment by twinaphex** [comment]
Added back get_load_content_animation_data, a function callback of the menu driver.

https://github.com/libretro/RetroArch/commit/59ded50d5924075499cd74343091b7e54e64294c

**Comment by twinaphex** [comment]
BTW - the switch to compile with is also still there (--enable-menu_widgets), so all we need to do now is to reintegrate it again and this time make sure OSX/Android keep working properly.

**Comment by orbea** [comment]
@natinusala and @twinaphex 

The new cheevos is still broken.
```
./configure --enable-new_cheevos --enable-lua && make
```
```
cheevos-new/cheevos.c: In function ‘cheevos_award_task_softcore’:
cheevos-new/cheevos.c:445:48: warning: passing argument 4 of ‘task_push_http_transfer’ from incompatible pointer type [-Wincompatible-pointer-types]
    task_push_http_transfer(buffer, true, NULL, cheevos_award_task_softcore, user_data);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from cheevos-new/cheevos.c:62:
cheevos-new/../tasks/tasks_internal.h:40:7: note: expected ‘retro_task_callback_t’ {aka ‘void (*)(struct retro_task *, void *, void *, const char *)’} but argument is of type ‘void (*)(void *, void *, const char *)’
 void *task_push_http_transfer(const char *url, bool mute, const char *type,
       ^~~~~~~~~~~~~~~~~~~~~~~
cheevos-new/cheevos.c: In function ‘cheevos_award_task_hardcore’:
cheevos-new/cheevos.c:476:48: warning: passing argument 4 of ‘task_push_http_transfer’ from incompatible pointer type [-Wincompatible-pointer-types]
    task_push_http_transfer(buffer, true, NULL, cheevos_award_task_hardcore, user_data);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from cheevos-new/cheevos.c:62:
cheevos-new/../tasks/tasks_internal.h:40:7: note: expected ‘retro_task_callback_t’ {aka ‘void (*)(struct retro_task *, void *, void *, const char *)’} but argument is of type ‘void (*)(void *, void *, const char *)’
 void *task_push_http_transfer(const char *url, bool mute, const char *type,
       ^~~~~~~~~~~~~~~~~~~~~~~
cheevos-new/cheevos.c: In function ‘cheevos_lboard_submit_task’:
cheevos-new/cheevos.c:621:48: warning: passing argument 4 of ‘task_push_http_transfer’ from incompatible pointer type [-Wincompatible-pointer-types]
    task_push_http_transfer(buffer, true, NULL, cheevos_lboard_submit_task, user_data);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from cheevos-new/cheevos.c:62:
cheevos-new/../tasks/tasks_internal.h:40:7: note: expected ‘retro_task_callback_t’ {aka ‘void (*)(struct retro_task *, void *, void *, const char *)’} but argument is of type ‘void (*)(void *, void *, const char *)’
 void *task_push_http_transfer(const char *url, bool mute, const char *type,
       ^~~~~~~~~~~~~~~~~~~~~~~
cheevos-new/cheevos.c: In function ‘cheevos_test_leaderboards’:
cheevos-new/cheevos.c:676:13: error: too few arguments to function ‘runloop_msg_queue_push’
             runloop_msg_queue_push("Leaderboard attempt cancelled!",
             ^~~~~~~~~~~~~~~~~~~~~~
In file included from cheevos-new/cheevos.c:58:
cheevos-new/../retroarch.h:385:6: note: declared here
 void runloop_msg_queue_push(const char *msg,
      ^~~~~~~~~~~~~~~~~~~~~~
cheevos-new/cheevos.c: In function ‘cheevos_iterate’:
cheevos-new/cheevos.c:1356:10: error: too few arguments to function ‘runloop_msg_queue_push’
          runloop_msg_queue_push(
          ^~~~~~~~~~~~~~~~~~~~~~
In file included from cheevos-new/cheevos.c:58:
cheevos-new/../retroarch.h:385:6: note: declared here
 void runloop_msg_queue_push(const char *msg,
      ^~~~~~~~~~~~~~~~~~~~~~
cheevos-new/cheevos.c:1767:10: error: too few arguments to function ‘runloop_msg_queue_push’
          runloop_msg_queue_push(
          ^~~~~~~~~~~~~~~~~~~~~~
In file included from cheevos-new/cheevos.c:58:
cheevos-new/../retroarch.h:385:6: note: declared here
 void runloop_msg_queue_push(const char *msg,
      ^~~~~~~~~~~~~~~~~~~~~~
cheevos-new/cheevos.c:1770:10: error: too few arguments to function ‘runloop_msg_queue_push’
          runloop_msg_queue_push(
          ^~~~~~~~~~~~~~~~~~~~~~
In file included from cheevos-new/cheevos.c:58:
cheevos-new/../retroarch.h:385:6: note: declared here
 void runloop_msg_queue_push(const char *msg,
      ^~~~~~~~~~~~~~~~~~~~~~
CC deps/rcheevos/src/rcheevos/lboard.c
CC deps/rcheevos/src/rcheevos/alloc.c
make: *** [Makefile:201: obj-unix/release/cheevos-new/cheevos.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by natinusala** [comment]
I will fix it

**Comment by natinusala** [comment]
https://github.com/libretro/RetroArch/pull/8241

**Pull request merged**
