### PR TITLE
Add option to automatically backup cores when updating

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This is a follow-up to PR #10788. It adds the following new options under `Settings > Network > Updater`:

- `Backup Cores When Updating`: When enabled, a backup of any existing core will be created automatically whenever the core is updated via the `Online Updater`

- `Core Backup History Size`: Sets a limit on the number of automatic backups to create for each core. When this is exceeded, the oldest backup(s) will be be removed when creating a new one

This is basically a 'set and forget' option that allows easy rollback to a working system in the event that a core update introduces a regression.

Note: Automatic backups exist independently from manual ones:

- Manual backups will never be automatically removed

- A manual and automatic backup with the same CRC can be created (this means you can roll back to a working auto backup, then create a manual 'snapshot' that will never be removed as the `Core Backup History Size` is exceeded in the future)

- Automatic backups are identified in the menu by an `[Auto]` suffix - e.g.:

Screenshot_2020-06-15_17-08-22

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
This is really great. I think we might want to consider setting a default history size of 1 backup on desktop platforms, as complaints about "I updated and now my $whatever doesn't work. Where can I find the old core??" are very, very common.

**Comment by jdgleaver** [comment]
>  I think we might want to consider setting a default history size of 1 backup on desktop platforms

Yes, I'm inclined to agree! Since the backups are compressed, it shouldn't really harm disk IO either.

@twinaphex Do you agree with enabling this by default? On desktop, and maybe for Android too (since the average Android user would probably find it difficult to find and sideload old versions of cores...)

**Comment by twinaphex** [comment]
Fine, we can do this.

**Comment by Ryunam** [comment]
Thanks a lot for adding this backup functionality, @jdgleaver. Given that for the cores I mainly use the Updater, it's incredibly useful to have an automatic backup just in case I notice anything strange with the latest implementations.

**Comment by jdgleaver** [comment]
@Ryunam You're very welcome!

I've been hit by core regressions a couple of times on Android in the past (where it's a bit of a bother to manually download and install old versions), and automatic backups would have been handy ;)

(I'm currently adding the option to 'lock' specific cores, so they can't be updated accidentally - probably not as useful as backups, but people who want to use the 'update installed cores' option but still need a specific core version for arcade ROM sets - or who compile a few cores themselves with custom tweaks - might find it useful!)

**Pull request merged**
