### PR TITLE
Make favorites and image/music/video collections optional and non redundant

### PR DESCRIPTION
**Pull request by JuanVCS**
Moved settings a bit so they can be disabled just like when using the xmb menu driver.
Also removed some repeated instances mostly noticeable on rgui.

### CODE REVIEW

**Comment by RobLoach** [comment]
Isn't this in Settings -> User Interface -> Views?

screenshot at 2017-09-02 15-59-38

**Comment by JuanVCS** [comment]
Only for XMB

**Comment by FayneAldan** [comment]
Also, the code doesn't look like it would work for MaterialUI, but I might be wrong.

**Comment by JuanVCS** [comment]
I kinda agree on Collections taking a more central place, however this pr was just about removing redundant instances of items and enabling some toggles already existing on the xmb driver.

AFAIK it works fine with material ui as well but testing is very appreciated.

**Comment by alfrix** [comment]
I think you are tackling too many things at once, if you want to add favorites to the other guis go on, but i do not like the removal of those xmb entries.

**Comment by fr500** [comment]
I like this overall, the only thing is that the options should lose the xmb prefix

**Comment by meepingsnesroms** [comment]
I made a pull request today that does almost the same thing not knowing there already was one, we should try to get this merged, yesterday I removed all the xmb prefixes but thought it was too much and tried something else, I could do it again though if we merge this, it was not that hard.

**Comment by twinaphex** [comment]
@meepingsnesroms' PR is merged now.

@JuanVCS try to see if the current master/nightly does what you intended this PR to do. If satisfied, we can then close this PR.

**Comment by JuanVCS** [comment]
Seems to work well

**Pull request closed without merging**
