### PR TITLE
fix wrong udev devices order, fixes #9071

### LINKED ISSUE #9071: [Linux] [udev] incorrect order when devices > 9
###  Description

If the linux system have more than 9 event devices the order is incorrect, because linux doesn't use zero-leading to number devices and the algorithm expects them (or maybe isn't tested using a lots of devices). 

I made some test and I think you dont need qsort in udev_joypad.c if you use the udev foreach: udev_list_entry_foreach. I get the correct order and i don't need sort anything.

just this simple code works:
```
   ...
   udev_enumerate_scan_devices(enumerate);
   devs = udev_enumerate_get_list_entry(enumerate);

   udev_list_entry_foreach(item, devs)
   {
      const char         *name = udev_list_entry_get_name(item);
      struct udev_device  *dev = udev_device_new_from_syspath(udev_joypad_fd, name);
      const char      *devnode = udev_device_get_devnode(dev);

      if (devnode != NULL)
         udev_check_device(dev, devnode);
      udev_device_unref(dev);
   }
   ....
```

thanks!

### Actual behavior

Actually this is the order show in ra:
imagen

Then event device 10 is used as #0 device and device 9 is used as #1 device.

### Expected behavior

imagen

### Steps to reproduce the bug

1. init ra with enough devices, active logs and you get

```
[INFO] [udev]: Plugged pad: DragonRise Inc.   Generic   USB  Joystick   (121:6) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event10) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event10) supports 16 force feedback effects.
[INFO] [Autoconf]: 49 profiles found.
[INFO] [Autoconf]: selected configuration: /opt/retroarch/autoconfig/DragonRise Inc.   Generic   USB  Joystick  .cfg
[INFO] [udev]: Plugged pad: DragonRise Inc.   Generic   USB  Joystick   (121:6) on port #1.
[INFO] [udev]: Pad #1 (/dev/input/event9) supports force feedback.
[INFO] [udev]: Pad #1 (/dev/input/event9) supports 16 force feedback effects.
[INFO] [Autoconf]: 49 profiles found.
[INFO] [Autoconf]: selected configuration: /opt/retroarch/autoconfig/DragonRise Inc.   Generic   USB  Joystick  .cfg
```

### Version/Commit

- RetroArch: 1.7.7

### Environment information

- OS: Ubuntu 18.04.2
- Compiler: gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04)

### PR DESCRIPTION
**Pull request by DSkywalk**
## Description
Hello, this PR fixes #9071 
And also removed sort_devnodes and cleaned the code a bit.

### Actual behavior

Actually this is the order show in ra:
imagen

Then event device 10 is used as #0 device and device 9 is used as #1 device.

### Expected behavior

imagen

## Related Issues

FIXES ISSUE: #9071 

## Reviewers
I think is correct, but please test. Really thanks.
@orbea @twinaphex

### CODE REVIEW

**Comment by orbea** [comment]
I'm not sure I am the right person to review this.

**Comment by RobLoach** [comment]
What's the best way to test this?

This is my udev output when run...

```
[INFO] [udev]: Keyboard #0 (/dev/input/event3).
[INFO] [udev]: Keyboard #1 (/dev/input/event4).
[INFO] [udev]: Mouse #0 (/dev/input/event5).
[INFO] [udev]: Mouse #1 (/dev/input/mouse0).
[INFO] [udev]: Mouse #2 (/dev/input/event6).
[INFO] [udev]: Mouse #3 (/dev/input/mouse1).
```

**Comment by hizzlekizzle** [comment]
Since this is basically just cutting out behavior (AFAICT, at least), it would probably be good to ask why that behavior was in there in the first place, which would give us a better idea of where to look for regressions. @bparker06 @twinaphex any thoughts?

**Comment by twinaphex** [comment]
@Themaister wrote this code.

**Comment by DSkywalk** [comment]
@RobLoach you need more devices to test the patch. 

The patch only fixes the joypad initialization code, maybe it should be ported to input udev, too. I could do it, if @Themaister aproves this changes :+1: 

Thanks!

**Comment by hhromic** [comment]
For what is worth, since May 2018 disabling qsort (to address a similar issue) had been in place in RetroPie in this commit:
https://github.com/RetroPie/RetroPie-Setup/commit/82721179f56c217de72c57381a65eed30aa30ad1#diff-afa16c8cf1a728d2dd27cfa73ddf4726

> disable udev sort as it the changed behaviour may cause more problems than it solves - https://retropie.org.uk/forum/topic/17276/usb-ports-no-longer-determine-player-number-retroarch-1-7-1

This means that a significant number of users (from RetroPie) have been benefiting from this behaviour already without complaints.

Furthermore, I think the solution in this PR using `udev_list_entry_foreach()` is the most elegant/correct approach as it relies on `udev` itself to order the device enumeration. Probably the reason for the udev function to exist in the first place.

**Comment by Themaister** [comment]
Does it matter which order devices come in? If list_entry_foreach does the expected thing, this code seems fine to me.

**Comment by DSkywalk** [comment]
thanks @Themaister 

> Does it matter which order devices come in?
Yes, because another games/emulators use the *logic* order. In my situation I have a CPO with two joys (input9/input10) groovymame/pcsx2/psp get input9 as 1st device and input10 as 2nd device. In retroarch actually the first player is the 2nd control :walking_man:

**Comment by twinaphex** [comment]
Alright, beyond @DSkywalk, can somebody else test this as well on their end, and then after he says it's good, we'll call it a day and merge it?

**Comment by twinaphex** [comment]
@orbea  Can you test this on your end?

**Comment by orbea** [comment]
Sorry no, I don't have enough devices to test this well.

**Comment by twinaphex** [comment]
Then we'll give it a shot I guess.

**Pull request merged**
