### PR TITLE
README.md: Replace HTML with Markdown syntax

### PR DESCRIPTION
**Pull request by diegoviola**

### CODE REVIEW

**Comment by lasers** [comment]
**PC** Instructions for compiling on PC can be found in the wiki.

**PC**

Instructions for compiling on PC can be found in the wiki.

**Comment by diegoviola** [comment]
@lasers What do you mean? Do you suggest changing the content?

In this PR, I've just changed the HTML markup to markdown.

**Comment by lasers** [comment]
Yes. Give it an extra return to replace the omitted br.

**Comment by diegoviola** [comment]
@lasers I think the markdown syntax automatically adds the line-break.

**Comment by diegoviola** [comment]
@lasers Done, see #4224

**Pull request merged**
