### PR TITLE
add config option to choose between cheevos implementations

### PR DESCRIPTION
**Pull request by meleu**
## Description

Adding the option `cheevos_rcheevos_enable`, if `true` RetroArch uses the new cheevos implementation, otherwise, use the old one. This option was created for debugging only and is intended to be temporary.

If everything works fine with the new implementation, later I'll submit another PR removing the old one.

**Why is this "needed"?**

Last time @leiradel tried to integrate [rcheevos](https://github.com/RetroAchievements/rcheevos) in RetroArch (#7321) it brought some issues on the Android build (as reported by @fr500 in #7341) and the PR had to be reverted. And as it's a pain to reproduce the same toolchain setup as the buildbot, the debugging was really tough.

My approach here is based on [a suggestion from @fr500](https://discordapp.com/channels/184109094070779904/434759979095031840/536634343649574934) so we can try to reproduce those issues while don't break anything.

I've been testing an Android binary built by @Jamiras on Windows Visual Studio (he had to do some tweaks to get it compiled on VS) and those issues reported by @fr500 don't happen. Here's the apk if someone is interested in testing: [retroarch-activity-memref.apk](https://www.dropbox.com/s/n0fvy5s27g57e8g/retroarch-activity-memref.apk?dl=1)).

This PR also updates rcheevos files.

## Related Issues

#7341
https://github.com/RetroAchievements/rcheevos/issues/3
https://github.com/RetroAchievements/rcheevos/issues/7

## Reviewers

@leiradel @fr500 @Jamiras

### CODE REVIEW

**Comment by fr500** [comment]
wow... big PR.
Why 111 files?

**Comment by fr500** [comment]
I'm pretty sure you need the griffin stuff.

**Comment by bparker06** [comment]
This pull request **introduces 4 alerts** when merging cc63738079cf9752fd3719308f88b3ef879cc526 into c5d9a69ae75bd37a33ea395c3bba69e706017442 - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-4767d4940d5c51ff24639ff034736a00106425f8)

**new alerts:**

* 3 for Comparison result is always the same
* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by orbea** [comment]
@meleu Does the new cheevos implementation require `--enable-lua`?

**Comment by meleu** [comment]
> Why 111 files?

88 files are from `deps/rcheevos` (cause we already use rcheevos on RAchievements emulators and Jamiras has been working on more features for it)
22 files are due the namespacing thing.
1 file is the `griffin/griffin.c` (which seems to be failing in the Travis CI build)

> I'm pretty sure you need the griffin stuff.

alright, I'm going to put them back. They were removed as part of tweaks Jamiras did to compile the Android build on Visual Studio, but it seems to be unnecessary here.

> This pull request **introduces 4 alerts** 

Thanks, I'll work on that.

> Does the new cheevos implementation require `--enable-lua`?

yes, but since rcheevos wasn't integrated in RetroArch yet, we don't have anything using Lua for now. Then it's not really required right now.

**Comment by bparker06** [comment]
This pull request **introduces 4 alerts** when merging 016d5c3f1c677bb1567f03cc49ecb53d1d8aa642 into 7b9fcfd2805d98362563cd502b8ba574a2d25d35 - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-ebf0dbc515c8f886c13866bfd21249ab6e857c2a)

**new alerts:**

* 3 for Comparison result is always the same
* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by orbea** [comment]
> yes, but since rcheevos wasn't integrated in RetroArch yet, we don't have anything using Lua for now. Then it's not really required right now.

I'm not sure I understand what you mean by recheevos not being integrated? Isn't that why its in deps?

https://github.com/libretro/RetroArch/tree/master/deps/rcheevos

My concern is that lua which is hardly used is already causing several issues and it seems more pain than gain in my opinion.

For example RetroArch will crash inside the system lua when playing video content when both `--enable-mpv` and `--enable-lua` are used. We also seem to be missing some defines when building lua leading the warnings at least on linux during the linking stage, but they are all highly platform specific making it hard to fix... Of course there is the issue with rcheevos requiring lua5.3 which makes it pretty much impossible to support a system lua given to missing features in upstream lua (pkg-config file and shared library). See issue https://github.com/RetroAchievements/rcheevos/issues/15 for more info on the third point.

I know this doesn't directly relate to your goal here, but I think its worth mentioning that this is a bit of a sore spot...

**Comment by Jamiras** [comment]
> 88 files are from deps/rcheevos (cause we already use rcheevos on RAchievements emulators and Jamiras has been working on more features for it in the last months)

81 files are in `rcheevos/test`, which isn't really required for RetroArch. I recommend excluding that directory for this PR.

> I'm pretty sure you need the griffin stuff.

I had to introduce a new griffin file to prevent conflicts between the old cheevos and new cheevos structures (perhaps more things need to be namespaced or shared). I also had to include two new include paths (`deps/rcheevos/include` and `deps/lua/src`). I did this to one project file. Is there any easy way to do it to all necessary projects? Or at least some way to identify all affected projects?

> since rcheevos wasn't integrated in RetroArch yet, we don't have anything using Lua for now. Then it's not really required right now.

rcheevos needs to know about the lua types/functions to compile, but we're not actually creating/passing around any lua objects yet. I haven't been part of the discussions around lua compatibility/versioning/etc, so I don't really have any insight to add about that.

**Comment by orbea** [comment]
> I haven't been part of the discussions around lua compatibility/versioning/etc, so I don't really have any insight to add about that.

Basically it should be fixed in upstream lua and this would not be an issue, but given that every distro reinvents the wheel fixing it themselves I am not going to hold my breath...

**Comment by meleu** [comment]
> I'm not sure I understand what you mean by recheevos not being integrated? Isn't that why its in deps?

I meant the rcheevos is not integrated in the *official* releases of RetroArch. Its files are there, but only for those who compile with `--enable-new_cheevos` (and I have a feeling that I'm the only person who actually does it).

Regarding Lua, there isn't any achievement coded with it (and our back-end is not yet ready for it).

To be fair, rcheevos not integrated in RetroArch is the bottleneck for the evolution of the RAchievements feature. We are holding many cool improvements (such as coding achievements with Lua) to avoid incompatibilities with RetroArch.

**Comment by orbea** [comment]
If we can switch between new and old achievements in the menu/configuration file then it should be fine to enable `HAVE_NEW_CHEEVOS` by default assuming it ready? The problems I have experienced seem limited to lua and as I don't use achievements I wasn't sure how useful the new cheevos was without lua.

**Comment by orbea** [comment]
Seems this doesn't work for osx + travis, maybe just something missing from griffin?

**Comment by bparker06** [comment]
This pull request **introduces 4 alerts** when merging 415d168a92b90e643ef6fd10a639f89eb2c4b816 into 4258836422608fcebc9423f823cd730b14765ebf - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-0dd9b62cc7d0eae6ce18ecb838f643c31467c6ea)

**new alerts:**

* 3 for Comparison result is always the same
* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bparker06** [comment]
This pull request **introduces 4 alerts** when merging aeac5f8b59c5cdcb5c228e39d13a8a9242db8b5e into 4258836422608fcebc9423f823cd730b14765ebf - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-a2218a00bb41549b693fccaa5a30b520904346b2)

**new alerts:**

* 3 for Comparison result is always the same
* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bparker06** [comment]
This pull request **introduces 3 alerts** when merging 38e01dec135022a6a5fdad7fae1cb6adc81ce98b into 4258836422608fcebc9423f823cd730b14765ebf - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-ddf342b874d57531adbfa3ffb63eb0dc17800ded)

**new alerts:**

* 3 for Comparison result is always the same

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bparker06** [comment]
This pull request **introduces 3 alerts** when merging c66b866a87a28ac3f6a06e5d9bda8ccbfba405de into fcd55d871e10a9c5b5eb744fef8304ae2d177755 - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-24ba548ca61b83099b7119300b3a4b5d07a0cd63)

**new alerts:**

* 3 for Comparison result is always the same

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by meleu** [comment]
Unless someone has something more to comment, this PR is now ready to be merged.

> This pull request **introduces 3 alerts** when merging [c66b866](https://github.com/libretro/RetroArch/commit/c66b866a87a28ac3f6a06e5d9bda8ccbfba405de) into [fcd55d8](https://github.com/libretro/RetroArch/commit/fcd55d871e10a9c5b5eb744fef8304ae2d177755) - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-24ba548ca61b83099b7119300b3a4b5d07a0cd63)

The 3 alerts mentioned by LGTM are all related to a comparison like this:
```C
unsigned long value;
/* ... */
if (value > 0xffffffffU)
```
And the alert is: `Comparison is always false because value <= 4294967295.`

However those checks were added as a way to prevent wrong 32-bit values on 64-bit platforms (as we can see [in this commit](https://github.com/RetroAchievements/rcheevos/commit/2bd970145d835e85e090915e7dd0e4588292d3fd) from @leiradel)

**Comment by leiradel** [comment]
These warnings are harmless, and they will happen on all platforms where `sizeof(long) == sizeof(int)` I believe, regardless of the LGTM analysis.

As for the PR, I think it's good to go, and an important step in phasing out the old cheevos code and putting RetroArch on par with the official Retro Achievements emulators.

**Comment by meleu** [comment]
Here's an android build with all commits until now: https://www.dropbox.com/s/xrp9dflycvy9qzl/retroarch-activity.apk?dl=1

**Comment by meleu** [comment]
Thanks to the help with testing from some fellows from the RetroAchievements community (namely @Jamiras, @Keltron3030 and @LootusMaximus) we have a strong feeling that this PR is stable enough. We have been testing it mainly on Android, but also on Linux x86_64 and Windows.

**Comment by bparker06** [comment]
>it's a pain to reproduce the same toolchain setup as the buildbot

Actually it couldn't be easier. All you have to do is rsync the bot's `/home/buildbot/tools/android` folder to your local machine and you're good to go, assuming you're on Linux. Let me know if you want to do this and I can give you instructions.

**Comment by meleu** [comment]
@bparker06 could you provide me access to that folder or a zip of it? (whichever is easier for you)

**Comment by leiradel** [comment]
I'm getting multiple warnings and errors trying to build the `runtime_rcheevos_switch` branch, i.e.:

```
$ git remote -v
origin	https://github.com/meleu/RetroArch.git (fetch)
origin	https://github.com/meleu/RetroArch.git (push)

$ git branch
  master
* runtime_rcheevos_switch

$ ./configure --enable-new_cheevos

$ make -j

In file included from command.c:44:0:
cheevos/var.h:71:49: error: unknown type name ‘cheevos_console_t’; did you mean ‘cheevos_var_size_t’?
 void cheevos_var_patch_addr(cheevos_var_t* var, cheevos_console_t console);
                                                 ^~~~~~~~~~~~~~~~~
                                                 cheevos_var_size_t
```

**Comment by Jamiras** [comment]
```$ ./configure --enable-new_cheevos
```

This branch implements the feature as a runtime switch, so you shouldn't have to specify anything when building.

This is most likely due to https://github.com/meleu/RetroArch/blob/runtime_rcheevos_switch/cheevos/cheevos.h#L19-L21
which suggests that all references to HAVE_CHEEVOS_NEW should be removed as part of this PR.

**Comment by leiradel** [comment]
How do I enable it?

**Comment by Jamiras** [comment]
From the PR description:

> Adding the option cheevos_rcheevos_enable, if true RetroArch uses the new cheevos implementation, otherwise, use the old one. This option was created for debugging only and is intended to be temporary.

add the following to your retroarch.cfg:
```
cheevos_rcheevos_enable = "true"
```

**Comment by leiradel** [comment]
Is there any place to make sure I'm running the new cheevos code?

**Comment by meleu** [comment]
> Is there any place to make sure I'm running the new cheevos code?

after enabling `cheevos_rcheevos_enable = true` and launching a game, you'll see a message on the OSD saying `cheevos: using the new implementation.` ([implemented in this commit](https://github.com/libretro/RetroArch/pull/8501/commits/c66b866a87a28ac3f6a06e5d9bda8ccbfba405de))

**Comment by leiradel** [comment]
I don't see that message, and the line is in the configuration file.

**Comment by LootusMaximus** [comment]
Looks like verbose mode also has to be enabled in achievement settings

**Comment by meleu** [comment]
@leiradel check if `cheevos_verbose_enable = true`.

**Comment by leiradel** [comment]
Ok, RetroArch was reading the configuration from `~/.config/retroarch/retroarch.cfg` instead of the current folder. I can see the message saying that I'm using the new implementation, and I could get a couple of SMW cheevos. I've switched back to the old implementation and was again able to get the same cheevos.

It looks good to me. Should I look for something else in specific?

**Comment by meleu** [comment]
A conflict with `managers/cheat_manager.c` appeared but it is very simple to solve (I'll do that tonight).

The LGTM anaysis failed [reported here](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-d00e194c00ac757fe1b2a88a519fbe2ec7f77705) seems to be something wrong with the LGTM tool, and not with the PR (maybe @bparker06 can give some input here?).

Other than those, I think everything is fine. If I'm not mistaken, @twinaphex was only waiting for your (@leiradel) OK to merge this PR.

**Comment by orbea** [comment]
@meleu The LGTM issue should go away if you rebase against master.

**Comment by leiradel** [comment]
Ok, RetroArch was reading the configuration from `~/.config/retroarch/retroarch.cfg` instead of the current folder. I can see the message saying that I'm using the new implementation, and I could get a couple of SMW cheevos. I've switched back to the old implementation and was again able to get the same cheevos.

It looks good to me. Should I look for something else in specific?

**Comment by orbea** [comment]
@meleu If you don't mind, can you please use `git rebase` instead of merging the master branch into your PR?

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

This will avoid this ugly merge commits. :)

**Comment by Jamiras** [comment]
rebasing makes collaboration hard. Anyone who has this branch checked out will end up with a detached head because rebasing rewrites history. If you're concerned about clean history, squash and merge when pulling the code into master.

**Comment by orbea** [comment]
> rebasing makes collaboration hard

Not at all, you can use `git fetch` to get new changes and can use `git rebase` or `git reset` as needed to merge collaboration or reset the repo state.

> If you're concerned about clean history, squash and merge when pulling the code into master.

In practice this never happens and now look at our git history....

**Comment by fr500** [comment]
rebasing is essential to ensure your PR works on top of the current master.
the way I work usually is:

```
git remote add upstream $url_of_upstream_repo
git fetch upstream
git checkout $local_branch --------> most people just work on master
git rebase upstream/master
--fix conflicts if any--
git push -f
```

You shouldn't end up with a detached head anywhere doing this

**Comment by Jamiras** [comment]
Rebasing is great for local changes, and should be used judiciously for keeping any local changes out of your local master. But once you've pushed your branch, you've created a node that others might be dependent on. As soon as you rebase/forcepush after that, you destroy the upstream node and create a new one. If no one else is using that node then there aren't any problems. If someone is, then they have to jump through a lot of hoops to get back into a working state.

From git's [official documentation](https://www.atlassian.com/git/articles/git-team-workflows-merge-or-rebase): 
> Rebasing doesn't play well with pull requests, because you can't see what minor changes someone made if they rebased (incidentally, the consensus inside the Bitbucket Server development team is to never rebase during a pull request).

>Rebasing can be dangerous! Rewriting history of shared branches is prone to team work breakage. This can be mitigated by doing the rebase/squash on a copy of the feature branch, but rebase carries the implication that competence and carefulness must be employed.

I've worked at two companies who have used git, and both have insisted that you should not rebase once you've pushed.

However, this discussion is irrelevant to the changes in this pull request. If libretro's official stance is to use rebase in PRs, then by all means we should do so.

**Comment by orbea** [comment]
@meleu You broke C89_BUILD=1 for cheevos...

```
CC cheevos/cheevos.c
CC cheevos/badges.c
CC cheevos/var.c
CC cheevos/cond.c
CC cheevos-new/cheevos.c
cheevos/var.c: In function ‘cheevos_var_get_memory’:
cheevos/var.c:298:4: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
    rarch_system_info_t* system = runloop_get_system_info();
    ^~~~~~~~~~~~~~~~~~~
CC cheevos-new/fixup.c
CC cheevos-new/parser.c
CC cheevos-new/hash.c
CC deps/rcheevos/src/rcheevos/trigger.c
In file included from cheevos-new/cheevos.c:67:
deps/rcheevos/include/rcheevos.h:161:4: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   };
    ^
CC deps/rcheevos/src/rcheevos/condset.c
cheevos-new/cheevos.c: In function ‘rcheevos_test_leaderboards’:
cheevos-new/cheevos.c:676:13: error: C++ style comments are not allowed in ISO C90
             // this is where we would update the onscreen tracker
             ^
cheevos-new/cheevos.c:676:13: error: (this will be reported only once per input file)
cc1: some warnings being treated as errors
In file included from cheevos-new/fixup.c:23:
deps/rcheevos/include/rcheevos.h:161:4: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   };
    ^
cc1: some warnings being treated as errors
make: *** [Makefile:201: obj-unix/release/cheevos-new/cheevos.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:199: obj-unix/release/cheevos-new/fixup.o] Error 1
In file included from deps/rcheevos/src/rcheevos/internal.h:4,
                 from deps/rcheevos/src/rcheevos/trigger.c:1:
deps/rcheevos/include/rcheevos.h:161:4: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   };
    ^
cc1: some warnings being treated as errors
make: *** [Makefile:199: obj-unix/release/deps/rcheevos/src/rcheevos/trigger.o] Error 1
In file included from deps/rcheevos/src/rcheevos/internal.h:4,
                 from deps/rcheevos/src/rcheevos/condset.c:1:
deps/rcheevos/include/rcheevos.h:161:4: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   };
    ^
cc1: some warnings being treated as errors
make: *** [Makefile:199: obj-unix/release/deps/rcheevos/src/rcheevos/condset.o] Error 1
```

**Comment by orbea** [comment]
@twinaphex Can you please not merge these unrebased PRs which still need review? Its extremely demotivating...

**Comment by Jamiras** [comment]
Seems like something that should have been caught by one of the CI checks.

**Comment by orbea** [comment]
I have a commit to add those to travis now although it will make CI even slower, but I'll wait for a fix first...

**Comment by Jamiras** [comment]
C89 fix here: https://github.com/meleu/RetroArch/commit/1c0efbfa90ddc7d9e01a913b290623d1e9cde635
Do you want me to add it to this branch/PR, create a new PR to merge to this branch, or a new PR to merge directly to libretro/master?

**Comment by meleu** [comment]
I suppose a new PR is easier/simpler.

**Comment by twinaphex** [comment]
It's also CXX_BUILD that has to be fixed -

also @orbea I cannot be blamed for merging this when I was continually nudged into merging this PR over and over again, and then it turns out these build checks were not being run.

What we should do is add CXX_BUILD/C89_BUILD checks to Travis so that it gets reviewed for every PR automatically.

**Comment by Jamiras** [comment]
The CXX_BUILD failure is unrelated to this feature:
```
CC gfx/drivers_context/wayland_ctx.c
gfx/drivers_context/wayland_ctx.c:609:1: error: invalid conversion from ‘void (*)()’ to ‘void (*)(void*, wl_surface*, wl_output*)’ [-fpermissive]
 };
 ^
In file included from /usr/include/wayland-client-core.h:30:0,
                 from /usr/include/wayland-client.h:39,
                 from gfx/drivers_context/wayland_ctx.c:20:
gfx/drivers_context/wayland_ctx.c: In function ‘void handle_toplevel_config(void*, xdg_toplevel*, int32_t, int32_t, wl_array*)’:
gfx/drivers_context/wayland_ctx.c:639:5: error: invalid conversion from ‘void*’ to ‘const uint32_t* {aka const unsigned int*}’ [-fpermissive]
     wl_array_for_each(state, states) {
     ^
gfx/drivers_context/wayland_ctx.c: In function ‘void handle_zxdg_toplevel_config(void*, zxdg_toplevel_v6*, int32_t, int32_t, wl_array*)’:
gfx/drivers_context/wayland_ctx.c:708:5: error: invalid conversion from ‘void*’ to ‘const uint32_t* {aka const unsigned int*}’ [-fpermissive]
     wl_array_for_each(state, states) {
     ^
gfx/drivers_context/wayland_ctx.c: In function ‘void registry_handle_global(void*, wl_registry*, uint32_t, const char*, uint32_t)’:
gfx/drivers_context/wayland_ctx.c:871:33: error: invalid conversion from ‘void*’ to ‘output_info_t* {aka output_info*}’ [-fpermissive]
       output_info_t *oi = calloc(1, sizeof(output_info_t));
                           ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by twinaphex** [comment]
That's on Linux though. On Windows, those files don't get compiled so it arrives at the Cheevos files instead, and there are definitely errors there.

I'll fix those errors you pointed out and commit it so that you can see it for yourself.

**Comment by fr500** [comment]
@Jamiras while I understand the logic behind not rebasing, fact is RetroArch is somewhat fragile.
So having commits neatly packed together make things easier to bisect.

**Comment by twinaphex** [comment]
Hi @Jamiras ,

https://github.com/libretro/RetroArch/commit/7b3be5eddf6c1a1c1a9f30c4c0eb3eaf1f1fa96f

Can you tell me what CXX_BUILD errors remain for you after this commit?

**Comment by orbea** [comment]
I'm at this with the `CXX_BUILD`.

```
menu/cbs/menu_cbs_ok.c: In function ‘int generic_action_ok_displaylist_push(const char*, const char*, const char*, unsigned int, size_t, size_t, unsigned int)’:
menu/cbs/menu_cbs_ok.c:282:37: error: invalid conversion from ‘int’ to ‘msg_hash_enums’ [-fpermissive]
    menu_displaylist_info_t info = {0};
                                     ^
CC menu/cbs/menu_cbs_scan.c
make: *** [Makefile:201: obj-unix/release/menu/cbs/menu_cbs_ok.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Jamiras** [comment]
I've got at least three files still complaining:
```
menu/cbs/menu_cbs_ok.c: In function ‘int generic_action_ok_displaylist_push(const char*, const char*, const char*, unsigned int, size_t, size_t, unsigned int)’:
menu/cbs/menu_cbs_ok.c:282:37: error: invalid conversion from ‘int’ to ‘msg_hash_enums’ [-fpermissive]
    menu_displaylist_info_t info = {0};
                                     ^
```
```                                     
In file included from /usr/include/wayland-client-core.h:30:0,
                 from /usr/include/wayland-client.h:39,
                 from gfx/drivers_context/wayland_ctx.c:20:
gfx/drivers_context/wayland_ctx.c: In function ‘void handle_toplevel_config(void*, xdg_toplevel*, int32_t, int32_t, wl_array*)’:
gfx/drivers_context/wayland_ctx.c:666:4: error: lvalue required as left operand of assignment
    wl_array_for_each((void*)state, states)
    ^
gfx/drivers_context/wayland_ctx.c:666:4: error: lvalue required as increment operand
    wl_array_for_each((void*)state, states)
    ^
gfx/drivers_context/wayland_ctx.c: In function ‘void handle_zxdg_toplevel_config(void*, zxdg_toplevel_v6*, int32_t, int32_t, wl_array*)’:
gfx/drivers_context/wayland_ctx.c:745:4: error: lvalue required as left operand of assignment
    wl_array_for_each((void*)state, states)
    ^
gfx/drivers_context/wayland_ctx.c:745:4: error: lvalue required as increment operand
    wl_array_for_each((void*)state, states)
    ^
```
```
gfx/drivers/gl.c: In function ‘void gl2_load_texture_image(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid*)’:
gfx/drivers/gl.c:359:31: error: invalid conversion from ‘unsigned int’ to ‘gl_capability_enum’ [-fpermissive]
    if (gl_check_capability(cap) && internalFormat != GL_BGRA_EXT)
                               ^
```

**Comment by twinaphex** [comment]
Pushed another buildfix -

https://github.com/libretro/RetroArch/commit/499235cd40af48226e62d13a137ebdcb4b128145

**Comment by Jamiras** [comment]
I think this is the last one:
```
CC gfx/drivers_context/wayland_ctx.c
In file included from /usr/include/wayland-client-core.h:30:0,
                 from /usr/include/wayland-client.h:39,
                 from gfx/drivers_context/wayland_ctx.c:20:
gfx/drivers_context/wayland_ctx.c: In function ‘void handle_toplevel_config(void*, xdg_toplevel*, int32_t, int32_t, wl_array*)’:
gfx/drivers_context/wayland_ctx.c:666:4: error: lvalue required as left operand of assignment
    wl_array_for_each((void*)state, states)
    ^
gfx/drivers_context/wayland_ctx.c:666:4: error: lvalue required as increment operand
    wl_array_for_each((void*)state, states)
    ^
gfx/drivers_context/wayland_ctx.c: In function ‘void handle_zxdg_toplevel_config(void*, zxdg_toplevel_v6*, int32_t, int32_t, wl_array*)’:
gfx/drivers_context/wayland_ctx.c:745:4: error: lvalue required as left operand of assignment
    wl_array_for_each((void*)state, states)
    ^
gfx/drivers_context/wayland_ctx.c:745:4: error: lvalue required as increment operand
    wl_array_for_each((void*)state, states)
    ^
Makefile:199: recipe for target 'obj-unix/release/gfx/drivers_context/wayland_ctx.o' failed
make: *** [obj-unix/release/gfx/drivers_context/wayland_ctx.o] Error 1
```

**Comment by twinaphex** [comment]
@Jamiras OK, so it turned out wl_array_for_each is a macro that is not compatible with CXX_BUILD - so I had to make a modified version of the macro for it to work -

https://github.com/libretro/RetroArch/commit/8e638f435a37c46195aad1589ab024e443971d12

**Comment by Jamiras** [comment]
That seemed to clear it up. I'm seeing the errors in cheevos-new now. Will address and open a new PR.

**Comment by twinaphex** [comment]
Thanks.

**Pull request merged**
