### PR TITLE
When extracting content from compressed archive files, set valid extensions to the indicated one in the path instead of the (currently) hardcoded valid extensions in the cores

### PR DESCRIPTION
**Pull request by ChoquePumper**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]
The current behavior does not allow extracting content from compressed archive files whose extrension is not in the hardcoded valid extensions even if the core info file says otherwise. Example:
* Content path: /path/to/archive.zip#mygame.ex3
* Supported extensions from core info file: ex1|ex2|ex3
* Hardcoded valid extensions from the core itself: ex1|ex2 ("ex3" is missing)

If it tries to extract the content with "ex3" file extension, it will fail because it takes precedence from the hardcoded valid extensions and won't extract the content because "ex3" is not valid. This issue doesn't happen if it loads the content from the compressed archive file directly to memory without extracting it (when need_fullpath is false).

This PR changes the behavior by setting the valid extensions to only the writen one in the path, making it able to extract and load the content. Example:
* Content path: /path/to/archive.zip#mygame.ex3
* Valid extensions before: ex1|ex2
* Valid extensions after (on load): ex3

Example 2:
* Content path: /path/to/archive.zip#anothergame.ex1
* Valid extensions before: ex1|ex2
* Valid extensions after (on load): ex1

I mean, i those files can be added to the playlist via "Scan Directory" because the core info file says that the extension is valid, but the core itself says otherwise and prevents RetroArch from extracting it and the content can't be loaded (if need_fullpath is true).

Note: I know I'm limiting the file extension up to 8 characters (see the diff). I just want to know if it's fine or it should allow larger file extensions.

## Related Issues

* #12462 (also opened by me)

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by twinaphex** [comment]
hi there, a couple of things:

* Can you use strlcpy instead of strncpy?
* Can you make it so that variables are declared either at the start of the function or the start of a code block? Merging it like this right now would break C89 compliance.

**Comment by jdgleaver** [comment]
This is really a core bug, though. Core info files are a necessary crutch, but the hard coded extension list in the core should always be considered as 'definitive'. If there is a mismatch between the core and the info file, then one or the other should be corrected.

**Comment by ChoquePumper** [comment]
@jdgleaver That's means, if there are new known file extensions to be added, then you also have to add them to the core itself by touching the source code each time it happens, right?
Currently, the Sega Genesis / Mega Drive cores have that mismatch you mention: "68k" and "sgd" are missing in the hard coded list. And yet RetroArch is still able to load uncompressed content with those file extensions because it passes a valid path (regardless the file extension) to the core.
The point of this PR is at least to allow the frontend **to extract** the content from the **specified** path even if the extension is not valid. I just don't get why only the **file extraction** (through `content_file_extract_from_archive`) has to be restricted to the hard coded valid extensions. `content_file_load_into_memory` does not perform that check and it actually ends up searching for the file without requiring the `valid_exts` parameter, and `zlib_file_read` calls `file_archive_parse_file_iterate` with `valid_exts` set to "" (an empty string) to search the file and it works. In my opinion, if the path tells what file to load, at least it should do an attempt.

**Comment by i30817** [comment]
It's probably on purpose for at least the first.

68k is a extremely weird extension to use for megadrive because there are lots and lots of machines using the 68k processor, including the amiga, the megadrive, the sharp 68k (this one might actually use that extension),  the early apple macintosh, tandy, capcom system 1 etc etc.

It might not be allowed simply because the 68k emulators got there first.

**Comment by jdgleaver** [comment]
> That's means, if there are new known file extensions to be added, then you also have to add them to the core itself by touching the source code each time it happens, right?

Yes, absolutely. Only the core itself knows what file types it can actually open. If the developer has not specified that a file type is valid, then to all intents and purposes you are passing garbage data.

> And yet RetroArch is still able to load uncompressed content with those file extensions because it passes a valid path (regardless the file extension) to the core.
> content_file_load_into_memory does not perform that check and it actually ends up searching for the file without requiring the valid_exts parameter, and zlib_file_read calls file_archive_parse_file_iterate with valid_exts set to "" (an empty string) to search the file and it works.

You are right - but this behaviour is a bug! We should never be passing anything to the core if it's not on the whitelist. There should really be an additional check in `content_file_get_path()` to ensure that invalid files are filtered out (at present this only happens when passing a parent archive file).

**Comment by ChoquePumper** [comment]
@jdgleaver If that's how it should work, then fine, I'm closing this pull request. I guess I got the wrong idea after all.

Personally, I still think that there should be a way to try to load the content anyway but also show a warning message or a disclaimer. And since "Manual Scan" allows to add content with specified (**and non valid**) file extensions to a playlist and set a default core for it, why should we prevent the user from loading that content for such a specific case?
In the case of the Sega Classics from Steam, the roms are delivered with certain file extensions including "68k" and "sgd". If the 'bug' ever gets fixed, then the user is forced to rename those files (likely one at a time) or request to add those extensions to the core which probably won't happen, and some file managers don't allow to change the file extension (that's my case with the Android 4.4 default file manager in my device).
I tested removing the "sgd" from the core info file and using "Manual Scan" to add my games to the playlist and set the Genesis Plus GX as default core. I got no issues at all because the core (fortunately) can run the content through its default handling. I don't see that as a 'bug' but a feature. You can take that as a suggestion.

Or maybe I'm just talking too soon and there's already a better idea. I don't know.

Sorry for opening a pull request without discussing this beforehand. :(

**Pull request closed without merging**
