### PR TITLE
Android: Remove external storage permission

### PR DESCRIPTION
**Pull request by cwyc**
## Description
The android client requests blanket access to internal storage, even though it only needs to access the self-contained `/sdcard/RetroArch` folder. 
By getting rid of this permission, we can improve sandboxing and show respect to the user's privacy. Also, this issue is what's holding up play store updates.

We do this by moving the RetroArch folder to app-specific storage, `/sdcard/Android/data/com.retroarch.aarch64/files/RetroArch`. A DocumentsProvider is added to allow the user to easily access it. And a migration flow is added to prompt existing users to copy their RetroArch folder to the new location.

Consequences are that users will have to copy their content into app-specific storage before they play them, and that some automated backup workflows will be disrupted.

It wasn't practical to accomplish this by leaving the folder in place and accessing it through DocumentsContract, since the files couldn't be accessed through the POSIX apis that the rest of the codebase relies on, and because it has a performance penalty.

## Related Issues

This issue is discussed here: https://github.com/libretro/RetroArch/issues/12181

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
@LibretroAdmin

**Comment by hizzlekizzle** [comment]
if this will allow us to update the Play Store version, this is very exciting stuff! We very much appreciate the contribution!

**Comment by warmenhoven** [comment]
I'm not very familiar with Android at all, but fairly familiar with iOS. I took a look at this PR and it seems reasonable and straightforward to me, but I did have a couple concerns.

@cwyc , could you please describe in more detail how the migration affects:
1. paths in retroarch.cfg and playlists
2. roms that may not exist in the retroarch directory?

For the paths in the .cfg and .lpl files, on iOS if a file exists in the sandbox, the filename is prefixed/truncated to indicate it should be searched for in the sandbox. Does the same thing happen on Android? If so I'd expect it's probably not an issue except for any the files the user has created themselves outside the sandbox, which is basically the same question as 2.

**Comment by cwyc** [comment]
@warmenhoven 
Thank you for pointing this out, I hadn't considered path references in config files.

Yes, retroarch.cfg and playlists do carry absolute paths. We will need to update them when we copy content over. This is complicated by the fact that the app gives users the option to individually relocate the content directories, so they might need to be selected and copied in separate operations.

As for roms outside of the RetroArch folder, they won't be copied over, and playlists referring to them will be broken. But for roms that are copied, we can update the paths in content*_history.lpl and other playlist files we find on a best-effort basis.

The current migration flow assumes all this exists in ~/RetroArch. 
Instead, perhaps it needs to begin by searching config and playlist files for external references, giving users the option to select and copy each to standard locations in app-specific storage, and updating the paths. It will also have to be recursive, as files in the content directories might reference others. ROMs can go in a RetroArch/roms folder.

Still, we might be able to catch and replace all the references, and some people's setups might get messed up. I'd be open to other approaches.

**Comment by warmenhoven** [comment]
@cwyc 
Ok so in my opinion:
* getting it on the play store again is a big important thing, 
* upgrades/migrations are always an place where people are expecting weirdness/brokenness, 
* and people who are putting retroarch-related stuff outside the retroarch folder are already more likely to be equipped to be able to fix the brokenness manually;
* so my opinion is that worst case this is fine to merge as is. Still, there should be best effort made to do something better if at all easy/possible. If not, at least you tried, and people will get over it.

Given that, I think it's safest not to try to get too smart/tricky with it. Update the paths in the .cfg and .lpl files that you are already directly affecting (the most common cases), and everything else the user is going to have to sort out for themselves.

**Comment by hizzlekizzle** [comment]
I don't know if there's an easy way to give people an option to migrate or not. If it were me as an end-user, I'd rather just start over fresh if weird breakage were a possibility.

We already have the welcome message that shows on first launch, so we could duplicate that function to make another message that shows only when the other message is disabled (i.e., already been seen) and refers them to a docs page that lays all this out in more detail.

I'm just wary, in general, of automagic stuff.

But whatever, I'm fine with it either way. Any breakage/discomfort is going to be transitory anyway, and, as warmenhoven stated, just getting the Play Store version updated is worth pretty much any amount of temporary inconvenience.

**Comment by WargusUser** [comment]
If it will make only possible to play ROMS only from folder “/sdcard/Android/data/com.retroarch.aarch64/files/RetroArch” than no, just delete google play support or make sure that APK version from site sill have external storage permission support. I anyway use APK from site because google play version is limited. Google don’t care about emulation scene anyway and you should not care about their paranoid security stuff that mostly makes no sense.
Also deleting retroarch will delete also your saves and savestates.
So, if you implement google play support, make sure it’s still possible to use retroarch in convenient way for APK from site. I will not use google play version anyway

**Comment by i30817** [comment]
RetroArch, either the site build or the playstore build is essentially useless for big collection of roms until it supports reading roms or making the playlists read roms from SAF (storage access framework).

The reason is that SAF middleware like RSAF is the only way to access localhost or remote NAS, like webdav, nfs, samba, etc. I can run (even if it's annoying to lose the nice playlist interface) remote roms in android PPSSPP, dolphin, etc using RSAF and a Linux webdav server. I can't in RA.

**Comment by cwyc** [comment]
@hizzlekizzle I've added some code that just does a find-and-replace in .cfg and .lpl files, replacing the old default path to the new location. For good measure it makes a backup before it does so.
Agree with @i30817 integrating the file browser with DocumentProviders should be a priority, but I don't have experience with that codebase.

**Comment by RenanSD007** [comment]
Would it be possible to keep the version of the website as it is? It is much better to be able to read files from anywhere and without depending on Files app (Besides being annoying, many Android TVs don't have it, making it impossible to access any folders)

**Comment by i30817** [comment]
Playlist path auto changing has some danger because the manual playlists relocation feature already autochanges paths in some circumstances. Please test what happens if that code triggers before a change like that.


The trigger for the change is explained in this post and the next one: https://github.com/libretro/RetroArch/issues/9163#issuecomment-1834096083

I think it's a bit of a obscure feature. Useful though.

**Comment by cwyc** [comment]
@i30817 
I couldn't get the playlist relocation behaviour to work through the upgrade. At least with content_history.lpl, it looks in the old locations if we don't otherwise patch the paths.

But maybe we need to switch our focus to SAF in native code. I'll look into how scummvm does it. And if we achieve that, those who prefer it can leave the folder can be left in sdcard.

**Comment by i30817** [comment]
It's possible that the portable playlist feature was left half baked when jdgleaver left, and content history never changes even if you change rgui_browser_directory and it's different from base_content_directory.

There is no reason for that be because base_content_directory actually exists.

It can also be that you have to restart RetroArch before these changes get reflected on the playlists, I kind of recall something like that.

**Comment by i30817** [comment]
Regardless, after thinking about it a bit, I think if this automove happens.

1. The user will have to move the roms into the subdir you "annoint" as the base rom dir
2. This probably can't be automatic, since we're talking about potentially hundreds of gigabytes
3. Other settings in the Retroarch.cfg and playlists with paths, like rgui_browser_directory will also need to change\be reset to the apk sandbox
4. That may need to cause to turn off certain settings using those paths (such as portable playlists). This probably should have at least a user visible warning....

**Comment by hizzlekizzle** [comment]
@cwyc hey man, just so you don't think we've forgotten about this/you: we're hoping to get another stable release out very soon and then we'll be digging into this immediately after. We very much appreciate the work and are excited for the possibilities this opens up.

**Comment by StLouisCPhT** [comment]
The biggest issue with this is going to be rom storage. Moving them over to the data directory with everything else will result in their deletion if RetroArch is uninstalled. I would definitely recommend making sure users can still select alternative locations. Or consider using the same way Seleco does it with Mame4Droid 2024, and place the files in the media folder instead of data.

**Comment by cwyc** [comment]
@LibretroAdmin Why was this PR merged? I don’t believe we’ve come to consensus about how to handle this issue. On Jun 30, 2024, at 11:27 PM, i30817 ***@***.***> wrote:﻿
SAF doesn't require roms to be in the program sandbox, just that the directory be allowed access (in the android file chooser\files app). The user visible part of the local filesystem (the so called internal storage) is still accessible.

**Comment by hizzlekizzle** [comment]
@cwyc  Oh, I thought this was ready to go, at least to see if it makes it through Google's approval gauntlet. Is this salvageable as-is or do we need to revert? I (at least; can't speak for others) am okay with some temporary breakage on the nightly build, which is why we waited to get a stable release out before doing anything here.

**Comment by cwyc** [comment]
@hizzlekizzleI mean, it’s a big change that will mess up people’s workflows, and I think we can find a better solution that works in a different way. I think it would be best to revert it. On Jul 1, 2024, at 2:37 PM, hizzlekizzle ***@***.***> wrote:﻿
@cwyc  Oh, I thought this was ready to go, at least to see if it makes it through Google's approval gauntlet. Is this salvageable as-is or do we need to revert? I (at least; can't speak for others) am okay with some temporary breakage on the nightly build, which is why we waited to get a stable release out before doing anything here.

**Comment by LibretroAdmin** [comment]
I was asked to merge it. 

Anyway, I will revert it now then.

How do we proceed from here?

**Comment by hizzlekizzle** [comment]
Yeah, my bad.

So, what still needs to be resolved is how people are going to get ROMs into RetroArch's reachable locations without putting them at risk of deletion during app uninstallation, right? And some stuff about playlists? 

As you may have inferred, I'm of the opinion that getting the Play Store package up-to-date is of the utmost importance, even if the transition is bumpy.

**Comment by StLouisCPhT** [comment]
> Yeah, my bad.
> 
> So, what still needs to be resolved is how people are going to get ROMs into RetroArch's reachable locations without putting them at risk of deletion during app uninstallation, right? And some stuff about playlists?

Not just the roms. Anything that goes into the data folder would suffer that same fate. And not all android based devices can grant access - aside from the Shield TVs, a lot of android TV boxes are not designed for that level of file manager and phone companies like Samsung are starting to lock that kind of access down tightly (former co-workers of mine from uBreakiFix complain about it all the time now).

**Comment by StLouisCPhT** [comment]
There might be another idea too.

Shizuku can grant access to the SAF folders and they have provided code to make other file manager type apps compatible with it. That at least would allow RA's file manager "native" access to the SAF directories as well as external directories.

**Comment by leonstyhre** [comment]
Hi! Unless I've completely misunderstood this PR, implementing it would be very problematic. It would make all external frontends (ES-DE, Daijishou, Dig etc.) unusable with RetroArch, and like mentioned above, clearing the storage for the RetroArch app or uninstalling it would also delete all ROMs. In addition to this a lot of people mix RetroArch with standalone emulators using the same ROM directories and those emulators would also not be able to access the games any longer.

The best approach would be to add SAF support, or to give RetroArch MANAGE_EXTERNAL_STORAGE permissions. However the latter would likely get rejected by Google so a Play release would be impossible.

But you could argue whether the Play store is a lost cause anyway, the crazy restrictions that Google has introduced to their store have now reached a point where it makes it close to impossible to ship complex applications that actually work as intended. It's a usability nightmare to deal with all the SAF setup and Google is likely going to make it even worse with future OS releases and app store policy changes. It's probably best to drop Play store support and focus on publishing via your website, as you are already doing actually. The alternative stores like Samsung Galaxy Store, Huawei AppGallery and Amazon Appstore also don't have these restrictions so MANAGE_EXTERNAL_STORAGE works fine when publishing there.

@LibretroAdmin Just to confirm, you've reverted this PR? As mentioned it would be incredibly disruptive and make a lot of setups unusable. Thanks! :)

**Comment by StLouisCPhT** [comment]
Well, I wouldn't say 'misunderstood' but this PR IS basically to give SAF access. Which then creates the issue of where to place roms and other support files so they don't get accidentally deleted by an uninstall or a bad update.

**Comment by leonstyhre** [comment]
Thanks for your comments, well as long as it's thoroughly tested and doesn't break frontend support for instance then I guess improvements to the storage and security model are always appreciated!

**Comment by RenanSD007** [comment]
Being able to choose a folder like PPSSPP (/sdcard/PSP for example) when starting is the least, imagine deleting RetroArch and losing all your saves that you invested a lot of time, this way it would still be completely safe and whenever you reinstall it you would keep the data as it is now

**Comment by leonstyhre** [comment]
I've looked a bit more at this PR and my understanding is that it may be very disruptive. Moving directories to application-internal storage, i.e. under Android/data will make them inaccessible by other apps on recent Android versions (version 13 and later?). I'm not sure how the DocumentsProvider will help here, as someone may just want to access the savestates or whatnot using a file manager, or syncing data between various devices using a third party app and so on.

In addition to this, launching games from external applications like frontends will probably be broken too. Take for example the following am command:

```am start -n com.retroarch.aarch64/com.retroarch.browser.retroactivity.RetroActivityFuture -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg -e LIBRETRO cap32_libretro_android.so -e ROM /storage/emulated/0/ROMs/amstradcpc/3D_Fight.zip```

This is basically how frontends do it, although for example ES-DE is of course not using the am command directly but is natively utilizing the Intent API. It's still the same effect though, if removing storage access permissions from RetroArch it would not be able to load the ROM file. And many people also want to relocate their ROMs to external storage such as an SD card, which requires that RetroArch has access to this external storage device.

And as mentioned in a previous comment many people mix emulators and use RetroArch and standalone emulators interchangeably with the same ROMs directory.
Adding to the above there's the problem of someone uninstalling RetroArch or clearing its internal storage from the Android app settings, which would wipe all saves, savestates, ROMs and so on.

Again, please let me know if I misunderstood the approach taken here as I've not tested the code in the PR. I'm all for modernizing RetroArch as far as Android is concerned but it really needs to be done in a way that is non-disruptive so that users retain the functionality they have today and that third party apps like frontends can continue to function as they do today.

Thanks! :)

**Comment by GaussTek** [comment]
So, was this reverted completely? Any chance it will be implemented again in a future? It's weird to see the app is on iOS main app store and not in Android main app store.

Other emulators have already implemented workarounds, and in most of them you are able to choose a ROM folder, and a separate folder to store/access saves, etc, or in emulators like Dolphin, you are even able to export/import a ZIP file with all your save content for backup purposes. Why this cannot be implemented into RetroArch?

**Pull request merged**
