### PR TITLE
added cheevos_verbose_enable to Achievements menu

### PR DESCRIPTION
**Pull request by meleu**
The first commit is a small improvement in my previous PR (#5138). Now it shows login info only after a RA login procedure (the previous logic shows login info every time a game is launched). The message with the number of unlocked cheevos will be displayed every time a game is launched, though.

The second commit is adding the `cheevos_verbose_enable` option to the Achievements menu. Like the image below:

ra_menu

### CODE REVIEW

**Comment by twinaphex** [comment]
Just to make sure, you do make sure this is disabled by default, right?

**Comment by meleu** [comment]
Yep. As you can see in #5138 diff ([link to the exact line of code](https://github.com/libretro/RetroArch/pull/5138/files#diff-55b11c8dab3e1e8a8a7998e7e9cda4fcR1222)).

**Comment by grenade44** [comment]
Nice, will be updating from source tonight 😀

**Comment by meleu** [comment]
@grenade44 if you're talking about updating from source on RetroPie, maybe you'll want to see the discussion here: https://retropie.org.uk/forum/topic/11366/retroarch-update-from-source-isn-t-bleeding-edge/

**Comment by grenade44** [comment]
What sort of conflicts? I will have to see what happens, can always replace the v1.6.0 and reget from source if there's any issues.

**Comment by meleu** [comment]
A message saying something about that file being changed... But if you delete the file and update everything will be fine. ;-)

**Comment by meleu** [comment]
@grenade44 the logic for showing unlocked cheevos was reversed, actually showing the number of **locked** cheevos. I've fixed it in #5145 . If you already compiled the previous version, maybe you want to compile it again now.
Cheers!

**Comment by grenade44** [comment]
@meleu That didnt work, I updated like you said after removing the v1.6.0. When I ran the update I checked where it was pulling retroarch from and it still said v1.6.0. any ideas?

**Comment by grenade44** [comment]
I worked it out, I had to removed the .git as well for it to work. :D

**Comment by grenade44** [comment]
Its so nice to see that message 👍 @meleu, Thank you

**Comment by meleu** [comment]
@grenade44 you're welcome.

@frangarcj I saw you worked on the PSVita port and I'm tagging you here to contact you. Sorry if I'm wrong.
I would like to help to enable retroachievements on the PSVita port, is there something that a "hobbyist-average-C-programmer" can do to help?

**Pull request merged**
