### PR TITLE
Fix C89_BUILD=1 with clang.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This is because some people have misconfigured editors that automatically change the newline at end of file and clang's c89 build does not like that.

## Related Issues

```
In file included from retroarch.c:76:
./menu/widgets/menu_widgets.h:80:7: error: no newline at end of file
      [-Werror,-Wnewline-eof]
#endif
      ^
1 error generated.
make: *** [obj-unix/release/retroarch.o] Error 1
```

### CODE REVIEW

**Comment by orbea** [comment]
@natinusala Can you please fix your editor to not do this? :)

**Comment by natinusala** [comment]
I should configure myself to take the habit and add the newline manually, this is where the issue resides, my editor is fine

**Comment by orbea** [comment]
I added a second commit to disable `HAVE_MENU_WIDGETS` with `CXX_BUILD` for now.

@natinusala I'd really appreciate it you could help fix these numerous warnings and errors when you have time.

You can reproduce it by removing the `CXX_MENU_WIDGETS=no` line in `qb/config.params.sh` and then building with `./configure && make CXX_BUILD=1`.

**Comment by natinusala** [comment]
Sure I will take care of it later in the evening

**Comment by natinusala** [comment]
@orbea are you talking about all the `ISO C++ forbids converting a string constant to char*` ?

**Comment by orbea** [comment]
Yes, also the `-fpermissive errors. Most if not all of them could probably be fixed by a cast?

**Comment by natinusala** [comment]
Fix incoming in my next PR

**Pull request merged**
