### PR TITLE
(cheevos) generic memory mapping using rcheevos

### PR DESCRIPTION
**Pull request by Jamiras**
## Description

Leverages functionality added in rcheevos 9.0 (and live in RALibretro for over a month) to generically map core memory for achievement use. 

* Replaces the per-console mapping code (previously in fixup.c) with generic code (now in memory.c). This will allow support for new consoles to be made in the future just by upgrading the rcheevos dependency.
* Replaces per-address binary search with linear bank lookup. As most systems will only register one or two banks, this improves the performance of individual memory lookups - especially for games with more than a handful of important addresses.
* Cross-references block sizes specified by the core with what is expected by the achievement code and truncates or null-pads to match.
* Adds support for consoles where SRAM appears before RAM (i.e. GBA) when the core does not expose a memory map.
* Eliminates the Sameboy special-case code (#10080) as the entire memory map is generated before deciding that the core is not supported
* Modifies the Mupen64_Next special-case code (#10102) by detecting that some quantity of memory was exposed, even if the backing data is not yet ready. The first frame when achievements are processed will update the memory map and determine the validity of the core at that time.
* Updates the memory map when the core is reset (handles issue where 4D0 core changes its pointers on reset)

## Related Issues

n/a

## Related Pull Requests

n/a

## Reviewers

@Sanaki @meleu @leiradel

### CODE REVIEW

**Comment by i30817** [comment]
Could this be used to support cheats in more cores later? I'm a bit bummed about the cores that don't have inbuilt cheat support (ppsspp and dolphin).

**Comment by twinaphex** [comment]
Can you change cheevos/memory.c to something less generic? Like maybe cheevos/cheevos_memory.c. You might ask why I request this - on some platforms where we do static linking, the linker might not be sophisticated enough to tell two similarly named object names apart from one another so you'd get undefined reference to symbols errors at linking stage. Renaming it to a name that is less likely to conflict would sidestep all that.

**Comment by Jamiras** [comment]
> Could this be used to support cheats in more cores later? I'm a bit bummed about the cores that don't have inbuilt cheat support or only have 'internal' cheats (ppsspp and dolphin).

No. It leverages the same functionality that cheats does. Both ask the core for exposed memory. This just provides a translation from the map provided by the core to something the achievement code can understand.

**Comment by Jamiras** [comment]
> Can you change cheevos/memory.c to something less generic?

I can, but note that we have other similarly generic names in the rcheevos subdirectory: `parser.c` and `hash.c`. 

Don't most compilers generate the .o files next to the .c files, thereby requiring the path as part of the command to the linker?

Please confirm that you still want me to rename the file.

**Comment by twinaphex** [comment]
I'd prefer you rename the files to something less generic yes. It will just make things much easier across a lot of old compilers/toolchains.

**Comment by twinaphex** [comment]
BTW regarding rcheevos_djb2 - is it different functionally from the djb2 version in libretro-common?

**Comment by Jamiras** [comment]
> BTW regarding rcheevos_djb2 - is it different functionally from the djb2 version in libretro-common?

The only apparent difference is that it takes a length instead of expecting a null terminator.

**Comment by twinaphex** [comment]
Would it be possible to reuse the one from libretro-common? Of course, test first if everything still works fine for you. But if it'd be possible to use the one from libretro-common and then we could remove the one in cheevos, that'd be great.

**Pull request merged**
