### PR TITLE
Add dinput rumble support

### PR DESCRIPTION
**Pull request by casdevel**
This is related to issue #4998.

### CODE REVIEW

**Comment by bparker06** [comment]
@casdevel @twinaphex why was DISCL_NONEXCLUSIVE changed to exclusive? isn't that a bad thing?

**Comment by casdevel** [comment]
@bparker06 IDirectInputEffect::Start method requires that flag.

**Comment by bparker06** [comment]
Does this mean other applications cannot use the controller at the same time? If so I would consider that a major regression. We might have to put this behind an option as I see this easily interfering with launchers and other programs.

**Comment by casdevel** [comment]
Yes, non-exclusive access is always available (according to the API docs).

**Pull request merged**
