### PR TITLE
Add Windows raw input driver

### PR DESCRIPTION
**Pull request by casdevel**

### CODE REVIEW

**Comment by casdevel** [comment]
Under Windows only SDL video driver allows user selected input driver, but with 3-line change in WGL context driver, OpenGL video driver can also work with user selected input driver (at least this one). Didn't tested this with D3D driver.

**Comment by twinaphex** [comment]
Hi there, great work.

How are we doing to do the 3-line WGL modification so that we can use RawInput driver in conjunction with it? I guess the best thing to do would be to check if the input driver is set to 'rawinput', and if so, use that. If not, we fall back to DInput/XInput.

**Comment by twinaphex** [comment]
Hi there,

https://www.bountysource.com/issues/43321949-rawinput-input-driver-for-windows

You should try to claim your bounty here, then I can accept the solution, and you should get the money. I will try to give you something extra for your efforts too, I will probably pay that out to you separate from this bounty, as a token of appreciation so far.

**Comment by casdevel** [comment]
I'll think about that tomorrow (it's been a long day), and also I'll check whether some other input driver works with OpenGL too. Regarding bounty, I can claim it only when issue #4777 is marked as closed.

**Comment by twinaphex** [comment]
OK, I closed the issue. You can now try to claim it.

**Comment by casdevel** [comment]
@twinaphex I think that simplest solution is as you suggested. I can make PR since I already have the code, or if you wish to do it, go ahead.

One note regarding code at line 115: void *cls = (void*)wi.atomWindowType. This line triggers warning with GCC compiler (this is way I used those odd pointer arithmetic instead of cast). Instead of ATOM, hard-coded class name can be used and warning will go away. I used ATOM here because at first this function was in common header file intended to be shared by input, joypad and HID driver since this API supports all those driver types. I think that at this point hard-coded class name is simplest solution for this warning (I can change that).

Also, I claimed the bounty.

**Comment by casdevel** [comment]
Should I check whether same or similar solution works with other video drivers?

**Comment by twinaphex** [comment]
OK, you can fix that warning - hopefully it will work for both mingw and MSVC though, that's why I had to change it. It also has to work for both CXX_BUILD and C89_BUILD as well.

> Should I check whether same or similar solution works with other video drivers?

Sure

> Also, I claimed the bounty

Yeah, I already accepted the solution. However, we have another guy in that bounty who put up $10 - Scroom, and I think we have to either wait for him to accept your solution or to wait 21 days until we can claim the bounty. I sure hope we don't have to wait on that, otherwise I have to think of something.

**Comment by casdevel** [comment]
I checked now, the bounty was awarded.

**Comment by twinaphex** [comment]
Cool, good to hear that. There might also be a little surprise coming later too.

**Comment by bparker06** [comment]
Hi @casdevel, I noticed a bug with the raw input driver. When you're playing a game and enter the menu, it is not impossible to close the menu and return to the game when pressing F1 as usual. The other input drivers do not exhibit this bug. Could you take a look at it please?

Thanks

**Comment by casdevel** [comment]
@bparker06 I'm having trouble finding the source to this problem, so this may take a while...

**Comment by casdevel** [comment]
@bparker06 #4992 and #4995 should fix this.

**Comment by Tatsuya79** [comment]
In azerty the search was on "!" and it's now on ":" (one key to the left).

There's a more annoying issue, you can't use shift or caps lock in core instance.
It's working in menu when entering a search, but if you run a core like TyrQuake or px68k, shift does nothing at all.

**Comment by casdevel** [comment]
@Tatsuya79 I'll check that, but it may take a few days since I'm currently working on something else.

**Comment by casdevel** [comment]
@Tatsuya79 Regarding search, #4995 is responsible for this, and that will stay like that. Furthermore, if you look at changes, all keymaps that starts with VK_OEM_ and ends with a number are not guarantied to be mapped to the same character on different keyboard layouts. This is nature of Windows raw input and winraw driver can't do anything about that.

Can you tel me some game(s) for px68k core that have issue with shift and/or caps lock key?
Also I want to test this with TyrQuake core but I'm having trouble setting things up, so I need little help with this. If this requires some links that shouldn't be posted here, you can email me, my GitHub email is public.

**Comment by Tatsuya79** [comment]
For px68k just load human68k (I got the one from mame software list romset). It gives you a command line prompt where you can type stuff. 
You need the bios files in a system/keropi folder for this core (read the info file).

For TyrQuake, you need the original quake id1 folder (it's important to keep it named id1).
Then just load PAK0.PAK. You can type in the console (you call it with the top left key before the numbers # in qwerty or ² in azerty).

**Comment by casdevel** [comment]
#5031 Solves issue with px86k core. TyrQuake needs more investigation...

**Comment by casdevel** [comment]
TyrQuake core don't uses libretro API as winraw driver expects (and probably other drivers too). Input driver's callback that is intended to be used for querying keyboard state is used only for arrow keys. I also noticed that, when using dinput driver, caps lock also don't working.

Based on what I seen so far, I think that this is TyrQuake issue. To be sure I'll have to play around with TyrQuake sources, and I can't promise when/whether will that happen.

**Comment by Tatsuya79** [comment]
Thanks for fixing shift and looking into it.
Indeed I see that caps lock isn't working anyway with dinput in px68k and Tyrquake, even in DosBox.
Has to be changed in the cores probably.

**Pull request merged**
