### PR TITLE
Finalize support for pthreads in emscripten

### PR DESCRIPTION
**Pull request by loganmc10**

### CODE REVIEW

**Comment by loganmc10** [comment]
By the way, I've run into a few show-stopper bugs (https://github.com/kripken/emscripten/issues/4578), that have been fixed by the emscripten people, but I'll need to wait until those fixes get merged into the next release before I implement pthreads in glupen64

**Comment by fr500** [comment]
Wouldn{t it be better to have all these rules like this:

```
diff --git a/Makefile.emscripten b/Makefile.emscripten
index 310b234..feb7cd3 100644
--- a/Makefile.emscripten
+++ b/Makefile.emscripten
@@ -37,13 +37,17 @@ endif
 #if you compile with SDL2 flag add this Emscripten flag "-s USE_SDL=2" to LDFLAGS:

 LIBS    := -s USE_SDL=2 -s USE_ZLIB=1
-LDFLAGS := -L. --no-heap-copy -s USE_ZLIB=1 -s TOTAL_MEMORY=$(MEMORY) -s ASYNCIFY=$(ASYNC) -s USE_PTHREADS=$(PTHREAD) \
+LDFLAGS := -L. --no-heap-copy -s USE_ZLIB=1 -s TOTAL_MEMORY=$(MEMORY) \
            -s EXPORTED_FUNCTIONS="['_main', '_malloc', '_cmd_savefiles', '_cmd_save_state', '_cmd_load_state', '_cmd_take_screenshot']" \
            --js-library emscripten/library_rwebaudio.js \
            --js-library emscripten/library_rwebinput.js \
            --js-library emscripten/library_rwebcam.js
 ifneq ($(PTHREAD), 0)
-   LDFLAGS += -s PTHREAD_POOL_SIZE=2
+   LDFLAGS += -s USE_PTHREADS=$(PTHREAD) -s PTHREAD_POOL_SIZE=2
+endif
+
+ifneq ($(ASYNC), 0)
+   LDFLAGS += -s ASYNCIFY=$(ASYNC)
 endif

 include Makefile.common


```

**Comment by loganmc10** [comment]
I think logically they mean the same thing, but yes it's probably a bit easier to read that way

**Comment by fr500** [comment]
@loganmc10 hmmm gamepad input no longer works (and not just autoconf)
maybe SDL2 gamepad only works with the SDL2 context driver?

**Comment by loganmc10** [comment]
It's possible, I've only tested with a keyboard (which works). I assumed the gfx context driver only affected the graphics, which still works.

**Comment by twinaphex** [comment]
The issue is here -

https://github.com/libretro/RetroArch/blob/master/gfx/drivers_context/emscriptenegl_ctx.c#L237

We might be able to work around it by adding an #ifndef HAVE_SDL2 there.

**Comment by twinaphex** [comment]
Try to see if this works and allows you to still primarily use the Emscripten EGL context driver -

https://github.com/libretro/RetroArch/commit/83be6daa93e63fade1b21901fddc7120121da210

**Pull request merged**
