### PR TITLE
Leds

### PR DESCRIPTION
**Pull request by pattheaux**
## Description

Added an LED output interface to RetroArch to allow game cores to set LEDs when the hardware is available.  I added RETRO_ENVIRONMENT_GET_LED_INTERFACE to get a callback function pointer to set a single led to a value.

The led_driver configuration can select between "null"' and "rpi".
The led1_map - led16_map configurations can be used by the driver to figure out what to do with a given LED.  The rpi implementation uses these to map an LED to a GPIO output.

### CODE REVIEW

**Comment by twinaphex** [comment]
Very cool contribution.

**Comment by UDb23** [comment]
Really nice, thanks !
Is there a chance to use the 'led status' to activate leds in overlays instead of actual leds?
Would be cool to graphically recreate leds with bezel/marquee graphics (e.g. illuminated letters in Skydiver).

**Comment by pattheaux** [comment]
@UDb23 an overlay led driver sounds like a very good idea.  I might take a stab at that if I get some free time.

**Comment by hyarsan** [comment]
This would be really cool in the Citra core, to emulate the status lights! ( Battery, StreetPass and Friends) Speaking of Nintendo 3DS, can we have the Leds function on RetroArch 3DS? ( Manipulate the status lights )

**Pull request merged**
