### PR TITLE
Try to declutter Quick Menu

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

Since now after the new replay menu item additions the default Quick Menu is somewhat noisy. Therefore I suggest we change the defaults of showing savestate submenu to ON and replay items to OFF. Also moved the replay items out of the way to the center of the menu if savestate submenu is not enabled.

### CODE REVIEW

**Comment by i30817** [comment]
I was wondering if you could add a button in the 'manage playlists' menu to refresh/clean them all. Could be the first two buttons in the list instead of a actual playlist menu.

**Comment by sonninnos** [comment]
I have thought about it, but would have to come up with a way to have refresh also to non-manual scanned playlists first.

**Comment by i30817** [comment]
Maybe a warning is good enough?

**Comment by hizzlekizzle** [comment]
having an option to refresh/clean all playlists on startup is oft-requested, as well /OT

on-topic: should BSV replays get a submenu? I also think it may be worth revisiting the redundant settings links, as well. I've long thought a single 'settings' link should cover it, but I think there's also an argument to not have that stuff in the quick menu at all.

**Pull request merged**
