### PR TITLE
(RGUI) Add option to hide associated cores in playlists

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

When viewing a playlist, RGUI appends the currently associated core to each entry. This clutters the screen, and is also somewhat inconsistent with the other menu drivers (where playlists shown in 'tabs' only contain the content name).

This PR adds a new `Show associated cores in playlists` option under `Settings > Playlists` which allows the core name to be hidden. Here's an example:

- `Show associated cores in playlists` `ON`: (wall of text!)

screenshot_2019-02-17_14-17-36

- `Show associated cores in playlists` `OFF`: (nice and tidy)

screenshot_2019-02-17_14-18-10

(Internally, the PR also changes the way that playlists are identified. Instead of performing string comparisons with the current menu title, I realised that you're meant to check the `label` value provided by `rgui_populate_entries()`. Playlist detection was accurate before, but now it cannot ever fail even if the user engineers a convoluted edge case...)

For perfectly 'clean' playlists, we still need to improve the displayed title (it's currently a file path, whereas it should be a playlist name). I'll address this in my next PR.

### CODE REVIEW

**Comment by fr500** [comment]
Do you have any idea on how to implement sublables on playlists?

**Comment by jdgleaver** [comment]
> Do you have any idea on how to implement sublables on playlists?

I need to study the code in more detail, but it certainly looks doable.

This is a fantastic idea. It would allow us to clean up the 'history' and 'favourites' playlists too, and also add some extra flavour to playlists in general. I'm assuming we'd want the sublabel to contain the currently associated core + playtime. Does that sound good?

RGUI would support this immediately (although I'd need to rework this PR...). I think XMB, Ozone et al. would support this for 'history', 'favourites' and 'collections', but the playlist tab code would need to be rewritten.

There'd also be a performance hit (I guess playlist load time would maybe double?) - this is not an issue on most platforms, but we'd probably want to make 'playlist sublabels' optional for very slow devices.

I have a couple more small things to add to RGUI - as soon as I'm done, I'll take a look at this sublabel business. :slightly_smiling_face:

**Comment by fr500** [comment]
Yeah that I would want to do, so it can show core and playtime as the bare minimum, and other metadata if available.

**Comment by jdgleaver** [comment]
I'll see what I can do... :wink:

**Pull request merged**
