### PR TITLE
Remove commited Mac binaries

### PR DESCRIPTION
**Pull request by bkoropoff**
I assume these were added by accident.

### CODE REVIEW

**Comment by RobLoach** [comment]
Are these part of .gitignore?

**Comment by twinaphex** [comment]
Yes, this was definitely an error. Our/my bad.

**Comment by bkoropoff** [comment]
You can rebase to squash the fix and force-push the result, although anyone who has already updated will get an error trying to do an ordinary `git pull`.

**Comment by RobLoach** [comment]
`git clone --depth=1` speeds things up.

**Pull request merged**
