### PR TITLE
Basic lobby system (don't merge, just for tracking)

### PR DESCRIPTION
**Pull request by fr500**
I started implementing basic matchmaking. I will try to add a "rooms" list the user can check and join.
So far I have only implemented game announcement.

Once a host starts hosting an announce is sent to http://lobby.libretro.com/

If you check that page after an announcement has been made it looks like this:

```
Andres
201.183.128.86
55436
Snes9x
1.53 d43c7e5
Super Mario Kart (USA)
002f
1484623256
```

```
Andres   --> username
201.183.128.86 --> IP address (from the connection, not posted by the hoster)
55436 --> port
Snes9x --> core name
1.53 d43c7e5 --> core version
Super Mario Kart (USA) --> game name
002f --> game CRC
1484623256 --> timestamp?
```

There are still a few issues with the register script.
~~As far as I can see it adds duplicate entries. If **username** **port** and **ip** are matched it should just overwrite.~~

~~https://github.com/RobLoach/libretro-netplay-registry/issues/1~~

**TO-DO**
- ~~Afaik, we don't have the CRC of the loaded game in memory, 0000002f is just a placeholder~~ needs to be implemented for full_path, two codepaths there I think, if block_extract the CRC of the whole archive, otherwise the CRC of the file from within the archive
- ~~Announce periodically, entries timeout after a few minutes~~
- ~~Client "rooms" implementation (I started adding the gui, but downloading the file and parsing it may be beyond my skill set~~"
- ~~Move the whole netplay menu to quick menu since you can start hosting at runtime it makes more sense there~~ (copied the menu for now)
- Add settings to enable or disable announcements
- What's timestamp for? @RobLoach
- Add a bool to check if the room needs a password

### CODE REVIEW

**Comment by RobLoach** [comment]
> What's timestamp for? @RobLoach

The timestamp is when the entry was created. Allows us to know when to remove the entry.... We could remove it once we switch to another storage method like SQLite.

**Comment by twinaphex** [comment]
Why was this closed?

**Comment by fr500** [comment]
I won't have time to work on it this week maybe next one

**Comment by twinaphex** [comment]
So why close something for that reason? Might as well keep it open so that others can look into it.

**Comment by fr500** [comment]
It's still there... it isn't removed or deleted, it's just closed, also if
I rebase with the PR things get screwy.

**Comment by twinaphex** [comment]
Alright.

**Comment by fr500** [comment]
image

**Comment by fr500** [comment]
It's still just a placeholder, the idea would be to have the room list below that

**Comment by fr500** [comment]
image

Parsin the room data works now, need help to add the menu items

**Comment by fr500** [comment]
image

As it stands now it scans succesfully, needs sublabels now for the extra info.

@Kivutar guess we need some extra icons, I was thinking a world globe for the category and something like the icon in the PSP link play for the rooms (with a lock and without for rooms with password)

@twinaphex ideally we would have a function that scans all the existing playlists for a matching CRC and returns the rom path to try to get one-button connect working

**Comment by twinaphex** [comment]
OK, I can look into that CRC scanning function. I think it would be best to make this a task though.

Secondly, tell me what sublabel text needs to be implemented and for which entries and I can take a look.

**Comment by RobLoach** [comment]
Could look at other examples out there. Here's what Battlefield 4 server browser looks like....
serverbrowser

Label
```
Username
```

Sublabel
```
Gamename - Corename
```

**Comment by fr500** [comment]
This is "pretty much ready" except for content loading.
The killer feature would be a one click connect.

**Comment by twinaphex** [comment]
@Kivutar Can you help radius with creating this function now?

**Comment by RobLoach** [comment]
1. When selecting Refresh Room List
2. Scan through each Room found
3. Grab the Room's CRC
4. Search through every Playlist for the Game Room's CRC
5. Have it so that when the user chooses that room, load the match playlist item, and join the server

**Comment by fr500** [comment]
The room doesn't have a CRC, the game does and this is not viable for many cores. When needs_fullpath is defined the CRC is never stored in memory.

**Comment by RobLoach** [comment]
We have the CRC in the playlists though. May not be for all games, however...

```
/home/rob/Games/Sega - Mega Drive - Genesis/Streets of Rage 2 (USA).zip#Streets of Rage 2 (USA).md
Streets of Rage 2 (USA)
DETECT
DETECT
E01FA526|crc
Sega - Mega Drive - Genesis.lpl
```

**Comment by fr500** [comment]
The game CRC needs to be in memory on the load event not in the playlist. Even if the user doesn't use playlists.

**Comment by fr500** [comment]
Ok this works, it can connect to games underway, and it can do a deferred connection after a game is loaded.

Missing:
- One click connect (look for correct core, correct game and load)
- Connect using to a room that has specified a different port that what the client has configured

**Pull request merged**
