### PR TITLE
Vulkan: Create command pool for correct queue family.

### PR DESCRIPTION
**Pull request by Themaister**

### CODE REVIEW

**Comment by twinaphex** [comment]
@Themaister By stubbing out this line, I can get Vulkan to work again on my Intel HD 4K Linux setup.

https://github.com/libretro/RetroArch/blob/master/libretro-common/vulkan/vulkan_symbol_wrapper.c#L472

What do we do about this?

**Comment by Themaister** [comment]
hm ... Probably easiest to add some exceptions to the symbol loading script to skip certain functions which we aren't going to be using.
For now, just commenting out the offending function is fine with me.

**Comment by twinaphex** [comment]
Well, I could get it to just not return false when it cannot find the symbol.

Also, this was while testing it on X11. On Wayland I can no longer get it to work anymore, it reports this:

 RARCH_ERR("[Vulkan]: Could not find instance extensions. Will attempt without them.\n");

Probably extension-related as well.

**Comment by twinaphex** [comment]
Pushed this for now, ugly but it work.

https://github.com/libretro/RetroArch/commit/1c1c1fa32cef431944b02a66ac6c6f80362a6a9b

I will still need some input on the Wayland issue though and what we could possibly do there.

**Comment by twinaphex** [comment]
According to preliminary logging results, inside vulkan_find_extensions, it cannot find  -

VK_KHR_wayland_surface - VK_KHR_surface
VK_KHR_wayland_surface - VK_KHR_xcb_surface
VK_KHR_wayland_surface - VK_EXT_debug_report

This then triggers the error 'could not find instance extensions. Will continue without them'.

**Pull request merged**
