### PR TITLE
Display Help menu (boolean)

### PR DESCRIPTION
**Pull request by lasers**

### CODE REVIEW

**Comment by AlexFolland** [comment]
Can you separate the line ending stuff into another PR?  Also, what exactly is this meant to do?

**Comment by lasers** [comment]
Add `?w=1` to the link to omit whitespaces.
https://github.com/libretro/RetroArch/pull/4188/files?w=1

There's an UI option to toggle off "Core / No Core" on bottom left corner and to toggle off "Date/Time" on top right corner. This toggles off "Help" in Main Menu.

**Comment by AlexFolland** [comment]
Those are for constantly-visible text labels, but this is for a menu entry.  This seems inconsistent.

**Comment by lasers** [comment]
After learning how RetroArch works, one may not want to visit it again. I'm not sure what `Settings->UserInterface->Menu->ShowAdvancedSettings` does right now, but maybe it could be useful for that toggle instead in the future along with other changes.

**Comment by fr500** [comment]
I don't think we want this at all

**Pull request closed without merging**
