### PR TITLE
libusb hotplug fix

### PR DESCRIPTION
**Pull request by hiddenasbestos**
Only try and register a hotplug callback if the feature is supported on the platform.

n.b. I've added code to store the hotplug state for platforms that do support it, but left the cap check disabled as I found it in the code.

### CODE REVIEW

**Comment by hiddenasbestos** [comment]
Paging @bparker06 , hope this patch is okay - my GameCube pads don't work without it as the callback registration fails.

**Comment by bparker06** [comment]
The if block at https://github.com/hiddenasbestos/RetroArch/blob/ac38f866de67ff3feb8d2b6d50ad4721c076c134/input/drivers_hid/libusb_hid.c#L591 would never be reached because `can_hotplug` is always false.

**Comment by hiddenasbestos** [comment]
Well I should have probably followed through and removed the #if 0 block and comment about FreeBSD/Windows around the caps. check - letting the libusb implementation decide the value of can_hotplug, However I felt a bit shy since I'd stepped on your code earlier, so I held back.

**Comment by hiddenasbestos** [comment]
Hi @bparker06, I've updated my commit to completely disable the hotplug registration callback.

**Comment by hiddenasbestos** [comment]
p.s. After re-reading the comment at the point where the cap check is made, it sounded to me like even trying to call the libusb_has_capability function on FreeBSD would fail (I can't test that). This update is based on that assumption.

**Comment by bparker06** [comment]
I don't think we should disable the hotplug callback for all platforms since it does work on some of them. If `LIBUSB_API_VERSION > 0x01000102`, I think it's safe to assume that we can at least check for hotplug support, just don't `goto error` if the capability is missing, but don't register the callback in that case either. On FreeBSD (or more specifically, API <= 0x01000102), `libusb_has_capability` is not a function at all, so it must be ifdef'ed out in that case. Hope this makes sense.

**Comment by hiddenasbestos** [comment]
Okay that makes sense. Should the code assume on API <= 0x01000102 that hot plugging is _not_ available?

**Comment by bparker06** [comment]
It should assume that hotplug IS available, (as long as we're not on Windows of course, but this check may be version-agnostic for now) but `libusb_has_capability` is just not a function until after 102.

**Comment by bparker06** [comment]
by the way, any idea why this might happen with the libusb backend on FreeBSD?
`[ERROR] Interface not found (4-PLAY PORT.1) (VID/PID: 16d0:0d04).`

**Comment by hiddenasbestos** [comment]
I'm afraid I have no idea, I've not really used libusb before yesterday. On Windows (10) it tries lots of things too - external hard drives, my usb wifi adapter, but I dont think I've seen it get to the "interface not found" stage for anything other than input devices.

**Comment by hiddenasbestos** [comment]
Going to close this and reimplement based on our discussion. I'm going to have it on old apis that it should assume it can try to register a callback but not fail if it can't  (and correct the can hotplug flag with this new info). If caps check is available it'll not even try if driver says no (eg. on Windows)

**Comment by hiddenasbestos** [comment]
Hi @bparker06 - not sure if you saw my reply to your FreeBSD issue above. Anyway, I can't really help, I'm not sure what's going on there and I don't have a 4PLAY / bliss-box to test on Windows, sorry.

**Comment by bparker06** [comment]
Oops, I missed the earlier reply. Yea it happens with any gamepad. Thanks

**Pull request closed without merging**
