### PR TITLE
Fixed math to translate a physical address to the memory descriptor index + offset

### PR DESCRIPTION
**Pull request by leiradel**

### CODE REVIEW

**Comment by meleu** [comment]
I can confirm. The Hungriest Runner cheevo is working fine with this fix. :-)
Tested with [Snex9x 2010](https://github.com/libretro/snes9x) and [bsnes](https://github.com/libretro/bsnes-libretro) and it's working fine.
Not working with [Snex9x](https://github.com/libretro/snes9x).

**Comment by fr500** [comment]
Snes9x is not building currently in several platforms, I think @twinaphex is trying to implement MSU1 support

**Comment by meleu** [comment]
@fr500 could you confirm which one is the actual "snes9x next"?

I think it's the [Snes9x 2010](https://github.com/libretro/snes9x) (based on the description) but @leiradel says that [Snes9x](https://github.com/libretro/snes9x) is the "snes9x next".

Now I'm a little confused...

**Comment by Alcaro** [comment]
Are you aware that you're linking the same repo as if it's two different repos?

snes9x2010 is snes9x-next, snes9x is snes9x mainline. Nothing else.

**Comment by meleu** [comment]
@Alcaro my bad. Sorry. I edited with the correct link.
Snes9x 2010 = https://github.com/libretro/snes9x2010
Snes9x = https://github.com/libretro/snes9x

**Comment by twinaphex** [comment]
@leiradel We have a C89_BUILD issue now - 

http://hastebin.com/azewujerus.pas

**Comment by leiradel** [comment]
@twinaphex I've fixed the C89 build.

I've been told the snes9x_next core is built from https://github.com/libretro/snes9x so yeah, I'm too a bit confused about which is which.

**Pull request merged**
