### PR TITLE
Unify timedate ENUMs and cleanup

### PR DESCRIPTION
**Pull request by im4potato**
## Description

This is an updated version of my previous PR (#10574) that removes redundant ENUMs, makes the remaining ENUMs more generic now that they are used in multiple places, and brings all languages to ISO8601 compliance. Previously, the settings were a mixture of `/` and `-`, now all date and time output consistently uses `-`.

There was some discussion on #10574 about adding a new setting that would allow the user to select the character that separates `YYYY`, `MM`, and `DD`, which I'd still like to work on, but this PR sets the foundation for that.

## Related Pull Requests

#10574

## Reviewers

@twinaphex @hizzlekizzle

### CODE REVIEW

**Comment by Ryunam** [comment]
Hi @im4potato, would you be okay with me looking into the option to choose the separator? I think I can whip up something before the weekend and I would definitely like to restore the `/` as a selectable option. Let me know if that’s okay or if you’d rather work on it by yourself.

**Comment by im4potato** [comment]
Go for it, I've only just begun to look into how to add options like that to RA and I'd be interested to see how you would do it.

This might complicate things a bit, but would it be possible to make it so that whatever separator is selected is also what appears in the time and date options list?

**Comment by Ryunam** [comment]
I think so, I’ll have to experiment a little bit with it, but it should be doable!

**Comment by jdgleaver** [comment]
@Ryunam Oh man... Many apologies - I only noticed your comment about implementing a configurable date separator *after* I'd already finished this: #10707

Really sorry...  :(

**Comment by Ryunam** [comment]
It's totally okay! I had managed to implement a separator option on my local branch, but I still had to make it work with the runtime log too, so I'm not sure how long it would have taken me to complete it. I'm taking a look at your code now and my implementation was definitely very similar to how you did it, so at least I'm learning :)

**Comment by jdgleaver** [comment]
Thanks for being so understanding :)

(I hadn't really looked at the PR here at all... When I went to link to it in mine, and saw your comment, I just felt terrible about it!)

Anyway, glad to hear that you're getting a handle on the menu code - I'm sure your implementation would have been spot on!

**Pull request merged**
