### PR TITLE
[PS2] Open RetroArch menu from Core

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description

This PR enables the users to open the RArchMenu pressing at the same time `Select&Start`.
Additionally in the `GFX` driver now I need to clean the screen otherwise the RGUI was visible once the user turns back to the game/core.

## Related Issues

Disable for now the time function because is still buggy.

### CODE REVIEW

**Comment by bparker06** [comment]
FYI There are a lot of style issues in the ps2_gfx file. Mixing tabs and spaces, not always using 3 spaces, braces not on their own lines, etc.

There are also C89 errors, with variables not declared at the top of a block.

**Comment by fjtrujy** [comment]
> FYI There are a lot of style issues in the ps2_gfx file. Mixing tabs and spaces, not always using 3 spaces, braces not on their own lines, etc.
> 
> There are also C89 errors, with variables not declared at the top of a block.

Let me fix them.

Thanks

**Comment by fr500** [comment]
hmmm, that's a lot of code for something you can achieve with a default no?
`input_menu_toggle_gamepad_combo = "4"`

would achieve this

**Comment by fr500** [comment]
```
#if defined(__CELLOS_LV2__) || defined(_XBOX1) || defined(_XBOX360)
static unsigned menu_toggle_gamepad_combo    = INPUT_TOGGLE_L3_R3;
#elif defined(VITA)
static unsigned menu_toggle_gamepad_combo    = INPUT_TOGGLE_L1_R1_START_SELECT;
#elif defined(SWITCH)
static unsigned menu_toggle_gamepad_combo    = INPUT_TOGGLE_START_SELECT;
#else
static unsigned menu_toggle_gamepad_combo    = INPUT_TOGGLE_NONE;
#endif
```

Just add the correct code there for PS2 😂

**Pull request merged**
