### PR TITLE
Improved Turkish Language

### PR DESCRIPTION
**Pull request by fpscan**
I mostly finished Desktop Menu texts, translated Cheats section and still digging for some words to be sure. 
I also saw a unnecessary space in us.c file and wanted to delete it, for tidy up, somehow it says thousands line differences, anychance we can ignore that one?

### CODE REVIEW

**Comment by fpscan** [comment]
Not sure why The Travis CI build failed, I just changed text files and uploaded into my fork then PR for those files, nothing else, did I missed a step?

**Comment by orbea** [comment]
Don't worry about the xcode travis build, its already broken and certainly not your fault.

However these files are changing all the line endings, can you please fix your editor to not to that?

**Comment by fpscan** [comment]
> Don't worry about the xcode travis build, its already broken and certainly not your fault.
> 
> However these files are changing all the line endings, can you please fix your editor to not to that?

Sorry for that but not sure why its act like that and not sure how to prevent it, I am using latest Sublime Text 3 but I could use something else if its Sublime Text issue.

**Comment by orbea** [comment]
You need to configure your editor to use unix line endings, but I am not sure how to do that with sublime text.This link might help you.

https://blog.hostonnet.com/how-to-set-unix-as-default-line-ending-in-sublime-text

**Comment by fpscan** [comment]
> You need to configure your editor to use unix line endings, but I am not sure how to do that with sublime text.This link might help you.
> 
> https://blog.hostonnet.com/how-to-set-unix-as-default-line-ending-in-sublime-text

Oh okay, you are life saver, so I set as unix now, I assume it won't act like that, beside that the process that I following ( translating .c & .h and putting them into my retroarch and Requesting Pull) is legit, right?

**Comment by orbea** [comment]
If you could change the current files to unix line endings now it would help. Its kind of hard to review what is being changed when the whole file is being changed. :)

This link might help.

https://medium.com/@Rascle/fix-line-endings-in-sublime-text-3-35d926d1c041

**Comment by fpscan** [comment]
@orbea changed to Unix from Windows and did some translation but didn't worked I guess, however as a default it is Unix and .c and .h files are unix as well. I should use something else I guess... any suggestion? Notepad++ is fine?
image

**Comment by orbea** [comment]
Sorry I can't advise on windows editors, I use `vi` and I don't think that will work for you.

Looking at the commit diff it looks like your fixed the line endings, but they are still changed for `intl/msg_hash_us.c`. Can you ifix it for that file too?

**Comment by fpscan** [comment]
> Sorry I can't advise on windows editors, I use `vi` and I don't think that will work for you.
> 
> Looking at the commit diff it looks like you fixed the line endings, but they are still changed for `intl/msg_hash_us.c`. Can you ifix it for that file too?

Oh no worries, I changed the `us.c` as well, can you check? So is that mean that I can use Sublime Text 3 without worries?

**Comment by orbea** [comment]
Yes it looks fine now!

**Comment by orbea** [comment]
@bparker06 Can you review this?

**Comment by fpscan** [comment]
Hey @orbea how are you doing? Thank you for checking, If this going to live I am going to update another version which I have been working on last 6 days, it has more translation than this one :) 

@bparker06 I hope you are doing fine :)

**Comment by orbea** [comment]
I'm not sure what to do about the `C89_BUILD` errors, anyone else know?
```
intl/msg_hash_tr.c: In function ‘menu_hash_get_help_tr_enum’:
intl/msg_hash_tr.c:965:30: error: string length ‘524’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
                              "germe filtresini etkiler.");
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
intl/msg_hash_tr.c:1229:30: error: string length ‘568’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
                              "ve bunu varsayılan olarak bırakın.");
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC libretro-common/compat/compat_strl.c
CC libretro-common/formats/image_texture.c
cc1: some warnings being treated as errors
make: *** [obj-unix/release/intl/msg_hash_tr.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by fpscan** [comment]
> I'm not sure what to do about the `C89_BUILD` errors, anyone else know?
> 
> ```
> intl/msg_hash_tr.c: In function ‘menu_hash_get_help_tr_enum’:
> intl/msg_hash_tr.c:965:30: error: string length ‘524’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
>                               "germe filtresini etkiler.");
>                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> intl/msg_hash_tr.c:1229:30: error: string length ‘568’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]
>                               "ve bunu varsayılan olarak bırakın.");
>                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CC libretro-common/compat/compat_strl.c
> CC libretro-common/formats/image_texture.c
> cc1: some warnings being treated as errors
> make: *** [obj-unix/release/intl/msg_hash_tr.o] Error 1
> make: *** Waiting for unfinished jobs....
> ```
I guess this is new, haven't seen this error before.

I also checked translations with my Switch, however some characters like " ı - ö - ü - ş " which is unique for Turkish, shown as ? question mark but it works fine on PC version

**Comment by twinaphex** [comment]
Since the C89 thing might be too hard to fix, I could do that instead after merging it.

Is everybody fine with that?

**Comment by fpscan** [comment]
> Since the C89 thing might be too hard to fix for OP, I could do that instead after merging this PR.
> 
> Is everybody fine with that?

Yeah sure no worries, there is few lines that I want to add as well, anychance I add those lines then let you know its okay? It will be done tonight and I will let you know tomorrow?

**Comment by orbea** [comment]
> Is everybody fine with that?

Fine by me, once I see the fix I'll know what to do next time. :)

**Comment by fpscan** [comment]
@twinaphex Okay So I just added these https://github.com/libretro/RetroArch/pull/8602/commits/cb010452769cfb3fe748e5fb033b9b4f119f6448 and its good to go... thank you:)

**Comment by bparker06** [comment]
per Twinaphex, can you also add a MENU_ENUM_LABEL_VALUE_LANG_TURKISH entry that has "Turkish" written in Turkish?

**Comment by fpscan** [comment]
> per Twinaphex, can you also add a MENU_ENUM_LABEL_VALUE_LANG_TURKISH entry that has "Turkish" written in Turkish?

If this going to be in below```
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_LANG_TURKISH
"Turkish"```, then we can say `"Türkçe"` instead `Turkish`

**Comment by LazyBumHorse** [comment]
About the `error: string length ‘524’ is greater than the length ‘509’ ISO C90 compilers are required to support`, the message is already pretty accurate, but here's a full explanation anyways:

According to the C90 standard (5.2.4.1 Translation limits),
> The implementation shall be able to translate and execute at least one program that contains
at least one instance of every one of the following limits:
> - (...)
> - 509 characters in a character string literal or wide string literal (after concatenation)

(Worth of note: Since C99 this minimum was increased to 4095.)

In other words, the concatenated string literals in line 965 and 1229 are longer than a compiler needs to support, which is to say there _could be_ a compiler out there which might not be able to compile this.

This is _not_ an "error" but only a warning, gcc (and clang and MSVC and probably every other compiler we are ever going to use) is absolutely not limited by this.
The standard even goes as far as to say that a compiler should not use fixed limits whenever possible.

We get this as an error because the `C89_BUILD` uses `-pedantic -Werror=pedantic` and `pedantic` implies `overlength-strings` and it truly is pedantic.

There are 2 solutions to this, one is to silence the warning via `-Wno-overlength-strings`, the other one - if we really really have to - is to split up the string literals and copy them in parts.
In this case the output is written to a string `s` via `snprintf` anyways, so instead of this
```
snprintf(s, len,
   <concatenated string literal which is too long>,
   <parameters>);
```
one can write something like this:
```
const char *t = <first part>;
snprintf(s, len,
   "%s"
   <second part>,
   t,
   <parameters>);
```

**Pull request closed without merging**
