### PR TITLE
fix building against ffmpeg 5.0

### PR DESCRIPTION
**Pull request by alucryd**
## Description

Adds compatibility with ffmpeg 5.0, still builds fine against ffmpeg 4.4.

Disclaimer: I don't speak C/C++, please consider this experimental, and I'd welcome pointers on how to test the changes, never looked into what purpose ffmpeg serves in retroarch.

## Related Issues

https://github.com/libretro/RetroArch/issues/13530

### CODE REVIEW

**Comment by keithbowes** [comment]
> never looked into what purpose ffmpeg serves in retroarch.

It allows you to record videos (in MP4 or WebM format) to share on YouTube, Dailymotion, or similar, when you press whatever `input_movie_record_toggle` is bound to (IIRC 'o' by default) or start with `retroarch -r <file>`.  Without it, it records in the BSV format, which you can replay in retroarch but can't share on a video-sharing platform.

**Comment by hizzlekizzle** [comment]
getting it building is certainly better than not building, though I believe there was some pre-existing breakage caused by FFmpeg ABI changes prior to this release. We have been discussing whether to vendor a known-working snapshot, but if 5.0 is going to be considered an LTS release, it's probably best to kick that can and just update to 5.0 compatibility for now.

**Comment by alucryd** [comment]
Thanks for the heads up, I'll give video recording a try then and report back.

**Comment by hizzlekizzle** [comment]
Just FYI, I believe the video recording was still functional. It was just the audio recording that was using a deprecated/discontinued function/call.

**Comment by alucryd** [comment]
I'm getting a segfault with these changes. I addressed some incompatible pointer types (AVCodecContext <-> AVCodecParameters) but it didn't help. I'm afraid I'm in way over my head, but hopefully the current commits can help in some way.

I can confirm that video recording works in vanilla 1.10.0, but there's no audio indeed. Here's the console log in case it can be of use:
```
[libx264 @ 0x56137a00f4c0] using SAR=1/1
[libx264 @ 0x56137a00f4c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x56137a00f4c0] profile High, level 1.3, 4:2:0, 8-bit
[libx264 @ 0x56137a00f4c0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:-1:-1 analyse=0x3:0x3 me=dia subme=1 psy=1 psy_rd=1.00:0.15 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=25.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 pb_ratio=1.30 aq=1:1.00
[matroska @ 0x56137ac7ef80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[matroska @ 0x56137ac7ef80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[swscaler @ 0x7f8890026140] Warning: data is not aligned! This can lead to a speed loss
[aac @ 0x56137ad09600] Qavg: nan
[libx264 @ 0x56137a00f4c0] frame I:4     Avg QP:13.56  size:  2156
[libx264 @ 0x56137a00f4c0] frame P:297   Avg QP:23.86  size:  1181
[libx264 @ 0x56137a00f4c0] frame B:213   Avg QP:24.74  size:   383
[libx264 @ 0x56137a00f4c0] consecutive B-frames: 37.7% 17.5% 10.5% 34.2%
[libx264 @ 0x56137a00f4c0] mb I  I16..4: 64.5% 14.3% 21.2%
[libx264 @ 0x56137a00f4c0] mb P  I16..4: 14.1%  5.0%  4.4%  P16..4: 35.5%  0.0%  0.0%  0.0%  0.0%    skip:40.9%
[libx264 @ 0x56137a00f4c0] mb B  I16..4:  1.7%  0.5%  0.3%  B16..8: 22.3%  0.0%  0.0%  direct: 7.5%  skip:67.8%  L0:45.0% L1:45.2% BI: 9.8%
[libx264 @ 0x56137a00f4c0] 8x8 transform intra:20.8% inter:12.9%
[libx264 @ 0x56137a00f4c0] coded y,uvDC,uvAC intra: 34.2% 43.5% 33.3% inter: 13.8% 11.8% 5.2%
[libx264 @ 0x56137a00f4c0] i16 v,h,dc,p: 49% 42%  9%  0%
[libx264 @ 0x56137a00f4c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  9% 37% 16%  7%  5%  2%  8%  2% 14%
[libx264 @ 0x56137a00f4c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 42% 14%  5%  3%  3%  5%  2%  5%
[libx264 @ 0x56137a00f4c0] i8c dc,h,v,p: 46% 41%  9%  4%
[libx264 @ 0x56137a00f4c0] Weighted P-Frames: Y:17.5% UV:12.1%
[libx264 @ 0x56137a00f4c0] kb/s:410.08
```

**Comment by keithbowes** [comment]
> I'm getting a segfault with these changes. I addressed some incompatible pointer types (AVCodecContext <-> AVCodecParameters) but it didn't help.

Well, casting only silences compiler warnings but isn't going to make code work, unless the data types are compatible.  For example, in GTK, `gtk_window_new` returns `GtkWidget`, which can then be cast to `GtkWindow` for calls to e.g. `gtk_window_set_title()`, because those two structures are compatible.  On the other hand, I seriously doubt that `AVCodecContext` and `AVCodecParameters` are compatible, so to fix the segfault, you'd have to find a way to get the proper structure.  Maybe the functions `avcodec_parameters_from_context` and `avcodec_parameters_to_context` will do the trick.

For the time being, it might be best just to disable building with ffmpeg 5 in qb/config.libs.sh, until getting it to work with ffmpeg 5 is done.

**Comment by alucryd** [comment]
I don't think I made any cast errors, but since it doesn't work that's definitely a possibility. In any case, we have so many packages that don't build against ffmpeg 5.0 that we might just maintain an additional ffmpeg 4.4 in our repos.

**Comment by keithbowes** [comment]
No, it wasn't a cast error.  The problem was that the `filename` member of `AVFormatContext` in earlier versions was defined as `char[1024]`, so the compiler knew to allocate enough memory for 1024 characters; however, the `url` member is defined as `char *`, so the compiler doesn't know how much memory to allocate and you must do it manually.

The cause of the segmentation fault was easy to solve.  I just used [gdb](https://www.sourceware.org/gdb/), which pointed me to the exact line that produced the problem.  The hard part was figuring out why there was no audio when linked against FFmpeg 5.

**Comment by alucryd** [comment]
Thanks for the explanation, not used to these problems as I mainly write Rust today, and was on Python before that. BTW, there was no audio with ffmpeg 4.4 either, you probably fixed it there as well!

**Comment by twinaphex** [comment]
Is this still necessary to be merged or did other merged PRs obsolete this?

**Comment by alucryd** [comment]
This was tackled in https://github.com/libretro/RetroArch/pull/13611, closing this one. Thanks.

**Pull request closed without merging**
