### PR TITLE
misc updates

### PR DESCRIPTION
**Pull request by fr500**

### CODE REVIEW

**Comment by fr500** [comment]
related: https://github.com/libretro/retroarch-assets/issues/95

**Comment by fr500** [comment]
Well, we gotta differentiate, so it's either the icon or we replace Nickname with the room type, otherwise with the RA version it gets to 4+ lines and it starts clipping.

This is how it's looking ATM:

image

image

Maybe changing both (the icon and the title) would be better?
Let me know what you think

I was thinking something like

Internet game: $nickname
Local game: $nickname
Internet game (mitm):  $nickname

**Comment by fr500** [comment]
Adding this to my todo list:
https://github.com/libretro/RetroArch/issues/5013

**Comment by fr500** [comment]
@baxysquare @Kivutar 
so what do you think, change title and icon, just title or just icon?

If it's icon I need icons for mitm

>@baxysquare imho the netplay - iroom icon is perfect, it should be renamed to:
>room_internet.png
>the netplay - LAN Room icon is fine too imho
>should be room_lan.png
>we need one for mitm though, maybe you could put a server in the center area?
>should be room_mitm.png
>As for password indication, maybe put a lock in the lower white thingie instead of on top of the badge?

**Comment by fr500** [comment]
SRAM autosave sometimes causes a lockup when joinining a lobby so I added this to prevent that https://github.com/libretro/RetroArch/pull/5160/commits/930addaa5c82654160f1087c1d0ea8e98902f0e7

**Comment by bparker06** [comment]
I agree the title should be changed as well:

Internet: $nickname
LAN: $nickname
Internet (MITM): $nickname

Perhaps we should get in the habit of not using "game" everywhere and just say content? Since there are non-game cores.

**Pull request merged**
