### PR TITLE
(xmb) Make xmb_node_t smaller

### PR DESCRIPTION
**Pull request by heuripedes**
Each xmb_node_t instance used over 4KiB of memory even when it didn't
need to. In big list like MAME (30+ thousand entries) RetroArch would
consume over 100MiB (4096 bytes * 30000) just to hold all xmb_node_t
instances.

heaptrack:
https://imgur.com/a/P332A

ps_mem.py output before:

    126.1 MiB +   4.1 MiB = 130.2 MiB	retroarch

ps_mem.py output after:

    70.1 MiB +   4.1 MiB =  74.2 MiB	retroarch

**edit:** these results are after loading a MAME playlist.

### CODE REVIEW

**Comment by twinaphex** [comment]
That's a significant reduction, awesome job.

BTW, were you able to reproduce the crashes with XMB when loading shader presets and/or loading shader passes, or is that fixed as of this PR too?

**Comment by heuripedes** [comment]
No, I was not able to reproduce it.

**Comment by twinaphex** [comment]
Try loading for instance fast-bilateral-nedi.cgp, still crashes for me here on Windows with XMB, but loads fine with MaterialUI.

**Comment by heuripedes** [comment]
I don't get any crashes or valgrind/asan "invalid access" errors when I load the CRT emulation glslp files (I don't have Cg support). Neither nedi nor nnedi3 glslp files seem to be working.

**Comment by twinaphex** [comment]
The crash happens with fast-bilteral-nedi.glslp too.

**Pull request merged**
