### PR TITLE
More metadata categories in the explore menu

### PR DESCRIPTION
**Pull request by TheRetroPirate**
There aren't enough categories for my taste so I added some more.
Most of this data can be taken from mobygames which I'm also working on.

**Achievements**, games supported by RetroAchivements
this data can be acquired from the RA API

**Category**, redump style category e.g. Games, Demos, Translations, Hacks, etc.
for redump this data is already available in their DAT files
for no-intro and other roms this can mostly be guessed based on the filename while defaulting to the Games category

**Language**, which language the game supports
can be inferred from the set names and from redump webpage
for translations from the filename e.g. [T+En]

**Region**, World, USA, Europe, etc.
from rom country

**Console exclusive**, only on console
use data from mobygames

**Platform exclusive**, only has a single platform
use data from mobygames

**Rumble**, if the game supports rumble
use data from mobygames

**Score**, 1..10 in 10 increments up to 100
use data from mobygames and/or RetroAchivements (for hacks)

**Media**, CD, DVD, BD, Cartridge, Tape, Digital, etc.
redump already has this info, adding other systems should be easy as most use the same media

**Controls**, the controls supported by the game e.g. gamepad, keyboard, mouse, etc.
use data from mobygames

**Artstyle**, art style of the game e.g. Anime
use data from mobygames

**Gameplay**, e.g. Shooter
use data from mobygames

**Narrative**, e.g. War
use data from mobygames

**Pacing**, e.g. Turn-based
use data from mobygames

**Perspective**, e.g. 1st-person
use data from mobygames

**Setting**, e.g. Fantasy, Sci-fi / futuristic
use data from mobygames

**Visual**, e.g. Free-roaming camera
use data from mobygames

**Vehicular**, e.g. Space flight
use data from mobygames

Here's a screenshot from my build.
Untitled

### CODE REVIEW

**Comment by twinaphex** [comment]
very cool, i love this idea.

**Comment by i30817** [comment]
Much better. Although still not anything close to perfect, as is usual with databases trying to be ontologies without enough user contribution.

**Comment by i30817** [comment]
Is it possible to add metadata about controller types?

Ie: snes games supporting snes mouse, games with multiple controller support in the dreamcast and wii/gamecube, ps1 games that require dualshock etc.

**Comment by ofry** [comment]
@TheRetroPirate could you answer to @i30817 question?

**Pull request merged**
