### PR TITLE
(Vulkan) Implement HDR viewport readback

### PR DESCRIPTION
**Pull request by CRefice**
## Description

This PR adds HDR support for screenshots (aka viewport reading, aka readback) to the Vulkan video driver.
This is implemented on the GPU by running a pipeline which converts the HDR10 pixels in the backbuffer to BGRA8 format through a fragment shader which also applies tonemapping if necessary. The resulting image buffer is saved to an image using already-existing scaler logic for SDR screenshots.

If the currently active filter chain does not emit HDR10, the driver already applies SDR->HDR inverse tonemapping to the image as a final pass before submitting it to the swapchain. I thought it would be wasteful to then immediately tonemap the image back to the original result when taking a screenshot, so in these instances the original linear-space SDR image is used as a source for format conversion, and tonemapping is skipped.

Some light refactoring of HDR-relevant code is included in this PR for convenience of implementation. Embedded HDR shaders have also been refactored so that (inverse) tonemapping and related HDR utilities are all defined in one shader file, `hdr_common.glsl`, which is then `#include`d by both the tonemapping and inverse tonemapping fragment shaders. I also explicitly enabled the `VK_EXT_swapchain_colorspace` extension, as the Vulkan validation layers were complaining about undefined constants on swapchain creation.

No explicit reference is made in the code to specific swapchain formats such as `A2R10G10B10` or `A2B10G10R10`, so the implementation should be format-agnostic, but so far I only tested it on my machine which supports `A2R10G10B10` only.

## Screenshots

The following screenshots are of the SMPTE Color Bars from the SNES 240p test ROM. Click to zoom on both as these are 4k screenshots and (especially the shader one) will show artifacts when scaled.

No shaders active, reading directly from SDR buffer:
No shaders

Using the crt-sony-megatron-default-hdr shader, which emits HDR10 colors:
Using crt-sony-megatron-default-hdr shader

## Related Pull Requests

#16435: Original PR in which this feature was requested.

## Reviewers

@warmenhoven @MajorPainTheCactus

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Sounds great!

>I have an irrational fear of copyright lawyers

You can always use homebrew, like the 240p test suite, which we have available for many cores via the online updater's content downloader.

**Comment by LibretroAdmin** [comment]
> I also explicitly enabled the `VK_EXT_swapchain_colorspace` extension, as the Vulkan validation layers were complaining about undefined constants on swapchain creation.

Cool, I noticed that this happened sometime ago and that this was missing from the initial Vulkan HDR implementation indeed.

**Comment by LibretroAdmin** [comment]
One quick question about ```VK_EXT_swapchain_colorspace```, when this extension is not supported, I assume the current PR just disables HDR support instead of the driver not being able to be used right? As in it's an optional extension,  we still want users to be able to use the Vulkan driver if they're on a GPU driver without this extension, we can just deal with it then by not enabling HDR codepath.

**Comment by warmenhoven** [comment]
Right now the PR unmodified crashes at startup in vkQueueSubmit just after printing this error:

> -[MTLDebugRenderCommandEncoder setRenderPipelineState:]:1615: failed assertion `Set Render Pipeline State Validation
> For color attachment 0, the render pipeline's pixelFormat (MTLPixelFormatBGRA8Unorm) does not match the framebuffer's pixelFormat (MTLPixelFormatRGB10A2Unorm).

I'll look into why. (Just to rule things out, `VK_EXT_swapchain_colorspace` is supported and the VkInstance gets created with it enabled.)

**Comment by CRefice** [comment]
> One quick question about `VK_EXT_swapchain_colorspace`, when this extension is not supported, I assume the current PR just disables HDR support instead of the driver not being able to be used right? As in it's an optional extension, we still want users to be able to use the Vulkan driver if they're on a GPU driver without this extension, we can just deal with it then by not enabling HDR codepath.

That would be the correct behavior, yes. The current logic does not check if the extension is supported, but I'll make it work

**Comment by CRefice** [comment]
> Right now the PR unmodified crashes on macOS at startup in vkQueueSubmit just after printing this error:
> 
> > -[MTLDebugRenderCommandEncoder setRenderPipelineState:]:1615: failed assertion `Set Render Pipeline State Validation
> > For color attachment 0, the render pipeline's pixelFormat (MTLPixelFormatBGRA8Unorm) does not match the framebuffer's pixelFormat (MTLPixelFormatRGB10A2Unorm).

Maybe try ending the command buffer and starting a new one just for the readback pipeline? Could be there's some state that isn't flushed until queue submit.

**Comment by CRefice** [comment]
> > One quick question about `VK_EXT_swapchain_colorspace`, when this extension is not supported, I assume the current PR just disables HDR support instead of the driver not being able to be used right? As in it's an optional extension, we still want users to be able to use the Vulkan driver if they're on a GPU driver without this extension, we can just deal with it then by not enabling HDR codepath.
> 
> That would be the correct behavior, yes. The current logic does not check if the extension is supported, but I'll make it work

Done. I added an extra context flag for HDR support, and gated all HDR-related functionality behind it. As a bonus, the driver will no longer attempt to reinitialize HDR pipelines every frame if HDR is enabled in the settings but disabled in the OS, something which I noticed could cause a lot of slowdown.

**Comment by LibretroAdmin** [comment]
Thanks. So I think the current issue is the issues on Mac with MoltenVK, not sure how to really proceed there. I assume the other platforms are fine so far.

**Comment by CRefice** [comment]
I think I might have caught the issue with MoltenVK. When creating pipelines, the `VkGraphicsPipelineCreateInfo pipe` is reused to initialize all pipelines, but I forgot to restore `pipe`'s render pass after creating the hdr readback pipeline. (Not sure how this wasn't caught by validation layers tbh.) @warmenhoven please try again 🤞🏼

**Comment by warmenhoven** [comment]
It works!

**Comment by bslenul** [comment]
Hello! I've bisected a graphical glitch with Vulkan to this PR few days ago: https://github.com/flyinghead/flycast/issues/1631#issuecomment-3261714564

To be perfectly clear I'm not saying this is the culprit (especially because the issue happens in standalone as well, although less severe), just that it started to appear with these changes. Flyinghead is suspecting an issue with 30xx series or the Nvidia drivers.

I tried other Vulkan cores (Beetle PSX HW, SwanStation, Dolphin, PPSSPP) and they don't have these issues. I was wondering if you'd have any idea what could be the cause? If not that's fine of course, just thought it was worth asking :p

**Pull request merged**
