### PR TITLE
WIP: Orbis/PS4 Support using OrbisDev toolchain

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description

This is the WIP PR for adding PS4/ORBIS support in RA.

Thanks to @frangarcj and @psxdev for the contribution and to @OsirizX for the initial code base port.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi @fjtrujy , can you fix the C89 build failure? You can check the details by clicking on 'Details' for 'RetroArch CI / linux-c89 (pull_request)'

**Comment by fjtrujy** [comment]
> Hi @fjtrujy , can you fix the C89 build failure? You can check the details by clicking on 'Details' for 'RetroArch CI / linux-c89 (pull_request)'

Fixed, there was temporal commit in the middle

**Comment by hizzlekizzle** [comment]
This is great news. I've had a lot of end-users express excitement for PS4 support. Cheers to the folks who have worked hard to make it happen :)

**Comment by LibretroAdmin** [comment]
This PR replaces this one -
https://github.com/libretro/RetroArch/pull/13961

**Pull request merged**
