### PR TITLE
Added HDR Support for D3D12

### PR DESCRIPTION
**Pull request by MajorPainTheCactus**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

Added support for HDR on the d3d12 driver. This enables a HDR swap chain and provides an inverse tonemapper to make an SDR image into a HDR image. Should work seemlessly for all emulators. Added a HDR menu option underneath Video when a HDR monitor is detected which allows the user to enable disable it plus change a few settings like max nits, paper white nits, contrast and whether to expand the colour gamut. Tested and it works but I only have a HDR capable monitor but it doesn't have HDR brightness so I can't fine tune it or see any problems in HDR values. I'll need someone else to test that.

Fixed issues that were flagged on last submission.  Will add D3D11 support in later pull request.

## Related Issues

N/A

## Related Pull Requests

N/A

## Reviewers

Hi @twinaphex hopefully this fixes all your requests! (apart from D3D11 support - will do that later)

### CODE REVIEW

**Comment by MajorPainTheCactus** [comment]
Can you squash all these commits down your side please?  I had already pushed my commits up to my GitHub fork before I realised that I had to rebase and my git and github skills do not stretch to fixing this after the fact (in fact I'm not sure I know how to rebase either, really)

**Comment by twinaphex** [comment]
Hi @MajorPainTheCactus,

I tried to accomplish it like this? https://github.com/libretro/RetroArch/pull/12917

Are you OK with doing it like that? I can still credit you in the files BTW if you'd like, either with a nick or real name. We can add that later to the files if you'd like. If you don't care, we can leave it out. Either way it's fine with me.

**Comment by MajorPainTheCactus** [comment]
@twinaphex  Hi added support for HDR in D3D11 - sadly as you can see I'm still having problems with Git and GitHub as its now added it to this pull request - I thought I was creating a new pull request - oh I give up!

**Comment by hizzlekizzle** [comment]
Yeah, new stuff just gets tacked onto the existing PR unless you commit to a branch and then do the PR from your branch instead (note: I always mean to do this but never do, so I frequently end up in this same situation :P)

**Comment by MajorPainTheCactus** [comment]
@twinaphex fixed those two issues identified with the d3d12 present transition not occuring when HDR was turned off and fixed the cel shader displaying black

**Comment by MajorPainTheCactus** [comment]
Now added as a separate neater and more bug free pull request by @twinaphex

**Pull request closed without merging**
