### PR TITLE
Add toggle to show/hide Controller autoconfig notifications

### PR DESCRIPTION
**Pull request by Ryunam**
This commit represents the first part of a series of toggles I would like to implement under Settings->Onscreen Display->Onscreen Notifications, in order to allow the user a higher degree of customization over which notifications to display if onscreen messages are enabled. This is also in an effort to satisfy the feature request posted on #4341, as well as on the libretro message boards.
The option in question allows the user to show/hide onscreen messages printed upon connecting a controller with a corresponding autoconfig file. I have also included a sublabel description, in order to better convey the effect of the option at first glance.

### CODE REVIEW

**Comment by retro-wertz** [comment]
will this move notifications to debug window at least or totally disable the notification?

**Comment by Ryunam** [comment]
Output to the debug window would be unaffected by this implementation. 
This toggle option only affects the visualization of the OSD message itself, but the autodetection task is still being performed as normal. The debug window will report the same messages it was showing previously.

As a direct example, upon connection of my Xbox One Elite controller through the official Wireless Adapter, I get the following log on the debug window:

`RetroArch [INFO] :: Found XInput v1.4.`
`RetroArch [INFO] :: Found XInput controller, user #0`
`RetroArch [INFO] :: Enumerating DInput joypads ...`
`RetroArch [INFO] :: Device #0 PID: {02E3} VID:{045E}`
`RetroArch [INFO] :: Done enumerating DInput joypads ...`
`RetroArch [INFO] :: Found joypad driver: "xinput".`
`RetroArch [INFO] :: Autodetect: 45 profiles found.`

This is still being printed in the debug window accordingly, regardless of the notifications being set to ON or OFF.

**Comment by orbea** [comment]
While I do like this idea, it might be a better idea to make sure these OSD notifications actually fully work before trying to hide them or not. There are at least two issue reports with OSD problems that should be fixed. See https://github.com/libretro/RetroArch/issues/4353 and https://github.com/libretro/RetroArch/issues/4237.

**Comment by meleu** [comment]
Hi @Ryunam ! In [this comment](https://github.com/libretro/RetroArch/issues/4237#issuecomment-270181838) @twinaphex seems to agree if we have only one config to enable/disable the OSD verbosity and not creating several config options to enable different OSD messages. I implemented such option in my PR #4217 and named it `video_message_verbosity` in retroarch.cfg (in configuration.c it is `settings_t.video.msg_verbosity`). You can see the diff here: https://github.com/libretro/RetroArch/pull/4217/files

He suggested that we rebase your PR here to use `video_message_verbosity` rather than using `video_font_show_controller_autoconfig`. Could you change your PR doing this way. :-) It would be cool. If you are busy I can do it tonight.

**Comment by meleu** [comment]
Continuing the conversation here seems to have more sense...

@fr500 
> I think @meleu's idea would be more problematic than @Ryunam's. Again, obscuring many notifications behind one setting would be bad imho...
I vote to implement @Ryunam's (one setting for each), provide sane defaults and hide it under advanced settings.

I thought better and I think that only one toggle for the verbosity is very reasonable. This way we would have three levels of OSD verbosity: total silence (`video_font_enable = false`), "normal" mode (`video_message_verbosity = false`) and verbose mode (`video_message_verbosity = true`).

@Ryunam 
> Some questions then spring to mind: what makes a certain notification 'verbose' and others 'not verbose'? What about plugging in a non-autoconfigured controller for example, or the message that comes up when disconnecting it?

Yep. Those questions need answers. Maybe we can discuss it better. I would combine the two PRs in one this night, but since we didn't have a consensus here I'll wait a little more.

Cheers.

**Comment by Ryunam** [comment]
Hi @meleu, I was indeed interested in reaching a consensus between the different opinions shared in Issue #4237. 

Once again I'd like to restate that I'll have no qualms with altering my pull request, making it so that `video_message_verbosity` controls if a notification appears upon connecting a controller with an autoconfig file, if the final agreement on the matter veers in that direction. 
I understand that this would further facilitate the integration of your changes pertaining to RetroAchievements.

Still, I'd like to summarize my concerns over this approach:
1. Limiting the visualization of several OSD messages to one general toggle would be restrictive and would prevent exact control over the type of notification the user is interested in receiving, as untidy as it may look for the time being.

2. Having three layers of verbosity is a reasonable scope in terms of customization, but I'd find it too subjective. It would have to be decided whether a particular notification belongs to a certain 'verbose' setting or the other. Moreover, it would be very difficult, I think, to properly convey this categorization to the user: provided that a certain approach is chosen, how could the user learn that something like 'Autoconfig controllers' is verbose or not? The RetroAchievements information falls under the same scope: how will the user know that it belongs to the highest verbosity and that such a notification actually exists?

3. Finally, I understand the doubts over making the interface too complicated and overloaded with settings.
However, as @fr500 suggested, I propose we leverage the 'Show Advanced Settings' option found under Settings->User Interface->Menu, hide the OSD toggles under that condition and provide individual show/hide options for each OSD string under Settings->Onscreen Display->Onscreen Notifications. 
The individual OSD toggles would default to either ON or OFF, based once again on the ultimate word from the libretro team. This would hopefully address the priority of immediacy and ease of use, while simultaneously giving advanced users a broader variety of features to adjust as they see fit.

**Comment by meleu** [comment]
Just putting here what I said on the other thread to facilitate the conversation history:

I don't know the details of how the RetroArch team works (who decides what) and I'm not sure if we can get a **final word** about using `video_message_verbosity`. But looking at the [commits history](https://github.com/libretro/RetroArch/commits) @twinaphex seems to be the person that merge most of the PRs. That's why I'm trying to make as he suggests. 

I'm a RetroAchievements enthusiast and I really would like to see the PR #4217 merged (see some useful retroachievements messages when launching a game that has achievements, [details of why I think the cheevos messages useful here](https://github.com/libretro/RetroArch/pull/4217#issuecomment-270281219)). My vote is to get only one toggle to enable/disable the OSD verbosity, but this is not something that worries me a lot. I don't care if I need to enable a specific option to see those messages or if it is enabled by a general OSD verbosity toggle (to be honest I think it should be the default, but the discussion on my PR showed that this isn't a consensus). I just did that way (`video_message_verbosity`) in a hope to make the PR be merged.

I submitted that PR about a month ago and I had no hope to see it merged anytime soon (before 1.4.0). The @twinaphex 's [comment](https://github.com/libretro/RetroArch/issues/4237#issuecomment-270181838) increased my hope and that's why I asked you to use the `video_message_verbosity` in your PR.

I'm realizing that to resolve this divergence a debate is needed (or a "boss" to say which approach he prefers). But we don't want to bother the team before releasing 1.4.0, right? :-) I'm already conformed, let's wait 1.4.0 release and discuss about it later.

Cheers!

**Comment by Ryunam** [comment]
May I ask if a consensus has been reached on this proposal? My idea is that, by hiding individual and very specific OSD notification toggles under "Show Advanced Settings" and defaulting them to the current behavior, it should be possible to preserve an uncluttered approach while giving "advanced" users more options to customize the scope and frequency of these on-screen messages.
I see that there are conflicting files right now on this PR, so in the event it is decided that we can go this route I will be happy to refactor everything in a more compatible and comprehensive manner.

**Comment by meleu** [comment]
> May I ask if a consensus has been reached on this proposal?
I asked it in the issue #4725 , but sadly didn't get any answer... :(

**Comment by Awakened0** [comment]
Since Advanced Settings are now hidden by default, I think having individual toggles would work without overwhelming casual users. There aren't too many options under Settings, Onscreen Display, Onscreen Notifications, so I don't think it would be too cluttered to add the toggles there. Though it'd be nice to nest them under their own section.

There are a ton of display toggles under Settings, User Interface, Menu and I haven't seen anyone complain.

**Comment by RobLoach** [comment]
Whenever I see some youtube footage of people playing Super Mario Bros 3 or something, the way I can tell they're using RetroArch is by the OSD notification showing up :wink:

But I'm all for this, as long as the default stays as `true`. Looks like there are some conflicts to resolve?

**Comment by Ryunam** [comment]
Hi @RobLoach, thanks for the input! Indeed there are currently quite a few conflicts with the updates that have been implemented, so I would have to refactor this and also include toggles for the other OSD notification types in accordance to the proposed "vision". 
I was waiting for a consensus to be reached before doing any changes, though in the meantime I will close this pull request and by next week I should hopefully be able to create something cleaner and more comprehensive.

**Pull request closed without merging**
