### PR TITLE
fetch multiple sectors from CD in a single read

### PR DESCRIPTION
**Pull request by twinaphex**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by twinaphex** [comment]
I tried this out on my end hoping it would make Beetle PSX on Windows run more inline with what I get on Linux, but alas, it's just as slow, possibly even slower. 

Hardware in question -

image

**Comment by Jamiras** [comment]
Note: The buffering logic is happening one step up from the Linux/Window #ifdefs, so will impact both. I have only tested on Windows, where I was capping around 45fps without buffering and running (for the mostpart) at full speed with buffering.

**Comment by bparker06** [comment]
I haven't had a chance to read through this completely but just note we should never fetch more than one sector at a time because it is not guaranteed by the MMC spec to actually work. Some drives can do it (up to an arbitrary, un-queryable limit) and some cannot. You also run into the issue of crossing track boundaries when doing this which can also fail or cause problems.

**Comment by bparker06** [comment]
Closing as this was the wrong solution, OK'd by Jamiras.

**Pull request closed without merging**
