### PR TITLE
Fetch translation from Crowdin

### PR DESCRIPTION
**Pull request by guoyunhe**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

Fetch translation from Crowdin. Update python script to support UTF-8 better and fix some key mismatch.

### CODE REVIEW

**Comment by twinaphex** [comment]
OK, is everything up to date with the translations right now in master?

Also, can you perhaps make a tutorial for how we can work with Crowdin? Perhaps then I could get all translators to start taking a look at it. I need to know myself how to set it up so that we can get the workflow going.

**Comment by Ryunam** [comment]
This is actually very interesting, thank you for implementing this. I have been interested in possibly contributing to the Italian translation for quite a long time, so I will definitely appreciate any tutorial / guide on how to use Crowdin for this purpose.

**Comment by guoyunhe** [comment]
@twinaphex I changed the bash script to Python script. Hope it will work on Windows (didn't have a Windows device to test now because of lock down).

@Ryunam I updated the README with some introduction and links https://github.com/guoyunhe/RetroArch/blob/master/intl/README.md

**Comment by WeedyWeedSmoker** [comment]
This should not sync the french file…

All modifications are actually downgrades from my file…
Even the removed spaces had a purpose… This un-translates many things too!

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker I fixed a trim issue and some KEY-VALUE format in msg_hash_us.h. Now the French translation should be fixed. Please check it again.

**Comment by WeedyWeedSmoker** [comment]
Is it a known error, why do you fix the "800x240" and "800x240" x to be uppercase X?

(in `MENU_ENUM_LABEL_VALUE_CTR_VIDEO_MODE_2D_400x240` and `MENU_ENUM_LABEL_VALUE_CTR_VIDEO_MODE_2D_800x240`…

@twinaphex?

**Comment by guoyunhe** [comment]
The script only supports key in uppercase.

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe yeah, that makes sense…

@twinaphex does it have to be changed somewhere else in the code then ?

**Comment by WeedyWeedSmoker** [comment]
Please resync the french file, as this again un-translates the newest stuff…

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker Updated. You can also check https://crowdin.com/translate/retroarch/11735/en-fr where some translations are missing in French.

**Comment by WeedyWeedSmoker** [comment]
You seem to have accidentally removed `MENU_ENUM_SUBLABEL_VIDEO_CTX_SCALING` when changing the if condition to have the unique `MENU_ENUM_SUBLABEL_VIDEO_RGA_SCALING` ID, (I assume your script can't have duplicate values, even in "if…else" situations…)

Do you think the script should be modified to allow this and maybe the lowercase handling (to avoid future errors maybe, and avoid being tied to the script's incompatibilities)?

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker which line? I didn't touch `MENU_ENUM_SUBLABEL_VIDEO_CTX_SCALING` (I cannot find any changes to it in the diff). I just renamed `MENU_ENUM_LABEL_VALUE_VIDEO_CTX_SCALING` (it is a different key) to `MENU_ENUM_LABEL_VALUE_VIDEO_RGA_SCALING` when `#ifdef HAVE_ODROIDGO2`.

The script doesn't support duplicated keys and here is no way to overcome it. It is a bad practice to have two different strings with the same key.

About the casing, since keys are 99.99% uppercase, I think we can just enforce uppercase naming. But technically, the script can support lower case, too.

**Comment by WeedyWeedSmoker** [comment]
Line 10271 , in `menu/menu_setting.c`

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker It is:

`MENU_ENUM_LABEL_VALUE_VIDEO_CTX_SCALING`

not

`MENU_ENUM_SUBLABEL_VIDEO_CTX_SCALING`

**Comment by WeedyWeedSmoker** [comment]
Yeah, that's what I meant…

**Comment by guoyunhe** [comment]
I don't see any problem with it. It is just a renaming and it is by purpose.

**Comment by WeedyWeedSmoker** [comment]
Ok, I see… Good job finding all those bugs already!

**Comment by WeedyWeedSmoker** [comment]
I think you should synchronize translations again now that the US file has consistent formatting all across it…

**Comment by twinaphex** [comment]
There are some C89_BUILD failures in this PR -

https://travis-ci.org/github/libretro/RetroArch/builds/676956132

Please re-do the specific C89 fix that was done for these files to overcome the string array limitations of C89.

**Comment by guoyunhe** [comment]
@twinaphex can you give me an example? I cannot find a fix for it.

**Comment by WeedyWeedSmoker** [comment]
There is a problem with the new formatting, many elements are flagged with  `/* FIXME` ... `*/`, and none of the older translations for those elements are imported from the originally translated ones…

You should fix the script and reimport the previous language files afterwards…

**Comment by WeedyWeedSmoker** [comment]
The C89_BUILD failures that @twinaphex was talking about are because C89 limits text strings to 509 characters, and some of the new translations are too long:

Here are the strings that are still too long
intl/msg_hash_el.h

-----------------

intl/msg_hash_el.h:4361:1: error: string length ‘535’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]

```
MSG_HASH(
   MENU_ENUM_SUBLABEL_CONTENT_FAVORITES_SIZE,
   "Περιορισμός του αριθμού καταχωρίσεων στην λίστα αγαπημένων. Μόλις φτάσει το όριο, οι νέες προσθήκες θα αποτρέπονται μέχρι οι παλιές να αφαιρεθούν. Ορίζοντας την τιμή σε -1 επιτρέπει 'απεριόριστες' (99999) καταχωρήσεις. ΠΡΟΕΙΔΟΠΟΙΗΣΗ: Μειώνοντας την τιμή θα διαγράψει ήδη υπάρχουσες καταχωρήσεις!"
   )
```

-----------------
intl/msg_hash_el.h:5748:1: error: string length ‘582’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]

```
MSG_HASH(
   MENU_ENUM_SUBLABEL_DISK_TRAY_EJECT,
   "Ανοίγει μία εικονική θύρα δίσκου και αφαιρεί τον τωρινά φορτωμένο δίσκο. ΣΗΜΕΙΩΣΗ: Εάν το RetroArch έχει ρυθμιστεί να κάνει παύση ενώ το μενού είναι ενεργοποιημένο, μερικοί πυρήνες μπορεί να μην σημειώσουν τις αλλαγές εκτός και αν το περιεχόμενο συνεχιστεί για μερικά δευτερόλεπτα μετά από κάθε ενέργεια χειρισμού δίσκου."
   )
```

------------------

intl/msg_hash_el.h:5756:1: error: string length ‘636’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]

```
MSG_HASH(
   MENU_ENUM_SUBLABEL_DISK_TRAY_INSERT,
   "Εισάγει τον δίσκο που αντιστοιχεί στον 'Δείκτη Τρέχοντος Δίσκου' και κλείνει την εικονική θύρα δίσκου. ΣΗΜΕΙΩΣΗ: Εάν το RetroArch έχει ρυθμιστεί να κάνει παύση ενώ το μενού είναι ενεργοποιημένο, μερικοί πυρήνες μπορεί να μην σημειώσουν τις αλλαγές εκτός και αν το περιεχόμενο συνεχιστεί για μερικά δευτερόλεπτα μετά από κάθε ενέργεια χειρισμού δίσκου."
   )
```

------------------

intl/msg_hash_el.h:5764:1: error: string length ‘644’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Werror=overlength-strings]

```
MSG_HASH(
   MENU_ENUM_SUBLABEL_DISK_IMAGE_APPEND,
   "Εξαγωγή τρέχοντος δίσκου, επιλογή ενός νέου δίσκου από αρχείο, εισαγωγή του και μετά κλείσιμο της τρέχουσας εικονικής θύρας δίσκου. ΣΗΜΕΙΩΣΗ: Αυτή είναι μία απαρχαιωμένη λειτουργία. Προτείνουμε καλύτερα να φορτώσετε λίστες πολλαπλών δίσκων M3U που επιτρέπουν την επιλογή δίσκου μέσω των επιλογών 'Εξαγωγή/Εισαγωγή Δίσκου' και 'Τρέχων Ευρετήριο Δίσκων'."
   )
```

**Comment by guoyunhe** [comment]
But how to fix it?

**Comment by WeedyWeedSmoker** [comment]
The translator should fix it, is there an option BTW on Crowdin to limit text input per string to 509 characters?

**Comment by guoyunhe** [comment]
The string is actually around 300 characters long. But since it is mostly Greek characters, which are two bytes long, the byte length of the string is almost doubled. So I need to talk with the Greek translator if he/she can reduce the length of the texts.

**Comment by guoyunhe** [comment]
string fixed. the python script will check byte length and cut the string at 500 byte.

still have a macos/xcode build error which I have no idea about...

**Comment by WeedyWeedSmoker** [comment]
Wow, you did a great job cutting longer strings… Wouldn't it be better to use `[…]` instead of `[...]`?

(It uses at least 1 less bytes, right?)

**Comment by WeedyWeedSmoker** [comment]
I think you should re-sync translations now, the US file has new formatting corrections, and the french file was updated to adopt the new format too…

**Comment by im-4-potato** [comment]
I haven't been following your work here too closely, but it looks like you've updated the script to handle some of the new changes in the translation files. One issue that I'm seeing is that blank lines are not being preserved.

**Comment by WeedyWeedSmoker** [comment]
Yeah, I think you should leave blank lines, and maybe even duplicates with the english file, to facilitate comparison or translation of the language files…

**Comment by WeedyWeedSmoker** [comment]
I think we could move the Language selection to the bottom the main menu, inside we could show the percentage of the translation advancement next to each language, then add a menu option at the bottom that shows informations on how to help with the translation?

**Comment by im-4-potato** [comment]
@WeedyWeedSmoker I really like the percentages added to the languages, but I'm not sure I like moving more stuff into `Main Menu`. Personally, I'd like to see `Configuration File` moved into `Settings > Configuration`, and `Help` either being greatly expanded upon or removed entirely, currently it's rather useless.
I can understand the value of having the language settings easily accessible without having to dig into menus, but every added menu item adds some noise to the UI that I'm not a big fan of.

**Comment by guoyunhe** [comment]
I like to put "Language" in the first level of the settings menu. When the menu is a language that you cannot understand a single word, you cannot find it easily in second level.

**Comment by carlos-ks** [comment]
Let's merge this branch, because the discussion begins to deviate from the topic.

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe Why is the arabic translation now appearing empty on Crowdin? (0%…)

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker some unmatched English translations were cleaned up.

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe There are some translations inside the arabic langage file in the repo… But it shows 0% on Crowdin, shouldn't they then be removed ?

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker Crowdin uses a round method for percentage. So 0.4% will be shown as 0%. These translations indeed exist, though the amount is too small.

**Comment by WeedyWeedSmoker** [comment]
The esperanto is at 6 % though, and it should be almost empty, there are many english strings just a little different from the us file ones…

**Comment by WeedyWeedSmoker** [comment]
Can you remove wrong strings on Crowdin? If you can give delete permissions I may be able to help remove the untranslated wrong strings from each language…

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker now you have the permission. I can check Chinese/Japanese/Korean.

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe Ok, I'll do esperanto first

**Comment by guoyunhe** [comment]
You can use proof read view https://crowdin.com/proofread/retroarch/11735/en-eo

**Comment by WeedyWeedSmoker** [comment]
I did esperanto, vietnamese, and some others…

I think you should re-enable the removal of duplicates now to facilitate finding those extra strings (that are sometimes well hidden)…

**Comment by WeedyWeedSmoker** [comment]
Ok, I just finished checking all the other languages…

**Comment by WeedyWeedSmoker** [comment]
And I just finished adding all the missing multi-line translations for all languages…

**Comment by WeedyWeedSmoker** [comment]
I think you should synchronize again now!

I removed the untranslated strings here too https://github.com/libretro/RetroArch/pull/10511

**Comment by WeedyWeedSmoker** [comment]
It seems you imported many untranslated strings again in Crowdin… (Especially in arabic and esperanto…)

Also, there was a string in Crowdin that contains a [return] key, making compilation fail… I just fixed it, but you should change the script to remove newlines in the strings…

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker I undo the import and the script can escape the line break now.

**Comment by WeedyWeedSmoker** [comment]
I was in the process of removing wrong strings by hand… Ok!

**Comment by WeedyWeedSmoker** [comment]
But now it removed the correct strings too!

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker yeah, but adding correct strings back is easier than deleting wrong strings I think...

**Comment by WeedyWeedSmoker** [comment]
You can let me delete them, I was already doing it… But for now even French is missing translations that were there and correct before…

**Comment by WeedyWeedSmoker** [comment]
Don't worry you can just redo, I'll handle it… I already did arabic deleting 94 strings in a short amount of time…

**Comment by guoyunhe** [comment]
I did import with Translation Memory in Crowdin, which contains a lot of English strings.

This undo remove all strings from translation memory. Here are 21 strings with key name change (caused by a mistake in script). So in each language, max. 21 correct strings are deleted.

You can search the following key:
- MSG_COMPILER
- MSG_UNKNOWN_COMPILER
- MENU_ENUM_SUBLABEL_VIDEO_LAYOUT_SELECTED_VIEW
- MENU_ENUM_LABEL_VALUE_RGUI_SHOW_START_SCREEN
- MENU_ENUM_SUBLABEL_RGUI_SHOW_START_SCREEN
- MENU_ENUM_LABEL_VALUE_RGUI_BROWSER_DIRECTORY
- MENU_ENUM_SUBLABEL_RGUI_BROWSER_DIRECTORY
- MENU_ENUM_LABEL_VALUE_RGUI_CONFIG_DIRECTORY
- MENU_ENUM_SUBLABEL_RGUI_CONFIG_DIRECTORY
- MENU_ENUM_LABEL_VALUE_RETROKEYBOARD
- MENU_ENUM_LABEL_VALUE_XMB_MAIN_MENU_ENABLE_SETTINGS
- MENU_ENUM_SUBLABEL_XMB_MAIN_MENU_ENABLE_SETTINGS
- MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_FOOTER_OPACITY
- MENU_ENUM_SUBLABEL_MATERIALUI_MENU_FOOTER_OPACITY
- MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_HEADER_OPACITY
- MENU_ENUM_SUBLABEL_MATERIALUI_MENU_HEADER_OPACITY
- MENU_ENUM_LABEL_VALUE_NETPLAY_START_WHEN_LOADED
- MENU_ENUM_LABEL_VALUE_NETPLAY_LOAD_CONTENT_MANUALLY
- MENU_ENUM_LABEL_VALUE_VIDEO_DRIVER_FALLBACK
- MENU_ENUM_LABEL_VALUE_SIDELOAD_CORE_SUCCESS
- MENU_ENUM_LABEL_VALUE_SIDELOAD_CORE_ERROR

and add translation back

**Comment by WeedyWeedSmoker** [comment]
Ok, I'm doing it now…

**Comment by im-4-potato** [comment]
Are you guys ever on the Discord? I think we could coordinate better there.

**Comment by WeedyWeedSmoker** [comment]
Ok I just finished adding all the strings back… Also I hate Discord, no offense intended!

**Comment by WeedyWeedSmoker** [comment]
You can synchronize again now if this doesn't add back the untranslated strings…

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker  Updated with percentage fetched from Crowdin, available in [intl/progress.h](https://github.com/guoyunhe/RetroArch/blob/master/intl/progress.h)

**Comment by WeedyWeedSmoker** [comment]
Ok it's looking good for me!

**Comment by twinaphex** [comment]
Hi, can this PR be rebased? There's some merge conflicts right now

**Comment by guoyunhe** [comment]
@twinaphex rebased. but we need to add back some translations which become invalid after source changing.

@WeedyWeedSmoker if you want to help check strings affected by this update, type the following query in the search box in Crowdin editor:

```
h=0d356f06fd651fae46227dadf9dac53a462384
```

I am checking Simplified Chinese and Traditional Chinese.

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe Oh, that's quite a lot of strings!!!

Around 8000 strings to check for all languages, isn't there a way to get these strings by the ID instead of the US text strings?

That way, if a string changes in english it would not delete it's translations in all the other languages…

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker I can re-import strings from a back up. Let's see how well it works.

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker most strings are restored. 1% have to be done manually.

**Comment by guoyunhe** [comment]
@twinaphex do you know why ci failed on mac/xcode?

**Comment by guoyunhe** [comment]
@twinaphex do you think the PR can be merged? I have some personal issue and will probably be offline for a couple of weeks.

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe Ok, I think you could rebase now that the preliminary translations merge has been accepted into master…

**Comment by IlDucci** [comment]
Just to point it out: It appears that any changes that were done in RetroArch's translation files ended up superseding what was translated in Crowdin, and Crowdin itself didn't send any emails mentioning out that this happened. This should be normal for English languages, but not for the rest of them.

**Comment by guoyunhe** [comment]
@IlDucci It shouldn't be like this. When I run Crowdin scripts, it only uploads msg_hash_us.h, not rest of them. And it should then download translations from Crowdin and override these files from Git. If you are seeing files from Git overriding Crowdin translations, it must be someone manually uploaded or typed them on Crowdin. (It is most likely me or @WeedyWeedSmoker) You can find out who did it easily on Crowdin. To **lock** the translation for extra safety, you can click the :heavy_check_mark: mark to approve translations. Then it won't be messed up by others.

**Comment by IlDucci** [comment]
@WeedyWeedSmoker Well, I did found the translations someone else managed to snuck in while the Crowdin fetching was still under development via an accepted PR, and I had to change those. It's something that now that the system is in place should be avoidable.

And just to sigh in relief, those translations were not entirely gone. They are removed from the current string, yes, but are kept in the server's translation memory, so I was able to quickly restore the version that was written there.

Thank you for porting the latest changes!

**Comment by WeedyWeedSmoker** [comment]
Finally Merged!

Great work @guoyunhe and all the translators involved…

**Pull request merged**
