### PR TITLE
xmb: Add Morning Blue theme

### PR DESCRIPTION
**Pull request by RobLoach**
This adds a new lighter theme, called "Morning Blue", to somewhat match the likes of "Midnight Blue". It could use some tweaks, and possibly more dashes of colour, but I'm no designer. Here's a screenshot....

morningblue

### CODE REVIEW

**Comment by twinaphex** [comment]
Looks good.

**Comment by twinaphex** [comment]
Can we make it a tiny bit less bright? I think that would also make the text stand out more than what is currently the case.

**Comment by twinaphex** [comment]
image

**Comment by twinaphex** [comment]
image

**Comment by twinaphex** [comment]
image

**Comment by twinaphex** [comment]
as you can see, it's a tiny bit too bright and the text should be able to stand out a bit better.

**Comment by hyarsan** [comment]
To make it look good with both white and black text?

**Comment by twinaphex** [comment]
Yeah.

**Comment by RobLoach** [comment]
Here it is with the black text and mono inverted.
screenshot at 2018-03-11 22-24-56

**Comment by twinaphex** [comment]
well can you make it more suitable for something other than black text? we really need this to be more flexible.

**Comment by fr500** [comment]
a Light theme always needs dark fonts, seems pretty standard

**Comment by twinaphex** [comment]
image

With Monochrome Inverted it looks like this for me. I think the white text still clashes and doesn't look really good.

**Comment by RobLoach** [comment]
Have to change the text color. "Menu Font Red Color" at 0, along with the others, will do it.

**Comment by twinaphex** [comment]
Well, can we make all this much more convenient for the user so that when he selects this menu color theme, some of these settings will be changed for him as well? It must be possible to make this much easier than what it currently is.

**Pull request merged**
