### PR TITLE
Increase Maximum number of Shader Parameters

### PR DESCRIPTION
**Pull request by HyperspaceMadness**
Increase the number of shader parameters so we don't run into an upper limit when necessary

### CODE REVIEW

**Review by RobLoach — APPROVED** [review]
Seems fine. The whitespace is unrelated, but some good clean up. Thanks!

**Comment by LibretroAdmin** [comment]
Can you maybe move the variable 'parameters' over from a fixed-size array to a dynamically sized array? And then the array could be increased if the situation demands it.

The reason I bring it up is because increasing it from 1024 to 2048 parameters will obviously cost a lot of extra memory, and if it's going to waste by a shader barely using more than 20 parameters that is quite unfortunate. Making it heap allocated will theoretically make it a tad bit slower but it prob won't be perceptible to the user.

**Comment by HyperspaceMadness** [comment]
Yeah, that makes sense, I'll look into how to address this

**Comment by Misunderstood-Wookiee** [comment]
Neat

**Review by RobLoach — CHANGES_REQUESTED** [review]
Dynamic array :+1:

**Comment by HyperspaceMadness** [comment]
Closed, because working in the variable array was looking a lot more complex

**Pull request closed without merging**
