### PR TITLE
Auto hide overlays

### PR DESCRIPTION
**Pull request by yoshisuga**
## Description

Add an option to automatically hide onscreen overlay when a physical controller is connected. When a controller is disconnected, the overlay will appear again.

### CODE REVIEW

**Comment by jdgleaver** [comment]
@yoshisuga I'm really sorry to be a nuisance here, but while this is a great idea there are several issues with the PR:

- It doesn't work correctly on Android, because the Android input driver is incomplete - it doesn't handle controller disconnect events. This means the overlay will be hidden when connecting a gamepad, but thereafter will never be shown again (unless manually toggled). This makes the option very cumbersome on Android - to the point where (personally) I'm not sure that it's even worth enabling on that platform...

- Your implementation is very inefficient:

    - You're calling `input_config_get_device_count()` to determine whether a gamepad is connected. This is *slow*, because it runs a loop over all possible input devices. Moreover, it is incorrect - overlays are connected to port 1, so we should only be checking the connection status of port 1

    - You're checking the gamepad connection state even when overlays are disabled. Now I can see why you might want to do this, but it incurs an unnecessary performance overhead for users who don't want anything to do with overlays

    - The overlay loading/handling functions need to return early if auto hiding is enabled, otherwise it's more wasted effort

- Translations (i.e. `msg_hash_ja.h`) cannot be modified via regular PRs - they have to go via Crowdin

- We can't merge a PR that consists of 15 commits... (These need to be squashed)

I actually implemented this same feature quite a few months ago, but never PR'd it due to the Android driver issue. But I guess the fact that you made this PR means there is some demand for it, despite any platform-specific shortcomings :)

I just dusted off my old branch and rebased it, and fixed it up a little - I still need to do some proper ASAN testing, but should have it wrapped up tomorrow morning. Would you be offended if I submitted it as an alternative/replacement for this PR...?

**Comment by jdgleaver** [comment]
Okay, well here's my version: #11239

@yoshisuga Please let me know if there are any issues with this!

**Comment by yoshisuga** [comment]
Hi @jdgleaver, not a nuisance at all, thanks for taking the time to leave
detailed comments. I approached the implementation in a really naive way
and I kind of had a feeling it wouldn’t be the most efficient.

I’ll definitely test out your changes and let you know if it works ok.

**Comment by jdgleaver** [comment]
@yoshisuga Ah, that's lovely - thank you for being so understanding :)

After submitting my PR, I had a horrible premonition that you might think I was being heavy handed or overly critical. My only intention was to save burdening you with a bunch of code changes. I had no doubt that you could fix these things yourself, but I've had to review quite a few PRs now, and every time I tell someone to change this or that, it makes me feel bad... So now I just tend to make any small required changes myself, so as not to make work for people :)

Anyway, I look forward to your test results!

**Comment by yoshisuga** [comment]
@jdgleaver I commented on your PR #11239  and I'm happy to report that the auto hide works great on iOS 👍 

You were absolutely not being heavy handed or overly critical - this is just part of software development and I appreciate the time and care taken to leave the detailed feedback. 

I'm closing this PR in favor of yours - thanks, it's a nice addition!

**Pull request closed without merging**
