### PR TITLE
New GLUI theme: Flux

### PR DESCRIPTION
**Pull request by fpscan**
## Description

image

## Reviewers

@twinaphex 
@jdgleaver

### CODE REVIEW

**Comment by fpscan** [comment]
base color scheme https://github.com/libretro/RetroArch/pull/9681

**Comment by jdgleaver** [comment]
@fpscan This is a strong start, but for Material UI I think we want a certain level of consistency across all the themes. That means:

- Header background colour shouldn't be the same as the list background colour

- I don't think you should completely disable the border shadow effect when landscape optimisations are enabled

Two other comments:

- The red scroll bar is a little strong - I think it's a visual element that should err on the side of subtlety, rather than being something that always draws the user's eye

- `list_text_highlighted` is a little too light - I think it's pushing the limits of text legibility standards: https://material.io/design/color/text-legibility.html

**Comment by RobLoach** [comment]
I've found the Color Tool helpful for colour choice:
https://material.io/resources/color/#

**Comment by RobLoach** [comment]
Looks like some feedback could be implemented on here. Going to close for now, feel free to re-open once a new review is needed. Thanks!

**Pull request closed without merging**
