### PR TITLE
DISPMANX: Disable triple buffering for now, for stability reasons.

### PR DESCRIPTION
**Pull request by vanfanel**

### CODE REVIEW

**Comment by joolswills** [comment]
What stability problems were caused by this btw ? Since removal some users are reporting performance issues / stuttering. Perhaps it might be best to revert this ?

**Comment by hizzlekizzle** [comment]
Does reverting it fix the issues?

**Comment by joolswills** [comment]
I've not actually had a change to test myself, but I have reverted it in retropie for now, and am waiting on user feedback.

**Comment by dukesilverfan** [comment]
I will test this evening and report back.

**Comment by dukesilverfan** [comment]
Updating to Retropie 4.2.2 after https://github.com/RetroPie/RetroPie-Setup/commit/cfaa04786b885b19c6246d15d72836a0e4270a03 via binary did not fix the issue, so I updated just Retroarch via source and it is mostly fixed. There is still a slightly noticeable performance issue and slight stuttering (around every 2 seconds) compared to the Retropie 4.1 build, but it is mostly playable now, and eliminated the stutter every .5 seconds or less.

**Comment by andrewlxer** [comment]
FWIW, with 4.2.1 I'm able to reproduce the stuttering every 5s or so in snes9x2010 with the 240p grid scroll test.  After updating to 4.2.2 and updating retroarch from source, the stutter is totally gone.

Note my output is set to 720p, which may account for my slightly better results.

**Comment by joolswills** [comment]
I hadn't rebuilt binaries yet as I wanted it tested first. I am building new binaries for retropie now it has been confirmed that reverting it solves the issue.

**Comment by andrewlxer** [comment]
FYI @joolswills I took a stab at solving the issue causing the revert (at least in my testing), you may want to pull the followup to the revert once it's upstream:

https://github.com/libretro/RetroArch/pull/4862

**Pull request merged**
