### PR TITLE
(Ozone+XMB) Add option to adjust cursor memory when changing menu tabs

### PR DESCRIPTION
**Pull request by Ryunam**
## Description

This PR consists of a follow-up to the changes introduced with https://github.com/libretro/RetroArch/pull/14519 and https://github.com/libretro/RetroArch/pull/14526, which made it so that when navigating the menu with both XMB and Ozone drivers the cursor position would be memorized at all times, whenever switching from one tab to another. 

Some users may prefer to retain the old behavior, always going back to the top entry, or tweak the cursor memory feature to only affect certain sections of the user interface.

The new setting is found under "Settings -> User Interface -> Remember Selection when Changing Tabs" and provides four possible values:

- Always (default behavior, memorizes the cursor selection whenever possible)
- Only for Playlists
- Only for Main Menu and Settings
- OFF (cursor memory is completely disabled)

The setting in question will also not show up when using either GLUI or RGUI, since cursor memory is not (yet) implemented for those drivers.

## Reviewers

@sonninnos 
@LibretroAdmin

### CODE REVIEW

**Comment by sonninnos** [comment]
I think it would make much more sense that value 0 is OFF and 1 is ON, and so on, but since it is like that with the refresh rate autoswitch too, and changing that is too late, I guess it won't matter here either..

**Comment by Ryunam** [comment]
Yeah, the fact it was not taken into consideration with the autoswitch setting either is most likely due to an oversight on my part. If I remember well, the logic behind it was that 0 was assigned to the default value. 
That being said, I could spot quite a few examples in `menu_defines.h` where the "none"/disabled value is not set to 0...

Two questions for you:

1. Provided that value 0 is assigned to OFF/Disabled, would "1 = Always; 2 = Playlists; 3 = Main/Settings" make sense as a proper order for this setting?
2. Should we keep the default value as "Always"?

**Comment by sonninnos** [comment]
Indeed, and only those zeroes that get saved to the config as zeroes when not disabled/off are confusing when reading the config with human eyes, but it is a minor nitpick really.

1. Sure. I feel that value 3 will be pretty much useless though, but sure it won't hurt having it
2. Sure

**Comment by Ryunam** [comment]
All done:

- 0 is now assigned to the OFF/Disabled value;
- The #ifdefs were fixed to prevent the unintended disappearance of the screensaver-related settings.

Should be good to go, but let me know if there's anything else that needs further tweaking.

**Comment by sonninnos** [comment]
Okeydokey, looking better now. Just realized though that what about Netplay and Import Content tabs..

Also it might look a bit cleaner if all that decision logic would be inside `ozone_tab_set_selection()` instead.

**Comment by Ryunam** [comment]
The reason why I left the Netplay and Import Content tabs out of value 3 ("Main Menu and Settings") is that I thought of that value as serving a very specific purpose: it might be useful to have it that way when you want to try if a certain setting might be more or less compatible with more than one piece of content in a playlist. 
Having just Main and Settings keep the cursor position allows for some easy back-and-forth testing in the menu, while still retaining the convenience of having the cursor default to the top entry in the playlists.

Perhaps we should add two more values then:

- Value 4 - "All Non-Playlist Tabs": Main Menu, Settings, Import Content, Explore, Standalone Cores
- Value 5 - "All System Tabs": all of the above **plus** Favorites, History, Music and Video.

What do you think?

Also, at first I did think of putting the logic inside `xmb_tab_selection()` and `ozone_tab_set_selection()` respectively. However, I decided against this idea for these reasons:

- for XMB `settings_t` was declared already in `xmb_list_switch()`;
- based on what I understand so far, the current approach would allow us to skip the *_tab_set_selection() functions completely if the conditions are not met. Instead, if we put the decision logic in there, those functions will be called at all times.

This may or may not matter. Let me know if it's indeed preferrable to apply the suggested change.

**Comment by sonninnos** [comment]
Nah, I don't think it is worth the effort.

Doing the same stuff in the function won't cost much more though, and `settings` could be added to the function parameters too. But no need to hassle with it more as far as I'm concerned.

**Pull request merged**
