### PR TITLE
Reworked Undo options

### PR DESCRIPTION
**Pull request by rz5**
Notable changes and observations:
* Reverted almost all of @fr500's commits related to these features but content_rename_state() is still in task_save_state.c;
* Extended content_save/load_state, to allow them to save the state/load a file into buffers instead saving to disk/changing core's state;
* 'Undo Load State' can be used multiple times, it swaps current state <-> buffered state;
* 'Undo Save State' behavior is different - it undoes the last overwrite done to a savestate file;
* The two associated buffers are meant to be cleared when either the core or the content is changed/closed;

TODOs: Search for TODO/FIXME in command.c and task_save_state.c. There are several places where msg_hash_to_str() should be used and content_reset_savestate_buffers() is called 3 times more than it should when closing a core.

Also worth considering is the memory requirements for this PR: the worst case for memory utilization happens while inside content_undo_load_state(), where we make a temporary copy of the buffered state, to allow the swap. So we'd need 3 * size of a savestate file bytes.
PPSSPP has ~90MB savestates, which means memory requirements are ~300MBs.

### CODE REVIEW

**Comment by fr500** [comment]
you should always rebase not merge to prevent  "Merge remote-tracking branch 'upstream/master'
Also you certainly didn't revert my commits from the menu stuff :p

I still think this needs to have a setting and it should be ifdefed out on consoles.

**Comment by hizzlekizzle** [comment]
Aren't there cores and consoles where it would be appropriate? Wouldn't it be better to toggle the option at runtime than to compile it out entirely?

**Comment by fr500** [comment]
Could be @hizzlekizzle @twinaphex is looking for a solution

**Comment by fr500** [comment]
hmmm merging this is impossible now, a shame since it works really great

**Comment by RobLoach** [comment]
Fixed the merge conflict for @rz5 over at https://github.com/rz5/RetroArch/pull/2 .

**Comment by rz5** [comment]
Thanks to @RobLoach's PR, this fork can again be merged with origin/master. However, the changes in this fork are already in origin/staging.
@fr500 - should this fork be kept alive when you consider the above?

**Comment by fr500** [comment]
no, my staging branch has some code experiments that might not be desirable.

**Comment by fr500** [comment]
this is working perfectly fine right now, way better than the older implementation, and since the older one is in master I would advice merging it or removing the other implementation to avoid problems with the rename function

**Comment by rz5** [comment]
I'm still worried that saving the backups in main memory might cause issues for toasters when they're running e.g. PPSSPP. Since @twinaphex added some code to allow the frontend to know how much RAM the hardware has, we could use that to toggle saving main memory or disk.

I have an inkling of an idea of how it would go. The structs I'm saving that symbolize savestate data have a pointer to the data, the size and a file path.

```
/* Some flag to toggle where the backups are kept */
bool backupInRAM;
...
/* We run the following check at RA startup or core startup */

/* 'MinFeatureReq' is some arbitrary value we deem good enough */
if ( totalRAM > MinFeatureReq)
    backupInRAM = true;
 
...  
```

**Comment by fr500** [comment]
toasters can't run PPSSPP.

**Comment by rz5** [comment]
Here's some more thoughts about huge savestates and running RA in toasters:
If saving the state fails, RA prints a nice error message in the console and in the OSD. Because I reutilized a lot of existing code related to loading/saving state in the new options, nice messages will also be printed if the backups can't be stored in main memory.

I propose pulling my branch as-is. If users complain enough about not being able to take advantage of the undo options (due to not having enough RAM), I'll alter the code some more so that we fall back to saving/loading backups to/from disk if frontend_driver_get_total_memory() is less than 2GB, for example.

**Pull request merged**
