### PR TITLE
Use RGBA for internal format

### PR DESCRIPTION
**Pull request by loganmc10**
Please don't merge without more testing.

This will make GLES devices use GL_RGBA(8) as the internal format, and GL_BGRA as the format.

This should fix the thumbnail colours and still allow GLupeN64 to copy into the libretro framebuffer using glCopyImageSubData.

The only thing I'm not sure on: If this will work with GLES2 only devices like the Raspberry Pi, mine is out of commission right now, but if someone could test this on a GLES2-only device that would be helpful

### CODE REVIEW

**Comment by loganmc10** [comment]
@hunterk @hizzlekizzle If you could test this to make sure the thumbnails/cores that had issues before are still good that would be helpful

**Comment by loganmc10** [comment]
Perhaps @dankcushions or another Raspberry Pi user that knows how to compile RetroArch could try this out on a Raspberry Pi. If it works there and the thumbnails are still good then we should be good to go.

**Comment by dankcushions** [comment]
happy to! but won't have access to my pi until 28th December.

**Comment by hizzlekizzle** [comment]
I don't have an Android toolchain to actually test with but my guess is that will be okay. bparker was doing the testing for me and I asked him to take a look at this PR, as well, but I'm not sure if he can test GLES2-only.

**Comment by bparker06** [comment]
Has anyone done performance testing with this? I know some devices take a sizeable performance hit when using RGBA vs BGRA because of an extra copy done in the driver.

**Comment by loganmc10** [comment]
RGBA is already the default for non-GLES. If you look at the spec for GLES3 glteximage2d (https://www.khronos.org/opengles/sdk/docs/man3/html/glTexImage2D.xhtml), you'll see that BGRA isn't an option. It's an extension for GLES2 and GLES3, so I doubt it's the native format for many devices

**Comment by dankcushions** [comment]
just tested this commit with latest glupen with mario64 and after the initial title card i got some mad flashing and total distortion of the screen. recompiled with mainline retroarch and same thing. so, err, maybe someone else should test :)

**Comment by loganmc10** [comment]
@dankcushions that looks like it's actually an issue with GLideN64, you can work around it for now by changing the core option "Color buffer to RDRAM" from "async" to "off"

**Comment by dankcushions** [comment]
@loganmc10 there are still depth issues for me with it 'off' - very few 3d elements are now rendered. is there an issue logged against gliden64 i can track? getting off-topic, sorry all!

**Comment by loganmc10** [comment]
ya sorry these issues are unrelated to this RGBA stuff, @dankcushions can you try the latest master? I believe the depth issues should be fixed now

**Comment by twinaphex** [comment]
OK so has enough rigorous testing been performed now? What remains to be tested before we can merge this?

**Comment by loganmc10** [comment]
I'm just waiting to hear back from @dankcushions on how this works on the Raspberry Pi. It seems like it worked ok though, he ran into some glupen specific issues, but if this didn't work it would have produced a black screen, and it sounds like it didn't

**Comment by twinaphex** [comment]
OK, I guess @dankcushions makes the final call on this one.

**Comment by loganmc10** [comment]
ok just heard from @dankcushions (https://github.com/GLupeN64/GLupeN64/issues/145#issuecomment-269780197) that this worked, so I think it's good to be merged

**Comment by twinaphex** [comment]
Hi there @loganmc10, reporting one regression -

ever since merging this PR, I can no longer start 2048 on Android, it results in a crash at startup.

To reproduce this -

1 - Go to Load Core, go to 'Download Core...', download the 2048 core.
2 - Select the 2048 core.
3 - Select 'Start Core'.

It should now crash. Previously it would then start the game.

**Comment by loganmc10** [comment]
Even with the latest master? This should have been reverted by https://github.com/libretro/RetroArch/commit/18cfe90d0acad83c8e20b2bea07e98632cf8d740

I'll do some testing in a bit

**Comment by loganmc10** [comment]
I just tried the latest buildbot Android version and 2048 worked for me (Xperia XA)

**Comment by twinaphex** [comment]
I get a crash on my Galaxy S4. I will test some more devices now.

**Comment by twinaphex** [comment]
I don't get the crash on the Shield Tablet, but  I do get it on a Nexus 7 2013 and Samsung Galaxy S4.

**Comment by twinaphex** [comment]
BTW, the 2048 core uses XRGB8888 color format. So I think it's directly related to the GL color format we're trying here.

**Comment by loganmc10** [comment]
GLupeN64 uses the same pixel format, is 2048 the only core that is having an issue? Does glupen64 work on those devices?

**Comment by twinaphex** [comment]
Glupen64 works on the Nexus 7 2013 yes, but of course it's a libretro GL core, not a software rendered core, in so far as that would make any difference.

**Comment by loganmc10** [comment]
Ok I sent a pull request that should hopefully fix it: https://github.com/libretro/RetroArch/pull/4342

**Comment by loganmc10** [comment]
This is definitely the last time I mess with the GL rendering code, even different Android devices behave differently, it's so hard to make sure it works on every kind of device out there. Gotta love OpenGL...

**Pull request merged**
