### PR TITLE
Initial implementation of VK_KHR_display backend.

### PR DESCRIPTION
**Pull request by Themaister**
This is essentially a platform-agnostic KMS-like backend for Vulkan.

### CODE REVIEW

**Comment by twinaphex** [comment]
@Themaister How do we avoid this compilation error for the Windows x64 SEH target? The buildbot just informed about this - 

http://hastebin.com/okiterinog

**Comment by Alcaro** [comment]
Fixed the warning.

sigaction is Unix only. The closest match on Windows is signal(), or (for SIGINT) SetConsoleCtrlHandler(), or just ignore it because Windows builds usually don't have a console. SIGTERM is also Unix only. Ifdef it.

Or move that entire thing somewhere else, the graphics driver has little if anything to do with the signal handlers. Signals should be its own driver, or something like that.

**Comment by Themaister** [comment]
Ah, right. Forgot that it's compiled in for windows as well.

**Comment by Themaister** [comment]
In general, it seems like signals should be caught in frontend, and not context drivers, indeed.

**Pull request merged**
