### PR TITLE
libnx: Fix split joycons mode

### LINKED ISSUE #12685: Nintendo Switch - Only first player controller is detected
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When connecting 2 or more controllers to retroarch, only the controller assigned to player 1 in the switch OS is actually read by RetroArch. 

### Expected behavior

Every controller should be read in each corresponding slot

### Actual behavior

Only player 1's controller is read.

###This Doesn't happen on RetroArch 1.9.4 on the switch, haven't tried 1.9.5

### Steps to reproduce the bug

1. Use RetroArch 1.9.6 on the switch
2. Connect a second controller on switch os
3. Try to use it

- RetroArch: 1.9.6

### Environment information

- OS: Atmosphère 19.5 with OFW 11.0

### PR DESCRIPTION
**Pull request by R-YaTian**
## Description

Fix Button layout on single joycons mode.
This should automatically done by "hidScanInput()" previously, we do it manually now.

## Related Issues

should finally fix #12685

## Related Pull Requests

#12704 #12702

## Reviewers

@m4xw @p-sam

### CODE REVIEW

**Comment by p-sam** [comment]
The reason i've been holding on a PR for this was to get a response from libnx first, as imo we should not have to do this manually. I'm worried right now that you just can't push multiple buttons with this

**Comment by twinaphex** [comment]
My bad for the premature merge @p-sam , I assumed this had been vetted by you guys.

In any case, you can tell me what follow up steps should be done.

**Comment by R-YaTian** [comment]
> The reason i've been holding on a PR for this was to get a response from libnx first, as imo we should not have to do this manually. I'm worried right now that you just can't push multiple buttons with this

Tested and it works fine when pushing multiple buttons.
hmmm, I think we can keep this until get a response from libnx...

**Comment by p-sam** [comment]
From what I see, it at the very least should not allow pressing multiple buttons on the same frame. You'll agree button_state should be an accumulation of all button pressed (button_state |= instead of button_state =) instead of picking the first one you encounter, to keep things like block jumps in Super Mario World possible in the first place. Analog to Digital should help a bit here since it would allow both the stick movement doing dpad and buttons, but did I miss something that makes multiple button presses possible?

**Comment by R-YaTian** [comment]
> From what I see, it at the very least should not allow pressing multiple buttons on the same frame. You'll agree button_state should be an accumulation of all button pressed (button_state |= instead of button_state =) instead of picking the first one you encounter, to keep things like block jumps in Super Mario World possible in the first place. Analog to Digital should help a bit here since it would allow both the stick movement doing dpad and buttons, but did I miss something that makes multiple button presses possible?

oh, any idea to improve multiple buttons input?

**Comment by p-sam** [comment]
See previous message

> button_state should be an accumulation of all button pressed (button_state |= instead of button_state =) instead of picking the first one you encounter

don't forget to set button_state to 0 first else you'd keep presses from the frames before

Be warned that we're still currently debating the best course of action, so the actual change that makes into release may be different in the end, I'm not sure myself yet.

**Comment by R-YaTian** [comment]
> See previous message
> 
> > button_state should be an accumulation of all button pressed (button_state |= instead of button_state =) instead of picking the first one you encounter
> 
> don't forget to set button_state to 0 first else you'd keep presses from the frames before
> 
> Be warned that we're still currently debating the best course of action, so the actual change that makes into release may be different in the end, I'm not sure myself yet.

oh, waiting for you guys to find the best course of action...

**Comment by m4xw** [comment]
Yea currently it should break any button combos

**Pull request merged**
