### PR TITLE
D3D12 Updates

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

- Relocated `d3d12_gfx_sync()` = one frame less lag
- Fixed swap interval option
- Cleanups

Please do test and confirm that I'm not dreaming with that lag reduction!

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
that lag reduction seems like a big deal. Perhaps @Tatsuya79 could help us out with a little high-speed camera verification...

**Comment by sonninnos** [comment]
Anything is welcome. I only did crude comparisons with emulated mouse cursor and OS mouse cursor visible at the same time (ungrab), heh.

It is now not at all far off from gl hard sync / Vulkan.

**Comment by Tatsuya79** [comment]
Someone on win7 and with a hd4000 can definitely not help you in this case. :frowning_face:

**Comment by twinaphex** [comment]
Going to assume this improves things for the better then until somebody points out something to the contrary.

**Pull request merged**
