### PR TITLE
Prevent duplicate inputs when using remaps with input overlays

### LINKED ISSUE #12240: Overlay and Button remapping cause conflicting input.
## Description

Playing on 1.9.1 on android. if you swap two buttons A and B in the controls then when pressing the overlay A button, both an A button press and the remapped B button will register, instead of just the A and, and the same goes for the B button, registering both an A and B button. effectively making remapping useless when using any overlay, and across all cores.

### Expected behavior

remap A to B. and B to A. Press B on the overlay expecting to register an A input

### Actual behavior

A and B are both registered as the same input from the overlay button.

### LINKED ISSUE #12422: RetroArch (32-bit) 1.9.3 uses both default and remapped inputs simultaneously. Using touchscreen controls on Android device
## Description

Updated from RA (32-bit) 1.9.0 to RA (32-bit) 1.9.3 non-Play Store on Android phone, loaded content for which I had a 'core remap' and noticed the game character was performing 2 actions simultaneously upon one button press, I deleted the remap file, resumed content and pressed the same button again and noticed the 2nd unexpected action was the default one. I created the core remap again and the problem persisted. Since the 'Load remap file' entry was still empty I entered it to have it load the .rmp file, but that didn't solve the problem. This happened with FBA 2012 Neo Geo.

Next, I tried with a content for which I had a 'Game remap' on a different core (mGBA). I did everything as described before except that now with a game-specific remap.

I've already tried fresh installs of RetroArch without luck.

### Expected behavior

Only use the remapped inputs and ignore the default inputs until I delete the .rmp

### Actual behavior

Both default and remapped inputs are being used. Upon one button press the character performs 2 actions: 1 determined by the default input and the other determined by the remapped input.

### Steps to reproduce the bug

1. Open RetroArch
2. Launch content
3. Go to Quick Menu -> Controls -> Port 1 and remap inputs.
4. Make sure 'Remap controls for this core' is ON (under 'Input' main settings). If it's turned OFF the remap is completely ignored
5. At this point, the remapped inputs are already active. Resume content and press overlay buttons. (The problem persist regardless of Saving and Loading the .rmp file for Core/Game)

### Version/Commit
RetroArch (32-bit) 1.9.3 Stable
Downloaded from [here](https://www.retroarch.com/?page=platforms)
(the 32-bit specific download for Android)

### Environment information

- OS: Android 4.4

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

As described in #12422, #12240, when using input overlays with an active remap, pressing an overlay button will trigger both the original and remapped inputs (e.g. remap RetroPad A to RetroPad B; pressing A will then trigger both A and B). This happens because the overlay buttons are process twice with insufficient 'guards': `input_driver_poll()` handles all remaps, while `input_state_device()` handles all non-remapped inputs - but the latter does not recognise which buttons have been processed by the former, so the remaps end up getting read twice (with both remapped and 'raw' values).

This small PR fixes the issue by correctly ignoring remapped inputs in `input_state_device()`.

## Related Issues

Closes #12422
Closes #12240

### CODE REVIEW

**Comment by Tatsuya79** [comment]
Thank you it's working fine now, tested on android 11.

The only little remaining issue is that the button you're touching on the screen overlay isn't the one lighting up, it's the one mapped instead.

**Comment by jdgleaver** [comment]
> The only little remaining issue is that the button you're touching on the screen overlay isn't the one lighting up, it's the one mapped instead.

Yeah, that's an annoying little thing, and I'm not really sure what to do about it...

We can make it light up the touched button, but this incurs some nasty performance overheads (i.e. we have to loop over the remaps array every time to find which physical button the input corresponds to). And then if we do this, any remapped input generated from gamepads/other input devices will light up the wrong button... (since it will show physical inputs instead of what the gamepad button is mapped to).

Do you have any suggestions...? :)

**Comment by Tatsuya79** [comment]
Not really, it will stay like this then. :smiley: 
Buttons animation could be disabled when using remaps but that would confuse users too.

**Comment by jdgleaver** [comment]
Hmm... I suppose we could make the 'show inputs' option an enum - 'physical buttons', 'mapped buttons', 'off'. I'll have a look at this next week... :)

**Pull request merged**
