### PR TITLE
Add playlist-based thumbnail downloader

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new entry to the online updater: `Playlist Thumbnails Updater`

This opens a menu that displays all existing playlists. When one is selected, each entry of the playlist is scanned, and any missing thumbnails are downloaded.

This is a lighter alternative to using the huge thumbnail zip archives, and it should work on consoles etc. that have limited RAM. (It also saves disk space, since we only download what we're going to use)

Note 1: The url formation/http_transfer stuff is lifted from PR #8490 (Thanks @fr500!)

Note 2: I've deliberately made this so it only downloads one file at a time. This makes it slower, but since it's explicitly targeting devices that cannot use the zip archives (due to memory constraints), I didn't want to risk 'overloading' the system by spamming multiple concurrent downloads (and it's not really *that* slow)

## Related Pull Requests

I guess this could perhaps be considered as a replacement for PR #8490?

## Reviewers

I've never done any task-related stuff before - only started looking at it a couple of hours ago. Maybe someone more experienced with tasks could check that I've correctly followed the RetroArch paradigm.

### CODE REVIEW

**Comment by fr500** [comment]
Looks good
That's what PoCs are for don't worry about lifting my code.

**Comment by bparker06** [comment]
```
tasks/task_pl_thumbnail_download.c: In function ‘void download_pl_thumbnail(pl_thumb_handle_t*)’:
tasks/task_pl_thumbnail_download.c:164:55: error: invalid conversion from ‘void*’ to ‘retro_task_t*’ {aka ‘retro_task*’} [-fpermissive]
          pl_thumb->http_task = task_push_http_transfer(url, true, NULL, cb_generic_download, transf);
                                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jdgleaver** [comment]
@bparker06 Just pushed a commit - hopefully that will fix it...

**Comment by bparker06** [comment]
Looks like now there's some missing HAVE_MENU ifdefs:

```
obj-unix/release/tasks/task_pl_thumbnail_download.o: In function `download_pl_thumbnail':
task_pl_thumbnail_download.c:(.text+0x9d): undefined reference to `menu_thumbnail_get_system'
task_pl_thumbnail_download.c:(.text+0xab): undefined reference to `menu_thumbnail_get_db_name'
task_pl_thumbnail_download.c:(.text+0xb9): undefined reference to `menu_thumbnail_get_img_name'
task_pl_thumbnail_download.c:(.text+0xce): undefined reference to `menu_thumbnail_get_sub_directory'
task_pl_thumbnail_download.c:(.text+0x251): undefined reference to `cb_generic_download'
obj-unix/release/tasks/task_pl_thumbnail_download.o: In function `task_pl_thumbnail_download_handler':
task_pl_thumbnail_download.c:(.text+0x45a): undefined reference to `menu_thumbnail_path_init'
task_pl_thumbnail_download.c:(.text+0x472): undefined reference to `menu_thumbnail_set_system'
task_pl_thumbnail_download.c:(.text+0x49d): undefined reference to `menu_thumbnail_set_content_playlist'
task_pl_thumbnail_download.c:(.text+0x4c4): undefined reference to `menu_thumbnail_get_label'
```

**Comment by orbea** [comment]
Good to see that testing `HAVE_MENU` with travis is already helpful! :P

**Comment by jdgleaver** [comment]
Ah - thanks for the alert!

I'll fix that immediately...

**Comment by jdgleaver** [comment]
Okay, seems to be fine now :)

**Pull request merged**
