### PR TITLE
implement global shader presets

### PR DESCRIPTION
**Pull request by LazyBumHorse**
## Description

As a followup to #9315, this allows to save global shader presets which have lowest priority.
This effectively has the same behavior as the removed `video_shader` setting with the only difference being that presets have to be saved manually.

The overall preset priority goes like this, from left to right:
game preset > folder preset > core preset > global preset

Tested for xmb, ozone, glui, rgui and Qt.

The global preset file is saved under `presets\global.<type>p`

### CODE REVIEW

**Comment by LazyBumHorse** [comment]
A comma too many, let's see if C89 is happy now

**Comment by LazyBumHorse** [comment]
Get rid of that stray line break as well and it should be good

**Comment by Tatsuya79** [comment]
Working fine here. :+1:

**Comment by LazyBumHorse** [comment]
Thanks for testing!

**Pull request merged**
