### PR TITLE
Change "sombreadores" to just "shaders"

### PR DESCRIPTION
**Pull request by cain-dev**
Nobody in Brazil will understand this made up term, same for "Diretório superior" we use "Diretório acima".

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Thanks for this, but I think translations need to be submitted through Crowdin, as anything committed directly will just get overwritten by the Crowdin integration scripts.

**Comment by cain-dev** [comment]
Sorry to bother but can you do that for me please? It is strange to read "sombreadores" here

**Comment by hizzlekizzle** [comment]
I don't have access to the Crowdin stuff, but perhaps @IlDucci can help us out here.

**Comment by IlDucci** [comment]
Changing translations via PRs is a waste of time, as they will be overwritten by Crowdin's the moment the system updates. So this PR should be closed with extreme prejudice.

Regarding the actual decisions in translations, there's an active Brazilian Portuguese translator in Crowdin's project (his last update was less than a month ago), so you should talk about it with him, either [there ](https://crowdin.com/project/retroarch) or in #retroarch-translations channel, on RetroArch's Discord server.

There's also an additional discussion on Crowdin regarding existing terms, which include the word "shader": https://crowdin.com/project/retroarch/discussions/37

**Comment by cain-dev** [comment]
What do you mean? Extreme prejudice?

**Comment by sonninnos** [comment]
As in "no hesitation"

**Comment by cain-dev** [comment]
> As in "no hesitation"

Thanks for the explanation, i've made the account there and did the same.

Thanks for the info guys o/

**Pull request closed without merging**
