### PR TITLE
(WiiU) Buildfix 2

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi @Cthulhu-throwaway , this might not be related to this PR per se, but I notice something concerning - when I select 'Update Assets', after downloading the assets, it reports back 'Extracting assets.zip (Task failed)'. Does this happen to you too? Can we track down when this broke down?

**Comment by LibretroAdmin** [comment]
Weird -

weird
the only way I have been able to fix it
is to get rid of the existing assets in the folder
and redownload and extract it from scratch
then it works

**Comment by LibretroAdmin** [comment]
It seems the write permissions are not set?

**Comment by Cthulhu-throwaway** [comment]
> It seems the chmod write permissions could be messed up for TTF files?

Works fine for me on Windows 7.

https://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z over my current (1.10.0) installation.

```
[INFO] RetroArch 1.10.3 (Git 38f6ad9)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Jun 26 2022
[INFO] Version: 1.10.3
[INFO] Git: 38f6ad9
```

**Comment by LibretroAdmin** [comment]
It definitely still happens here.

More context - I am building with the latest Msys2/Mingw-w64. 

> gcc version 12.1.0 (Rev2, Built by MSYS2 project)

> after selecting Update Assets from the menu
if you then try to Update Assets a second time
extraction will fail
on the first bold.ttf file
I don't know when this problem suddenly started happening but it is happening consistently now
if I check permissions they look like this
-rw-r--r-- 1 libre libre     594 Jun 26 16:41 README.md
-rw-r--r-- 1 libre libre 2691456 Jun 26 16:41 bold.ttf
drwxr-xr-x 1 libre libre       0 Jun 26 16:41 png
-rw-r--r-- 1 libre libre 2569576 Jun 26 16:41 regular.ttf
chmodding the files also does nothing
this is the error that happens
[ERROR] Failed to deflate C:\RetroArch\assets\ozone/bold.ttf.

**Comment by Cthulhu-throwaway** [comment]
> It definitely still happens here.
> 
> More context - I am building with the latest Msys2/Mingw-w64.
> 
> > gcc version 12.1.0 (Rev2, Built by MSYS2 project)
> 
> > after selecting Update Assets from the menu
> > if you then try to Update Assets a second time
> > extraction will fail
> > on the first bold.ttf file
> > I don't know when this problem suddenly started happening but it is happening consistently now
> > if I check permissions they look like this
> > -rw-r--r-- 1 libre libre     594 Jun 26 16:41 README.md
> > -rw-r--r-- 1 libre libre 2691456 Jun 26 16:41 bold.ttf
> > drwxr-xr-x 1 libre libre       0 Jun 26 16:41 png
> > -rw-r--r-- 1 libre libre 2569576 Jun 26 16:41 regular.ttf
> > chmodding the files also does nothing
> > this is the error that happens
> > [ERROR] Failed to deflate C:\RetroArch\assets\ozone/bold.ttf.

Just tried it again with the nightly build... 3 times in a row and no issues for me.

**Comment by LibretroAdmin** [comment]
Apparently the latest Freetype DLL in Mingw has some kind of open file handle issue. 

If I use the stb_unicode font renderer driver, this doesn't happen.

./configure --disable-freetype --enable-stb_font

Since stb_unicode seems to be equivalent in terms of features as the Freetype driver, we might be able to just use stb_unicode from now on.

I confirmed this issue does not happen with RetroArch Linux on Ubuntu with Freetype.

**Comment by LibretroAdmin** [comment]
For the record, I solved this problem with this commit -
https://github.com/libretro/RetroArch/commit/128753c81dabb66c1958b80ba77034e9d4125ce5

**Pull request merged**
