### PR TITLE
Add 3DS threads

### PR DESCRIPTION
**Pull request by meepingsnesroms**
Compiles and runs.

### CODE REVIEW

**Comment by twinaphex** [comment]
Before you submit this, let's do one thing at a time here -

3DS is still not building on the buildbot - let's fix this first -

http://p.0bl.net/144169

[quote]
mv: cannot stat '../retroarch_3ds.xml': No such file or directory
[/quote]

**Comment by meepingsnesroms** [comment]
I can wait, I was unaware that was still happening.

**Comment by meepingsnesroms** [comment]
The snes9x issue has been fixed, I replaced posix_memalign with normal memalign for 3DS.

**Comment by twinaphex** [comment]
What about this issue?

mv: cannot stat '../retroarch_3ds.xml': No such file or directory

after each successful core compilation.

**Comment by meepingsnesroms** [comment]
Those files are not even used in the build, the new devkitarm likely does not generate them.
This is not a bug, just an annoying log entry.

**Comment by orbea** [comment]
As its an error message, yes, it is a bug...

**Comment by meepingsnesroms** [comment]
The only answer I can give is to remove the mv command, that file is no longer generated by the sdk.

**Pull request merged**
