### PR TITLE
Add more flags to `./configure`

### PR DESCRIPTION
**Pull request by thiagokokada**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

This PR implements some extra new flags to `./configure`:
- `HAVE_UPDATE_CORE_INFO`: similar to the existing `HAVE_UPDATE_ASSETS`, allow disabling the "Update Core Info" from "Online Updater"
- `ASSETS_DIR`: this flag already exists before, but changed it so its path is also in the assets search path inside `platform_unix.c`
- `FILTERS_DIR`: similar to the `ASSETS_DIR`, this flag will be an additional path for the filter search path inside `platform_unix.c`

The use case for then is for our package inside nixpkgs. We have some big patches that we need to ship to make the assets load statically. And while this PR doesn't fix all the issues we have, it will reduce the number of patches we have.

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi, can you fix some of the build failures that are happening in some of the CI jobs?

**Comment by thiagokokada** [comment]
> Hi, can you fix some of the build failures that are happening in some of the CI jobs?

Hope [2bf7ce9](https://github.com/libretro/RetroArch/pull/14756/commits/2bf7ce9200254438dfe5934bf123f53620a48172) will fix it.

**Comment by thiagokokada** [comment]
`linux-c89` fail doesn't seem related to this PR (I can see the builds in `master` failing for the same reason).

**Comment by LibretroAdmin** [comment]
Yeah, it was unfortunately some other PR that screwed that up. I'm in the process of fixing it now.

**Comment by thiagokokada** [comment]
> > Hi, can you fix some of the build failures that are happening in some of the CI jobs?
> 
> Hope ~[2bf7ce9](https://github.com/libretro/RetroArch/pull/14756/commits/2bf7ce9200254438dfe5934bf123f53620a48172)~ [c3f55b7](https://github.com/libretro/RetroArch/pull/14756/commits/c3f55b72505e178b15f0696637441538c3b410c2) will fix it.

Did a better fix that doesn't depend on updating each `Makefile` that uses `platform_unix.c`.

**Comment by LibretroAdmin** [comment]
Alright, I'll have to manually go over the Makfiles that already define `HAVE_UPDATE_CORES` and add `HAVE_UPDATE_CORE_INFO` too, but I can manage that. I'll merge this then.

**Pull request merged**
