### PR TITLE
Fix undeclared (VIDEO_RGA_SCALING) label

### PR DESCRIPTION
**Pull request by shantigilbert**
## Description

This commit, https://github.com/libretro/RetroArch/commit/2c635e9e1b73a697d22c703dad05f08c20595c11 is missing this declaration. Without this, RA will not compile for the Odroid Go Advance

### CODE REVIEW

**Comment by valadaa48** [comment]
Why are there references to both CTX_SCALING and RGA_SCALING? I thought the agreement was to use CTX_SCALING?

**Comment by twinaphex** [comment]
I will merge this for now so that the compilation can work again. However, let's indeed get both of you guys on the same page with regards to what @valadaa48 is saying here. If the agreement was to use CTX_SCALING, then I guess in a followup PR you guys can get rid of the other enum.

Just let me know what kind of consensus you two have reached. You could perhaps discuss this on Discord too if needed or here on Github.

**Comment by shantigilbert** [comment]
Thank you @twinaphex. I did not made the change, it was originally on the commit I mentioned (https://github.com/libretro/RetroArch/commit/2c635e9e1b73a697d22c703dad05f08c20595c11) by @guoyunhe , I just merely added the declaration so that it compiles again on the OGA.

**Comment by valadaa48** [comment]
@shantigilbert can you verify that both oga (2D) driver and gl + ctx/rga_scaling works still?

**Comment by shantigilbert** [comment]
Yes, works as it did before

**Comment by valadaa48** [comment]
@twinaphex posted from the chat:

actually, on second look - I think it's fine the way it is.  This is just a matter of the menu system. We either #ifdef CTX_SCALING for odroidgo2 filling in RGA + warnings or just create another label (which is how it is now) and it's more explicit.
I don't think there's anything to change

**Pull request merged**
