### PR TITLE
Use overlay separation parameters only for auto-scale

### PR DESCRIPTION
**Pull request by Valent-in**
Remove aspect ratio check which disables Y separation in portrait mode for auto-scale.
Do not block manual adjustment of overlay X/Y separation

Fix https://github.com/libretro/RetroArch/issues/14699

### CODE REVIEW

**Comment by Valent-in** [comment]
Also prevents this for overlays without separation parameter (notice shifted dpad_up and X buttons when screen aspect ratio is smaller than overlayXX_aspect_ratio in config)

RA_overlay_glitch

**Comment by LibretroAdmin** [comment]
Hi @neil4 , would you like to review this?

**Comment by neil4** [comment]
Defaulting block_y_separation to true sounds like a good idea since any overlay not made with Y separation in mind will probably have a problem with it.

I don't think auto-scale's aspect ratio check should be removed. Auto-scale separates things as much as it can, so it might move portrait controls too far down on overlays with block_y_separation=false.

**Comment by Valent-in** [comment]
This parameter does not work in portrait mode - it is always "true". So removing aspect ratio check just enables it.

Setting default value for it does not make sense until it actually works.

If overlay config has explicit option "stick to top/bottom in portrait mode" it should not be ignored.

**Comment by neil4** [comment]
It does work in portrait mode if auto-scale is off, using "(Portrait) Overlay Vertical Separation".

Having block_y_separation=false only means Y separation is permitted. It doesn't mean auto-scale must always use it, and it doesn't have to mean max separation.

**Comment by Valent-in** [comment]
Ow, thanks. Had not noticed this "dual purpose" before... Which is rather strange. I think X/Y separation parameters should work *only* as hints for auto-scaling. What is the reason to block manual adjusting of this parameter? If user wants this - why not?

Anyway, changes are inside conditional operator. So it applies only if auto-scale is enabled.
https://github.com/libretro/RetroArch/blob/f4e545e588e777ae755b5fb0e44d40ad5cee5ca4/input/input_driver.c#L1726-L1727

**Comment by neil4** [comment]
> If user wants this - why not?

I think partly to avoid any misperception that something is wrong with the overlay or the feature. But it can also avoid bad situations if a user adjusts x/y separation and then swaps to an overlay that doesn't support it.

> it applies only if auto-scale is enabled.

That's where I _don't_ think the change is needed. Portrait controls are usually at a good height already, roughly where your thumbs rest and not on top of the video (usually).

**Comment by Valent-in** [comment]
Overlay may be used on screens with different size and aspect ratio, with different scale and game vieport dimensions. Which is not initially designed for. It is not possible to account all use-cases.
Applying separation block to autoscale gives more control for overlay developer. And blocking manual separation means less control for user.

Almost all builtin overlays has same design (fill only bottom half in portrait, 16:9 initial aspect). So manually set separation will give same result on different overlays. Now behavior is inconsistent - for some overlays these settings does not  have any effect, but for others does. And no cue for user, why.

Also some 3rd-party portrait overlay may have buttons above game viewport and separation parameter (combined with vertical shift) should allow place it correctly 

If default block_y_separarion will be set to true it will block manual adjustment for overlays without this option. This is opposite to what I want to achieve.

**Comment by neil4** [comment]
You're asking to change the meaning of block_y_separation. So maybe what you really want is a new option, like an 'auto_separate_y' in the cfg to tell auto-scale to use Y separation...?

**Comment by Valent-in** [comment]
> You're asking to change the meaning of block_y_separation.

I have no clear answer for this... As it is already blocking separation, and I just removed some conditions. So meaning did not change much.

I think it should be used for auto-scale only. And without blocking manual settings.

If overlay does not designed for splitting on center line, then changing these parameters will give visual feedback for user - what exactly wrong here. Instead of current "silent ignoring".


> But it can also avoid bad situations if a user adjusts x/y separation and then swaps to an overlay that doesn't support it.
Not in all cases. There will be button misalignment in overlays with background image (like builtin gba-anim/gb-anim). And just blocking separation by default is bad solution - it may break existing configurations for many users.

**Comment by neil4** [comment]
This PR now effectively removes block_x/y_separation in favor of something that requests (or requires?) X/Y separation from auto-scale when false. I really think it needs to be a new option like I suggested, probably in a fresh PR.

On unblocking the manual adjustments, there could be an override for that, but honestly if the overlay wants it blocked I don't see much upside.

**Comment by Valent-in** [comment]
Rebased by mistake

> I really think it needs to be a new option like I suggested, probably in a fresh PR.

Created new PR: https://github.com/libretro/RetroArch/pull/15106

**Comment by neil4** [comment]
Saw this a little too late. I'll be out for a week FYI but will take a look when I'm back.

**Pull request closed without merging**
