### PR TITLE
(Manual Content Scanner) Enable automatic naming of arcade content via DAT files

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new `Arcade DAT File` option to the manual content scanner.

This is compatible with DAT files in either `Logiqx XML` or `MAME List XML` format. When a DAT file is selected, a lookup is performed for each item of scanned 'archive-type' content. This allows automatic conversion of 'meaningless' arcade file names (e.g. `garou.zip`) into proper description labels in playlists.

These DAT files are readily available online - e.g.:

https://github.com/libretro/FBNeo/tree/master/dats
http://www.progettosnaps.net/dats/MAME/
https://github.com/libretro/mame2003-plus-libretro/blob/master/metadata/mame2003-plus.xml

-----

Here's an example use case:

With the latest DAT from here: http://www.progettosnaps.net/dats/MAME/

...I can scan my `NAOMI` collection:

Screenshot_2019-12-04_12-38-01

...with the following settings:

Screenshot_2019-12-04_12-41-14

...and obtain a nice tidy playlist like this:

Screenshot_2019-12-04_12-42-03

---

This PR also fixes some serious errors in the `rxml` code.

### CODE REVIEW

**Comment by fr500** [comment]
The RDBs are created from these files.
Wouldn't it be possible to use those too?

**Comment by jdgleaver** [comment]
@fr500 The RDB files are locked behind an `#ifdef HAVE_LIBRETRODB`

I wanted a solution that would work on *all* platforms.

**Comment by fr500** [comment]
I see, good call.

**Comment by fr500** [comment]
Is it possible to use the RDBs too somehow? because unlike these, everyone has the RDBs, I think they are always packaged.

**Comment by fr500** [comment]
also, I figure rxml may be a bigger dep when considering memory footprint alone, isn't it?

**Comment by jdgleaver** [comment]
> Is it possible to use the RDBs too somehow? because unlike these, everyone has the RDBs, I think they are always packaged.

Still only included if `HAVE_LIBRETRODB` is defined  :)

But I really don't want to deal with the databases. That code is a big old hairy mess of beans, and the arcade rdb files don't even contain essential info like `is_bios` or `runnable` (I can't scan without this). So that means the databases would need to be updated too, and I'm not interested in that.

If a user has enough sense to find an arcade rom set, I think they should be capable enough to find a dat file!

> also, I figure rxml may be a bigger dep when considering memory footprint alone, isn't it?

Not really. The rxml (and underlying yxml) code is incredibly small and lightweight (there's hardly anything to it at all). It's probably one of the most trivial dependencies in the whole of RetroArch  :)

XML dat files are of course larger than rdb files - but this is never an issue on desktop/modern mobile platforms, and console ports generally only run arcade cores for which the corresponding dat files are small.

**Pull request merged**
