### PR TITLE
Hide mouse when loading overlay in fullscreen.

### PR DESCRIPTION
**Pull request by Tatsuya79**

### CODE REVIEW

**Comment by orbea** [comment]
@twinaphex I can confirm this issue and fix, is there a problem with this PR?

**Comment by Tatsuya79** [comment]
They don't want overlay to hide the mouse because we could have overlays for computers where you could click on a setting or drive on screen.
So this should be made an option I guess.

**Comment by hizzlekizzle** [comment]
Having a flag in the overlay itself to do it is an interesting idea, though with the option to show button presses on the overlay, I can imagine situations where someone would want to hide the cursor on an overlay that would typically be used for control (i.e., where the author wouldn't think to include the 'hide cursor' flag).

**Comment by twinaphex** [comment]
OK so what are the outstanding issues here @Tatsuya79 ? A setting still needs to be added?

@hizzlekizzle what do you think about this? Should this be the default or should this be a setting that is enabled optionally?

**Comment by Tatsuya79** [comment]
It's totally up to you as I don't use overlays as borders at all.
Just made that for people asking for this repeatedly.

**Comment by Ryunam** [comment]
I began to refactor this change with a selectable toggle positioned under Settings -> Onscreen Display -> Onscreen Overlay, with the default behaviour set to show the mouse cursor like it is right now.

If everyone agrees on this approach, I can finish working on it and submit a PR shortly.

**Comment by twinaphex** [comment]
@Ryunam Ah yes, that would be a good idea. I'm OK with that.

**Comment by orbea** [comment]
Since PR https://github.com/libretro/RetroArch/pull/8903 was merged I am going to go ahead and close this one. :)

**Pull request closed without merging**
