### PR TITLE
Enable CHD hashing on libnx

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by phcoder** [comment]
@m4xw @LibretroAdmin WDYT?

**Comment by LibretroAdmin** [comment]
Hi there @m4xw ,

requesting a review of this since it pertains to the libnx port. Thanks.

**Comment by ccondry** [comment]
any chance of this getting merged? I would love to get CHD files working with retro achievements on the Nintendo 3DS platform.

**Comment by yonailo** [comment]
Yes now that the Virtua Tennis 2 retroachievement for Dreamcast is out in the wild I can not use it because of this, +1

**Comment by m4xw** [comment]
We wanted to avoid this for switch

**Pull request merged**
