### PR TITLE
Vulkan maintenance and bug fixes.

### PR DESCRIPTION
**Pull request by Themaister**
Integrated Vulkan Validation Layers and found lots of errors.
A lot of the errors concerned uninitialized structs which must have happened during coding style cleanups.
There is a good reason that I initialize the structs the way I do in Vulkan backend.
No serious errors are now reported by Validation layers so this might fix AMD Vulkan.

Also started sketching out interface for async compute where libretro cores have high degree of control over how the device is created.

### CODE REVIEW

**Comment by twinaphex** [comment]
BTW maister, we still like to have a Windows XP version, unfortunately, there is a part in glslang right now that prevents that.

https://github.com/KhronosGroup/glslang/blob/a4a4d5e22c375d37bd286106904ef819eafff29b/glslang/Include/Common.h#L205

This function is not available for Windows XP.

Can a potential workaround be pushed to glslang to still ensure we can make a general Windows version that will also work for XP?

**Comment by Themaister** [comment]
If it's a link-time error, can't we implement _itoa_s in compat module?

**Comment by Themaister** [comment]
In that case, wouldn't _itoa_s be linked statically and not actually try to link against windows runtime? If we override it for all windows versions, it should still work.

**Comment by twinaphex** [comment]
It looked like a dynamic runtime error to me where the function could not be found. Maybe its down to some mingw toolchain issue on our buildbot again. Maybe I can bring @fr500 into this conversation.

**Comment by Themaister** [comment]
ye, in that case I think just implementing _itoa_s in RetroArch would fix that problem.

**Pull request merged**
