### PR TITLE
XMB: Add Light theme

### PR DESCRIPTION
**Pull request by RobLoach**
## Description

This adds a Light theme, which reflects the Dark color theme. 

light-theme

With #5972 , it's easier to read the text.

font

## Related Pull Requests

- https://github.com/libretro/RetroArch/pull/5972 Allow changing Font Menu Color

### CODE REVIEW

**Comment by fr500** [comment]
My Eyes!!!!

**Comment by fr500** [comment]
But it's cool, just blinding as every light theme :)

**Comment by hyarsan** [comment]
I feel like the icons should be inverted.

**Comment by RobLoach** [comment]
> I feel like the icons should be inverted.

That would be on [retroarch-assets](https://github.com/libretro/retroarch-assets) front. Perhaps a `monochrome-black`.

**Comment by hyarsan** [comment]
Can't a simple invert function be implemented for mono-chrome? Like it detects if you're using monochrome with the Light theme, and then it inverts it?

**Comment by RobLoach** [comment]
Problem comes in when you're using FlatUI or Systemic. You don't want those ones inverted.

**Comment by hyarsan** [comment]
I said it should detect if you are using monochrome?

**Comment by RobLoach** [comment]
Not going to do that. Outside scope of this feature request. This is just about adding a Light theme, not changing the icons.

**Comment by hyarsan** [comment]
That's okay. Thanks for this light theme.

**Comment by RobLoach** [comment]
Great idea though! Changing the bitmask is a bit more complicated in RA. It would be much easier to change it on the retroarch-assets front. A small script could do it.

**Comment by hyarsan** [comment]
Have you tried experimenting with no gradient? Maybe that could look good...

**Comment by hyarsan** [comment]
cleaner

It looks a lot cleaner to me this way.

**Comment by RobLoach** [comment]
MonoChrome Inverted https://github.com/libretro/retroarch-assets/pull/199

Just all white? My monitor is not good enough to pick up the difference lol. Have a git diff?

**Comment by hyarsan** [comment]
Ooh, that's really cool! All white really does make it look cleaner. Or just reduce the gradient.

hereiguess

**Comment by hyarsan** [comment]
I know this isn't as easy but, can the pipelines also be inverted later on? ( Black ribbon, black snowflakes... )

**Comment by RobLoach** [comment]
Unsure, never played with the shaders before. Snowflake looks pretty cool.

screenshot at 2017-12-27 19-55-34

**Comment by hyarsan** [comment]
That's very neat! I just realized that the FlatUI and Pixel also should have inverted variants.

**Comment by twinaphex** [comment]
I think the text can still be too hard to read on an entirely white background.

**Comment by hyarsan** [comment]
I don't think that there is anything more clear than black on an white background. It looks like RobLoach turned off the shadows for his latest screenshot?

**Pull request merged**
