### PR TITLE
provide a means for cores to coordinate with the frontend when shutting down multiple threads gracefully

### PR DESCRIPTION
**Pull request by RetroSven**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

provide a means for cores to coordinate with the frontend when shutting down multiple threads gracefully

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

@twinaphex

### CODE REVIEW

**Comment by twinaphex** [comment]
Historically we never wanted anything in libretro to deal with threads. This seems like it violates that design rule.

Why do you need this environ callback added? You are just stopping/starting the audio driver? Is there no other way for you to just avoid this crash on exit?

**Comment by RetroSven** [comment]
see my comments on https://github.com/libretro/reicast-emulator/issues/260

we either need a callback to tell cores that RA has entered paused/menu mode or we need this callback

**Comment by twinaphex** [comment]
OK, I will be asking @Themaister again for commentary on this.

**Comment by twinaphex** [comment]
Can we make these private environment callbacks for now ? That way, we don't commit to them just yet in the API (libretro.h) but we can still fix the RetroArch bug all the same. We will return to it after some consultation so we can push them then to non-private.

**Comment by twinaphex** [comment]
@Themaister still believes this is plain wrong, and he is going to make a test core illustrating how it is supposed to be done instead.

**Comment by RetroSven** [comment]
@twinaphex I'm pretty sure I know what @Themaister is going to suggest - which will essentially be restoring what I previously implemented and was recently removed to simplify the process.  We can  put that stuff back, but if all of the recent libretro defines are going to go away (including the one for fastforwarding) then you're still going to have the fastforwarding issue to deal with.  Please be sure he's aware of that as well.

Also, this really doesn't have anything to do with any of the things I added recently (save states, vmu display).  This is all tied to the original implementation of threaded rendering in reicast.  I just got sucked into it because save states weren't working from the main menu - but that's because of the way threaded rendering is implemented and the video/audio mutexes/blocking.  If you roll everything back to after threaded rendering was implemented and before save states was implemented, you'll still have the same problems with RA crashing whenever you close content in threaded mode if you happen to pause RA when the reicast CPU loop is blocked in the audiostream.cpp:audio_batch_cb call.  What happens is that RA free()s the audio driver resources while audio_batch_cb is waiting on them - resulting in audio_batch_cb trying to access free()d resources.  We can workaround that with the implementation I put in place earlier with the audio callbacks, but the fast forward problem will still remain.


I'm  happy to assist, but I get the impression that this is deemed to be related to something that I did and therefore my responsibility (because all of these issues are getting routed directly to me)

**Comment by twinaphex** [comment]
@RetroSven Yeah, to be honest, it is not helping that @Themaister does not want to look at the actual Reicast implementation, so yeah, I'm in a bit of an uncomfortable position here where on one hand I want to see these Reicast issues fixed and on the other hand I have to also be cognizant of libretro API changes that go on.

> I'm happy to assist, but I get the impression that this is deemed to be related to something that I did and therefore my responsibility (because all of these issues are getting routed directly to me)

I hugely appreciate your contributions and I can understand if you're getting fed up of the filibustering. I might have to just compromise and go with your solution.

Can we come to a compromise for now then? Can you make these private environment callbacks so that we can have our cake and eat it for now with the latest RetroArch version and the latest Reicast core? That way, it is not yet set in stone in the main API, but we still have the main issues fixed.

So, just make these two environment callbacks private, don't put them in libretro.h, that way they are for now undocumented private environment callbacks that we just use in this core and RetroArch. This gives us a fair amount of time to orient around and experiment with alternative approaches in case it ever gets anywhere.

Thanks again for your contributions. I don't want to give you the impression your commits are not appreciated, far from it.

**Comment by RetroSven** [comment]
@twinaphex oh no, was not feeling unappreciated - just suggesting we may also want to loop in whoever it was who did the threaded rendering implementation so that they can "share the love"  :)  I'll remove the libretro.h stuff and push it to retroarch.h and libretro.cpp

**Comment by twinaphex** [comment]
OK, cool.

And yeah, the threaded rendering implementation was @flyinghead's work.

**Comment by twinaphex** [comment]
@RetroSven The fastforwarding environment callback can stay in libretro.h. The rest is fine though. So change that last part and it's OK.

**Comment by twinaphex** [comment]
Alright, we'll settle at this for now. This way it's not yet a part of the libretro API but we still have a fully functional libretro core right now that at least works on RetroArch. Hopefully @Themaister can do some investigation into the Reicast core though to determine whether all this hacking around is even necessary.

**Pull request merged**
