### PR TITLE
New XMB Menu Color Theme: Sunbeam

### PR DESCRIPTION
**Pull request by fpscan**
image

### CODE REVIEW

**Comment by RobLoach** [comment]
While it is pretty, I find the white at the top left of the screen makes it difficult to read the text. Could work on the text contrast to ensure it's readable across devices.

**Comment by fpscan** [comment]
> While it is pretty, I find the white at the top left of the screen makes it difficult to read the text. Could work on the text contrast to ensure it's readable across devices.

Thank you for your feedback, Maybe this is why Autechre is not merging,

**Comment by RobLoach** [comment]
Also note that it is possible to change the Menu Font color...

Screenshot at 2019-10-25 14-57-03

Unfortunately we can't currently change those settings from the theme itself. You could expect that user to change the text color to black if needed.

**Comment by fpscan** [comment]
> Also note that it is possible to change the Menu Font color...
> 
> Screenshot at 2019-10-25 14-57-03
> 
> Unfortunately we can't currently change those settings from the theme itself. You could expect that user to change the text color to black if needed.

isn't it hard to see with Light?
image

**Comment by twinaphex** [comment]
Yeah I do find that the Light theme should be fixed.

What about Sunbeam? Does the text stand out more now while still maintaining the same color scheme? Otherwise I think this looks very good.

**Comment by RobLoach** [comment]
> isn't it hard to see with Light?

Correct, with Light theme, it's best to use.....

- Menu Font Color: 0
- Menu Icon Theme: Monochrome Inverted
- Icon Shadows: Disabled
- Menu Color Theme: Light

light

It would be awesome if we could change those settings automagically when swiching the Menu Color Theme :wink:

**Comment by fpscan** [comment]
and this is morning blue theme
image

**Comment by RobLoach** [comment]
Both Light and Morning Blue are intended to use the black menu text color, and inverted menu icon color. The issue to have them auto select for you is over at https://github.com/libretro/RetroArch/issues/6380

**Pull request merged**
