### PR TITLE
android: add option to vibrate on touch

### LINKED ISSUE #2834: haptic feedback option for mobile versions
Please add an option to enable haptic feedback (vibration when touching on-screen overlay) to the Android/iOS versions.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32547376-haptic-feedback-option-for-mobile-versions?utm_campaign=plugin&utm_content=tracker%2F296058&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F296058&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bparker06**
Fixes #2834.

### CODE REVIEW

**Comment by blackman91** [comment]
Awesome but it is not working on latest RetroArch Android nightlies (not aarch64) the option is not showing in input settings even with a clean install, I am on Android 7 so it should appear. Please test.

**Comment by Dalorbi** [comment]
Can confirm that option doesn't appear on Android 7 using the 2019-03-13 aarch64 nightly.
Additionally, manually adding the setting to retroarch.cfg `vibrate_on_keypress = "true"` doesn't appear to have an effect either

**Comment by bparker06** [comment]
It shows up for me on aarch64 just fine:

img

There should be nothing preventing the option from appearing. Can you screenshot Information->System Information?

**Comment by Dalorbi** [comment]
Huh, this is odd
Screenshot_20190314-031924
It looks like I've got the 2019-03-10 build installed but I installed Retroarch using the latest nighly.
Reinstalling doesn't seem to change the Build Date either

**Comment by blackman91** [comment]
So the option doesn't work below Android 7 right? Maybe that is causing some issues for other devices.

**Comment by xTMODx** [comment]
We have to wait for a new android build maybe it will work then

**Comment by Dalorbi** [comment]
@blackman91 nice catch. I noticed that one of the changes made was moving from `target=android-24` to `target=android-26` android 7.1 and below match up to android-25 and below

**Comment by blackman91** [comment]
Why does the option even require Android 26? Vibrate on touch works even on jellybean on other emus. Just curious.

**Comment by blackman91** [comment]
On latest nightly the option finally appears but even if you enable it and restart it does nothing at all, nonvibrate on touch on overlays:
Screenshot_20190315-101406

**Comment by bparker06** [comment]
@blackman91 It does not require api 26, that's just when the vibrate API deprecated the older functions in favor of new ones... but my code still has a path for the older devices that still uses the old functions.

@Dalorbi Changing the target api level does not mean that is the minimum version, it means it's the maximum, i.e. we can only use API functions as high as level 26. Whether or not such functions are called only on the right version devices is still up to your code.

My PR supports both api 26 (8.0/Oreo) vibrate API as well as everything before that down to level 1 even.

As far as @blackman91's issue with the overlay not vibrating, I have no idea... but I have verified with multiple other users that the option does work for them.

**Comment by blackman91** [comment]
Thanks for the clarification, to anyone using nightlies from the build bot, does the option work for you? I am on latest nightly and can enable the option but the overlays don't vibrate on touch, does it causes any issues that the overlays are on other file path not the default one on Android?

**Comment by MANGOM1LK** [comment]
Annoyingly vibrations occur whenever the screen is pressed even when an area with no touch buttons is pressed, which defeats the purpose of using haptic feedback

**Pull request merged**
