### PR TITLE
Add a new "Classic (Toggle)" turbo mode

### PR DESCRIPTION
**Pull request by bslenul**
## Description

This PR adds a new "Classic (Toggle)" turbo mode, it acts pretty much the same as "Classic" but instead of disabling turbo on button release you have to press the Turbo hotkey again.

So basically:

* Classic: hold a button then press Turbo hotkey -> button will be turbo until you release it.
* Classic (Toggle): hold a button then press Turbo hotkey -> button will be turbo until you hold it and press Turbo hotkey again.

Please let me know the help text is clear enough!

## Reviewers

@sonninnos @hunterk and/or anyone willing to test!

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
eyyy, I was working on this but had hit a wall, so I'm grateful/excited to find out you were working on it, too! I'll try to give it some testing this evening :)

**Comment by bslenul** [comment]
Yeah I saw your messages while catching up on Discord this morning and thought I could give it a shot! Didn't know you were working on it however, I should've asked first :x 

Turbo mode feels much more "intuitive" that way IMO!

**Comment by hizzlekizzle** [comment]
>I should've asked first :x

not at all! I was only tackling it because it was low-hanging fruit and someone had pointed out on Reddit that my recent turbo-d-pad change didn't really make any useful sense without it latching. I didn't realize that deficiency existed, since I don't use turbo myself, so I figured it needed a change!

**Comment by hizzlekizzle** [comment]
Just did some testing and this seems to work as expected. Good stuff :D

**Comment by Cibomatto2002** [comment]
This will be good for handheld lovers.

**Pull request merged**
