### PR TITLE
Revert incorrect submodule revert.

### PR DESCRIPTION
**Pull request by Themaister**
Commit 996f9a59b7e42287b379ff8b870f603a60a77b46 randomly
decided to change submodules back.

It looked arbitrary, so I assume it was a mistake.

### CODE REVIEW

**Comment by Alcaro** [comment]
Yeah, my git is an idiot. I don't know enough about git to get rid of them.

Let's hope those things are properly packaged soon enough so we can get rid of this incomprehensible misfeature.

**Comment by Themaister** [comment]
git submodule update should do the trick.

**Comment by Alcaro** [comment]
Yeah, that fixed it.

But I'm afraid you'll have to remind me every time you update those submodules. At least until git quits being some kind of low-level piece of plumbing full of stupid failure cases.

**Comment by Themaister** [comment]
Ye, kinda surprised git pull doesn't do that automatically :\

**Pull request merged**
