### PR TITLE
Add Indonesian, Swedish and Ukrainian language options

### PR DESCRIPTION
**Pull request by DisasterMo**
## Description

Since the translations into these languages have progressed noticeably, it has been deemed appropriate by the Crowdin management to add them to RetroArch.

## Reviewers

@IlDucci @guoyunhe

### CODE REVIEW

**Comment by DisasterMo** [comment]
I forgot to mention: For RGUI languages are divided into English + 5 other groups (extended ASCII, Asian, Russian, others & "no font available"?). I have not categorised these new languages like this, yet. It would be great, if anyone could help me out with this.

**Comment by DisasterMo** [comment]
Indonesian and Swedish seem to fit into the extended ASCII category (each use the Latin alphabet with some extra letters). Can someone confirm this?

Ukrainian uses the Russian alphabet + a couple extra letters. Not sure what to do here.

**Comment by IlDucci** [comment]
@DisasterMo Doing a quick Google search, it seems that your comments are correct:
 - Indonesian and Swedish stay in Latin-1 Supplement territory: 
   - (Wikipedia reference for ISO 8859-1)[https://en.wikipedia.org/wiki/ISO/IEC_8859-1]
   - (Character Table page for Indonesian)[https://character-table.netlify.app/indonesian/]
   - (Character Table page for Swedish)[https://character-table.netlify.app/swedish/]
 - Ukrainian does indeed have two different characters from the standard Russian Cyrillic set. I'd have to see the current Russian RGUI font to verify if those two extra characters are or are not available.
   - (Wikipedia reference to Code page 1124 for Ukrainian)[https://en.wikipedia.org/wiki/Code_page_1124]
   - (Character Table page for Ukrainian)[https://character-table.netlify.app/ukrainian/] Notice that the extra characters, Ґ and ґ, are at the very bottom.

**Comment by guoyunhe** [comment]
Maybe just use geo location to divide languages: West Europe, East Europe, Asia, Africa, North America, etc.

**Comment by IlDucci** [comment]
@guoyunhe According to the first lines of this file:
https://github.com/libretro/RetroArch/blob/master/gfx/drivers_font_renderer/bitmapfont_10x10.c
The separation is done via Unicode ranges. ( https://www.ssec.wisc.edu/~tomw/java/unicode.html ) Therefore, any new font files should be made keeping the ranges/alphabets in mind.

**Comment by DisasterMo** [comment]
Okay, I gave it a go on RGUI:

- Indonesian and Swedish work fine with extended ASCII
- Ukrainian crashes RA with the Russian font - so no dice there

I say let's merge it how it is and maybe add support for Ukrainian later.

**Comment by guoyunhe** [comment]
@DisasterMo can you post this PR's link to the localization document? here are a lot of translation contributors asking how to add language to the software's language menu.

**Comment by DisasterMo** [comment]
@guoyunhe Just wanted to let you know, I am currently rewriting the respective section of the docs and will include a note on it in the translators guide as well. Should be finished soon.

**Comment by Dontknow09** [comment]
> Indonesian and Swedish seem to fit into the extended ASCII category (both use the Latin alphabet with some extra letters). Can someone confirm this?

Yes, Swedish does in fact use extended latin (the only extra letters are 'å, ä, ö')

**Pull request merged**
