### PR TITLE
Add option to scale overlays automatically (with aspect ratio correction)

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

PR #11305 added comprehensive options for adjusting the scale/position/spacing of overlays, allowing proper aspect ratio correction on non-16:9 displays. The problem is that these options are rather tricky for the average user to configure, particularly on mobile platforms where the overlay itself often has to be used to adjust the various parameters (a literal moving target, so to speak...).

This PR adds a new `Auto-Scale Overlay` option under `Settings > On-Screen Display > On-Screen Overlay` (enabled by default on mobile platforms, disabled by default elsewhere). When enabled, the overlay scale, aspect and horizontal/vertical separation are automatically adjusted to fit the current display. Which means you get the following with zero additional configuration:

Screenshot_2020-09-17_17-13-20

Screenshot_2020-09-17_17-16-15

Screenshot_2020-09-17_17-17-14

Screenshot_2020-09-17_17-14-59

Screenshot_2020-09-17_17-15-40

By default, this new feature assumes that existing layouts with `portrait` in the name have a native aspect ratio of 9:16, while everything else has an aspect of 16:9. This works in most cases - but for the purposes of fine-tuning (by overlay developers), the following additional parameters have been added to the overlay spec:

- `overlayN_aspect_ratio`: Allows the precise native aspect ratio to be specified

- `overlayN_block_x_separation`: When `true`, disables adjustments to the horizontal separation of overlay elements

- `overlayN_block_y_separation`:  When `true`, disables adjustments to the vertical separation of overlay elements

The two `block...separation` options are for overlays with grouped elements that sit astride a centre line (to prevent them from being pulled apart). The default (on mobile) `neo-retropad` overlay requires these additional parameters - I will PR the changes immediately after posting this.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
@jdgleaver would it make sense to, instead of having it as a RetroArch setting that we default on/off by platform, make it one of the overlay attributes? That is, the way we have overlay_fullcreen = true (or whatever; I forget the exact syntax), have overlay_aspect_adapt = true?

**Comment by jdgleaver** [comment]
@hizzlekizzle I do see your point here, but there are a couple of issues with this:

- We would have to update every gamepad preset in order to enable auto-scaling - this is quite laborious! With the current implementation, almost every existing overlay works out-of-the-box (it's only the ones with dpads and face button groups which span a centre line that need some attention)

- If the option is set via the config file, then how would a user disable it? It's a valid use case to *not* always scale a gamepad overlay - a user might want to shrink it a little, or move it lower on the screen. If the option is force enabled for an overlay, then we need to have some kind of fiddly option: `Auto-Scale Overlay`: `Off`, `On`, `Use preset value`. I guess that's not too bad, actually - but then for mobile platforms we'd still need to default this to `On` until all the controller presets have been updated.

Not really sure how to handle this... Any thoughts...?

**Comment by hizzlekizzle** [comment]
No, those are good points, and I hadn't actually looked at your overlay-preset commit before commenting, and it looks like what I had in mind is at least somewhat covered by the aspect ratio attribute you've added.

So, yeah, I say: let's carry on like this for now and if it needs revisiting later, we can revisit it :)

**Comment by jdgleaver** [comment]
Ah, I'm glad you're happy with the status quo :)

Yes, let's leave it as-is, and I can always come back with some tweaks if we get relevant user feedback ;)

**Pull request merged**
