### PR TITLE
More core updater improvements

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This is a follow-up to PR #10716. It makes two additional improvements to the Core Updater menu:

- Installed cores are now highlighted via a `[#]` symbol:

Screenshot_2020-05-28_17-44-47

- Pressing RetroPad `start` on a selected, *installed* entry opens the `Core Information` menu (when using Material UI, swiping left or right triggers the same action). This means we can now view bios info etc. - and more importantly *delete cores* - without jumping through all the hoops of loading a core first and navigating all over the place :)

Note: It would be possible to open the `Core Information` menu for non-installed cores, but this is difficult and requires some substantial refactoring. I may do it if time allows...

### CODE REVIEW

**Comment by WindyWinston** [comment]
Awesome! This means i'll finally be able to delete cores that don't work on Android (like Game & Watch) because if the core didn't load you couldn't delete it. Now you can. Thanks.

**Comment by im4potato** [comment]
@jdgleaver Thank you so much for all the work you do on RetroArch, you are a machine!

Can I ask why `(#)` was chosen instead of something like `Installed`? It just seems somewhat arbitrary. The only reason I can think of for that choice is that it will take up less space on low resolution displays.

**Comment by i30817** [comment]
This is ok for ozone but not so ok for xmb, where the text label is already weirdly overflowing in spite of being full of nothing by the sides. Unless the commit solves it ofc, i haven't test it.

A better idea (imo) would be to have two images for the right side little emoticon, installed and not installed, or a color shift.

**Comment by Sanaki** [comment]
Looks fine on xmb.
Screenshot from 2020-05-28 22-44-17

**Comment by i30817** [comment]
Ah, it doesn't overlap. Yes that's fine.

**Comment by jdgleaver** [comment]
@im4potato 

> Can I ask why (#) was chosen instead of something like Installed? It just seems somewhat arbitrary. The only reason I can think of for that choice is that it will take up less space on low resolution displays.

The reasoning here was as follows:

- I wanted the shortest indicator possible, since a long one would really harm readability in RGUI and XMB (e.g. 'Installed' basically made the menu unusable)

- A single character looked silly, so I opted to wrap it in brackets

- All the core names have suffix text in round brackets, so I opted for square ones (to make the indicator easily distinguishable)

- I chose the `#` character because it's mostly language-agnostic, and it occupies the full line height (so makes for a uniform appearance)

Note that it wouldn't be difficult at all to detect `[#]` within a menu driver and replace it with an icon (like we currently do with on/off switches in XMB and Material UI) - and that in fact is the plan. It's just that it's fiddly and annoying (and we have to make new icons), so it's quite low on the TODO list :P

**Pull request merged**
