### PR TITLE
Graceful switching between videodrivers #2.

### PR DESCRIPTION
**Pull request by Rinnegatamante**
This PR fixes issues on Linux build.

### CODE REVIEW

**Comment by orbea** [comment]
@twinaphex This PR was not ready and its still broken (segfaults).

**Comment by twinaphex** [comment]
What segfaults?

**Comment by twinaphex** [comment]
We discussed before that this intermediary step is necessary in order to push forward.

Please, state exactly what this segfault is, and then let the issue rest. I repeat again, Rome was not built in a day, and we cannot continue this way by having this be a deterrent to further progress.

**Comment by orbea** [comment]
@twinaphex As discussed in the issue it crashes when closing content with at least dolphin libretro, it would help to wait for testing to be done.

**Comment by twinaphex** [comment]
I'm going to lock this conversation down for now until things settle down, this kind of pesturing is helping drive away a very promising new contributor from contributing to the project and we cannot be having that.

**Comment by twinaphex** [comment]
@orbea We've found some issues with this PR on Linux. We're currently working through them.

**Comment by twinaphex** [comment]
@orbea The issues have been fixed now to the best of our knowledge. Let us know if you still encounter issues and we can investigate them.

**Comment by orbea** [comment]
@twinaphex Breaking old cores is a really bad idea.

I tested briefly and dolphin-emu now crashes when starting content and its still impossible to use the desired video driver with dolphin or beetle-psx.

Bluntly said, RetroArch is progressively getting more broken, not fixed.

**Comment by twinaphex** [comment]
Compile Dolphin from source, the one on the buildbot might not have the patch yet.

You should be seeing a log message like this -

'[Environ]: GET_PREFERRED_HW_RENDER.'

**Comment by twinaphex** [comment]
Also @m4xw recommended that you nuke your OpenGL shader cache as well.

**Comment by jdgleaver** [comment]
FWIW, using Linux + Nvidia GFX I have no issues running Dolphin or Beetle PSX, and I can select any video driver for Beetle PSX using a config override. So perhaps this is GFX hardware related? (a hardware driver issue, and not a problem with RetroArch?)

**Comment by orbea** [comment]
@m4xw Good idea, the crashes went away at least for now after deleting the shader cache. Thanks! The black screen also seems fixed.

The remaining immediately noticeable issue is the forced video driver changes.

> Compile Dolphin from source, the one on the buildbot might not have the patch yet.

Again I ask, how are we supposed to bisect old cores? If you want to change the API you should at least bump the API version number from `1` to `1.1`. Personally I would think changing this bad behavior would of been obvious.

> I can select any video driver for Beetle PSX using a config override.

It should respect the video driver set in the video settings when not using any overrides unless the core does not at all support the desired video driver. Is my reasoning flawed?

**Comment by orbea** [comment]
I can also reproduce a crash in beetle-psx when closing content with these steps.

1. Start RetroArch with `vulkan`.
2. Switch to `glcore` without closing RetroArch.
3. Start any game with beetle-psx and then close content via the quick menu.
4. Crash

Log: [ra-psx.log](https://github.com/libretro/RetroArch/files/3740154/ra-psx.log)

If I start RetroArch with the `glcore` driver and then start beetle-psx the quick menu will be invisible, but it does not crash if I blindly close the content.

Log: [ra-psx.2.log](https://github.com/libretro/RetroArch/files/3740165/ra-psx.2.log)

**Comment by Rinnegatamante** [comment]
If you start RetroArch with a driver and then switch without closing RetroArch, the driver change is not taken into account at all. (Infact as it can be seen from logs, beetle started with vulkan). This means that crash is the same as the other one you reported. The second issue you reported is imho not even related to a driver swap. I suspect there's something wrong outside of RetroArch that messes glcore drivers on your system.

**Comment by m4xw** [comment]
@orbea can u pull out gdb for info file, info threads, bt full, info reg, disas (1 page)?
Just for good measure?

**Comment by Rinnegatamante** [comment]
According to gdb, the crash you got has already been fixed. I had same issues and set up an Ubuntu machine just to fix it. Please be sure to be on latest RetroArch commit.

**Comment by orbea** [comment]
The crash looked familiar to me too, but I double checked I was on the latest commit (836fb17d0d473d710fb4ec6d8f8daf633466e093) just now.

**Comment by Rinnegatamante** [comment]
Ok, for some obscure reasons, your menu driver is not being reinited (In your log there's a single log of [INFO] [Menu]: Found menu display driver: "NAMEOFDRIVER" while you should have three of them.) I did double check rn to perform same action you did on win and i indeed have 3 of these logs. This is the cause of your crash (according to log, with glcore context, menu is trying to use vulkan) and of quick menu being black screen. I'll try to look into what's causing this mess.

**Comment by Rinnegatamante** [comment]
Can you send me logs with this diff?
[log.zip](https://github.com/libretro/RetroArch/files/3740509/log.zip)

**Comment by orbea** [comment]
log: [ra-psx.3.log](https://github.com/libretro/RetroArch/files/3740589/ra-psx.3.log)

**Comment by Rinnegatamante** [comment]
Is your system compiling with HAVE_DYNAMIC defined?

**Comment by orbea** [comment]
Yes.
```
$ grep DYNAMIC config.mk 
HAVE_DYNAMIC = 1
DYNAMIC_LIBS = -ldl
```

[config.mk.log](https://github.com/libretro/RetroArch/files/3740749/config.mk.log)

**Comment by Rinnegatamante** [comment]
Logs with this diff?
[log.diff.log](https://github.com/libretro/RetroArch/files/3740803/log.diff.log)

**Comment by orbea** [comment]
[ra-psx.4.log](https://github.com/libretro/RetroArch/files/3741130/ra-psx.4.log)

**Comment by Rinnegatamante** [comment]
[driver.diff.log](https://github.com/libretro/RetroArch/files/3744859/driver.diff.log)

Does this diff solve the issue? (If not, can you provide logs please?)

**Comment by orbea** [comment]
Yes, that does seem to solve it, it seems I can no longer reproduce invisible menus, black screens or crashes when switching between glcore and vulkan with dolphin and beetle-psx. Thanks!

My only remaining issue is that there really should be a way to get a gl context with beetle-psx or a vulkan context with dolphin, both used to work.

**Comment by Rinnegatamante** [comment]
You have to update cores for this one.

**Comment by orbea** [comment]
Like I said earlier, how are we supposed to debug core regressions? It will be impossible to bisect these cores unless using an old RetroArch.

**Comment by twinaphex** [comment]
@orbea There's a new setting in RetroArch -
image

If you turn it off, you get the old behavior back - it will ignore the preferred hw context flag then, and it wont' do driver switching.

**Comment by Rinnegatamante** [comment]
To be more precise, it won't do force drive switch. Overrides are still working even with that setting turned off.

**Pull request merged**
