### PR TITLE
(RGUI) Add dynamic theme

### PR DESCRIPTION
**Pull request by MrHuu**
This adds support for dynamically loading themes with ```RGUI``` based on the menu title from a playlist.

- When ```Dynamic``` is chosen as a theme, a default theme will be loaded. It will look for ```default.cfg```.
- When a playlist is selected, it will load the theme ```*playlist_title.cfg```.
  With ```*playlist_title``` replaced as the actual title of-course.

Themes will be looked for in the ```dynamic wallpapers``` directory.

rgui theme with background png example, at-least.. i tried..:
Default_16_10
Handheld Electronic Game_16_10
Atari - 5200_16_10
atari-lynx-screenshot

### CODE REVIEW

**Comment by jdgleaver** [comment]
Thank you, this is a nice feature!

There are, however, a few issues:

1. Your string 'comparisons' in `rgui_frame()` are wrong. Comparing pointers like that does not work :)
2. The paths you are generating are not platform independent
3. Updating the dynamic theme path in `rgui_frame()` is suboptimal - this only needs to be done when the menu list changes
4. Loading a custom theme incurs significant performance overheads. We should really be caching the results - at least the default and current playlist theme data + processed wallpaper image - so they can be quickly `memcpy()`'d rather than hitting the file system every time

1, 2, and 3 are easy to deal with. I will prepare a little patch that you can apply to your PR in order to address these things (after which we should be able to merge).

4 is far more difficult, due to the asynchronous loading of image data. This requires some thought - I think it is most likely something that would have to be addressed in a separate PR at a later date...

**Comment by MrHuu** [comment]
Thank you! @jdgleaver 

You're being very helpful not only pointing out and addressing my rookie mistakes, but also giving a clear example which from an educational standpoint is very valuable to me.

I've been able to apply you patch, and it builds and runs without issues on my end (3DS platform).

**Comment by jdgleaver** [comment]
@MrHuu I'm happy I could help! This dynamic theme feature is inspired, and adds a great deal of 'life' to the menu - I am very glad that you made this PR :)

@twinaphex This is ready for merging - just in time for the next release ;)

**Comment by MrHuu** [comment]
Here's an improved version of the theme shown before,
it has a semi-transparent background and supports both 4:3 and 16:10 aspect ratios.

This should give a good example on how to use this feature.

 - Extract these files to the ```retroarch/assets/wallpapers``` directory (default)
 - Or, set your ```dynamic wallpaper``` directory to the directory containing these files

Default
Sega - Game Gear_16_10

[libretro_dynamic_theme.zip](https://github.com/libretro/RetroArch/files/8053908/libretro_dynamic_theme.zip)

**Pull request merged**
