### PR TITLE
(RGUI) Add 'particle effect' animation system

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

Inspired by #8626, this PR expands upon the existing snow animation by introducing the concept of RGUI particle effects. Basically, you get 256 'particles' to play with, each consisting of 4 float variables with which you can do as you please. This is very crude and simplistic, but it's also quite flexible and adding new effects is a fairly trivial exercise.

From a user's perspective, the current `Snow` option has been removed and replaced with a new `Background Animation` setting under `User Interface > Appearance`. This can be disabled, or set to one of the following:

(I'm arbitrarily using the `Hack the Kernel` theme here, since the black background makes animations 'pop'. Also, these gifs are a little jerky for some reason - the actual animations are smooth)

- `Snow (Light)`: This is the existing snow effect

window_record__2019_04_29__15_47_07

- `Snow (Heavy)`: Same as above, but with variable (larger) snow flakes

window_record__2019_04_29__15_47_47

- `Rain`:

window_record__2019_04_29__15_48_26

- `Vortex`:

window_record__2019_04_29__15_49_01

- `Star Field`:

window_record__2019_04_29__15_49_45

(I'll probably add some more once I've caught up with my TODO list...)

**NOTE 1:**

The particle colour is now set per-theme. This means that custom theme preset files have yet another new (optional) entry:

```
rgui_particle_color = "0xAARRGGBB"
```

**NOTE 2:**

All animations are frame rate dependent. When frame rate drops below 60, this is by design - slow animations are better than jerky animations. I don't know if higher frame rates will ever be a problem (i.e. who wants to run RGUI at 144Hz anyway...?), but if there is sufficient demand I'll implement some kind of speed cap.

**NOTE 3:**

These animations of course have a performance impact. They make RGUI update on every frame (just like ticker text), and they increase the performance overheads of `rgui_render()` by the following amounts:

- `Snow (Light)`: +52%

- `Snow (Heavy)`: +55%

- `Rain`: +38%

- `Vortex`: +78%

- `Star Field`: +39%

(But much of this can be mitigated by disabling borders)

Note, however, that in practical terms the real-world performance impact is completely negligible on anything other than garbage-tier hardware. Also, I think I've spotted a way to shave another 15-20% off `rgui_render()` anyway - I'll come back to this when I have time...

## Related Pull Requests

#8626

### CODE REVIEW

**Comment by twinaphex** [comment]
I definitely run RetroArch at 120Hz these days so framerate independent animation would be awesome.

**Comment by jdgleaver** [comment]
@twinaphex Okay, no worries - I've got some other stuff to do first, then I'll look at disentangling this from frame rate.

**Comment by twinaphex** [comment]
Well yeah - one thing though

> All animations are frame rate dependent. When frame rate drops below 60, this is by design - slow animations are better than jerky animations. I don't know if higher frame rates will ever be a problem (i.e. who wants to run RGUI at 144Hz anyway...?), but if there is sufficient demand I'll implement some kind of speed cap.

I believe the intent here is good for framerates below 60fps - in that case it would be preferable to have slower animations instead of jerky ones. However, 60fps and above we do want the animations to be as smooth as they possibly can be.

So hopefully my explanation makes sense to you that way.

**Comment by jdgleaver** [comment]
Don't worry - that's exactly how I was planning to do it :slightly_smiling_face:

**Pull request merged**
