### PR TITLE
Additional revision of the Spanish translation

### PR DESCRIPTION
**Pull request by IlDucci**
- Decided that all instances of "Refresh rate" will be translated as "frecuencia de actualización", not "tasa de refresco". Used Windows' official translation as a reference.
 - Minor typo corrections and tweaks.
 - Unified certain phrasings in the Settings sublabels.

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by IlDucci** [comment]
Bump for the owners. It seems the latest pull requests were ignored because the checks stayed in an infinite loop. How can I fix that, if I'm the one I should fix this?

**Comment by twinaphex** [comment]
Hi, is this PR ready?

**Comment by IlDucci** [comment]
It was a long time ago, but I don't know why the checks got stuck. Now that you've responded, I've translated the latest changes in the US files.

**Comment by IlDucci** [comment]
@twinaphex I'm sorry to ping you, but I do not know what's wrong with this Pull Request that's got stuck all this time. The translation is updated to the Update Installed Cores point and ready to deploy.

**Comment by twinaphex** [comment]
My bad. Let's update it.

**Pull request merged**
