### PR TITLE
Add Daite XMB Icon Theme

### PR DESCRIPTION
**Pull request by TheRhysWyrill**
## Description

Adds a new XMB Icon Theme known as Daite, here are some screenshots of the various icons.

Main Menu:
2022-07-31 17_34_56-image png @ 100% (RGB_8) _

Quick Menu
2022-07-31 17_37_42-RetroArch pcsx2 (alpha) 02a24a18

Input Remapping:
2022-07-31 17_38_08-RetroArch pcsx2 (alpha) 02a24a18

Settings [1/2]:
2022-07-31 17_35_28-RetroArch

Settings [2/2]:
2022-07-31 17_35_40-RetroArch

Various Playlists:
2022-07-31 17_36_26-RetroArch

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Thanks for creating this.

**Comment by gouchi** [comment]
Related [PR](https://github.com/libretro/retroarch-assets/pull/438) for retroarch-assets repository.

**Comment by LibretroAdmin** [comment]
Umm, we need to change some things. These icons are now being used for Ozone too, which in some cases breaks the visual style of Ozone. So we have to start splitting these two up. We cannot have a case where XMB icons start creating visual clashes for Ozone too.

**Comment by LibretroAdmin** [comment]
retroarch-ozone

Here is what I mean -

all the colored icons are wrong and shouldn't be used by Ozone. The gear icon on the left shouldn't be there. 

I'll probably change it myself anyway, at least that way I can ensure nothing will go wrong again.

**Comment by LibretroAdmin** [comment]
OK, so the sidebar icons you changed are to blame for this. I'm going to change that back. I don't like this current look and it breaks Ozone's visual consistency hard.

**Pull request merged**
