### PR TITLE
(Android/Play Store) Add frontend support for core installation via Play Feature Delivery

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR implements the C code + menu/frontend additions required to make use of the Play Store 'Play Feature Delivery' support added in #11213 

With these changes, the Play Store builds of RetroArch for Android no longer use the buildbot to install cores - instead, cores are installed as modules directly from Google's servers. All other builds (including 'normal' Android builds) are entirely unaffected.

As a result, the Play Store builds are subject to the following limitations:

1) Only 50 cores can be served (we haven't decided on a list yet!) - although sideloading cores should still work correctly.

2) Automatic core backups are disabled

3) The 'Update Installed Cores' menu entry is removed/disabled

The rationale for (2) and (3) is that, when using 'Play Feature Delivery', Google decides when cores get updated - we no longer have in-app control. Once a core is installed, it will be updated automatically when the app itself is updated (so menu-based updating is irrelevant). Note that this also means core updates will *only* be available for the Play Store builds when a new stable version of RetroArch is released.

I should also make it very clear that this code is untested. I've checked that the core update list is retrieved successfully via the JNI interface, but the actual downloading part requires a bunch of external setup...

## Reviewers

@farmerbb This should all be functionally complete and ready to go - but I have no idea about the testing requirements. Any help will be very much appreciated :)

### CODE REVIEW

**Comment by farmerbb** [comment]
Ok, I did some extensive testing of this PR using a private Play Store listing.  The C side of things seems to work almost perfectly!  The Java/Gradle side did have a couple of minor things that I needed to address (I've opened a separate PR with those fixes)

One thing I noticed is that the `[#]` indicator doesn't seem to stick around after leaving the Core Updater and re-entering it.  The indicator successfully shows right after installing a core, it just doesn't appear on cores that were already installed via Play Feature Delivery.

Other than that, downloading cores seems to work great!

**Comment by twinaphex** [comment]
I have merged your PR @farmerbb . Let me know if this can be merged as well. We could then move onto the next phase (we'll probably have to discuss this when all three of us are together on Friday).

**Comment by farmerbb** [comment]
I think this is good to merge.

**Comment by jdgleaver** [comment]
@farmerbb Thank you so much for testing this, and for the Java/Gradle fixes. We have so few devs with Android experience - your expertise is an absolute godsend!

I'm very pleased to hear that the PR is (mostly) functional - writing code that I can't run myself is always somewhat nerve-racking :)

> One thing I noticed is that the [#] indicator doesn't seem to stick around after leaving the Core Updater and re-entering it. The indicator successfully shows right after installing a core, it just doesn't appear on cores that were already installed via Play Feature Delivery.

That's a very peculiar bug!

In order to generate those markers for a menu entry, it does two things:

1) Fetches the current core updater list and searches for the core updater file name associated with the menu entry (It does this in order to obtain the full file path, from which it then obtains the core file name. I know this may seem like a circular waste of effort, but this is generic code - it also handles buidbot downloads, where the 'downloaded' file name *does not* match the local one, so we need a lookup)

2) Searches the `core_info` object for an entry corresponding to the file name. This object, when initialised, scans the cores directory and creates an entry for each shared object file that it finds (parsing any available data from matching core info files). So this means that if a particular core is found in the `core_info` object, the core shared object file exists - and so it is 'installed' (and gets a `[#]` marker). If it's not found, then core isn't installed, and gets no marker...

When you perform an install, your code regenerates the core symlinks, the `core_info` object gets refreshed (and finds the new core), the current core updater list is unchanged, and you see a `[#]` marker - all is well.

When you back up and immediately re-enter the core downloader menu, the `core_info` object is unchanged, the core updater list gets refreshed - but now the `[#]` marker isn't displayed? This is very strange! We know the `core_info` object is correct, and although we've regenerated the core updater list, its contents should be identical every time (when parsing buildbot cores, we're dependent upon a remote file listing, which can change - but the play feature delivery list is hardcoded/constant)

So I don't know how to explain this...

Could you confirm that I've described the error correctly? i.e. That the marker shows on successful installation, but then disappears when leaving then immediately returning to the core downloader menu? If so, could you also test the transition in the opposite direction? What I mean is:

- Get the `[#]` marker to show, then swipe the marked entry left or right (I assume you're using glui?) to enter the core info menu

- Backup to the previous menu and check whether the marker is still there

When going forwards then backwards like this, neither the `core_info` object nor the core updater list is modified - so the menu should be identical.

If I've misunderstood the issue, is it actually the case that the marker doesn't show up when restarting RetroArch? i.e. If you open RetroArch and go straight to the core downloader menu (without installing anything), are there any markers on cores that you know are installed? And if not, could you go to `Settings > Core > Manage Cores` and check that the installed cores show up there?

If the `Manage Cores` menu is empty after a fresh launch of RetroArch, then we have an entirely different problem :)

This would mean that the `core_info` object isn't finding any cores at all on launch. But we know that `updateSymlinks()` works, because this gets triggered after the core install, and at that point the `core_info` object is correctly populated. Perhaps on launch, the symlinks aren't getting updated properly? Or maybe it's happening after the `core_info` object is first initialised...?

I'm not sure how best to debug this, but if we can check all the things I mentioned, that should at least narrow things down a bit... (and I apologise for making so many requests!)

**Comment by farmerbb** [comment]
> Could you confirm that I've described the error correctly? i.e. That the marker shows on successful installation, but then disappears when leaving then immediately returning to the core downloader menu? If so, could you also test the transition in the opposite direction? What I mean is:
>
> * Get the `[#]` marker to show, then swipe the marked entry left or right (I assume you're using glui?) to enter the core info menu
>
> * Backup to the previous menu and check whether the marker is still there

Yes, you've described the error correctly. After following those steps, the `[#]` marker still shows, which is good.

>If I've misunderstood the issue, is it actually the case that the marker doesn't show up when restarting RetroArch? i.e. If you open RetroArch and go straight to the core downloader menu (without installing anything), are there any markers on cores that you know are installed? And if not, could you go to `Settings > Core > Manage Cores` and check that the installed cores show up there?

The installed cores do show up under Manage Cores.  It's just the markers that don't show up, either after a RetroArch restart or after simply backing up from the Core Downloader and re-entering it.

------------------------------

I also tried out your suggestion of performing a symlink update inside `core_info_init_list()` - assuming I set up the C code correctly, that didn't end up working either.

What _does_ seem to work is simply copying the download cores to the `cores` directory instead of symlinking them.  The `[#]` indicators show up correctly inside the Core Downloader.  However, there are drawbacks to taking this approach - RetroArch will use twice the disk space since the cores are duplicated on disk, and there will be extra time taken up by the copy operation which will be especially apparent for larger cores such as MAME.

What's interesting is that if I install the standard version of 1.9.0, download some cores, open up a root shell, move the cores outside of the `cores` directory then symlink them back in, the Core Downloader will correctly show the `[#]` indicators.  So I'm not sure if it's an issue with RetroArch trying to handle symlinks vs actual files, or if it's an issue with the implementation in this PR.

**Comment by jdgleaver** [comment]
Okay, so I *think* the problem here is that play feature delivery core files use a non-standard naming scheme (i.e. they're not called `<core_name>_libretro_android.so`). We almost always resolve the real path when dealing with core files - so when this happens with a play store delivery core, we end up with the wonky source file name (which none of the RA code recognises). This would affect the core updater list, and also every playlist operation.

This diff modifies the 'realpath' function usage such that core symlinks are ignored when using the play store builds: [play_store_installed_fix.patch.zip](https://github.com/libretro/RetroArch/files/5146850/play_store_installed_fix.patch.zip)

Could you please apply this to current master, and check whether it fixes the core updater list issue? And could you then try loading content with play feature delivery cores, and make sure the content history playlist has sane core path entries?

Many thanks in advance for your continued debugging efforts!

**Comment by farmerbb** [comment]
>Could you please apply this to current master, and check whether it fixes the core updater list issue? And could you then try loading content with play feature delivery cores, and make sure the content history playlist has sane core path entries?

Tested the patch, and it works great!  The core updater list issue is now resolved, and the content history playlist works fine as well, using the correct core path.

**Comment by jdgleaver** [comment]
Excellent - that's great to hear!

I'll clean up the patch and PR it forthwith :)

**Pull request merged**
