### PR TITLE
Update to dynamic width

### PR DESCRIPTION
**Pull request by alphanu1**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by orbea** [comment]
Can you please squash these commits?

**Comment by alphanu1** [comment]
@orbea Will do. Just adding some more changes first

**Comment by orbea** [comment]
Thanks, I appreciate it!

**Comment by alphanu1** [comment]
@twinaphex @orbea commits have been squashed

**Comment by orbea** [comment]
Thanks, but now there is a mingw build error revealed by travis.
```
gfx/display_servers/dispserv_win32.c: In function ‘win32_display_server_destroy’:
gfx/display_servers/dispserv_win32.c:119:13: error: too few arguments to function ‘video_display_server_set_resolution’
             win32_orig_refresh, (float)win32_orig_refresh, crt_center, 0);
             ^
In file included from gfx/display_servers/dispserv_win32.c:34:0:
gfx/display_servers/../video_display_server.h:61:6: note: declared here
 bool video_display_server_set_resolution(
      ^
make: *** [obj-unix/release/gfx/display_servers/dispserv_win32.o] Error 1
The command "make" exited with 2.
```

**Comment by alphanu1** [comment]
@orbea this should be resolved now.

**Comment by alphanu1** [comment]
sorry I will squash these again

**Comment by twinaphex** [comment]
Merge conflicts.

**Comment by orbea** [comment]
@alphanu1 There are some new warnings with gcc8, maybe can you take a look at them? :)
```
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_set_resolution’:
gfx/display_servers/dispserv_x11.c:156:45: warning: ‘%d’ directive output may be truncated writing between 1 and 11 bytes into a region of size 7 [-Wformat-truncation=]
    snprintf(crt_name, sizeof(crt_name), "CRT%d", crt_name_id);
                                             ^~
gfx/display_servers/dispserv_x11.c:156:41: note: directive argument in the range [-2147483647, 2147483647]
    snprintf(crt_name, sizeof(crt_name), "CRT%d", crt_name_id);
                                         ^~~~~~~
gfx/display_servers/dispserv_x11.c:156:4: note: ‘snprintf’ output between 5 and 15 bytes into a destination of size 10
    snprintf(crt_name, sizeof(crt_name), "CRT%d", crt_name_id);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by alphanu1** [comment]
@orbea no worries I'll look into it.

**Comment by orbea** [comment]
Thank you!

**Pull request merged**
