### PR TITLE
Overhaul default playlist core association

### PR DESCRIPTION
**Pull request by jdgleaver**
## ## Description

As mentioned in PR #8961, the current method for handling playlist core associations is fundamentally flawed. Playlist name/core path pairs are stored as delimited strings in the settings char arrays `playlist_names` and `playlist_cores` - for users with large collections, it is very easy to overflow these arrays, at which point the whole system breaks. It is also virtually impossible to edit the `playlist_names` and `playlist_cores` config values by hand, since there is no way to determine which name corresponds to which core without manually counting delimiters. It is a very ugly setup.

This PR changes the whole thing:

- Default core path/name are now stored inside playlist files, via two new top level metadata entries: `default_core_path` and `default_core_name`(playlist version number has been bumped to 1.1, accordingly) - e.g.:

```
{
  "version": "1.1",
  "default_core_path": "/WORK/WORKB/play/RetroArchSys/cores/mgba_libretro.so",
  "default_core_name": "Nintendo - Game Boy Advance (mGBA)",
  "items": [
    {
      "path": "/WORK/WORKB/play/ROMs/GameboyAdvance/007 - Everything or Nothing (USA, Europe) (En,Fr,De).gba",
      "label": "007 - Everything or Nothing (USA, Europe) (En,Fr,De)",
      "core_path": "/WORK/WORKB/play/RetroArchSys/cores/mgba_libretro.so",
      "core_name": "Nintendo - Game Boy Advance (mGBA)",
      "crc32": "0|crc",
      "db_name": "Nintendo - Game Boy Advance.lpl"
    },
```
- Default core assignment is now handled via a new `Playlist Management` menu under `Settings > Playlists`:

Screenshot_2019-06-26_17-36-05

...when selected, this presents the user with a list of existing playlists:

Screenshot_2019-06-26_17-36-23

...and selecting one of these opens a new utility menu:

Screenshot_2019-06-26_17-36-34

**Note**: This has only one entry at present: `Default Core` - I will add options to reset all core associations and remove invalid entries in my next PR(s)

This `Default Core` setting is similar to the old playlist core assignment entries: you can press left/right to select a core - but now, you can also press select to get a proper drop down list of all installed cores:

Screenshot_2019-06-26_17-37-10

This is a much cleaner/saner arrangement, and the new  `Playlist Management` category will allow for a range of additional functionality to be added in the future.

The one downside is that users will have to re-associate default cores for their existing playlists - but that's a small one-off penalty...  ;)

## Reviewers

I would appreciate it if someone could review the Qt interface changes. I have verified that everything works, but Qt (and this part of the code in general) is unfamiliar to me...

### CODE REVIEW

**Comment by bparker06** [comment]
My biggest concern is that this seems incompatible with the old playlist format which we still have to support.

And forcing end-users to make changes to their existing playlists (even with the new format) is not something @twinaphex would agree with IMO.

**Comment by i30817** [comment]
Considering the scanner in general is a disaster area of bugs i wouldn't be too worried about supporting the old playlist format. After all everyone that wants to support a MAME playlist is probably not using it because the scan crashes retroarch.

**Comment by jdgleaver** [comment]
Just pushed a commit that enables support for the old playlist format - i.e.:

- New 'old format' playlists will contain default core metadata

- New 'old format' playlists can still be loaded with old versions of RetroArch without issues (although, of course, this will fallback to the old `playlist_names`/`playlist_cores` method of setting associations)

**Comment by Tatsuya79** [comment]
So it's fine here on windows 7 x64, couldn't find bugs and works from QT too.

Jdgleaver has an issue when clicking in QT on an entry in a playlist, every time the playlist reloads itself.
It's not happening for me.
If more people can check that (on Linux was it?).

**Comment by escalade** [comment]
> My biggest concern is that this seems incompatible with the old playlist format which we still have to support.
> 
> And forcing end-users to make changes to their existing playlists (even with the new format) is not something @twinaphex would agree with IMO.

The current core assignment really sucks though, anything is better. Perhaps the old method could be preserved with a setting if that's a concern?

**Comment by jdgleaver** [comment]
@Tatsuya79 Thanks for testing :heart: 

To clarify on the playlist reloading issue: the Qt interface is currently setup so the default core association is fetched each time an entry is selected (this has always been the case). It's incorrect behaviour, because we only need to do this when the playlist is first loaded (to populate the list view) - but regardless, whereas fetching the default core originally involved parsing the `playlist_names` and `playlist_cores` strings (itself a horribly inefficient procedure!), we now read the playlist file - so each time we select an item, the file is opened, read and closed again. (note: it doesn't refresh the list view - it literally just reads the file contents)

Now on platforms that support the Qt interface, this is really a non-issue: the playlist file is cached to RAM (by the OS), and the playlist parsing is so fast that the user cannot notice it (I mean, there are greater overheads in loading a playlist entry thumbnail, for example). So I don't think it blocks this PR in any way. Moreover, I can probably edit the Qt interface to 'do the right thing' and only cache the default core assignment when needed (but I need to brush up on my C++/Qt, and I also want to add the other playlist management options first).

>>    My biggest concern is that this seems incompatible with the old playlist format which we still have to support.
>>
>>    And forcing end-users to make changes to their existing playlists (even with the new format) is not something @twinaphex would agree with IMO.
>
> The current core assignment really sucks though, anything is better. Perhaps the old method could be preserved with a setting if that's a concern?

The commit I pushed adds full support for old format playlists, so that part's not an issue any more  :)

As for maintaining the old method (`playlist_names`/`playlist_cores`)... That's a really bad idea IMHO. Most people don't realise how broken the current system is - if those strings overflow, then we're done for.

I was testing this again on the Wii last week, and assigning cores to too many playlists left RetroArch in an unrecoverable state - I had to delete my config. That's not something that users should ever be exposed to, and that's why I made this PR in the first place! These changes require the user to update their core associations once - but after that, everything is properly maintainable/reliable/future proof.

**Pull request merged**
