### PR TITLE
Silence LGTM 'Use of potentially dangerous function' alert.

### PR DESCRIPTION
**Pull request by orbea**
## Description

Attempts to silence a LGTM alert.

## Related Issues

> Call to localtime is potentially dangerous

https://lgtm.com/rules/2154840805/

## Reviewers

@jdgleaver Mind taking a look at this when you have a chance to make sure I'm not doing something stupid or otherwise wrong? It seems to work here...

### CODE REVIEW

**Comment by jdgleaver** [comment]
@orbea Looks fine, but you probably want to call `tzset()` before invoking `localtime_r()` (for reference: https://stackoverflow.com/questions/19170721/real-time-awareness-of-timezone-change-in-localtime-vs-localtime-r)

I'm afraid I can't compile this to test at the moment, however, since I'm away on holiday for a week, and barely have internet access let alone a dev machine!

**Comment by orbea** [comment]
Thanks for the tip! From the posix spec from `tzset`.

> Since the ctime(), localtime(), mktime(), strftime(), and strftime_l() functions are required to set timezone information as if by calling tzset(), there is no need for an explicit tzset() call before using these functions. However, portable applications should call tzset() explicitly before using ctime_r() or localtime_r() because setting timezone information is optional for those function

https://pubs.opengroup.org/onlinepubs/9699919799/functions/tzset.html

I'll update the PR in a bit, I have no problem waiting until you have time to continue with this PR or you could test it more thoroughly when you are back?

**Comment by bparker06** [comment]
This pull request **fixes 1 alert** when merging 86d336bd10e9b3e84e9c4754717dae0b36e3f488 into 3f1a516696680a0cedb58451830a56e4c57b6255 - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-fe502da895f4ba7a3475bf51b2169fd60cbf0897)

**fixed alerts:**

* 1 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bparker06** [comment]
This pull request **fixes 1 alert** when merging efb8f767c9b56e54c0eddb69fb914d6e2ad62f2a into 3f1a516696680a0cedb58451830a56e4c57b6255 - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-261d53a340f480a06df4abbab7583b909c550926)

**fixed alerts:**

* 1 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by orbea** [comment]
I dont know why travis never triggered, but if it did it would show this doesn't work for windows...
```
LD retroarch
obj-unix/release/runtime_file.o:runtime_file.c:(.text+0xed1): undefined reference to `localtime_r'
collect2: error: ld returned 1 exit status
make: *** [retroarch] Error 1
```

**Comment by orbea** [comment]
I'm going to close this while I consider the windows issue...

**Pull request closed without merging**
