### PR TITLE
(ozone) Added simple playlist entry enumeration

### PR DESCRIPTION
**Pull request by DisasterMo**
## Description

Now the meta data for each playlist entry displays two numbers in addition to the core association, runtime and last played date: the index of the selected entry and the total number of entries in the playlist.

entry enumeration reduced

This works in ozone only, for now. Whether this feature is sensible/desirable for other menu drivers is up for debate.

Honestly, I am not sure whether I've added/modified all the code I need to here, so please feel free to try it out and educate me on anything I've missed.

### CODE REVIEW

**Comment by Ryunam** [comment]
This is actually an interesting addition! I have just a few comments:

1) Perhaps it coiuld be useful to make the string just a bit more verbose and self-explanatory. Something like "Entry n. 15 / 91" to make it clearer that the number refers to the enumeration of the playlist entries and not something else.

2) I would personally appreciate a toggle to allow the visibility of this string based on one's preference.

**Comment by DisasterMo** [comment]
Thank you for your feedback!

1. Is easy enough. I'll add a translatable string shortly.
2. I have no idea how to do. I'm not saying I can't or won't, just that it's going to take some time & I'd like to hear more opinions first.

**Comment by hizzlekizzle** [comment]
I think this is a good addition, and it's something I've seen requested a number of times. Unless there's a technical reason not to add it, I'd say :+1:

**Comment by DisasterMo** [comment]
Thank you, @hizzlekizzle!

Do you have any thoughts on the toggle idea from above?
Or maybe on how to implement this for other menu drivers? I was thinking, XMB could work the same as ozone, just add it to the meta data, and for rgui the enumeration should be "static" (like the clock) and not scroll. As for GLUI, well... I don't know

**Comment by jdgleaver** [comment]
@DisasterMo This is very nice!

I agree with Ryunam that there should be a visibility toggle option, and that this should be added before merging. I would be happy to do this for you (I can give you a diff to apply on top of this PR). Unfortunately I don't have time to work on this over the weekend, but I can get it done early next week.

I think it would indeed be good to add this feature to the other menu drivers, in follow-up PRs. If you don't mind, I would like to handle RGUI and GLUI myself. This is just because I know these drivers inside and out, and so it would be easier for me to deal with the tricky stuff, rather than expecting a new contributor to wade through a huge amount of unfamiliar code :)

RGUI is a little bothersome, due to the extremely limited screen space; GLUI is somewhat laborious, since the different playlist view modes need different approaches (with variations depending upon other display options). I will need to think about this for a while...

For XMB, I think the index number could either go in the metadata, or be added as footer text in the bottom right corner. I... don't really like working with XMB... so anything you want to add there is welcome, and fine with me ;)

**Comment by DisasterMo** [comment]
Very well, I'll leave the toggle option to you, @jdgleaver. Thank you!
It will serve as a great example for future reference as well! I'll start working on the XMB implementation in the meantime. I really like the footer text idea.

**Comment by jdgleaver** [comment]
@DisasterMo Okay - I've prepared a patch file with a new `Settings > Playlists > Show Playlist Entry Index` option for controlling the visibility of the enumeration text: [entry_index.patch.zip](https://github.com/libretro/RetroArch/files/6495039/entry_index.patch.zip)

I also made a few other tiny changes:

- The entry text is now `"Entry: %lu/%lu"`, to match the other metadata lines (i.e. these all have the format `<tag>:<value>`)
- I replaced your `INFO_ENTRY_NUM` references with `INFO_ENTRY_IDX` (just personal preference, but it seemed to fit better!)
- Using the `snprintf()` formatting string `%lu` with a variable of type `size_t` is not portable, and will segfault on some platforms. So I explicitly cast those `size_t`s to `unsigned long`s

If you could please apply the patch to your PR, then rebase and squash your commits, we should be ready to merge this :)

**Comment by DisasterMo** [comment]
Thank you very much, @jdgleaver! It's perfect!

**Pull request merged**
