### PR TITLE
qb: Improve the CDROM check.

### PR DESCRIPTION
**Pull request by orbea**
## Description

The first commit extends the `check_platform` function to be able to check for more than one OS per feature and also adds a `match` helper function in `qb/qb.init.sh`. This will have no change in behavior on its own, but this will allow to improve the CDROM check in the second commit to correctly respect configure arguments. I also added a missing configure check for headers which are required on Linux and this prevents build failures on some distros where these headers are not available. @bparker06 may want to find more portable headers in a followup commit.

Currently the CDROM code will be enabled automatically for `Linux` and `Win32` while other platforms will require `--enable-cdrom`. It can be enabled automatically for other platforms if the platform string is added to the `check_platform` `CDROM` check in `qb/config.libs.sh` or it can be enabled everywhere by removing that check and changing `HAVE_CDROM=auto` in `qb/config.params.sh` to `yes`.

If specific platforms should disable `CDROM` support or if it should only be enabled for certain platforms with `--enable-cdrom` resulting in an error on other platforms this can be easily changed, please let me know?

## Related Issues

Fixes https://github.com/libretro/RetroArch/issues/9096.

### CODE REVIEW

**Comment by bparker06** [comment]
Unfortunately those headers are absolutely required for sending ATAPI commands, whether it's RA or a CD burning program or what have you... I don't think there is any alternative. What distros don't this available? Or is it just a case of requiring a specific package? (like kernel headers or something)

**Comment by orbea** [comment]
It appears that RHEL/Fedora do not have these headers. Please see these two issues.

https://github.com/libretro/RetroArch/issues/9096
https://bugzilla.redhat.com/show_bug.cgi?id=656245

If RetroArch absolutely needs those headers then I am not sure what else can be done short of fixing RHEL/Fedora besides adding a configure check as already done in this PR.

**Comment by bparker06** [comment]
That sounds very strange... I wonder how programs on those distros use `ioctl()` then? My manpage for it says that POSIX.1 2008 defines stropts.h, which includes ioctl.

**Comment by orbea** [comment]
Slackware does not have this problem so I can't say, regardless I don't think there is anything more to do in this PR and I tested it as thoroughly as I could.

**Comment by s3gfaultx** [comment]
> Unfortunately those headers are absolutely required for sending ATAPI commands, whether it's RA or a CD burning program or what have you... I don't think there is any alternative. What distros don't this available? Or is it just a case of requiring a specific package? (like kernel headers or something)

Can you include "sys/ioctl.h" header and drop stropts.h as it's not available in Fedora / RHEL?

**Comment by bparker06** [comment]
@s3gfaultx According to https://www.gnu.org/software/gnulib/manual/html_node/sys_002fioctl_002eh.html that header does not define ioctl on some platforms, but I suppose if we ever do support those platforms with the cdrom code, we could always include a different header for those. If the only difference on Linux with using sys/ioctl.h is that additional distros are supported, that's fine with me.

**Comment by orbea** [comment]
Do alternative libc implementations have that header or would that only work with glibc?

Regardless changing the header outside the scope of this PR.

@twinaphex This is ready.

**Comment by orbea** [comment]
@bparker06 Relevant link.

https://stackoverflow.com/questions/7294732/replacement-for-the-ioctl-function

This quote in particular might be helpful.

> I would urge you to put all the details on YOUR ioctls in the .h file for the device as a way to be sure it is always available to developers.

**Pull request merged**
