### PR TITLE
Fix Crowdin Daily Action

### PR DESCRIPTION
**Pull request by guoyunhe**
Python module installation

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

The previous CI config has mistake in package name

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by IlDucci** [comment]
Systems are working perfectly this time around. Both GitHub->Crowdin, as well as Crowdin->GitHub directions have worked today.

Great job!

**Comment by guoyunhe** [comment]
Good! This week I will look into core translation on Crowdin.

**Comment by DisasterMo** [comment]
@guoyunhe Well, you can, of course. But I'm pretty much done with the scripts & GitHub actions at this point.
Only thing missing is to figure out how to do a singular initial upload of translations and how to have the files of each core in a separate folder on Crowdin.

**Comment by guoyunhe** [comment]
@DisasterMo To upload translation in a separate folder, you need to add `dest` property in crowdin.yaml See https://support.crowdin.com/configuration-file/#uploading-files-to-specified-path-with-specified-type

You will need manager permission of the project to upload initial translations, either through the cli or on the website. I have added you as a manager. Now you should be able to upload sources or translations.

**Comment by DisasterMo** [comment]
Thank you so much, @guoyunhe! This is going to make working on this and future Crowdin related projects a billion times easier!

**Pull request merged**
