### PR TITLE
Graceful fallback to readonly mode if RDB can't be opened readwrite

### LINKED ISSUE #15566: (UWP) Databases don't work anymore
## Description

Before, when you wanted to look at a console's database (AKA RDB file), you would be greeted by a bunch of entries, but ever since PR #15527 was merged, no entries are displayed now in the UWP ports on Xbox. @JoeOsborn Your help would be appreciated here.

### Expected behavior

See the contents of the RDB file.

### Actual behavior

Nothing shows up.

### Steps to reproduce the bug

1. Go to Main Menu > Database Manager
2. Open a RDB file
3. Be greeted by nothingness.

### Bisect Results

PR #15527 is the culprit.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0/09e4719

### Environment information

- OS: Xbox Series X OS
- Compiler: MSVC (1937) 64-bit

### PR DESCRIPTION
**Pull request by JoeOsborn**
My guess is that this will fix #15566 , but I can't test on UWP.

This PR also replaces some stray tabs with spaces.

### CODE REVIEW

**Comment by GABO1423** [comment]
I should be able to test this later today, I'll let you know what results I can find.

**Comment by GABO1423** [comment]
This sadly did not fix the issue @JoeOsborn

**Comment by JoeOsborn** [comment]
Interesting. The only code path I changed connected with just listing database entries was in opening the DB with different flags—the rest of the changes concerned find_entry, find_index, and create_index.  Are those used in RA’s database listing code?

**Comment by JoeOsborn** [comment]
Sorry for the CI noise, I’m trying to fix this from my phone!

**Comment by GABO1423** [comment]
I got the strength to get to the computer, I'll get to testing this now

**Comment by GABO1423** [comment]
Good news, these new commits did the trick!

Unknown-2023_08_09-23_13_31
Unknown-2023_08_09-23_13_53

**Comment by JoeOsborn** [comment]
I’m glad it works. I still don’t know why the fallback to opening readonly didn’t do the trick, but it does feel more correct to only open the file readonly when we don’t need to write to it.

**Comment by LibretroAdmin** [comment]
Would you guys like me to squash and merge this PR?

Would that fix the issue for Xbox?

**Comment by GABO1423** [comment]
> Would you guys like me to squash and merge this PR?
> 
> Would that fix the issue for Xbox?

Yes, the screenshots above show that this fixes the issue.

**Pull request merged**
