### PR TITLE
Numerous fixes for HDR feature

### PR DESCRIPTION
**Pull request by MajorPainTheCactus**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

Fixed up HDR for UWP/WinRT builds
Fixed D3D11 validation warnings
Fixed up technically incorrect labels

## Related Issues

N/A

## Related Pull Requests

Added HDR Support for D3D12 #12916 

## Reviewers

@twinaphex

### CODE REVIEW

**Comment by twinaphex** [comment]
Awesome work! I'll try and take care of the conflict for you.

**Comment by twinaphex** [comment]
Hopefully you agree with the edit in some of the sublabels there? 

"Once the color space is converted to linear space, controls whether should we use an expanded colour gamut to get to HDR10."

**Comment by MajorPainTheCactus** [comment]
Thanks @twinaphex  hopefully this won't be on the scale of my last pull request! There are still a few more minor things I need to do and fix - I'll do those over the coming days hopefully once this pull request has been wrapped up.

**Comment by MajorPainTheCactus** [comment]
Yes that sub label edit is fine although 'should we' should probably be 'we should', no? Really that whole sub label should be re-written as to explain why we expand the colour gamut - it's to do with low quality HDR TVs.

**Comment by twinaphex** [comment]
Question @MajorPainTheCactus , so this happens on Xbox right now -

line 491 of dxgi_common.c returns false -

```
         supported = (desc1.ColorSpace == DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020);
```

instead, `desc1.ColorSpace` is -

```
desc1.ColorSpace = DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709 (0)
```

Is this sufficient for HDR support or should we let it fail like this?

**Comment by twinaphex** [comment]
Yeah, looks like it's not worth bothering with on Xbox for now. If I add that format to 'supported' I can get the HDR tab to show, however after setting HDR Enable to 'ON', it takes a while for it to display the screen again, and after it shows the screen I lose all controller input. So might not be worth messing around with for now.

**Comment by twinaphex** [comment]
Yeah it seems it's some kind of swapchain issue on Xbox with HDR Mode.

on D3D12 it seems the screen constantly flickers between black and the final output image when HDR is enabled. It's very annoying.

On D3D11 it seems like the screen/frame is just frozen in place and no longer updates. 

It still seems like RetroArch the app itself is still running and does not hang.

**Comment by twinaphex** [comment]
There's also still this warning spam in Debug Mode with D3D12 and HDR on -

D3D12 WARNING: ID3D12CommandList::ClearRenderTargetView: The application did not pass any clear value to resource creation. The clear operation is typically slower as a result; but will still clear to the desired value. [ EXECUTION WARNING #820: CLEARRENDERTARGETVIEW_MISMATCHINGCLEARVALUE]

**Comment by MajorPainTheCactus** [comment]
Ah yes I need to fix the clear colour - it's a simple fix but shouldn't make too much difference to the release build. 

As for Xbox what Xbox does this run on? XBox One doesn't support HDR I'm not sure if Xbox One X does - it might do if I recall correctly. Anything like Xbox 360 is no way going to support it.

**Comment by twinaphex** [comment]
I tested it on Xbox Series X.

**Comment by MajorPainTheCactus** [comment]
Oh wow I didn't know we could develop on that. Hmm that should work straight out of the box (excuse the pun). I sadly don't have an XSX at home so can't test it myself.

**Comment by MajorPainTheCactus** [comment]
Ah ok so reading the Arstechnica article on what you've done and it looks like Retroarch an Xbox One title running on the XSX. I'm guessing you're using the dx11 driver? In which case the custom Xbox HDR part of the dxgi is definitely not going to backwards compatible with dx11. But that's all guess work and assumptions on my part.

**Comment by twinaphex** [comment]
Hi, for Xbox we use the unedited MSVC 2019 UWP solution - this is the solution file -

https://github.com/libretro/RetroArch/blob/master/pkg/msvc-uwp/RetroArch-msvc2019-UWP.sln

any Xbox Series S or X can be turned into a devkit officially by just using Dev Mode (costs a one-time $15).  From there you can deploy UWP apps to it.

**Comment by twinaphex** [comment]
BTW @MajorPainTheCactus , this is something you might want to address in a future PR - we have a new warning now with msys2/mingw64 -

```
gfx/common/win32_common.c: In function 'win32_get_client_rect':
gfx/common/win32_common.c:2356:43: warning: passing argument 2 of 'GetWindowRect' from incompatible pointer type [-Wincompatible-pointer-types]
 2356 |    return GetWindowRect(main_window.hwnd, &rect);
      |                                           ^~~~~
      |                                           |
      |                                           RECT ** {aka struct tagRECT **}
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:72,
                 from gfx/common/win32_common.c:29:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winuser.h:3639:60: note: expected 'LPRECT' {aka 'struct tagRECT *'} but argument is of type 'RECT **' {aka 'struct tagRECT **'}
 3639 |   WINUSERAPI WINBOOL WINAPI GetWindowRect(HWND hWnd,LPRECT lpRect);
      |                                                     ~~~~~~~^~~~~~

```

**Comment by MajorPainTheCactus** [comment]
Interesting I did compile both release and debug under mingw with no warnings - I must have made a last minute change or something. I'll fix it up as soon as I can.  

That's amazing that we can release full blown titles on XSX, something Microsoft seemed to promise on Xbox One but never delivered AFAIK. Anyway ok so yes this should all absolutely work. Hmm maybe we need to pass correct values into SetHDRMetaData rather than the 'I don't know' values of zero for some things. 

Then again that wouldn't stop it working. I'm sure it's a simple fix tbh as there's not a lot of difference in the swap chain between SDR and HDR. Do you have any contact with Microsoft to see whether this should work - they have an open discord forum to talk to the devs there. Thinking about it I can post there - the only problem is I don't have a XSX to investigate where it's failing. It's a good excuse to buy one...

**Pull request merged**
