### PR TITLE
Move the notification message to avoid overlapping

### PR DESCRIPTION
**Pull request by alfrix**
Current positions it's overlapping stuff
current

This is the position in this PR
4k no scaling
4k_nodpi

4k 250%
4k_dpi_250

4k 300%
4k300

1080 no scaling
1080p_nodpi
1080 125%
1080_dpi_125

Handheld layout
handheld_mode

### CODE REVIEW

**Comment by alfrix** [comment]
An alternative is lowering the version/core string of xmb, because i just compiled @natinusala ozone and this doesn't look good there

**Comment by RobLoach** [comment]
With this change, the OSD would look like it's in a strange position when in game.

The OSD is on a separate layer than the XMB Menu. If you're very concerned, enable the Background Color for the OSD text.

**Comment by fr500** [comment]
I make it very small and at 0.01 x/y

**Comment by alfrix** [comment]
There is no consensus

**Pull request closed without merging**
