### PR TITLE
Add plain DRM display driver.

### PR DESCRIPTION
**Pull request by vanfanel**
This is a simple DRM video driver so rendering is done using DRM planes (of the overlay type).
It's intenteded to work on the Raspberry Pi using the new VC4 KMS/DRM kernel video driver, but it should work on any hardware having XRGB8888 and RG565 overlays.
It will take the place of the dispmanx driver when Raspbian starts booting in KMS mode by default, but it will benefit other boards, too.
For example, when the DRM driver is completed for the Allwinner A20 boards like the Cubieboard, it will take the place of the custom sunxi framebuffer driver. 

For now, it's blocking on vsync and single-threaded, using a simple double buffering mechanism, so it should be a low input latency solution.

### CODE REVIEW

**Comment by Alcaro** [comment]
> +HAVE_PLAINDRM=no           # Plain DRM (no GL) video support

You sure that shouldn't be auto?

> + CFLAGS += -I/usr/include/libdrm

Shouldn't that go through pkg-config? Or does pkg-config not support that specific package?

> +static void drm_surface_set_aspect (float aspect, struct drm_surface *surface) {

Weird argument order ('this' equivalents usually go first), and that space before the paren is a typo. Not sure if it needs to be a function at all, but I guess you've got a plan there.

> +void deinit_drm();
> +void format_name(const unsigned int fourcc, char *format_str)
> +uint64_t plane_type (drmModePlane *plane) {
> +void drm_plane_setup(struct drm_surface *surface) {
> +void deinit_drm() {

static? And plane_type has another of those weird spaces.

Finally, this should probably be added to griffin.c.

**Comment by twinaphex** [comment]
Very impressive, and looks like a highly ambitious driver. I quite like the idea.

I'm going to rebase it a bit and then commit it. I will let you know when this has happened and then close this PR.

**Comment by twinaphex** [comment]
I backported this and I also addressed the concerns Alcaro had about the initial PR, so I think we are good there now.

**Comment by Kivutar** [comment]
Thanks for this, I really hope we can use this on Allwinner some day.

**Pull request closed without merging**
