### PR TITLE
Update apple_platform.h

### PR DESCRIPTION
**Pull request by mrjschulte**
This quick hack restores the builds for iOS.

@Autechre64 @yoshisuga

### CODE REVIEW

**Comment by twinaphex** [comment]
This breaks the Mac build though.

Can you find a way so that this will compile for both iOS and OSX?

**Comment by twinaphex** [comment]
OK, let me know if it's fixed as of this commit - 

https://github.com/libretro/RetroArch/commit/d2d240ecf5a877b6adc6f4be0dde23920e3c3b84

**Comment by mrjschulte** [comment]
Yup, we're good now. Thanks @Autechre64 !

**Comment by mrjschulte** [comment]
Spoke too soon. No games work right now. Content loads but the screen remains dark :(

**Comment by twinaphex** [comment]
@mrjschulte Can you bisect this issue? I cannot really test on iOS.

**Comment by twinaphex** [comment]
Better than a bisect is an actual fix.

**Comment by twinaphex** [comment]
@mrjschulte Try this branch -

https://github.com/libretro/RetroArch/tree/iosfix

and see if it works with that.

**Comment by twinaphex** [comment]
OK so I merged the iosfix into master.

@yoshisuga says this works for him on iOS with a core like Beetle PSX.

Let me know if the current master works for you on iOS.

**Comment by mrjschulte** [comment]
Working now. Closing.

**Pull request closed without merging**
