### PR TITLE
Disable save states based on save state support level defined in core info files (do not merge)

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR represents the first stage of starting to make use of the extended core info data added in https://github.com/libretro/libretro-super/pull/1182, https://github.com/libretro/libretro-super/pull/1519

It adds parsing of the core info 'savestate support' parameters, as defined by:

```
# Libretro Features - The libretro API features the core supports. Useful for sorting cores
# Does the core support savestates
# savestate = "true"
# If true, how complete is the savestate support? basic, serialized (rewind), deterministic (netplay/runahead)
# savestate_features = "serialized"
```

These are converted to a savestate support 'level' in the internal core info struct:

```c
/* Defines the levels of savestate support
 * that may be offered by a core:
 *   - serialized:    rewind
 *   - deterministic: netplay/runahead
 * Thus:
 *   (level < CORE_INFO_SAVESTATE_BASIC)
 *      -> no savestate support
 *   (level < CORE_INFO_SAVESTATE_SERIALIZED)
 *      -> no rewind/netplay/runahead
 *   (level < CORE_INFO_SAVESTATE_DETERMINISTIC)
 *      -> no netplay/runahead
 */
#define CORE_INFO_SAVESTATE_DISABLED      0
#define CORE_INFO_SAVESTATE_BASIC         1
#define CORE_INFO_SAVESTATE_SERIALIZED    2
#define CORE_INFO_SAVESTATE_DETERMINISTIC 3
```

This information is currently used as follows:

- It is displayed in the core info menu (e.g. `Settings > Cores > Manage Cores > <core_name>`
- It is used to disable all internal save/load state functions for cores with no savestate support
- It is used to hide the Quick Menu savestate entries for cores with no savestate support

In future PRs, the savestate support level will be used to selectively disable (and hide the menu entries for) rewind, runahead and netplay functions.

The PR itself should be fine, code-wise - but while testing it, I found that a number of existing core info files are inaccurate. Some specify that cores with working savestates don't have savestate support, others specify the wrong savestate level. Thus we should not merge this PR (or add selective runahead, etc. disabling) until all the core info files are checked.

### CODE REVIEW

**Comment by i30817** [comment]
Does the keyboard passthrough the savestate hotkey if the core doesn't support it? Probably not worth it, feels kind of inconsistent now that i think about it, some cores would need game focus mode to access the fkeys f2 and f4 and some wouldn't just based on savestate support.

**Comment by jdgleaver** [comment]
@i30817 I agree that it's not worth meddling with hotkey assignments based on the currently loaded core - that would likely just cause confusion, and not really provide much tangible benefit :)

**Comment by Ryunam** [comment]
This could be *very* handy especially for new users. Preventing the visualization of unsupported features for any given core is definitely an improvement in convenience.

I just have one minor observation regarding this feature. Perhaps it might be sensible to also include a toggle somewhere, that allows to de-activate this detection for testing purposes. 
I will give you one practical example: as per its intended configuration (and as reflected in its core info file) the Mupen core does not currently support deterministic savestates and thus does not work with Runahead. However, m4xw did some work on an experimental branch some time ago that resulted in partial support for Runahead Single Instance mode (only when compiling the Mupen core from that branch). 
Now, the potential issue I see with this is that, if one were to test that core in such a situation, trying to forcedly activate Runahead or any other savestate-based option that is not "officially" supported would become harder, because this detection could get in the way and automatically make those options invisible.

It may or may not be an actual problem with this implementation, but I just thought it was worth mentioning!

**Comment by i30817** [comment]
I'd assume that since this was part of the core info files, someone testing a new feature could just edit that file.

**Comment by jdgleaver** [comment]
@Ryunam 

> This could be very handy especially for new users. Preventing the visualization of unsupported features for any given core is definitely an improvement in convenience.

The visualization is just part of it :)

One of the main things here is to automatically disable unsupported functionality - i.e. if the user enables runahead or rewind globally, then are are a number of cores that will outright crash on start due to 'incomplete' savestate implementations. By checking the savestate support level before enabling runahead/rewind/etc., all of this unpleasantness goes away without requiring any user intervention.

> Now, the potential issue I see with this is that, if one were to test that core in such a situation, trying to forcedly activate Runahead or any other savestate-based option that is not "officially" supported would become harder, because this detection could get in the way and automatically make those options invisible.

Yes, that's a valid concern. But as @i30817 points out, you can change the status of a core by editing (or just commenting out) one line of an info file. I think testers should be able to handle these sorts of edits? Having a menu toggle in this case seems like overkill, and would make for some messy code...

**Comment by i30817** [comment]
IMO just needs documentation in the libretro headers for the savestates functionality. New implementators of savestate functionality will read that before anything and a setting is not necessary or desirable.

**Comment by Ryunam** [comment]
Fair enough, definitely sounds like the most reasonable choice! No need to over-complicate anything or add bloat/clutter when one can just modify the core info file to achieve the same purpose.

**Pull request merged**
