### PR TITLE
Explore: Better accommodate different languages (updated)

### PR DESCRIPTION
**Pull request by schellingb**
## Description

As suggested by @IlDucci in https://github.com/libretro/RetroArch/pull/11111#commitcomment-41082796 this PR replaces 3 strings with format strings to better accommodate different languages.

- "By" becomes "By %s"
- "Select" becomes "Select %s"
- "Items" becomes "%u Items"

This PR correctly removes the already translated old strings from the language files other than US.

## Related Pull Requests

#11111 initial localization PR
#11126 Failed PR that did not remove the old string from languages other than US

## Reviewers

@IlDucci

### CODE REVIEW

**Comment by IlDucci** [comment]
Thank you for the changes, but there can be improvements by adding the entirety of the strings, instead of using variables, in this case.

For example: "By Release Date", as it is, would show up in Spanish as "Por Fecha de lanzamiento", where the uppercasing would look odd. If you could add one string per element, for example, "By Release Date" as a whole, I could translate it as "Por fecha de lanzamiento". The same could be said with "Select %s".

However, "%s items", as it uses a numeric value, it's a whole different ball game, as the plural forms can be very different between languages (Russian and Ukranian, if I recall correctly, have one value for 1 element, one for two elements, and one for 3+). I think RetroArch doesn't deal with these sort of situations, so this string can be kept as is and we can add a parenthesis afterwards.

**Comment by schellingb** [comment]
These are all good points. I'm not sure if adding that many strings just for this feature is worth it. So far it re-uses strings from the already existing database browser, which would all need to be copied twice just for "By %s" and "Select %s".
Maybe we'll better get rid of these prefixes then.  
I think it's fine if the title bar just shows "Developer" instead of "Select Developer".  
Similarly it's probably fine to have the top menu item be "Developer (300)" instead of "By Developer (300 Items)".

What do you think?

**Comment by IlDucci** [comment]
About the two combinations of text, I think you could take out the "Select X" and use the "By X" as both the option name as well as the title name, like it is done in other areas of RA. I think it could be important to point out in the Explore section that these options are searches with the "By" word.

As for the items, it's okay if you leave the items word as well for now.

**Comment by schellingb** [comment]
OK, I think that's a good compromise. I'll prepare a PR.

**Pull request merged**
