### PR TITLE
Implement the 'up' and 'down' menu sounds for all menu drivers

### PR DESCRIPTION
**Pull request by Skirlez**
## Description

This PR implements the up and down sounds that were unused until now, in the closest way possible to how the
previous menu sounds were implemented. Here's a basic list of what it does:
1. Adds a new "Enable 'Scroll' Sounds" option in the Menu Sounds submenu, matching the other menu sounds.
2. Calls the function audio_driver_mixer_play_scroll_sound (defined in audio_driver.c) in all of the menu drivers' code files in the appropriate places
and also inside menu_cbs_left and menu_cbs_right, for scrolling with those buttons.
The function is called to play the 'up' sound when scrolling up or right (e.g. xmb top layer, leaving and entering ozone sidebar), and 'down' for down and left.
3. Adds a Hebrew translation for the new option and also the rest of the Menu Sounds option because I know that language and the page for adding new options says you should translate if you can.

Hopefully I did all of this right.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Oh man, this is great. Thanks for the contribution.

This has been a much-requested feature from our users with visual impairments who depend on audio cues to navigate.

**Comment by sonninnos** [comment]
Would it have been impossible to do it globally in `menu_driver.c` instead of all menu drivers separately? As in is that the only way to sense if the action actually did something?

As a tiny nitpick at least those ifs in the cbs files could be completely inside `#ifdef HAVE_AUDIOMIXER`, and also without curly brackets because they are single-lines.

**Comment by Skirlez** [comment]
> Would it have been impossible to do it globally in `menu_driver.c` instead of all menu drivers separately? As in is that the only way to sense if the action actually did something?

You *could* try that, but then you'd be running into issues like when you wrap around a list of options using down, it plays the 'up' sound, since the new selection is higher than the first, or issues like it playing when a selection technically changes, but you're not supposed to hear the sound (I remember an attempted implementation of mine doing that when scrolling through the ozone sidebar). Doing it per menu driver gives you a lot more flexibility.

> As a tiny nitpick at least those ifs in the cbs files could be completely inside `#ifdef HAVE_AUDIOMIXER`, and also without curly brackets because they are single-lines.

My mistake, I'll fix it.

**Comment by sonninnos** [comment]
> like it playing when a selection technically changes, but you're not supposed to hear the sound (I remember an attempted implementation of mine doing that when scrolling through the ozone sidebar)

Hmm why shouldn't scrolling the Ozone sidebar also make a sound..?

(On a related note I've had on my list a long time the ability to do multiline scrolling with L/R also in the sidebar, since it can easily become a long list.)

Sure I get the flexibility bonus of doing it per menu, but also the bonus of having it global/centralized and more manageable. But can't have all as we all know. I would have assumed that all menus work basically close enough for the same tricks to apply always.

And I missed a few more nitpicks which are just trivial curly brackets opening on the same row.

**Comment by Skirlez** [comment]
> 
> Hmm why shouldn't scrolling the Ozone sidebar also make a sound..?
> 
> (On a related note I've had on my list a long time the ability to do multiline scrolling with L/R also in the sidebar, since it can easily become a long list.)
> 
> Sure I get the flexibility bonus of doing it per menu, but also the bonus of having it global/centralized and more manageable. But can't have all as we all know. I would have assumed that all menus work basically close enough for the same tricks to apply always.

The ozone sidebar should make a sound, sorry. I meant as in, due to the fact the selection was automatically changing when you changed tabs (iirc), it would play the sound/incorrect sound if you have an implementation that checks what changed when it detects a selection changes (which also makes it play a scrolling sound when you back out of a menu, iirc). 

You could try having it play the scroll sound in the menu action switch statement in `menu_driver.c`, instead of just checking for selection changes, but neither approaches make the sound play when you scroll in the ozone sidebar for some reason (I assume it's a different variable than the regular selection one) and I suspect it is handled in `ozone.c`, but I don't know.

I agree with you that a general implementation is preferable but I don't see a way to do it that plays the sound 100% accurately in all scenarios.

> And I missed a few more nitpicks which are just trivial curly brackets opening on the same row.

I would fix those but I don't know where they are. I know I accidentally changed one to that on `menu_cbs_right.c`. I guess I should go over it..?

**Comment by sonninnos** [comment]
Okeydokey, bingo bango.

**Comment by gouchi** [comment]
Tested quickly and it is working

<details>
<summary>xmb</summary>

scroll-sound

</details>

<details>
<summary>ozone</summary>

scroll-sound-ozone

</details>


<details>
<summary>rgui</summary>

scroll-sound-rgui


</details>



<details>
<summary>glui</summary>

scroll-sound-glui


</details>

**Comment by Skirlez** [comment]
Last reply reminded me I never attached a video showing the sounds being played, whoops

https://user-images.githubusercontent.com/17904548/210366793-d6361190-8b6c-4e90-8811-d80d8cf878ec.mp4

**Pull request merged**
