### PR TITLE
(Linux) Install the desktop entry for everyone in the top-level Makefile

### PR DESCRIPTION
**Pull request by chungy**
I've also removed the PNG from installation because the icon
specification will cause it to be prefered over the SVG version when
picking the icon.  I have edited the desktop entry to refer to the
icon by basename only, this will allow it to be properly selected
regardless of whether retroarch is installed in /usr or /usr/local

The desktop entry has also been cleaned up to the proper desktop entry
specifications.

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
It's missing GenericName and Keywords in desktop entry:

Keywords=frontend;engine;emulator;multi;xmb;

Something like that

**Comment by chungy** [comment]
Neither of those are actually required; GenericName shouldn't be just a copy of Name, either, but if you can suggest something for it, that'd be great. I'll go ahead and add the keywords.

**Comment by sergiobenrocha2** [comment]
You'll get lintian warnings without them.

**Comment by chungy** [comment]
I had a look at the Lintian tags and that doesn't appear to actually be true about GenericName. Still, not sure what could be written for it. "Libretro Frontend", perhaps?

**Comment by sergiobenrocha2** [comment]
Humm, yeah, maybe "Libretro Frontend"

You'll see lintian warnings on debian 8, at least for the missing Keywords.

**Comment by chungy** [comment]
It's already done ;)

**Comment by twinaphex** [comment]
@Alcaro and/or others - can we merge this or not?

**Comment by sergiobenrocha2** [comment]
I tested here, it's working.

**Comment by Alcaro** [comment]
The smaller the Debian-specific parts, the better. If sergio says it works, I'll trust that.

**Pull request merged**
