### PR TITLE
wiiu changes; move net function back into its net define block

### PR DESCRIPTION
**Pull request by FIX94**
needed to properly compile for platforms without network

### CODE REVIEW

**Comment by FIX94** [comment]
hm damn, I wanted to make a separate PR for the wiiu stuff, what do I do now?

**Comment by FIX94** [comment]
Oh well I guess I'll just explain the wiiu change as well, basically for the wiiu build it now requires libiosuhax from my branch compiled using "make wut":
https://github.com/FIX94/libiosuhax
and libfat from dimok here:
https://github.com/dimok789/libfat
compiling using the Makefile in the "wiiu folder".
Doing so will allow the wiiu build to have fast SD access as well as FAT32 USB access, if no iosuhax is present it will run like normal so people without a CFW arent affected in any negative way.

**Comment by twinaphex** [comment]
@FIX94 Hi there,

maybe you could add these build instructions to README.md inside the RetroArch repo? I don't think it has a Wii U section yet so you could add these instructions there and further details as well.

**Comment by fr500** [comment]
@FIX94 I guess after building thosed have to be copied to some place? or added to the path or something?
Just compiling them wouldn't achieve anything

**Comment by FIX94** [comment]
they have to go into devkitpro/portlibs/ppc to be then used.

**Pull request merged**
