### PR TITLE
WIP: discord-rpc support

### PR DESCRIPTION
**Pull request by fr500**
## Immediate Goals:

1. Allow rich presence updates to be posted to discord
2. Show the game name, core name while in-game, show an icon depicting the currently emulated system

## Future Goals:

1. Allow joining netplay lobbies (as player or spectator) from discord

### CODE REVIEW

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/5690#issuecomment-375175714

**Comment by fr500** [comment]
So far it shows that you're running RA
image

And changes to in-game status once a game is loaded
image

**Comment by twinaphex** [comment]
I will merge this and then make some improvements to its initial state.

**Comment by fr500** [comment]
I'm no longer sending any PRs until I consider them complete then. 
I care about the quality of my contributions and this was nowhere near ready.

**Comment by twinaphex** [comment]
I frankly don't see the need to turn this into yet another argument. 

I fixed mac/Linux compilation, I made it work for Griffin. We now have a solid base to build upon. We can now just continue building it up through iterative PRs.

I don't see the value of one huge PR that needs to get merged weeks down the line, and at least this speeds up development. I think iterative PRs is a better approach.

**Comment by fr500** [comment]
It's not an argument. Nor a fight, it's my stance. I'd like to have a say on when I want my code merged.

The pull request is there with a WIP status, the only reason to send one is to get more eyes on the subject, find any potential issues. I have seen this plenty of times in the past. If I had let you merge my remapping changes I would have never finished them. 

Now I have to read your changes in order to do any other changes, and as I said, it wasn't ready.
We may be freeing uninitialized memory on discord shutdown since the API doesn't have any return codes. I was still trying to figure it because the ready callback isn't being fired.

Also you merged the implementation without even trying to figure out how the API works. You don't even own the app you are merging which in turn means your implementation now reads Dongers:

image

I like to send complete stuff, I actually detailed stuff that I'd like to do last night on the chat before having it on master. There are ways to contribute and advance PRs without having it on master.

I really don't understand why merging everything immediately is so important.

**Comment by fr500** [comment]
For reference:
https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

https://discordapp.com/developers/docs/rich-presence/how-to

**Comment by twinaphex** [comment]
Alright, you didn't want it merged and you wanted a say in when it got merged.

That is fine.

Since it has already happened anyway and I can't change the past, how do you want to proceed from here? At the very least this happened:

* Strings are now translated
* It should build now for mac and Linux
* It should work now with Griffin

Let's stop fighting here and let's instead focus on finishing this up. You can create a new PR and I will put you in the driver's seat and I won't merge without your consent.

**Pull request merged**
