### PR TITLE
android: add runtime permission checking for Android 6.0+

### PR DESCRIPTION
**Pull request by bparker06**
for issue #4769

### CODE REVIEW

**Comment by meepingsnesroms** [comment]
Can retroarch open files on the external sd using c code with this?

I thought you had to use external storage provider in Java for this permission.

**Comment by bparker06** [comment]
Why did you merge this? Did you test it yourself? Did you see any feedback that said it was working? This issue is also attached to a bounty, so please do not merge it without knowing that it works.

**Comment by twinaphex** [comment]
@meepingsnesroms Don't jump the gun like this again. Realize you are in a team where ultimately I'd prefer looking at things first before I decide to merge.

**Comment by meepingsnesroms** [comment]
Sorry, I won't do that again.

**Pull request merged**
