### PR TITLE
Choice to build standard folder struc. on PS3

### PR DESCRIPTION
**Pull request by crystalct**
This is a request: the choice to compile and build the package with standard structure of folders for PS3.
Many PS3 users from psx-place.com request the possibility of having the folders in the stardard format as the other systems:
```
INSTDIR
  |_ assests
  |_ cores
  |_ system
  |_ logs
etc etc
```
Current folders structure on PS3 is:
```
INSTDIR
  |_ cores
      |_ assests
      |_ system
      |_ logs
etc etc
```

### CODE REVIEW

**Comment by twinaphex** [comment]
How about we make this the new default instead?

**Comment by crystalct** [comment]
The idea is to keep the past safe with HAVE_STANDARD_FOLDERS = 0 (present only in the contest build of PS3)
and with HAVE_STANDARD_FOLDERS = 1 to make salamander and cores manually. It is enought to make and arrange a PKG
that follow the Retroarch standard folder structure.
After could be adjusted the scripts to make pkgs or with old PS3 folder structure  or the Retroarch standard folder structure, using HAVE_STANDARD_FOLDERS.

**Comment by dizine** [comment]
New default with an option to build old style manually if necessary but focus on the future/new releases?

**Comment by crystalct** [comment]
If you are agree, i added the script ps3-new-cores.sh and a new folder inside pkg/ps3 to create the new package using the Retroarch standard folders structure.
To avoid wrong overwrite to PS3 end users, i added a new INSTDIR "RETROARCH" (as other platforms).

**Comment by twinaphex** [comment]
I'd prefer we don't add yet even more files for this.

**Comment by crystalct** [comment]
Removed added files. 
HAVE_STANDARD_FOLDERS default is 0
If HAVE_STANDARD_FOLDERS setted to 1:
PSL1GHT version will "know" the standard Retroarch folder structure and INSTDIR will be RETROARC1
or 
the other SDK  version will "know" the standard Retroarch folder structure and INSTDIR will be RETROARC0

**Comment by twinaphex** [comment]
Hi, I'm very sorry but we have to give up on this target completely. We recommend that you and others can help us making the PSL1GHT port more viable in the future.

**Comment by crystalct** [comment]
Retroarch folder structure is indipendet about sdk version.....so do you want keep the strange folder structure for (any) PS3 version?

**Comment by twinaphex** [comment]
@crystalct Please try to help us building up the PSL1GHT port instead. I feel very sorry but this is how it has to be.

**Comment by crystalct** [comment]
We need to build up a good OpenGL driver for PSL1GHT or expand GCM driver for RSX... but im not good in graphics...
Anyway... after many years now the "other " SDK for PS3 has become a problem.... even to remove all references as it suddenly became dangerous... now that PS3 is an obsolete machine and noboy at his japanese Company doesn't care anymore....

I was petrified by what you did.

**Comment by twinaphex** [comment]
I am very sad by it too.

**Pull request closed without merging**
