### PR TITLE
(3DS) Sanitise/Improve display mode selection

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

At present, the display mode of the top screen of the 3DS port is set by adjusting the 3D slider. This has the following issues:

- Without googling, it's not at all obvious which mode each slider position corresponds to

- It's not possible to disable the 3D effect without adjusting the slider (this can be troublesome if the 3D slider breaks/gets stuck, which does happen...)

- Certain display modes only work on o3DS, due to differences in the display hardware - if an unsupported mode is selected, the output 'breaks', as described in issue #3919

This PR does away with selection via the 3D slider, and instead adds a new `3DS Display Mode` option under `Settings > User Interface` (see note at end...). This has the following settings:

- `3D`: Standard 3D mode with square pixels and menu depth effect. Intensity is set via the 3D slider

- `2D`: Disables 3D effect completely - same as turning the 3D slider to the 'off' position (also provides the highest performance, which was always the case)

- `2D (Pixel Grid Effect)`: (o3DS only - option not shown on n3DS) This is the existing "400x240" mode, which creates a nice screen door/vertical scanline effect by disabling the parallax barrier and outputting black to every other pixel column

- `2D (High Resolution)`: (o3DS only - option not shown on n3DS) This is the existing "800x240" mode, which enables 'proper' access to all pixels on the screen again by disabling the parallax barrier

While adding this, I also took the opportunity to disable fps statistics calculation/output when the bottom screen is turned off (since you can't see this anyway with the bottom screen turned off...). This actually provides a not insignificant performance boost on o3DS.

**Note:** I was unsure whether to place `3DS Display Mode` under `Video` or `User Interface`. On o3DS, it's very much a `Video`-related option - but on n3DS it's basically a 3D on/off switch, which perhaps most significantly affects the appearance of the quick menu (so a `User Interface` matter). Since the existing `3DS Bottom Screen` option is already under `User Interface`, I decided just to group them together. If anyone objects, just let me know.

## Related Issues

This should close issue #3919, since the 'broken' display mode is no longer selectable on n3DS.

### CODE REVIEW

**Comment by orbea** [comment]
@jdgleaver You might find this article helpful.

https://help.github.com/en/articles/closing-issues-using-keywords

I'll close issue https://github.com/libretro/RetroArch/issues/3919 given your comments. :)

**Comment by jdgleaver** [comment]
@orbea Ah, awesome, thank you!

(I was wondering why sometimes issues were closing automatically, and sometimes not. Turns out I wasn't always using the correct syntax...)

**Comment by gabrielmathus** [comment]
Hi! I would advise you to reimplement 800x240 mode for N3DS, since now there are apps like mGBA that make use of that, and Luma3DS officially supports it.

**Comment by pdpapper** [comment]
I'm not sure how this is currently being done that only supports the old 3DS, but 800x240 resolution mode can be enabled using libctru gfxSetWide(). This works for o3DS, n3DS, and n2DS XL. The original 2DS is not supported because its upper screen is not 800x240.

**Pull request merged**
