### PR TITLE
Add setting for showing/hiding the ability to rename playlist items

### PR DESCRIPTION
**Pull request by Brunnis**
Stage 4 of the implementation of "Kiosk Mode" as specified here: [RetroArch Kiosk Mode v4.pdf](https://github.com/libretro/RetroArch/files/1320429/RetroArch.Kiosk.Mode.v4.pdf) (see further discussion in #3106)

This pull request implements a menu item under Settings -> Playlists called "Allow to rename entries", which can be used to show/hide the ability to rename playlist entries.

**Note:** I've renamed a couple of existing labels so that the naming matches that used for the implementation of the similar "Allow to remove entries" option. Those renamed labels are located at the same place in the msg_hash_*.h files as before my edits. I've placed completely new labels at the bottom of each file, as was requested for my previous pull request.

### CODE REVIEW

**Comment by twinaphex** [comment]
I cannot load playlists at all now. @JuanVCS can confirm. 

This is honestly a pretty bad way of filtering all this stuff away. Maybe it's better if I do this if there is going to be major regressions like this.

**Comment by Brunnis** [comment]
@twinaphex Sorry for that. I implemented the show/hide rename setting in the same way as the remove setting (I used the old pull request for that feature to double check my implementation). I'll have a look at what went wrong.

As for the Enable Settings Tab entry at the top of RGUI: This is a bug. The Enable Settings Tab shall not even be available in RGUI, but only XMB. I actually found this bug myself yesterday. Do you have any trouble with the placement in XMB (below Online Updater)? I'm open to suggestions, of course, but I can't read minds.

**Comment by Kivutar** [comment]
I haven't take a look at the implementation yet, but I tested the changes this morning and using a password to hide the settings tab worked as expected. It's also good to have a way to hide the 'rename entry' in the use case of the kiosk mode, for arcade cabinets.

I'm going to take a look at the diffs.

**Comment by Brunnis** [comment]
@twinaphex I could not reproduce the issue with my fork. However, my fork isn't completely synced up to the latest commits, so I thought that might be the issue. I tried the latest nightly and could reproduce the issue. So, I made a new build at the commit right before this pull request was merged. The issue remained.

So, whatever it is that's causing the playlist issue, it's not caused by this pull request. I would prefer if such things were checked before handing out the blame...

I will go ahead and remove the "Enable Settings Tab" option from RGUI, though.

@Kivutar Thanks for the feedback.

**Comment by Brunnis** [comment]
@twinaphex I've added a pull request that removes "Enable Settings Tab" from RGUI: https://github.com/libretro/RetroArch/pull/5501

Let me know if there are any other things that need to be changed.

**Comment by Kivutar** [comment]
Does it fix the loading of collections from RGUI? Go in the Main Menu, Load Content, From Collection.

**Comment by Brunnis** [comment]
No. I don't know where you've gotten the idea that it was my code that caused that issue... I've compiled RetroArch just after https://github.com/libretro/RetroArch/pull/5479 and the issue was not present. I've also compiled RetroArch just before https://github.com/libretro/RetroArch/pull/5496 and the issue was present.

So, whatever it is that caused this, it has nothing to do with my two pull requests. Some other commit between my two pull requests is to blame.

**Comment by twinaphex** [comment]
@Brunnis - Alright, we'll investigate that. Sorry about attributing blame where it shouldn't.

**Comment by Brunnis** [comment]
@twinaphex No worries. :-)

**Pull request merged**
