### PR TITLE
Add option for merging 'Hotkey Enable' device types

### LINKED ISSUE #15492: "Enable Hotkey" doesn't work across multiple devices
## Description

I'm trying to set up custom controls for the non-Steam RetroArch on the Steam Deck and have run into this RetroArch bug that's giving me a real hard time.

### Expected behavior

If I set "Enable Hotkeys" to a keyboard key, then none of the hotkeys should activate when I am not holding that key down, (they should only activate when I am holding that key down) regardless of what control they are mapped to, no matter which control device.

### Actual behavior

If I set "Enable Hotkeys" to a keyboard key, but some of the hotkey functions are mapped to the game controller, the ones mapped to the game controller don't require the keyboard key to be pressed. They activate regardless whether the keyboard key is pressed or not.

### Steps to reproduce the bug

1. Set "Enable Hotkeys" to a keyboard key, such as Q
2. Set "Save State" to a controller button, such as right shoulder.
3. Press right shoulder in game without pressing Q and you'll see the save state function activated, even though it shouldn't be activated without pressing Q.

### Bisect Results

The concept of a separate keyboard and joypad are sort of made obsolete by the Steam Deck and other handhelds that have more buttons than an XBox controller, so naturally one of those "extra" buttons that I'm trying to use for "Enable Hotkeys" would have to get mapped to the keyboard. Except I can't do that because of this bug.

### Version/Commit
6616b80 built on May 16 2023, flatpak downloaded through Discover Software Center on the Steam Deck.

### Environment information

- OS: Steam OS on the Steam Deck
- Compiler: GCC (12.2.0 64-bit)

This issue is similar to #14048 because changing that would also solve this I think.
I also posted about this on the forums: https://forums.libretro.com/t/enable-hotkeys-bug-or-just-unexpected-behavior/42140

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

Let's add a simple switch for getting the previous behavior regarding hotkeys and different device types. Which is that keyboard hotkeys will also be blocked if only controller has the enabler set, and vice versa.

## Related Issues

Closes #15492

### CODE REVIEW

**Comment by bradrhodes** [comment]
Thanks @sonninnos for having a look at this. Your consideration and work to make people's experience better is definitely appreciated.

**Comment by Immersion95** [comment]
The L3 + R3 hotkey doesn't work anymore, Start + Select works for example

**Comment by sonninnos** [comment]
More info would be nice than just "anymore". With this new option on or off? Should not matter one bit, since all it does is act as if the enabler is bound to both keyboard and gamepad if only either.

**Comment by Immersion95** [comment]
> More info would be nice than just "anymore". With this new option on or off? Should not matter one bit, since all it does is act as if the enabler is bound to both keyboard and gamepad if only either.

Sorry, the culprit isn't this PR. It's from the Jan, 24-25th commits.

**Pull request merged**
