### PR TITLE
Clean up the builtin zlib.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This cherry-picks two commits from PR https://github.com/libretro/RetroArch/pull/9192 which are safe and should prevent excessive conflicts in the future by merging them first.

## Related Issues

This does a few things (Clean up only).

* It removes `WANT_ZLIB` which is not useful and causes a giant mess in the build files. Any builds that are not using the builtin zlib should not include `libretro-common/include/compat/zlib`.
* It adds and removes `HAVE_BUILTINZLIB` where relevant, this variable is only needed when using both `Makefile.common` and the builtin zlib.
* It updates the include paths across the repo by making sure `libretro-common/include/compat/zlib` is included, removing `deps/libz ` which only has internal zlib headers and removing `deps/zlib` which does not exist in the repo anymore. Note that anything that sets both `HAVE_BUILTINZLIB` and then uses `Makefile.common` will automatically have `libretro-common/include/compat/zlib`.

## Related Pull Requests

https://github.com/libretro/RetroArch/pull/9192

## Reviewers

This should be safe, but let travis help confirm that.

### CODE REVIEW

**Comment by orbea** [comment]
I added two more commits for more clean up.

* This removes `infback.c` which is not used and should not be used with `inflate.c` which we do use.
* Renames `libz-crc32.c` to `crc32.o` to match the upstream file name.
* Removes `zconf.h.in` which is an identical file to `zconf.h` and also a duplicate copy of `zconf.h`. 
* Moves `libretro-common/include/compat/zlib/zutil.h` back to `deps/libz/zutil.h`. This is an internal zlib header and should not be used by other projects which should only use `zlib.h`. Fortunately this still seem the case everywhere in the repo.

**Comment by twinaphex** [comment]
'Renames libz-crc32.c to crc32.o to match the upstream file name.'

This is an issue with many cores though that have an object name called 'crc32.c', and especially on statically linked targets this could resolve in linker errors. Hence why it's prudent to rename this file. It's too generic as-is.

**Comment by orbea** [comment]
Thank you for pointing that out, I reverted that specific change.

**Comment by RobLoach** [comment]
Compiled and ran for me. Can still run zipped games...

Screenshot at 2019-07-25 13-28-14

**Comment by orbea** [comment]
Thanks for testing, this PR should be almost entirely clean up and should not change behavior.

The exception is that removing `WANT_ZLIB` exposed that the `xcode10.1` build was not correctly using zlib by using `-DHAVE_ZLIB`, but not `-DWANT_ZLIB`. Now that is fixed and it exposed several new (Previously hidden) warnings, regardless seems like a step in the right direction.

@twinaphex As this is clean up, should not break anything and will help avoid a lot of extra rebasing work later I think this is ready.

For cores the update steps are very simple and safe.

1. Update `libretro-common`.
2. Update `deps/libz`.
3. Make sure `libretro-common/include/compat/zlib` is included and it is safe to remove any includes for `deps/libz` or `deps/zlib`.

**Comment by orbea** [comment]
I rebased this one more time to be safe.

**Comment by RobLoach** [comment]
Feels weird to have zlib in libretro-common instead of deps. One would assume deps would be third-party dependencies for RetroArch, while libretro-common would be common reusable code that libretro wrote.

**Comment by orbea** [comment]
I think moving it back would be outside the scope of my two PRs, but maybe one benefit is that a lot of internal zlib headers in `deps/libz` are not in the include path.

**Pull request merged**
