### PR TITLE
Fix AI translation service when using HW renderer

### PR DESCRIPTION
**Pull request by viachaslavic**
## Description

Hotfix for  #16275 .  Not as radical as #16428 . Tested on GNU/Linux.

### CODE REVIEW

**Comment by viachaslavic** [comment]
There is still a [issue with accessing the viewport in a multi-threaded cycle]( https://github.com/libretro/RetroArch/issues/16275#issuecomment-1981883837)
As a temporary workaround  - set `threaded_data_runloop_enable` to `"false"` in the retroarch.cfg.

**Comment by BarryJRowe** [comment]
I've noticed other issues with the old PR on my machine. In my case the HW screencaps are just black instead of upside down, so this doesn't address that issue.

**Comment by zoltanvb** [comment]
In my env (Linux + wayland + glcore + Beetle PSX HW), the current implementation crashes, and unfortunately also with this change it does that. (Which is not caused by a problem in this PR, of course.)
I spent some hours trying to get to the root of the problem, but could not find why - same function calls like in case of screenshot, but screenshot works, AI service crashes at read_viewport in translation_grab_frame. Crash is within EGL library, out of my depth unfortunately.

**Comment by viachaslavic** [comment]
> same function calls like in case of screenshot, but screenshot works ...

@zoltanvb because screenshot task running on main thread. I checked this just adding the  `task_is_on_main_thread` call

**Comment by mrobss** [comment]
> There is still a [issue with accessing the viewport in a multi-threaded loop](https://github.com/libretro/RetroArch/issues/16275#issuecomment-1981883837) As a temporary workaround - set `threaded_data_runloop_enable` to `"false"` in the retroarch.cfg.

I added this to my Dreamcast retroarch.cfg and now the core is no longer crashing but AI Service is giving me gibberish:
440576793_984200513065593_2902243748709591586_n
441034108_457224356830802_375862525508872571_n

Is there any current work around to be able to use the AI Service translations properly until RA gets updated?

**Pull request closed without merging**
