### PR TITLE
Create msg_hash_ru.c

### PR DESCRIPTION
**Pull request by 6lackmag3**
Added Russian translation

### CODE REVIEW

**Comment by Alcaro** [comment]
While we're grateful for help, RetroArch does currently not support non-Latin languages. A Russian translation is something we want at some point, but we're not ready for it yet.

Twinaphex, I'll leave it to you whether we should close this, leave it open as reminder that we need to get UTF-8 running, or if we should try to hack rarch up into supporting some Russian-friendly charset as well.

(and you forgot closing the MSG_RECORDING_TERMINATED_DUE_TO_RESIZE string.)

**Comment by twinaphex** [comment]
I'd say we make it a priority to have RetroArch support UTF-8 now since we will have to do it sooner or later anyway.

**Comment by 6lackmag3** [comment]
Thanks for the replies, guys! I will add other files then and keep fingers crossed for utf-8 support.

**Comment by twinaphex** [comment]
We're going to take tentative steps now to getting this to work - 

https://github.com/libretro/RetroArch/commit/51db7e695e72b303d957df74403a0f540e699832

Closing this for now.

**Pull request closed without merging**
