### PR TITLE
An environment callback for selectively hiding core options

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new environment callback: `RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY`

This can be used by a core to signal to the frontend whether a specific core option should be visible in the menu. This will allow cores to hide settings that are not relevant to the current configuration - e.g. certain Beetle PSX options could be hidden when using the software renderer.

[PokeMini PR #24](https://github.com/libretro/PokeMini/pull/24) serves as an example implementation - in particular, the code:

```c
	// If video scale is 1x, LCD filter is disabled
	// > hide pokemini_lcdfilter core option
	if (video_scale == 1)
	{
		struct retro_core_option_display option_display;

		option_display.key     = "pokemini_lcdfilter";
		option_display.visible = false;

		environ_cb(RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY, &option_display);
	}
```

Here are some screenshots of the PokeMini example:

- All options present:

Screenshot_2019-07-12_16-34-37

- `LCD Filter` hidden because it is not supported by the current config:

Screenshot_2019-07-12_16-35-15

### CODE REVIEW

**Comment by fr500** [comment]
Why though?
Genuinely wondering.

I have this setup in dosbox and other cores by setting core options again.

**Comment by fr500** [comment]
I figure this is easier/cleaner and there is less risk of RA crashing
because of the amount of core options changing

**Comment by jdgleaver** [comment]
> I figure this is easier/cleaner and there is less risk of RA crashing because of the amount of core options changing

That's exactly right. Changing the number of options while running is incompatible with the reference API - and doing so will very likely cause the frontend to segfault (or at least it would have done, before this PR was merged!)

**Comment by fr500** [comment]
It is what it does yes, but that's something that should still be handled.
If you did, thanks to you.

**Comment by jdgleaver** [comment]
Yup - it was really just a matter of making sure that the quick menu is correctly refreshed (and the selection marker reset) when the number of displayed options changes  :)

**Comment by fr500** [comment]
Thanks that means I could make some dosbox/sameboy options work on the fly
again, I'll do it in my forks I guess in case anyone wants that.

**Comment by RobLoach** [comment]
Would be awesome to expand this beyond the core options. For the Netplay Relay settings, for example, when "Use Relay Server" is disabled, hide the "Relay Server Location" option.

Screenshot at 2019-07-18 13-18-59

**Comment by jdgleaver** [comment]
@RobLoach Ah, yes - we can already do this 'piecemeal' with specific non-core options (just a little menu tweaking required), but a proper interface for hiding/showing any option (with all the required menu refreshing) would be very cool. It's a substantial amount of work though - adding show/hide to the core options just involved changing one display list, but having it everywhere would propagate some pretty low level modifications to *all* the menu code.

I guess we can add it to the TODO list, and see what happens...

**Pull request merged**
