### PR TITLE
Replay UI support

### PR DESCRIPTION
**Pull request by JoeOsborn**
This should add all the config, menu, hotkey, and features around BSV replay after program launch, resolving #4984.

Specifically:
- BSVs are saved to the savestate dir now, with suffix .bsvXXXX
- BSV filenames can autoincrement and be garbage collected
- Hotkeys and quick menu items for increment/decrement replay slot, start recording, start playback, halt replay record/playback
- Save state during recording and playback, and load state during playback are supported.  In the future load state during recording will be supported IF the state was part of that recording.
- Recording can be initiated during playback but not vice-versa, and recording cannot be initiated during recording.
- BSV record toggle was removed.

### CODE REVIEW

**Comment by JoeOsborn** [comment]
I see the build failures, I'll check them out.

**Comment by JoeOsborn** [comment]
I’m looking for feedback here on three areas:

1. whether bsv replays are integrated correctly into the UI, analogously to save states.
2. If there are places I’ve missed feature-gating on HAVE_BSV_MOVIE.
3. Weird interactions between states and replays, especially around state undo. I’ve tried to catch these but have been surprised before.

**Comment by hizzlekizzle** [comment]
These sounds like great improvements. Thanks for devoting so much time and effort to improving this feature.

I'll try to build and test some this evening.

**Comment by LibretroAdmin** [comment]
> I’m looking for feedback here on three areas:
> 
> 1. whether bsv replays are integrated correctly into the UI, analogously to save states.
> 2. If there are places I’ve missed feature-gating on HAVE_BSV_MOVIE.
> 3. Weird interactions between states and replays, especially around state undo. I’ve tried to catch these but have been surprised before.

Well given the lack of testing that has went on with BSV for over a decade, I think you can pretty much go with whatever you think is best here. So do whatever you think is best, it can only improve.

**Comment by JoeOsborn** [comment]
Thanks for being so open to patches!  Associating save states to replays and having a proper replay format are the next big changes but those shouldn’t be too noticeable to users (except that saving/loading states during recording and replay will work in a more useful way). It should be easy to maintain back compatibility of save states, but the replay format change will be breaking—at the least the file suffix will probably change to .replay and I may change the HAVE_BSV_MOVIE nomenclature to HAVE_REPLAY.

**Pull request merged**
