### PR TITLE
(RGUI) Add widescreen support

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new `Menu Aspect Ratio` option to RGUI, under `User Interface > Appearance`. It has three settings: `4:3` (default), `16:9` and `16:10`:

window_record__2019_03_19__11_53_52

This works by increasing the horizontal resolution of the framebuffer. The resolutions are as follows:

- `4:3`: 320 x 240

- `16:9`: 426 x 240

- `16:10`: 384 x 240

The extra width is beneficial when viewing playlists with long entry names:

Screenshot_2019-03-19_11-55-39

...or when viewing 'wide' thumbnails:

Screenshot_2019-03-19_11-55-54

Note:

- This works best with `Lock Menu Aspect Ratio` turned on, since most content is 4:3 and will thus cause extreme horizontal squishing when opening the quick menu. (This is not required on 3DS, which is one of the few platforms to always render RGUI 'correctly')

- This is completely disabled for the Wii, since `gx_gfx.c` does strange and unusual things with `video_driver_set_texture_frame()` (all the other drivers seem to handle menu rendering properly)

- Existing 320x240 custom wallpapers are not compatible with the new widescreen modes (simply stretching them looks terrible, so it just won't load them). I've therefore added new entries to the  'theme preset' configuration file:

```
rgui_entry_normal_color = "0xAARRGGBB"
rgui_entry_hover_color = "0xAARRGGBB"
rgui_title_color = "0xAARRGGBB"
rgui_bg_dark_color = "0xAARRGGBB"
rgui_bg_light_color = "0xAARRGGBB"
rgui_border_dark_color = "0xAARRGGBB"
rgui_border_light_color = "0xAARRGGBB"
rgui_wallpaper = "wallpaper_file.png"
rgui_wallpaper_16_9 = "wallpaper_file_16_9.png"
rgui_wallpaper_16_10 = "wallpaper_file_16_10.png"
```

...so a single theme can specify different wallpapers for each mode. I thought this was cleaner than having to create a whole new theme each time.

I will update some of the existing RGUI themes in `retroarch-assets`, but this is a lengthy and tedious task, so I'll do it as and when.

## Related Issues

This should close issue #8436

## Reviewers

@orbea might want to check that this meets his needs... :slightly_smiling_face:

### CODE REVIEW

**Comment by jdgleaver** [comment]
Just pushed another commit that allows for the menu text to be centred when selecting widescreen layouts:

window_record__2019_03_19__13_08_42

This enables the use of fancy borders via custom wallpapers.

**Comment by orbea** [comment]
Looks good, but `16:10` and `16:9` both appear as `16:9` on my screen with black bars on the top and bottom. I spent sometime playing with that and it seems the menu aspect ratio is inconsistent if the the aspect ratio is not `Core Provided` in the video settings.

Also I would suggest that the default should be set to the same value as the aspect ratio in the video settings (i.e. No change in behavior).

> This works best with Lock Menu Aspect Ratio turned on, since most content is 4:3 and will thus cause extreme horizontal squishing when opening the quick menu. (This is not required on 3DS, which is one of the few platforms to always render RGUI 'correctly')

I imagine this is not trivial to change, but I think it would be better if the rgui aspect ratio was not directly tied into the aspect ratio of the cores avoiding issues like this altogether?

**Comment by bparker06** [comment]
This pull request **introduces 1 alert** when merging a17f0e2136f4b30faa8d66dde91a8bac9eac387e into 4fb95db80b9e8b37eaed21c70787157ede416be9 - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-8b9fbd7b419d0fb48ee7cc4c264984049f1a11c4)

**new alerts:**

* 1 for Multiplication result converted to larger type

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jdgleaver** [comment]
>  Looks good, but 16:10 and 16:9 both appear as 16:9 on my screen with black bars on the top and bottom. I spent sometime playing with that and it seems the menu aspect ratio is inconsistent if the the aspect ratio is not Core Provided in the video settings. If it is set to Core Provided this feature seems to work as expected.

That's an inherent 'feature' of RGUI - and why we need the `Lock Menu Aspect Ratio` option. If you turn this on, you'll find that everything works as expected (regardless of video settings)

> Also I would suggest that the default should be set to the same value as the aspect ratio in the video settings (i.e. No change in behavior).

Not really possible, I'm afraid, since this would require supporting each aspect ratio in RGUI itself (which can result in some crazy large framebuffers that will not be compatible with console platforms)... :disappointed: 

> I imagine this is not trivial to change, but I think it would be better if the rgui aspect ratio was not directly tied into the aspect ratio of the cores avoiding issues like this altogether?

With `Lock Menu Aspect Ratio` turned on, the RGUI aspect ratio is not tied to core aspect ratio.

But you're right - the larger issue is with `video_driver_set_texture_frame()`.

I would *love* it if this function worked independently from the current video settings - i.e. if we could pass it a buffer, and an offset/scale size and it would just dump the texture on screen. As it is, it's completely entangled with everything else, and every platform has a different implementation. The only 'sane' version, in fact, is the 3DS one.

Fixing this would require a rewrite of every gfx driver, which is beyond the scope of what I want to do... (not to mention, how could I test all these different drivers, when I don't possess the relevant hardware?)

If someone could sanitise `video_driver_set_texture_frame()` then all this nastiness would go away, and we could get rid of the `Lock Menu Aspect Ratio` hack...

**Comment by RobLoach** [comment]
This is great! Thanks so much... I suppose there couldn't be an "Auto" to match the window's height and width? Similar to how XMB and Ozone grows and shrinks?

**Comment by jdgleaver** [comment]
@RobLoach That would be nice :slightly_smiling_face: 

But as with trying to handle all aspect ratios, it's kinda impractical. We'd have to support arbitrary framebuffer resolutions, which (a) wouldn't work on console platforms and (b) messes up text scaling (since we're using a bitmap font, we can't increase it's height)

I think what we really need is a new menu driver: `rgui-hd`. All the retro goodness, but with a 'standard' menu driver implementation...

**Comment by jdgleaver** [comment]
@bparker06 Whoops - let me fix that alert

**Comment by orbea** [comment]
> That's an inherent 'feature' of RGUI - and why we need the Lock Menu Aspect Ratio option. If you turn this on, you'll find that everything works as expected (regardless of video settings)

I do have `Lock Menu Aspect Ratio` enabled, try this...

1. Set the video settings aspect ratio to `4:3`.
2. Toggle the different menu aspect ratio settings and loop through them a few times.
3. At first it will seem right, but after a while I get a `16:10` aspect ratio when the menu aspect ratio is set to `4:3`.

**Comment by jdgleaver** [comment]
@orbea Ah, okay - an edge case! Sorry about that. This will never be apparent during normal use (actually running content), but let me see if I can fix it...

**Comment by jdgleaver** [comment]
@orbea That's what I get for trying to be efficient...

Should be fixed now - could you please try again?

Note: if you change the aspect ratio in video settings *after* changing 'Menu Aspect Ratio' the display will be wrong. There is nothing I can do about this, unfortunately (known limitation) - but it will fix itself after restarting or toggling the quick menu.

**Comment by orbea** [comment]
Thanks, that works better!

**Comment by orbea** [comment]
Actually I am noticing one more thing, but its so minor that its maybe not worth fixing, especially if difficult.

I set the menu aspect ratio to `16:10` and the video aspect ratio to `Core Provided` and launched content which appeared correctly as `4:3`. However when I toggle quick menu it shows the content transparently in the background also stretched to `16:10` like the menu. This corrects itself as soon as I resume the content, but its looks kind of strange.

**Comment by jdgleaver** [comment]
@orbea Lovely - glad that's working now :slightly_smiling_face: 

> I set the menu aspect ratio to 16:10 and the video aspect ratio to Core Provided and launched content which appeared correctly as 4:3. However when I toggle quick menu it shows the content transparently in the background also stretched to 16:10 like the menu. This corrects itself as soon as I resume the content, but its looks kind of strange.

Yes, that's kinda annoying, but we're at the limit of what we can do with RGUI here. With XMB and Ozone, the menu is 'blended' with the current content in a nice consistent fashion (so the ratios are independent). With RGUI, it's a dumb 'shove it to screen', and we have to rely on whatever the gfx driver does internally.

It all comes back to `video_driver_set_texture_frame()` - if it behaved correctly, this wouldn't be an issue. (and again, 3DS is the only platform that does it right - i.e. both content and menu are always displayed correctly)

**Comment by orbea** [comment]
Yea, it would be good to improve that, but I totally understand that it would be a lot of work and testing all the video drivers would be very hard...the only possibility I see is to complete what is possible and slowly find people people to test the other video driers one by one before merging similar to how menu widgets was done.

I suppose the alternative is your `rgui-hd` idea? Potentially in the future it could replace the current rgui if its feature complete and doesn't have any obvious regressions?

**Comment by jdgleaver** [comment]
> Yea, it would be good to improve that, but I totally understand that it would be a lot of work and testing all the video drivers would be very hard...the only possibility I see is to complete what is possible and slowly find people people to test the other video driers one by one before merging similar to how menu widgets was done.

I would love to see this happen :slightly_smiling_face: 

It really is a huge undertaking, however - a daunting rewrite of heaps of fundamental code (I was kinda demoralised to see how knotted up all the internal settings are...). It needs some gfx driver experts. I'm a little scared to start picking this stuff apart...

> I suppose the alternative is your rgui-hd idea? Potentially in the future it could replace the current rgui if its feature complete and doesn't have any obvious regressions?

It could never replace RGUI, because as soon as we start using the 'regular' menu driver methods we loose compatibility with all the esoteric platforms (i.e. sometimes `video_driver_set_texture_frame()` is all we have access to).

But it could be a very nice lo-fi option for Windows/Linux/Android.

**Comment by bparker06** [comment]
This pull request **introduces 1 alert** when merging 8336163112efcc5005799284eec1474d608dc3e3 into 51af4330ebf40fdfb29f3dfde2c561267bd3a5c7 - [view on LGTM.com](https://lgtm.com/projects/g/libretro/RetroArch/rev/pr-fa09fbdd596320ee7ae93a051aa5697376016dd0)

**new alerts:**

* 1 for Multiplication result converted to larger type

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by orbea** [comment]
So it sounds like it would be better to improve `video_driver_set_texture_frame()` than to write a new menu driver? Getting help with gfx issues is hard unfortunately...

**Pull request merged**
