### PR TITLE
Shader Preset Simple Save & Load

### PR DESCRIPTION
**Pull request by HyperspaceMadness**
## Description

This PR addresses Simplifying the Presets which are saved by Retroarch so that if desired they only contain a reference to the original preset loaded and any parameter changes the user has made.  In short this will help keep per game/core presets manageable, and will prevent shaders from failing to load because you are loading an old preset and there is a discrepancy with what an updated shader now expects.

**The Problem:**
Currently when a preset is loaded then saved it saves a preset file with a #reference directive and a path to the original shader loaded. This preset saved is a referenced preset and the #reference directive points to a root shader preset. This is works great if you have not made any parameter changes in the preset.

If you save a preset after you have made some parameter changes an entire copy of the original preset is saved along with the changes, this creates a lot of redundancy which makes it hard to keep things updated after you have a number of presets saved. Also if the original shader preset is updated which requires new things the user saved presets do not have their presets will fail to load because they are missing resources.

**The Solution**
This PR adds a new "Save Simple Shader" entry into the Shaders/Save sub-menu which defaults to ON. 

When "Save Simple Preset" is ON a user loads a preset then saves it the file saved is exactly the same as what Retroarch saves now, an almost empty file with just the #reference directive and the path to the root preset. When the user makes parameter changes to a loaded shader then saves a preset Retroarch will save the reference and any parameters or textures which are different than the root preset.

When "Save Simple Preset" is OFF a full traditional preset will be saved. If a referenced preset cannot be saved (because it would refer to itself, or it is an auto-shader, etc, or there are structural changes, e.g. changing a pass) the saving will fall back to saving a full preset.

## Reviewers

@hizzlekizzle , @twinaphex , @jdgleaver 

Snapshot of the UI
image

Example of a simple preset saved using this feature
image

### CODE REVIEW

**Comment by bslenul** [comment]
Doesn't seem to work properly for me, tested with "crt-easymode.slangp":

* Load crt-easymode preset.
* Change the "Sharpness Horizontal" parameter from "0.50" to "0.45".
* Save core preset.
* Go back to shaders parameters and "Sharpness Horizontal" is back to its default value of "0.50" (even after closing content).

The .slangp file itself seems fine:
```
#reference "..\..\shaders\shaders_slang\crt\crt-easymode.slangp"
SHARPNESS_H = "0.450000"
parameters = ";SHARPNESS_H"
```
but it keeps loading the default value of "0.50".

**Comment by HyperspaceMadness** [comment]
Thanks for trying this out I'll check out your repro and see what's going on

**Comment by HyperspaceMadness** [comment]
Ok I looked into this, this happens whenever the original preset loaded has no "parameters" entry in it's preset file. As soon as there is a "parameters" entry it works fine. I'll fix this so it works in the case where there is no "parameters" entry

**Comment by HyperspaceMadness** [comment]
Closing because the PR wouldn't update so I closed it and created a new one

**Pull request closed without merging**
