### PR TITLE
Fix issue #6747 black bug

### PR DESCRIPTION
**Pull request by daliaetnano**
Description
Unload the Textures of thumbnail images in a thread when the video is threaded.

Related Issues
 #2791 XMB GUI lag and "black bug" for boxart and dynamic wallpaper
 #6747 XMB always stops displaying images with low-power/memory (rpi, Switch, Classic, others)

### CODE REVIEW

**Comment by markwkidd** [comment]
This was tested by @natinusala on Switch. natinusula found that this patch does fix the issue.

**Comment by twinaphex** [comment]
I'm sorry but I have to revert this.

We spent an entire day fixing threaded video issues on Windows today, and now after merging this PR, it crashes again when toggling Threaded Video with the GL driver.

So I have to revert this.

If @daliaetnano can get it working with threaded video and if toggling threaded video and toggling fullscreen no longer crashes, I can merge any new PR he has.

**Comment by daliaetnano** [comment]
Hi @twinaphex 
No problem.
I will have a look at it this weekend to find what's wrong.
Those driver issues are really painfull to fix but I don't give-up.

**Comment by twinaphex** [comment]
Thanks, I really appreciate the persistence. Thanks for all your efforts so far.

I hope we can get to the finish line with this stuff.

**Comment by daliaetnano** [comment]
Hi @twinaphex 
I know why my fix does not work when we switch the driver threaded mode.
When xmb_context_destroy is called, the texture are unloaded with a threaded mode different to the one used to load the texture.

Here is a typical exemple describing the problem:

1. Retroarch starts with video_threaded=false
2. All texture **loaded** in the **retroarch thread**
3. Switch Video Threaded to true
4. xmb_context_destroy is called 
5. All texture **unloaded** in the **video thread** ===> crash

All texture should be loaded and unloaded in the same thread.
If I comment all the unloading stuff in xmb_context_destroy, it works fine.

I don't know how to fix this issue.
The setting of the threaded mode is done in a task queue. It seems strange.
Any idea to fix this issue ?

**Pull request merged**
