### PR TITLE
Log to file

### PR DESCRIPTION
**Pull request by fr500**
This allows setting logging to file via config.
Should ease the "generating logs conundrum"

I implemented default locations for windows and android. Other port mantainers should do the same for other platforms.

~~I still haven't tested on android so this is still a draft.~~ 
works fine, logs to `sdcard/RetroArch/logs/`

Won't do:
- other platforms
- menu entries... sorry but it's just too much work. As is this will make logging to file a default on android (once verbosity is enabled)

### CODE REVIEW

**Comment by jdgleaver** [comment]
This is really nice (and a godsend on Android), but AFAIK it's impossible to disable logging verbosity on Android (at least, the setting is on by default and always ignored on all my devices). So maybe it's not so good to enable logging to file by default on Android? (i.e. it forces both a performance hit and flash storage wear on the user)

**Comment by fr500** [comment]
I'll see why is it always enabled then

**Comment by fr500** [comment]
should be fixed now

**Comment by jdgleaver** [comment]
@fr500 You are truly a scholar and a gentleman.

**Comment by fr500** [comment]
LOL!
Haven't tested yet, I'm at work but builds here:
https://bot.libretro.com/.radius/retroarch-release.apk

**Comment by ofry** [comment]
@fr500 This PR has merge conflicts.

**Comment by fr500** [comment]
Done

**Comment by twinaphex** [comment]
It cannot log to file by default though, that would be wasteful file I/O. Logging to file has to be optional.

Also, didn't @jdgleaver already implement something similar to this to allow for logging to file? I'd like some clarification on this.

**Comment by jdgleaver** [comment]
@twinaphex This PR deals with logging system messages (`RARCH_LOG()`,`RARCH_ERR()`etc.) to file - my logging stuff is for runtime, so quite different.

I agree that this system logging should be off by default on all platforms. This PR currently requires the 'log to file' option to be set by hand in the config file. If @fr500 doesn't want to do it, I could wire up the `settings->bools.log_to_file` menu entry later (I've added so many options now, it's become routine...)

**Comment by fr500** [comment]
Sorry about being lazy but it's what it is, working on RA is not a priority for me nowadays.

I don't think changing log to file to on or off should be a blocker for the PR, it's just a matter of opinions, and even if it was on by default verbose logging is NOT so it's not like it will do any considerable I/O.

**Pull request merged**
