### PR TITLE
(Qt) Refactoring the QString constructing

### PR DESCRIPTION
**Pull request by viachaslavic**
Minor updates to #17167 to avoid unnecessary conditional compilation by avoiding implicit conversions.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi there, our buildbot is currently failing to build after merging the Qt PR .

See the errors here -

**Comment by LibretroAdmin** [comment]
Pushed this, let me know if this is fine -

https://github.com/libretro/RetroArch/commit/adcf146e7d7bab3710605ce8611f2b3475f816c7

**Comment by viachaslavic** [comment]
My omission, I apologize. I was thinking to hold off on #17167 a little longer, just to test it on a very old environment.

**Comment by LibretroAdmin** [comment]
Alright, give it a test on that old environment. We just need to make sure it keeps working fine on Qt 5.

**Comment by LibretroAdmin** [comment]
It works weird now. When I click on any of the icons it also clicks in the RetroArch window. So it is not correctly unfocusing the main RetroArch window.

So this needs some Qt 5 fixes quick.

**Pull request merged**
