### PR TITLE
Add generic rumble gain to input settings

### PR DESCRIPTION
**Pull request by davidgfnet**
Keep default at 100% for compatibility.
This (in theory) superseeds the dingux gain control.

### CODE REVIEW

**Comment by davidgfnet** [comment]
I'd like @jdgleaver to review this please. Since I'm deleting some dingux code, and I'm not sure it's the right thing to do :) 
Thanks!

**Comment by twinaphex** [comment]
Of course, we'll await his feedback on this one before doing anything.

**Comment by twinaphex** [comment]
@davidgfnet @jdgleaver When the buildbot work slows down, we can resume looking at this again.

**Comment by davidgfnet** [comment]
Dingux support still WIP, currently broken.
I'm not sure how to proceed since Dingux rumble requires a restart due to broken driver.
An option could be: ignore any set_rumble for dingux but store the setting value, that would mean that, after a restart the value is picked up.
Also I'm gonna need to test this a bit more, since I currently don't have a udev rumble device (for some reason my chinese Xiaomi bluetooth gamepad does not support FF??? I know, wtf right?)

**Comment by gouchi** [comment]
I tried this patch with this [test core](https://github.com/libretro/libretro-samples/tree/master/tests/test) and in game and rumble is working with udev.

**Comment by twinaphex** [comment]
Hi there @davidgfnet , my bad for neglecting this for so long. We should definitely try to rebase this PR. Could you take a look at it?

**Comment by iancharnas** [comment]
@davidgfnet I have been working on this as well (I've been speaking with @gouchi and @DisasterMo on discord)

Two things:

1. I am using this controller and it's been reliable. Are you in the US? Perhaps I can send you mine for a while. They are super cheap though so maybe you'd want to pick one up to keep: https://www.pdp.com/pdp-wired-controller-048-082-na-rd

2. I believe I found an issue or bug in your code. If you look in udev_joypad.c in the udev_set_rumble_gain function, your code is expecting the "gain" parameter to be a 0-1 float. However what's being passed in is a 0-100 float. Also, I'm not sure if it's necessary but in the fftest code I used as an example they used memset to zero out the input_event struct before using it. I've made both changes in my version of the code here: https://github.com/iancharnas/RetroArch/blob/rumble/input/drivers_joypad/udev_joypad.c 

I hope this is helpful! Thank you all for working on this.

**Comment by davidgfnet** [comment]
Oh you can drop this. This was done in a hurry sorry!

**Comment by gouchi** [comment]
I think it is a nice feature so we should keep it.

**Comment by DisasterMo** [comment]
Well, for what it's worth, I'm currently working on this. My first attempt at rebasing didn't work out, so I'm looking through all changes to figure out the issue. This is my first time working on anything controller or even driver related, so this will take a while.

**Comment by markwkidd** [comment]
@davidgfnet would you mind closing this PR now? thank you and DisasterMo for your awesome work on this

**Pull request closed without merging**
