### PR TITLE
French: French translation update

### PR DESCRIPTION
**Pull request by WeedyWeedSmoker**
## Description

French translation update:

- (Ozone) Add option to sort playlists after name truncation
- Enable configuration of date separator in clock and runtime 'last played' displays
- Core updater improvements
- Update Downloader/Updater confusion
- Update MENU_ENUM_SUBLABEL_DOWNLOAD_CORE

## Related Pull Requests

https://github.com/libretro/RetroArch/pull/10498

## Reviewers

@twinaphex

### CODE REVIEW

**Comment by twinaphex** [comment]
Do these changes come from Crowdin?

**Comment by WeedyWeedSmoker** [comment]
@twinaphex I will add them to Crowdin as soon as @guoyunhe syncs the latest US file with Crowdin, but none of the changes here have been available there yet…

**Comment by guoyunhe** [comment]
@WeedyWeedSmoker I think the following strings should be disabled for translation:

Screenshot_2020-05-31 All Strings - RetroArch - Crowdin translation

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe You can leave them in, it's just that only one from each language will be actually used by Retroarch…

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe I think you should hide ALL the strings containing `_LANG_` in them…

**Comment by im4potato** [comment]
Hey guys, if you've been following any of my comments/issues lately you might have seen me say that I'm in the process of overhauling the US translation and I'm just about done with it. As far as I understand, the US translation is the only one still manually updated with a PR? Also, I'm trying to standardize the language across everything and make it more descriptive, and one of the changes I've made is changing anything that requires a restart to say `(Restart Required)`, not just `(Restart)`.

I'm not sure if anything I've done will interfere/conflict with what you're doing, just thought I'd make you aware that a big change should be coming (assuming it gets merged).

**Comment by WeedyWeedSmoker** [comment]
@im4potato Yeah, I was very tempted to put "(Restart Required)" instead of just "(Restart)" in my PR https://github.com/libretro/RetroArch/pull/10727

I'm all for unification, so yeah, "(Restart Required)" would indeed be more self-explanatory, and not so much harder to understand for non-english speakers anyway…

**Comment by im4potato** [comment]
I've been thinking more about this and a better solution might be to just put a note about some languages requiring a restart in the sub-label instead of putting them on each individual language. That would make some of the formatting more consistent.

**Comment by WeedyWeedSmoker** [comment]
@im4potato I have to disagree on that point, the sub-label might be hidden in some cases… This is kinda crucial information…

**Comment by im4potato** [comment]
That is true, however, sub-labels are turn on by default in all menu drivers, and there are already plenty of settings that rely on them to convey important information. So this would be no different than many other settings that already exist.

**Comment by twinaphex** [comment]
@WeedyWeedSmoker @guoyunhe is this ready to go now?

**Comment by WeedyWeedSmoker** [comment]
@twinaphex This PR is ready

**Pull request closed without merging**
