### PR TITLE
Add option to disable analog stick menu navigation

### LINKED ISSUE #16274: [Feature Request] Add an option to disable menu navigation using right analog
Two really useful options have been recently added under Settings > Input > Menu Controls:
“Disable Info Button” and “Disable Search Button”.
Would be possible to add also a “Disable menu navigation using right analog”?

As 90% of retro-games don’t uses right analog is very convenient to assign hotkey to it, but when you open/close the RA menu it start to scroll. Considering the menu scrolling is already assigned to D-pad and left Analog the usability of RA menu will bot be compromised disabling right analog.

### PR DESCRIPTION
**Pull request by zoltanvb**
## Description

Two new settings added to Settings / Input / Menu Control:
- disable left analog stick in menu navigation
- disable right analog stick in menu navigation

Since the logic for menu control by analog stick is already a distinct flow in input driver.c, no change was necessary to analog-to-digital settings or other mappings. Defaults are false (i.e. all sticks control menu).

## Related Issues

Closes #16274 
May provide a workaround for #16644 

## Reviewers
@sonninnos

### CODE REVIEW

**Comment by sonninnos** [comment]
I was rather looking forward to complete customization and the removal of "disable" options instead of adding more, but that can be done later I guess.

**Comment by zoltanvb** [comment]
I was considering extending it, and I can still do it, if you consider it better. My line of thinking was:
- currently, only right analog stick removal was requested
- allowing the D-pad to be excluded from menu navigation can lock the user out immediately
So this is why 2 simple options were added. But I can swing either way, remove left analog stick exclusion (which was not asked so far) and leaving only 1 simple toggle for right analog, or do a combined option, with or without D-pad removal.

**Comment by sonninnos** [comment]
D-pad never needs to be customized or removed. I was referring to all other buttons.

**Comment by s3gfaultx** [comment]
Would it not be safe to just disable the right analog stick altogether and fore go the options? I'd consider myself a power user and until seeing this, I had no idea that the right analog stick even did anything at all.

**Comment by zoltanvb** [comment]
Ah, total customization, I get the point. That is indeed a bit more than what I was looking for, so I will not include it to this PR.

Right analog stick has been in the code since #14579 and it mentions a request, so I would also not remove it unconditionally.

From my side, PR is finalized.

**Comment by zoltanvb** [comment]
Ping. Any open concerns for this PR?

**Comment by illando** [comment]
@zoltanvb I think it will be a good idea to insert these option, meanwhile we are ready for a total customisation.
For people who are using R3 as Hotkey enable it would solve an annoying situation.
Thanks.

**Comment by illando** [comment]
@sonninnos @zoltanvb sorry guys but I don’t understand if these options should be already implemented.
I downloaded the latest nightly builds for Android and Mac and I can’t find the preferences in the menu:
`
IMG_5481
`

**Comment by sonninnos** [comment]
The PR needs to be merged first.

**Comment by illando** [comment]
@sonninnos sorry for the stupid question, but what’s the reason because it has not been merged?

**Comment by sonninnos** [comment]
Not up to me, and I have no new objections.

**Comment by illando** [comment]
@zoltanvb could you merge this one please?
It would be really nice to have these options.
Thanks!

**Pull request merged**
