### PR TITLE
Core Options: Add sublabels + localisation support

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This replaces PR #9082.

It adds support for the following:

- Core option sublabels

- Full localisation of core options.

It is implemented as follows:

We have the following new structs:

```c
struct retro_core_option_value
{
   /* Expected option value */
   const char *value;

   /* Human-readable value label. If NULL, value itself
    * will be displayed by the frontend */
   const char *label;
};

struct retro_core_option_definition
{
   /* Variable to query in RETRO_ENVIRONMENT_GET_VARIABLE. */
   const char *key;

   /* Human-readable core option description (used as menu label) */
   const char *desc;

   /* Human-readable core option information (used as menu sublabel) */
   const char *info;

   /* Array of retro_core_option_value structs, terminated by NULL */
   struct retro_core_option_value values[RETRO_NUM_CORE_OPTION_VALUES_MAX];
};

struct retro_core_options_intl
{
   /* Pointer to an array of retro_core_option_definition structs
    * - US English implementation
    * - Must point to a valid array */
   struct retro_core_option_definition *us;

   /* Pointer to an array of retro_core_option_definition structs
    * - Implementation for current frontend language
    * - May be NULL */
   struct retro_core_option_definition *local;
};
```

...and three new environment callbacks:

`RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION`
`RETRO_ENVIRONMENT_SET_CORE_OPTIONS`
`RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL`

At present, core options are set via an array of `retro_variable` structs:

`environ_cb(RETRO_ENVIRONMENT_SET_VARIABLES, struct retro_variable[]);`

This can still be used in any case, but if `RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION` returns `1` (the legacy path is version `0`) then core options may be set via one of two new methods:

- An array of `retro_core_option_definition` structs:

`environ_cb(RETRO_ENVIRONMENT_SET_CORE_OPTIONS, struct retro_core_option_definition[]);`

- A `retro_core_options_intl` struct:

`environ_cb(RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL, struct retro_core_options_intl);`

The latter of the two requires further explanation: The `retro_core_options_intl` struct contains pointers to two `retro_core_option_definition` arrays:

- `retro_core_options_intl::us`: This is a US English core options definition. It must always be provided, and forms the basis for all translations.

- `retro_core_options_intl::local`: This is a core options definition localised for the current frontend language (This is queried from the core side via `RETRO_ENVIRONMENT_GET_LANGUAGE` - note that we have to do this on the core side, otherwise we risk out of bounds array access if core and frontend have different versions of `libretro.h`). If it is `NULL`, then the US English version is used. If the localised version omits any option or option value included in the US English version, that option/value is again taken from the US English version (i.e. incomplete translations do no harm).

Here are some screenshots of localisation in action: (this is a google translate monstrosity, but you get the idea)

Screenshot_2019-07-11_15-59-27

Screenshot_2019-07-11_16-00-43

As before, [PokeMini PR #23](https://github.com/libretro/PokeMini/pull/23) serves as a reference for implementing this on the core side. In particular, the file [libretro_core_options.h](https://github.com/libretro/PokeMini/blob/a6dc2cf3bbd704d4b29531322a1e14fbdf1961c9/libretro/libretro_core_options.h) should be noted. It is intended that an equivalent `libretro_core_options.h` will be added to each core (in the same directory as `libretro.h`), and included in the core's `libretro.c`.

To use a `libretro_core_options.h` file, a core dev need only do the following:

1. Define a US English core options array:

```c
struct retro_core_option_definition option_defs_us[] = {
   {
      "option_key",
      "option_description (menu label)",
      "option_info (menu sublabel)",
      {
         { "value_1", "value_1_label (displayed in menu)" },
         { "value_2", "value_2_label (displayed in menu)" },
         { NULL, NULL },
      }
   },
   { NULL, NULL, NULL, {{0}} },
}
```
Note that `option_info` may be `NULL`.
Note that value labels may be `NULL` (in which case the value itself is displayed in menus)

2. Optionally define core options arrays for any other languages:

```c
struct retro_core_option_definition option_defs_fr[] = {
   {
      "option_key",
      "option_description_fr (menu label)",
      "option_info_fr (menu sublabel)",
      {
         { "value_1", "value_1_label_fr (displayed in menu)" },
         { "value_2", "value_2_label_fr (displayed in menu)" },
         { NULL, NULL },
      }
   },
   { NULL, NULL, NULL, {{0}} },
}
```

Note: For values that do not require translating (e.g. numbers, `enabled`/`disabled`) the value entries may be omitted (provided that the terminating `{ NULL, NULL }` exists)

3. Wire up all supported languages in an `option_defs_intl` map array:

```c
struct retro_core_option_definition *option_defs_intl[RETRO_LANGUAGE_LAST] = {
   option_defs_us, /* RETRO_LANGUAGE_ENGLISH */
   NULL,           /* RETRO_LANGUAGE_JAPANESE */
   option_defs_fr, /* RETRO_LANGUAGE_FRENCH */
   NULL,           /* RETRO_LANGUAGE_SPANISH */
   NULL,           /* RETRO_LANGUAGE_GERMAN */
   NULL,           /* RETRO_LANGUAGE_ITALIAN */
   NULL,           /* RETRO_LANGUAGE_DUTCH */
   NULL,           /* RETRO_LANGUAGE_PORTUGUESE_BRAZIL */
   NULL,           /* RETRO_LANGUAGE_PORTUGUESE_PORTUGAL */
   NULL,           /* RETRO_LANGUAGE_RUSSIAN */
   NULL,           /* RETRO_LANGUAGE_KOREAN */
   NULL,           /* RETRO_LANGUAGE_CHINESE_TRADITIONAL */
   NULL,           /* RETRO_LANGUAGE_CHINESE_SIMPLIFIED */
   NULL,           /* RETRO_LANGUAGE_ESPERANTO */
   NULL,           /* RETRO_LANGUAGE_POLISH */
   NULL,           /* RETRO_LANGUAGE_VIETNAMESE */
   NULL,           /* RETRO_LANGUAGE_ARABIC */
   NULL,           /* RETRO_LANGUAGE_GREEK */
   NULL,           /* RETRO_LANGUAGE_TURKISH */
};
```

4. Replace any existing core options configuration inside `retro_set_environment()` with a simple call of the `libretro_set_core_options()` function defined in the reference `libretro_core_options.h` file.

(Note: Core devs are of course free to implement this however they want, but using the `libretro_core_options.h` from the `PokeMini` PR makes everything rather trivial)

----------

**An important note about APIs:**

Many good suggestions were made in the comments thread of PR #9082 regarding additions and enhancements to the core options interface. However: after much deliberation, a group consensus was reached that backwards compatibility and stability are the order of the day. To that end, two strict guidelines are enforced:

- Whatever format the new `retro_core_option_definition` struct takes, it must be possible to convert it's contents into a `retro_variable` with no loss of functionality

- Cores must continue to access core option values via the existing `retro_variable` interface

Failure to observe this would mean that core devs would be obliged to maintain two separate code paths when dealing with core options. This is entirely unacceptable:

- It invites errors and oversights when core options are added/changed

- It requires core devs to test their work with at least two different frontends (i.e. one that supports the new interface, and one that does not)

- If core devs have to implement a working solution using the existing `retro_variable` interface anyway, then they cannot take advantage of any new API features in any meaningful fashion

This PR therefore remains minimally invasive, with no backwards/forwards compatibility issues - nor does it place any significant maintenance burden on core devs.

The cool ideas mentioned in the comments thread of PR #9082 will be considered for a future overhaul of the core options interface, but this will be deferred until libretro API v2.0 (i.e. not any time soon!)

This is not open for discussion  :)

## Related Issues

This seems to address https://github.com/libretro/libretro-common/issues/35

## Reviewers

Again, I would be grateful if @twinaphex and @bparker06 could review the changes before they are merged.

### CODE REVIEW

**Comment by RobLoach** [comment]
Sublabels for core options are a great idea! Localisation is fantastic too. Nice work! Will be able to test in 6 hours.

**Comment by jdgleaver** [comment]
@RobLoach Thanks! All testing is very welcome  ;)

**Comment by orbea** [comment]
Will there be any compatibility issues if the frontend and core advertise different number or order or languages? Over time these things could change and not all frontends should be expected to support the exact same languages.

**Comment by twinaphex** [comment]
See the Travis CI checks, CXX_BUILD is broken -

https://travis-ci.org/libretro/RetroArch/jobs/557418727

**Comment by RobLoach** [comment]
Tested by adding [Core Option Sublabels to ChaiLove](https://github.com/libretro/libretro-chailove/pull/369). Worked well! You can see a screenshot of it at https://github.com/libretro/libretro-chailove/pull/369

I then tried to run it in [Ludo](https://github.com/libretro/ludo), which doesn't implement the new API, and got the following error:
```
➜  ludo git:(master) ./ludo -L ~/libretro-chailove/chailove_libretro.so ~/libretro-chailove/examples/bunnymark/main.chai
[ChaiLove] Initializing ChaiLove
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/libretro/ludo/libretro.(*Variable).Choices(0xc421abda48, 0xc4220ab540, 0x16, 0x1)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:111 +0xc8
github.com/libretro/ludo/core.environmentGetVariable(0x7ffc419bfc50, 0x50)
	/home/rob/.gocode/src/github.com/libretro/ludo/core/environment.go:37 +0xe0
github.com/libretro/ludo/core.environment(0xc40000000f, 0x7ffc419bfc50, 0x7c7280)
	/home/rob/.gocode/src/github.com/libretro/ludo/core/environment.go:87 +0x12b
github.com/libretro/ludo/libretro.coreEnvironment(0xc40000000f, 0x7ffc419bfc50, 0x86e100)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:483 +0x3f
github.com/libretro/ludo/libretro._cgoexpwrap_0624a055ae0e_coreEnvironment(0xffffffff0000000f, 0x7ffc419bfc50, 0xffffffffffffffff)
	_cgo_gotypes.go:668 +0x33
github.com/libretro/ludo/libretro._Cfunc_bridge_retro_load_game(0x7fce72ddad70, 0xc420127200, 0xc42009b200)
	_cgo_gotypes.go:416 +0x4a
github.com/libretro/ludo/libretro.(*Core).LoadGame.func1(0x7fce72ddad70, 0xc420127200, 0x92c7e30)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:380 +0xd7
github.com/libretro/ludo/libretro.(*Core).LoadGame(0xc4247b2000, 0x7ffc419c0ff4, 0x42, 0xddc, 0x0, 0x0)
	/home/rob/.gocode/src/github.com/libretro/ludo/libretro/libretro.go:380 +0xa1
github.com/libretro/ludo/core.LoadGame(0x7ffc419c0ff4, 0x42, 0x0, 0x0)
	/home/rob/.gocode/src/github.com/libretro/ludo/core/core.go:143 +0x115
main.main()
	/home/rob/.gocode/src/github.com/libretro/ludo/main.go:115 +0x56c
```

**Comment by jdgleaver** [comment]
@twinaphex Damn! I neglected to cast the output from one of the `calloc()`s. Silly trivial error. I've just pushed a commit that fixes this.

@orbea The language selection is 100% consistent with the existing libretro API. If a frontend obeys the API (as it stands without this PR) then it's not possible for there to be compatibility issues. If a frontend does not support a particular language then the core will provide US English. Likewise, if a frontend does not support core options v1, the core will always provide US English. And of course - if a frontend supports a language that the core doesn't, the core will again provide US English.  :)

@RobLoach Great, thanks for testing! This Ludo error is a puzzle... I of course verified that these changes are compatible with old versions of RetroArch - i.e. everything works correctly with my updated PokeMini core (with sublabels) when using the current RetroArch `master`. So this would suggest that Ludo is doing something out of spec. Let me check the Ludo source code...

**Comment by jdgleaver** [comment]
@RobLoach Right, the crash is a result of Ludo playing fast and loose with the API..

Basically, it's just storing a pointer to the array of `retro_variable`s passed to `RETRO_ENVIRONMENT_SET_VARIABLES`. This is not good. Nowhere in the spec does it say that anything passed to `RETRO_ENVIRONMENT_SET_VARIABLES` is persistent - the values should be parsed/cached by the frontend when the callback is called, not at some arbitrary point in the future.

The current `libretro_core_options.h` only creates a temporary `retro_variable` in the event that core options v1 is not supported - so of course, when Ludo tries to extract the variables long after the core has been loaded, there's nothing there.

This absolutely sucks. We can implement a workaround by keeping a copy of the temporary `retro_variable`s array and `free()`ing it in `retro_deinit()`, but this is ugly and crass.

@twinaphex Could you please give some input here? Should we implement workarounds for frontends that don't behave correctly? I'm kinda guessing that we might have to, since who knows what jiggery-pokery other frontends are getting up to...

**Side Note:** This issue actually has no bearing at all on this PR, thankfully. The 'problem' is purely on the core side, and the workaround is easy peasy (it's just the ugliness that I don't like...)

**Comment by twinaphex** [comment]
I'd say Ludo needs to be fixed then. If older versions of RetroArch don't crash then it stands to reason that the frontend that does crash on this is simply not following spec correctly.

**Comment by twinaphex** [comment]
I believe this is the most mileage we can get out of the current API while still having a nicer core options interface. @jdgleaver will be following this up with some other PRs that will further improve core options without breaking ABI. On that note, let's merge this. A more ambitious core options can be considered for the future API bump but was outside the scope for the current libretro API.

**Comment by RobLoach** [comment]
Thanks! Excited to see this in. 1.7.8 is looking pretty awesome! Made an issue in the Ludo queue about cleaning up the Variable API usage: https://github.com/libretro/ludo/issues/212

**Comment by kivutar** [comment]
> @RobLoach Right, the crash is a result of Ludo playing fast and loose with the API..
> 
> Basically, it's just storing a pointer to the array of retro_variables passed to RETRO_ENVIRONMENT_SET_VARIABLES. This is not good. Nowhere in the spec does it say that anything passed to RETRO_ENVIRONMENT_SET_VARIABLES is persistent - the values should be parsed/cached by the frontend when the callback is called, not at some arbitrary point in the future.

The code is here https://github.com/libretro/ludo/blob/master/core/environment.go#L86-L92

and this line `Options = options.New(libretro.GetVariables(data))` is supposed to cache the variables.

**Comment by kivutar** [comment]
Found a fix, thanks for the hints

**Pull request merged**
