### PR TITLE
Fixed the way devices were previously indexed

### PR DESCRIPTION
**Pull request by dyllan500**
## Description

Input devices were only being index in order and will stop at the first time an input has no device connected to it. The problem is when a device gets disconnected that input will have no devices connected to it, but the next input may still have a device connected. So, that makes changing the port of the currently connected devices impossible.

## Related Issues

https://github.com/libretro/RetroArch/issues/14524

### CODE REVIEW

**Comment by dyllan500** [comment]
Okay, I was able to build on Linux. I will try UWP tomorrow.

**Comment by dyllan500** [comment]
My latest commit should fix the error. I realized I forgot to initialize the variable wish the Linux compiler would've reminded me of that.

**Comment by hizzlekizzle** [comment]
As a general note, thanks for the contribution! It's always appreciated when someone recognizes a problem, reports it and then submits a fix for it. That's what keeps open source software alive.

**Comment by LibretroAdmin** [comment]
Make sure variables are always declared at the start of a code block or function right now. This PR broke C89 compliance which is an issue for older MSVC compilers. I will fix this manually but try to keep this in mind next time. There is also a file called CODING-GUIDELINES which goes over most of our coding rules.

**Comment by dyllan500** [comment]
Sorry small mistake, I will be sure to be more careful next time. I never compiled a program for C89 before, forgot how strict older compilers can be.

**Comment by sonninnos** [comment]
I'm getting new harmless warnings after this PR:
```
menu/menu_displaylist.c: In function 'menu_displaylist_parse_input_device_index_list':
menu/menu_displaylist.c:5176:16: warning: variable 'val_na' set but not used [-Wunused-but-set-variable]
 5176 |    const char *val_na           = NULL;
      |                ^~~~~~
menu/menu_displaylist.c:5175:16: warning: variable 'val_port' set but not used [-Wunused-but-set-variable]
 5175 |    const char *val_port         = NULL;
      |                ^~~~~~~~
```

**Comment by LibretroAdmin** [comment]
Fixed the unused variable warnings.

**Pull request merged**
