### PR TITLE
(Android) Ask for external sdcard permission

### PR DESCRIPTION
**Pull request by Aaahh**
Permission has to be explicitly asked for or it won't be granted on api 23 or higher.

Didn't test this either

### CODE REVIEW

**Comment by Aaahh** [comment]
should solve https://github.com/libretro/RetroArch/issues/4150 and https://github.com/libretro/RetroArch/issues/3945

**Comment by twinaphex** [comment]
@Aaahh is this still backwards compatible with prior Android versions? Guess I'll soon learn.

**Comment by Aaahh** [comment]
lol, I'll test it now. I added the Api check which should cover it

**Comment by fr500** [comment]
Nice, I had this implemented but it would fail to build even though it was copy pasted code from samples

**Comment by Aaahh** [comment]
Trick was that to use open source android rather than contextcompact google support package that wasn't imported

**Comment by twinaphex** [comment]
@Aaahh We have serious doubts whether this even compiled, it certainly doesn't on our buildbot. So we are rolling it back for now.

**Comment by Aaahh** [comment]
Yeah I noticed it was broken, i need to setup the build enviroment so i can actually test the stuff, sorry ive been busy

**Comment by twinaphex** [comment]
OK, hopefully you can come up with another pull request that will build and work, and we can merge it then in preparation for the upcoming 1.4.0 release.

**Pull request merged**
