### PR TITLE
Fix emscripten build

### PR DESCRIPTION
**Pull request by Yogarine**
This fixes Emscripten build for me. Tested it with a couple of games and cores and seems to work ok.

### CODE REVIEW

**Comment by twinaphex** [comment]
Thanks a lot for this.

**Comment by twinaphex** [comment]
@Yogarine - Input still doesn't work for us. Any idea what is wrong?

Last time around we had the very same issue.

**Comment by Yogarine** [comment]
Input seems to work just fine in games, just not in the rgui. (I directly load the games with an argument, bypassing the gui)

I'll take a look at library_rwebinput some point this week.

**Comment by twinaphex** [comment]
Thanks for wanting to look into it.

**Pull request merged**
