### PR TITLE
Also fix the video filter selection.

### PR DESCRIPTION
**Pull request by orbea**
## Description

One more case...

## Related Pull Requests

https://github.com/libretro/RetroArch/pull/8599

## Reviewers

@bparker06

### CODE REVIEW

**Comment by bparker06** [comment]
I tested the video filters and it worked without this for me. What about you?

**Comment by orbea** [comment]
You need to navigate to the root directory (`/`) before it breaks, this was the same for the audio DSP plugins.

**Comment by bparker06** [comment]
I did but it still worked for me /shrug

**Comment by orbea** [comment]
I tried again with a build before this PR and was still able to reproduce it.

Here are some steps I took to reproduce this.

1. The video filter directory is configured to `/usr/lib64/retroarch/filter/video`.
2. Navigating to to this directory in the video setting works.
3. From here navigate to the root directory (`/`) and do not press the back button at any time.
4. After reaching `/` continue to `/usr/lib64/retroarch/filter/video` where it shows `No items`.

**Pull request merged**
