### PR TITLE
Add Italian messages

### PR DESCRIPTION
**Pull request by Ezio-PS**

### CODE REVIEW

**Comment by Alcaro** [comment]
+1, but I recommend adding `extern const char force_iso_8859_1[sizeof("äÄöÖßüÜ")==7+1 ? 1 : -1];` to ensure nothing stupid happens in the future. (It won't break anything if present in multiple files, it's fine to have multiple extern declarations of the same variable.)

**Comment by Ezio-PS** [comment]
Thanks for the tip, but i noticed it's not in the other header files such as french.h or spanish.h, so i thought i didn't need to add it.
In my case i should just add  `extern const char force_iso_8859_1[sizeof("àèéìòù")==6+1 ? 1 : -1];` since umlaut is only for german language. ;)

Let me see if @twinaphex agrees about adding it.

**Comment by Alcaro** [comment]
Doesn't really matter how many funky characters you add, as long as there's at least one.

And it should be added to all encoding-sensitive files. I'll go fix the other headers.

**Comment by Ezio-PS** [comment]
Ok, i understood, i'll add it.

**Pull request merged**
