### PR TITLE
Add MOD/S3M/XM support to audio mixer (libretro-common) through micromod/ibxm

### PR DESCRIPTION
**Pull request by rtissera**
This PR adds the audio mixer the capability of playing module files.
So far MOD/S3M/XM are supported thanks to the tiny, self-contained ibxm library.

This PR still needs a bit of love to get the MOD/S3M/XM file extensions properly registered into RetroArch GUI.

### CODE REVIEW

**Comment by twinaphex** [comment]
@rtissera One drawback I can notice so far with the MOD sound support is that it doesn't actually mix the MOD sound together with the game/core's audio, it instead silences the sound of the core entirely.

We can't have it properly mix with the sound of the game/core just like what was done for Wave and Ogg Vorbis?

**Comment by rtissera** [comment]
@twinaphex I can't see why it is not doable, probably a misunderstanding from my side.
Let me have a look to implement the proper behaviour.

**Comment by rtissera** [comment]
PR https://github.com/libretro/RetroArch/pull/5267 should fix this.

**Comment by frranck** [comment]
Salut @rtissera 
I have a problem trying to integrate some mod playing in that game:
https://github.com/Javanaise/mrboom-libretro/issues/36
Could you please help me on that ?

**Pull request merged**
