### PR TITLE
(RGUI) Add menu sublabel support

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new `Show menu sublabels` option to the `User Interface > Views` menu when using RGUI. When this is enabled, the space currently reserved for printing the core name is used to display the sublabel for the currently selected entry (if the entry has no sublabel then it falls back to the core name).

screenshot_2019-02-11_12-44-22

This is quite handy when using subsystems or configuring input remaps, since these rely on sublabel text that is currently hacked on to the end of the relevant entry (we still do this when sublabels are disabled, but turning them on makes things a little tidier):

screenshot_2019-02-11_12-42-21

screenshot_2019-02-11_12-43-42

I've also added sublabels for all the RGUI-specific menu options (which previously didn't have them, because they couldn't be seen...)

NOTE: It is currently painful to read long sublabels due to the S-L-O-W scroll speed of ticker text. I'll make the scroll speed configurable in a future PR later in the week.

### CODE REVIEW

**Comment by fr500** [comment]
how do network lobbies look like (multiline sublabels)

**Comment by hhromic** [comment]
@jdgleaver  great! this is really a great usability improvement! \o/

> (if the entry has no sublabel then it falls back to the core name).

Wouldn't it be better to keep it blank on these cases instead?  After enabling the show sublabel option, I would expect that area to always show the sublabel, even if there is none. Falling back to the core name could create confusion as it would look like the core name is a sublabel of whatever is selected, no?

**Comment by jdgleaver** [comment]
> how do network lobbies look like (multiline sublabels)

`'\n'` is rendered as a space, so the sublabel just becomes one long line (it's quite readable though - or it will be once I enable a faster scroll speed... :wink: )

> Wouldn't it be better to keep it blank on these cases instead? After enabling the show sublabel option, I would expect that area to always show the sublabel, even if there is none. Falling back to the core name could create confusion as it would look like the core name is a sublabel of whatever is selected, no?

Hmm... That's a good point...

I'm not sure, though - you can already turn the core name off via the `User Interface > Views` menu (which would produce the behaviour you suggest), and there are circumstances where having the core name on entries without sublabels is quite nice: for example, I like seeing which core I currently have loaded when browsing playlists on the 3DS.

I think we need a straw poll on what the default settings should be!

**Comment by orbea** [comment]
> I'm not sure, though - you can already turn the core name off via the User Interface > Views menu (which would produce the behaviour you suggest), and there are circumstances where having the core name on entries without sublabels is quite nice: for example, I like seeing which core I currently have loaded when browsing playlists on the 3DS.

If its already configurable then it seems fine as is?

**Comment by hhromic** [comment]
> you can already turn the core name off via the `User Interface > Views` menu (which would produce the behaviour you suggest)

What is *not* configurable in RetroArch? :D  Yes I think that would do it then. Kudos!

**Pull request merged**
