### PR TITLE
(Menu) Clarify the BIOS Missing/Present screen

### PR DESCRIPTION
**Pull request by RobLoach**
This aims to clean up the user interface around the BIOS checks on the Core Information screen.

## Changes
- Replaces the `(!)` for every entry with `[-]` or `[+]` depending on if the bios file was found.
- Moves the name of the bios file first, so that it's easier to know what entry is being considered

## Before

You'll find the text prior to the name make it difficult to parse whether or not the given bios files are there.

screenshot at 2019-01-05 19-25-59

## After

Making the critical information up front makes it easier to understand which files are missing or not.

screenshot at 2018-09-25 00-01-23

## References
- #6514

## Next Steps

Would love some thoughts on this. Tested out using `☐ ☑ ☒`, but the UTF-8 characters don't work in RGUI. Would like to keep them the same for simplicity.

### CODE REVIEW

**Comment by fr500** [comment]
lol, justt FYI when I first made this thing, it was like that (used [x],
then lasers made it like it is now)

**Comment by RobLoach** [comment]
Would be okay with `( )` and `(!)` but I don't think people really understand what it means. `[ ]` for missing, and `[*]` for present makes sense. I'm open to other representations.

**Comment by alfrix** [comment]
Can it be two characters? like
(Ok) and (!!)
I think that would be pretty clear

**Comment by RobLoach** [comment]
When using two characters, the alignment gets off quite a bit. Updated to `[+]` and `[-]`...

screenshot at 2019-01-05 19-07-12

**Comment by RobLoach** [comment]
Should we consider rgui too? Rgui isn't available there.

**Comment by RobLoach** [comment]
Closing for now.

**Pull request closed without merging**
