### PR TITLE
Support for AppleTV (tvOS)

### PR DESCRIPTION
**Pull request by yoshisuga**
- add tvOS target
    - support code signing tvOS cores by adding an argument to the code signing cores script
    - use NSCachesDirectory for the documents directory
    - add some mfi controller handling logic to set non-game controllers to the last index to avoid interfering with operation
    - autodetect mfi controller for apple tv on startup - added autodetect to hid joypad
    - added a webserver to transfer files for tvOS
    - xcode: clean up project, remove unused folders
    - remove HAVE_MATERIALUI setting for tvos build, make it use XMB as default
    - added retroarch app icon courtesy of @MrJs
    - a ton of "#if"s to support tvOS

For issue #5519 

## Reviewers

@stuartcarnie

### CODE REVIEW

**Comment by yoshisuga** [comment]
I'll need to submit more PRs individual cores to build using the tvOS SDK. So far I've tried the FCEUMM, genesis_plus_gx and mednafen_psx cores and they work great.

**Comment by twinaphex** [comment]
Cool!

**Comment by twinaphex** [comment]
Are all those GDCWebServer/WebUploader files necessary?

**Comment by orbea** [comment]
This is also currently breaking xcode with travis.

**Comment by yoshisuga** [comment]
It does add a bit of code, but it was a quick fix to allow some way to
transfer files to the AppleTV, as there's really no other way :(

**Comment by yoshisuga** [comment]
Not sure what the problem is with travis but i can try to take a look.

**Comment by twinaphex** [comment]
@yoshisuga OK, I guess we can make an exception for that.

**Comment by ScarAce1989** [comment]
Please add SMB or FTP support like Infuse. I want to serve my ROMs using my NAS.

**Comment by yoshisuga** [comment]
Ok found the issue and looks like the travis build was successful - thanks for setting up travis for this, super helpful 👍

**Comment by ScarAce1989** [comment]
Nice progress. Any help installing on my Apple TV 4k?

**Comment by mrjschulte** [comment]
Pretty straight forward to build/install. Follow the Instructions tat are on the doc site except there’s no need to manuall sign cores, Xcode will do this building to the device. Use libretro-super to pull all the cores in and build w the iOS-arm64 script. Pull end up with abou 43 working cores. 
As @yoshisuga mentioned, the iOS arm64 cores appear to work with the tvOS build. Once built just move them to the modules dir in the apple/tvOS subdirectory and then build to your device with Xcode.

**Comment by ScarAce1989** [comment]
git clone https://github.com/libretro/RetroArch.git retroarch
cd retroarch
git clone https://github.com/libretro/libretro-super
cd libretro-super
./libretro-fetch.sh

Now I have a folder 'retroarch' with about 15Gb of data.
Not sure what to do next?

**Comment by yoshisuga** [comment]
I wrote up an install guide for iOS and tvOS here:

https://docs.libretro.com/guides/install-ios/

**Comment by ScarAce1989** [comment]
Okay I got it installed. I don’t have a MFi controller. Is it possible to connect a DS4 controller? If not, I will buy a SteelSeries Nimbus.

First it needs to have NFS or SMB support, so I can use my NAS to serve the ROMs. Any ETA on that?

**Comment by ScarAce1989** [comment]
Bought a Nimbus.

I just follow the install guide, but if I want to play, all I got is ‘Failed to open libretro core’.

Any idea how to fix this? I already re-installed it three times, but no luck.

**Comment by aaronouthier** [comment]
Works just fine for me.
ScarAce, try moving/archiving/deleting the source you downloaded already, and re-pulling the source from scratch. Then, recompile, and reload. Also, it might help to say with what hardware you are working. Perhaps it is an isolated issue affecting only certain scenarios.

What Apple TV Version, tvOS, Mac Product, and macOS version are you using? Also, what Xcode? Do you have troubles when using the device simulators in Xcode?

**Comment by aaronouthier** [comment]
ScarAce, I just reread your message. Did you compile or include any pre-built cores?
I'm thinking not, and this is probably why you can't play any games.
Check Here:
https://docs.libretro.com/guides/install-ios/#download-the-emulator-cores

**Pull request merged**
