### PR TITLE
Major improvements to the video processor core

### PR DESCRIPTION
**Pull request by AdrianoML**
## Description

Includes several improvements such as handling different capture modes (alternate fields, interlaced frames, top or botton fields and the one of a kind "alternate_hack".

Allows for captured fields or frames to be output as a progressive signal or deinterlaced, with special care taken for lower latency output in case your capture card supports the alternate fields mode (or my alternate_hack works).

By capturing alternate fields on NTSC video you may output a progressive signal at 16ms or deinterlace a interlaced signal at 16ms without waiting for the next field or having to wait for a full frame containing both fields (which would ensure a delay of 33ms) as many capture software do.

The alternate_hack is a way to allow cards (or drivers) that have no alternate fields capture mode and therefore would be restricted to interlaced capture (forcing a 33ms latency) to still be able to reach a low latency by capturing discrete bottom and top fields by the means of quickly shutting off capture and starting it again with a different field specified. There are many caveats to this approach, it may or may not work, use at your own risk.

A dummy mode has been created for testing the core even without a capture card, select it by changing the video device in the options menu.

A frame time analysis output has been added, you can activate it in the options menu. May help with troubleshooting.

A freewheeling issue with capture cards that have no audio devices (including dummy mode) has been corrected.

XRGB8888 has been set as the standard retroarch output buffer

A really crappy de-interlacing filter has been added. I'm hoping for multiple selectable filters to be implemented in the future, just as I'm also hoping to implement multiple capture format encoding convertors (My card only worked correctly with BRG24 capture, so the original RGB565 has been discarded temporarily..)

## Outstanding Issues
Listing and identification of compatible capture formats needs to be implemented.
Implement a bunch of capture format convertors (only BGR24 to XRGB8888 for now)
A way to change capture width and height needs to be implemented.

## Features I intend to do eventually™
Get a list of video standards and allow user to select one
Get a list of video inputs and allow user to select one
Get a list of available video controls (brightness, saturation, etc..) and generate a list of allowed video controls and allow user to modify such controls
Implement decent de-interlacing filters.
Progressive captures (such as alternate mode) with Interlaced output has not been implemented yet (is this even useful?)

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Holy shit, that all sounds amazing :O

**Comment by twinaphex** [comment]
Hi there @AdrianoML , this is awesome to see especially as we were really lacking in somebody to continue pushing this core forward. So thanks a lot for that!

The only thing that I would like some clarification on though is the audio. Is audio completely stubbed out? I see an early return in the audio callback function. Or is this a misunderstanding on my end? if it is stubbed out, can we make audio being enabled/disable a core option instead?

**Comment by AdrianoML** [comment]
Thanks! My motivation for doing this was the robust shader library built into retroarch and wondering if I could lower captured video latency a bit, since I wasen't happy with tvtime's approach (which don't even have a progressive capture mode).

The return thing was a leftover from testing what was causing the 100% cpu usage), I've now pushed a comit fixing it.

**Comment by twinaphex** [comment]
Linking against libmath should be fine I guess.

**Comment by twinaphex** [comment]
Would you mind if I posted a blog article with the contents of your PR about these video processor enhancements/improvements? I can credit you as well in the article.

**Comment by AdrianoML** [comment]
Ok, no problem :)

**Pull request merged**
