### PR TITLE
ozone: implement wiggling for main menu when wrap-around is disabled

### PR DESCRIPTION
**Pull request by natinusala**
Followup of my last PR - implement wiggling for main menu when wrap-around is disabled.

I don't know if users can disable the "right goes down" and "left goes up" feature, in which case please let me know because I'll have to change the wiggle direction if that setting is disabled.

I also don't like using `config_get_ptr()` everywhere but it seems I don't have a choice here, unless you see a better solution.

Reviewers: @jdgleaver @twinaphex

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there @jdgleaver , 

would very much appreciate if you could review this.

**Comment by jdgleaver** [comment]
Ah, we have a slight problem here: when wrap-around is disabled, pressing left/right on the top/bottom entry of a settings list (to change the setting value) will incorrectly trigger a wiggle. The wiggle needs to be inhibited whenever the current selection is of a settings type.

This is actually a bit tricky to identify - you can see how I do it for glui here: https://github.com/libretro/RetroArch/blob/6767f0f0c303f5c2ef76ff58311503b89a7a2019/menu/drivers/materialui.c#L9207-L9254

As for the lesser concerns:

> I don't know if users can disable the "right goes down" and "left goes up" feature, in which case please let me know because I'll have to change the wiggle direction if that setting is disabled.

That can't be disabled, so no worries there :)

> I also don't like using config_get_ptr() everywhere but it seems I don't have a choice here, unless you see a better solution.

It's a necessary evil, and quite acceptable. The only thing (and this is just a minor style nit) is that, when using the settings pointer, we usually cache the value at the start of the scope - i.e.:

```c
   settings_t *settings = config_get_ptr();
   bool wraparound_enable = settings->bools.menu_navigation_wraparound_enable;
   size_t selection;
   size_t selection_total;
```

...Then you just use `wraparound_enable` instead of lugging that ugly `settings->bools.menu_navigation_wraparound_enable` around :)

**Comment by natinusala** [comment]
@jdgleaver good call, I missed that. I used the code from MUI and it seems to work fine.

**Comment by jdgleaver** [comment]
Nicely done! I think this is ready to merge now :)

**Pull request merged**
