### PR TITLE
French translation part 2

### PR DESCRIPTION
**Pull request by WeedyWeedSmoker**
## Description

Cosmetic changes (thanks to @cosmo-kray for your feedback), changes to better fit XMB menu, adding spaces to accomodate the QT desktop interface, and full translation of "msg_hash_fr.c" file !

## Reviewers

@twinaphex @cosmo-kray @Tatsuya79

### CODE REVIEW

**Comment by WeedyWeedSmoker** [comment]
@twinaphex What the heck, is Travis complaining 3 times about text strings that are still the same as the US file, and 1 time about a text string that is shorter than some others ?

Do I need to fix some strings length or is Travis just being strange ?

**Comment by twinaphex** [comment]
No, these are C89 build errors.

It's probably best if I just take you translator's commits and then implement them myself, so I can fix these C89 errors myself.

**Comment by WeedyWeedSmoker** [comment]
Ok, the french translation is now fully completed !

@twinaphex, you can now add this PR to the code and check dem nasty C89 errors... You da man bro !

**Comment by WeedyWeedSmoker** [comment]
@twinaphex Fixed the conflicts, and the last text string that was too big for the XMB menu... You can safely merge this PR now...

**Comment by WeedyWeedSmoker** [comment]
@twinaphex I shortened the problematic strings to compile with C89, I've posted the file here :
https://pastebin.com/raw/ufjgQXKw

Thanks !

**Pull request merged**
