### PR TITLE
qb: Add check_platform.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This allows enabling and disabling features for platforms more robustly by adding a new `check_platform` function to `qb/qb.libs.sh`.

* If `--enable-foo` is used and `foo` is not supported for the user's platform it will error.
* If `--enable-foo` is not used and `foo` is not supported for the user's platform then `foo` will be automatically disabled.
* If `--disable-foo` is not used and `foo` is supported for the user's platform it will be enabled by default.

This is then applied to several checks in `qb/config.libs.sh`.

## Related Issues

* `HAVE_DISCORD` is automatically disabled for `haiku` where its not supported.
* Configure now has both `--enable-rpiled` and `--disable-rpiled` to control `HAVE_RPILED`.
* Configure now respects `--disable-tinyalsa`.
* All platforms excluding `Win32` now error with `--enable-d3d9` and other D3D related options.

Fixes https://github.com/libretro/RetroArch/issues/8777.

## Reviewers

I tested this as much as I could, but there are a few people that should test this to make sure it works well on other platforms.

@kwyxz Please check that this handles the `HAVE_DISCORD` check for Haiku correctly.
@fr500 or anyone with windows please make sure `HAVE_D3D9` and other D3D related options still work.
@bparker06 Please test that this does not break DOS.

### CODE REVIEW

**Comment by orbea** [comment]
Travis is showing I am missing something, I'll fix this probably tomorrow.

**Comment by orbea** [comment]
Okay this is ready for testing again. I updated the commit with fixes for the D3D configure checks.

* Dehardcodes D3D8, D3D9 and D3DX compiler arguments and adds checks for them to configure.
* Adds a missing configure check for `HAVE_D3D8`.

**Comment by orbea** [comment]
Force pushed some trivial cleanup...

**Comment by orbea** [comment]
Forgot to update the static makefiles after dehardcoding variables, that is fixed now.

**Comment by twinaphex** [comment]
Again - another PR closed without any explanation why.

You seem to have unreasonable expectations for when something should be merged. This was less than 5 days old, there are PRs that have lingered in dev hell for months. Please start showing some more patience in the future.

**Comment by orbea** [comment]
@twinaphex Reopened and rebased. This was was tested by @fr500 roughly 20 days ago.

**Comment by kwyxz** [comment]
Forgot to try that out at the time, but I now confirm : it 100% fixes `./configure` with Haiku and builds without any issue. Thanks @orbea

**Pull request merged**
