### PR TITLE
(GLUI) Fix scrolling

### PR DESCRIPTION
**Pull request by heuripedes**

### CODE REVIEW

**Comment by heuripedes** [comment]
I'd be thankful if you could look into making this work on touch devices. I do not have access to one.

**Comment by Kivutar** [comment]
OK I will try! Can you explain me what scroll bug was fixed by your commit? So I will not cause regression.

**Comment by twinaphex** [comment]
Sadly enough we have to revert this because of the issues kivutar mentioned.

It's not enygmata's fault though, it is really GLUI's fault. @Kivutar - please sort this out. We cannot launch 1.2.1 like this where we either have missing 'items' or we have screwed up touch controls. Neither is acceptable and this really ought to be fixed by now after all this time.

**Comment by Kivutar** [comment]
I see.

Looks like the recent improvements here https://github.com/libretro/RetroArch/commit/bca0789d352ed761245f6c0279844fd6014cc041 fixed it? I was not able to reproduce it more since this commit.

**Pull request merged**
