### PR TITLE
add new theme RetroLive

### PR DESCRIPTION
**Pull request by MrHomebrew**
Description:

Add new theme RetroLive!!!!

Related Pull Requests:

https://github.com/libretro/retroarch-assets/pull/312/commits/08a9b6feaa268d3ca79bb3d2d2925a414984fd48

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks great. Here's a screenshot, and my thoughts...

- There is some inconsistency in the icons, likely because it's mixed across a bunch of baxysquare's themes. Some icons are 2D, while others appear 3D.
- Mind adding license information for the font and art? You can find a few of them here: https://github.com/baxysquare/baxy-retroarch-themes#licenses
- May want to get @baxysquare's blessing on this before we move it into RA. In the mean time, you can just name the `retrolive` folder `custom` and use it as a custom theme.

Screenshot at 2019-05-28 21-03-17

**Comment by bparker06** [comment]
LGTM pull request analysis was skipped for 8afcf774cdc044d15309f3499799017f5aff24c6 by [MrHomebrew](https://github.com/MrHomebrew). Analysis of future commits will happen as normal.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by MrHomebrew** [comment]
Not sure what this is about "C/C++
Analysis failed (could not build the merge commit and the base commit (4026075))"
Would that need fixed? If so any recomendations?

**Comment by baxysquare** [comment]
I honestly have mixed feelings about the use.  On one hand, I would have never been able to develop and evolve the themes I created, had it not been for the existence of Monochrome and FlatUI.  But in the end, all the icons became original, even though they may have been originally based on those theme icons.  Two of my own theme sets are derivatives of the originals, but they have a very different art style applied to them.  I have no problem with using my icons as a foundation, but the end result should look different enough that we're not confusing the end user.

@Tatsuya79 blended my sets together and continued the logo idea that I abandoned in the RetroActive Marked Alternative Icon Set.  Based on @RobLoach's screenshot It looks like RetroLive is actually more of a port of Retrosystem, complete with removed translucent borders and branded icons.  

I'd recommend more work to make the design a cohesive theme. I agree with @RobLoach that the icons should have consistency and continuity and feel like they go together as a set, rather than blended together from differing art styles and whatnot.  Use the [Guide to Making Themes](https://forums.libretro.com/t/guide-to-making-themes/9554) and build a set using those guidelines.

Please do not let this recommendation stop you from developing the theme to the point that it's ready for submission and approval. I submitted RetroActive to GitHub and [received some critiques](https://github.com/libretro/retroarch-assets/pull/18). I had to modify every single icon in the set, but it made for a quality product and made me a better artist and developer.

**Comment by orbea** [comment]
@MrHomebrew Please use `git rebase` and not `git merge` for updating PRs, we have enough messy merge commits as is...

**Pull request closed without merging**
