### PR TITLE
better handling HAVE_NEW_CHEEVOS compilation

### PR DESCRIPTION
**Pull request by meleu**
## Note

**The changes here don't affect anything in the binaries currently built by the buildbot.**

**[UPDATE]** based on [orbea's comment](https://github.com/libretro/RetroArch/pull/8045#issuecomment-455876540), I've added the `./configure --enable-new_cheevos` option to easily build RetroArch with the new cheevos implementation.

## Description

This is a preliminary work to allow further investigations of the problems occurred when @leiradel's [rcheevos](https://github.com/RetroAchievements/rcheevos/) were integrated to RetroArch (PR #7321, later reverted). 

### Changes

- **`Makefile.ctr`**: removing a leftover mention to `deps/rcheevos/include`.
- **`Makefile.common`**: better handling the HAVE_NEW_CHEEVOS flag (when it's set, use the `cheevos-new/*` files).
- **`cheevos-new/cheevos.c`**: using the new nes/snes/lynx hashing methods (changed in the current cheevos code in #7769 and #8010).

## Related Issues

#7341
https://github.com/RetroAchievements/rcheevos/issues/3
https://github.com/RetroAchievements/rcheevos/issues/7

## Reviewers

@leiradel @fr500 @Jamiras

### CODE REVIEW

**Comment by meleu** [comment]
@Jamiras 
> by excluding the old cheevos files, are there code changes required to call the new cheevos functions?

You'll need to define `HAVE_NEW_CHEEVOS` somewhere. In this case here it's defined [in the Makefile.common](https://github.com/libretro/RetroArch/pull/8045/files#diff-1c2b8e7c48acf6b44215acf450579143R1673) and used when building with `HAVE_NEW_CHEEVOS=1`.

By the way, here are the commands I usually use to compile RetroArch on my Linux:
```
$ ./configure --prefix="/path/to/retroarch/directory" --disable-sdl --enable-sdl2 --disable-oss --disable-al --disable-jack --enable-vulkan --disable-ffmpeg
$ make clean
$ make
$ sudo make install'
```

And here's how I compile using the new cheevos implementation (with rcheevos):
```
$ ./configure --prefix="/path/to/retroarch/directory" --disable-sdl --enable-sdl2 --disable-oss --disable-al --disable-jack --enable-vulkan --disable-ffmpeg
$ make clean
$ make HAVE_NEW_CHEEVOS=1 HAVE_LUA=1
$ sudo make install HAVE_NEW_CHEEVOS=1
```

**Comment by Jamiras** [comment]
I understand how to activate the feature, I was just concerned that the signatures changed between versions. If you're able to compile with the new flag, it's a good indication that they didn't. Which leads to my second question - presumably the previous attempt to integrate this did not compile both the old and new implementations into the same binary.

**Comment by meleu** [comment]
@Jamiras 
> I suppose there's probably another PR somewhere that would show the relevant changes for the previous attempt.
> presumably the previous attempt to integrate this did not compile both the old and new implementations into the same binary.

The original @leiradel's PR (#7321) does the necessary changes ([as you can see in this diff](https://github.com/libretro/RetroArch/pull/7321/files#diff-1c2b8e7c48acf6b44215acf450579143)). It just replaced the old implementation with the new one (didn't try to keep both implementations to be chosen in compile time).

During my current investigations I realized that differences regarding calling the old/new cheevos functions happens mostly in the `command.c` file. I noticed that by looking:
- [in the leiradel's PR diff for `command.c`](https://github.com/libretro/RetroArch/pull/7321/files#diff-22dda82c4f511a2b00e369c0649da0f2) and
- in the current command.c, inside `#if defined(HAVE_NEW_CHEEVOS)` clauses in [command_read_ram()](https://github.com/libretro/RetroArch/blob/8c5f4a842c574a1c3889c87bd8852a32f507ebb9/command.c#L278L305) and in [command_write_ram()](https://github.com/libretro/RetroArch/blob/8c5f4a842c574a1c3889c87bd8852a32f507ebb9/command.c#L345L348)

In a further research, in order to answer your question here, I also noticed that in the current code there are some `#include`s for rcheevos files in the current `griffin/griffin.c` ([inside the `#ifdef HAVE_NEW_CHEEVOS` clause](https://github.com/libretro/RetroArch/blob/fab4834b829b7e26b9760d471c9b2fa806ad1fec/griffin/griffin.c#L154L172)) which are not present [in the leiradel's fork](https://github.com/leiradel/RetroArch/blob/46e621b4a046439e802c442630ff5af6e2e6a64b/griffin/griffin.c#L146L157). But I'm not sure about the implications of that and if it's related with the issues faced by @fr500 on Android.

**Comment by Jamiras** [comment]
> It just replaced the old implementation with the new one

This is what I was looking for. Thanks.

> I also noticed that in the current code there are some #includes for rcheevos files in the current griffin/griffin.c which are not present in the leiradel's fork.

The griffin files are used by the MSVC projects. I had to make similar changes when I was trying to reproduce the reported crash (full diff attached). I don't know if they're used by the normal distribution process.

[android-diff.zip](https://github.com/libretro/RetroArch/files/2776191/android-diff.zip)

**Comment by orbea** [comment]
@meleu Just fyi there is also `--enable-lua`, it was disabled by default since the new cheevos didn't seem ready or to have anyone working on it at the time. Additionally `--enable-lua` will cause segfaults in the system lua if its installed, `--enable-mpv` is also used and libmpv is built against lua (Its needed for ytdl support).

I'm not sure what the plan is with the current or new cheevos implementations, but it shouldn't be hard to add a configure argument for `HAVE_NEW_CHEEVOS`.

See https://github.com/libretro/RetroArch/blob/master/qb/config.params.sh.

**Comment by leiradel** [comment]
Cool, this PR is important so we can see if the Android build still has issues with rcheevos, and to make it easier to debug them if it does.

**Comment by meleu** [comment]
@orbea thanks dude! I didn't know that trick. Added it in my last commit (04ec598b97ae4d041f0612821f0d598588ac8dab).

Tested here and it works like a charm. :ok_hand: 

no need to pass `HAVE_NEW_CHEEVOS=1` to `make` anymore.

**Pull request merged**
