### PR TITLE
GLES 3.1 and 3.2 build parameters, and corresponding context checks.

### PR DESCRIPTION
**Pull request by dankcushions**
## Description

`HAVE_OPENGLES3_1` and `HAVE_OPENGLES3_2` are used elsewhere, so added as build configure arguments, and introduced checks when requesting GLES 3.1/3.2 HW contexts. Previously it would always assume GLES3.2 support if `HAVE_OPENGLES3` was set.

A better solution rather than all these ifdefs for GL support might be to attempt the requested context and see if it succeeds, or attempt to retrieve GL/GLES version at runtime (this appears to be non-trivial: https://github.com/hrydgard/ppsspp/blob/629edf9454076d61600be8f82779529b460c55ed/ext/native/gfx_es2/gpu_features.cpp#L232-L297 - especially for the breadth of RetroArch targets).

Only tested on RPI4 (GLES 3.1) + duckstation. I'm not sure there are other cores that request a specific GLES 3.x context.

If accepted, I will submit PRs for retropie and lakka to use these flags for appropriate GLES devices.

## Related Issues

https://github.com/libretro/RetroArch/issues/11143

### CODE REVIEW

**Comment by twinaphex** [comment]
The only question I have here is how would this work for Android? Can you come up with an appropriate solution that covers the Android side too?

**Comment by dankcushions** [comment]
There's a PR that looks to deal with android: https://github.com/libretro/RetroArch/pull/9393

I can't comment on the PR itself, but I can certainly rebase these changes to work with the logic if that PR is accepted.

I guess with Android you could use the android API to establish what GLES version is supported, rather than using build defs, but I wouldn't know how to achieve that.

**Comment by twinaphex** [comment]
@webgeek1234 Could you provide some input here?

**Comment by dankcushions** [comment]
https://github.com/libretro/RetroArch/pull/9393 needs rebasing anyway so can this be merged since it works within the existing structure? happy to wait for https://github.com/libretro/RetroArch/pull/9393 but it doesn't seem to be moving.

**Comment by dankcushions** [comment]
Bumping this one again - other PR seems to not be moving, but this fits fine within the current master code.

**Pull request merged**
