### PR TITLE
Fix Arabic, Chinese and Korean font rendering

### LINKED ISSUE #7822: [intl] Arabic renders as boxes
## Description

When selecting languages Arabic appears as only boxes.

### Expected behavior

Arabic should be rendered.

### Actual behavior

arabic

### Steps to reproduce the bug

1. Go to `Settings -> User -> Language` and then scroll through all languages until boxes appear.

### Bisect Results

This never worked, I bisected this and found it started when Arabic support was merged.
```
commit 45580cb9a8f0fcd0a87f00eadf26d87f05289485
Author: aliaspider <aliaspider@gmail.com>
Date:   Mon Feb 5 20:54:55 2018 +0100

    add basic support for arabic.

:100644 100644 fcf90a92d9c0db4cc8bb44528f4df26512bab609 498be0f8889dc4ecfb78649bb324aea573074477 M	Makefile.common
:040000 040000 8acbd24ccbb7a7e1c50ce8a08f412ca9349076e2 5baf5404bf531d536145dc9da1868c8dd7083512 M	gfx
:040000 040000 e59db4e8ad19e17801a80813bb50a25a8b296449 1aac59f0f6d36935482ec17ffd9289cb00af3f1b M	griffin
:040000 040000 a82bd80dba3c3edb5beb17706925bd713d09c28c c0d1ec0a714af68e7cb59d41b0402a9d75a12c5a M	intl
:040000 040000 ced06bef085d83db752894e810585bb45d5c2fe4 1e0684e6b37c82845e7171dc82fd76c4d2de21fc M	libretro-common
:040000 040000 83faddb6bc1242a1beee542323e1ba9ecb49d7d1 7ff985531043d3dc44af0fadc7dfce35be598887 M	menu
:100644 100644 1ce3f6bc33f15cd92985e1855320676c822a4bc9 37a871b2228fe27f3f8ac8387e16ab7a5e3fff77 M	msg_hash.c
:100644 100644 91673d48f35e23a1721dc88c367f0eef7e9ef0e3 db3bbb9125bfd37c99611b4c61bfb2dcd1b745f2 M	msg_hash.h
```
45580cb9a8f0fcd0a87f00eadf26d87f05289485

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/fcf75fda170ede591cb37361f8a41a8f25f37404

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.2.0`

### LINKED ISSUE #9613: Android show squares in Chinese
### Expected behavior

Chinese characters should be rendered correctly

### Actual behavior

Some Chinese characters are rendered as squares

### Steps to reproduce the bug

1. Change Android system language to Chinese
2. Install RetroArch on Android
3. Open RetroArch

### Version/Commit

- RetroArch: 1.7.9 GIT

### Environment information

- OS: Android Pie

photo_2019-10-18_22-20-49

### PR DESCRIPTION
**Pull request by guoyunhe**
## Description

None of fonts from asses support Arabic, Chinese and Korean properly. So I made a PR to add these fallback fonts. See https://github.com/libretro/retroarch-assets/pull/338

Then in MaterialUI, OZONE and XMB menu driver, let RetroArch use fallback fonts when these languages are set. Note: this PR doesn't fix rgui and OSD fonts.

Result:

Korean fallback font: Sunflower
Screenshot_20200524_171042
Screenshot_20200524_173658

Chinese fallback font: Droid Sans Fallback
Screenshot_20200524_155722

Arabic fallback font: DejaVu Sans
Screenshot_20200524_170956

## Related Issues

Fix #9613
Fix #7822

## Related Pull Requests

https://github.com/libretro/retroarch-assets/pull/338

## Reviewers

@twinaphex @RobLoach @WeedyWeedSmoker

### CODE REVIEW

**Comment by twinaphex** [comment]
There's a small C89_BUILD error but I'll fix it afterwards.

**Comment by leoxxx** [comment]
It's worse than before version with default gui.

**Comment by guoyunhe** [comment]
@leoxxx  have you updated assets?

**Comment by leoxxx** [comment]
> 
> 
> @leoxxx have you updated assets?

I'm not update install. Just new install in a device.
RetroArch_ra32

**Comment by guoyunhe** [comment]
See https://github.com/libretro/retroarch-assets/pull/366

**Pull request merged**
