### PR TITLE
Implement ffmpeg send/receive encoding API

### PR DESCRIPTION
**Pull request by hasenbanck**
## Description

This is implementing the send/receive encoding API of ffmpeg in the ffmpeg record backend.

Newer encoder do need the client to use this API to use them (for example h264_amf and hvec_amf). "Old" encoders should work fine (Tested x264 and webm profiles).

The biggest change is the handling of the encoded packets, since the API can return multiple packets in it's queue. As a positive side-effect the code for flushing is much more easier.

Tested with ffmpeg 4.2.1. This feature is only really useful when the ffmpeg build includes the h264_amf and hvec_amf encoders. The currently included ffmpeg version in the windows builds seem to be of an older version (v3?). I think the buildbot needs to be updated to ship a newer version.

## Related Issues

Implements #9783

### CODE REVIEW

**Comment by hasenbanck** [comment]
Forced pushed a removal of two unneeded check for an empty package in the encode_audio() function which I spotted my going over my code again.

**Comment by twinaphex** [comment]
Thanks for this. We are going to be upgrading to a new server before the years' end, and with that we'll have newer toolchains and updated packages which should hopefully ensure we will be on a much more recent version of ffmpeg then.

BTW, this might be unbecoming of me to ask, but if you have any interest at all, would it be possible for you to research if you could add hardware accelerated video decoding to the current ffmpeg core? I believe information pertaining to this can be found here -

https://trac.ffmpeg.org/wiki/HWAccelIntro

This could finally make the video player part of RetroArch acceptable enough on systems where CPU-based video decoding is not going to cut it.

**Comment by twinaphex** [comment]
This should be an example of a hw_decode implementation -

https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/hw_decode.c

**Comment by hasenbanck** [comment]
> BTW, this might be unbecoming of me to ask, but if you have any interest at all, would it be possible for you to research if you could add hardware accelerated video decoding to the current ffmpeg core? I believe information pertaining to this can be found here -
> 
> https://trac.ffmpeg.org/wiki/HWAccelIntro
> 
> This could finally make the video player part of RetroArch acceptable enough on systems where CPU-based video decoding is not going to cut it. We've been really looking for somebody with the interest to add this for a while now.

@twinaphex 
I can have a look into it. Since I don't know the codebase very well, I will first have a deep look into it to estimate how much work would be needed. I will give a feedback over discord once I know more.

**Comment by twinaphex** [comment]
Huge thanks for even being willing to consider it! I am known as Autechre over on Discord, feel free to always ask me any questions pertaining to this and I'd be happy to be of assistance.

**Comment by fr500** [comment]
You don't really need this though.
At least for nvenc you don't, you just drop in the libraries with support for that and it will use hw acceleration just fine.

Maybe for amd it's different

**Comment by hasenbanck** [comment]
As stated in #9783 you need this change to use AMF.

The old API has an ```attribute_deprecated``` attached to it (```avcodec_encode_video2()```). So I guess they are marked deprecated.

The [documentation](https://ffmpeg.org/doxygen/trunk/group__lavc__encdec.html) states:

> Some codecs might require using the new API; using the old API will return an error when calling it. All codecs support the new API.

**Comment by twinaphex** [comment]
Let's not start a debate here over whether the ffmpeg core is bad or good, that is not the point.

The point is that I'd very much like to see hardware codecs working with it. This is not the thread to be discussing the merits of the core itself.

**Comment by fr500** [comment]
> 
> 
> As stated in #9783 you need this change to use AMF.
> 
> The old API has an `attribute_deprecated` attached to it (`avcodec_encode_video2()`). So I guess they are marked deprecated.
> 
> The [documentation](https://ffmpeg.org/doxygen/trunk/group__lavc__encdec.html) states:
> 
> > Some codecs might require using the new API; using the old API will return an error when calling it. All codecs support the new API.

Thanks for the clarification, I'm building to test with nvenc

**Pull request merged**
