### PR TITLE
Display a "Fast forward."  message

### LINKED ISSUE #5667: Fast forward key should show status message
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The fast forward key ( L by default ) should display an status message that says "Fast forward." just like how E ( The default slowmotion key ) shows "Slow motion."

### Expected behavior

Fast forward key ( L by default ) should show status message "Fast forward."

### Actual behavior

No status message.

### Steps to reproduce the bug

1. Fast forward using the L key
2. Look at the status message

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: RetroArch Oct 31 2017
### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW

### PR DESCRIPTION
**Pull request by RobLoach**
Similar to how we have a "Slow motion." message appear, display a "Fast forward." message when sped up.

fastforward

Fixes #5667 

## QA

1. Compile
2. Run a game
3. Press Fast Forward key (default is l)
4. See "Fast forward." appear on the screen

### CODE REVIEW

**Comment by twinaphex** [comment]
Reverting, this makes the FPS message no longer show.

**Comment by hyarsan** [comment]
Why does slow motion do the message "Slow motion." then?

**Comment by fr500** [comment]
it was re-submitted and merged already.

**Comment by hyarsan** [comment]
I know, that's great :)

**Pull request merged**
