### PR TITLE
qt: remove retroarch nightly updater

### PR DESCRIPTION
**Pull request by Tatsuya79**
Not working atm.
Will be replaced by a non qt specific method later.

### CODE REVIEW

**Comment by BParks21** [comment]
Really missing this feature :(

**Comment by n1ghttrap** [comment]
> Really missing this feature :(

Seconded.

**Comment by BParks21** [comment]
@Tatsuya79 Can we have some details on the replacement of this feature?

**Comment by Tatsuya79** [comment]
I just did it because it was discussed that it won't get fixed for qt only.
I'm not the one doing the reimplementation.
No ETA anyway, people volunteer when they find the time to do so.

**Comment by n1ghttrap** [comment]
Any news on when or if this feature will be restored or replaced, and how?  It's extremely handy to update from within RA and not use some separate script or download manually.

**Pull request merged**
