### PR TITLE
Add an environment call for querying the device's battery

### PR DESCRIPTION
**Pull request by JesseTG**
## Description

This pull request adds a new environment callback that allows cores to query the frontend's battery level and power status. This can be useful for emulating battery life on handheld game consoles such as the Nintendo DS. Another possible use case is to allow cores to reduce their workload if the battery is low.

RetroArch already implements this functionality in a cross-platform manner. I just expose it to cores.

~~Note that _this PR has not been tested yet_; I intend to test it on [a core I'm working on](https://github.com/JesseTG/melonds-ds) in the near future. Right now I'm gathering feedback and declaring my intent to get this merged at some point. Once I integrate this into my core, I will consider it ready to be merged.~~

Okay, I tested it. Works like a charm. https://cdn.discordapp.com/attachments/876520593636335646/1131628490148560988/20230720_124448.mp4

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
@LibretroAdmin @barbudreadmon (since you've added callbacks before) Anyone else?

This looks pretty straightforward to me.

**Comment by barbudreadmon** [comment]
It looks fine to me

**Review by RobLoach — APPROVED** [review]
I believe this is working well. Tried adding it to ChaiLove in https://github.com/libretro/libretro-chailove/pull/424 ....

```
var powerInfo = love.system.getPowerInfo()
print("Battery")
print(to_string(powerInfo.state))
print(to_string(powerInfo.seconds))
print(to_string(powerInfo.percent))
```

```
Battery
3
-1
-1
```

**Comment by JesseTG** [comment]
@LibretroAdmin Any objections to merging this PR?

**Pull request merged**
