### PR TITLE
Try to fix xcode10.1

### PR DESCRIPTION
**Pull request by LazyBumHorse**

### CODE REVIEW

**Comment by LazyBumHorse** [comment]
I thought it could have something to do with
https://stackoverflow.com/questions/32177046/ifeq-conditional-syntax-in-makefile

**Comment by orbea** [comment]
@LazyBumHorse This won't help the xcode build which doesn't use `Makefile.common` at all.

**Comment by LazyBumHorse** [comment]
Oh...
But then how does any of this work?

There's a
`xcodebuild -target RetroArchQt -configuration Release -project pkg/apple/RetroArch_Metal.xcodeproj`
Then some magic happens
And then there's
`/bin/sh -c /Users/travis/build/libretro/RetroArch/pkg/apple/build/RetroArch_Metal.build/Release/RetroArchQt.build/Script-053FC2782143764B00D98D46.sh`
which `moc`s all the stuff expect for `shaderparamsdialog.h` where does it decide to stop caring about `shaderparamsdialog`?

**Comment by orbea** [comment]
Yea, I am lost on that too. I have no idea how or where the moc files are generated for xcode and I haven't found any clear documentation yet.

**Comment by LazyBumHorse** [comment]
Wait, are you sure it's not using Makefile.common?

There's this in `pkg\apple\RetroArch_Metal.xcodeproj` (which is apparently what travis is building):
`shellScript = "make -C ${SRCBASE} -f Makefile.apple HAVE_MENU=1 HAVE_MENU_WIDGETS=1 HAVE_QT=1 MOC=${QT_INSTALL}/bin/moc generate\n";`

And in `Makefile.apple` there's this:
`include Makefile.common`

**Comment by orbea** [comment]
You're right, I think I see the problem now and I'll reopen my PR to test.

**Comment by orbea** [comment]
Seems like my idea worked out, thanks for the good hint with `Makefile.apple`.

https://github.com/libretro/RetroArch/pull/9158

**Comment by orbea** [comment]
@LazyBumHorse Given my PR was merged and travis should pass again I am going to close this, but thanks a lot for the time, effort and help! :)

**Pull request closed without merging**
