### PR TITLE
Date Time setting for AM:PM as an option

### PR DESCRIPTION
**Pull request by grimpunch**
## Description

Implemented AM:PM, among other time / date style options , since the existing PR for this issue seems to have fizzled out, I made an attempt at a cross platform friendly way of implementing this.

## Related Issues

https://github.com/libretro/RetroArch/issues/5216

## Reviewers
@m4xw @gouchi 
please let me know if linux version works fine on all setups.

### CODE REVIEW

**Comment by bparker06** [comment]
Can we have MM/DD HH:MM and YYYY-MM-DD HH:MM also?

And how does this react to locales that put their equivalent AM/PM marker at the beginning instead of the end (like with Japanese)?

**Comment by gouchi** [comment]
It is working correctly for changing date/time format but locale is not respected.

Using something like for french or japanese 
```
LANG=fr_FR.UTF-8 retroarch
LANG=ja_JP.UTF-8 retroarch
```
We should add `setlocale(LC_ALL,"");`  in function [menu_display_timedate](https://github.com/libretro/RetroArch/blob/master/menu/menu_driver.c#L340).

**Comment by gouchi** [comment]
> On startup of the main program, the portable "C" locale is selected
>        as default.  A program may be made portable to all locales by
>        calling:
> 
>            setlocale(LC_ALL, "");

[Source](http://man7.org/linux/man-pages/man3/setlocale.3.html)

**Comment by gouchi** [comment]
The locale is only working with %c from [strftime](http://man7.org/linux/man-pages/man3/strftime.3.html) which is 

> the preferred date and time representation for the current locale.

**Comment by grimpunch** [comment]
@gouchi  won't setLocale(LC_ALL, "") only show AM PM if the user has it set as their preferred time format? 
@bparker06  will do

**Comment by gouchi** [comment]
@grimpunch it seems we will have to use `%p` or `%P` to show AM/PM.

**Comment by grimpunch** [comment]
@gouchi  %r seems to work on linux, but not sure if that needs extensions.
and I think i have a solution for Windows/Other platforms, but I'm testing it now.

**Comment by grimpunch** [comment]
There isn't a reliable way to make Windows use AM/PM instead of the user's locale settings on their OS _while_ still respecting their locale for the placement of AM/PM markers. So I think there's two options, force AM PM to use the `%I:%M %p` structure like @gouchi said, and/or add the option to use `%c` and follow whatever the system uses (which on windows will follow AM PM or 24Hr depending on Windows setting, in HH:MM::SS format.
What do you think @bparker06 ?

**Comment by gouchi** [comment]
@grimpunch working fine on Linux. I was just wondering what do you think if we put the entry in Settings tab > User Interface > Appearance instead of Settings tab > User interface > Views ?

**Comment by grimpunch** [comment]
I think it's acceptable, i just put it under views because i thought it made sense to put it next to the time date enable/disable option.

@gouchi , if you think its best to move to Appearance, let me know and i'll update the PR.

**Comment by gouchi** [comment]
Let's wait others review ;-)

**Comment by grimpunch** [comment]
I think for now a reduced set of sensible options is best to help unblock other clock related bugs for UI.
I'll set up the default to be what it was before, what is the default it's meant to be?

HH:MM (AM/PM) seems to behave different on windows to linux, so might not be able to have a string to represent it correctly unless we have a different way of formatting it on windows which breaks locales.

I can see `YY-MM-DD` being weird, I'll replace it with `MM-DD-YYYY HH:MM` for American users benefit.

But yes, in future it may be best to break it up into "date display" and "time display" and let users customize each. (or as an advanced user setting, allow users to specify their own strings for formatting and handle it that way for those not happy with the defaults)

I'll take a look at making these changes later tonight.

**Comment by bparker06** [comment]
The default is DD/MM HH:MM.

**Comment by grimpunch** [comment]
@bparker06 , @gouchi  I've made changes to defaults and replaced uncommon formats with more common ones american users might appreciate, I think the options are in a state that is good enough to builld upon in future (perhaps splitting date/time displays as suggested) and should be good enough for now.

Please review,
thanks!

**Comment by bparker06** [comment]
Not quite yet:
img

**Comment by Kazzymax** [comment]
For anyone trying to configure it on Retropie, you are now able to use the format:
%B %d, %Y  %-I:%M %p
for
Month Day, Year  Hour:Minute AM/PM
or %-I:%M %p for just the time
:)

**Pull request merged**
