### PR TITLE
save unmodified auto-shaders as a reference instead of a copy

### PR DESCRIPTION
**Pull request by LazyBumHorse**
## Description

Automatic shader presets are currently always saved as copies, which has some disadvantages:
 - If an 'official' shader preset changes, a saved auto-shader won't change with it
 - If you have a custom preset that you often adjust, you'd need to adjust all auto-shaders manually each time

The idea is to allow (auto-shader) presets to refer to other (non-auto-shader) presets.

This is done by adding a custom
`#reference "<reference path>"`
or
`#reference <reference path>`
directive, which will act as if the referenced preset was loaded instead.
(The `config_file_t` or `video_shader` object's `path` will be \<reference path\>).

This directive is non-recursive and the menu shader saving code will only let auto-shaders refer to non-auto-shaders, which ensures that we never get references to references or self-referential presets.

References to the `retroarch.<ext>` preset are not permitted.

## How To Use

Load any shader in any way, save as an auto-shader without modifying and it will be saved as a reference (with the mentioned exceptions above).

If a shader is modified and then "Saved As", it will act as if it was freshly loaded, which allows to create auto-shaders pointing to custom presets.

## Changes

 - implement `#reference` directive for auto-shaders
 - replace usual preset saving and loading functions with `video_shader_read_preset()` and `video_shader_write_preset()`
 - apply saved presets automatically for console menus
 - move auto-shader saving logic from menus into menu_shader.c `menu_shader_manager_save_auto_preset()`
 - refactor `menu_shader_manager_save_preset()` into `menu_shader_manager_save_preset_internal()`

## Drawbacks

Currently, the detection of shader modifications is done via the UI elements.

This adds a small maintenance burden if new ways of modifications are added.

If the modification detection fails, a reference preset will be written instead of a needed copy, thus effectively saving the wrong shader.

### Console Menus:
Changing one of these counts as a modification:
 - Shader Passes
 - Shader #i (loading a pass)
 - Shader #i Filter
 - Shader #i Scale
 - Shader Parameters

Load -> Save <global/core/content/game> => reference
Load -> Modify -> Save As -> Save <global/core/content/game> => reference (to the saved as)
Load -> Modify -> Save <global/core/content/game> => copy

### Desktop/Qt Menu:
Changing one of these counts as a modification:
 - Add Pass
 - Remove Pass
 - Clear All Passes
 - 'Filter'
 - 'Scale'
 - Moving Passes
 - Shader Parameters

Load -> Save <global/core/content/game> => reference
Load -> Modify -> Save As -> Save <global/core/content/game> => reference (to the saved as)
Load -> Modify -> Save <global/core/content/game> => copy

### Loading

Loading through the console or desktop menu is a "Load", setting a shader via the network interface is a "Load" and loading an auto-shader is a "Load".
If the auto-shader is itself a reference, it behaves as if the referenced preset was loaded.

### CODE REVIEW

**Comment by LazyBumHorse** [comment]
fix `malloc` without cast

**Comment by LazyBumHorse** [comment]
Turns out
`param->current = param->initial;`
does not reset the shader parameter to it's "initial" value from the shader preset, but actually to the default value defined in the shader file's `#pragma`.

This wasn't counted as a modification but now is.

**Comment by twinaphex** [comment]
OK, looks like an all-around clear improvement and so far I see little potential for threading errors, so I think we can merge this.

**Comment by jdgleaver** [comment]
@LazyBumHorse This works beautifully - thank you so much!

**Comment by remimcgill** [comment]
@LazyBumHorse this is a fantastic addition. 

Please excuse me if I'm going about this the wrong way as I haven't worked with the group on github before :) I was wondering if it could be pushed further, Right now when any parameter is changed the whole preset is copied again with all parameters. I was wondering if it would be possible to have a reference to the original preset and then the changed parameters, or all parameters which would apply their values overtop the original values from the referenced preset.
The reason I suggest this is that when people save presets they are almost always only changing parameter values, but the way it is currently if the referenced preset gets updated they end up with an out of date copy of it which won't be updated.

**Comment by LazyBumHorse** [comment]
@HyperspaceMadness Hey there, sorry for the late reply, I'm currently on hiatus, so coding is out of the question, but let's take a look at this anyways.

What you suggest is not a bad idea but I think it's a lot of work for relatively little benefit, because how often do presets really change? It would also not be perfect because the meaning of parameters could change as well.

If you want to take a shot at it however, the easiest approach would probably be something like this:

1. Detect whether only shader parameters were changed by changing `menu_shader_set_modified()` and its calls to use a bitfield instead of one `bool`, so we have something along the lines of `menu_shader_set_modified(MS_PARAMS);` `menu_shader_set_modified(MS_OTHER);`
2. If only the parameters were changed, save all of them after `#reference ...` is written (so, [here](https://github.com/LazyBumHorse/RetroArch/blob/813a5cc37064656e16ab4b01212d24e77bc87633/gfx/video_shader_parse.c#L634)). We'd probably need to duplicate the part of code in `video_shader_write_conf_preset()` which writes the parameters and of course this all must be done without overrunning the `buf` buffer.
3. Load the parameters by reading a second line using another `filestream_getline()` (I think carriage returns need to be handled manually), parsing it as a config (with `config_file_new_from_string()`) and either duplicating the parameter parsing part of `video_shader_read_conf_preset()` or creating a temporary `video_shader` object and copying over all the parameters.

Ah... The last step wouldn't actually work, because a changed preset may have added new parameters or removed older ones, so can't just replace the parameter list with the read one but we'd need to properly "override" existing parameters. That's okay, this can be done with a simple O(n²) loop (for every original parameter, match the `id` with the "overridden" parameter and update the value).

All in all, even though this should be the easiest approach, it sounds pretty annoying to write and is surely not the most elegant approach with all the code duplication and temporary objects. It's also highly rigid since it can only do parameters and literally nothing else.

There's another approach I thought about, though it is much more ambitious:
Originally I tried to use the `#include` directive of `config_file_new_from_path_to_string()` for reference presets.
We wouldn't need the `#reference` directive at all if we could use the already existing `#include` directive instead.
Sadly, the handling of relative paths in config files using `#include` is a [pretty hard problem to solve](https://github.com/LazyBumHorse/RetroArch/blob/813a5cc37064656e16ab4b01212d24e77bc87633/gfx/video_shader_parse.c#L667-L688).

If we could use it however, simply reading the preset would give us a config object which contains both parameter lists.
Config objects aren't designed to contain multiples of the same setting, but we could add an accessor that can read the `i`th of a setting, thus making the reading part much easier... well, apart from all the hard work inbetween :smile:

**Comment by HyperspaceMadness** [comment]
Thanks @lazybumhorse for your suggestion, this really helps me with a place to start.

The two reasons I was thinking it would be helpful were to deal with updates to the referenced preset, the second is that having only the changed parameters in the saved preset will help the user know what changes they have made or what parameters have been changed in presets others have made.

**Comment by LazyBumHorse** [comment]
@HyperspaceMadness Btw, you might wanna check out our discord as well, we have a `#programming` channel there where you can talk about RetroArch development. This invite link should still work: https://discord.gg/C4Huaca

**Pull request merged**
