### PR TITLE
Auto save state when loading new content

### LINKED ISSUE #16805: Loading new content without closing the current one first wont create "auto"  savestate on exit
## Description
With Auto save state enabled, whenever you close content or quit retroarch, you get an "auto" save state created.
Issues is: when you load content while still having one running, it wont create the save state.

This is insidious because its so easy to do and lose progress.

### Expected behavior

I expect that when I load a content while another one is running, it would behave the same as closing the content then opening another one, thus creating a save state when auto save is on.

### Actual behavior
It does not create an "auto" savestate if I load another content while one is running.

### Steps to reproduce the bug

1. Make sure auto save and auto load is on
2. Start any content
3. Notice the screen content
4. Load another content while first one is still running
5. Load first content again and notice no "auto" savestate has been created

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Steam version 1.19.1

### Environment information

- OS: Windows 10 / Steam OS
- Compiler:

### PR DESCRIPTION
**Pull request by viachaslavic**
Close  #16805

### CODE REVIEW

**Comment by sonninnos** [comment]
Does not look too good to remove it from unload, as in how can it now save when new content is not loaded right afterwards..?

**Comment by viachaslavic** [comment]
It will still load the dummy core when closing content.

```c
#0  content_load (info=0x7fffffff8760, p_content=0x5555568fd358 <runloop_state+1912>) at tasks/task_content.c:1412
#1  0x0000555555777c18 in task_push_start_dummy_core (content_info=0x7fffffff8760) at tasks/task_content.c:1996
#2  0x0000555555652bdd in command_event (cmd=CMD_EVENT_UNLOAD_CORE, data=0x0) at retroarch.c:3692
#3  0x00005555559d5c26 in generic_action_ok_command (cmd=CMD_EVENT_UNLOAD_CORE) at menu/cbs/menu_cbs_ok.c:2150
#4  0x00005555559de3d8 in action_ok_close_content (path=0x7fffffffce6a "Close Content", label=0x7fffffffcf69 "unload_core", type=159, idx=2, entry_idx=0)
    at menu/cbs/menu_cbs_ok.c:5605
#5  0x00005555559d0981 in generic_menu_entry_action (userdata=0x555558640a20, entry=0x7fffffffca50, i=2, action=MENU_ACTION_OK) at menu/menu_driver.c:7643
#6  0x00005555559563f7 in ozone_menu_entry_action (userdata=0x555558640a20, entry=0x7fffffffca50, i=2, action=MENU_ACTION_OK) at menu/drivers/ozone.c:8623
#7  0x00005555559c93ff in menu_entry_action (entry=0x7fffffffca50, i=2, action=MENU_ACTION_OK) at menu/menu_driver.c:4211
#8  0x00005555559cf89b in generic_menu_iterate (menu_st=0x5555569b5780 <menu_driver_state>, p_disp=0x555556962ae0 <dispgfx_st>,
    p_anim=0x555556962bc0 <anim_st>, settings=0x7fffe240d010, menu=0x5555586329e0, userdata=0x555558640a20, action=MENU_ACTION_OK, current_time=108423023148)
    at menu/menu_driver.c:7301
#9  0x00005555559d13e6 in menu_driver_iterate (menu_st=0x5555569b5780 <menu_driver_state>, p_disp=0x555556962ae0 <dispgfx_st>,
    p_anim=0x555556962bc0 <anim_st>, settings=0x7fffe240d010, action=MENU_ACTION_OK, current_time=108423023148) at menu/menu_driver.c:7868
#10 0x00005555556697dd in runloop_check_state (error_on_init=false, settings=0x7fffe240d010, current_time=108423023148) at runloop.c:5971
#11 0x000055555566c1a0 in runloop_iterate () at runloop.c:6950
#12 0x00005555556573f9 in rarch_main (argc=1, argv=0x7fffffffdac8, data=0x0) at retroarch.c:5939
#13 0x000055555587d247 in main (argc=1, argv=0x7fffffffdac8) at ui/drivers/ui_qt.cpp:4281
```

 `current_core_type` will be changed after the successful `retroarch_main_init`: https://github.com/libretro/RetroArch/blob/38b3ba4e00d2fc16b3109d36e7a9d4477438a67e/tasks/task_content.c#L1452

**Comment by viachaslavic** [comment]
@sonninnos  done!

**Comment by sonninnos** [comment]
So now `command_event_save_auto_state()` is called both in `CMD_EVENT_CORE_DEINIT` and `CMD_EVENT_UNLOAD_CORE`, therefore is triggered twice in usual cases, and that does not sound too good.

**Comment by viachaslavic** [comment]
Are there any remaining obstacles to merge?

**Comment by jayare5** [comment]
Tested it!! Worked great! I really wanted this feature, thank you.

**Pull request merged**
