### PR TITLE
add analog deadzone and sensitivity options, rename axis threshold

### PR DESCRIPTION
**Pull request by bparker06**
These analog options have been missing from the frontend for far too long, and many cores don't offer one or both of them.

I renamed the axis threshold option because it has more to do with analog-to-digital conversion for button presses than it does with deadzones... if someone can come up with an even better name, feel free to change it again before it gets re-translated.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
"input button analog threshold" is a weird name, but it's a weird concept and I'm struggling to come up with anything better.

Cheers for the analog calibration options!!

**Comment by bparker06** [comment]
Yea it's weird, but the previous name was "Input Axis Threshold", followed by "Analog Stick Deadzone", which make even less sense to me. It's more like "Analog-to-Digital button map threshold of when to count as a button press". The default value of 0.5 means you must move an analog stick at least half-way for it to count as a button press. It applies both to the menu navigation as well as cores when you're using analog axes as button presses.

**Comment by orbea** [comment]
This should fix issue https://github.com/libretro/RetroArch/issues/8502?

**Comment by markwkidd** [comment]
@grant2258 fyi

**Comment by grant2258** [comment]
not an issue for us  we read the pressure pressed anyway and handle the deadzone in the core

**Pull request merged**
