### PR TITLE
[CRT] fix when having the same resolution with different refresh rate on X11

### PR DESCRIPTION
**Pull request by substring**
## Description

I've been reported that on X, when playing on PAL/NTSC systems, switching from one region to the other when changing rom, there was a problem to update the refresh rate of the mode, which meant the ROM was playing at the refresh rate of the previous ROM. This PR fixes it.

## Related Issues

None reported here

## Related Pull Requests

None

## Reviewers

no need

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi, can you resolve the merge conflicts?

**Comment by LibretroAdmin** [comment]
Still says this for me which prevents me from merging it

> This branch cannot be rebased due to conflicts

Maybe do a git pull and resubmit the PR ?

**Comment by sonninnos** [comment]
Hmm weird, here it says

> This branch has no conflicts with the base branch
Merging can be performed automatically.

**Comment by GABO1423** [comment]
Can confirm there are no merge conflicts
image

**Comment by substring** [comment]
rebased ... if it helps. Git subtrees really are a hell to deal with when rebasing

**Comment by hizzlekizzle** [comment]
weird, looks fine here but @LibretroAdmin said it's still showing conflicts on his end. Do you mind, @substring, if we just grab those changes and push them under libretroadmin's name/account?

**Comment by hizzlekizzle** [comment]
Hey, sorry for the runaround, but can you try closing this one and open a new one against latest main/master? to see if that helps at all?

**Comment by substring** [comment]
Sure I can!

**Pull request closed without merging**
