### PR TITLE
(zarch) Fix build

### PR DESCRIPTION
**Pull request by heuripedes**
zarch now builds, but it still renders incorrectly.

This commit introduced the rendering error:
https://github.com/libretro/RetroArch/commit/0d3e9875b13d2112725945dabf7f48e99a168f1c
If you comment the lines 1272 and 1276 the problem goes away.

### CODE REVIEW

**Comment by twinaphex** [comment]
@loganmc10 Can you look into this issue?

**Comment by loganmc10** [comment]
Yep I'll look into it tomorrow

**Comment by loganmc10** [comment]
So I'll be honest I had no idea what zarch is, it looks like it is the UI that is used on Android? @heuripedes can you be more specific about what is wrong? It looks just like it does on my Android phone, and it looks the same to me whether I comment out those lines or not

**Comment by lasers** [comment]
It looks like zarch is a mouse driven menu. glui is likely for Android.
Source: https://github.com/libretro/Lakka/wiki/Menu-drivers

**Comment by loganmc10** [comment]
oh ok ya it looks like it defaulted to glui, do I need some kind of ./configure flag to compile with zarch?

**Comment by loganmc10** [comment]
I guess just --enable-zarch

**Pull request merged**
