### PR TITLE
the thumbail updater now only downloads images for games in the playl…

### PR DESCRIPTION
**Pull request by leiradel**
…ists

### CODE REVIEW

**Comment by leiradel** [comment]
Well, it works, but when a download takes more than 60 frames (which is common for box arts), the osd message will disappear, and then reappear when the next image is downloaded.

Please notice that it only tries to download a thumbnail if it's missing from the filesystem. I think thumbnails are not updated very often so we can do that until there's a way to know if an image has been updated on the thumbnails server.

@twinaphex @fr500 @Kivutar can you take a look so we can decide if we go with this approach or not?  I can compute the total thumbnails that will be updated before the process is started, so that the osd will display "Updating thumbnail X/Y", but if the user adds a new game to a playlist then the counting will be wrong and there will be a message in the osd where X > Y.

**Comment by Kivutar** [comment]
I tested it, and it causes icons overlaps bugs in xmb. Is the code messing with file_list or menu_list?

**Comment by leiradel** [comment]
There was this code:

```C
   if (menu_displaylist_ctl(DISPLAYLIST_DATABASE_PLAYLISTS_HORIZONTAL, &info))
      menu_displaylist_ctl(DISPLAYLIST_PROCESS, &info);
```

I believe `DISPLAYLIST_DATABASE_PLAYLISTS_HORIZONTAL` fills a `content_playlist_t` pointer in `info` with all the existing playlists, but I don't know what `DISPLAYLIST_PROCESS` does. I changed tht code to

```C
   if (!menu_displaylist_ctl(DISPLAYLIST_DATABASE_PLAYLISTS_HORIZONTAL, &info))
      return false;
```

and the bug is gone. Could you confirm? Also, I don't think I have to `free(playlist)` when `DISPLAYLIST_DATABASE_PLAYLISTS_HORIZONTAL` fails, is that right?

**Comment by leiradel** [comment]
Hm, someone told me I could commit to my master branch without updating this pull request, but the commit "added a spetacular hack to support cheevos with the gambatte core" shouldn't be here.

I'll remove this PR since we still haven't decided what to do with the thumbnail updater and I need to make other changes.

**Pull request closed without merging**
