### PR TITLE
Adding some usb hid drivers

### PR DESCRIPTION
**Pull request by DiktatorShadaloo**
## Description
Usb Hid drivers for the popular ZeroDelay encoder (AKA DragonRise inc) and also for "Kade: Kick Ass Dynamic Encoder" to be able to use some custom arcade sticks on the wii.

## Related Issues

None

## Related Pull Requests

None

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Hi there, thanks for these contributions!

**Comment by LibretroAdmin** [comment]
Hmm, looks like our CI picked up some compilation issues for Wii and WiiU @DiktatorShadaloo - could you look into that?

Details should be here-
https://github.com/libretro/RetroArch/actions/runs/3380625278/jobs/5614709317
https://github.com/libretro/RetroArch/actions/runs/3380625263/jobs/5614708839

**Comment by DiktatorShadaloo** [comment]
> Hi there, thanks for these contributions! What was the platform that this was tested on? WiiU, macOS, or some other platform?

Hi! No, thank you all for retroarch. I have tested this on my wii by compiling a single core. I implemented this following as an example this PR https://github.com/libretro/RetroArch/commit/b6c12e5b85b4483be8c640ee8e74ea74087ea5b9 that I found in a thread.  Maybe something else needs to be done and I didn't realize it. I will try to fix it.

**Comment by LibretroAdmin** [comment]
Question BTW - what hardware do I need to buy to experiment/test this stuff myself? It's the first time of hearing about ZeroDelay or Kade.

**Comment by DiktatorShadaloo** [comment]
@LibretroAdmin 
For the zero delay you need one of [these](https://m.media-amazon.com/images/I/61G62Q1B76L._AC_SL1000_.jpg), they are very cheap and easy to find on aliexpress or ebay and very plug and play, they are quite popular among people who make their own arcade sticks without knowing too much, I was surprised that nobody had made a driver for it so people can use their sticks on the wii so I took the opportunity to do it.

Kade is a much more underground and little known project but it's awesome and a much better option than the zero delay. Kade works on microcontrollers with the atmega32u4 chip (arduino leonardo, teensy 2.0, arduino pro micro, etc), you can get one of these microcontrollers for 5-10 usd, I recommend the teensy 2.0 to have more compatible consoles. It can automatically detect many output systems allowing you to change between those systems without reprogramming your board, 
here is a link [link]( http://forum.arcadecontrols.com/index.php?topic=154126.0 ) about the project.

Particularly for this driver I used a kade sketch with the polling modified to 1ms that I found in this [forum ](https://www.aussiearcade.com/topic/90361-cheapest-fastest-diy-joystick-encoder-for-windows-ps-xbox-rpi-pico-gp2040/#post2097420)

**Comment by LibretroAdmin** [comment]
Hi @DiktatorShadaloo , you mentioned you develop for Wii, right? Would you like to perhaps meet us on Discord? You could contact either BoardsCanada or hunter, thanks. You can send either of them or both a DM. You can find the Discord link on our website www.retroarch.com

**Pull request merged**
