### PR TITLE
Add optional save state compression

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This PR adds a new `Savestate Compression` option under `Settings > Saving`. When enabled, save state files are written to disk as compressed archives. This both saves a substantial amount of disk space and reduces wear on solid state drives.

Actual compression ratios will vary depending upon core and loaded content. Here are a few examples of save state sizes for random cores/games:

| Core                    | Compression OFF | Compression ON |
| :---------------------- | --------------: | -------------: |
| Beetle PSX HW           |           16 MB |         1.5 MB |
| Flycast                 |           27 MB |         8.9 MB |
| Genesis Plus GX         |         1012 kB |          47 kB |
| mGBA                    |          453 kB |          45 kB |
| Mupen64Plus-Next OpenGL |           17 MB |         1.5 MB |
| PPSSPP                  |           40 MB |         9.3 MB |
| PCSX-ReARMed            |          4.3 MB |         2.3 MB |
| PUAE                    |           11 MB |         793 kB |
| Snes9x                  |          421 kB |          82 kB |

Notes:

- RetroArch will automatically detect whether state files are compressed or not, and load them approriately - i.e. `Savestate Compression` can be toggled at any time, and everything will Just Work (TM)

- We now have a new file stream for reading/writing archived data: `rzip_stream`. This can be used to handle any compressed data writing tasks we might have in the future

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
whoa, that's a big deal! Does it also compress in-memory states, like for rewind/runahead/netplay?

Either way, great job; very exciting development.

**Comment by jdgleaver** [comment]
@hizzlekizzle Thanks!

This only compresses states when they are written to file. For rewind and runahead, we need as much speed as possible - compressing the states every frame would more than negate any performance gains from having smaller data buffers  :)

Interestingly enough, netplay already compresses transferred save states - or at least, it's all geared up for this (I never use netplay, so haven't checked in detail). For example, this is where it does the compression part: https://github.com/libretro/RetroArch/blob/910da745190031142b1d16435663d7e905803711/retroarch.c#L5140-L5144

**Comment by Jamiras** [comment]
I was wondering how difficult it would be to turn the save state file into a container (sort of like mp4). I've been contemplating adding a screenshot to the save state for use as a thumbnail, and possibly adding metadata like when the save state was created and what versions of RetroArch and the core were being used.

With that sort of format, you could create a chunk labelled as uncompresed data or a chunk labelled as compressed data when saving, and either would be supported when reading the file.

I don't expect that sort of change in this ticket. I'm not even sure how feasible it would be. I'm just brain-dumping as supporting compressed save data was something I thought the format could be used for.

**Comment by jdgleaver** [comment]
@Jamiras That's an interesting proposition!

If I were going to tackle this, I'd still probably keep the compression separate from the data - i.e. establish a custom save state file format (with metadata in the header + state data + optional screenshot data) that gets written to a buffer, and then dump the buffer contents to file in exactly the same way as in this PR: either via a `filestream` or an `rzip_stream`. I think that splitting the load like this makes things more manageable, and makes the code more self contained.

This wouldn't even preclude using the save state metadata in the frontend - whether or not the file is compressed, the `rzip_stream` will still let you read the first n bytes without much effort, so you can grab the creation date, core version, etc.

So that means the task at hand would be to sort out the save state file format. That's probably not too difficult. The main thing would be getting all the data together in the right place, and handling it without too much duplication (i.e. states can be very large - we'd need to make sure only one 'formatted' buffer is allocated, and the core serialisation request dumps its output directly into it in the right place).

So yes, this is certainly something to think about  :)

**Comment by twinaphex** [comment]
Looks good enough to merge to me.

**Pull request merged**
