### PR TITLE
Update msg_hash_pl.h

### PR DESCRIPTION
**Pull request by DEX357**
FIXME Does not display the translation in the menu

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

[Description of the pull request, detail any issues you are fixing or any features you are implementing]

## Related Issues

[Any issues this pull request may be addressing]

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by fpscan** [comment]
I am not sure about in string notes

> /* FIXME Does not display the translation in the menu*/

**Comment by DEX357** [comment]
> 
> 
> I am not sure about in string notes
> 
> > /* FIXME Does not display the translation in the menu*/

Now is dosn't matter, translate is now working ok

**Comment by carlos-ks** [comment]
@DEX357 can you fix that ?

**Comment by guoyunhe** [comment]
Hi @DEX357 , you can directly contribute translations at https://crowdin.com/project/retroarch

**Comment by DEX357** [comment]
Nice, thx   
            
          
     
      
       
        Dnia 1 sierpnia 2020 17:56 Guo Yunhe &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Hi  github.com @DEX357  , you can directly contribute translations at  crowdin.com crowdin.com

**Comment by IlDucci** [comment]
PR should be obsolete thanks to the latest changes in Crowdin's integration. Should be closed.

**Pull request closed without merging**
