### PR TITLE
Update ISSUE template

### PR DESCRIPTION
**Pull request by viachaslavic**
Switching to the modern, more convenient template. You can see in [my fork](https://github.com/viachaslavic/RetroArch/issues/new/choose) (and even try to create a test issue there) how it would look in the case of a merge.
There is also the option to create an unformatted issue (`blank_issues_enabled: true` in _config.yml_).

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I think this looks really great.

**Comment by RobLoach** [comment]
This is a great idea. Could we have the `Feature request` get the label `feature request`?

**Comment by viachaslavic** [comment]
Yes, this PR also provide a template for feature requests. Unlike a bug report, its form is now arbitrary. However, each new such issue will automatically set the `feature request` label.
In any case, at any time, if necessary, we can [change the templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms): add/remove required fields, add selection fields with multiple options, and even automatically assigning; or add/delete templates for other types of issues. The only thing is that `yaml` is not Turing complete, so we won't be able to put any logic inside it :laughing:

**Comment by JesseTG** [comment]
Looks great! I'd add a field to mention affected cores as well. Maybe something like this:

> **Affected Cores**
> List the affected cores and their versions here, if applicable. If the issue only occurs with a single core then the bug may not be with RetroArch; in that case, you should report it in that core's repository instead of here.

**Comment by viachaslavic** [comment]
@JesseTG  Good suggestion. Added.

**Comment by zoltanvb** [comment]
Looks good, the text could be streamlined a bit:
- "This is only RetroArch bug" -> "This is a bug in RetroArch frontend"
- about the issue search - what do we expect people to do, if they find something that looks relevant? Add a comment, even if it is from 2019? Not sure if that is going to catch attention, at least I rarely switch to "recently updated" issue view
- "Also tell us, what did you expect to happen, and any steps we might use to reproduce the problem." -> "List all steps to reproduce the problem"
- "Try to bisect and tell us when this started happening" -> "Did this work with any older RetroArch version? Can you point to a version (or even commit) where it broke?"
- "The operating system you're running" -> "The system you're running RetroArch on", examples also including "Android 14", "PS Vita"
- I'd remove the compiler question - it is rarely relevant and if it is, usually the reporter is experienced enough to include that information

**Comment by viachaslavic** [comment]
@zoltanvb Thanks, i corrected all the suggestions except the second. I guess even old issues should be considered if they are still relevant. Otherwise, it makes no sense to keep them open. In addition, sometimes someone add a new issue that has recently been resolved but has not yet got into a new release… I left the checkbox, but made it optional, at the user's choice :)

@gouchi  Thanks, I added the field for night build.
> Maybe mention in config.yml for contacts links other Libretro projects like retroarch-joypad, database, assets, shaders ?

Links to other repositories, of course, can be added, but now there are quite a lot of links when trying to open a new issue. I would like this not to scare away. If you want, you can make changes to my branch, as you see.

You also gave me the opposite idea of ​​creating a [repository health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) in which some files would be common to all libretro repositories. (for ex. FUNDING.yml, ISSUE_TEMPLATE/feature-request.md, ISSUE_TEMPLATE/config.yml etc.)

**Comment by viachaslavic** [comment]
> You also gave me the opposite idea of ​​creating a [repository health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) in which some files would be common to all libretro repositories. (for ex. FUNDING.yml, ISSUE_TEMPLATE/feature-request.md, ISSUE_TEMPLATE/config.yml etc.)

Like https://github.com/viachaslavic/bk-emulator/issues/new/choose which has no templates, but inherits from 
https://github.com/viachaslavic/.github

@gouchi @hizzlekizzle @RobLoach what do you think?

**Pull request merged**
