### PR TITLE
Windows long paths fix

### PR DESCRIPTION
**Pull request by mpalomas**
## Description

This fixes some file I/O failures on Windows when paths is longer than 260 characters.
I've used the prefix trick described in https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file section "Win32 File Namespaces".
The thing is, since I have no idea how RetroArch is designed/supposed to work, if there are places *not* using fopen_utf8, then there are some issues left.
Tested with a couple of cores and roms in deeply nested paths, only on Windows 10. No clue about effect on Windows 7 or 8.

## Related Issues

This fixes probably at least some part of #11704 .

### CODE REVIEW

**Comment by twinaphex** [comment]
Looks fine to me. I will do a quick test on this before merging.

RetroArch and libretro cores typically discourage the developer from doing straight fopen calls and instead going through wrapper functions like this precisely to iron out issues like these. In most cases you will find us using compat_utf8.c and this function in particular in many libretro cores.

**Comment by twinaphex** [comment]
Hi, a couple of cleanups still necessary: 

* Declare all variables either at the top of a function or code block, otherwise it won't compile as C89
* Make sure that comments are written in C format instead of C++

**Comment by mpalomas** [comment]
Alright, done. There are CI failures currently, but not due to my changes.

**Comment by twinaphex** [comment]
Unfortunately we noticed some big regressions elsewhere - @Tatsuya79 was no longer able to work with playlists in Qt/Desktop mode, and runahead broke down.

So we have to revert this for now. Hopefully you can come up with a solution again in a future PR, but you'll have to test more parts of RetroArch to make sure these things are not broken in the process.

**Comment by Alcaro** [comment]
From what I can see, \\\\?\\ only works on absolute, canonical pathnames, i.e. no relative paths, forward or double slashes, or . or .. components.

A proper fix would have to canonicalize all of that by itself. I'm not sure if it's worth the effort, long paths are rare.

Maybe it is. Your choice.

**Comment by mpalomas** [comment]
Alright, sorry for that. Obviously "it worked on my machine".
Will see if I can find a proper fix, and if yes, will do more testing and a new PR.

**Comment by SimpleTease** [comment]
Use GetFullPathNameW to convert to absolute name. Then open.

Good example here.
https://stackoverflow.com/questions/38036943/getfullpathnamew-and-long-windows-file-paths/38038887

More helpful and detailed. Also explains how to solve remote UNC shares!
http://arsenmk.blogspot.com/2015/12/handling-long-paths-on-windows.html

**Comment by Alcaro** [comment]
Doesn't that one have the same MAX_PATH limit that we're trying to bypass?

If not, that certainly is a lot easier than reinventing things. And even if it does, we could probably steal [Wine's implementation](https://github.com/wine-mirror/wine/blob/master/dlls/ntdll/path.c#L627).

**Comment by SimpleTease** [comment]
From what I understand, we need to do this:
```
len = GetFullPathNameW(name,0,null,null)
if len 0, return 0;

allocate wchar_t buffer (len+4) // maybe 5+
if (!GetFullPathNameW(name, len, buffer, null)) {
  free buffer
  return 0;
}

might have to use GetLongPathNameW if we have short names ...
prefix "\\?\" or handle UNC shares

now open file
```

 I should try it myself but both claim to go 32767 chars.

**Comment by SimpleTease** [comment]
Still figuring this out. Only does slow conversion if we're past MAX_PATH. So many annoying cases to deal with: short, long, this, that, errors.

**Comment by mpalomas** [comment]
Thanks for your input. I have implemented the strategy used in the blog you mentioned (supports UNC and short paths).
Have not done extensive testing yet, bear with me, like many, I'm on holidays :)
But indeed it's baffling on Windows how many edge cases for a such thing thing we have to deal with...

**Pull request merged**
