### PR TITLE
(RGUI) Overhaul custom theme interface + add wallpaper support

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

The current mechanism for specifying custom colours in RGUI is unworkable:

- It is not realistically possible to enter custom colour values via the menu

- Editing the text/background/border colours in `retroarch.cfg` is unwieldy, and only allows for one custom 'theme' to be saved at a time.

This pull request does away with the existing RGUI 'custom colour' settings, and instead establishes a new 'theme preset' configuration file (e.g. `my_theme.cfg`). This has the following contents:

    rgui_entry_normal_color = "0xAARRGGBB"
    rgui_entry_hover_color = "0xAARRGGBB"
    rgui_title_color = "0xAARRGGBB"
    rgui_bg_dark_color = "0xAARRGGBB"
    rgui_bg_light_color = "0xAARRGGBB"
    rgui_border_dark_color = "0xAARRGGBB"
    rgui_border_light_color = "0xAARRGGBB"
    rgui_wallpaper = "wallpaper_file.png"

This also adds wallpaper support. `rgui_wallpaper` is the (relative) path to a suitable wallpaper file. If it is omitted (or left empty), no wallpaper is used. Wallpaper files must have the following properties:

- A resolution of exactly 320x240.

- They must be pre-converted to a reduced colour depth of 4 bits per pixel.

(NB: Normal background/border colours are still used for message boxes and the title background when showing thumbnails - it looks better this way!)

Theme preset files can be loaded via a new 'Custom Menu Theme Preset' option under 'User Interface > Appearance'. They are enabled by setting 'Menu Color Theme' to 'Custom'.

I've thrown together a small collection of (rough) themes which can be downloaded here: https://github.com/jdgleaver/rgui_themes. I need to tidy this up (some of the text colours are bad), and I still have a number of themes to add, but I wanted to get this PR out first. Clone the repo, and copy the `rgui` folder to your assets directory (or anywhere, I guess). Here are some screenshots of what the included `.cfg` files look like:

screenshot_2019-01-29_16-56-52

screenshot_2019-01-29_16-57-23

screenshot_2019-01-29_16-57-36

screenshot_2019-01-29_16-57-49

screenshot_2019-01-29_16-58-02

screenshot_2019-01-29_16-58-14

screenshot_2019-01-29_16-58-27

screenshot_2019-01-29_16-58-38

screenshot_2019-01-29_16-58-49

screenshot_2019-01-29_16-59-00

I think with this PR, we've pushed RGUI as far as it will go...

(On an unrelated note, we really need some documentation explaining how to add file path menu entries. This was an absolutely horrible thing to reverse engineer...)

### CODE REVIEW

**Comment by twinaphex** [comment]
I absolutely love all the other changes, but on the subject of being able to edit the menu colors I am a bit torn. The reality is that most regular endusers will have no clue how to edit a config file to make those changes. Can't you still provide something to them so that they will be able to do this in-app and then be able to create a new config theme file that way? I'd be fine with merging this if you promise to investigate this as a separate PR later on.

**Comment by orbea** [comment]
My main suggestion is that it the config file should parse something more recognizable like color hex codes.

https://www.color-hex.com/

**Comment by twinaphex** [comment]
@hizzlekizzle Yeah that is true, they currently can't be edited in-app.

**Comment by twinaphex** [comment]
OK, let's merge this then.

**Comment by RobLoach** [comment]
Would love to see more configuration moved in the assets space. Will these live in [retroarch-assets](https://github.com/libretro/retroarch-assets)? If we provide sane defaults, then people could build upon them.

**Comment by twinaphex** [comment]
@jdgleaver I don't really like how the user cannot individually select the wallpaper easily and has to go through this song and dance of loading a config file first.

Can we have a setting like XMB and MaterialUI where you can just select the wallpaper through a file picker? That's all I'm really asking for here.

**Comment by jdgleaver** [comment]
Well, that generated a lot of comments... :slightly_smiling_face: 

Let's try to address them in order:

About removing the custom colour menu options: @hizzlekizzle is completely correct - the old options were just config file placeholders, and thus pointless. If we want to edit colours via the menu then we need a proper colour chooser widget - I think this would be quite difficult to implement given RGUI's limitations (and I'm not sure I'd want to invest the time it would take!).

@orbea: The values in the config file actually are colour hex codes (although with an extra byte at the beginning for alpha). Sorry I wasn't clear about that!

@RobLoach: I debated about whether to make a pull request adding some themes to `retroarch-assets`, but things can get sticky with image licencing issues. With the exception of the two CRT images, everything I've included is okay for commercial use with modification (but not necessarily compatible with the current `retroarch-assets` license). The CRT images are from here: https://github.com/TreyM/classic-crt-collection, which is a collection of RetroArch overlays, so I don't think anyone would object to them being used in this way (but the licensing is not clear). I guess the point I'm trying to make is that anything in `retroarch-assets` would have to be bullet proof in terms of usage rights, so I think someone more knowledgable in such things would have to make some sensible 'default' themes...

@twinaphex:

> I don't really like how the user cannot individually select the wallpaper easily and has to go through this song and dance of loading a config file first.
>
> Can we have a setting like XMB and MaterialUI where you can just select the wallpaper through a file picker? That's all I'm really asking for here.

I get your point completely, but there are a couple of issues here:

1. You are perhaps unaware (and quite rightly so!) of how awkward it is to make RGUI wallpapers. The limited colour depth is generally okay for screenshots, but try to use general wallpaper-type images (or anything with smooth gradients, or anything with solid blocks of certain colours) and the whole thing turns to crap. Some careful preparation is required. I mean, it's not technically difficult per se, but the kind of user who can't edit a simple config file isn't going to be able to do it - and when that kind of user tries loading any old junk and gets terrible results, they're just going to complain about it online... (this is why I didn't bother supporting non-320x240 images - it's kind of a first-level barrier to entry, intended to prevent non-preprepared wallpapers...)

2. XMB at least is in quite a different sort of situation - by default (and I doubt anyone changes this!), all text is white with a nice shadow. Like subtitles in a movie, this kind of text is legible against any type of background image (light or dark, busy or plain), so it makes sense to allow easy loading of generic wallpaper. With RGUI, there are three shades of text and no shadows, so the individual text colours have to be chosen specifically to compliment the background. For example, look at my 'Pinball Arcade.cfg' screenshot - I didn't have time to tune this properly yesterday, and the text looks **bad** (I'll fix this later). Basically, it's not as simple as just 'loading a wallpaper' - and without the ability to change text colours *easily* via the menu, I don't think having a wallpaper file picker is of much benefit to the user. (And imagine noobs on the forum - "Halp! I loaded a wallpaper the same colour as the text and now I can't see anything. What do?")

Heck, I can add the option if I really have to, but I don't see a convincing argument for it. I'd rather that less technical users just load themes made by people who know what they're doing - it makes for a much better user experience... :slightly_smiling_face: 

Once I've finished with my own themes, I'll try to find time to update the RGUI documentation, including some info on how to create wallpapers + configs. I guess I'll then make a post about it on the forums, and maybe some talented users will step up and make nice themes for everyone...?

**Comment by jdgleaver** [comment]
Ran out of time today, but managed to add two more themes to https://github.com/jdgleaver/rgui_themes:

screenshot_2019-01-30_17-01-59

screenshot_2019-01-30_17-02-31

**Pull request merged**
