### PR TITLE
accept playlists with Unix and Windows style line endings

### PR DESCRIPTION
**Pull request by markwkidd**
I could use help testing this patch across platforms in order to make sure it works as intended.

### CODE REVIEW

**Comment by markwkidd** [comment]
One small update to use strpbrk and keep the code concise

**Comment by Alcaro** [comment]
that drops the first \r or \n, not the last. are you sure you want that?

**Comment by markwkidd** [comment]
Thanks @Alcaro I was trying to get too fancy. I've pushed back my first attempt -- simpler but longer

          if(last = strrchr(buf[i], '\r'))
             *last = '\0';
          else if(last = strrchr(buf[i], '\n'))
             *last = '\0';

**Comment by bparker06** [comment]
Also just FYI I believe some compilers will complain if assignments made in a conditional are not surrounded by quotes.

**Comment by markwkidd** [comment]
@bparker06 thanks. I have a bad habit of not including the extra parenthesis from way back.  Updated.

**Comment by twinaphex** [comment]
What is the current status of this PR? @Alcaro can you review it again? If there is nothing more objectionable to it I'd suggest we start merging it then.

**Comment by Alcaro** [comment]
NULL is a pointer. The character is called NUL.

Other than that, looks good to me.

**Comment by markwkidd** [comment]
That is part of the unchanged code,  correct?  I'm glad to make add that fix in this PR but I wanted to be sure.

**Comment by Alcaro** [comment]
It's in the comment you added.

**Comment by markwkidd** [comment]
Ahhh, I kept looking at the code, and wondering if you meant line 460. Fixed the comment to accuractly use "NUL" rather than NULL

**Pull request merged**
