### PR TITLE
XAudio - threaded audio

### PR DESCRIPTION
**Pull request by IAmBoring**
## Description

Initialize Windows COM system.

## Related Issues

Tested with ChaiLove. Likely affects EasyRPG, Dinothawr.
#8815

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi @SimpleTease , let me know if this fixes the issue you were meaning to address in your prior PR as well.

**Comment by SimpleTease** [comment]
Tried it and it fixes my silent XAudio issue, and has more error-checking to boot. I'm okay with this improved one. +1

**Comment by SimpleTease** [comment]
@IAmBoring 
Oh! Would you mind look into another nasty threading audio issue? When you go into the RA menu and *paused* menu, RA still spams core with callbacks. Which blows up ChaiLove if not caught quickly.

**Comment by SimpleTease** [comment]
I did some research and ... ... here's some commit logs.
- So we used to have `CoInitialize` in `xaudio2` driver itself. https://github.com/libretro/RetroArch/commit/9c75b9cb7f3710579e7f62dc36ca967ac12c73b6
- Which was taken out in favor of placing it in the main thread itself. https://github.com/libretro/RetroArch/pull/7969/commits/0cff7eefa7c7580d22191ad88e44b5531940d642
- Which got moved into `int rarch_main(int argc, char *argv[], void *data)` at some unknown time.
- Causing some possible threaded failures.

And some PR problems:
- Co(Un)Initialize should have guards also `#if !defined(_XBOX) && !defined(__WINRT__)` --> `"FATAL: Failed to initialize the COM interface\n"`
- But it's possible to double call `CoInitialize` in same thread. It will return `S_FALSE` on call 2 but COM is still valid. So XAudio2 still should be allowed to try creation. And we'd still have to `CoUninitialize` the pair in that case.

**Comment by IAmBoring** [comment]
Thanks for the helpful information! I'll redesign everything and submit when I think everything is tested better.

**Pull request closed without merging**
