### PR TITLE
Changes to make keyboard and mouse games more playable

### PR DESCRIPTION
**Pull request by AdrianoML**

### CODE REVIEW

**Comment by twinaphex** [comment]
I like the game focus toggle button. This could indeed make RetroArch much more suitable for use with home computer cores and the like. Thanks for coming up with this.

**Comment by AdrianoML** [comment]
btw, i've just realised i left a nasty debug printf for that commit in command.c

**Comment by twinaphex** [comment]
Yeah, heh, I noticed. Anyway, thanks for this great contribution.

**Comment by AdrianoML** [comment]
I'm also sitting on a giant patchset for tyrquake, which among then has a merge of the sound system from quakespasm into tyrquake that allows for disk file soundtrack rather than CD audio. I haven't looked at it for months and I wonder if you would be interested in such big changes? Other changes include a fix for sound popping, better support for different game packs (like the expansions) and a fix for lookspring (which was stuck on). Anyway I could tidy it all up and do a pull request.

**Comment by twinaphex** [comment]
@AdrianoML That all sounds awesome to hear, definitely don't hesitate to send us a pull request for that, we'd love to merge it!

**Comment by lasers** [comment]
@AdrianoML If you're not occupied with something, could you look into this too?

`Improvement -> Ignore all key events when using a modifier key.` https://github.com/libretro/RetroArch/issues/3796

**Comment by fr500** [comment]
@AdrianoML if it blocks hotkeys... how do you go back to the menu?

**Comment by twinaphex** [comment]
You press the game focus toggle button again, that will change everything back to normal.

I think this is a pretty good solution to the problem we faced with cores that have full keyboard/mouse support which gets in the way of RA's default hotkeys.

**Comment by markwkidd** [comment]
Apologies for butting in, but is this the right group of people to ask about what is necessary to add support for multiple mouse devices?

My understanding is that RA can only support one at the current moment, but it would be nice to have more than one mouse recognized for lightgun games (guns are identified as mice by the OS).

If someone could give a starting point to help me understand the multiple mice issue, I would be grateful.

**Comment by fr500** [comment]
Would need to be addressed in the API first

**Comment by markwkidd** [comment]
@fr500 By that you mean the libretro API I assume? In other words it's not something I'm going to find in the RetroArch codebase?

**Comment by Alcaro** [comment]
[No, it's in here](https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h)

**Comment by markwkidd** [comment]
Thanks. I'm in over my head with this mouse issue, but It's great to have the right starting point.

**Pull request merged**
