### PR TITLE
fix udev light gun issue

### PR DESCRIPTION
**Pull request by grant2258**
This should fix https://github.com/libretro/RetroArch/issues/12973 and https://github.com/libretro/RetroArch/pull/12974  please wait for user response on testing

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi @grant2258 ,

just a headsup that I am leaving this and your other PRs in @jdgleaver 's very capable hands to oversee and review. 

Looks like right now there is a merge conflict that has to be resolved in the meantime first though.

Let me and jdgleaver also know about the testing results by the testers you are talking with.

**Comment by grant2258** [comment]
To honest I will be making another pull request I can't replicate the problem on x. I'm just waiting on some feedback from the user. From what I have gathered it's a relative mouse issue . I have a pi 3 I can test on will look into that more at the weekend.

**Comment by twinaphex** [comment]
Did he report back yet? Also, it seems we have a merge conflict now in both PRs.

**Comment by grant2258** [comment]
https://github.com/libretro/RetroArch/issues/12973 he reported back here @twinaphex but I'm having problems reproducing this. @jdgleaver cam you confirm why we

**Comment by jdgleaver** [comment]
@grant2258 

> can you confirm why we would need to set minx and miiny for a none abs mouse.

No, I'm afraid that I don't really understand this code at all...

I think you are correct that a relative input device should not be making use of absolute values (so min/max x/y should not be set in this case). Nor can I reproduce the issues mentioned in #12973 when using the existing udev driver. So I don't know what is going on....

**Comment by twinaphex** [comment]
@grant2258 Can you check when these additions were made, by whom and for what purpose? Like look at the PR that added it? It might not be needed or it might, I don't know really.

**Comment by grant2258** [comment]
It more a question of the api should be doing we need consistency across drivers. If you probe a pointer (abs device) and it is abs and ra reads it it should return that. If the device is realtive and you probe it with an abs read it should fail like its doing now or should you force it to pretend it relative

**Comment by grant2258** [comment]
am going to close this for now as ill need to actually test whats going on the pi 3 mouse code takes a different path in x. Will restore to what it was with a litttle more clarity and then you guys can decide what to do with it in the future.

**Pull request closed without merging**
