### PR TITLE
Runahead cleanup

### PR DESCRIPTION
**Pull request by Dwedit**
Replaced the new file handling code with the file streams
Hide secondary instance menu item if dynamic libraries are not supported
Remove unlink_utf8 stuff
Fix a compiler warning

### CODE REVIEW

**Comment by Dwedit** [comment]
whoops, gotta remove the utf-8 unlink stuff from the makefile too...

**Comment by twinaphex** [comment]
Thanks a lot. That definitely cleans things up a bit.

**Comment by twinaphex** [comment]
Expanding on this, are some of the functions in memutil.c really necessary?

for instance, malloc_zero - can't we just use calloc there instead? free_str seems to be rather superfluous too.

**Comment by twinaphex** [comment]
Had to push these changes since the function names were wrong in this PR -

https://github.com/libretro/RetroArch/commit/67c3fd88f403317e0a2cee8c6fc229dd9ef9d912

Did you test if this PR still works alright?

**Comment by twinaphex** [comment]
Actually, I don't think this is going to work at all - you should really check if this actually works before sending a PR for this - look at this for instancxe

filestream_write(*tempDllPath, data, dataSize);

Incompatible pointre types passing 'char *' to parameter of type 'RFILE * (aka 'struct RFILE *')

So this code is going to fail hard as it is right now.

**Comment by twinaphex** [comment]
Another issue with the code -

typedef struct retro_core_t retro_core_t; - this happens in a bunch of files -

'Redefinition of typedef '_retro_core_t' is a C11 feature'

We cannot assume C11, it has to work all the way back to C89.

**Comment by twinaphex** [comment]
I fixed the issue I pointed out above by replacing the call with filestream_write_file - 

https://github.com/libretro/RetroArch/commit/0712c0ba998efa081b901a44bf2ab7667e9bef60

Now all that remains is fixing the typedef redefinition issue.

**Comment by Dwedit** [comment]
MSVC build didn't define HAVE_RUNAHEAD so I missed the error.

**Comment by twinaphex** [comment]
I'll start defining HAVE_RUNAHEAD for the MSVC builds.

**Comment by twinaphex** [comment]
OK, MSVC 2003/2005/2010/2013/2015/2017 should all have HAVE_RUNAHEAD defined now.

**Comment by twinaphex** [comment]
See if the code still works fine after this -

https://github.com/libretro/RetroArch/commit/2db0c21f52ebd3d6185d524cbb984273eca99edc

**Comment by twinaphex** [comment]
Pushed commit -

https://github.com/libretro/RetroArch/commit/d04d1c0214ba9ead7457d8467a4cbd78194c242b

**Pull request merged**
