### PR TITLE
[LIBNX] USB mouse support

### PR DESCRIPTION
**Pull request by rsn8887**
## Description

USB mouse support for libnx (Nintendo Switch) platform

## Related Issues

fixed a few int -> unsigned int in loop counters in same file

## Related Pull Requests

none

## Reviewers

Tested working on Dosbox core. Ready to merge I think, but if you want to take a look @m4xw @natinusala

### CODE REVIEW

**Comment by rsn8887** [comment]
Tested working in Dosbox core.

**Comment by natinusala** [comment]
Out of curiosity, does the cursor work in XMB if enabled?

**Comment by rsn8887** [comment]
No.

**Comment by orbea** [comment]
You can enable the mouse by going to `settings -> user interface -> mouse support`.

**Comment by rsn8887** [comment]
No that won't work because Retroarch uses a special device for the menu mouse (RARCH_DEVICE_MOUSE_SCREEN)

**Comment by natinusala** [comment]
Do you think you could implement this device then? Until it has bad side effects I don't see why we would leave it out

**Comment by rsn8887** [comment]
I think I implemented that. Also implemented scaling of mouse coords, so that the mouse doesn't suddenly become super fast in a lo-res game, or super-slow in a hi-res game.

**Comment by rsn8887** [comment]
Ok tested working now both in Dosbox and in XMB menu (after enabling advanced options and enabling mouse).

**Comment by rsn8887** [comment]
I lied I left a useless include statement in there. But now it is ready to merge.

**Pull request merged**
