### PR TITLE
qb: Allow building with a shared lua.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This allows building RetroArch with the system lua instead of the builtin lua, the builtin lua will be default and the configure argument `--disable-builtinlua` must be used to enable the auto detected system lua (If found).

## Reviewers

I have only tested that RetroArch continues to build with the builtin lua, with the system lua and without lua. I have not used retroachievements before nor do I have an account to do so. If someone can test this more thoroughly during run time it would be appreciated.

1. Install lua system wide.
2. `./configure --enable-lua --disable-builtinlua && make`
3. Test retroachievements.

### CODE REVIEW

**Comment by orbea** [comment]
I'm told the lua implementation is not currently in use because it was crashing, I suppose this PR doesn't offer much until it is in use...

**Comment by twinaphex** [comment]
Yeah, can you make lua something that is currently not baked in by default? I am fine with merging the rest of the PR as-is as long as that change is brought about.

**Comment by orbea** [comment]
Yes, I did that. Now it will automatically detect if a system lua is available and build with it if possible. if `--enable-builtinlua` is used then the baked in lua will be preferred.

**Comment by orbea** [comment]
@twinaphex Did I  not understand your request?

**Comment by orbea** [comment]
Nvm, you're just wasting my time and energy again...

**Pull request closed without merging**
