### PR TITLE
add rgui snow

### PR DESCRIPTION
**Pull request by retrotails**
## Description
adds snow to rgui
~~edit: I see it failed some checks, I'll get to that tomorrow~~

most likely needs some changes, it does have a menu option (by grepping and cloning all instances of the shadow menu option lol, which also means some might not be necessary) I'm not sure where it's best for the code/variables in rgui.c to go. also it forces the menu to refresh constantly, and the snow will probably fall at a different speed depending on the framerate. without snow retroarch uses 7% CPU idling in the menu, this only increases that to 8%.

I'm not 100% sure this feature is even desired, but I was going to write it for personal use anyway so here it is.

I mostly made the snow shader for the XMB menu but technically this is my first PR, woo.

### CODE REVIEW

**Comment by orbea** [comment]
This breaks the C89 build, please see travis for logs.

For example with clang.
```
menu/drivers/rgui.c:1560:12: error: variable declaration in for loop is a
      C99-specific feature [-Werror,-Wc99-extensions]
      for (int i = 0; i < 1024; i += 4) {
           ^
menu/drivers/rgui.c:2445:12: error: variable declaration in for loop is a
      C99-specific feature [-Werror,-Wc99-extensions]
      for (int i = 0; i < 1024; i += 4) {
           ^
2 errors generated.
make: *** [obj-unix/release/menu/drivers/rgui.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by hizzlekizzle** [comment]
All this RGUI love lately. What a time to be alive!

**Comment by twinaphex** [comment]
Yeah, just push a fix for C89_BUILD -

menu/drivers/rgui.c: In function ‘rgui_cache_background’:
menu/drivers/rgui.c:1560:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < 1024; i += 4) {
       ^
menu/drivers/rgui.c:1560:7: note: use option -std=c99 or -std=gnu99 to compile your code
menu/drivers/rgui.c: In function ‘rgui_render’:
menu/drivers/rgui.c:2445:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < 1024; i += 4) {
       ^

And we can merge this. Variables need to be declared at either the top of a function or the top of a block.

**Comment by orbea** [comment]
@jdgleaver I know you don't have time now, but when you do it would be nice if you could review this. :)

**Comment by jdgleaver** [comment]
@retrotails This is very cool - nice work!

@orbea Yeah, I can't check this properly until next week, but the following issues stand out:

- Snow will break completely (any may randomly cause a segfault) if it's turned on when using a wallpaper theme (i.e. the `snowflakes` array doesn't get initialised in this case)

- Snow should have the same transparency as the background, not the text (I guess it should have its own colour field, but this is too much work... it's quite easy to tweak the transparency, however)

- Style nits (trivial stuff)

I think it's easiest/best if I fix these things myself when I get back on Monday. I have another little thing I want to add to RGUI anyway, so it's no bother.  :)

**Pull request merged**
