### PR TITLE
Partial fix for issue #6427 - GPU screenshot support on D3D11

### PR DESCRIPTION
**Pull request by miguedevel**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

This is a partial fix for issue #6427 . I say partial because only D3D11 screenshot support is implemented.
Also, this method produces incorrect result if using HDR so it will produce nothing instead.
I tested this on Windows 11 and Windows 10 one with NVIDIA GPU and another with AMD GPU.
Does this affect Xbox One or UWP???

## Related Issues

Issue #6427 
Issue #14432 (not tested)

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
The D3D11 driver is also used by UWP/Xbox if that's what you mean.

Also it would be nice if we could figure out a way to get it working with HDR too. This could be a good first step towards that though.

**Comment by hizzlekizzle** [comment]
IIRC, Vulkan screenshots don't work with HDR, either.

**Comment by miguedevel** [comment]
Vulkan does support HDR screenshots and according to the code `/* Hdr readback is implemented through format conversion on the GPU */` /shrug

I tried a naive way of just bit-shifting from 10 bits to 8 but it produces a very dim/contrast-less image.

**Comment by LibretroAdmin** [comment]
I'll merge this for now.

I do hope though you'll take the initiative of researching a solution for HDR since it's pretty important in the long run and increasingly more and more ppl will run RetroArch with it enabled.

**Comment by Awakened0** [comment]
I tried a fresh RetroArch build with this but my d3d11 shots are pushed over to the right for some reason.

vulkan:
Mega Man X vulkan
Sonic Adventure vulkan

d3d11:
Mega Man X d3d11
Sonic Adventure d3d11

Using a GTX 4080 on Windows 11. Here's my retroarch.cfg: https://pastebin.com/dZ7yRSGY

I tried defaulting some of the video settings like shader enable, the window position/size, aspect ratio and crop overscan. But the screenshots still came out pushed to the right under d3d11.

**Comment by miguedevel** [comment]
On which cores is this happening on?

**Comment by Awakened0** [comment]
Flycast and bsnes were the ones I tested. Figured I'd do a hardware core and a software one.

**Comment by Awakened0** [comment]
I tried a RetroArch nightly extracted into a new folder without changing settings. In windowed mode, d3d11 GPU screenshots seem to come out fine. But if I go into fullscreen and take another shot it gets pushed over like in my shots above.

**Comment by miguedevel** [comment]
Confirmed it's not working right on fullscreen. Will investigate.

**Pull request merged**
