### PR TITLE
New Lightgun API

### PR DESCRIPTION
**Pull request by hiddenasbestos**
Adds an enhanced lightgun API. Extends the number of available buttons to those found on a Guncon 2, adds absolute screen position input and off-screen query.

Caveats:
* Only dinput driver has been updated to new API
* Input names in localisation strings are all English only 
* Core input remapping not implemented.

Additionally
* Changed naming style of mouse buttons.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there @hiddenasbestos ,

thanks for the PR.

Some warnings that pop up now in Coverity -

https://hastebin.com/nakucafece.coffeescript

Would you be willing to come up with some potential fixes for them? Thanks.

**Comment by hiddenasbestos** [comment]
Hi @twinaphex - took me a while to work out what's going on here. The issue is that now the lightgun binds have been added the value of RARCH_MENU_TOGGLE is greater than 64 so the shift is failing.

A quick fix for this I think is to just move the RARCH_MENU_TOGGLE value up a bit so that it's less than 64 (seems to be at 69 right now). I don't know if anything in the core is relying on the exact values of these constants (it shouldn't imo but I can't say for sure).

A longer term fix might be to add a home button to the retropad and/or rewrite the Wii U code to support 256 binds.

**Comment by orbea** [comment]
@hiddenasbestos There are also some new warnings with gcc, can you fix them? :)
```
input/connect/connect_ps4.c: In function 'hidpad_ps4_get_buttons':
input/connect/connect_ps4.c:213:47: warning: left shift count >= width of type [-Wshift-count-overflow]
    buttonstate |= (rpt->btn.ps ? (UINT64_C(1) << RARCH_MENU_TOGGLE)             : 0);
                                               ^

input/connect/connect_wiiupro.c: In function 'hidpad_wiiupro_get_buttons':
input/connect/connect_wiiupro.c:147:53: warning: left shift count >= width of type [-Wshift-count-overflow]
    buttonstate |= (rpt->btn.home     ? (UINT64_C(1) << RARCH_MENU_TOGGLE)             : 0);
                                                     ^
```
```
dbd9bf3b46c5ab8b2eaefa6cb6ec3dc53bd7b504 is the first bad commit
commit dbd9bf3b46c5ab8b2eaefa6cb6ec3dc53bd7b504
Author: David Walters <contact@davidwaltersdevelopment.com>
Date:   Sun Nov 26 16:59:48 2017 +0000

    New lightgun binds

:100644 100644 6a999a0e32ee81c3bc7f83b273189ca0f7a3ab82 b7f0a32e86a06a8110def245f324309f5bebd853 M      config.def.keybinds.h
:040000 040000 f7b6b0332244325838e3ab4b1be468a12cb5aa0b d28ddc2827bd5658decfa2380923da1fc2f7a4fb M      input
```
dbd9bf3b46c5ab8b2eaefa6cb6ec3dc53bd7b504

**Comment by hiddenasbestos** [comment]
This bug is caused by a side-effect of adding >64 binds and the connect input code bursting its banks. Not this commit itself.

I'll take a look -- I have a PS4 controller and official dongle (no WiiU pro controller though), but doesn't seem to sync to RetroArch on Windows atm when I set the HID driver. Any hints? If not i'll take a stab at it and put it up for testing / review.

**Comment by orbea** [comment]
Unfortunately not, I don't have the either of those gamepads.

**Comment by hiddenasbestos** [comment]
Okay @orbea and @twinaphex - I've submitted pull request #5809 to fix this stuff. Now hopefully someone can test it.

**Comment by hiddenasbestos** [comment]
@twinaphex the true pull request is now #5812 which fixes the warning but did require quite a lot of changes once I "pulled the thread".

**Pull request merged**
