### PR TITLE
Add external mouse support and touch screen mouse emulation to Android input driver

### PR DESCRIPTION
**Pull request by diablodiab**
This adds external mouse support to the Android input driver. It also adds support for using the touch screen as mouse in cores with mouse support (eg. ScummVM).

It has been tested with the ScummVM core on:
- NVIDIA Shield TV running Android Nougat 7.0
- NVIDIA Shield Tablet running Android Nougat 7.0
- NVIDIA Shield Tablet running Android Lollipop 5.1
- Huawei Honor 7 running Android Marshmallow 6.0
- HTC Desire 500 running Android Jelly Bean 4.1

It's been tested using the touch screen, a USB mouse/keyboard combo, and a bluetooth mouse.

The Android version running on the device limits the functionality and user experience of the external mouse support.
Android Nougat and/or an NVIDIA SHIELD device with NVIDIA extensions provides the best user experience:

Android API < 14:
- Only left mouse button supported
- The Android mouse cursor will be visible along with the in game mouse cursor
- When the Android mouse cursor hits the edge of the screen it will not be possible to move the in-game mouse cursor further in that direction

Android API < 24 and no NVIDIA extensions available:
- Both left and right mouse buttons supported
- The Android mouse cursor will be visible along with the in game mouse cursor
- When the Android mouse cursor hits the edge of the screen it will not be possible to move the in-game mouse cursor further in that direction

Android API > 23 and/or NVIDIA extensions available (SHIELD devices):
- Both left and right mouse buttons supported
- The Android mouse cursor will be hidden
- The mouse is not limited by the (hidden) Android mouse cursor hitting the edge of the screen

Description of how the the touchscreen mouse support works:
- You can move the in-game mouse cursor using the touch screen. The in-game mouse cursor will move relative to your movements on the touch screen, it will not be centered on where you press the screen.
- One quick tap on the touch screen results in the left mouse button being clicked
- Two taps on the screen and keeping the second tap pressed down results in a left mouse being held down until you release
- Two fingers on the touch screen results in the right mouse button being clicked

The touch screen mouse functionality is active at the same time as overlay support. This might cause some confusion when using cores that are designed for mouse support but where you have also enabled overlay controls. At the top of android_input.c there's a define that can be used to turn off this functionality if it causes more problems than it solves.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Wow, this sounds awesome. I look forward to trying it out!

**Comment by diablodiab** [comment]
I do have to add, that in order to hide the Android mouse you currently need the NVIDIA extensions and you need to launch Retroarch using the "HIDEMOUSE" extra parameter that was added in:
https://github.com/libretro/RetroArch/commit/77e479a8bcb90d01ad679e05c2efd260f693b2e3

**Comment by Ferk** [comment]
Wohh!! Thank you! I've been waiting for this feature for a long time, and it's already merged! I'll test it out as soon as the buildbot produces a nightly

**Comment by t1254362** [comment]
How the touch mode works? I downloaded RetroArch for Android, downloaded ScummVM core and loaded Secret of the Monkey Island (CD VGA DOS version).

RetroPad is displayed, I click "start, start..."  and then a "+" appears at the corner. I can move the "+" with the D-pad, but I touch the screen and it doesn't move. I go to "configuration -> overlay" select scummvm, all icons dissapears (except one) but I can't do nothing more (because touch doesn't do nothing and D-pad dissapears).

**Pull request merged**
