### PR TITLE
Fix C89_BUILD=1.

### PR DESCRIPTION
**Pull request by orbea**
## Description

Fixes the c89 build again.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi @orbea, can you also look into how we can fix C89_BUILD for Windows? That'd be much appreciated.

**Comment by orbea** [comment]
I'll have to test with travis which makes it much more tedious, but I'll try taking a look later.

**Comment by orbea** [comment]
For reference travis found this so far.
```
gfx/common/win32_common.c:119:4: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   };
    ^
gfx/common/win32_common.c:135:22: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
     } DUMMYSTRUCTNAME;
                      ^
gfx/common/win32_common.c:136:19: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   } DUMMYUNIONNAME;
                   ^
gfx/common/win32_common.c:161:4: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   };
    ^
gfx/common/win32_common.c:172:6: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
     };
      ^
gfx/common/win32_common.c:173:4: error: ISO C90 doesn’t support unnamed structs/unions [-Werror=pedantic]
   };
    ^
```

**Comment by orbea** [comment]
Sorry I'm not sure and it seems risky to change this code without being able to test it beyond compile...

This reference may help.
https://stackoverflow.com/questions/3228104/anonymous-union-within-struct-not-in-c99

**Pull request merged**
