### PR TITLE
Vulkan: Add async compute test core

### PR DESCRIPTION
**Pull request by Themaister**
Dummy raymarch compute shader that someone can improve.
Test core uses semaphore and multiple queues to overlap compute and shading in frontend.

### CODE REVIEW

**Comment by twinaphex** [comment]
I get this when trying to compile the test core:

../../libretro-common/include/vulkan/vulkan_symbol_wrapper.h:326:8: error: unknown type name 'PFN_vkDebugMarkerSetObjectTagEXT'
 extern PFN_vkDebugMarkerSetObjectTagEXT vulkan_symbol_wrapper_vkDebugMarkerSetObjectTagEXT;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libretro-common/include/vulkan/vulkan_symbol_wrapper.h:328:8: error: unknown type name 'PFN_vkDebugMarkerSetObjectNameEXT'
 extern PFN_vkDebugMarkerSetObjectNameEXT vulkan_symbol_wrapper_vkDebugMarkerSetObjectNameEXT;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libretro-common/include/vulkan/vulkan_symbol_wrapper.h:330:8: error: unknown type name 'PFN_vkCmdDebugMarkerBeginEXT'
 extern PFN_vkCmdDebugMarkerBeginEXT vulkan_symbol_wrapper_vkCmdDebugMarkerBeginEXT;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libretro-common/include/vulkan/vulkan_symbol_wrapper.h:332:8: error: unknown type name 'PFN_vkCmdDebugMarkerEndEXT'
 extern PFN_vkCmdDebugMarkerEndEXT vulkan_symbol_wrapper_vkCmdDebugMarkerEndEXT;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../libretro-common/include/vulkan/vulkan_symbol_wrapper.h:334:8: error: unknown type name 'PFN_vkCmdDebugMarkerInsertEXT'
 extern PFN_vkCmdDebugMarkerInsertEXT vulkan_symbol_wrapper_vkCmdDebugMarkerInsertEXT;

**Comment by Themaister** [comment]
Update your Vulkan headers.

**Comment by twinaphex** [comment]
Apparently the latest vulkan-headers in Arch LInux' community repos are not recent enough then.

We can't define this somewhere for all of the people that won't be having such recent Vulkan drivers?

**Comment by Themaister** [comment]
There are builtin headers that are recent enough in the RA repo, so -I-ing that folder might work to avoid using global header.

**Comment by twinaphex** [comment]
OK, that worked. Should we maybe move these builtin headers to libretro-common or do you prefer we keep them inside RetroArch?

**Comment by twinaphex** [comment]
BTW @Themaister, Vulkan doesn't work at all for me anymore on my Ivy Bridge laptop.

I think this has something to do with the most recent changes.

RetroArch [ERROR] :: [Vulkan]: Failed to load device symbols.

**Pull request merged**
