### PR TITLE
libnx: Reuse deprecated HID APIs

### LINKED ISSUE #12685: Nintendo Switch - Only first player controller is detected
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When connecting 2 or more controllers to retroarch, only the controller assigned to player 1 in the switch OS is actually read by RetroArch. 

### Expected behavior

Every controller should be read in each corresponding slot

### Actual behavior

Only player 1's controller is read.

###This Doesn't happen on RetroArch 1.9.4 on the switch, haven't tried 1.9.5

### Steps to reproduce the bug

1. Use RetroArch 1.9.6 on the switch
2. Connect a second controller on switch os
3. Try to use it

- RetroArch: 1.9.6

### Environment information

- OS: Atmosphère 19.5 with OFW 11.0

### PR DESCRIPTION
**Pull request by R-YaTian**
## Description

Reuse deprecated HID APIs on libnx/switch. This should fix some input issues.
Compiling with [m4xw's custom libnx](https://git.m4xw.net/Switch/RetroArch/libnx/-/tree/deprecated-features). Tested and works all fine on my console (HOS 12+/AMS 0.19.5)

## Related Issues

Should fix #12685

## Related Pull Requests

N/A

## Reviewers

@m4xw (sry for ping)

### CODE REVIEW

**Comment by m4xw** [comment]
No, we need to fix it properly.
We missed the case when doing the rewrite.

**Comment by m4xw** [comment]
I will bump the prio, i was under the assumptions its only a issue with split con and not player 2+ in general.

**Comment by R-YaTian** [comment]
> No, we need to fix it properly.
> We missed the case when doing the rewrite.

The problem seems on "button_state[i] = padGetButtons(&pad_states[i])", this only get the first user's input...
And split joycons seems not working without "hidScanInput()"

**Comment by m4xw** [comment]
https://github.com/libretro/RetroArch/blob/master/input/drivers_joypad/switch_joypad.c#L228 woops

**Pull request closed without merging**
