### PR TITLE
Fix rwebinput driver

### PR DESCRIPTION
**Pull request by Yogarine**
input/drivers/rwebinput_input.c:
 -  rwebinput_key_pressed() was defined twice. Not sure why, but removed the first instance of it.
 -  in rwebinput_input_state() the device was hardcoded to INPUT_DEVICE_TYPE_NONE which would result in it always returning 0

### CODE REVIEW

**Comment by twinaphex** [comment]
Thanks for this.

Does the Emscripten port work with these patches again?

**Comment by Yogarine** [comment]
It does for me. :-)

Only tested it with snes9x_next for now though, but no reason to believe it won't work with the other cores.

**Comment by twinaphex** [comment]
Good to hear. Thanks a lot for this.

**Comment by fr500** [comment]
@Yogarine it doesn't seem to work, I just built with the latest SDK and no inputs register 
http://bot.libretro.com/.radius/template.html

**Pull request merged**
