### PR TITLE
libnx: fix swkbd indefinitely showing up

### LINKED ISSUE #9909: [SWITCH] 1.8.2 Unable to to input user/pass for retro achievements (or: keyboard input broken)
## Description
When I try to input the username or password the keyboard does not disappear and the input is not entered. 

### Expected behavior
Keyboard should disappear after input is recognized and entered. 

### Actual behavior
Keyboard does not disappear and the input is not entered. Keyboard is always reappearing. 

### Steps to reproduce the bug

1. Open retroarch
2. Go to settings
3. Go to achievements
4. Switch "Achievements" on
5. Enter either username or password.

### Bisect Results
After the update to 1.8.2 

### Version/Commit
1.8.2 Switch

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

### LINKED ISSUE #9922: Keyboard crashes app on Switch
On the Switch app, when the keyboard opens it cannot be closed (trying to exit it will result in it opening again, over and over) the only way to get out of this keyboard is to go to the home menu and close the app, which will make the Switch display the app crash message (application was closed due to an unexpected error)

Steps to reproduce the bug

1. Open the in-app keyboard at any time
2. Done

- RetroArch: [b6a4564]

- OS: Nintendo Switch 9.1.0/AMS 0.10.1

### PR DESCRIPTION
**Pull request by natinusala**
Fixes #9922 
Fixes #9909

@mtoensing can you confirm it's fixed on your end?

### CODE REVIEW

**Comment by mtoensing** [comment]
@natinusala Where can I download the new binary?

**Comment by twinaphex** [comment]
We just merged it so we need to wait until the next nightly is finished.

The current nightly here is dated -

http://buildbot.libretro.com/nightly/nintendo/switch/libnx/

2020-01-07 17:28

So anything more recent than that should have it.

**Comment by mtoensing** [comment]
I downloaded the 2020-01-08_RetroArch.7z extracted it and copied it over my retroarch folder replacing all files. The problem did not disappear or change.

**Comment by natinusala** [comment]
Was it built before or after my commit?

**Comment by mtoensing** [comment]
Well 2020-01-08 is today so it should contain your changes

**Comment by natinusala** [comment]
Not if the bot started all the builds before pulling my commit

**Comment by mtoensing** [comment]
Ok I will try again today. Is there a specific file I can swap instead of moving the whole folder? This takes forever over FTP. =)

**Comment by natinusala** [comment]
Just move one NRO and run that one specifically, don't load content as it may chainload another core

**Pull request merged**
