### PR TITLE
x11: enable window transparency

### PR DESCRIPTION
**Pull request by bparker06**

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi, looks like there is a conflict that needs to be resolved first.

**Comment by orbea** [comment]
I tested this PR with `xorg-server-1.19.5` and changed the `window opacity` in the video settings to 20, however it did nothing?

**Comment by bparker06** [comment]
@orbea It requires a compositing window manager, and probably RA can't have the "disable compositor" option on either. I tested with Xfce4 and it works there.

**Comment by bparker06** [comment]
@twinaphex The conflicts weren't there when the PR was added, but they're resolved now.

**Comment by twinaphex** [comment]
merged.

**Comment by orbea** [comment]
One of the conflicts was my fault, sorry.

Also for the record this did not work for me because the wm I use, spectrwm, does not have compositing support and likely does not currently work with external compositors. Given this I think there is not much need to fix this in RetroArch.

**Pull request merged**
