### PR TITLE
Ozone: Add thumbnail scale option

### PR DESCRIPTION
**Pull request by realnc**
## Description

Thumbnails in the Ozone menu driver are very small on my screen:

This adds an option that scales the size of the thumbnail sidebar, which in turns means the thumbnails are scaled along with it:

Ideally, the scaling of the thumbnails should be changed so that they watch width, but that's a bit more complicated.

## Reviewers

@jdgleaver @twinaphex

### CODE REVIEW

**Comment by Ryunam** [comment]
Yes! I have been thinking of trying to implement something like this for a long time, but never really found the right state of mind and patience to dabble in the code for this purpose. Glad you beat me to it. 😄

Just a couple things:

1) Since the “thumbnail bar” is also used to display some metadata, such as the playtime log, I am just curious to see how that section looks when the scaling is increased.

2) I am wondering whether it would make sense to change the naming of this option and call it “Right Sidebar Scale”, rather than “Thumbnail Bar Scale”. There are two reasons why I think it would be a good idea:

a. the sidebar in question is already being used to display metadata, as mentioned above;
b. this is more of a future-proof concern: the implementation of the right sidebar in Ozone could be extended to other areas of the menu, for example in the core list, where it could be used to parse and conveniently show at a glance the description of each selected core, as well as lots of other data.

**Comment by jdgleaver** [comment]
Yes, this is a worthy feature :)

In addition to Ryunam's comments, there are a couple of issues that need to be addressed:

- The maximum width of the thumbnail sidebar must be limited to a fixed fraction of the display width (one third, or whatever seems appropriate). With the PR in its current state, it is very easy to make the thumbnail sidebar exceed the entire display width - which breaks the menu quite badly :)
- The content metadata wrapping and placement needs to be adjusted to account for any increases in the sidebar width. In particular, the word-wrapping of the 'last played' text falls down when the width is greater than the nominal (1x) value, and all of the text should be centred or at least offset somewhat such that it doesn't cling to the left hand edge of the bar (which looks very odd when the sidebar is large...)

**Comment by realnc** [comment]
I don't know, "thumbnail bar" sounds pretty intuitive to me. Especially since it shows a "no thumbnail available" message when there's no thumbnail. It's also what it's called in ozone's code.

**Comment by realnc** [comment]
OK, so adapting the metadata display to make it centered turned out to be a can of worms. The text wrap functions from stdstring.h need improving.

For now, I changed the maximum scale factor to just 2x, which prevents the metadata from looking completely out of place. This will have to do for now, until I find the time to fix the text wrapping functions.

**Comment by jdgleaver** [comment]
> For now, I changed the maximum scale factor to just 2x, which prevents the metadata from looking completely out of place. This will have to do for now, until I find the time to fix the text wrapping functions.

That seems like a perfectly reasonable compromise for the time being. I think we should go ahead and merge this as-is - it's a definite improvement on high resolution displays.

**Pull request merged**
