### PR TITLE
Make scanning support .chd files

### PR DESCRIPTION
**Pull request by bkoropoff**
This uses libchdr to look up serials or compute CRCs of `.chd` files.  Because `.chd` files do not preserve the original `.cue`/`.gdi` file, this requires a new set of databases which contain CRCs for the first data track rather than the cue.  I have a branch of https://github.com/RobLoach/libretro-dats which does this for the redump dats.

### CODE REVIEW

**Comment by twinaphex** [comment]
Awesome PR. Let's invite @RobLoach into this conversation to see how you and him can collaborate on the new data sets this will require.

**Comment by twinaphex** [comment]
I also like how you made the database task scanning work through the generic stream interface. Very nice forward thinking there.

**Comment by bkoropoff** [comment]
After some further testing, this probably needs the following changes to merge:

- I found dats where picking the first data track can result in ambiguity.  Picking the *largest* data track is probably a better heuristic.  To be perfect it might be necessary to check *all* tracks, but that looks to be a major change to the database system.
- CHD files created from `.gdi` aren't handled; the metadata tags are different.
- Loose `.gdi` files need to be parsed to find the appropriate data track or scanning will stop working once the databases are updated.

**Comment by twinaphex** [comment]
I think we can merge what you have for now and then wait for future updates from you. LibFLAC/CHD handling is probably something I am going to put behind ifdefs since libflac will be a bit of a big dependency and we like to keep all our options open from a portability/modularity perspective, but the major dominant platforms for RetroArch probably will get libflac and CHD support baked in from now on yeah.

**Comment by twinaphex** [comment]
Also, some minor things I am noticing - 

We will need to use INLINE instead of ínline inside libchdr. I notice that you changed that; that will have to be changed back. I can do that for you. So we essentially need to use retro_inline.h. The reason for using INLINE is that for some targets (like C89), inline did not even exist back then, so we have to be able to optionally stub it out for such targets. And for Windows/MSVC versions, it would be _inline.

**Comment by RobLoach** [comment]
Great work! This will be great for Redump compatibility. Do we need to run another build of the .dats to get this to work?

**Comment by bparker06** [comment]
Just FYI one of these commits (4ead5da) broke netplay and changed the version at the bottom-left of XMB from 1.6.7 to "retroarch". This was due to libflac's use of PACKAGE_VERSION conflicting with RetroArch's, which I fixed in 2c45f0c.

**Comment by bkoropoff** [comment]
Whoops, sorry about that.  The global define namespace is getting a little
crowded with all the third party libraries integrated into the same build
system...

**Pull request merged**
