### PR TITLE
Overhaul content 'Information' menu display

### LINKED ISSUE #8865: feature request: see filepath in the info for a playlist entry
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

sometimes i get duplicate entries and i cant tell which playlist entry i want to delete without using desktop menu or opening the playlist file

### Expected behavior

the info section in the playlist entry to show the filepath for the rom

### Actual behavior

there is no such thing

### Steps to reproduce the bug

not really a bug

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

- OS: win8.1
- Compiler: [In case you are running local builds]

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

At present, selecting `Information` for an item of content via the quick menu just shows the database entry for said item.

This PR changes the `Information` display to show all available content metadata, in addition to the database entry. It looks something like this:

Screenshot_2019-06-06_17-31-08

Where available, the following items are shown:

- Content label
- Content file path
- Currently associated core
- Currently associated database
- Current play time
- Last played time

`Database Entry` is provided as a submenu.

This is particularly beneficial for users who disable menu sublabels (or Ozone users who have both thumbnails turned on), since these users would otherwise have no access to content metadata.

## Related Issues

This closes #8865

## Reviewers

@orbea Little did I know how horrible this would be to implement when I agreed to do it! I would appreciate it if you could give it a test run - I've checked everything and I'm sure it's correct, but I had to dig around in some murky stuff here...

### CODE REVIEW

**Comment by orbea** [comment]
I'll test it by the end of the day. :)

**Comment by jdgleaver** [comment]
Nice - thanks!

(I probably won't get the chance to see your results this evening - but I'll look forward to them tomorrow morning!)

**Comment by orbea** [comment]
I tried this PR and opened an old playlist entry and found it displays this.

PR

Upon selecting this entry RetroArch immediately segfaults. 

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff3d45b66 in __strlen_sse2 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff3d45b66 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007ffff3d32b6e in strdup () from /lib64/libc.so.6
#2  0x00000000007cc7ce in menu_displaylist_ctl (type=DISPLAYLIST_DATABASE_ENTRY, 
    info=0x7fffffffd190) at menu/menu_displaylist.c:5074
#3  0x00000000007a442b in deferred_push_dlist (info=0x7fffffffd190, 
    state=DISPLAYLIST_DATABASE_ENTRY) at menu/cbs/menu_cbs_deferred_push.c:55
#4  0x00000000007a4b6a in deferred_push_rdb_entry_detail (info=0x7fffffffd190)
    at menu/cbs/menu_cbs_deferred_push.c:183
#5  0x00000000007c7826 in menu_displaylist_push (entry=0x7fffffffd228)
    at menu/menu_displaylist.c:3126
#6  0x000000000079a530 in action_refresh_default (list=0x200b3b0, 
    menu_list=0x200b390) at menu/cbs/menu_cbs_refresh.c:34
#7  0x000000000074406d in menu_entry_action (entry=0x7fffffffd390, i=2, 
    action=MENU_ACTION_OK) at menu/menu_entries.c:593
#8  0x00000000007e206c in generic_menu_iterate (menu=0x21370f0, 
    userdata=0x213d520, action=MENU_ACTION_OK) at menu/drivers/menu_generic.c:243
#9  0x000000000073e1f6 in menu_driver_iterate (iterate=0x7fffffffddb8)
    at menu/menu_driver.c:2134
#10 0x000000000045cac6 in runloop_check_state (settings=0x7ffff0593010, 
    input_nonblock_state=false, runloop_is_paused=false, fastforward_ratio=5, 
    sleep_ms=0x7fffffffe050) at retroarch.c:3680
#11 0x000000000045b6f1 in runloop_iterate (sleep_ms=0x7fffffffe050)
    at retroarch.c:4501
#12 0x00000000005fb961 in ui_application_qt_run (args=0x0)
    at ui/drivers/qt/ui_qt_application.cpp:164
#13 0x0000000000454213 in rarch_main (argc=1, argv=0x7fffffffe1d8, data=0x0)
    at frontend/frontend.c:172
#14 0x00000000005fb496 in main (argc=1, argv=0x7fffffffe1d8)
    at ui/drivers/qt/ui_qt_application.cpp:188
```

Full GDB log: [retroarch.log](https://github.com/libretro/RetroArch/files/3264385/retroarch.log)

Before trying this PR I tested this entry with master and found it work as expected, but now that I tried a second time with master I see this.

master

And it still crashes upon selecting that entry with the same backtrace...other entries are unaffected.

I recompiled with `--disable-qt` and it still crashes.

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff540bb66 in __strlen_sse2 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff540bb66 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007ffff53f8b6e in strdup () from /lib64/libc.so.6
#2  0x00000000007303dd in menu_displaylist_ctl (type=DISPLAYLIST_DATABASE_ENTRY, 
    info=0x7fffffffd1b0) at menu/menu_displaylist.c:5074
#3  0x0000000000706bcb in deferred_push_dlist (info=0x7fffffffd1b0, 
    state=DISPLAYLIST_DATABASE_ENTRY) at menu/cbs/menu_cbs_deferred_push.c:55
#4  0x000000000070730a in deferred_push_rdb_entry_detail (info=0x7fffffffd1b0)
    at menu/cbs/menu_cbs_deferred_push.c:183
#5  0x000000000072b3e6 in menu_displaylist_push (entry=0x7fffffffd248)
    at menu/menu_displaylist.c:3126
#6  0x00000000006fc580 in action_refresh_default (list=0x20c2ff0, 
    menu_list=0x20c2fd0) at menu/cbs/menu_cbs_refresh.c:34
#7  0x00000000006a60a9 in menu_entry_action (entry=0x7fffffffd3b0, i=2, 
    action=MENU_ACTION_OK) at menu/menu_entries.c:593
#8  0x0000000000745ff0 in generic_menu_iterate (menu=0x20bbfc0, 
    userdata=0x208f4d0, action=MENU_ACTION_OK) at menu/drivers/menu_generic.c:243
#9  0x00000000006a00f7 in menu_driver_iterate (iterate=0x7fffffffddd8)
    at menu/menu_driver.c:2134
#10 0x00000000004247c0 in runloop_check_state (settings=0x7ffff1ce2010, 
    input_nonblock_state=false, runloop_is_paused=false, fastforward_ratio=5, 
    sleep_ms=0x7fffffffe08c) at retroarch.c:3680
#11 0x00000000004233a5 in runloop_iterate (sleep_ms=0x7fffffffe08c)
    at retroarch.c:4501
#12 0x000000000041bfaa in rarch_main (argc=1, argv=0x7fffffffe1d8, data=0x0)
    at frontend/frontend.c:156
#13 0x000000000041c0b6 in main (argc=1, argv=0x7fffffffe1d8)
    at frontend/frontend.c:184
```
Full GDB log: [retroarch.2.log](https://github.com/libretro/RetroArch/files/3264395/retroarch.2.log)

**Comment by jdgleaver** [comment]
@orbea Thanks - awesome testing as always! That's an incredibly bizarre edge case that I would never have discovered on my own.

What you have here is the peculiar situation of a 'collection' playlist (not history/favourites) with an entry that has a missing label. This would never normally happen - so the condition that checks whether the 'database entry' option should be shown fails. This is actually an old bug that I copy/pasted (it existed long before this PR!) but I guess no-one ever noticed before.

I should be able to fix this easily. Stand by for another commit  :)

**Comment by jdgleaver** [comment]
@orbea Okay, just pushed a commit that does the following:

- Fix cosmetic issues - `Database Entry` is no longer shown if content has a missing label

- Fix underlying logic - the menu_displaylist `DISPLAYLIST_DATABASE_ENTRY` case will no longer segfault/screw up in the event of error conditions

- Fix a stupid `snprintf()` compiler warning (I wish there was a directive to deal with these - like `__attribute__(shut_up_i_know_what_im_doing)`...)

This should be solid now, and ready for further testing  :)

**Comment by orbea** [comment]
Seems all good now. :)

**Comment by jdgleaver** [comment]
Great, thanks for checking!

**Pull request merged**
