### PR TITLE
Menu time/date: Add 12-hour versions of all formats + clean ups

### LINKED ISSUE #8634: [feature request] new time layout/option
Apologies if this is the wrong place.  Several medium's for this and ive found feature requests in all of them.

I noticed in the past several formats for the time in the upper right corner have been added.  However my preferred (and i imagine most americans preferred) has seemingly been missed.

We have an option for month/date/time  but its month/date/military time(24hr) time.

I'd like month/date/12hr time (Hour/Minutes)

I imagine this would be a relatively easy addition, however I also imagine you guys have a "to-do" list that wraps around the block.

Just wanted to get this out there.

Thank you for all your hard work and time!

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

A number of American users have complained that there are insufficient menu date/time formatting options, since we mostly cater for European locales (24 hour clocks + DD-MM-YYYY/YYYY-MM-DD).

This trivial PR adds 12-hour clock versions of all the existing menu time formats, which should be sufficient for our stateside friends. It also cleans up the menu time/date code with format-type enums, so we no longer have arbitrary numbers of arbitrary integers to keep track of,

## Related Issues

This closes #8634

### CODE REVIEW

**Comment by jdgleaver** [comment]
Ah - Travis reports a build error with `DISABLE_MENU=1`

I'll fix that immediately

**Comment by jdgleaver** [comment]
Just pushed a build fix - this should be fine now

**Comment by Awakened0** [comment]
This is cool, I wanted an option for 12 hour time without the seconds displayed, since the seconds changing make the whole string of digits move back and forth a little in ozone :P

Also, I noticed that RGUI only shows HH:MM 24 hour time, no matter what the time setting is set to. I wonder if some of the longer options would fit well in the larger text of that menu driver.

**Comment by jdgleaver** [comment]
@Awakened0

> This is cool, I wanted an option for 12 hour time without the seconds displayed, since the seconds changing make the whole string of digits move back and forth a little in ozone :P

Glad you like it!

> Also, I noticed that RGUI only shows HH:MM 24 hour time, no matter what the time setting is set to. I wonder if some of the longer options would fit well in the larger text of that menu driver.
>
> Edit: Looking at the commit, it looks like you already added changing the time format to RGUI too. Awesome!

Ah, not quite! RGUI still uses fixed 24 hour time.

The issue here is lack of space - since menu sublabels are shown at the bottom of the screen, the space down there is rather precious. If we allowed all the usual time/date formats, the longest would occupy over 40% of the bottom line when using the 4:3 aspect ratio. I think we could maybe allow 12 hour clock selection, and *possibly* day/month.

I'm currently implementing date/time format control for runtime 'last played' info - I'll have a think about RGUI later. I'm also going to add a clock to MaterialUI, which has similar space constraints (i.e. title bar is pretty narrow in portrait mode) - so maybe a common set of 'reduced' time/date options would be useful for both of these menu drivers.

**Pull request merged**
