### PR TITLE
Input binding rework

### LINKED ISSUE #8965: Disabling "Bind Hold" when set to "0" instead of literally setting it to 0 second?
## Description

When "Bind Hold" is set to "0" and you press A on controller (I mean default for enter/accept/OK) it instantly binds this button, so basically every button you'll try to map will be A :x

It means literally 0 second, I think it would make more sense if it meant "disabled" instead. It works if you press Enter on the keyboard and then press the button on your controller, but try the "Bind All" option and you'll see the problem with that: trying to bind a single button will bind multiple at once since the timer gives you 0 second to bind...

### Expected behavior

Just disabling the hold timer when set to "0".

### Actual behavior

Instantly bind the A button.

### Steps to reproduce the bug

1. Go to `Settings > Input`.
2. Set `Bind Hold` to "0".
3. Go to `User 1 Binds` and try to bind any button for your controller.
4. Bonus step: try the `Bind All` option...

### Bisect Results

No idea when it started really, I'd guess since the option exists?

### Version/Commit

- RetroArch: 57c373e1d7

### Environment information

- OS: Windows 10 64bits/Linux 64bits on a VM and 32bits on SNES Classic

### LINKED ISSUE #10276: Input Bind Hold functionality broken
## Description

The "Bind Hold" option under Settings -> Input does not seem to function properly. This option allowed to define a certain amount of seconds that users would have to hold a button for when rebinding any input in the Menu. Instead, this is what is happening right now:

- when setting this option to any number above zero, the outcome is exactly the same. Rebinding any input will just require one press of the button, regardless of whichever value was chosen;
- when setting this option to zero, input remapping stops working. You cannot configure any input (pressing A / Confirm does nothing) and you cannot reset bindings to their default state with the Start button either.

### Expected behavior

When ribinding any input, Settings -> Input -> Bind Hold should effectively control the number of seconds that users are required to hold a button for.

### Actual behavior

Inputs can be configured with a simple press of the chosen button, ignoring the Bind Hold option. Also, setting the option to zero breaks all input rebinding.

### Version/Commit

- RetroArch: 1.8.5 / 8794360b65dfe462c9cf6c5a0ab62ff95f656db1

### Environment information

- OS: Windows 10 x64 - build 1909
- Compiler: mingw64

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

- Made "Bind Hold" work always and not just in Android
  - "Bind Hold" 0 uses current desktop behavior
- Added a "Release all inputs" feature, which only works when Bind Hold > 0, and will also timeout
- Changed keyboard to use states instead of events, in order to capture holding
- Adjusted Timeout and Hold defaults and limits (Really need more maximum?)
- Localized binding message box
- Reformatted bind labels to be more unified
- Changed the bind order to BAYX since B is the universal first button, and everything else goes from left to right
- Removed confusing "(N/A)" suffix with non-autoconf binds
- "Set All" will give up at first timeout instead of forcing to go to the end without the ability to break
- "Set All" uses the same visible bind order instead of internal
- Reformatted controller environment info logging
- Cleaned up tabs and some unused stuff

## Related Issues

Closes #8965
Closes #10276

## Reviewers

@bslenul 

Please test the controller with the "sticky" axis as mentioned in the issue, and also that the new logic feels reasonable, thanks.

### CODE REVIEW

**Comment by sonninnos** [comment]
Hmm, it does not show "Auto" prefix at all here in the box and in the result even when having the existing profile enabled.. Just like "Axis +5" in the case of R2.

Good catch with the dropdown offset, fixed.

**Comment by sonninnos** [comment]
Okeydoke, should be sorted now.

**Comment by bslenul** [comment]
Seems perfect now, haven't noticed any other issue so far 👌

**Comment by markwkidd** [comment]
Nice!

**Pull request merged**
