### PR TITLE
recording improvements

### PR DESCRIPTION
**Pull request by fr500**
Add webm support and gif for recording

I even added a menu entry for threads but for some stupid reason it doesn't show the value, help with that please

### CODE REVIEW

**Comment by 5schatten** [comment]
@fr500 
Well I appreciate your changes but had some ideas how the codec selection could be improved. I tried to clarify the name scheme to make it more obvious which codec is used and added VP9 which was missing. The whole point of my changes is that different device have different feature sets if it comes to encoding. My Skylake only supports VP8 encoding but Kabylake VP9 so if you have hardware support for this code I guess you would want to use the latest encoding standard too.

Unfortunately I have some trouble with the streaming options. If I change them with the cursor it works but if I use the pull down menu I end up with an empty field. Maybe you could have a look at my changes? Feel free to correct me or them und create a PR. 

https://github.com/5schatten/RetroArch/commit/f4e8b4f6d4f64bdc304d0bc29e94582e17e5b7a5

**Comment by fr500** [comment]
It doesn't matter what the processor supports because we are not using
hardware acceleration.

**Comment by 5schatten** [comment]
@fr500 
If it comes to Lakka it does not support recording at all or I don't see how https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/multimedia/ffmpeg/package.mk#L173 since x264 264rgb & libvpx are disabled and no encoders are set so of course it doesn't matter.

Correct me if I'm wrong but Retroarch uses FFmpeg for encoding so it only matters which hardware accelerators are supported by the FFmpeg libs. If you build them for example with libva support it should use VA-API to encode videos and accelerate it. At least it works this way for me.

**Comment by fr500** [comment]
I am not sure, for PC/windows you do have to pick the gpu accelerated codec.

**Comment by 5schatten** [comment]
But it wouldn't hurt to update the name scheme & add VP9 -> so maybe h264 instead of x264 since this points to the encoder not the codec would also be fine. But having the most popular encoders would be great :-)

**Pull request merged**
