### PR TITLE
Adding savestate garbage collector for autoincrement stavestates

### PR DESCRIPTION
**Pull request by davidgfnet**
As some issues indicate (#6195 #10471 #11008 #6861) there's an issue with
the autoincrement save slot feature: slot index will increase and very old
saves won't be deleted.

This commit adds support to delete old save states with a user defined
save state limit (global). Instead of wrapping around the slot counter
it will simply delete the oldest save, since it is simpler.

For now there's a limit of one deletion per save, which ensures a user
cannot delete many saves by accident if they set the limit too low.

### CODE REVIEW

**Comment by i30817** [comment]
@jdgleaver

**Comment by jdgleaver** [comment]
@davidgfnet Thank you for this.

I should let you know that I'll be making significant changes to save states in the next couple of weeks (or thereabouts), so your work here will become redundant at some point - but there's no reason why we can't use it in the meantime.

I'm afraid that I'm struggling to keep up with PRs at the moment, but I'll review your code as soon as possible :)

**Comment by davidgfnet** [comment]
Hey!
Yeah I can imagine things might change for savestates in the future, to make the whole thing better. Feel free to drop it if you have better stuff. I'd ask you to keep the PR around until that happens (just in case your changes never make it you know :P).
Thanks!

**Comment by jdgleaver** [comment]
Okay, I've checked this over - it's fundamentally sound, but there are a few small issues:

- Comments must be C-style, or the C89 build will fail

- Translation files have to updated via Crowdin - regular PRs cannot edit them

- `settings->uints.save_max_keep` should be `settings->uints.savestate_max_keep` (it only applies to save states)

- The textual descriptions in `msg_hash_us.h` are unclear/incorrect - it needs to be obvious that this only applies to save states and only when 'auto increment' is enabled. Also 'oldest' does not necessarily correspond to 'lowest index'

- You didn't wire up `action_left`/`action_right` for `SAVESTATE_AUTO_INDEX`

- `SAVESTATE_MAX_KEEP` has an unnecessary `SD_FLAG_CMD_APPLY_AUTO` flag

- You set the maximum UI display/selection value for `SAVESTATE_MAX_KEEP` to 'unlimited' - this means opening the drop-down list is *very* slow, and will lock up some platforms

- You use `strstr()` in `command_event_set_savestate_garbage_collect()` - this is very slow, and we have better functions in `stdstring.h` (I know you copy/pasted this code from elsewhere, but we should avoid propagating bad practice!)

- `command_event_set_savestate_garbage_collect()` will delete automatic save states! (i.e. `.state.auto`) This is not desirable behaviour...

The following diff should fix these issues: [savestate.zip](https://github.com/libretro/RetroArch/files/5577677/savestate.zip)

Please apply it on top of your PR, then rebase and squash your commits. And of course, double-check that everything still works :)

After that, we should be ready to merge. And certainly - we will keep your changes right up until the new savestate improvements are in place!

**Comment by davidgfnet** [comment]
Patch looks good to me too! Thanks for that!
I did copy everything from the function above, that's why I did not try to improve it.
Did you test your changes? The strstr replacement with that logic is something I cannot tell upfront whether will work or not, but I assume you know more than me :)
Oh and this ("build_list[i].checked = savestate_auto_index;") is how you hide an option that depends on another one? Cool. I thought the text quite obvious, since the option would only appear if auto-index is enabled, but perhaps it's not that obvious.

Thanks a lot!

**Comment by jdgleaver** [comment]
> Patch looks good to me too! Thanks for that!

You're very welcome :)

> I did copy everything from the function above, that's why I did not try to improve it.

Yes, I don't blame you - and I didn't change the original function in my patch either, since that code will disappear entirely in due course! I just wanted to make sure that 'new' code uses the current accepted methods :)

> Did you test your changes? The strstr replacement with that logic is something I cannot tell upfront whether will work or not, but I assume you know more than me :)

Certainly I tested it - but you should test it too, after `git apply`ing the patch, and before pushing the new commit. It's your PR, so it's ultimately your responsibility... ;)

> Oh and this ("build_list[i].checked = savestate_auto_index;") is how you hide an option that depends on another one?

Yep, the way you did it certainly wasn't incorrect - but since we have a standard mechanism for handling cases like that, it was better to switch over to it (twinaphex added the `build_list[i].checked` stuff quite a while ago - it's been incredibly useful!)

> I thought the text quite obvious, since the option would only appear if auto-index is enabled, but perhaps it's not that obvious.

Yeah, I know what you mean - but we have to be quite pedantic with UI text (you never know who's going to be reading it, so it's always best to spell everything out explicitly!)

Anyway, I'm looking forward to getting this merged - it's a feature that should have been there from the start :)

**Comment by davidgfnet** [comment]
Allright! Does look much better now, thanks!
Did some testing and it works great!
Thanks for your help, really appreciated!

**Comment by jdgleaver** [comment]
No problem, happy to help!

@twinaphex This is ready for merging :)

**Comment by twinaphex** [comment]
Thanks very much for your contribution @davidgfnet ! Merged

**Pull request merged**
