### PR TITLE
Change udev driver for dual lightgun support in X11

### PR DESCRIPTION
**Pull request by pjft**
## Description

Dual lightgun inputs (on a "LIGHTGUN" device type isn't fully supported in the X11 code path, it seems, leading to behaviors such as this: https://github.com/libretro/flycast/issues/562 (across multiple emulators that use LIGHTGUN type controller devices). An easy way is to test it with dual mice, in the udev driver in Linux, but a lightgun will yield the same result.

The reason is actually obvious from reading the code: this code path here https://github.com/libretro/RetroArch/blame/1c5f4e1dee5e18d13f9ea6270110e04342738b3c/input/drivers/udev_input.c#L822 does not request the pointer coordinates for any specific instance (i.e. lightgun 1 or 2 or 3 or N), and will always return the same cursor's value, resulting in both lightgun devices controlling the same cursor on screen.

This code change makes multiple lightguns work, but *I do not know if it will break anything from the previous code that was there*, so I am open to feedback or fine-tuning this. I am developing for RetroPie, so I don't know if other X11 systems require the previous/legacy way of retrieving the screen coordinates.

Thanks.

## Related Issues

 https://github.com/libretro/flycast/issues/562

## Reviewers

I am not sure here, but I'd appreciate @twinaphex and @markwkidd 's feedback if possible, as I imagine you're the most familiar with this code. Apologies If I should be tagging others.

### CODE REVIEW

**Comment by pjft** [comment]
Also - apologies -  removed the if(inside) checks as what that resulted in was everytime the gun points outside of the screen, the cursor moves to the middle of the screen, which is awkward. This way at least it stays in the border it left the screen by. 

I don't think it breaks anything from my tests but, once again, feedback appreciated.

Thanks.

**Comment by pjft** [comment]
Hi all,

Apologies for pinging this. I just wanted to ask if there's anything else needed on my end, or any particular question or change I can detail. 

I also see that the Travis CI build failed, but I don't think it's related to these specific changes, so let me know if there's anything on my end that I can help with in this regard.

Thanks for your time.

**Comment by twinaphex** [comment]
Hi there @pjft ,

sorry for the long wait on this. 

Has this been tested on all the respective platforms? On both X11 contexts (GLX and such) as well as non-X11 based? (DRM/KMS).

**Comment by pjft** [comment]
Hi @twinaphex , not a bother and thank you for taking the time.

Alas, the answer is "no", as my only devices are a Raspberry Pi and an Ubuntu laptop, but I can certainly ask for more tests where I can get them and report back if needed.

I tested the following:
- on RetroPie (both with X11 and without X11 set on compile time), using the GL video driver. I believe it's currently using the vc4-fkms-v3d overlay on our end, but I can test others if needed.
- on Ubuntu (the current version, and my PR), using GL, GLCORE, GL1 and SDL2 as video drivers, in windowed and full-screen modes. I take it that these are what you mean by contexts, but if not do let me know and I can test further. I am not extremely savvy in what concerns all these different Linux setups, apologies.

My tests involved plugging in two separate mouse devices (on the Pi, the test was actually run with the mouse devices as well as with two lightguns), setting input drivers to udev and setting the correct mouse indexes so that the two devices were correctly detected.

On all of these it works as described - prior to the change, the buttons are detected separately but the cursor coordinates are the same for all players, and controlled simultaneously by both (any) mouse devices that are plugged in. With my PR, it works as intended, the cursors are controlled independently - each mouse device controls a unique cursor.

To detail what I did (as I really only removed a small code path, the rest was code and variable initializations that were used there and were no longer needed):

```
#ifdef HAVE_X11	
   /* udev->pointer_x and y is only set in X11 */	
   if (!(video_driver_translate_coord_viewport_wrap(	
               &vp, udev->pointer_x, udev->pointer_y,	
               &res_x, &res_y, &res_screen_x, &res_screen_y)))	
      return 0;	
```

If the code was compiled with the HAVE_X11 flag, this would be the default code path for the lightgun coordinates using udev (the only Linux driver that allows multiple mouse devices). If you read this code, if is getting the coordinates based on: viewport (&vp); pointer_x and pointer_y from the udev event; and resolution width and height, but it never makes any specific distinction as far as the actual device it's reading the coordinates from. As such, it is impossible for this code path to be effectively supporting multiple mouse devices.

The alternative code path, though, does get the specific coordinates for the individual mouse devices:

```
udev_input_mouse_t *mouse   = udev_get_mouse(udev, port);
(...)	
#ifdef HAVE_X11
(...)
#else
   res_x = udev_mouse_get_pointer_x(mouse, false);	
   res_y = udev_mouse_get_pointer_y(mouse, false);	
#endif
```

as the mouse parameter is the actual mouse device for the udev port being polled.

My change removed the previous HAVE_X11 code path so that the X11 build runs the same code path as non-X11. 

So, what do I know:
- That single mouse/lightgun coordinates were working before in the different systems I tested;
- That multiple mouse/lightgun coordinates cannot be working in the current HAVE_X11 code path;
- That multiple mouse/lightgun coordinates are working in the X11 contexts I tested it in.

What don't I know:
- What combination of X11 contexts will this new code path not support, if any.

Another tidbit of information:
- This code I'm removing has been there for 3 years and has worked: https://github.com/libretro/RetroArch/commit/c453675d386606871a32fb04af7b1ea3822ebc93
- The code path I'm suggesting us to use in X11 is the code path that @benklop added 5 months ago: https://github.com/libretro/RetroArch/commit/17465462b8a5ad17dcabf052783091a4cb9e39be

From his comment, I believe he added the new code path because some of those values are only filled by udev in X11 (correct), but it doesn't retrieve the coordinates for multiple mouse devices/lightguns. From my tests (which, admittedly, aren't exhaustive), in X11 the new code path using udev_mouse_get_pointer_x and udev_mouse_get_pointer_y seems to also return the correct coordinates, so I'm just proposing to use that code path for this purpose.

The same functions are used in more locations in this code without and #ifdef HAVE_X11 around them, so I'm led to believe that they are fairly context-agnostic. They were added precisely to implement absolute mouse coordinates (https://github.com/libretro/RetroArch/commit/135b636bd42b2ec01cb4cb2dd42f1f7dc4d901c0) which is exactly what we're in need of here.

So that's the summary of my changes.

I removed the (inside) check because, for a lightgun (and some games with off-screen reloading), there is a purpose for still retrieving coordinates off screen, instead of defaulting to centering the cursor.

I hope these help, and do let me know if I can help dig into it further, but given that the previous code path wasn't working for multiple devices anyway, and the new codepath uses calls that are used in other locations for the same purpose, I am hopeful that it is a safe change, and one that just wasn't done by @benklop a few months back because he was fixing the exceptions (the cases that didn't work), but hoped that the current code was fully working (which it isn't in the case of multiple devices).

Happy to have others' feedback, and thanks for the reply. Hope you are doing well.

**Comment by bozothegeek** [comment]
Hi @twinaphex , I confirm that I have also the same difficulty, with build done with "HAVE_X11" on last release 1.9.0, to configure dual lightgun. To explain quickly, we can't have 2 cursors with 2 different colors finally... only one switching between both lightgun. I just success to catch events from lightgun, but I need to set video driver to X11 (ok for that certainly ;-). I will study the @pjft  solution's... I already configured more than 150 games in retroarch.... I have a "little" experience ;-) of lightgun games now and on different cores ! I will keep you informed.

**Comment by bozothegeek** [comment]
Hi @twinaphex , @pjft, I did the update by patching the retroarch 1.9.0 released version and it's confimed, it's working well. I tested on PCs X64 (using X11) and Raspberry PIs (without X11). We have really now the dual lightgun working well in games when X11 is used. For sure, I tested with 1 or 2 lightguns, now the management of cursors is OK on screen as before for platform without X11. Thanks in advance to integrate that in next release.

**Comment by pjft** [comment]
Thank you for testing and for the feedback @bozothegeek .

**Comment by pjft** [comment]
Hi all, and happy new year. I resolved the conflicts that the PR now had with master.

Any further testing needed here, after mine and @bozothegeek went through it in other settings?

Let me know how I can help.

Thanks.

**Comment by pjft** [comment]
Hi all. Hope you're all doing well.

Just pinging this as I had this in my task list, and more people are running into this challenge with dual lightgun setups using Sinden Lightgun. They have to resort to using a pre-compiled older version of RetroArch with this change applied, but I'd rather incentivize people to be running the official RetroArch and keep supporting the project so let me know how I can help move this forward, after @bozothegeek has tested this on top of my initial tests.

Thanks, keep safe.

**Comment by pjft** [comment]
Hi all, happy Friday.

Gently pinging this, let me know if there's anything else needed here.

Regards.

**Comment by markwkidd** [comment]
@twinaphex with the recent stable release complete, would you consider merging this PR? Is there any additional testing needed?

I'm improving MAME2003+ lightgun support and it would be great if udev/x11 could handle more than one lightgun :D

**Comment by pjft** [comment]
Hi all,

Just checking in on this topic @twinaphex . Anything I can do to help move this along?

Regards, and thanks.

**Comment by bozothegeek** [comment]
Hi All, for your information, we are using this MR as patch in our version of retroarch and it's working very well. Users are happy and it's released since recalbox 7.2 ;-), I advice really to merge this MRnow , the benefit has been confirmed !

**Comment by pjft** [comment]
Thanks @twinaphex for merging this, and @markwkidd and @bozothegeek for the help in testing and pushing this forward.

Have a great week!

**Comment by grant2258** [comment]
It might be worth noting i had no issues with the code as is before this merge with kms using mesa drivers.

**Comment by pjft** [comment]
@grant2258 did something break with the merge with kms using mesa drivers? :|

**Comment by grant2258** [comment]
havent compiled it to test just letting you know the kms mouse worked fine in udev input with x11 enabled for me. I dont really dont think x11 input code paths belong in udev when it has its own drivers input drivers. I 100% agree with that

**Comment by pjft** [comment]
Thanks, got it. Good to see you around, hope you're doing well!

**Comment by grant2258** [comment]
yea its been a while all is well here hope things are good your end too!

**Pull request merged**
