### PR TITLE
Special functions for core serialization

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**
## Description

This should make the code nicer and avoid future problems when forgetting to wrap those calls.

## Reviewers

@barbudreadmon (don't think this needs any special reviewing, but you were the last one to edit them)

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Looks like the Github actions are finally being put to good use and they are finding some errors in the PR.

**Comment by Cthulhu-throwaway** [comment]
Ops, forgot to wrap the new function around a HAVE_NETWORKING || HAVE_RUNAHEAD macro, which is why it's failing for some of the esoteric platforms.

Should just make "request_special_savestate" visible to all platforms though, this way the new functions still work for them, even if they won't do anything special.

**Comment by LibretroAdmin** [comment]
> 

Alright, go ahead with that.

**Comment by Cthulhu-throwaway** [comment]
Done!

**Pull request merged**
