### PR TITLE
(Netplay/LAN Discovery) Support for IPv4 tunneling (6to4)

### PR DESCRIPTION
**Pull request by Cthulhu-throwaway**
## Reviewers

@fr500

### CODE REVIEW

**Comment by fr500** [comment]
I'll build this tonight when I get home

**Comment by fr500** [comment]
yup still working

**Comment by Cthulhu-throwaway** [comment]
> yup still working

Think this can be merged? I don't have a platform that I could test this on right now.

**Comment by fr500** [comment]
yeah it still works, no issues so far

**Pull request merged**
