### PR TITLE
(PSL1GHT) Code cleanup

### PR DESCRIPTION
**Pull request by OsirizX**
This should cleanup most of the compiler warnings as seen from this [issue](https://github.com/libretro/RetroArch/issues/15001).

### CODE REVIEW

**Comment by crystalct** [comment]
Hi @OsirizX 
I've looked for rsxSetZMinMaxControl in all the PSL1GHT sources, but it is defined nowhere. Where is it?

**Comment by crystalct** [comment]
rsxSetZMinMaxControl was used in some samples... but i think i was a mistake.... it should be  rsxSetZControl

**Comment by OsirizX** [comment]
@crystalct 
It's defined [here](https://github.com/ps3dev/PSL1GHT/blob/master/ppu/include/rsx/commands_inc.h#L389). All functions there will add rsx to the beginning when librsx is compiled.

**Comment by crystalct** [comment]
I have to update my PSL1GHT....

**Pull request merged**
