### PR TITLE
Hold-to-Bind

### PR DESCRIPTION
**Pull request by hiddenasbestos**
## Description

Implements (although disabled with # if 0 block on line 588 of menu\widgets\menu_input_bind_dialog.c) a hold-to-bind system as an alternative to the current trigger based binding dialog. Requires the user to press and hold a joystick button, axis, hat or mouse button for 2 secs (adjustable with new input_bind_hold setting) before binding completes.

Keyboard inputs are still instantly bound which has the side-effect that a virtual mouse input will implicitly have a lower priority than a virtual keyboard press. This in turn potentially fixes the android virtual mouse + touchscreen keyboard binding conflict issue, albeit accidentally and in a brittle way - however it's the closest I can get to a solution.

I suggest changing the # if 0 to be conditional on Android (or any system with a virtual mouse) for now as traditional desktop systems shouldn't need to have this delay.

## Related Issues

Android virtual mouse + touchscreen keyboard binding conflict. I forgot the number sorry.

## Related Pull Requests

Perhaps has some bearing on #6485 ?

## Reviewers

@twinaphex @Tatsuya79 @fr500

### CODE REVIEW

**Comment by SapphireTactician** [comment]
I don't know how I feel about this idea. If I'm holding down to scroll through the input settings faster, then wouldn't it automatically bind down to whatever I was attempting to scroll past? Wouldn't binding `Retropad B` also be impossible because that's also how you back out of menus and therefore you'd navigate back before the binding can even occur?

**Comment by hiddenasbestos** [comment]
Hi @SapphireTactician the hold-to-bind only applies after the initial press of (A) or Enter to begin binding, it's a modification to the popup that appears not a change to the menu itself.

**Comment by SapphireTactician** [comment]
Oh, I see. Good, I was worried that it'd replace the need to press "A" / Enter initially.

**Comment by fr500** [comment]
This was merged already by another PR I submitted with these commits already there, please close :)

**Comment by hiddenasbestos** [comment]
Cheers

**Pull request closed without merging**
