### PR TITLE
(don't merge) Fixes for input functions using uint64_t

### PR DESCRIPTION
**Pull request by hiddenasbestos**
The input/connect code was based around a 64 bind limit. I've replaced all the get button state calls with a pointer to retro_bits_t which lets them return up to 256 inputs -- typically the home button triggers a menu toggle input.

I've no idea how to test this stuff but it fixes the shift overflow warnings.

### CODE REVIEW

**Comment by orbea** [comment]
I tested this PR and got this build error unfortunately.
```
input/drivers_hid/libusb_hid.c: In function ‘libusb_hid_joypad_get_buttons’:
input/drivers_hid/libusb_hid.c:448:14: error: too few arguments to function ‘pad_connection_get_buttons’
       return pad_connection_get_buttons(&hid->slots[port], port);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from input/drivers_hid/libusb_hid.c:30:0:
input/drivers_hid/../connect/joypad_connection.h:73:6: note: declared here
 void pad_connection_get_buttons(joypad_connection_t *joyconn,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
CC input/connect/joypad_connection.c
make: *** [Makefile:159: obj-unix/input/drivers_hid/libusb_hid.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by hiddenasbestos** [comment]
No problem @orbea I'm working on fixes now and I'll monitor the automated build for further issues.

**Comment by orbea** [comment]
Thanks for working on this, unfortunately there are still build issues and now new warnings.
```
input/drivers_hid/libusb_hid.c: In function ‘libusb_hid_joypad_button’:
input/drivers_hid/libusb_hid.c:466:59: error: expected ‘;’ before ‘)’ token
   return (RARCH_INPUT_STATE_BIT_GET(buttons, joykey)) != 0);
                                                           ^
input/drivers_hid/libusb_hid.c:465:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if ((port < MAX_USERS) && (joykey < 32))
  ^~
input/drivers_hid/libusb_hid.c:466:59: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   return (RARCH_INPUT_STATE_BIT_GET(buttons, joykey)) != 0);
                                                           ^
input/drivers_hid/libusb_hid.c:466:59: error: expected statement before ‘)’ token
input/drivers_hid/libusb_hid.c: At top level:
input/drivers_hid/libusb_hid.c:632:4: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    libusb_hid_joypad_get_buttons,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_hid/libusb_hid.c:632:4: note: (near initialization for ‘libusb_hid.get_buttons’)
make: *** [Makefile:158: obj-unix/input/drivers_hid/libusb_hid.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by hiddenasbestos** [comment]
When I was at school my computing teacher would tell us stories of sending off punch cards to be executed and they'd get a result or, more often, an error report a week later. Here I am 20 years later ...

**Comment by orbea** [comment]
It compiles now! Just one new warning.
```
CC input/drivers_hid/libusb_hid.c
input/drivers_hid/libusb_hid.c:632:4: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    libusb_hid_joypad_get_buttons,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_hid/libusb_hid.c:632:4: note: (near initialization for ‘libusb_hid.get_buttons’)
```
Also, before this is merged could you rebase the PR against master and squash the build fixes? It will help future bisects to not have to skip commits. :)

**Comment by orbea** [comment]
Actually I commented before the new commits...
```
input/drivers_joypad/hid_joypad.c: In function ‘hid_joypad_get_buttons’:
input/drivers_joypad/hid_joypad.c:61:14: error: too few arguments to function ‘generic_hid->get_buttons’
       return generic_hid->get_buttons((void*)hid_driver_get_data(), port);
              ^~~~~~~~~~~
make: *** [Makefile:158: obj-unix/input/drivers_joypad/hid_joypad.o] Error 1
make: *** Waiting for unfinished jobs....
CC input/connect/connect_ps2adapter.c
```

**Comment by hiddenasbestos** [comment]
Yeah @orbea turns out pulling on this thread has affected quite a lot of uint64_t based functions. Good news is it will, I think, ultimately mean any controller/input device can report the full gamut of possible bindable controls. The principle one is the PS / home / guide button on 7th+ gen consoles.

**Comment by orbea** [comment]
```
In file included from input/drivers_hid/null_hid.c:19:0:
input/drivers_hid/null_hid.c: In function ‘null_hid_joypad_get_buttons’:
input/drivers_hid/../input_defines.h:165:49: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_hid/null_hid.c:46:4: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
    RARCH_INPUT_STATE_CLEAR_PTR(state);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_hid/../input_defines.h:165:49: warning: incompatible implicit declaration of built-in function ‘memset’
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_hid/null_hid.c:46:4: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
    RARCH_INPUT_STATE_CLEAR_PTR(state);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_hid/../input_defines.h:165:49: note: include ‘<string.h>’ or provide a declaration of ‘memset’
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_hid/null_hid.c:46:4: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
    RARCH_INPUT_STATE_CLEAR_PTR(state);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
CC playlist.c
CC movie.c
In file included from input/drivers_joypad/../input_driver.h:35:0,
                 from input/drivers_joypad/null_joypad.c:22:
input/drivers_joypad/null_joypad.c: In function ‘null_joypad_get_buttons’:
input/drivers_joypad/../input_defines.h:165:49: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_joypad/null_joypad.c:42:2: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
  RARCH_INPUT_STATE_CLEAR_PTR( state );
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_joypad/../input_defines.h:165:49: warning: incompatible implicit declaration of built-in function ‘memset’
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_joypad/null_joypad.c:42:2: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
  RARCH_INPUT_STATE_CLEAR_PTR( state );
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_joypad/../input_defines.h:165:49: note: include ‘<string.h>’ or provide a declaration of ‘memset’
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_joypad/null_joypad.c:42:2: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
  RARCH_INPUT_STATE_CLEAR_PTR( state );
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
In file included from input/drivers_joypad/../../tasks/../msg_hash.h:26:0,
                 from input/drivers_joypad/../../tasks/tasks_internal.h:34,
                 from input/drivers_joypad/hid_joypad.c:17:
input/drivers_joypad/hid_joypad.c: In function ‘hid_joypad_get_buttons’:
input/drivers_joypad/../../tasks/../input/input_defines.h:165:49: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_joypad/hid_joypad.c:63:7: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
       RARCH_INPUT_STATE_CLEAR_PTR( state );
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_joypad/../../tasks/../input/input_defines.h:165:49: warning: incompatible implicit declaration of built-in function ‘memset’
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_joypad/hid_joypad.c:63:7: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
       RARCH_INPUT_STATE_CLEAR_PTR( state );
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_joypad/../../tasks/../input/input_defines.h:165:49: note: include ‘<string.h>’ or provide a declaration of ‘memset’
 #define RARCH_INPUT_STATE_CLEAR_PTR(a)          memset(a, 0, sizeof(retro_bits_t));
                                                 ^
input/drivers_joypad/hid_joypad.c:63:7: note: in expansion of macro ‘RARCH_INPUT_STATE_CLEAR_PTR’
       RARCH_INPUT_STATE_CLEAR_PTR( state );
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
In file included from input/drivers_joypad/../input_driver.h:35:0,
                 from input/drivers_joypad/parport_joypad.c:29:
input/drivers_joypad/parport_joypad.c: In function ‘parport_joypad_get_buttons’:
input/drivers_joypad/parport_joypad.c:347:32: warning: passing argument 1 of ‘memset’ makes pointer from integer without a cast [-Wint-conversion]
   RARCH_INPUT_STATE_COPY16_PTR(pad->buttons, state);
                                ^
input/drivers_joypad/../input_defines.h:180:56: note: in definition of macro ‘RARCH_INPUT_STATE_COPY16_PTR’
 #define RARCH_INPUT_STATE_COPY16_PTR(a,bits)   {memset(a, 0, sizeof(retro_bits_t));((a)->data[0] = (bits)&0xffff);}
                                                        ^
In file included from input/drivers_joypad/parport_joypad.c:17:0:
/usr/include/string.h:60:14: note: expected ‘void *’ but argument is of type ‘uint64_t {aka const long unsigned int}’
 extern void *memset (void *__s, int __c, size_t __n) __THROW __nonnull ((1));
              ^~~~~~
In file included from input/drivers_joypad/../input_driver.h:35:0,
                 from input/drivers_joypad/parport_joypad.c:29:
input/drivers_joypad/../input_defines.h:180:88: error: invalid type argument of ‘->’ (have ‘uint64_t {aka const long unsigned int}’)
 #define RARCH_INPUT_STATE_COPY16_PTR(a,bits)   {memset(a, 0, sizeof(retro_bits_t));((a)->data[0] = (bits)&0xffff);}
                                                                                        ^
input/drivers_joypad/parport_joypad.c:347:3: note: in expansion of macro ‘RARCH_INPUT_STATE_COPY16_PTR’
   RARCH_INPUT_STATE_COPY16_PTR(pad->buttons, state);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
input/drivers_joypad/../input_defines.h:180:106: error: invalid operands to binary & (have ‘retro_bits_t * {aka struct <anonymous> *}’ and ‘int’)
 #define RARCH_INPUT_STATE_COPY16_PTR(a,bits)   {memset(a, 0, sizeof(retro_bits_t));((a)->data[0] = (bits)&0xffff);}
                                                                                                          ^
input/drivers_joypad/parport_joypad.c:347:3: note: in expansion of macro ‘RARCH_INPUT_STATE_COPY16_PTR’
   RARCH_INPUT_STATE_COPY16_PTR(pad->buttons, state);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:159: obj-unix/input/drivers_joypad/parport_joypad.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by hiddenasbestos** [comment]
Seems to build okay now. Will rebase after sleep!

**Comment by orbea** [comment]
You can always rebase locally and then force push to your branch so you don't have to open several PRs. :)

I can confirm it builds here now with no warnings, thanks!

**Pull request closed without merging**
