### PR TITLE
(ozone) new theme: Hacking the Kernel

### PR DESCRIPTION
**Pull request by fpscan**
image
--
image
--
image

Assets: https://github.com/libretro/retroarch-assets/pull/379

--
@twinaphex 
@RobLoach 
@jdgleaver 
@natinusala

### CODE REVIEW

**Comment by natinusala** [comment]
Are your assets up to date? I think the highlight cursor is the fallback one

**Comment by fpscan** [comment]
> Are your assets up to date? I think the highlight cursor is the fallback one

It should be updated, I changed and send it: https://github.com/libretro/retroarch-assets/pull/379/commits/001f7ed663571322bd2dfc12dcb1c5b73010161f

**Comment by jdgleaver** [comment]
@fpscan Just noticed a small error: the top gradient of the sidebar should fade into the background, just like the bottom one - at the moment it's solid colour.

Other than that, this is a very nice retro theme :)

**Comment by fpscan** [comment]
> @fpscan Just noticed a small error: the top gradient of the sidebar should fade into the background, just like the bottom one - at the moment it's solid colour.
> 
> Other than that, this is a very nice retro theme :)

Ah, thank you so much:) actually it was the thing I intended :) What I was thinking "it starts there and goes beyond(fading away)". If it's wrong I can change .

**Comment by natinusala** [comment]
I don't mind the difference, themes can be ever so slightly different

**Comment by jdgleaver** [comment]
Actually, yes - natinusala is perfectly right :)

I only mentioned the gradient because it's different from what we mentioned on discord - but of course, there are no hard and fast rules regarding themes, and it's all a matter of personal preference. If you want the sidebar to start solid and then fade away, that's fine with me! :+1:

**Pull request merged**
