### PR TITLE
[3DS] Allow sideways screen rotation

### PR DESCRIPTION
**Pull request by justinweiss**
## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

Enables 90 and 270 degree rotation on 3ds. Note that because of the 3ds' low resolution this will likely only work well with integer scaling off / bilinear filtering on.

## Related Issues

#9567 #8754

## Related Pull Requests

[Any other PRs from related repositories that might be needed for this pull request to work]

## Reviewers

[If possible @mention all the people that should review your pull request]

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
oh wow, I didn't think this was even in the realm of possibility, and the implementation is surprisingly straightforward. Good stuff, man :)

**Comment by justinweiss** [comment]
Thanks! It's the first time I've done anything with shaders, so I'm sure there's a better way... but this works :-)

The decreased resolution is a pain, but there's not much that can be done about it unless we used both screens. But that's a much bigger effort, and then you have a hinge right through your screen. So it may not be worth it. Maybe something to try someday.

**Comment by MarioKartFan** [comment]
@justinweiss Hi. Is there a trick to making this menu command appear or is it possible that it’s just not showing up in the latest nightly builds?

**Comment by justinweiss** [comment]
Interesting, it looks like this is considered an "Advanced Setting." That seems weird.

If you turn on User Interface -> Show Advanced Settings, it will show up under Video -> Output -> Video Rotation.

**Pull request merged**
