### PR TITLE
RetroAchievements leaderboards

### PR DESCRIPTION
**Pull request by celerizer**
ra_lboards

The RetroAchievements implementation here had partial leaderboard support so I've added what was needed / what needed to be fixed and enabled them.

- Leaderboards are enabled based on an Achievements settings boolean
- Leaderboards don't trigger in softcore
- Values multiplied by nothing are correctly parsed
- Leaderboard memaddrs are patched based on console like cheevos
- Support for '$' operator added
- Human-readable formatting for LB values

Some typedefs related to Rich Presence Script are here as well but aren't used at the moment, I wanted to include them both as one PR but decided to add just leaderboards for now.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there @celerizer ,

nice PR. I will invite @leiradel to the discussion since he has done a large part of the cheevos work so far, so I'd like his input on this PR and whether or not we can merge it as-is or if he still feels there are some unresolved things to address first.

**Comment by orbea** [comment]
One thing that could make these PRs easier to review is if you squashed some of those commits. You can do that with `git remote add upstream https://github.com/libretro/RetroArch/ ; git rebase -i upstream/master` and then changing some of those redundant commits from `pick` to `s` for squash or `f` for fixup which will squash some of those commits into one.

**Comment by leiradel** [comment]
Thanks for the PR, @celerizer . I'll take a look later today.

**Comment by leiradel** [comment]
`cheevos_print_frames`, `cheevos_print_millis`, and `cheevos_print_secs` allocate memory that isn't freed afterwards.

I believe the best approach is to create a `char str[16]` in the caller, and pass a pointer to these functions so they format the value into it.

This way there's no need to `malloc` and `free` things every frame.

**Comment by leiradel** [comment]
`CHEEVOS_CONSOLE_ZX81_SPECTRUM` should be just `CHEEVOS_CONSOLE_ZX81`. The ZX Spectrum is a different machine.

**Comment by leiradel** [comment]
Do leaderboards have multipliers with decimal places?

If they do, does the `multiplier` in `cheevos_term_t` have to be a `double`? Can't it be a `float`?

Maybe @twinaphex have other concerns regarding floating point support on some platforms supported by RetroArch.

**Comment by leiradel** [comment]
`#define CHEEVOS_ENABLE_LBOARDS`

If leaderboards are feature complete, we can get rid of this macro and have them always compiled.

**Comment by leiradel** [comment]
`lboard->format = cheevos_parse_format(cheevos_dupstr(&ud->format));`

Here, `cheevos_dupstr` allocates memory which is not being freed. A better approach would be to pass a pointer to `cheevos_field_t` to `cheevos_parse_format`, and the later can use `strncmp` using the `length` field in `cheevos_field_t`.

The less `malloc`s and `free`s in the code, the better :)

**Comment by leiradel** [comment]
The rest of the code looks good to me.

Thanks again for the PR, leaderboards have been missing in RetroArch for too long :)

**Comment by celerizer** [comment]
I'll clean up the `malloc`s tonight and reupload, then. Thanks for looking it over!

As for the decimals in expressions, the RA emus do support them (I multiply by 1.667 and 3.333 in some of my leaderboards on the site to get correct times). I defined it as `double` here because [RASuite](https://github.com/RetroAchievements/RASuite/blob/8d2836c969a271f3715bc8b02bb8c770eb90a09f/RA_Integration/RA_Leaderboard.h#L22) does as well, but if there are any issues please let me know.

**Comment by leiradel** [comment]
I'll let @twinaphex decide between `float` and `double`, because I believe some platforms may not support `double`. If there are platforms without any floating point support, we can use fixed point.

**Comment by celerizer** [comment]
@leiradel I took what you mentioned into account and pushed again. The multiplier is still defined as a `double` right now.

**Comment by leiradel** [comment]
Awesome, looks good to me, except the address adjustment for the Atari 2600. I believe that, when RA has an emulator for that console, the addresses will come in the 0-0x7f range and will have to be adjusted to 0x80-0xff.

@twinaphex if your ok with using a double in the cheevos, you can merge the PR after `var.c` is fixed.

**Comment by leiradel** [comment]
Ah, there's a `//` line comment that I think some toolchains won't like when compiling the C code.

**Comment by celerizer** [comment]
With Stella's retro_get_memory_data function the values I expect are returned when I look in the 0x00 - 0x7F range and not 0x80 - 0xFF; I don't think an RA emulator is planned for 2600 but if someone starts one I can change this to fit.

**Comment by celerizer** [comment]
Is the comment with an issue the one here?

https://github.com/libretro/RetroArch/pull/5666/files#diff-68d7c6b8f599a82edc68a139cf1e5190R1910

**Comment by leiradel** [comment]
Yes, but if there are others we should change them too

---- On Sun, 12 Nov 2017 01:50:08 +0000 notifications@github.com wrote ----

Is the comment with an issue the one here?

https://github.com/libretro/RetroArch/pull/5666/files#diff-68d7c6b8f599a82edc68a139cf1e5190R1910

**Comment by celerizer** [comment]
There, sorry. Didn't know the comments would cause issues.

Can you give the okay on the 2600 behaviour as well? Regardless of which method an official RA emu would use, the patch gives it the address Stella needs.

**Comment by leiradel** [comment]
Regarding the Atari 2600 address patch, I only add patches for systems that are supported by Retro Achievements. I don't see a reason to do this right now.

**Comment by celerizer** [comment]
Gamelists for 2600 are available on the site to add to; I was planning on including leaderboards that would be RetroArch-only until someone wants to make an RAStella.

I can remove the fix but I probably won't make any LBs if I have to make them wrong on purpose.

**Comment by leiradel** [comment]
Retro Achievements don't use correct memory addresses, that's why they're patched in RetroArch.

In the Atari 2600 case, the RAM is in the 0x80-0xFF range, but if there were a RAStella, and if it reported addresses like all other Retro Achievements emulators, the addresses in the achievements and leaderboards would come in the 0x00-0x7F range.

So if you want to develop leaderboards for Atari 2600 games that would be compatible with a future RAStella, you should use wrong addresses in the 0x00-0x7F range, and adjust them in RetroArch by adding 0x80 to them along with other adjustments being made below the `Patch the address to correctly map it to the mmaps` comment:

```C
else if (console == CHEEVOS_CONSOLE_ATARI_2600)
{
   var->value += 0x80;
}
```

**Comment by leiradel** [comment]
In other words, you must use wrong addresses on purpose, unless a Retro Achievements developer says they can make RAStella use correct addresses for achievements and leaderboards.

**Comment by celerizer** [comment]
You'd have to change the core itself then if you wanted it to work like that.

retro_get_memory_data starting from 0x00:

pit1

retro_get_memory_data starting from 0x80:

pit2

**Comment by leiradel** [comment]
There are three different memory models in play here:

1. `retro_get_memory_data/size`, which just returns a pointer to the memory and its size. It doesn't know anything about addresses.
2. The memory map interface, set by the core using `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`. Here, the correct addresses are reported for each of the memory regions.
3. The Retro Achievements memory view. This is a flat view, usually starting with the System RAM, concatenated with the Save RAM, and maybe concatenated with other important memory from the system. The addresses start with 0 and go up.

Cores must implement model 1 or 2, or both, to be able to work with achievements. RetroArch will use model 2 if the core implements both models. If the core only implements model 1, RetroArch provides a flat view by concatenating memories in the following order: `RETRO_MEMORY_SYSTEM_RAM`, `RETRO_MEMORY_SAVE_RAM`, `RETRO_MEMORY_VIDEO_RAM`, `RETRO_MEMORY_RTC`. This usually works with Retro Achievements' flat model, but sometimes the system is too complex and have other relevant memory types not visible using this interface.

In the Atari 2600 case, Retro Achievements would report the System RAM as a 128-byte memory starting at address 0.

If a core for that system implements model 1, there would be no need to patch anything, because RetroArch presents the flat memory view as described above. Sometimes Retro Achievements present RAM mirrors as if they were real RAM, so with some systems RetroArch checks if an address is inside a mirror range, and brings the address to the actual RAM.

If the core implements model 2, it would report a 128-byte memory starting at address 0x80, which is the correct address for the Atari 2600 System RAM but doesn't match with addresses used by achievements and leaderboards, so addresses would have to be patched by adding 0x80 to them.

I'm not sure if a future RAStella could report the System RAM already in the correct 0x80-0xFF range so that achievements and leaderboards use the correct addresses, but even if it could, the patching would have to be made for model 1 instead of 2. Like I said, the three memory models are different from each other and some kind of adjustment will always be needed, and considering the way all the existing official Retro Achievements work, it would have to be made like I described before.

**Comment by leiradel** [comment]
In short: just remove the address patching from `var.c`, and the Stella core will work just fine with the wrong addresses in the 0x00-0x7F range, which will very likely be the same addresses reported by an eventual RAStella.

If there's a new Atari 2600 core which uses the `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` interface, which will report address in the correct 0x80-0xFF range, I'll add an adress patching for it so it's compatible with Retro Achievements.

**Comment by celerizer** [comment]
Done, hopefully all should be good now

**Comment by leiradel** [comment]
Awesome, thanks!

We can leave the double multiplier BTW, all platforms supported by RetroArch support the double type.

@twinaphex you can merge this PR whenever you see fit.

**Comment by twinaphex** [comment]
Ok, following leiradels suggestion then and merging this,

**Pull request merged**
