### PR TITLE
(ozone) new theme: 1987

### PR DESCRIPTION
**Pull request by fpscan**
image
--
image
--
image
--
check
cursor_noborder
cursor_static
switch
--

Hex
  | #2c8aff | 
  | #50c4fd | 
  | #d599ff | 
  | #febcff | 

@jdgleaver 
@twinaphex 
@RobLoach 
@natinusala

### CODE REVIEW

**Comment by RobLoach** [comment]
There isn't much contrast between the text and the background, making it pretty difficult to read. I'd suggest plugging the values in an accessibility tool like https://contrastchecker.com

In addition, the purple subtext and blue is very close.

**Comment by fpscan** [comment]
> There isn't much contrast between the text and the background, making it pretty difficult to read. I'd suggest plugging the values in an accessibility tool like https://contrastchecker.com
> 
> In addition, the purple subtext and blue is very close.

So this is how it is right now: https://contrastchecker.com/?c=d599ff&b=2c8aff but I guess `#7A30AD` would've better?

--
currently:
image

**Comment by natinusala** [comment]
I second what Rob said, as a colorblind this is unusable for me 🙈

**Comment by jdgleaver** [comment]
Yes, these are pretty colours, but the text contrast is just too low. Readability must always come first in UX design. A little tweaking and I think this will be a nice theme :)

**Comment by fpscan** [comment]
I will talk with jdg tomorrow, so far I have this;

image

it's `#D396FF` 

image

**Comment by askotx** [comment]
That font and background colors are unreadable.

**Comment by fpscan** [comment]
> That font and background colors are unreadable.

Thank you for your feedback

**Pull request closed without merging**
