### PR TITLE
More 'Log to File' Additions

### PR DESCRIPTION
**Pull request by jdgleaver**
## Description

This is a follow up to PR #8511, with the following additions/changes:

- New menu option: `Timestamped Log Files` under `Settings > Logging`. When this is enabled, the output from each RetroArch session will be written to a separate timestamped log file (instead of always overwriting `<log_path>/retroarch.log`)

- Errors are now handled correctly if the specified log file cannot be opened for any reason

- On Android, log files are now flushed after each write (this already happened on other platforms)

- Log to file has been tweaked/tested and is fully working on 3DS

- Default log paths have been added for all platforms (so far, Windows, Linux, Android and 3DS have been verified)

**Notes:**

- @gblues has confirmed that log to file does not work on Wii. I cannot see any reason for this, but I've made a couple of small tweaks that might make some difference (?). It would be great if @gblues could test this again (please reset any existing log file path to default)

- For systems that rely on forking to launch content (mostly console platforms), it's not really practical to log to file anything between `frontend_driver_exitspawn()` and the next read of `retroarch.cfg`. I do not think this will be an issue in practice, however.

- There is a large amount of cleaning up and testing that remains to be done, but I'm kinda at the limit of what I can do myself. We have a mess of `HAVE_NETLOGGER`, `HAVE_LOGGER` and `HAVE_FILE_LOGGER` defines all over the place, each of which change how logging works, and even in the 'regular' `RARCH_LOG_V()` function we have a number of platform dependencies. The `LOGGER` defines at least need to be purged, but this is tricky sticky stuff and since I cannot test all the various platforms this is not something I feel confident about doing. We really need individual platform maintainers to step up and work over the remaining frontend drivers, if we want file logging to be enabled everywhere.

## Related Pull Requests

#8511, #8425

## Reviewers

@twinaphex In adding default log paths, I've edited a number of frontend drivers that I have no way of even compiling. I don't foresee any issues (it's a single line in most cases, just formatting a string),  but I guess caution is advised...

### CODE REVIEW

**Comment by twinaphex** [comment]
Looks good.

@gblues apparently according to the comments, you might want to try again now that this PR has been merged.

**Comment by orbea** [comment]
> There is a large amount of cleaning up and testing that remains to be done, but I'm kinda at the limit of what I can do myself. We have a mess of HAVE_NETLOGGER, HAVE_LOGGER and HAVE_FILE_LOGGER defines all over the place, each of which change how logging works, and even in the 'regular' RARCH_LOG_V() function we have a number of platform dependencies. The LOGGER defines at least need to be purged, but this is tricky sticky stuff and since I cannot test all the various platforms this is not something I feel confident about doing. We really need individual platform maintainers to step up and work over the remaining frontend drivers, if we want file logging to be enabled everywhere.

Is this something that can be done one platform at a time? Or what else could help move this along?

**Comment by jdgleaver** [comment]
@orbea Absolutely, this can be done one platform at a time, and I don't think it should be that onerous (took me 10 minutes to 'fix' the 3DS version, and it only took that long because I wanted to add some extra output to the bottom screen). Basically, for each platform we need to do the following:

- Edit the relevant `platform_*.c` file in `frontend/drivers` to remove all references to `HAVE_LOGGER` and `HAVE_FILE_LOGGER` (typically just removing the code inside these defines)

- Check the `frontend_*_deinit()` function: in some cases, this calls verbosity_enable()/disable() and `command_event(CMD_EVENT_LOG_FILE_DEINIT, NULL);` - in general these two lines may be left in place, after removing any `ifdef` wrappers, but port maintainers should check that they cause no side effects (i.e. some alteration/workaround will be required if anyone wants to capture output after calling `frontend_driver_exitspawn()` on systems that fork)

- Edit the makefiles to ensure that none of `HAVE_NETLOGGER`, `HAVE_LOGGER` and `HAVE_FILE_LOGGER` are set.

This is really not difficult to do, but it needs someone who can compile and test code for each affected platform.

Once the individual platforms are sorted, we can go back to RetroArch in general and purge all remaining instances of `HAVE_LOGGER` and `HAVE_FILE_LOGGER` (which mainly involves removing redundant code from `verbosity.c/.h`, removing references from Makefiles and dropping the old netlogger stuff).

The final step would be to go through the `RARCH_LOG_V()` function and 'standardise' the last two special cases (IOS and XBOX1), and maybe remove the Nintendo Switch nxlink stuff (which I don't think is needed once file logging is enabled).

Again, this is just basic donkey work, but it needs to be tested and tested and tested, because any slip-ups/typos/oversights could completely break RetroArch on a particular platform (hence the need for port maintainers to get involved).

**Comment by jdgleaver** [comment]
@gblues Also, just to confirm, you will need to make sure that both `Logging Verbosity` *and* `Log To File` are enabled.

**Comment by orbea** [comment]
@jdgleaver Thanks for the explanation, do you happen to have a list of platforms which this still needs to be done on? I can only test Linux so I'm not sure I can personally help test here...

**Comment by jdgleaver** [comment]
@orbea I think the full list is as follows:

- Mac (OSX + IOS)

- DOS (Can probably ignore - looks like it's not fully implemented...)

- Emscripten

- NGC + Wii (I've updated the code for these, but still needs testing, and any bugs need fixing if it still doesn't work...)

- PS4

- PS2

- PS3

- PSP (I wouldn't mind doing this one, if someone could point me to the PSP toolchain binaries currently used by the buildbot - I have a toolchain that kinda-sorta works, but it's an absolute headache to use...)

- Vita

- Blackberry

- Nintendo Switch

- UWP (I guess this is XBox One?)

- WiiU

- OG XBox

- XBox 360

It's quite a daunting list...

**Comment by orbea** [comment]
That is a pretty daunting list...

I'm not sure blackberry is maintained or worth maintaining anymore and maybe we can just remove it?

As for DOS, @bparker06 would you want to do this? Otherwise its probably best to ignore since its kind of a novelty platform.

**Pull request merged**
